{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported"},"metadata":{"modules":[{"name":"AutomixIQ"}],"role":"symbol","externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeSdkNotInitialisedVersionNoLongerSupported","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"symbolKind":"case","title":"ErrorCode.sdkNotInitialisedVersionNoLongerSupported","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/errorcode\/sdknotinitialisedversionnolongersupported"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode\/sdknotinitialisedversionnolongersupported"]}],"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/sdkNotInitialisedVersionNoLongerSupported":{"kind":"symbol","role":"symbol","url":"\/documentation\/automixiq\/errorcode\/sdknotinitialisedversionnolongersupported","abstract":[],"title":"ErrorCode.sdkNotInitialisedVersionNoLongerSupported","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/automixiq","title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"url":"\/documentation\/automixiq\/errorcode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/title"},{"op":"replace","value":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/fragments"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle"}]}]}