{"variants":[{"paths":["\/documentation\/socialradio\/automixsdkplaybackeventtype\/trackplayfinished"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixsdkplaybackeventtype\/trackplayfinished"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayFinished"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished"},"metadata":{"symbolKind":"case","role":"symbol","modules":[{"name":"SocialRadio"}],"title":"AutomixSDKPlaybackEventType.trackPlayFinished","externalID":"c:@M@SocialRadio@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeTrackPlayFinished","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayFinished"}],"roleHeading":"Case","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayFinished","kind":"identifier"}]},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/trackPlayFinished":{"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/trackplayfinished","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished","abstract":[],"title":"AutomixSDKPlaybackEventType.trackPlayFinished","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayFinished"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType":{"abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"title":"AutomixSDKPlaybackEventType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayFinished","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayFinished"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayFinished"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AutomixSDKPlaybackEventTypeTrackPlayFinished","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayFinished\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayFinished\/fragments","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/fragments","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}