{"variants":[{"paths":["\/documentation\/socialradio\/socialradiostatus\/playingtrackcurrenttime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiostatus\/playingtrackcurrenttime"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Represents the current playback time of the playing track. If seeking, it reports seek landing time until jump is complete. This should be use on the UI."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"playingTrackCurrentTime","modules":[{"name":"SocialRadio"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"playingTrackCurrentTime"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackCurrentTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioStatus(py)playingTrackCurrentTime"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackCurrentTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus\/playingTrackCurrentTime","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatus/playingTrackCurrentTime":{"navigatorTitle":[{"text":"playingTrackCurrentTime","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus\/playingTrackCurrentTime","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackCurrentTime","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"title":"playingTrackCurrentTime","abstract":[{"text":"Represents the current playback time of the playing track. If seeking, it reports seek landing time until jump is complete. This should be use on the UI.","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiostatus\/playingtrackcurrenttime"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatus":{"navigatorTitle":[{"text":"SocialRadioStatus","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","title":"SocialRadioStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatus","kind":"identifier"}],"abstract":[{"text":"SocialRadioStatus models the State of the AutomixIQ during playback.","type":"text"}],"url":"\/documentation\/socialradio\/socialradiostatus","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"playingTrackCurrentTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"playingTrackCurrentTime","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackCurrentTime"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus~1playingTrackCurrentTime\/title","value":"playingTrackCurrentTime"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus~1playingTrackCurrentTime\/fragments","value":[{"text":"playingTrackCurrentTime","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/title","value":"SocialRadioStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/navigatorTitle","value":[{"text":"SocialRadioStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}