{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"]]},"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"PacemakerRadio"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayStartMixingIntoNext","kind":"identifier"}],"externalID":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext","title":"AutomixSDKPlaybackEventType.trackPlayStartMixingIntoNext","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackPlayStartMixingIntoNext","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplaystartmixingintonext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplaystartmixingintonext"]}],"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlayStartMixingIntoNext":{"type":"topic","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplaystartmixingintonext","title":"AutomixSDKPlaybackEventType.trackPlayStartMixingIntoNext","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayStartMixingIntoNext","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","title":"PacemakerRadio","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType":{"url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype","type":"topic","kind":"symbol","abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"title":"AutomixSDKPlaybackEventType","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayStartMixingIntoNext\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext","op":"replace"},{"value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayStartMixingIntoNext\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/title","op":"replace","value":"AutomixSDKPlaybackEventType"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/fragments","op":"replace","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},{"value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/navigatorTitle"}]}]}