{"variants":[{"paths":["\/documentation\/socialradio\/automixsdkplaylistoperationtype\/added"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixsdkplaylistoperationtype\/added"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType\/Added"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Added","kind":"identifier"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Added","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKPlaylistOperationTypeAdded","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@SocialRadio@E@AutomixSDKPlaylistOperationType@AutomixSDKPlaylistOperationTypeAdded","role":"symbol","title":"AutomixSDKPlaylistOperationType.Added"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperationType/Added":{"url":"\/documentation\/socialradio\/automixsdkplaylistoperationtype\/added","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Added","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType\/Added","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutomixSDKPlaylistOperationTypeAdded","kind":"identifier"}],"title":"AutomixSDKPlaylistOperationType.Added","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperationType":{"url":"\/documentation\/socialradio\/automixsdkplaylistoperationtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"title":"AutomixSDKPlaylistOperationType","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AutomixSDKPlaylistOperationTypeAdded","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKPlaylistOperationTypeAdded","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"AutomixSDKPlaylistOperationTypeAdded","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType~1Added\/title","value":"AutomixSDKPlaylistOperationTypeAdded"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType~1Added\/fragments","value":[{"text":"AutomixSDKPlaylistOperationTypeAdded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/title","value":"AutomixSDKPlaylistOperationType","op":"replace"},{"value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/navigatorTitle","value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}