{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqtunedrestdelegate\/logautomixiqmessage(loglevel:message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqtunedrestdelegate\/logautomixiqmessage(loglevel:message:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Called by AutomixIQ when it wishes to output a log message","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"symbolKind":"method","externalID":"c:@M@SocialRadio@objc(pl)AutomixIQTunedRestDelegate(im)logAutomixIQMessageWithLogLevel:message:","roleHeading":"Instance Method","title":"logAutomixIQMessage(logLevel:message:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logAutomixIQMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"logLevel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQLogLevel","kind":"typeIdentifier","text":"AutomixIQLogLevel"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"SocialRadio"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"text":"AutomixIQLogLevel","preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"logLevel","content":[{"type":"paragraph","inlineContent":[{"text":"The log level.","type":"text"}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message it wishes to log."}]}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQLogLevel":{"type":"topic","title":"AutomixIQLogLevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixIQLogLevel","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"abstract":[{"type":"text","text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels"}],"url":"\/documentation\/socialradio\/automixiqloglevel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate":{"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"url":"\/documentation\/socialradio\/automixiqtunedrestdelegate","title":"AutomixIQTunedRestDelegate","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate/logAutomixIQMessage(logLevel:message:)":{"kind":"symbol","title":"logAutomixIQMessage(logLevel:message:)","url":"\/documentation\/socialradio\/automixiqtunedrestdelegate\/logautomixiqmessage(loglevel:message:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logAutomixIQMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"logLevel","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQLogLevel","text":"AutomixIQLogLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"logAutomixIQMessageWithLogLevel:message:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"logAutomixIQMessageWithLogLevel:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixIQLogLevel","preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel"},{"kind":"text","text":") "},{"text":"logLevel","kind":"internalParam"},{"kind":"text","text":" "},{"text":"message:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The log level.","type":"text"}],"type":"paragraph"}],"name":"logLevel"},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message it wishes to log."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/title","op":"replace","value":"AutomixIQLogLevel"},{"value":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/navigatorTitle"},{"value":"AutomixIQTunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/title","value":"logAutomixIQMessageWithLogLevel:message:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments","op":"replace"}]}]}