{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tunedRestTokenExpired","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"oldAccessToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"refreshToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tokenType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"credentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixIQTunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedAuthenticationResponse","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQTunedAuthenticationResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tunedUserId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"deviceIdentifierForVendor","content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the device.","type":"text"}]}]},{"name":"countryCode","content":[{"type":"paragraph","inlineContent":[{"text":"The ISO2 code of the country the device is located.","type":"text"}]}]},{"name":"tunedUserId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user’s id within the Tuned Global backend."}]}]},{"name":"oldAccessToken","content":[{"type":"paragraph","inlineContent":[{"text":"The expired access token.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The refresh token.","type":"text"}]}],"name":"refreshToken"},{"name":"tokenType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The token type."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}]}],"name":"completion"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/automixiqtunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:refreshtoken:tokentype:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqtunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:refreshtoken:tokentype:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"required":true,"roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tunedRestTokenExpired"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedUserId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"oldAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"refreshToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"tokenType"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"credentials"},{"kind":"text","text":": "},{"text":"AutomixIQTunedAuthenticationResponse","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQTunedAuthenticationResponse"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedUserId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}],"title":"tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","externalID":"c:@M@SocialRadio@objc(pl)AutomixIQTunedRestDelegate(im)tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called by AutomixIQ when initialised against a Tuned Global backend or when its access token has expired."}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedAuthenticationResponse":{"title":"AutomixIQTunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedAuthenticationResponse","abstract":[{"type":"text","text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request"}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQTunedAuthenticationResponse","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqtunedauthenticationresponse","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedAuthenticationResponse"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tunedRestTokenExpired"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedUserId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"oldAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"refreshToken"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tokenType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"credentials"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQTunedAuthenticationResponse","text":"AutomixIQTunedAuthenticationResponse"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedUserId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"}],"kind":"symbol","abstract":[{"text":"Called by AutomixIQ when initialised against a Tuned Global backend or when its access token has expired.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","role":"symbol","url":"\/documentation\/socialradio\/automixiqtunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:refreshtoken:tokentype:completion:)","type":"topic","title":"tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate":{"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"url":"\/documentation\/socialradio\/automixiqtunedrestdelegate","title":"AutomixIQTunedRestDelegate","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"deviceIdentifierForVendor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"countryCode:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"countryCode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tunedUserId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tunedUserId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"oldAccessToken:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"oldAccessToken"},{"text":" ","kind":"text"},{"text":"refreshToken:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"refreshToken"},{"kind":"text","text":" "},{"text":"tokenType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"tokenType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"AutomixIQTunedAuthenticationResponse","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQTunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedAuthenticationResponse","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":{"parameters":[{"name":"deviceIdentifierForVendor","content":[{"inlineContent":[{"type":"text","text":"The unique identifier of the device."}],"type":"paragraph"}]},{"name":"countryCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ISO2 code of the country the device is located."}]}]},{"name":"tunedUserId","content":[{"inlineContent":[{"text":"The user’s id within the Tuned Global backend.","type":"text"}],"type":"paragraph"}]},{"name":"oldAccessToken","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The expired access token."}]}]},{"name":"refreshToken","content":[{"type":"paragraph","inlineContent":[{"text":"The refresh token.","type":"text"}]}]},{"name":"tokenType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The token type."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"AutomixIQTunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedAuthenticationResponse\/title"},{"value":[{"kind":"identifier","text":"AutomixIQTunedAuthenticationResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedAuthenticationResponse\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedAuthenticationResponse\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQTunedAuthenticationResponse"}],"op":"replace"},{"op":"replace","value":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/fragments"},{"value":"AutomixIQTunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/fragments"},{"value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}