{"kind":"symbol","metadata":{"modules":[{"name":"SocialRadio"}],"symbolKind":"method","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioList(im)listLimit","title":"listLimit()","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listLimit","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"listLimit","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList\/listLimit()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The list current limit","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listLimit"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiolist\/listlimit()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiolist\/listlimit()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioList/listLimit()":{"type":"topic","abstract":[{"text":"The list current limit","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList\/listLimit()","title":"listLimit()","role":"symbol","url":"\/documentation\/socialradio\/socialradiolist\/listlimit()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"listLimit","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"listLimit","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioList":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioList"}],"title":"SocialRadioList","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","url":"\/documentation\/socialradio\/socialradiolist","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioList"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"listLimit","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listLimit"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"listLimit"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"listLimit","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList~1listLimit()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listLimit"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList~1listLimit()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/title","op":"replace","value":"SocialRadioList"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/fragments","op":"replace","value":[{"text":"SocialRadioList","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioList","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}