{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"canSkipToPrevious","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSkipToPrevious"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariableCanSkipToPrevious","kind":"identifier"}],"title":"AutomixSDKStatusVariable.canSkipToPrevious","modules":[{"name":"AutomixIQ"}],"symbolKind":"case","externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableCanSkipToPrevious","roleHeading":"Case","role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSkipToPrevious"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/canskiptoprevious"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/canskiptoprevious"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canSkipToPrevious":{"abstract":[],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canskiptoprevious","kind":"symbol","type":"topic","title":"AutomixSDKStatusVariable.canSkipToPrevious","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSkipToPrevious"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSkipToPrevious","navigatorTitle":[{"text":"AutomixSDKStatusVariableCanSkipToPrevious","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","role":"collection","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkstatusvariable","title":"AutomixSDKStatusVariable","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","type":"topic","abstract":[{"type":"text","text":"AutomixIQ status variable type"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AutomixSDKStatusVariableCanSkipToPrevious","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToPrevious"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToPrevious"}]}]},"op":"replace"},{"value":"AutomixSDKStatusVariableCanSkipToPrevious","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canSkipToPrevious\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canSkipToPrevious\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToPrevious"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}