{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailable"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"variants":[{"paths":["\/documentation\/socialradio\/errorcode\/nointernetavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/errorcode\/nointernetavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeNoInternetAvailable","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noInternetAvailable"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailable"}],"roleHeading":"Case","title":"ErrorCode.noInternetAvailable"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailable","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"role":"symbol","url":"\/documentation\/socialradio\/errorcode","title":"ErrorCode","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/noInternetAvailable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailable","role":"symbol","url":"\/documentation\/socialradio\/errorcode\/nointernetavailable","title":"ErrorCode.noInternetAvailable","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailable"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noInternetAvailable"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","url":"\/documentation\/socialradio","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ErrorCodeNoInternetAvailable","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailable"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailable"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1noInternetAvailable\/title","value":"ErrorCodeNoInternetAvailable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1noInternetAvailable\/fragments","value":[{"text":"ErrorCodeNoInternetAvailable","kind":"identifier"}],"op":"replace"}]}]}