{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlistDiff","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/playlistdiff"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/playlistdiff"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Case","title":"AutomixIQStatusVariable.playlistDiff","symbolKind":"case","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@AutomixIQStatusVariable@AutomixIQStatusVariablePlaylistDiff","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariablePlaylistDiff","kind":"identifier"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlistDiff"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable":{"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable","title":"AutomixIQStatusVariable","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playlistDiff":{"title":"AutomixIQStatusVariable.playlistDiff","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylistDiff"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlistDiff","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlistDiff"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/playlistdiff","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AutomixIQStatusVariablePlaylistDiff","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylistDiff"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylistDiff"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/title","value":"AutomixIQStatusVariable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playlistDiff\/title","value":"AutomixIQStatusVariablePlaylistDiff","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playlistDiff\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylistDiff"}],"op":"replace"}]}]}