{"metadata":{"symbolKind":"class","role":"symbol","title":"TunedStoreSettings","modules":[{"name":"SocialRadio"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"TunedStoreSettings"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedStoreSettings","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)TunedStoreSettings"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/init(from:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/automixIQEnabled","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/maxStudioTransitionLength","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/minAutoMixSdkVersion","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/minRadioSdkVersion","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/mqttBrokerAddress","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/socialRadioEnabled"],"anchor":"Instance-Properties","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedStoreSettings"}],"languages":["swift"]}]}],"abstract":[{"text":"Tuned Store settings","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/Se","doc:\/\/org.cocoapods.SocialRadio\/SE","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"type":"conformsTo"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/tunedstoresettings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/tunedstoresettings"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","url":"\/documentation\/socialradio","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings/socialRadioEnabled":{"url":"\/documentation\/socialradio\/tunedstoresettings\/socialradioenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialRadioEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/socialRadioEnabled","navigatorTitle":[{"kind":"identifier","text":"socialRadioEnabled"}],"kind":"symbol","title":"socialRadioEnabled","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings/minAutoMixSdkVersion":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/minAutoMixSdkVersion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minAutoMixSdkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","title":"minAutoMixSdkVersion","navigatorTitle":[{"text":"minAutoMixSdkVersion","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/socialradio\/tunedstoresettings\/minautomixsdkversion"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings/minRadioSdkVersion":{"url":"\/documentation\/socialradio\/tunedstoresettings\/minradiosdkversion","title":"minRadioSdkVersion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minRadioSdkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/minRadioSdkVersion","role":"symbol","navigatorTitle":[{"text":"minRadioSdkVersion","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings/maxStudioTransitionLength":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxStudioTransitionLength","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":"?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/maxStudioTransitionLength","title":"maxStudioTransitionLength","url":"\/documentation\/socialradio\/tunedstoresettings\/maxstudiotransitionlength","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings/automixIQEnabled":{"url":"\/documentation\/socialradio\/tunedstoresettings\/automixiqenabled","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/automixIQEnabled","type":"topic","role":"symbol","navigatorTitle":[{"text":"automixIQEnabled","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automixIQEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"automixIQEnabled","kind":"symbol"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings/init(from:)":{"url":"\/documentation\/socialradio\/tunedstoresettings\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/init(from:)","title":"init(from:)"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings/mqttBrokerAddress":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/mqttBrokerAddress","navigatorTitle":[{"text":"mqttBrokerAddress","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/tunedstoresettings\/mqttbrokeraddress","title":"mqttBrokerAddress","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mqttBrokerAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedStoreSettings"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings","kind":"symbol","title":"TunedStoreSettings","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TunedStoreSettings"}],"url":"\/documentation\/socialradio\/tunedstoresettings","role":"symbol","abstract":[{"text":"Tuned Store settings","type":"text"}]},"doc://org.cocoapods.SocialRadio/Se":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/Se","title":"Swift.Decodable"},"doc://org.cocoapods.SocialRadio/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SE"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings/init":{"abstract":[],"url":"\/documentation\/socialradio\/tunedstoresettings\/init","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/init","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"TunedStoreSettings","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"TunedStoreSettings","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"TunedStoreSettings","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/automixIQEnabled","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/minAutoMixSdkVersion","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/minRadioSdkVersion","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/mqttBrokerAddress","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/socialRadioEnabled"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/init"],"title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedStoreSettings"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"socialRadioEnabled","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1socialRadioEnabled\/title"},{"value":[{"text":"socialRadioEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1socialRadioEnabled\/fragments"},{"value":"minAutoMixSdkVersion","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1minAutoMixSdkVersion\/title"},{"value":[{"text":"minAutoMixSdkVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1minAutoMixSdkVersion\/fragments"},{"value":"minRadioSdkVersion","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1minRadioSdkVersion\/title"},{"value":[{"text":"minRadioSdkVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1minRadioSdkVersion\/fragments"},{"value":"automixIQEnabled","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1automixIQEnabled\/title"},{"value":[{"text":"automixIQEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1automixIQEnabled\/fragments"},{"value":"mqttBrokerAddress","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1mqttBrokerAddress\/title"},{"value":[{"kind":"identifier","text":"mqttBrokerAddress"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings~1mqttBrokerAddress\/fragments"},{"value":"TunedStoreSettings","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings\/title"},{"value":[{"text":"TunedStoreSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings\/fragments"},{"value":[{"kind":"identifier","text":"TunedStoreSettings"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings\/navigatorTitle"}]}]}