{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedStoreSettings\/init","interfaceLanguage":"occ"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedStoreSettings"]]},"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)TunedStoreSettings(im)init","roleHeading":"Instance Method","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/tunedstoresettings\/init"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedStoreSettings":{"abstract":[{"type":"text","text":"Tuned Store settings"}],"navigatorTitle":[{"text":"TunedStoreSettings","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedStoreSettings","title":"TunedStoreSettings","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedStoreSettings","kind":"identifier"}],"url":"\/documentation\/automixiq\/tunedstoresettings","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedStoreSettings/init":{"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedStoreSettings\/init","title":"init","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/automixiq\/tunedstoresettings\/init","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"url":"\/documentation\/automixiq","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedStoreSettings\/title","op":"replace","value":"TunedStoreSettings"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedStoreSettings\/fragments","op":"replace","value":[{"text":"TunedStoreSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedStoreSettings\/navigatorTitle","op":"replace","value":[{"text":"TunedStoreSettings","kind":"identifier"}]}]}]}