{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"asyncGetAuthenticatedDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedDeviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"deviceIdentifierForVendor","content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the device","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiotunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiotunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required."},{"type":"text","text":" "},{"text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”.","type":"text"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asyncGetAuthenticatedDevice"},{"text":"(","kind":"text"},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedDeviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"externalID":"c:@M@SocialRadioLite@objc(pl)SocialRadioTunedRestDelegate(im)asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","roleHeading":"Instance Method","symbolKind":"method","title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","modules":[{"name":"SocialRadioLite"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedRestDelegate":{"title":"SocialRadioTunedRestDelegate","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiotunedrestdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedRestDelegate/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)":{"url":"\/documentation\/socialradiolite\/socialradiotunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)","abstract":[{"type":"text","text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required."},{"type":"text","text":" "},{"text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asyncGetAuthenticatedDevice"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tunedDeviceId","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"deviceIdentifierForVendor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier of the device"}]}],"name":"deviceIdentifierForVendor"},{"content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request","type":"text"}],"type":"paragraph"}],"name":"completion"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/title","value":"SocialRadioTunedRestDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/fragments","op":"replace","value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/navigatorTitle","value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}]},{"value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}