{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logAutomixIQMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"logLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioLogLevel","preciseIdentifier":"c:@M@SocialRadioLite@E@SocialRadioLogLevel","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"logLevel","content":[{"inlineContent":[{"type":"text","text":"The log level."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The message it wishes to log."}],"type":"paragraph"}],"name":"message"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiotunedrestdelegate\/logautomixiqmessage(loglevel:message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiotunedrestdelegate\/logautomixiqmessage(loglevel:message:)"]}],"abstract":[{"text":"Called by AutomixIQ when it wishes to output a log message","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)"},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@SocialRadioLite@objc(pl)SocialRadioTunedRestDelegate(im)logAutomixIQMessageWithLogLevel:message:","title":"logAutomixIQMessage(logLevel:message:)","modules":[{"name":"SocialRadioLite"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logAutomixIQMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"logLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadioLite@E@SocialRadioLogLevel","text":"SocialRadioLogLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"symbolKind":"method","required":true,"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedRestDelegate/logAutomixIQMessage(logLevel:message:)":{"url":"\/documentation\/socialradiolite\/socialradiotunedrestdelegate\/logautomixiqmessage(loglevel:message:)","required":true,"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logAutomixIQMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"logLevel"},{"text":": ","kind":"text"},{"text":"SocialRadioLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@E@SocialRadioLogLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"title":"logAutomixIQMessage(logLevel:message:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedRestDelegate":{"title":"SocialRadioTunedRestDelegate","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiotunedrestdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel","role":"symbol","abstract":[{"type":"text","text":"SocialRadioLogLevel is an enum of all the AutomixIQ available log levels"}],"title":"SocialRadioLogLevel","type":"topic","url":"\/documentation\/socialradiolite\/socialradiologlevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioLogLevel"}],"navigatorTitle":[{"text":"SocialRadioLogLevel","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"logAutomixIQMessageWithLogLevel:message:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioLogLevel","preciseIdentifier":"c:@M@SocialRadioLite@E@SocialRadioLogLevel","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"logLevel","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"logLevel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The log level."}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message it wishes to log."}]}]}]},"op":"replace"},{"value":"logAutomixIQMessageWithLogLevel:message:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments"},{"value":"SocialRadioTunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}]},{"value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/title","op":"replace","value":"SocialRadioLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/fragments","value":[{"text":"SocialRadioLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/navigatorTitle","value":[{"text":"SocialRadioLogLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}