{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates"]]},"variants":[{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/moderationdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/moderationdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding content moderation."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moderationDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerModerationDelegate"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/moderationDelegate","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"text":"moderationDelegate","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates(py)moderationDelegate","symbolKind":"property","modules":[{"name":"SocialRadio"}],"title":"moderationDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moderationDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerModerationDelegate"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerDelegates","kind":"identifier"}],"title":"SocialLayerDelegates","navigatorTitle":[{"text":"SocialLayerDelegates","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/sociallayerdelegates","abstract":[{"type":"text","text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions."},{"type":"text","text":" "},{"type":"text","text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc."},{"type":"text","text":" "},{"type":"text","text":"See each delegate’s documentation for details."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates/moderationDelegate":{"type":"topic","navigatorTitle":[{"text":"moderationDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/sociallayerdelegates\/moderationdelegate","abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding content moderation."}],"title":"moderationDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/moderationDelegate","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moderationDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerModerationDelegate"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerModerationDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"title":"SocialLayerModerationDelegate","navigatorTitle":[{"kind":"identifier","text":"SocialLayerModerationDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/sociallayermoderationdelegate","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding content moderation.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"moderationDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"moderationDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialLayerModerationDelegate","text":"id<SocialLayerModerationDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"moderationDelegate"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","op":"replace","value":"SocialLayerDelegates"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","op":"replace","value":[{"text":"SocialLayerDelegates","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerDelegates","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1moderationDelegate\/title","op":"replace","value":"moderationDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1moderationDelegate\/fragments","op":"replace","value":[{"text":"moderationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/title","op":"replace","value":"SocialLayerModerationDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/fragments","op":"replace","value":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}]}]}]}