{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:"}],"modules":[{"name":"SocialRadio"}],"roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioConfig(im)initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"featureSetConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioFeatureSetConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioFeatureSetConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"uiConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioUIConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUIConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/socialradio\/socialradioconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradioconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig\/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureSetConfig"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioFeatureSetConfig","text":"SocialRadioFeatureSetConfig"},{"text":" = SocialRadioFeatureSetConfig(), ","kind":"text"},{"kind":"externalParam","text":"uiConfig"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","text":"SocialRadioUIConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUIConfig","kind":"typeIdentifier"},{"text":" = SocialRadioUIConfig())","kind":"text"}]}]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"abstract":[{"text":"SocialRadioConfig holds the variables to initialise SocialRadio and describe the desired feature set and UI","type":"text"}],"role":"symbol","kind":"symbol","title":"SocialRadioConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioConfig","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioConfig","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradioconfig","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig":{"url":"\/documentation\/socialradio\/socialradiofeaturesetconfig","abstract":[{"text":"Social Radio’s feature set options","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"type":"topic","title":"SocialRadioFeatureSetConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig":{"type":"topic","title":"SocialRadioUIConfig","abstract":[{"type":"text","text":"Social Radio UI options"}],"url":"\/documentation\/socialradio\/socialradiouiconfig","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUIConfig"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"featureSetConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioFeatureSetConfig","text":"SocialRadioFeatureSetConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"uiConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUIConfig","text":"SocialRadioUIConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig\/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)","type":"topic","title":"init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)","navigatorTitle":[{"text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradioconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:)","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"url":"\/documentation\/socialradio","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithApiKey:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"apiKey","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"country:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"country","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"storeId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"storeId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"applicationId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"applicationId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"featureSetConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","text":"SocialRadioFeatureSetConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioFeatureSetConfig","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"featureSetConfig","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"uiConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","text":"SocialRadioUIConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUIConfig","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"uiConfig","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SocialRadioConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","op":"replace"},{"value":[{"text":"SocialRadioConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","op":"replace"},{"value":[{"text":"SocialRadioConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","op":"replace"},{"value":"SocialRadioFeatureSetConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/title","op":"replace"},{"value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/fragments","op":"replace"},{"value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/navigatorTitle","op":"replace"},{"value":"SocialRadioUIConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/title","op":"replace"},{"value":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/fragments","op":"replace"},{"value":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/navigatorTitle","op":"replace"},{"value":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig~1init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig~1init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)\/fragments","op":"replace"}]}]}