{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"authenticationDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","text":"SocialLayerAuthenticationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerAuthenticationDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerUserDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","text":"SocialLayerUserDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"liveMixtapeDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerLiveMixtapeDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","text":"SocialLayerLiveMixtapeDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mixtapeLikesDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeLikesDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","text":"SocialLayerMixtapeLikesDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mixtapeCommentsDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeCommentsDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","text":"SocialLayerMixtapeCommentsDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mixtapeBackgroundsDelegate"},{"kind":"text","text":": "},{"text":"SocialLayerMixtapeBackgroundsDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"trackLikesDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerTrackLikesDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerTrackLikesDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"moderationDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerModerationDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerModerationDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"notificationsDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerNotificationsDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerNotificationsDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"s:11SocialRadio0A14LayerDelegatesC22authenticationDelegate04userF0011liveMixtapeF0012mixtapeLikesF00j8CommentsF00j11BackgroundsF005trackkF0010moderationF0013notificationsF0AcA0ac14AuthenticationF0_p_AA0ac4UserF0_pAA0ac4LiveiF0_pAA0acikF0_pSgAA0acilF0_pSgAA0acimF0_pSgAA0ac5TrackkF0_pSgAA0ac10ModerationF0_pSgAA0ac13NotificationsF0_pSgtcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"authenticationDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerAuthenticationDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerAuthenticationDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerUserDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerUserDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"liveMixtapeDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerLiveMixtapeDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerLiveMixtapeDelegate"},{"text":", ","kind":"text"},{"text":"mixtapeLikesDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerMixtapeLikesDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeLikesDelegate"},{"text":"?, ","kind":"text"},{"text":"mixtapeCommentsDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerMixtapeCommentsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeCommentsDelegate"},{"text":"?, ","kind":"text"},{"text":"mixtapeBackgroundsDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate"},{"text":"?, ","kind":"text"},{"text":"trackLikesDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerTrackLikesDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerTrackLikesDelegate"},{"text":"?, ","kind":"text"},{"text":"moderationDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerModerationDelegate"},{"text":"?, ","kind":"text"},{"text":"notificationsDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerNotificationsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerNotificationsDelegate"},{"text":"?)","kind":"text"}],"symbolKind":"init","title":"init(authenticationDelegate:userDelegate:liveMixtapeDelegate:mixtapeLikesDelegate:mixtapeCommentsDelegate:mixtapeBackgroundsDelegate:trackLikesDelegate:moderationDelegate:notificationsDelegate:)","role":"symbol","roleHeading":"Initializer","modules":[{"name":"SocialRadio"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates"]]},"sections":[],"abstract":[{"text":"Initialises the delegates object.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/init(authenticationDelegate:userDelegate:liveMixtapeDelegate:mixtapeLikesDelegate:mixtapeCommentsDelegate:mixtapeBackgroundsDelegate:trackLikesDelegate:moderationDelegate:notificationsDelegate:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayerdelegates\/init(authenticationdelegate:userdelegate:livemixtapedelegate:mixtapelikesdelegate:mixtapecommentsdelegate:mixtapebackgroundsdelegate:tracklikesdelegate:moderationdelegate:notificationsdelegate:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerTrackLikesDelegate":{"title":"SocialLayerTrackLikesDelegate","url":"\/documentation\/socialradio\/sociallayertracklikesdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}],"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a track."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerUserDelegate":{"title":"SocialLayerUserDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerUserDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayeruserdelegate","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding  users."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","role":"symbol","navigatorTitle":[{"text":"SocialLayerUserDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeLikesDelegate":{"url":"\/documentation\/socialradio\/sociallayermixtapelikesdelegate","title":"SocialLayerMixtapeLikesDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerMixtapeLikesDelegate"}],"abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a mixtape.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLayerMixtapeLikesDelegate"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate":{"title":"SocialLayerLiveMixtapeDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate","type":"topic","kind":"symbol","abstract":[{"text":"(Required) Handles communication between SocialRadio SDK and a backend regarding live mixtapes.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","role":"symbol","navigatorTitle":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerModerationDelegate":{"url":"\/documentation\/socialradio\/sociallayermoderationdelegate","title":"SocialLayerModerationDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerModerationDelegate"}],"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding content moderation."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLayerModerationDelegate"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate":{"title":"SocialLayerMixtapeBackgroundsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate","type":"topic","kind":"symbol","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","role":"symbol","navigatorTitle":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerAuthenticationDelegate":{"url":"\/documentation\/socialradio\/sociallayerauthenticationdelegate","title":"SocialLayerAuthenticationDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}],"abstract":[{"text":"(Required) Handles communication between SocialRadio SDK and a backend regarding authentication","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates/init(authenticationDelegate:userDelegate:liveMixtapeDelegate:mixtapeLikesDelegate:mixtapeCommentsDelegate:mixtapeBackgroundsDelegate:trackLikesDelegate:moderationDelegate:notificationsDelegate:)":{"title":"init(authenticationDelegate:userDelegate:liveMixtapeDelegate:mixtapeLikesDelegate:mixtapeCommentsDelegate:mixtapeBackgroundsDelegate:trackLikesDelegate:moderationDelegate:notificationsDelegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"authenticationDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerAuthenticationDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerAuthenticationDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerUserDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerUserDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"liveMixtapeDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerLiveMixtapeDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerLiveMixtapeDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mixtapeLikesDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerMixtapeLikesDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeLikesDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"mixtapeCommentsDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerMixtapeCommentsDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeCommentsDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"mixtapeBackgroundsDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerMixtapeBackgroundsDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"trackLikesDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerTrackLikesDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerTrackLikesDelegate"},{"text":"?, ","kind":"text"},{"text":"moderationDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerModerationDelegate"},{"text":"?, ","kind":"text"},{"text":"notificationsDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerNotificationsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerNotificationsDelegate"},{"text":"?)","kind":"text"}],"url":"\/documentation\/socialradio\/sociallayerdelegates\/init(authenticationdelegate:userdelegate:livemixtapedelegate:mixtapelikesdelegate:mixtapecommentsdelegate:mixtapebackgroundsdelegate:tracklikesdelegate:moderationdelegate:notificationsdelegate:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Initialises the delegates object."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/init(authenticationDelegate:userDelegate:liveMixtapeDelegate:mixtapeLikesDelegate:mixtapeCommentsDelegate:mixtapeBackgroundsDelegate:trackLikesDelegate:moderationDelegate:notificationsDelegate:)","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate":{"title":"SocialLayerMixtapeCommentsDelegate","url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"}],"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding commenting a mixtape."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"title":"SocialLayerDelegates","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerDelegates"}],"url":"\/documentation\/socialradio\/sociallayerdelegates","type":"topic","kind":"symbol","abstract":[{"text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions.","type":"text"},{"text":" ","type":"text"},{"text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc.","type":"text"},{"text":" ","type":"text"},{"text":"See each delegate’s documentation for details.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialLayerDelegates"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerNotificationsDelegate":{"url":"\/documentation\/socialradio\/sociallayernotificationsdelegate","title":"SocialLayerNotificationsDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding notifications."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","type":"topic","navigatorTitle":[{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/title","value":"SocialLayerTrackLikesDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/fragments","value":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/navigatorTitle","value":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/title","value":"SocialLayerUserDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerUserDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/navigatorTitle","value":[{"text":"SocialLayerUserDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/title","value":"SocialLayerMixtapeLikesDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/fragments","value":[{"text":"SocialLayerMixtapeLikesDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerMixtapeLikesDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/title","value":"SocialLayerLiveMixtapeDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/title","op":"replace","value":"SocialLayerModerationDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/fragments","op":"replace","value":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/title","op":"replace","value":"SocialLayerMixtapeBackgroundsDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/fragments","op":"replace","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/title","op":"replace","value":"SocialLayerAuthenticationDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/fragments","op":"replace","value":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/title","op":"replace","value":"SocialLayerMixtapeCommentsDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/fragments","op":"replace","value":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","value":"SocialLayerDelegates","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerDelegates"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/title","value":"SocialLayerNotificationsDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerNotificationsDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerNotificationsDelegate"}],"op":"replace"}]}]}