{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate\/syncGetIsPreloaded(backgroundIdentifier:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"syncGetIsPreloadedWithBackgroundIdentifier:"}],"title":"syncGetIsPreloaded(backgroundIdentifier:)","required":true,"roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetIsPreloaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate(im)syncGetIsPreloadedWithBackgroundIdentifier:","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetIsPreloaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"backgroundIdentifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the background."}]}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if preloaded, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" otherwise.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Checks whether a background is preloaded."}],"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate\/syncgetispreloaded(backgroundidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate\/syncgetispreloaded(backgroundidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate/syncGetIsPreloaded(backgroundIdentifier:)":{"navigatorTitle":[{"kind":"identifier","text":"syncGetIsPreloadedWithBackgroundIdentifier:"}],"url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate\/syncgetispreloaded(backgroundidentifier:)","type":"topic","title":"syncGetIsPreloaded(backgroundIdentifier:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate\/syncGetIsPreloaded(backgroundIdentifier:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetIsPreloaded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","abstract":[{"type":"text","text":"Checks whether a background is preloaded."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate":{"role":"symbol","title":"SocialLayerMixtapeBackgroundsDelegate","navigatorTitle":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate","abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"syncGetIsPreloadedWithBackgroundIdentifier:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"syncGetIsPreloadedWithBackgroundIdentifier:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"syncGetIsPreloadedWithBackgroundIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundIdentifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"backgroundIdentifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the background."}]}]}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if preloaded, ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" otherwise.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"value":"syncGetIsPreloadedWithBackgroundIdentifier:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate~1syncGetIsPreloaded(backgroundIdentifier:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"syncGetIsPreloadedWithBackgroundIdentifier:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate~1syncGetIsPreloaded(backgroundIdentifier:)\/fragments","op":"replace"},{"value":"SocialLayerMixtapeBackgroundsDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialLayerMixtapeBackgroundsDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialLayerMixtapeBackgroundsDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/navigatorTitle","op":"replace"}]}]}