{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayStartMixingIntoNext"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType"]]},"metadata":{"role":"symbol","modules":[{"name":"AutomixIQ"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayStartMixingIntoNext"}],"title":"AutomixIQPlaybackEventType.trackPlayStartMixingIntoNext","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext"}],"symbolKind":"case","externalID":"c:@M@AutomixIQ@E@AutomixIQPlaybackEventType@AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplaystartmixingintonext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplaystartmixingintonext"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlayStartMixingIntoNext":{"kind":"symbol","role":"symbol","type":"topic","title":"AutomixIQPlaybackEventType.trackPlayStartMixingIntoNext","abstract":[],"navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplaystartmixingintonext","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayStartMixingIntoNext","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType":{"title":"AutomixIQPlaybackEventType","url":"\/documentation\/automixiq\/automixiqplaybackeventtype","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","role":"collection","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","title":"AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayStartMixingIntoNext\/title","op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayStartMixingIntoNext\/fragments","op":"replace","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/title","op":"replace","value":"AutomixIQPlaybackEventType"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/fragments","op":"replace","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}