{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/playingTrackCurrentTime"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackCurrentTime","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"SocialRadioStatusVariable.playingTrackCurrentTime","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"SocialRadioStatusVariablePlayingTrackCurrentTime","kind":"identifier"}],"externalID":"c:@M@SocialRadio@E@SocialRadioStatusVariable@SocialRadioStatusVariablePlayingTrackCurrentTime","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackCurrentTime","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable"]]},"variants":[{"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/playingtrackcurrenttime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/playingtrackcurrenttime"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable/playingTrackCurrentTime":{"type":"topic","title":"SocialRadioStatusVariable.playingTrackCurrentTime","url":"\/documentation\/socialradio\/socialradiostatusvariable\/playingtrackcurrenttime","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusVariablePlayingTrackCurrentTime","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/playingTrackCurrentTime","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playingTrackCurrentTime"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiostatusvariable","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"abstract":[{"text":"SocialRadio status variable type","type":"text"}],"title":"SocialRadioStatusVariable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SocialRadioStatusVariablePlayingTrackCurrentTime","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SocialRadioStatusVariablePlayingTrackCurrentTime","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SocialRadioStatusVariablePlayingTrackCurrentTime","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SocialRadioStatusVariablePlayingTrackCurrentTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1playingTrackCurrentTime\/title"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariablePlayingTrackCurrentTime"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1playingTrackCurrentTime\/fragments"},{"value":"SocialRadioStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title"},{"value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}