{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate\/setLoggedInUser(_:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLoggedInUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"user"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser","kind":"typeIdentifier","text":"SocialRadioUser","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The logged in user","type":"text"}],"type":"paragraph"}],"name":"user"}],"kind":"parameters"}],"metadata":{"navigatorTitle":[{"text":"setLoggedInUser:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLoggedInUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SocialRadioUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerAuthenticationDelegate(im)setLoggedInUser:","title":"setLoggedInUser(_:)","symbolKind":"method","modules":[{"name":"SocialRadio"}]},"kind":"symbol","abstract":[{"type":"text","text":"Sets the logged in user"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayerauthenticationdelegate\/setloggedinuser(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayerauthenticationdelegate\/setloggedinuser(_:)"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerAuthenticationDelegate/setLoggedInUser(_:)":{"title":"setLoggedInUser(_:)","abstract":[{"type":"text","text":"Sets the logged in user"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setLoggedInUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SocialRadioUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate\/setLoggedInUser(_:)","url":"\/documentation\/socialradio\/sociallayerauthenticationdelegate\/setloggedinuser(_:)","role":"symbol","navigatorTitle":[{"text":"setLoggedInUser:","kind":"identifier"}],"required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUser","kind":"identifier"}],"title":"SocialRadioUser","navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiouser","abstract":[{"text":"SocialRadioUser models a user","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerAuthenticationDelegate":{"kind":"symbol","abstract":[{"text":"(Required) Handles communication between SocialRadio SDK and a backend regarding authentication","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","title":"SocialLayerAuthenticationDelegate","url":"\/documentation\/socialradio\/sociallayerauthenticationdelegate","navigatorTitle":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setLoggedInUser:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setLoggedInUser:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setLoggedInUser:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","text":"SocialRadioUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser"},{"text":" *) ","kind":"text"},{"text":"user","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The logged in user"}]}],"name":"user"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate~1setLoggedInUser(_:)\/title","value":"setLoggedInUser:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate~1setLoggedInUser(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setLoggedInUser:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/title","value":"SocialRadioUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/fragments","value":[{"text":"SocialRadioUser","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/title","value":"SocialLayerAuthenticationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/fragments","value":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}]}]}]}