{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowPublicBroadcasts","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiofeaturesetconfig\/allowpublicbroadcasts"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiofeaturesetconfig\/allowpublicbroadcasts"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"allowPublicBroadcasts","navigatorTitle":[{"kind":"identifier","text":"allowPublicBroadcasts"}],"roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioFeatureSetConfig(py)allowPublicBroadcasts","symbolKind":"property","modules":[{"name":"SocialRadio"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPublicBroadcasts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig\/allowPublicBroadcasts","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig/allowPublicBroadcasts":{"abstract":[],"url":"\/documentation\/socialradio\/socialradiofeaturesetconfig\/allowpublicbroadcasts","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowPublicBroadcasts","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"allowPublicBroadcasts","navigatorTitle":[{"text":"allowPublicBroadcasts","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig\/allowPublicBroadcasts"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"title":"SocialRadioFeatureSetConfig","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","abstract":[{"type":"text","text":"Social Radio’s feature set options"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"url":"\/documentation\/socialradio\/socialradiofeaturesetconfig"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"allowPublicBroadcasts","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"allowPublicBroadcasts"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowPublicBroadcasts"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"allowPublicBroadcasts","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig~1allowPublicBroadcasts\/title"},{"op":"replace","value":[{"kind":"identifier","text":"allowPublicBroadcasts"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig~1allowPublicBroadcasts\/fragments"},{"op":"replace","value":"SocialRadioFeatureSetConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/title"},{"value":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}