{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQPlaybackEventType","text":"AutomixIQPlaybackEventType","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"originalSessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus","text":"AutomixIQStatus","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The playback event type"}],"type":"paragraph"}],"name":"type"},{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track identifier this event refers to"}]}]},{"name":"originalSessionId","content":[{"type":"paragraph","inlineContent":[{"text":"The initial session id for the track this event refers to. AutomixIQ may use more session ids as needed if the session expires and it needs more data.","type":"text"}]}]},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"text":"The current status of AutomixIQ","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstatusobserverdelegate\/playbackevent(type:identifier:originalsessionid:status:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqstatusobserverdelegate\/playbackevent(type:identifier:originalsessionid:status:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate\/playbackEvent(type:identifier:originalSessionId:status:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when a playback event of AutomixIQ happens"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"playbackEventWithType:identifier:originalSessionId:status:"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate(im)playbackEventWithType:identifier:originalSessionId:status:","role":"symbol","modules":[{"name":"AutomixIQ"}],"symbolKind":"method","roleHeading":"Instance Method","title":"playbackEvent(type:identifier:originalSessionId:status:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQPlaybackEventType","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQPlaybackEventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"originalSessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatus","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate","title":"AutomixIQStatusObserverDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate/playbackEvent(type:identifier:originalSessionId:status:)":{"role":"symbol","navigatorTitle":[{"text":"playbackEventWithType:identifier:originalSessionId:status:","kind":"identifier"}],"abstract":[{"text":"Called when a playback event of AutomixIQ happens","type":"text"}],"url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate\/playbackevent(type:identifier:originalsessionid:status:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate\/playbackEvent(type:identifier:originalSessionId:status:)","title":"playbackEvent(type:identifier:originalSessionId:status:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQPlaybackEventType"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"originalSessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"url":"\/documentation\/automixiq\/automixiqplaybackeventtype","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"AutomixIQPlaybackEventType"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatus","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"title":"AutomixIQStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"playbackEventWithType:identifier:originalSessionId:status:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"playbackEventWithType:identifier:originalSessionId:status:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"playbackEventWithType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQPlaybackEventType","kind":"typeIdentifier","text":"AutomixIQPlaybackEventType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalSessionId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"originalSessionId"},{"kind":"text","text":" "},{"kind":"identifier","text":"status:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus","kind":"typeIdentifier","text":"AutomixIQStatus"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"type","content":[{"inlineContent":[{"text":"The playback event type","type":"text"}],"type":"paragraph"}]},{"name":"identifier","content":[{"inlineContent":[{"text":"The track identifier this event refers to","type":"text"}],"type":"paragraph"}]},{"name":"originalSessionId","content":[{"inlineContent":[{"text":"The initial session id for the track this event refers to. AutomixIQ may use more session ids as needed if the session expires and it needs more data.","type":"text"}],"type":"paragraph"}]},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"text":"The current status of AutomixIQ","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"AutomixIQStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle"},{"value":"playbackEventWithType:identifier:originalSessionId:status:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate~1playbackEvent(type:identifier:originalSessionId:status:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playbackEventWithType:identifier:originalSessionId:status:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate~1playbackEvent(type:identifier:originalSessionId:status:)\/fragments"},{"value":"AutomixIQPlaybackEventType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/title"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/fragments"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/navigatorTitle"},{"value":"AutomixIQStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/fragments"},{"value":[{"text":"AutomixIQStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/navigatorTitle"}]}]}