{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate\/loggedInUser()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loggedInUser"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser","kind":"typeIdentifier","text":"SocialRadioUser","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"The logged in user, nil if no user is logged in.","type":"text"}]}],"kind":"content"}],"metadata":{"modules":[{"name":"SocialRadio"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"loggedInUser"}],"roleHeading":"Instance Method","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerAuthenticationDelegate(im)loggedInUser","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loggedInUser"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser","kind":"typeIdentifier","text":"SocialRadioUser"},{"kind":"text","text":"?"}],"role":"symbol","required":true,"title":"loggedInUser()"},"variants":[{"paths":["\/documentation\/socialradio\/sociallayerauthenticationdelegate\/loggedinuser()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayerauthenticationdelegate\/loggedinuser()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Gets the logged in user, nil if no user is logged in."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate"]]},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerAuthenticationDelegate/loggedInUser()":{"abstract":[{"text":"Gets the logged in user, nil if no user is logged in.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate\/loggedInUser()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loggedInUser"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser","kind":"typeIdentifier","text":"SocialRadioUser"},{"kind":"text","text":"?"}],"url":"\/documentation\/socialradio\/sociallayerauthenticationdelegate\/loggedinuser()","role":"symbol","required":true,"kind":"symbol","title":"loggedInUser()","navigatorTitle":[{"kind":"identifier","text":"loggedInUser"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerAuthenticationDelegate":{"abstract":[{"text":"(Required) Handles communication between SocialRadio SDK and a backend regarding authentication","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayerauthenticationdelegate","role":"symbol","navigatorTitle":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}],"kind":"symbol","title":"SocialLayerAuthenticationDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUser"}],"url":"\/documentation\/socialradio\/socialradiouser","abstract":[{"text":"SocialRadioUser models a user","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUser"}],"kind":"symbol","role":"symbol","title":"SocialRadioUser"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"loggedInUser"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loggedInUser"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","text":"SocialRadioUser"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"loggedInUser"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The logged in user, nil if no user is logged in.","type":"text"}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate~1loggedInUser()\/title","value":"loggedInUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate~1loggedInUser()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loggedInUser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/title","value":"SocialLayerAuthenticationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/title","value":"SocialRadioUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/fragments","value":[{"kind":"identifier","text":"SocialRadioUser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUser"}]}]}]}