{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/errorcode\/sdknotinitialisedversionnolongersupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/errorcode\/sdknotinitialisedversionnolongersupported"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkNotInitialisedVersionNoLongerSupported"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeSdkNotInitialisedVersionNoLongerSupported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"title":"ErrorCode.sdkNotInitialisedVersionNoLongerSupported","symbolKind":"case","modules":[{"name":"SocialRadio"}]},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"title":"ErrorCode","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"kind":"symbol","url":"\/documentation\/socialradio\/errorcode","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/sdkNotInitialisedVersionNoLongerSupported":{"navigatorTitle":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","kind":"symbol","title":"ErrorCode.sdkNotInitialisedVersionNoLongerSupported","type":"topic","url":"\/documentation\/socialradio\/errorcode\/sdknotinitialisedversionnolongersupported","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle"},{"value":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}