{"metadata":{"externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","modules":[{"name":"SocialRadio"}],"title":"AutomixSDKErrorCode.cannotLoadExplicitLyricsTrack","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotLoadExplicitLyricsTrack"}],"symbolKind":"case","navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"roleHeading":"Case"},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotLoadExplicitLyricsTrack"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/cannotloadexplicitlyricstrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/cannotloadexplicitlyricstrack"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/cannotLoadExplicitLyricsTrack":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/cannotloadexplicitlyricstrack","title":"AutomixSDKErrorCode.cannotLoadExplicitLyricsTrack","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/title","value":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title","op":"replace","value":"AutomixSDKErrorCode"},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle","op":"replace"}]}]}