{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAlreadyTurningOn"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/onalreadyturningon"]},{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/onalreadyturningon"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/onAlreadyTurningOn"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAlreadyTurningOn"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeOnAlreadyTurningOn","symbolKind":"case","title":"AutomixSDKErrorCode.onAlreadyTurningOn","role":"symbol","modules":[{"name":"SocialRadio"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/onAlreadyTurningOn":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onAlreadyTurningOn","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/onalreadyturningon","type":"topic","title":"AutomixSDKErrorCode.onAlreadyTurningOn","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/onAlreadyTurningOn","navigatorTitle":[{"text":"AutomixSDKErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKErrorCodeOnAlreadyTurningOn"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AutomixSDKErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeOnAlreadyTurningOn"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"AutomixSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1onAlreadyTurningOn\/title","value":"AutomixSDKErrorCodeOnAlreadyTurningOn","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1onAlreadyTurningOn\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeOnAlreadyTurningOn","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}