{"metadata":{"navigatorTitle":[{"text":"AutomixSDKErrorCodePlayToEndMissingTrack","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"AutomixSDKErrorCode.playToEndMissingTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playToEndMissingTrack"}],"externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodePlayToEndMissingTrack","symbolKind":"case","modules":[{"name":"SocialRadio"}]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/playtoendmissingtrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/playtoendmissingtrack"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMissingTrack","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playToEndMissingTrack","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/playToEndMissingTrack":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playToEndMissingTrack","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/playtoendmissingtrack","type":"topic","title":"AutomixSDKErrorCode.playToEndMissingTrack","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMissingTrack","navigatorTitle":[{"text":"AutomixSDKErrorCodePlayToEndMissingTrack","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"AutomixSDKErrorCodePlayToEndMissingTrack","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayToEndMissingTrack"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayToEndMissingTrack"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"AutomixSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title"},{"op":"replace","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playToEndMissingTrack\/title","value":"AutomixSDKErrorCodePlayToEndMissingTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playToEndMissingTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayToEndMissingTrack"}]}]}]}