{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playAlreadyPlaying","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/playalreadyplaying"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/playalreadyplaying"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playAlreadyPlaying","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"AutomixSDKErrorCode.playAlreadyPlaying","navigatorTitle":[{"text":"AutomixSDKErrorCodePlayAlreadyPlaying","kind":"identifier"}],"externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodePlayAlreadyPlaying","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"playAlreadyPlaying","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"SocialRadio"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/playAlreadyPlaying":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playAlreadyPlaying","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/playalreadyplaying","type":"topic","title":"AutomixSDKErrorCode.playAlreadyPlaying","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playAlreadyPlaying","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayAlreadyPlaying"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"AutomixSDKErrorCodePlayAlreadyPlaying","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayAlreadyPlaying"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AutomixSDKErrorCodePlayAlreadyPlaying","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"AutomixSDKErrorCodePlayAlreadyPlaying","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playAlreadyPlaying\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayAlreadyPlaying"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playAlreadyPlaying\/fragments","op":"replace"},{"value":"AutomixSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}