{"metadata":{"externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeUnable_to_load_mix","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeUnable_to_load_mix"}],"modules":[{"name":"SocialRadio"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unable_to_load_mix","kind":"identifier"}],"title":"AutomixSDKErrorCode.unable_to_load_mix","role":"symbol","roleHeading":"Case","symbolKind":"case"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/unable_to_load_mix"]},{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/unable_to_load_mix"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/unable_to_load_mix","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unable_to_load_mix","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/unable_to_load_mix":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/unable_to_load_mix","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unable_to_load_mix","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode\/unable_to_load_mix","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeUnable_to_load_mix","kind":"identifier"}],"title":"AutomixSDKErrorCode.unable_to_load_mix","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"AutomixSDKErrorCodeUnable_to_load_mix","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"AutomixSDKErrorCodeUnable_to_load_mix","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeUnable_to_load_mix"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"AutomixSDKErrorCodeUnable_to_load_mix","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1unable_to_load_mix\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1unable_to_load_mix\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeUnable_to_load_mix"}]},{"value":"AutomixSDKErrorCode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments"},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle"}]}]}