{"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelWarning"}],"roleHeading":"Case","title":"TunedLogLevel.logLevelWarning","navigatorTitle":[{"text":"TunedLogLevelLogLevelWarning","kind":"identifier"}],"role":"symbol","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@E@TunedLogLevel@TunedLogLevelLogLevelWarning"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedloglevel\/loglevelwarning"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/tunedloglevel\/loglevelwarning"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel\/logLevelWarning"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelWarning","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel/logLevelWarning":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelWarning"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel\/logLevelWarning","role":"symbol","title":"TunedLogLevel.logLevelWarning","navigatorTitle":[{"kind":"identifier","text":"TunedLogLevelLogLevelWarning"}],"type":"topic","url":"\/documentation\/socialradio\/tunedloglevel\/loglevelwarning"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel":{"url":"\/documentation\/socialradio\/tunedloglevel","title":"TunedLogLevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"TunedLogLevel","kind":"identifier"}],"abstract":[{"text":"TunedLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedLogLevel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"TunedLogLevelLogLevelWarning","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"TunedLogLevelLogLevelWarning"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"TunedLogLevelLogLevelWarning"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel~1logLevelWarning\/title","value":"TunedLogLevelLogLevelWarning","op":"replace"},{"value":[{"text":"TunedLogLevelLogLevelWarning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel~1logLevelWarning\/fragments"},{"op":"replace","value":"TunedLogLevel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/title"},{"value":[{"text":"TunedLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/fragments"},{"value":[{"text":"TunedLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/navigatorTitle"}]}]}