{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"],"kind":"relationships"}],"seeAlsoSections":[{"generated":true,"title":"Initializing AutomixIQ for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"],"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate"},"abstract":[{"text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixiqmusiccachedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqmusiccachedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"roleHeading":"Protocol","title":"AutomixIQMusicCacheDelegate","modules":[{"name":"AutomixIQ"}],"symbolKind":"protocol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate"},"sections":[],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","type":"topic","kind":"symbol","title":"AutomixIQConfig","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQConfig","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQConfig","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqconfig"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate/getCachedTrack(trackId:)":{"title":"getCachedTrack(trackId:)","url":"\/documentation\/automixiq\/automixiqmusiccachedelegate\/getcachedtrack(trackid:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getCachedTrack(trackId:)","abstract":[{"text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCachedTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"getCachedTrackWithTrackId:","kind":"identifier"}],"kind":"symbol","type":"topic","required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate/trackDownloadCompleted(trackId:data:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","required":true,"title":"trackDownloadCompleted(trackId:data:)","navigatorTitle":[{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"abstract":[{"text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixiqmusiccachedelegate\/trackdownloadcompleted(trackid:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadCompleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","title":"TunedRestDelegate","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/tunedrestdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate/getTrackMetadata(trackId:)":{"title":"getTrackMetadata(trackId:)","url":"\/documentation\/automixiq\/automixiqmusiccachedelegate\/gettrackmetadata(trackid:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getTrackMetadata(trackId:)","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","text":"TunedTrackModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"getTrackMetadataWithTrackId:","kind":"identifier"}],"kind":"symbol","type":"topic","required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-article":{"title":"Initializing AutomixIQ","kind":"article","abstract":[{"text":"How to validate your client and start using the AutomixIQ SDK with Tuned Global APIs","type":"text"}],"url":"\/documentation\/automixiq\/initialising-automixiq-article","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","role":"article"},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","type":"topic","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate":{"kind":"symbol","navigatorTitle":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqmusiccachedelegate","role":"symbol","title":"AutomixIQMusicCacheDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate/trackDownloadProgressChanged(trackId:progress:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","required":true,"title":"trackDownloadProgressChanged(trackId:progress:)","navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"kind":"symbol","url":"\/documentation\/automixiq\/automixiqmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadProgressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixIQMusicCacheDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"]}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Initializing AutomixIQ for use with Tuned Global’s APIs","generated":true,"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixIQConfig","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments"},{"op":"replace","value":[{"text":"AutomixIQConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle"},{"op":"replace","value":"getCachedTrackWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1getCachedTrack(trackId:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getCachedTrackWithTrackId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1getCachedTrack(trackId:)\/fragments"},{"op":"replace","value":"trackDownloadCompletedWithTrackId:data:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1trackDownloadCompleted(trackId:data:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1trackDownloadCompleted(trackId:data:)\/fragments"},{"op":"replace","value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title"},{"op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/navigatorTitle"},{"op":"replace","value":"getTrackMetadataWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1getTrackMetadata(trackId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1getTrackMetadata(trackId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTrackMetadataWithTrackId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/title","value":"AutomixIQMusicCacheDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title","value":"trackDownloadProgressChangedWithTrackId:progress:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}]}]}]}