{"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH","doc:\/\/org.cocoapods.AutomixIQ\/SY"],"kind":"relationships"}],"seeAlsoSections":[{"generated":true,"title":"Data models","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Data-models-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType"],"anchor":"Data-models"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable"},"abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixiqstatusvariable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqstatusvariable"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"metadata":{"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"roleHeading":"Enumeration","title":"AutomixIQStatusVariable","modules":[{"name":"AutomixIQ"}],"role":"symbol","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@AutomixIQStatusVariable"},"sections":[],"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/adIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/adTrackCurrentTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/adTrackTotalTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canBack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canMixNow","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canOnOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canPlayPause","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canReorderTracks","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canSeek","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canSkipToNext","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canSkipToPrevious","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/explicitLyricsFiltering","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/mixId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/mixing","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/muted","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/nextTransitionDuration","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/normalisedVolume","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playSpeed","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playing","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingAd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackCurrentTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackTotalTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlistDiff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/readyToPlay","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/replayOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/vinylStartStop"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/Equatable-Implementations","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Data-models-article":{"role":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Data-models-article","title":"Data models","kind":"article","type":"topic","url":"\/documentation\/automixiq\/data-models-article","abstract":[{"type":"text","text":"How data is passed to and from the AutomixIQ player"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playlistDiff":{"kind":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariablePlaylistDiff","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/playlistdiff","role":"symbol","title":"AutomixIQStatusVariable.playlistDiff","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlistDiff"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/init(rawValue:)":{"kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/init(rawValue:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/canBack":{"title":"AutomixIQStatusVariable.canBack","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBack"}],"abstract":[],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/canback","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canBack","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableCanBack"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedTrackModel":{"title":"TunedTrackModel","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"url":"\/documentation\/automixiq\/tunedtrackmodel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel","type":"topic","role":"symbol","navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/mixing":{"title":"AutomixIQStatusVariable.mixing","url":"\/documentation\/automixiq\/automixiqstatusvariable\/mixing","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/mixing","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mixing","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableMixing","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playingTrackOriginalSessionId":{"kind":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariablePlayingTrackOriginalSessionId","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/playingtrackoriginalsessionid","role":"symbol","title":"AutomixIQStatusVariable.playingTrackOriginalSessionId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"playingTrackOriginalSessionId","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackOriginalSessionId"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playlist":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlist","abstract":[],"kind":"symbol","type":"topic","title":"AutomixIQStatusVariable.playlist","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playlist"}],"navigatorTitle":[{"text":"AutomixIQStatusVariablePlaylist","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/playlist"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable":{"abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"title":"AutomixIQStatusVariable","role":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable","navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/canMixNow":{"title":"AutomixIQStatusVariable.canMixNow","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canMixNow","url":"\/documentation\/automixiq\/automixiqstatusvariable\/canmixnow","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canMixNow"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableCanMixNow","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQWaveformModel":{"abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"title":"AutomixIQWaveformModel","role":"symbol","url":"\/documentation\/automixiq\/automixiqwaveformmodel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel","navigatorTitle":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/vinylStartStop":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/vinylStartStop","type":"topic","abstract":[],"title":"AutomixIQStatusVariable.vinylStartStop","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vinylStartStop","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableVinylStartStop","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/vinylstartstop"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playingTrackIndex":{"kind":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariablePlayingTrackIndex","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/playingtrackindex","role":"symbol","title":"AutomixIQStatusVariable.playingTrackIndex","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackIndex","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackIndex"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playingTrackCurrentTime":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackCurrentTime"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/playingtrackcurrenttime","role":"symbol","title":"AutomixIQStatusVariable.playingTrackCurrentTime","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackCurrentTime"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackCurrentTime"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/muted":{"title":"AutomixIQStatusVariable.muted","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/muted","url":"\/documentation\/automixiq\/automixiqstatusvariable\/muted","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"muted","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableMuted","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/normalisedVolume":{"title":"AutomixIQStatusVariable.normalisedVolume","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalisedVolume","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/normalisedvolume","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/normalisedVolume","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariableNormalisedVolume","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","type":"topic","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaylistOperationType":{"title":"AutomixIQPlaylistOperationType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqplaylistoperationtype","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/requestedPauseTrackIdentifier":{"title":"AutomixIQStatusVariable.requestedPauseTrackIdentifier","abstract":[],"role":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/requestedpausetrackidentifier","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestedPauseTrackIdentifier","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/requestedPauseTrackIdentifier","navigatorTitle":[{"text":"AutomixIQStatusVariableRequestedPauseTrackIdentifier","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/canSkipToPrevious":{"title":"AutomixIQStatusVariable.canSkipToPrevious","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canSkipToPrevious","url":"\/documentation\/automixiq\/automixiqstatusvariable\/canskiptoprevious","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSkipToPrevious","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableCanSkipToPrevious","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedPluginMetadataModel":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedPluginMetadataModel"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedPluginMetadataModel","title":"TunedPluginMetadataModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TunedPluginMetadataModel"}],"url":"\/documentation\/automixiq\/tunedpluginmetadatamodel","abstract":[{"text":"TunedPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"text":" ","type":"text"},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/readyToPlay":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readyToPlay","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/readyToPlay","title":"AutomixIQStatusVariable.readyToPlay","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixIQStatusVariableReadyToPlay","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/readytoplay","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus":{"kind":"symbol","navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqstatus","role":"symbol","title":"AutomixIQStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/mixId":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableMixId"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/mixid","role":"symbol","title":"AutomixIQStatusVariable.mixId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixId"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/mixId"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/canPlayPause":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canPlayPause","title":"AutomixIQStatusVariable.canPlayPause","navigatorTitle":[{"text":"AutomixIQStatusVariableCanPlayPause","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/canplaypause","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlayPause","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaylistOperation":{"title":"AutomixIQPlaylistOperation","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"url":"\/documentation\/automixiq\/automixiqplaylistoperation","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperation","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAuthenticationResponse":{"title":"TunedAuthenticationResponse","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAuthenticationResponse"}],"type":"topic","abstract":[{"text":"TunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"url":"\/documentation\/automixiq\/tunedauthenticationresponse","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse","role":"symbol","navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/requestedLoopTrackIdentifier":{"title":"AutomixIQStatusVariable.requestedLoopTrackIdentifier","abstract":[],"role":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/requestedlooptrackidentifier","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestedLoopTrackIdentifier","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/requestedLoopTrackIdentifier","navigatorTitle":[{"text":"AutomixIQStatusVariableRequestedLoopTrackIdentifier","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/canOnOff":{"title":"AutomixIQStatusVariable.canOnOff","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canOnOff","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableCanOnOff"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canOnOff"}],"role":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/canonoff","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playSpeed":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playSpeed","type":"topic","abstract":[],"title":"AutomixIQStatusVariable.playSpeed","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playSpeed","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariablePlaySpeed","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/playspeed"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playing":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playing","title":"AutomixIQStatusVariable.playing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaying"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/playing","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/canSkipToNext":{"title":"AutomixIQStatusVariable.canSkipToNext","url":"\/documentation\/automixiq\/automixiqstatusvariable\/canskiptonext","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canSkipToNext","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSkipToNext","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableCanSkipToNext","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/adTrackTotalTime":{"abstract":[],"title":"AutomixIQStatusVariable.adTrackTotalTime","role":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/adtracktotaltime","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"adTrackTotalTime"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/adTrackTotalTime","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableAdTrackTotalTime"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/canSeek":{"title":"AutomixIQStatusVariable.canSeek","abstract":[],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/canseek","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canSeek","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSeek","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableCanSeek","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SY"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/failedTrackLoadIdentifiers":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/failedTrackLoadIdentifiers","abstract":[],"kind":"symbol","type":"topic","title":"AutomixIQStatusVariable.failedTrackLoadIdentifiers","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableFailedTrackLoadIdentifiers"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/failedtrackloadidentifiers"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/canReorderTracks":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canReorderTracks","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canReorderTracks","title":"AutomixIQStatusVariable.canReorderTracks","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixIQStatusVariableCanReorderTracks","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/canreordertracks","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/automixiq\/automixiqstatusvariable\/equatable-implementations","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/Equatable-Implementations"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/adIndex":{"title":"AutomixIQStatusVariable.adIndex","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/adIndex","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixIQStatusVariableAdIndex","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adIndex","kind":"identifier"}],"role":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/adindex","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/adTrackCurrentTime":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/adTrackCurrentTime","title":"AutomixIQStatusVariable.adTrackCurrentTime","navigatorTitle":[{"text":"AutomixIQStatusVariableAdTrackCurrentTime","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/adtrackcurrenttime","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adTrackCurrentTime","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/explicitLyricsFiltering":{"title":"AutomixIQStatusVariable.explicitLyricsFiltering","abstract":[],"role":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/explicitlyricsfiltering","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"explicitLyricsFiltering","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/explicitLyricsFiltering","navigatorTitle":[{"text":"AutomixIQStatusVariableExplicitLyricsFiltering","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/nextTransitionDuration":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTransitionDuration"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/nextTransitionDuration","title":"AutomixIQStatusVariable.nextTransitionDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableNextTransitionDuration"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/nexttransitionduration","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/automixiq\/automixiqstatusvariable\/rawrepresentable-implementations","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/RawRepresentable-Implementations"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playingTrackIdentifier":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackIdentifier","title":"AutomixIQStatusVariable.playingTrackIdentifier","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackIdentifier"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/playingtrackidentifier","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackIdentifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playingTrackStreamingProgress":{"abstract":[],"title":"AutomixIQStatusVariable.playingTrackStreamingProgress","role":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/playingtrackstreamingprogress","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackStreamingProgress","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackStreamingProgress","navigatorTitle":[{"text":"AutomixIQStatusVariablePlayingTrackStreamingProgress","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedArtistModel":{"title":"TunedArtistModel","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedArtistModel"}],"abstract":[{"text":"TunedArtistModel models an artist.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel","url":"\/documentation\/automixiq\/tunedartistmodel","role":"symbol","navigatorTitle":[{"text":"TunedArtistModel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playingAd":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingAd","abstract":[],"kind":"symbol","type":"topic","title":"AutomixIQStatusVariable.playingAd","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingAd"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingAd"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/playingad"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playingTrackTotalTime":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackTotalTime"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackTotalTime","title":"AutomixIQStatusVariable.playingTrackTotalTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackTotalTime"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/playingtracktotaltime","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/transitionStartTimeSeconds":{"title":"AutomixIQStatusVariable.transitionStartTimeSeconds","url":"\/documentation\/automixiq\/automixiqstatusvariable\/transitionstarttimeseconds","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/transitionStartTimeSeconds","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionStartTimeSeconds"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableTransitionStartTimeSeconds","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/preferredTransitionDurationSeconds":{"abstract":[],"title":"AutomixIQStatusVariable.preferredTransitionDurationSeconds","role":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/preferredtransitiondurationseconds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredTransitionDurationSeconds","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/preferredTransitionDurationSeconds","navigatorTitle":[{"text":"AutomixIQStatusVariablePreferredTransitionDurationSeconds","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/SH":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/replayOn":{"title":"AutomixIQStatusVariable.replayOn","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"replayOn"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/replayOn","url":"\/documentation\/automixiq\/automixiqstatusvariable\/replayon","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableReplayOn"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixIQStatusVariable","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/adIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/adTrackCurrentTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/adTrackTotalTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canBack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canMixNow","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canOnOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canPlayPause","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canReorderTracks","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canSeek","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canSkipToNext","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canSkipToPrevious","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/explicitLyricsFiltering","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/mixId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/mixing","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/muted","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/nextTransitionDuration","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/normalisedVolume","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playSpeed","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playing","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingAd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackCurrentTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingTrackTotalTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlistDiff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/readyToPlay","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/replayOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/vinylStartStop"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Data-models-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType"],"anchor":"Data-models","title":"Data models","generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixIQStatusVariablePlaylistDiff","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playlistDiff\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlaylistDiff","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playlistDiff\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableCanBack","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canBack\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableCanBack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canBack\/fragments"},{"op":"replace","value":"TunedTrackModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariableMixing","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1mixing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableMixing"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1mixing\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlayingTrackOriginalSessionId","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackOriginalSessionId\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlayingTrackOriginalSessionId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackOriginalSessionId\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlaylist","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playlist\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlaylist","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playlist\/fragments"},{"op":"replace","value":"AutomixIQStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/navigatorTitle","op":"replace"},{"value":"AutomixIQStatusVariableCanMixNow","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canMixNow\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanMixNow"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canMixNow\/fragments","op":"replace"},{"value":"AutomixIQWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/title","op":"replace"},{"value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/navigatorTitle","op":"replace"},{"value":"AutomixIQStatusVariableVinylStartStop","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1vinylStartStop\/title","op":"replace"},{"value":[{"text":"AutomixIQStatusVariableVinylStartStop","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1vinylStartStop\/fragments","op":"replace"},{"value":"AutomixIQStatusVariablePlayingTrackIndex","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackIndex\/title","op":"replace"},{"value":[{"text":"AutomixIQStatusVariablePlayingTrackIndex","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackIndex\/fragments","op":"replace"},{"value":"AutomixIQStatusVariablePlayingTrackCurrentTime","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackCurrentTime\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackCurrentTime"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackCurrentTime\/fragments","op":"replace"},{"value":"AutomixIQStatusVariableMuted","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1muted\/title","op":"replace"},{"value":[{"text":"AutomixIQStatusVariableMuted","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1muted\/fragments","op":"replace"},{"value":"AutomixIQStatusVariableNormalisedVolume","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1normalisedVolume\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableNormalisedVolume"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1normalisedVolume\/fragments","op":"replace"},{"value":"AutomixIQPlaylistOperationType","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType\/navigatorTitle","op":"replace"},{"value":"AutomixIQStatusVariableRequestedPauseTrackIdentifier","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1requestedPauseTrackIdentifier\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableRequestedPauseTrackIdentifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1requestedPauseTrackIdentifier\/fragments","op":"replace"},{"value":"AutomixIQStatusVariableCanSkipToPrevious","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canSkipToPrevious\/title","op":"replace"},{"value":[{"text":"AutomixIQStatusVariableCanSkipToPrevious","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canSkipToPrevious\/fragments","op":"replace"},{"op":"replace","value":"TunedPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedPluginMetadataModel\/title"},{"op":"replace","value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedPluginMetadataModel\/fragments"},{"op":"replace","value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedPluginMetadataModel\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariableReadyToPlay","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1readyToPlay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableReadyToPlay"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1readyToPlay\/fragments"},{"op":"replace","value":"AutomixIQStatus","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/title"},{"op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/fragments"},{"op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariableMixId","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1mixId\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableMixId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1mixId\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableCanPlayPause","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canPlayPause\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableCanPlayPause","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canPlayPause\/fragments"},{"op":"replace","value":"AutomixIQPlaylistOperation","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperation\/title"},{"op":"replace","value":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperation\/navigatorTitle"},{"op":"replace","value":"TunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/fragments"},{"op":"replace","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariableRequestedLoopTrackIdentifier","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1requestedLoopTrackIdentifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableRequestedLoopTrackIdentifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1requestedLoopTrackIdentifier\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableCanOnOff","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canOnOff\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableCanOnOff","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canOnOff\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playSpeed\/title","value":"AutomixIQStatusVariablePlaySpeed"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playSpeed\/fragments","value":[{"text":"AutomixIQStatusVariablePlaySpeed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playing\/title","value":"AutomixIQStatusVariablePlaying"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playing\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaying"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canSkipToNext\/title","value":"AutomixIQStatusVariableCanSkipToNext"},{"value":[{"text":"AutomixIQStatusVariableCanSkipToNext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canSkipToNext\/fragments"},{"value":"AutomixIQStatusVariableAdTrackTotalTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1adTrackTotalTime\/title"},{"value":[{"text":"AutomixIQStatusVariableAdTrackTotalTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1adTrackTotalTime\/fragments"},{"value":"AutomixIQStatusVariableCanSeek","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canSeek\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanSeek"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canSeek\/fragments"},{"value":"AutomixIQStatusVariableFailedTrackLoadIdentifiers","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1failedTrackLoadIdentifiers\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableFailedTrackLoadIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1failedTrackLoadIdentifiers\/fragments"},{"value":"AutomixIQStatusVariableCanReorderTracks","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canReorderTracks\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanReorderTracks"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canReorderTracks\/fragments"},{"value":"AutomixIQStatusVariableAdIndex","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1adIndex\/title"},{"value":[{"text":"AutomixIQStatusVariableAdIndex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1adIndex\/fragments"},{"value":"AutomixIQStatusVariableAdTrackCurrentTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1adTrackCurrentTime\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableAdTrackCurrentTime"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1adTrackCurrentTime\/fragments"},{"value":"AutomixIQStatusVariableExplicitLyricsFiltering","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1explicitLyricsFiltering\/title"},{"value":[{"text":"AutomixIQStatusVariableExplicitLyricsFiltering","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1explicitLyricsFiltering\/fragments"},{"value":"AutomixIQStatusVariableNextTransitionDuration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1nextTransitionDuration\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1nextTransitionDuration\/fragments","op":"replace","value":[{"text":"AutomixIQStatusVariableNextTransitionDuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackIdentifier\/title","op":"replace","value":"AutomixIQStatusVariablePlayingTrackIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackIdentifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackStreamingProgress\/title","op":"replace","value":"AutomixIQStatusVariablePlayingTrackStreamingProgress"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackStreamingProgress\/fragments","op":"replace","value":[{"text":"AutomixIQStatusVariablePlayingTrackStreamingProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel\/title","op":"replace","value":"TunedArtistModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedArtistModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedArtistModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingAd\/title","op":"replace","value":"AutomixIQStatusVariablePlayingAd"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingAd\/fragments","op":"replace","value":[{"text":"AutomixIQStatusVariablePlayingAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackTotalTime\/title","op":"replace","value":"AutomixIQStatusVariablePlayingTrackTotalTime"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingTrackTotalTime\/fragments","op":"replace","value":[{"text":"AutomixIQStatusVariablePlayingTrackTotalTime","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1transitionStartTimeSeconds\/title","op":"replace","value":"AutomixIQStatusVariableTransitionStartTimeSeconds"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1transitionStartTimeSeconds\/fragments","op":"replace","value":[{"text":"AutomixIQStatusVariableTransitionStartTimeSeconds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1preferredTransitionDurationSeconds\/title","op":"replace","value":"AutomixIQStatusVariablePreferredTransitionDurationSeconds"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1preferredTransitionDurationSeconds\/fragments","op":"replace","value":[{"text":"AutomixIQStatusVariablePreferredTransitionDurationSeconds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1replayOn\/title","op":"replace","value":"AutomixIQStatusVariableReplayOn"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1replayOn\/fragments","op":"replace","value":[{"text":"AutomixIQStatusVariableReplayOn","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}