{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayPlayed5Secs","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplayplayed5secs"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplayplayed5secs"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@E@AutomixIQPlaybackEventType@AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"roleHeading":"Case","title":"AutomixIQPlaybackEventType.trackPlayPlayed5Secs","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayPlayed5Secs","kind":"identifier"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/trackPlayPlayed5Secs":{"title":"AutomixIQPlaybackEventType.trackPlayPlayed5Secs","url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplayplayed5secs","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayPlayed5Secs","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType","title":"AutomixIQPlaybackEventType","abstract":[{"text":"AutomixIQPlaybackEventType is an enum of all the available playback events","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixiqplaybackeventtype","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/title","op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/fragments","op":"replace","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}]},{"value":"AutomixIQPlaybackEventType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/title"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/fragments"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}