{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAlreadyTurningOn"}]}]}],"variants":[{"paths":["\/documentation\/socialradio\/errorcode\/onalreadyturningon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/errorcode\/onalreadyturningon"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeOnAlreadyTurningOn","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeOnAlreadyTurningOn"}],"title":"ErrorCode.onAlreadyTurningOn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAlreadyTurningOn"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/onAlreadyTurningOn","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","abstract":[],"role":"symbol","url":"\/documentation\/socialradio\/errorcode","title":"ErrorCode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/onAlreadyTurningOn":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAlreadyTurningOn"}],"type":"topic","role":"symbol","url":"\/documentation\/socialradio\/errorcode\/onalreadyturningon","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/onAlreadyTurningOn","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeOnAlreadyTurningOn"}],"title":"ErrorCode.onAlreadyTurningOn"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"ErrorCodeOnAlreadyTurningOn","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ErrorCodeOnAlreadyTurningOn","kind":"identifier"}]}]}},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1onAlreadyTurningOn\/title","op":"replace","value":"ErrorCodeOnAlreadyTurningOn"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1onAlreadyTurningOn\/fragments","op":"replace","value":[{"text":"ErrorCodeOnAlreadyTurningOn","kind":"identifier"}]}]}]}