{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Case","title":"ErrorCode.sdkAlreadyInitialised","navigatorTitle":[{"text":"ErrorCodeSdkAlreadyInitialised","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeSdkAlreadyInitialised","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkAlreadyInitialised","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkAlreadyInitialised"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/socialradio\/errorcode\/sdkalreadyinitialised"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/errorcode\/sdkalreadyinitialised"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkAlreadyInitialised"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/sdkAlreadyInitialised":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}],"url":"\/documentation\/socialradio\/errorcode\/sdkalreadyinitialised","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkAlreadyInitialised"}],"abstract":[],"type":"topic","title":"ErrorCode.sdkAlreadyInitialised","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkAlreadyInitialised"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","abstract":[],"role":"symbol","url":"\/documentation\/socialradio\/errorcode","title":"ErrorCode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ErrorCodeSdkAlreadyInitialised","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ErrorCodeSdkAlreadyInitialised","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkAlreadyInitialised\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkAlreadyInitialised\/fragments","op":"replace"},{"value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}