{"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"role":"symbol","title":"initialise(config:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"kind":"identifier","text":"initialiseWithConfig:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadio(cm)initialiseWithConfig:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:","symbolKind":"method","roleHeading":"Type Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"platforms":["iOS"]}]},{"parameters":[{"name":"config","content":[{"inlineContent":[{"type":"text","text":"The SocialRadio configuration."}],"type":"paragraph"}]},{"name":"tunedRestDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of feeding and renewing Tuned Global APIs access tokens. See TunedRestDelegate."}]}]},{"name":"socialRadioStatusDelegate","content":[{"inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from SocialRadio. See SocialRadioStatusObserverDelegate.","type":"text"}],"type":"paragraph"}]},{"name":"socialRadioUIDelegate","content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of presenting user interfaces the SocialRadio needs"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}]}]}],"type":"unorderedList"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/socialradio\/socialradio\/initialise(config:tunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradio\/initialise(config:tunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialise(config:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio"]]},"kind":"symbol","abstract":[{"text":"Initialiser for SocialRadio to work against a Tuned Global’s Store and Tuned Global’s APIs.","type":"text"},{"text":" ","type":"text"},{"text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID.","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"url":"\/documentation\/socialradio\/socialradiouidelegate","title":"SocialRadioUIDelegate","type":"topic","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioConfig"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","abstract":[{"type":"text","text":"SocialRadioConfig holds the variables to initialise SocialRadio and describe the desired feature set and UI"}],"url":"\/documentation\/socialradio\/socialradioconfig","role":"symbol","type":"topic","title":"SocialRadioConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioConfig"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/initialise(config:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)":{"navigatorTitle":[{"text":"initialiseWithConfig:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:","kind":"identifier"}],"type":"topic","role":"symbol","title":"initialise(config:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Initialiser for SocialRadio to work against a Tuned Global’s Store and Tuned Global’s APIs."},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"url":"\/documentation\/socialradio\/socialradio\/initialise(config:tunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedRestDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedRestDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialise(config:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio":{"title":"SocialRadio","url":"\/documentation\/socialradio\/socialradio","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadio"}],"abstract":[{"type":"text","text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadio"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"url":"\/documentation\/socialradio\/tunedrestdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","role":"symbol","type":"topic","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedRestDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"title":"TunedRestDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"abstract":[],"role":"symbol","title":"SocialRadioStatusObserverDelegate","url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"initialiseWithConfig:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initialiseWithConfig:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initialiseWithConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","text":"SocialRadioConfig","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tunedRestDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<TunedRestDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)TunedRestDelegate"},{"text":") ","kind":"text"},{"text":"tunedRestDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"socialRadioStatusDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SocialRadioStatusObserverDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"text":") ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"socialRadioUIDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"id<SocialRadioUIDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The SocialRadio configuration.","type":"text"}],"type":"paragraph"}],"name":"config"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of feeding and renewing Tuned Global APIs access tokens. See TunedRestDelegate."}]}],"name":"tunedRestDelegate"},{"content":[{"inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from SocialRadio. See SocialRadioStatusObserverDelegate.","type":"text"}],"type":"paragraph"}],"name":"socialRadioStatusDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of presenting user interfaces the SocialRadio needs"}]}],"name":"socialRadioUIDelegate"},{"content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}]}]}],"type":"unorderedList"}],"name":"completion"}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","value":"SocialRadioUIDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","value":"SocialRadioConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","value":[{"kind":"identifier","text":"SocialRadioConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialise(config:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)\/title","value":"initialiseWithConfig:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialise(config:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/title","value":"SocialRadio","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/fragments","value":[{"kind":"identifier","text":"SocialRadio"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadio"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","value":"TunedRestDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","value":"SocialRadioStatusObserverDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}