{"metadata":{"title":"allStatusVariables()","navigatorTitle":[{"text":"allStatusVariables","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allStatusVariables","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"symbolKind":"method","externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus(cm)allStatusVariables","roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstatus\/allstatusvariables()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqstatus\/allstatusvariables()"]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus\/allStatusVariables()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allStatusVariables","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus"]]},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus":{"abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}],"url":"\/documentation\/automixiq\/automixiqstatus","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","role":"symbol","title":"AutomixIQStatus","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatus"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus/allStatusVariables()":{"abstract":[],"role":"symbol","url":"\/documentation\/automixiq\/automixiqstatus\/allstatusvariables()","title":"allStatusVariables()","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus\/allStatusVariables()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allStatusVariables","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"allStatusVariables","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"allStatusVariables"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allStatusVariables"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"allStatusVariables","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/title","value":"AutomixIQStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/fragments","value":[{"text":"AutomixIQStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus~1allStatusVariables()\/title","value":"allStatusVariables"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus~1allStatusVariables()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"allStatusVariables","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}