{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"]]},"metadata":{"title":"uniqueDeviceIdentifier()","required":true,"externalID":"c:@M@SocialRadio@objc(pl)TunedRestDelegate(im)uniqueDeviceIdentifier","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uniqueDeviceIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"uniqueDeviceIdentifier","kind":"identifier"}],"roleHeading":"Instance Method"},"abstract":[{"text":"Called by AutomixIQ to request the unique identifier for the users device as a string.","type":"text"},{"text":" ","type":"text"},{"text":"On iOS this is generally the Identifier for Vendor.","type":"text"},{"text":" ","type":"text"},{"text":"It can be any string as long as it is unique","type":"text"},{"text":" ","type":"text"},{"text":"AutomixIQ will use this string as the UniqueId if it needs to register the device for playback","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueDeviceIdentifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The unique device identifier as string","type":"text"}],"type":"paragraph"}]},{"mentions":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article"],"kind":"mentions"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedrestdelegate\/uniquedeviceidentifier()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/tunedrestdelegate\/uniquedeviceidentifier()"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate\/uniqueDeviceIdentifier()"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-article":{"abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}],"role":"article","type":"topic","title":"Initializing SocialRadio","kind":"article","url":"\/documentation\/socialradio\/initialising-socialradio-article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","url":"\/documentation\/socialradio\/tunedrestdelegate","kind":"symbol","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"type":"topic","title":"TunedRestDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate/uniqueDeviceIdentifier()":{"required":true,"kind":"symbol","url":"\/documentation\/socialradio\/tunedrestdelegate\/uniquedeviceidentifier()","abstract":[{"type":"text","text":"Called by AutomixIQ to request the unique identifier for the users device as a string."},{"text":" ","type":"text"},{"type":"text","text":"On iOS this is generally the Identifier for Vendor."},{"type":"text","text":" "},{"type":"text","text":"It can be any string as long as it is unique"},{"type":"text","text":" "},{"text":"AutomixIQ will use this string as the UniqueId if it needs to register the device for playback","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate\/uniqueDeviceIdentifier()","type":"topic","title":"uniqueDeviceIdentifier()","role":"symbol","navigatorTitle":[{"text":"uniqueDeviceIdentifier","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uniqueDeviceIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"uniqueDeviceIdentifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"uniqueDeviceIdentifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"uniqueDeviceIdentifier","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"The unique device identifier as string","type":"text"}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","op":"replace","value":"TunedRestDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate~1uniqueDeviceIdentifier()\/title","op":"replace","value":"uniqueDeviceIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate~1uniqueDeviceIdentifier()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"uniqueDeviceIdentifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}