{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playbackMode"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkstatusvariable\/playbackmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkstatusvariable\/playbackmode"]}],"metadata":{"navigatorTitle":[{"text":"AutomixSDKStatusVariablePlaybackMode","kind":"identifier"}],"externalID":"c:@M@SocialRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariablePlaybackMode","title":"AutomixSDKStatusVariable.playbackMode","symbolKind":"case","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackMode","kind":"identifier"}],"roleHeading":"Case","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable\/playbackMode"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable"]]},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable":{"title":"AutomixSDKStatusVariable","type":"topic","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/automixsdkstatusvariable","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusVariable"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable/playbackMode":{"role":"symbol","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlaybackMode","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackMode","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playbackMode","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable\/playbackMode","url":"\/documentation\/socialradio\/automixsdkstatusvariable\/playbackmode","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"AutomixSDKStatusVariablePlaybackMode","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"AutomixSDKStatusVariablePlaybackMode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AutomixSDKStatusVariablePlaybackMode","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"AutomixSDKStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/navigatorTitle","op":"replace"},{"value":"AutomixSDKStatusVariablePlaybackMode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable~1playbackMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable~1playbackMode\/fragments","value":[{"text":"AutomixSDKStatusVariablePlaybackMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}