{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"text":"AutomixIQStreamingDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"getAutomixStreamingDelegate()","symbolKind":"method","role":"symbol","externalID":"c:objc(cs)AutomixIQObjC(im)getAutomixStreamingDelegate","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"text":"AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate","kind":"typeIdentifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/getAutomixStreamingDelegate()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqobjc\/getautomixstreamingdelegate()"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC/getAutomixStreamingDelegate()":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/getAutomixStreamingDelegate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAutomixStreamingDelegate"},{"kind":"text","text":"() -> any "},{"kind":"typeIdentifier","text":"AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate"}],"url":"\/documentation\/automixiq\/automixiqobjc\/getautomixstreamingdelegate()","role":"symbol","kind":"symbol","type":"topic","abstract":[],"title":"getAutomixStreamingDelegate()"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate":{"navigatorTitle":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixiqstreamingdelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate","title":"AutomixIQStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC":{"title":"AutomixIQObjC","kind":"symbol","url":"\/documentation\/automixiq\/automixiqobjc","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC","role":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQObjC","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AutomixIQStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/fragments","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/navigatorTitle","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"op":"replace"}]}]}