{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig\/allowSongSuggestions"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowSongSuggestions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"metadata":{"title":"allowSongSuggestions","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowSongSuggestions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"allowSongSuggestions","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioFeatureSetConfig(py)allowSongSuggestions"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig"]]},"variants":[{"paths":["\/documentation\/socialradio\/socialradiofeaturesetconfig\/allowsongsuggestions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiofeaturesetconfig\/allowsongsuggestions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","type":"topic","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig/allowSongSuggestions":{"title":"allowSongSuggestions","navigatorTitle":[{"kind":"identifier","text":"allowSongSuggestions"}],"abstract":[],"type":"topic","url":"\/documentation\/socialradio\/socialradiofeaturesetconfig\/allowsongsuggestions","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig\/allowSongSuggestions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowSongSuggestions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig":{"title":"SocialRadioFeatureSetConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","abstract":[{"text":"Social Radio’s feature set options","type":"text"}],"url":"\/documentation\/socialradio\/socialradiofeaturesetconfig","type":"topic","role":"symbol","navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"allowSongSuggestions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"allowSongSuggestions"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"allowSongSuggestions","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig~1allowSongSuggestions\/title","value":"allowSongSuggestions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig~1allowSongSuggestions\/fragments","value":[{"text":"allowSongSuggestions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/title","value":"SocialRadioFeatureSetConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/fragments","value":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/navigatorTitle","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}]}]}]}