{"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyOn","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/errorcode\/sdkalreadyon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/errorcode\/sdkalreadyon"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sdkAlreadyOn","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeSdkAlreadyOn","navigatorTitle":[{"text":"ErrorCodeSdkAlreadyOn","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkAlreadyOn"}],"symbolKind":"case","modules":[{"name":"AutomixIQ"}],"title":"ErrorCode.sdkAlreadyOn"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/sdkAlreadyOn":{"url":"\/documentation\/automixiq\/errorcode\/sdkalreadyon","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyOn","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ErrorCodeSdkAlreadyOn","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkAlreadyOn","kind":"identifier"}],"title":"ErrorCode.sdkAlreadyOn"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/automixiq\/errorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"title":"ErrorCode"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"ErrorCodeSdkAlreadyOn","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyOn"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ErrorCodeSdkAlreadyOn","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeSdkAlreadyOn","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkAlreadyOn\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkAlreadyOn\/fragments","value":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyOn"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","value":"ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"ErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}