{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"trackExplicit","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack\/trackExplicit","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"True if this track has explicit content, false otherwise"}],"metadata":{"modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtapeTrack(py)trackExplicit","title":"trackExplicit","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"trackExplicit","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"trackExplicit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkmixtapetrack\/trackexplicit"]},{"paths":["\/documentation\/socialradio\/automixsdkmixtapetrack\/trackexplicit"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack"]]},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"title":"AutomixSDKMixtapeTrack","url":"\/documentation\/socialradio\/automixsdkmixtapetrack","kind":"symbol","abstract":[{"text":"AutomixSDKMixtapeTrack models a track in a mixtape","type":"text"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack/trackExplicit":{"abstract":[{"type":"text","text":"True if this track has explicit content, false otherwise"}],"url":"\/documentation\/socialradio\/automixsdkmixtapetrack\/trackexplicit","title":"trackExplicit","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack\/trackExplicit","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"trackExplicit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"trackExplicit","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"trackExplicit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"trackExplicit","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"trackExplicit","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/title","value":"AutomixSDKMixtapeTrack","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/fragments","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack~1trackExplicit\/title","value":"trackExplicit"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack~1trackExplicit\/fragments","value":[{"text":"trackExplicit","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}