{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkNotInitialisedVersionNoLongerSupported"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotInitialisedVersionNoLongerSupported"},"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"AutomixIQ"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported","title":"AutomixSDKErrorCode.sdkNotInitialisedVersionNoLongerSupported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/sdknotinitialisedversionnolongersupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/sdknotinitialisedversionnolongersupported"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"type":"topic","title":"AutomixSDKErrorCode","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","kind":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/sdkNotInitialisedVersionNoLongerSupported":{"title":"AutomixSDKErrorCode.sdkNotInitialisedVersionNoLongerSupported","type":"topic","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotInitialisedVersionNoLongerSupported","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkNotInitialisedVersionNoLongerSupported"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/sdknotinitialisedversionnolongersupported"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/title","op":"replace","value":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported"},{"value":[{"text":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}