{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate"]]},"variants":[{"paths":["\/documentation\/socialradio\/automixiqstreamingdelegate\/syncgettrackmetadata(trackid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqstreamingdelegate\/syncgettrackmetadata(trackid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate(im)syncGetTrackMetadataWithTrackId:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","text":"TunedTrackModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"SocialRadio"}],"title":"syncGetTrackMetadata(trackId:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","text":"TunedTrackModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The id of the track that AutomixIQ  is streaming.","type":"text"}]}],"name":"trackId"}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The metadata of the track, nil if not available.","type":"text"}]}],"kind":"content"},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-article"]}],"abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","url":"\/documentation\/socialradio\/automixiqstreamingdelegate","title":"AutomixIQStreamingDelegate","kind":"symbol","abstract":[{"text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/syncGetTrackMetadata(trackId:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/syncgettrackmetadata(trackid:)","required":true,"title":"syncGetTrackMetadata(trackId:)","kind":"symbol","abstract":[{"text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available.","type":"text"}],"navigatorTitle":[{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"TunedTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-with-custom-audio-and-social-layer-article":{"abstract":[{"type":"text","text":"How to validate your client and start using the SocialRadio SDK with custom audio track data and custom social layer."}],"title":"Initializing SocialRadio with custom audio and social layer","role":"article","url":"\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-and-social-layer-article","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-with-custom-audio-article":{"type":"topic","title":"Initializing SocialRadio with custom audio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-article","abstract":[{"type":"text","text":"How to validate your client and start using the SocialRadio SDK with custom audio track data."}],"kind":"article","role":"article","url":"\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"role":"symbol","kind":"symbol","abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","title":"TunedTrackModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/tunedtrackmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"syncGetTrackMetadataWithTrackId:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","text":"TunedTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel"},{"text":" *) ","kind":"text"},{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"trackId","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"trackId","content":[{"type":"paragraph","inlineContent":[{"text":"The id of the track that AutomixIQ  is streaming.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The metadata of the track, nil if not available."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title","value":"AutomixIQStreamingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/title","value":"syncGetTrackMetadataWithTrackId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title","value":"TunedTrackModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments","value":[{"text":"TunedTrackModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle","value":[{"text":"TunedTrackModel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}