{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixId"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/mixid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/mixid"]}],"metadata":{"navigatorTitle":[{"text":"SocialRadioStatusVariableMixId","kind":"identifier"}],"title":"SocialRadioStatusVariable.mixId","role":"symbol","roleHeading":"Case","externalID":"c:@M@SocialRadio@E@SocialRadioStatusVariable@SocialRadioStatusVariableMixId","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixId","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/mixId"},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable/mixId":{"title":"SocialRadioStatusVariable.mixId","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/mixId","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariableMixId"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixId"}],"type":"topic","url":"\/documentation\/socialradio\/socialradiostatusvariable\/mixid","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","url":"\/documentation\/socialradio","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","role":"symbol","abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","title":"SocialRadioStatusVariable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusVariable"}],"url":"\/documentation\/socialradio\/socialradiostatusvariable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SocialRadioStatusVariableMixId","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SocialRadioStatusVariableMixId","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SocialRadioStatusVariableMixId","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SocialRadioStatusVariableMixId","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1mixId\/title","op":"replace"},{"value":[{"text":"SocialRadioStatusVariableMixId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1mixId\/fragments","op":"replace"},{"value":"SocialRadioStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title","op":"replace"},{"value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}