{"variants":[{"paths":["\/documentation\/socialradio\/radiosdk\/initialise(config:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/radiosdk\/initialise(config:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)"]}],"metadata":{"symbolKind":"method","role":"symbol","title":"initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","externalID":"c:@M@SocialRadio@objc(cs)RadioSDK(cm)initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","modules":[{"name":"SocialRadio"}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RadioSDKConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"radioUIDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)RadioUIDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": "},{"text":"TunedMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","kind":"identifier"}]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK"]]},"abstract":[{"text":"Initialiser for Radio SDK to work against a Tuned Global’s Store and Tuned Global’s APIs.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RadioSDKConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedDelegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIDelegate"},{"text":": ","kind":"text"},{"text":"RadioUIDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)RadioUIDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TunedMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The RadioSDK configuration."}],"type":"paragraph"}],"name":"config"},{"name":"tunedDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of feeding and renewing Tuned Global APIs access tokens. See TunedRestDelegate.","type":"text"}]}]},{"name":"statusDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from Automix SDK. See AutomixSDKStatusObserverDelegate.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of presenting user interfaces the Radio SDK needs"}]}],"name":"radioUIDelegate"},{"name":"musicCacheDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate providing cached track data and metadata.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedMusicCacheDelegate":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"title":"TunedMusicCacheDelegate","abstract":[{"text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"url":"\/documentation\/socialradio\/tunedmusiccachedelegate","navigatorTitle":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)":{"navigatorTitle":[{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RadioSDKConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKConfig"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedRestDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate"},{"kind":"text","text":", "},{"text":"radioUIDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)RadioUIDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"musicCacheDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Initialiser for Radio SDK to work against a Tuned Global’s Store and Tuned Global’s APIs."},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"title":"initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","url":"\/documentation\/socialradio\/radiosdk\/initialise(config:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK","navigatorTitle":[{"text":"RadioSDK","kind":"identifier"}],"url":"\/documentation\/socialradio\/radiosdk","abstract":[{"type":"text","text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"type":"topic","kind":"symbol","title":"RadioSDK","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDK"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKConfig":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","title":"RadioSDKConfig","abstract":[],"url":"\/documentation\/socialradio\/radiosdkconfig","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKConfig"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate":{"role":"symbol","title":"RadioUIDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioUIDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RadioUIDelegate"}],"abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"url":"\/documentation\/socialradio\/radiouidelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedRestDelegate"}],"title":"TunedRestDelegate","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"url":"\/documentation\/socialradio\/tunedrestdelegate","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate":{"title":"AutomixSDKStatusObserverDelegate","url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RadioSDKConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"config"},{"text":" ","kind":"text"},{"text":"tunedDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<TunedRestDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)TunedRestDelegate"},{"text":") ","kind":"text"},{"text":"tunedDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"statusDelegate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"id<AutomixSDKStatusObserverDelegate>"},{"text":") ","kind":"text"},{"text":"statusDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"radioUIDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)RadioUIDelegate","text":"id<RadioUIDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"radioUIDelegate"},{"kind":"text","text":" "},{"text":"musicCacheDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<TunedMusicCacheDelegate>","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"musicCacheDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The RadioSDK configuration."}]}],"name":"config"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of feeding and renewing Tuned Global APIs access tokens. See TunedRestDelegate."}]}],"name":"tunedDelegate"},{"name":"statusDelegate","content":[{"inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from Automix SDK. See AutomixSDKStatusObserverDelegate.","type":"text"}],"type":"paragraph"}]},{"name":"radioUIDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of presenting user interfaces the Radio SDK needs","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The delegate providing cached track data and metadata."}],"type":"paragraph"}],"name":"musicCacheDelegate"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/title","op":"replace","value":"TunedMusicCacheDelegate"},{"op":"replace","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/navigatorTitle","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}]},{"value":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/title","op":"replace","value":"RadioSDK"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/fragments","value":[{"kind":"identifier","text":"RadioSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDK"}]},{"value":"RadioSDKConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/navigatorTitle","value":[{"text":"RadioSDKConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/title","value":"RadioUIDelegate","op":"replace"},{"value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/fragments"},{"value":[{"kind":"identifier","text":"RadioUIDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/navigatorTitle"},{"value":"TunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title"},{"value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}