{"metadata":{"role":"symbol","navigatorTitle":[{"text":"reportUserWithIdentifier:completion:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@SocialRadio@objc(cs)RadioSDK(im)reportUserWithIdentifier:completion:","symbolKind":"method","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportUser"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"reportUser(identifier:completion:)"},"abstract":[{"type":"text","text":"Submits a report for inappropriate content for a user."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK"]]},"variants":[{"paths":["\/documentation\/socialradio\/radiosdk\/reportuser(identifier:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/radiosdk\/reportuser(identifier:completion:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/reportUser(identifier:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportUser"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}]}]},{"kind":"parameters","parameters":[{"name":"identifier","content":[{"inlineContent":[{"text":"The identifier of the user to report","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/reportUser(identifier:completion:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/reportUser(identifier:completion:)","abstract":[{"type":"text","text":"Submits a report for inappropriate content for a user."}],"navigatorTitle":[{"text":"reportUserWithIdentifier:completion:","kind":"identifier"}],"title":"reportUser(identifier:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportUser"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"url":"\/documentation\/socialradio\/radiosdk\/reportuser(identifier:completion:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK","navigatorTitle":[{"text":"RadioSDK","kind":"identifier"}],"url":"\/documentation\/socialradio\/radiosdk","abstract":[{"type":"text","text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"type":"topic","kind":"symbol","title":"RadioSDK","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDK"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"reportUserWithIdentifier:completion:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reportUserWithIdentifier:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"reportUserWithIdentifier:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The identifier of the user to report","type":"text"}],"type":"paragraph"}],"name":"identifier"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}]}]}},{"op":"replace","value":"reportUserWithIdentifier:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1reportUser(identifier:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reportUserWithIdentifier:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1reportUser(identifier:completion:)\/fragments"},{"op":"replace","value":"RadioSDK","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/fragments","value":[{"text":"RadioSDK","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"RadioSDK"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}