{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"variables"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixIQStatus","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"AutomixIQ"}],"title":"statusChanged(variables:status:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"statusChangedWithVariables:status:"}],"role":"symbol","required":true,"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate(im)statusChangedWithVariables:status:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"variables"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus","text":"AutomixIQStatus"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of AutomixIQStatusVariable that changed since last time this method was called, or since AutomixIQ was initialised."}]}],"name":"variables"},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"text":"The current status of AutomixIQ","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/automixiq\/automixiqstatusobserverdelegate\/statuschanged(variables:status:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqstatusobserverdelegate\/statuschanged(variables:status:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate\/statusChanged(variables:status:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Called when the status of AutomixIQ changes"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"title":"AutomixIQStatusObserverDelegate","abstract":[{"text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate/statusChanged(variables:status:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"variables","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus","text":"AutomixIQStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"statusChanged(variables:status:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate\/statusChanged(variables:status:)","abstract":[{"type":"text","text":"Called when the status of AutomixIQ changes"}],"type":"topic","url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate\/statuschanged(variables:status:)","kind":"symbol","role":"symbol","required":true,"navigatorTitle":[{"text":"statusChangedWithVariables:status:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","type":"topic","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus":{"url":"\/documentation\/automixiq\/automixiqstatus","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatus"}],"kind":"symbol","title":"AutomixIQStatus","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"statusChangedWithVariables:status:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"statusChangedWithVariables:status:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"statusChangedWithVariables:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"variables"},{"kind":"text","text":" "},{"kind":"identifier","text":"status:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","kind":"typeIdentifier","text":"AutomixIQStatus","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"variables","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of AutomixIQStatusVariable that changed since last time this method was called, or since AutomixIQ was initialised."}]}]},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current status of AutomixIQ"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title","value":"AutomixIQStatusObserverDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate~1statusChanged(variables:status:)\/title","value":"statusChangedWithVariables:status:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate~1statusChanged(variables:status:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"statusChangedWithVariables:status:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"AutomixIQStatus","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/title"},{"op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/navigatorTitle","value":[{"text":"AutomixIQStatus","kind":"identifier"}],"op":"replace"}]}]}