{"variants":[{"paths":["\/documentation\/socialradio\/socialradiosocialcredentials\/expiresin"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials\/expiresIn"},"metadata":{"externalID":"s:11SocialRadio0abA11CredentialsC9expiresInSiSgvp","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"expiresIn","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"expiresIn","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expiresIn"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"type":"text","text":"The time remaining for this token to expire."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioSocialCredentials":{"url":"\/documentation\/socialradio\/socialradiosocialcredentials","title":"SocialRadioSocialCredentials","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials","type":"topic","abstract":[{"type":"text","text":"SocialRadioSocialCredentials models credentials to access social REST APIs."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioSocialCredentials"}],"navigatorTitle":[{"text":"SocialRadioSocialCredentials","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioSocialCredentials/expiresIn":{"title":"expiresIn","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials\/expiresIn","kind":"symbol","url":"\/documentation\/socialradio\/socialradiosocialcredentials\/expiresin","abstract":[{"text":"The time remaining for this token to expire.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"expiresIn","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"title":"SocialRadio","kind":"symbol","url":"\/documentation\/socialradio"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioSocialCredentials\/title","value":"SocialRadioSocialCredentials","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioSocialCredentials"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioSocialCredentials\/fragments"},{"value":[{"text":"SocialRadioSocialCredentials","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioSocialCredentials\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}