{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canBack","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"SocialRadio"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"AutomixIQStatusVariableCanBack","kind":"identifier"}],"title":"AutomixIQStatusVariable.canBack","externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariableCanBack","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canBack"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/canback"]},{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/canback"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBack"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canBack":{"kind":"symbol","url":"\/documentation\/socialradio\/automixiqstatusvariable\/canback","role":"symbol","type":"topic","title":"AutomixIQStatusVariable.canBack","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canBack","abstract":[],"navigatorTitle":[{"text":"AutomixIQStatusVariableCanBack","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canBack"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"type":"topic","kind":"symbol","title":"AutomixIQStatusVariable","url":"\/documentation\/socialradio\/automixiqstatusvariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"AutomixIQStatusVariableCanBack","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanBack"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixIQStatusVariableCanBack"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canBack\/title","value":"AutomixIQStatusVariableCanBack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canBack\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanBack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title","value":"AutomixIQStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}