{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH","doc:\/\/org.cocoapods.SocialRadio\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadio playback mode"}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"],"generated":true,"title":"Data models","anchor":"Data-models"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"roleHeading":"Enumeration","externalID":"c:@M@SocialRadio@E@SocialRadioPlaybackMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"title":"SocialRadioPlaybackMode","role":"symbol","symbolKind":"enum","modules":[{"name":"SocialRadio"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradioplaybackmode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradioplaybackmode"]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/automix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/liveConsumption","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/liveCreation"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioPlaybackMode"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode/Equatable-Implementations":{"abstract":[],"type":"topic","kind":"article","title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/Equatable-Implementations","url":"\/documentation\/socialradio\/socialradioplaybackmode\/equatable-implementations"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioList":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioList"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioList"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","title":"SocialRadioList","kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/socialradiolist","type":"topic","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode":{"role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/socialradioplaybackmode","type":"topic","title":"SocialRadioPlaybackMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","abstract":[{"type":"text","text":"SocialRadio playback mode"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCredentials":{"url":"\/documentation\/socialradio\/socialradiocredentials","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioCredentials"}],"title":"SocialRadioCredentials","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioCredentials"}],"abstract":[{"text":"SocialRadioCredentials models credentials to access social REST APIs.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatus":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","url":"\/documentation\/socialradio\/socialradiostatus","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioStatus","kind":"identifier"}],"title":"SocialRadioStatus","abstract":[{"type":"text","text":"SocialRadioStatus models the State of the AutomixIQ during playback."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage":{"abstract":[{"type":"text","text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape"}],"navigatorTitle":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","url":"\/documentation\/socialradio\/socialradiomixtapetrackimage","title":"SocialRadioMixtapeTrackImage"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Data-models-article":{"url":"\/documentation\/socialradio\/data-models-article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","abstract":[{"text":"How data is passed to and from SocialRadio","type":"text"}],"kind":"article","role":"article","title":"Data models","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeLite":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"title":"SocialRadioMixtapeLite","url":"\/documentation\/socialradio\/socialradiomixtapelite","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"type":"topic","abstract":[{"text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode/liveCreation":{"navigatorTitle":[{"text":"SocialRadioPlaybackModeLiveCreation","kind":"identifier"}],"title":"SocialRadioPlaybackMode.liveCreation","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveCreation","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/socialradioplaybackmode\/livecreation","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/liveCreation"},"doc://org.cocoapods.SocialRadio/SY":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode/automix":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioPlaybackModeAutomix"}],"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automix"}],"type":"topic","kind":"symbol","title":"SocialRadioPlaybackMode.automix","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/automix","url":"\/documentation\/socialradio\/socialradioplaybackmode\/automix"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode/init(rawValue:)":{"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/init(rawValue:)","url":"\/documentation\/socialradio\/socialradioplaybackmode\/init(rawvalue:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment":{"title":"SocialRadioComment","url":"\/documentation\/socialradio\/socialradiocomment","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioComment"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioComment models a comment"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioComment"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"title":"SocialRadioStatusVariable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","abstract":[{"type":"text","text":"SocialRadio status variable type"}],"navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/socialradiostatusvariable","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser":{"title":"SocialRadioUser","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiouser","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUser","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioUser models a user"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCommentTag":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","navigatorTitle":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"role":"symbol","abstract":[{"type":"text","text":"SocialRadioCommentTag models a user tag in a comment"}],"title":"SocialRadioCommentTag","url":"\/documentation\/socialradio\/socialradiocommenttag","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioCommentTag"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioGenericList":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioGenericList"}],"abstract":[{"text":"SocialRadioGenericList models a list of things","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","title":"SocialRadioGenericList","kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/socialradiogenericlist","navigatorTitle":[{"kind":"identifier","text":"SocialRadioGenericList"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"role":"collection","kind":"symbol","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode/RawRepresentable-Implementations":{"abstract":[],"type":"topic","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/RawRepresentable-Implementations","url":"\/documentation\/socialradio\/socialradioplaybackmode\/rawrepresentable-implementations"},"doc://org.cocoapods.SocialRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape":{"abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"kind":"symbol","title":"SocialRadioMixtape","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtape"}],"url":"\/documentation\/socialradio\/socialradiomixtape"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioWaveformBlob":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","abstract":[{"text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track","type":"text"}],"url":"\/documentation\/socialradio\/socialradiowaveformblob","type":"topic","kind":"symbol","title":"SocialRadioWaveformBlob","navigatorTitle":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","type":"topic","abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"title":"TunedTrackModel","url":"\/documentation\/socialradio\/tunedtrackmodel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedArtistModel":{"url":"\/documentation\/socialradio\/tunedartistmodel","navigatorTitle":[{"text":"TunedArtistModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedArtistModel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","role":"symbol","abstract":[{"text":"TunedArtistModel models an artist.","type":"text"}],"title":"TunedArtistModel","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode/liveConsumption":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioPlaybackModeLiveConsumption"}],"type":"topic","abstract":[],"url":"\/documentation\/socialradio\/socialradioplaybackmode\/liveconsumption","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveConsumption"}],"title":"SocialRadioPlaybackMode.liveConsumption","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/liveConsumption"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack":{"abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"url":"\/documentation\/socialradio\/socialradiomixtapetrack","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","role":"symbol","type":"topic","navigatorTitle":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"title":"SocialRadioMixtapeTrack","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SocialRadioPlaybackMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/automix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/liveConsumption","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/liveCreation"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Data-models","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel"],"title":"Data models"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioPlaybackMode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/title","value":"SocialRadioList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/fragments","value":[{"text":"SocialRadioList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioList"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/title","value":"SocialRadioPlaybackMode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/fragments","value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/title","value":"SocialRadioCredentials"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/fragments","value":[{"text":"SocialRadioCredentials","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/navigatorTitle","value":[{"text":"SocialRadioCredentials","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/title","value":"SocialRadioStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/fragments","value":[{"text":"SocialRadioStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/title","value":"SocialRadioMixtapeTrackImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/fragments","value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/title","value":"SocialRadioMixtapeLite"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode~1liveCreation\/title","value":"SocialRadioPlaybackModeLiveCreation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode~1liveCreation\/fragments","value":[{"text":"SocialRadioPlaybackModeLiveCreation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode~1automix\/title","value":"SocialRadioPlaybackModeAutomix"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode~1automix\/fragments","value":[{"text":"SocialRadioPlaybackModeAutomix","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/title","value":"SocialRadioComment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/fragments","value":[{"text":"SocialRadioComment","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioComment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title","value":"SocialRadioStatusVariable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/title","value":"SocialRadioUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/fragments","value":[{"text":"SocialRadioUser","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/navigatorTitle","value":[{"text":"SocialRadioUser","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/title","value":"SocialRadioCommentTag"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/fragments","value":[{"kind":"identifier","text":"SocialRadioCommentTag"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/navigatorTitle","value":[{"text":"SocialRadioCommentTag","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/title","value":"SocialRadioMixtape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtape"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/navigatorTitle","value":[{"text":"SocialRadioMixtape","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/title","value":"SocialRadioWaveformBlob"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/fragments","value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title","value":"TunedTrackModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments","value":[{"text":"TunedTrackModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle","value":[{"kind":"identifier","text":"TunedTrackModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/title","value":"TunedArtistModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/fragments","value":[{"text":"TunedArtistModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/navigatorTitle","value":[{"text":"TunedArtistModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode~1liveConsumption\/title","value":"SocialRadioPlaybackModeLiveConsumption"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode~1liveConsumption\/fragments","value":[{"text":"SocialRadioPlaybackModeLiveConsumption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/title","value":"SocialRadioMixtapeTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]}]}]}