{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiosocialcredentials\/init(dictionary:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"externalID":"s:11SocialRadio0abA11CredentialsC10dictionaryACSgSDySSypG_tcfc","role":"symbol","roleHeading":"Initializer","title":"init(dictionary:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"symbolKind":"init","modules":[{"name":"SocialRadio"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials\/init(dictionary:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioSocialCredentials/init(dictionary:)":{"title":"init(dictionary:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"url":"\/documentation\/socialradio\/socialradiosocialcredentials\/init(dictionary:)","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials\/init(dictionary:)","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioSocialCredentials":{"title":"SocialRadioSocialCredentials","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioSocialCredentials"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioSocialCredentials"}],"abstract":[{"text":"SocialRadioSocialCredentials models credentials to access social REST APIs.","type":"text"}],"url":"\/documentation\/socialradio\/socialradiosocialcredentials","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioSocialCredentials\/title","op":"replace","value":"SocialRadioSocialCredentials"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioSocialCredentials\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioSocialCredentials"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioSocialCredentials\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioSocialCredentials"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}