{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLoopingNoLoopingTrack"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/startLoopingNoLoopingTrack","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/errorcode\/startloopingnoloopingtrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode\/startloopingnoloopingtrack"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"metadata":{"roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeStartLoopingNoLoopingTrack","symbolKind":"case","title":"ErrorCode.startLoopingNoLoopingTrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLoopingNoLoopingTrack"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"modules":[{"name":"AutomixIQ"}],"role":"symbol"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","type":"topic","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorCode"}],"abstract":[],"type":"topic","title":"ErrorCode","url":"\/documentation\/automixiq\/errorcode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/startLoopingNoLoopingTrack":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/startLoopingNoLoopingTrack","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startLoopingNoLoopingTrack"}],"abstract":[],"type":"topic","title":"ErrorCode.startLoopingNoLoopingTrack","url":"\/documentation\/automixiq\/errorcode\/startloopingnoloopingtrack","navigatorTitle":[{"text":"ErrorCodeStartLoopingNoLoopingTrack","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ErrorCodeStartLoopingNoLoopingTrack","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ErrorCodeStartLoopingNoLoopingTrack","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle"},{"op":"replace","value":"ErrorCodeStartLoopingNoLoopingTrack","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1startLoopingNoLoopingTrack\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1startLoopingNoLoopingTrack\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}