{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/errorcode\/sdkalreadyinitialised"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode\/sdkalreadyinitialised"]}],"metadata":{"symbolKind":"case","title":"ErrorCode.sdkAlreadyInitialised","roleHeading":"Case","role":"symbol","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeSdkAlreadyInitialised","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkAlreadyInitialised","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyInitialised"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkAlreadyInitialised"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/sdkAlreadyInitialised":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyInitialised","url":"\/documentation\/automixiq\/errorcode\/sdkalreadyinitialised","title":"ErrorCode.sdkAlreadyInitialised","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkAlreadyInitialised"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"kind":"symbol","title":"ErrorCode","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","url":"\/documentation\/automixiq\/errorcode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ErrorCodeSdkAlreadyInitialised","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ErrorCodeSdkAlreadyInitialised","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeSdkAlreadyInitialised","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkAlreadyInitialised\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkAlreadyInitialised\/fragments"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}