{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/terminate()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Method","symbolKind":"method","title":"terminate()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"terminate","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"terminate"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQ(im)terminate"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"terminate","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/socialradio\/automixiq\/terminate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiq\/terminate()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ"]]},"abstract":[{"text":"Terminates \/ deinitialises AutomixIQ. Call this on applicationWillTerminate, or whenever you no longer need it.","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}],"type":"topic","title":"AutomixIQ","url":"\/documentation\/socialradio\/automixiq","navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ/terminate()":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/terminate()","type":"topic","url":"\/documentation\/socialradio\/automixiq\/terminate()","abstract":[{"text":"Terminates \/ deinitialises AutomixIQ. Call this on applicationWillTerminate, or whenever you no longer need it.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"terminate","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"terminate","kind":"identifier"},{"text":"()","kind":"text"}],"title":"terminate()","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"terminate","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"terminate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"terminate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixIQ","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title"},{"value":[{"text":"AutomixIQ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments"},{"value":[{"text":"AutomixIQ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle"},{"value":"terminate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1terminate()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"terminate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1terminate()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}