{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMetadata"},{"kind":"text","text":" "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","text":"TunedAdModel"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/CompletionWithError","text":"CompletionWithError","preciseIdentifier":"c:AutomixIQ.h@T@CompletionWithError"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]},{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMetadata","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","text":"TunedAdModel","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/addAds(withMetadata:completion:)"},"sections":[],"metadata":{"externalID":"c:objc(cs)AutomixIQObjC(im)addAdsWithMetadata:completion:","role":"symbol","modules":[{"name":"SocialRadio"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionWithError","preciseIdentifier":"c:AutomixIQ.h@T@CompletionWithError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"addAds(withMetadata:completion:)","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqobjc\/addads(withmetadata:completion:)"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC/addAds(withMetadata:completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMetadata"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","kind":"typeIdentifier","text":"TunedAdModel"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AutomixIQ.h@T@CompletionWithError","kind":"typeIdentifier","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"url":"\/documentation\/socialradio\/automixiqobjc\/addads(withmetadata:completion:)","title":"addAds(withMetadata:completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/addAds(withMetadata:completion:)","kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAdModel":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","type":"topic","url":"\/documentation\/socialradio\/tunedadmodel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAdModel"}],"kind":"symbol","title":"TunedAdModel","navigatorTitle":[{"kind":"identifier","text":"TunedAdModel"}],"abstract":[{"type":"text","text":"TunedAdModel models a Ad."}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"url":"\/documentation\/socialradio\/automixiqobjc","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQObjC","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}],"role":"symbol","title":"AutomixIQObjC","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/CompletionWithError":{"url":"\/documentation\/socialradio\/completionwitherror","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/CompletionWithError","type":"topic","title":"CompletionWithError","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"CompletionWithError","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CompletionWithError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"TunedAdModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/title"},{"value":[{"text":"TunedAdModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/fragments"},{"value":[{"kind":"identifier","text":"TunedAdModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}