{"abstract":[{"type":"text","text":"The duration of the left transition in track time, in seconds"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftTransitionDuration"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqwaveformmodel\/lefttransitionduration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqwaveformmodel\/lefttransitionduration"]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"leftTransitionDuration","externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQWaveformModel(py)leftTransitionDuration","navigatorTitle":[{"text":"leftTransitionDuration","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"leftTransitionDuration","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel\/leftTransitionDuration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel"]]},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQWaveformModel":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel","kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixiqwaveformmodel","title":"AutomixIQWaveformModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQWaveformModel/leftTransitionDuration":{"abstract":[{"type":"text","text":"The duration of the left transition in track time, in seconds"}],"navigatorTitle":[{"kind":"identifier","text":"leftTransitionDuration"}],"url":"\/documentation\/automixiq\/automixiqwaveformmodel\/lefttransitionduration","type":"topic","title":"leftTransitionDuration","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel\/leftTransitionDuration","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftTransitionDuration","kind":"identifier"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"leftTransitionDuration"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"leftTransitionDuration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"leftTransitionDuration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AutomixIQWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/title","op":"replace"},{"value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/fragments","op":"replace"},{"value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/navigatorTitle","op":"replace"},{"value":"leftTransitionDuration","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel~1leftTransitionDuration\/title","op":"replace"},{"value":[{"text":"leftTransitionDuration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel~1leftTransitionDuration\/fragments","op":"replace"}]}]}