{"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioFeatureSetConfig(py)maximumTimerStatusUpdatesPerSecond","title":"maximumTimerStatusUpdatesPerSecond","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumTimerStatusUpdatesPerSecond","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"maximumTimerStatusUpdatesPerSecond","kind":"identifier"}],"modules":[{"name":"SocialRadio"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig\/maximumTimerStatusUpdatesPerSecond"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTimerStatusUpdatesPerSecond"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiofeaturesetconfig\/maximumtimerstatusupdatespersecond"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiofeaturesetconfig\/maximumtimerstatusupdatespersecond"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig"]]},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig":{"abstract":[{"type":"text","text":"Social Radio’s feature set options"}],"url":"\/documentation\/socialradio\/socialradiofeaturesetconfig","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"title":"SocialRadioFeatureSetConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig/maximumTimerStatusUpdatesPerSecond":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maximumTimerStatusUpdatesPerSecond","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig\/maximumTimerStatusUpdatesPerSecond","url":"\/documentation\/socialradio\/socialradiofeaturesetconfig\/maximumtimerstatusupdatespersecond","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"maximumTimerStatusUpdatesPerSecond","kind":"identifier"}],"type":"topic","title":"maximumTimerStatusUpdatesPerSecond"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"maximumTimerStatusUpdatesPerSecond","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maximumTimerStatusUpdatesPerSecond"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"maximumTimerStatusUpdatesPerSecond","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/title","value":"SocialRadioFeatureSetConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/fragments","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/navigatorTitle","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig~1maximumTimerStatusUpdatesPerSecond\/title","value":"maximumTimerStatusUpdatesPerSecond","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig~1maximumTimerStatusUpdatesPerSecond\/fragments","value":[{"kind":"identifier","text":"maximumTimerStatusUpdatesPerSecond"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}