{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/tunedloglevel\/loglevelinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/tunedloglevel\/loglevelinfo"]}],"metadata":{"modules":[{"name":"AutomixIQ"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelInfo","kind":"identifier"}],"title":"TunedLogLevel.logLevelInfo","navigatorTitle":[{"text":"TunedLogLevelLogLevelInfo","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@TunedLogLevel@TunedLogLevelLogLevelInfo"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelInfo","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedLogLevel\/logLevelInfo","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedLogLevel"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedLogLevel":{"navigatorTitle":[{"kind":"identifier","text":"TunedLogLevel"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedLogLevel"}],"abstract":[{"text":"TunedLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"type":"topic","title":"TunedLogLevel","url":"\/documentation\/automixiq\/tunedloglevel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedLogLevel","kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedLogLevel/logLevelInfo":{"type":"topic","url":"\/documentation\/automixiq\/tunedloglevel\/loglevelinfo","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedLogLevel\/logLevelInfo","abstract":[],"title":"TunedLogLevel.logLevelInfo","role":"symbol","navigatorTitle":[{"text":"TunedLogLevelLogLevelInfo","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelInfo","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"TunedLogLevelLogLevelInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TunedLogLevelLogLevelInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"TunedLogLevelLogLevelInfo","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedLogLevel\/title","value":"TunedLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedLogLevel\/fragments","value":[{"text":"TunedLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedLogLevel\/navigatorTitle","value":[{"text":"TunedLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedLogLevel~1logLevelInfo\/title","value":"TunedLogLevelLogLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedLogLevel~1logLevelInfo\/fragments","value":[{"kind":"identifier","text":"TunedLogLevelLogLevelInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}