{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/socialradiolite\/socialradiostatusvariable\/failedtrackloadidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiostatusvariable\/failedtrackloadidentifiers"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable\/failedTrackLoadIdentifiers","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable"]]},"metadata":{"externalID":"c:@M@SocialRadioLite@E@SocialRadioStatusVariable@SocialRadioStatusVariableFailedTrackLoadIdentifiers","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"roleHeading":"Case","title":"SocialRadioStatusVariable.failedTrackLoadIdentifiers","modules":[{"name":"SocialRadioLite"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers"}]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable":{"abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"title":"SocialRadioStatusVariable","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiostatusvariable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable/failedTrackLoadIdentifiers":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"title":"SocialRadioStatusVariable.failedTrackLoadIdentifiers","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable\/failedTrackLoadIdentifiers","type":"topic","url":"\/documentation\/socialradiolite\/socialradiostatusvariable\/failedtrackloadidentifiers","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SocialRadioStatusVariableFailedTrackLoadIdentifiers","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SocialRadioStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/title"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable~1failedTrackLoadIdentifiers\/title","op":"replace","value":"SocialRadioStatusVariableFailedTrackLoadIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable~1failedTrackLoadIdentifiers\/fragments","value":[{"text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}]}]}]}