{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable\/mixing","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"SocialRadioStatusVariableMixing","kind":"identifier"}],"role":"symbol","modules":[{"name":"SocialRadioLite"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixing","kind":"identifier"}],"roleHeading":"Case","title":"SocialRadioStatusVariable.mixing","externalID":"c:@M@SocialRadioLite@E@SocialRadioStatusVariable@SocialRadioStatusVariableMixing","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixing"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiostatusvariable\/mixing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiostatusvariable\/mixing"]}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable":{"abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"title":"SocialRadioStatusVariable","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiostatusvariable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable/mixing":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixing"}],"url":"\/documentation\/socialradiolite\/socialradiostatusvariable\/mixing","navigatorTitle":[{"text":"SocialRadioStatusVariableMixing","kind":"identifier"}],"title":"SocialRadioStatusVariable.mixing","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable\/mixing","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SocialRadioStatusVariableMixing"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"SocialRadioStatusVariableMixing","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SocialRadioStatusVariableMixing","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"SocialRadioStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/title"},{"value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable~1mixing\/title","value":"SocialRadioStatusVariableMixing"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable~1mixing\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusVariableMixing"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}