{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable\/mixId","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SocialRadioLite@E@SocialRadioStatusVariable@SocialRadioStatusVariableMixId","title":"SocialRadioStatusVariable.mixId","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariableMixId"}],"modules":[{"name":"SocialRadioLite"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixId","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixId"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiostatusvariable\/mixid"]},{"paths":["\/documentation\/socialradiolite\/socialradiostatusvariable\/mixid"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable":{"abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"title":"SocialRadioStatusVariable","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiostatusvariable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable/mixId":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable\/mixId","type":"topic","url":"\/documentation\/socialradiolite\/socialradiostatusvariable\/mixid","abstract":[],"role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusVariableMixId","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixId"}],"title":"SocialRadioStatusVariable.mixId"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SocialRadioStatusVariableMixId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"SocialRadioStatusVariableMixId","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SocialRadioStatusVariableMixId"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/title","value":"SocialRadioStatusVariable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable~1mixId\/title","value":"SocialRadioStatusVariableMixId"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariableMixId"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable~1mixId\/fragments","op":"replace"}]}]}