{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable\/playingTrackIdentifier","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiostatusvariable\/playingtrackidentifier"]},{"paths":["\/documentation\/socialradiolite\/socialradiostatusvariable\/playingtrackidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackIdentifier","kind":"identifier"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariablePlayingTrackIdentifier"}],"modules":[{"name":"SocialRadioLite"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"playingTrackIdentifier","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@SocialRadioLite@E@SocialRadioStatusVariable@SocialRadioStatusVariablePlayingTrackIdentifier","title":"SocialRadioStatusVariable.playingTrackIdentifier","symbolKind":"case"},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable/playingTrackIdentifier":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"playingTrackIdentifier","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiostatusvariable\/playingtrackidentifier","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariablePlayingTrackIdentifier"}],"title":"SocialRadioStatusVariable.playingTrackIdentifier","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable\/playingTrackIdentifier","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable":{"abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"title":"SocialRadioStatusVariable","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiostatusvariable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SocialRadioStatusVariablePlayingTrackIdentifier","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusVariablePlayingTrackIdentifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SocialRadioStatusVariablePlayingTrackIdentifier","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SocialRadioStatusVariablePlayingTrackIdentifier","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable~1playingTrackIdentifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable~1playingTrackIdentifier\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusVariablePlayingTrackIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/title","value":"SocialRadioStatusVariable"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}]}]}]}