{"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeTiny","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioUIConfig(py)radioUIFontSizeTiny","modules":[{"name":"SocialRadio"}],"role":"symbol","title":"radioUIFontSizeTiny","symbolKind":"property","navigatorTitle":[{"text":"radioUIFontSizeTiny","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/radioUIFontSizeTiny"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeTiny","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/socialradiouiconfig\/radiouifontsizetiny"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiouiconfig\/radiouifontsizetiny"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig/radioUIFontSizeTiny":{"role":"symbol","abstract":[],"url":"\/documentation\/socialradio\/socialradiouiconfig\/radiouifontsizetiny","title":"radioUIFontSizeTiny","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeTiny"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeTiny"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/radioUIFontSizeTiny"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","url":"\/documentation\/socialradio\/socialradiouiconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUIConfig"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"abstract":[{"type":"text","text":"Social Radio UI options"}],"type":"topic","title":"SocialRadioUIConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/socialradio","title":"SocialRadio"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"radioUIFontSizeTiny"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"radioUIFontSizeTiny"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeTiny"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1radioUIFontSizeTiny\/title","value":"radioUIFontSizeTiny"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1radioUIFontSizeTiny\/fragments","value":[{"text":"radioUIFontSizeTiny","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/title","value":"SocialRadioUIConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/fragments","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}