{"variants":[{"paths":["\/documentation\/socialradio\/starting-a-broadcast-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/starting-a-broadcast-article"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"metadata":{"modules":[{"name":"SocialRadio"}],"title":"Starting a broadcast","role":"article","roleHeading":"Article"},"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Creating a draft","type":"heading","anchor":"Creating-a-draft"},{"inlineContent":[{"text":"When you want to start a radio broadcast with a set of tracks, you use ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","isActive":true,"type":"reference"},{"text":" as shown below:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["public class MyApplication {","    \/\/ ...","    func didPressRadioSessionButton() -> Void {","        let identifiers = myIdentifiers","        SocialRadio.instance.startRadioSession(identifiers: identifiers,","                                               metadata: nil,","                                               playTrackIndex:0,","                                               seconds:0,","                                               autoplay: true,","                                               contextType: nil, contextId: 0) { error, controller in","            self.present(controller, animated: true)","        }","    }","    \/\/ ...","}"]},{"inlineContent":[{"text":"The UIViewController provided by this function is a fullcreen view that contains the Radio UI and will allow the user tyo curate the playlist, go live with it, end its live session and more. This UI can be minimised and also it can be dismissed by terminating the Radio session.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"When you want to programatically force-end a radio session the user has created, use ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/endRadioSession(completion:)","isActive":true,"type":"reference"},{"text":" as shown below:","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["public class MyApplication {","    \/\/ ...","    func didPressEndRadioSessionButton() -> Void {","        SocialRadio.instance.endRadioSession()","    }","    \/\/ ...","}"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Starting-a-broadcast-article","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creating a draft for a radio show and presenting the UI to curate it, then going live."}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"url":"\/documentation\/socialradio\/socialradio\/startradiosession(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRadioSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TunedTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"radioViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"startRadioSessionWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","kind":"identifier"}],"title":"startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","abstract":[{"text":"Starts a Radio session in creation mode, with the tracks and metadata provided.","type":"text"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/endRadioSession(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endRadioSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"type":"topic","url":"\/documentation\/socialradio\/socialradio\/endradiosession(completion:)","title":"endRadioSession(completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/endRadioSession(completion:)","kind":"symbol","abstract":[{"text":"Ends a Radio session. Be mindful if there is an ongoing Live radio show, this will terminate it without asking.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"endRadioSessionWithCompletion:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title","value":"startRadioSessionWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRadioSessionWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1endRadioSession(completion:)\/title","value":"endRadioSessionWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1endRadioSession(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endRadioSessionWithCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}