{"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSManagedObjectID"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSFetchRequestResult","doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSCopying","doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH","doc:\/\/org.cocoapods.SocialRadioLite\/s8SendableP"],"kind":"relationships","title":"Conforms To"}],"metadata":{"modules":[{"name":"SocialRadioLite"}],"role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogID"}],"symbolKind":"class","title":"AutomixIQPlayLogID","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlayLogID"}],"externalID":"c:objc(cs)AutomixIQPlayLogID"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/automixiqplaylogid"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogID","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlayLogID"}]}],"kind":"declarations"}],"kind":"symbol","seeAlsoSections":[{"anchor":"Persistency","title":"Persistency","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLog","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogAttributes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLog","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogID","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"sections":[],"references":{"doc://org.cocoapods.SocialRadioLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.SocialRadioLite/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLogAttributes":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogAttributes","role":"symbol","abstract":[],"title":"AutomixIQPlayLogAttributes","type":"topic","url":"\/documentation\/socialradiolite\/automixiqplaylogattributes","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLog":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLog","role":"symbol","abstract":[],"title":"AutomixIQTransitionLog","type":"topic","url":"\/documentation\/socialradiolite\/automixiqtransitionlog","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQTransitionLog","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLog"}]},"doc://org.cocoapods.SocialRadioLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Persistency-article":{"title":"Persistency","kind":"article","type":"topic","url":"\/documentation\/socialradiolite\/persistency-article","abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article","role":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype","navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"title":"AutomixIQPlaybackEventType","type":"topic","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes","title":"AutomixIQTransitionLogAttributes","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/objc(pl)NSFetchRequestResult":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSFetchRequestResult","type":"unresolvable","title":"CoreData.NSFetchRequestResult"},"doc://org.cocoapods.SocialRadioLite/SH":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadioLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLog":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlayLog"}],"url":"\/documentation\/socialradiolite\/automixiqplaylog","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLog"}],"title":"AutomixIQPlayLog","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLog","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/objc(pl)NSCopying":{"title":"Foundation.NSCopying","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSCopying","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLogID":{"title":"AutomixIQPlayLogID","kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/automixiqplaylogid","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQPlayLogID","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogID"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogID","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/objc(cs)NSManagedObjectID":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSManagedObjectID","type":"unresolvable","title":"CoreData.NSManagedObjectID"},"doc://org.cocoapods.SocialRadioLite/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogID":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogid","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"title":"AutomixIQTransitionLogID","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogID","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/fragments","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/navigatorTitle","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}