{"variants":[{"paths":["\/documentation\/socialradiolite\/automixiq-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/automixiq-article"]}],"sections":[],"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"SocialRadioLite"}],"title":"AutomixIQ"},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQ-article"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"abstract":[{"type":"text","text":"Availablity of underlying technologies and APIs."}],"seeAlsoSections":[{"title":"AutomixIQ","anchor":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQObjC"],"generated":true}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Essentials","level":2,"text":"Essentials"},{"inlineContent":[{"text":"SocialRadio works on top of AutomixIQ and exposes the functionality of AutomixIQ. Please note that manipulating playback or queue with AutomixIQ when a user is creating or consuming a radio show may impact the radio show itself and is therefore discouraged.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The documentation for AutomixIQ can be found here: "},{"type":"reference","identifier":"https:\/\/tunedglobal.github.io\/automix-ios\/0.7.0\/documentation\/automixiq","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQObjC":{"title":"AutomixIQObjC","navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQObjC","kind":"symbol","url":"\/documentation\/socialradiolite\/automixiqobjc","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQObjC","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"https://tunedglobal.github.io/automix-ios/0.7.0/documentation/automixiq":{"titleInlineContent":[{"text":"AutomixIQ","type":"text"}],"identifier":"https:\/\/tunedglobal.github.io\/automix-ios\/0.7.0\/documentation\/automixiq","type":"link","title":"AutomixIQ","url":"https:\/\/tunedglobal.github.io\/automix-ios\/0.7.0\/documentation\/automixiq"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","value":[{"identifiers":[],"title":"AutomixIQ","generated":true,"anchor":"AutomixIQ"}],"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}