{"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH","doc:\/\/org.cocoapods.SocialRadioLite\/SY"]}],"abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"seeAlsoSections":[{"generated":true,"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLog","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogAttributes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogID","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLog","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogID"],"anchor":"Persistency"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Start of track playback"}]}],"name":"trackPlayStart"},{"content":[{"inlineContent":[{"text":"Track has played for 5 seconds","type":"text"}],"type":"paragraph"}],"name":"trackPlayPlayed5Secs"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Track has played for 30 seconds, this is called every 30 seconds of playback","type":"text"}]}],"name":"trackPlayHeartbeat30Secs"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Track has started transitioning into the next track","type":"text"}]}],"name":"trackPlayStartMixingIntoNext"},{"content":[{"inlineContent":[{"text":"Track has been skipped to the next track (this is also called when seeking through the same track)","type":"text"}],"type":"paragraph"}],"name":"trackPlaySkipped"},{"content":[{"inlineContent":[{"text":"Track has finished playback (if transitioning this is called at the end of the transition for the first track)","type":"text"}],"type":"paragraph"}],"name":"trackPlayFinished"},{"name":"mixPlaybackEnded","content":[{"type":"paragraph","inlineContent":[{"text":"Queue has reached the end and there are no more tracks to play","type":"text"}]}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/automixiqplaybackeventtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/automixiqplaybackeventtype"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext"]},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"metadata":{"externalID":"c:@M@SocialRadioLite@E@AutomixIQPlaybackEventType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"modules":[{"name":"SocialRadioLite"}],"symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","title":"AutomixIQPlaybackEventType"},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/trackPlayFinished":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayFinished"}],"navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/trackplayfinished","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayFinished","title":"AutomixIQPlaybackEventType.trackPlayFinished","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLog":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLog","role":"symbol","abstract":[],"title":"AutomixIQTransitionLog","type":"topic","url":"\/documentation\/socialradiolite\/automixiqtransitionlog","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQTransitionLog","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLog"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogID":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogid","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"title":"AutomixIQTransitionLogID","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogID","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/equatable-implementations","abstract":[],"kind":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLogAttributes":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogAttributes","role":"symbol","abstract":[],"title":"AutomixIQPlayLogAttributes","type":"topic","url":"\/documentation\/socialradiolite\/automixiqplaylogattributes","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes","title":"AutomixIQTransitionLogAttributes","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/trackPlayStartMixingIntoNext":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext"}],"title":"AutomixIQPlaybackEventType.trackPlayStartMixingIntoNext","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayStartMixingIntoNext"}],"abstract":[],"url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/trackplaystartmixingintonext","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/trackPlayPlayed5Secs":{"title":"AutomixIQPlaybackEventType.trackPlayPlayed5Secs","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayPlayed5Secs"}],"abstract":[],"url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/trackplayplayed5secs"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Persistency-article":{"title":"Persistency","kind":"article","type":"topic","url":"\/documentation\/socialradiolite\/persistency-article","abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article","role":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/trackPlayHeartbeat30Secs":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayHeartbeat30Secs","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayHeartbeat30Secs","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/trackplayheartbeat30secs","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayHeartbeat30Secs","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"AutomixIQPlaybackEventType.trackPlayHeartbeat30Secs"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","type":"topic"},"doc://org.cocoapods.SocialRadioLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ"},"doc://org.cocoapods.SocialRadioLite/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SY"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLogID":{"title":"AutomixIQPlayLogID","kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/automixiqplaylogid","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQPlayLogID","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogID"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogID","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/mixPlaybackEnded":{"abstract":[],"role":"symbol","type":"topic","title":"AutomixIQPlaybackEventType.mixPlaybackEnded","url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/mixplaybackended","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/mixPlaybackEnded","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/trackPlaySkipped":{"type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackPlaySkipped","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlaySkipped","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"title":"AutomixIQPlaybackEventType.trackPlaySkipped","kind":"symbol","url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/trackplayskipped","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLog":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlayLog"}],"url":"\/documentation\/socialradiolite\/automixiqplaylog","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLog"}],"title":"AutomixIQPlayLog","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLog","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/trackPlayStart":{"url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/trackplaystart","abstract":[],"navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlayStart","kind":"identifier"}],"title":"AutomixIQPlaybackEventType.trackPlayStart","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayStart","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype","navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"title":"AutomixIQPlaybackEventType","type":"topic","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/RawRepresentable-Implementations":{"type":"topic","abstract":[],"kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/RawRepresentable-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixIQPlaybackEventType","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article"],"anchor":"Persistency","title":"Persistency","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlaybackEventType"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayFinished\/title","op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayFinished"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayFinished\/fragments","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"op":"replace"},{"value":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayStartMixingIntoNext\/title"},{"value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayStartMixingIntoNext\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/title","value":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayHeartbeat30Secs\/title","op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayHeartbeat30Secs"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayHeartbeat30Secs\/fragments","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayHeartbeat30Secs","kind":"identifier"}]},{"op":"replace","value":"AutomixIQPlaybackEventTypeMixPlaybackEnded","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/fragments","value":[{"text":"AutomixIQPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlaySkipped\/title","value":"AutomixIQPlaybackEventTypeTrackPlaySkipped","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlaySkipped\/fragments","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayStart\/title","op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayStart"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1trackPlayStart\/fragments","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}]},{"op":"replace","value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/fragments","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/navigatorTitle"}]}]}