{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixIQTransitionLogAttributes","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/automixiqtransitionlogattributes"]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLog","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogAttributes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogID","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLog","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogID","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType"],"generated":true,"anchor":"Persistency","title":"Persistency"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/duration()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/guid()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/trackIdIn()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/trackIdOut()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/transitionType()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/userId()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/when()"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"metadata":{"symbolKind":"class","externalID":"c:objc(cs)AutomixIQTransitionLogAttributes","modules":[{"name":"SocialRadioLite"}],"navigatorTitle":[{"text":"AutomixIQTransitionLogAttributes","kind":"identifier"}],"title":"AutomixIQTransitionLogAttributes","role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTransitionLogAttributes","kind":"identifier"}]},"references":{"doc://org.cocoapods.SocialRadioLite/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogID":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogid","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"title":"AutomixIQTransitionLogID","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogID","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes/trackIdOut()":{"title":"trackIdOut()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackIdOut","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/trackIdOut()","kind":"symbol","url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes\/trackidout()","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes/when()":{"kind":"symbol","url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes\/when()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"when"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/when()","title":"when()","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes","title":"AutomixIQTransitionLogAttributes","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes/duration()":{"abstract":[],"role":"symbol","title":"duration()","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes\/duration()","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/duration()"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes/transitionType()":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/transitionType()","role":"symbol","url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes\/transitiontype()","kind":"symbol","type":"topic","title":"transitionType()","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"transitionType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://org.cocoapods.SocialRadioLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Persistency-article":{"title":"Persistency","kind":"article","type":"topic","url":"\/documentation\/socialradiolite\/persistency-article","abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article","role":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLog":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLog","role":"symbol","abstract":[],"title":"AutomixIQTransitionLog","type":"topic","url":"\/documentation\/socialradiolite\/automixiqtransitionlog","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQTransitionLog","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLog"}]},"doc://org.cocoapods.SocialRadioLite/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLogID":{"title":"AutomixIQPlayLogID","kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/automixiqplaylogid","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQPlayLogID","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogID"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogID","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes/trackIdIn()":{"title":"trackIdIn()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackIdIn","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/trackIdIn()","url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes\/trackidin()"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype","navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"title":"AutomixIQPlaybackEventType","type":"topic","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLogAttributes":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogAttributes","role":"symbol","abstract":[],"title":"AutomixIQPlayLogAttributes","type":"topic","url":"\/documentation\/socialradiolite\/automixiqplaylogattributes","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}]},"doc://org.cocoapods.SocialRadioLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLog":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlayLog"}],"url":"\/documentation\/socialradiolite\/automixiqplaylog","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLog"}],"title":"AutomixIQPlayLog","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLog","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes/userId()":{"abstract":[],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes\/userid()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/userId()","type":"topic","title":"userId()"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes/guid()":{"abstract":[],"role":"symbol","type":"topic","title":"guid()","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes\/guid()","url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes\/guid()","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"guid","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/title","value":"AutomixIQPlaybackEventType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/navigatorTitle"}]}]}