{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Errors-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/sdkError(code:)"],"title":"Errors","anchor":"Errors"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ErrorCode","kind":"identifier"}],"platforms":["iOS"]}]},{"parameters":[{"name":"notMainThread","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to use the SDK from any thread not main","type":"text"}]}]},{"name":"sdkNotInitialised","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to use the SDK prior to initialising it"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to use playback controls when AutomixIQ is not on"}]}],"name":"sdkNotOn"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to turn on AutomixIQ but it is already on","type":"text"}]}],"name":"sdkAlreadyOn"},{"name":"loadTracksEmptyPlaylist","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to load an empty playlist"}]}]},{"name":"loadTracksOutOfBounds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"}]}],"name":"addTrackPlaylistDoesNotExist"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to insert a track at a position outside the bounds of the loaded playlist"}]}],"name":"addTrackOutOfBounds"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when the metadata for a track you are trying to load is not available and could not be downloaded","type":"text"}]}],"name":"addTrackNoMetadata"},{"name":"addTrackInternalError","content":[{"inlineContent":[{"text":"Thrown when AutomixIQ fails internally (not user error)","type":"text"}],"type":"paragraph"}]},{"name":"removeTrackOutOfBounds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to remove a track at a position outside the bounds of the loaded playlist"}]}]},{"name":"playAlreadyPlaying","content":[{"inlineContent":[{"text":"Thrown when you attempt to play but AutomixIQ is already playing","type":"text"}],"type":"paragraph"}]},{"name":"pauseAlreadyPaused","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to pause but AutomixIQ is already paused"}],"type":"paragraph"}]},{"name":"previousNoTrackAvailable","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to go to the previous track but AutomixIQ is already on the first in the playlist and “Repeat” is off","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to go to the next track but AutomixIQ is already on the last in the playlist and “Repeat” is off"}]}],"name":"nextNoTrackAvailable"},{"name":"backNoTrackAvailable","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to go to the start of a track but the playlist is empty"}],"type":"paragraph"}]},{"name":"seekNoTrackAvailable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to seek to a track but the playlist is empty or the index is out of bounds of the playlist"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to seek within a track but the playlist is empty or the track is not yet loaded","type":"text"}]}],"name":"seekNoCurrentTrack"},{"name":"reorderMissingTrack","content":[{"inlineContent":[{"text":"Thrown when you attempt to move a track that is not on the loaded playlist","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to select a track to be played until the end but that track is not on the loaded playlist"}]}],"name":"playToEndMissingTrack"},{"content":[{"inlineContent":[{"text":"Thrown when you attempt to move a track at a position outside the bounds of the loaded playlist","type":"text"}],"type":"paragraph"}],"name":"moveTrackOutOfBounds"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to stop looping a track but that track is not on the loaded playlist","type":"text"}]}],"name":"startLoopingNoLoopingTrack"},{"name":"stopLoopingNoLoopingTrack","content":[{"inlineContent":[{"text":"Thrown when you attempt to loop a track but that track is not on the loaded playlist","type":"text"}],"type":"paragraph"}]},{"name":"unimplemented","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to use an unimplemented method of the SDK"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when an action you previously issued to AutomixIQ is cancelled due to another user initialed action that overrides it"}]}],"name":"cancelled"},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ on while it is already turning on"}],"type":"paragraph"}],"name":"onAlreadyTurningOn"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ on while it is already turning off"}]}],"name":"onWhileTurningOff"},{"name":"offAlreadyTurningOff","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ off while it is already turning off"}]}]},{"name":"offWhileTurningOn","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ off while it is already turning on"}]}]},{"name":"cannotCreateChannelLayout","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the channel layout"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the input buffer"}],"type":"paragraph"}],"name":"cannotCreateInputBuffer"},{"name":"cannotSetupAVAudioSession","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when AutomixIQ fails to set up the AVAudioSession","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to start the audio engine"}]}],"name":"cannotStartAudioEngine"},{"name":"cannotRestoreAudioSession","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to restore the audio session to the state it found it when you turned it on"}]}]},{"content":[{"inlineContent":[{"text":"Thrown when AutomixIQ is unable to be stopped","type":"text"}],"type":"paragraph"}],"name":"failedToStop"},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to load an explicit track but the setting to filter out explicit tracks is on"}],"type":"paragraph"}],"name":"cannotLoadExplicitLyricsTrack"}],"kind":"parameters"}],"sections":[],"metadata":{"externalID":"c:@M@SocialRadioLite@E@ErrorCode","symbolKind":"enum","modules":[{"name":"SocialRadioLite"}],"roleHeading":"Enumeration","title":"ErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"role":"symbol","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/errorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/errorcode"]}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH","doc:\/\/org.cocoapods.SocialRadioLite\/SY"],"title":"Conforms To","kind":"relationships"}],"kind":"symbol","topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cancelled","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/failedToStop","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/notMainThread","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/unable_to_load_mix","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/unimplemented"],"generated":true},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/RawRepresentable-Implementations"]}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/unimplemented":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeUnimplemented"}],"title":"ErrorCode.unimplemented","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/unimplemented","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/unimplemented","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unimplemented","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/sdkInitialisationUnauthorised":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkInitialisationUnauthorised"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkInitialisationUnauthorised","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkInitialisationUnauthorised","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/sdkinitialisationunauthorised","title":"ErrorCode.sdkInitialisationUnauthorised","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/seekNoCurrentTrack":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSeekNoCurrentTrack"}],"title":"ErrorCode.seekNoCurrentTrack","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/seekNoCurrentTrack","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/seeknocurrenttrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekNoCurrentTrack","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/addTrackOutOfBounds":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeAddTrackOutOfBounds"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackOutOfBounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackOutOfBounds","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/addtrackoutofbounds","title":"ErrorCode.addTrackOutOfBounds","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/cannotStartAudioEngine":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotStartAudioEngine"}],"title":"ErrorCode.cannotStartAudioEngine","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotStartAudioEngine","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/cannotstartaudioengine","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotStartAudioEngine","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/seekNoTrackAvailable":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSeekNoTrackAvailable"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/seekNoTrackAvailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekNoTrackAvailable","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/seeknotrackavailable","title":"ErrorCode.seekNoTrackAvailable","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/pauseAlreadyPaused":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}],"title":"ErrorCode.pauseAlreadyPaused","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/pauseAlreadyPaused","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/pausealreadypaused","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseAlreadyPaused","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/stopLoopingNoLoopingTrack":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeStopLoopingNoLoopingTrack"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/stopLoopingNoLoopingTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLoopingNoLoopingTrack","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/stoploopingnoloopingtrack","title":"ErrorCode.stopLoopingNoLoopingTrack","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/removeTrackOutOfBounds":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeRemoveTrackOutOfBounds"}],"title":"ErrorCode.removeTrackOutOfBounds","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/removeTrackOutOfBounds","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/removetrackoutofbounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeTrackOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/cannotRestoreAudioSession":{"navigatorTitle":[{"text":"ErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotRestoreAudioSession","title":"ErrorCode.cannotRestoreAudioSession","url":"\/documentation\/socialradiolite\/errorcode\/cannotrestoreaudiosession","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotRestoreAudioSession","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/sdkAlreadyOn":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyOn"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkAlreadyOn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkAlreadyOn","kind":"identifier"}],"role":"symbol","abstract":[],"title":"ErrorCode.sdkAlreadyOn","url":"\/documentation\/socialradiolite\/errorcode\/sdkalreadyon","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/addTrackInternalError":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeAddTrackInternalError"}],"title":"ErrorCode.addTrackInternalError","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackInternalError","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/addtrackinternalerror","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackInternalError","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/reorderMissingTrack":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeReorderMissingTrack"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/reorderMissingTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reorderMissingTrack","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/reordermissingtrack","abstract":[],"title":"ErrorCode.reorderMissingTrack","type":"topic"},"doc://org.cocoapods.SocialRadioLite/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/failedToStop":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failedToStop","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeFailedToStop"}],"kind":"symbol","title":"ErrorCode.failedToStop","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/failedToStop","type":"topic","url":"\/documentation\/socialradiolite\/errorcode\/failedtostop"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/cannotSetupAVAudioSession":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotSetupAVAudioSession"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotSetupAVAudioSession","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotSetupAVAudioSession","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/cannotsetupavaudiosession","abstract":[],"title":"ErrorCode.cannotSetupAVAudioSession","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/sdkNotInitialisedVersionNoLongerSupported":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"title":"ErrorCode.sdkNotInitialisedVersionNoLongerSupported","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/sdknotinitialisedversionnolongersupported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/playToEndMissingTrack":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePlayToEndMissingTrack"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/playToEndMissingTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playToEndMissingTrack","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/playtoendmissingtrack","abstract":[],"title":"ErrorCode.playToEndMissingTrack","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/offlineNoTunedUserIdAvailable":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeOfflineNoTunedUserIdAvailable"}],"title":"ErrorCode.offlineNoTunedUserIdAvailable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offlineNoTunedUserIdAvailable","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/offlinenotuneduseridavailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/onWhileTurningOff":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeOnWhileTurningOff"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/onWhileTurningOff","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onWhileTurningOff","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/onwhileturningoff","abstract":[],"title":"ErrorCode.onWhileTurningOff","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/noInternetAvailable":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailable"}],"title":"ErrorCode.noInternetAvailable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/noInternetAvailable","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/nointernetavailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailable","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/loadTracksOutOfBounds":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeLoadTracksOutOfBounds"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/loadTracksOutOfBounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracksOutOfBounds","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/loadtracksoutofbounds","abstract":[],"title":"ErrorCode.loadTracksOutOfBounds","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/nextNoTrackAvailable":{"url":"\/documentation\/socialradiolite\/errorcode\/nextnotrackavailable","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextNoTrackAvailable"}],"navigatorTitle":[{"text":"ErrorCodeNextNoTrackAvailable","kind":"identifier"}],"title":"ErrorCode.nextNoTrackAvailable","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/nextNoTrackAvailable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/notMainThread":{"title":"ErrorCode.notMainThread","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/notMainThread","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notMainThread","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/notmainthread","navigatorTitle":[{"text":"ErrorCodeNotMainThread","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/cannotCreateChannelLayout":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotCreateChannelLayout"}],"title":"ErrorCode.cannotCreateChannelLayout","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotCreateChannelLayout","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/cannotcreatechannellayout","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotCreateChannelLayout","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/RawRepresentable-Implementations":{"type":"topic","kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/socialradiolite\/errorcode\/rawrepresentable-implementations","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.SocialRadioLite/SH":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/cancelled":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCancelled"}],"title":"ErrorCode.cancelled","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cancelled","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/cancelled","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/previousNoTrackAvailable":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePreviousNoTrackAvailable"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/previousNoTrackAvailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousNoTrackAvailable","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/previousnotrackavailable","abstract":[],"title":"ErrorCode.previousNoTrackAvailable","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/noInternetAvailableTooLongOffline":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailableTooLongOffline"}],"title":"ErrorCode.noInternetAvailableTooLongOffline","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/noInternetAvailableTooLongOffline","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/nointernetavailabletoolongoffline","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/addTrackNoMetadata":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeAddTrackNoMetadata"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackNoMetadata","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackNoMetadata","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/addtracknometadata","abstract":[],"title":"ErrorCode.addTrackNoMetadata","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/moveTrackOutOfBounds":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeMoveTrackOutOfBounds"}],"title":"ErrorCode.moveTrackOutOfBounds","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/moveTrackOutOfBounds","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/movetrackoutofbounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveTrackOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/playToEndMixEnd":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePlayToEndMixEnd"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/playToEndMixEnd","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playToEndMixEnd","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/playtoendmixend","abstract":[],"title":"ErrorCode.playToEndMixEnd","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/playAlreadyPlaying":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePlayAlreadyPlaying"}],"title":"ErrorCode.playAlreadyPlaying","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/playAlreadyPlaying","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/playalreadyplaying","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playAlreadyPlaying","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/sdkNotOn":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkNotOn"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotOn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotOn","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/sdknoton","abstract":[],"title":"ErrorCode.sdkNotOn","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/loadTracksEmptyPlaylist":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeLoadTracksEmptyPlaylist"}],"title":"ErrorCode.loadTracksEmptyPlaylist","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/loadTracksEmptyPlaylist","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/loadtracksemptyplaylist","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracksEmptyPlaylist","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/offWhileTurningOn":{"title":"ErrorCode.offWhileTurningOn","role":"symbol","navigatorTitle":[{"text":"ErrorCodeOffWhileTurningOn","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradiolite\/errorcode\/offwhileturningon","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offWhileTurningOn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offWhileTurningOn"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/cannotLoadExplicitLyricsTrack":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotLoadExplicitLyricsTrack"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotLoadExplicitLyricsTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/cannotloadexplicitlyricstrack","abstract":[],"title":"ErrorCode.cannotLoadExplicitLyricsTrack","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/addTrackPlaylistDoesNotExist":{"title":"ErrorCode.addTrackPlaylistDoesNotExist","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackPlaylistDoesNotExist","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeAddTrackPlaylistDoesNotExist"}],"url":"\/documentation\/socialradiolite\/errorcode\/addtrackplaylistdoesnotexist","abstract":[]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Errors-article":{"title":"Errors","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Errors-article","kind":"article","abstract":[{"text":"What errors the SocialRadio player can issue to help with player integration","type":"text"}],"type":"topic","role":"article","url":"\/documentation\/socialradiolite\/errors-article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/offAlreadyTurningOff":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeOffAlreadyTurningOff"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offAlreadyTurningOff","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offAlreadyTurningOff","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/offalreadyturningoff","title":"ErrorCode.offAlreadyTurningOff","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/cannotCreateInputBuffer":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotCreateInputBuffer"}],"title":"ErrorCode.cannotCreateInputBuffer","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotCreateInputBuffer","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/cannotcreateinputbuffer","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotCreateInputBuffer","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/unable_to_load_mix":{"navigatorTitle":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}],"type":"topic","title":"ErrorCode.unable_to_load_mix","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unable_to_load_mix","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/unable_to_load_mix","kind":"symbol","abstract":[],"url":"\/documentation\/socialradiolite\/errorcode\/unable_to_load_mix"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/backNoTrackAvailable":{"role":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/errorcode\/backnotrackavailable","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"backNoTrackAvailable","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeBackNoTrackAvailable"}],"title":"ErrorCode.backNoTrackAvailable","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/backNoTrackAvailable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/startLoopingNoLoopingTrack":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/startLoopingNoLoopingTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLoopingNoLoopingTrack","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/startloopingnoloopingtrack","title":"ErrorCode.startLoopingNoLoopingTrack","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/init(rawValue:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/sdkNotInitialised":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotInitialised","abstract":[],"url":"\/documentation\/socialradiolite\/errorcode\/sdknotinitialised","kind":"symbol","title":"ErrorCode.sdkNotInitialised","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialised"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkNotInitialised"}]},"doc://org.cocoapods.SocialRadioLite/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/Equatable-Implementations","kind":"article","abstract":[],"type":"topic","role":"collectionGroup","url":"\/documentation\/socialradiolite\/errorcode\/equatable-implementations"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/sdkAlreadyInitialised":{"navigatorTitle":[{"text":"ErrorCodeSdkAlreadyInitialised","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkAlreadyInitialised","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkAlreadyInitialised"}],"role":"symbol","abstract":[],"title":"ErrorCode.sdkAlreadyInitialised","url":"\/documentation\/socialradiolite\/errorcode\/sdkalreadyinitialised","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/sdkError(code:)":{"title":"sdkError(code:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/sdkError(code:)","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/sdkerror(code:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkError"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadioLite@E@ErrorCode","kind":"typeIdentifier","text":"ErrorCode"},{"kind":"text","text":") -> "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/onAlreadyTurningOn":{"navigatorTitle":[{"text":"ErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/onAlreadyTurningOn","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAlreadyTurningOn"}],"role":"symbol","abstract":[],"title":"ErrorCode.onAlreadyTurningOn","url":"\/documentation\/socialradiolite\/errorcode\/onalreadyturningon","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCode"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cancelled","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/failedToStop","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/notMainThread","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/unable_to_load_mix","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/unimplemented"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Errors","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Errors-article"],"title":"Errors"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"ErrorCodeUnimplemented","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1unimplemented\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeUnimplemented"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1unimplemented\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkInitialisationUnauthorised\/title","value":"ErrorCodeSdkInitialisationUnauthorised","op":"replace"},{"value":[{"text":"ErrorCodeSdkInitialisationUnauthorised","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkInitialisationUnauthorised\/fragments"},{"value":"ErrorCodeSeekNoCurrentTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1seekNoCurrentTrack\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1seekNoCurrentTrack\/fragments","value":[{"kind":"identifier","text":"ErrorCodeSeekNoCurrentTrack"}],"op":"replace"},{"op":"replace","value":"ErrorCodeAddTrackOutOfBounds","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1addTrackOutOfBounds\/title"},{"value":[{"text":"ErrorCodeAddTrackOutOfBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1addTrackOutOfBounds\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotStartAudioEngine\/title","value":"ErrorCodeCannotStartAudioEngine"},{"value":[{"text":"ErrorCodeCannotStartAudioEngine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotStartAudioEngine\/fragments"},{"value":"ErrorCodeSeekNoTrackAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1seekNoTrackAvailable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1seekNoTrackAvailable\/fragments","value":[{"text":"ErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1pauseAlreadyPaused\/title","value":"ErrorCodePauseAlreadyPaused"},{"value":[{"text":"ErrorCodePauseAlreadyPaused","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1pauseAlreadyPaused\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1stopLoopingNoLoopingTrack\/title","value":"ErrorCodeStopLoopingNoLoopingTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1stopLoopingNoLoopingTrack\/fragments","value":[{"kind":"identifier","text":"ErrorCodeStopLoopingNoLoopingTrack"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1removeTrackOutOfBounds\/title","value":"ErrorCodeRemoveTrackOutOfBounds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1removeTrackOutOfBounds\/fragments","value":[{"text":"ErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}]},{"op":"replace","value":"ErrorCodeCannotRestoreAudioSession","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotRestoreAudioSession\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotRestoreAudioSession\/fragments","value":[{"text":"ErrorCodeCannotRestoreAudioSession","kind":"identifier"}]},{"value":"ErrorCodeSdkAlreadyOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkAlreadyOn\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkAlreadyOn\/fragments","op":"replace","value":[{"text":"ErrorCodeSdkAlreadyOn","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1addTrackInternalError\/title","value":"ErrorCodeAddTrackInternalError"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeAddTrackInternalError"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1addTrackInternalError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1reorderMissingTrack\/title","value":"ErrorCodeReorderMissingTrack"},{"value":[{"text":"ErrorCodeReorderMissingTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1reorderMissingTrack\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1failedToStop\/title","value":"ErrorCodeFailedToStop","op":"replace"},{"value":[{"text":"ErrorCodeFailedToStop","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1failedToStop\/fragments"},{"value":"ErrorCodeCannotSetupAVAudioSession","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotSetupAVAudioSession\/title","op":"replace"},{"value":[{"text":"ErrorCodeCannotSetupAVAudioSession","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotSetupAVAudioSession\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/title","value":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/fragments","value":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported"}]},{"value":"ErrorCodePlayToEndMissingTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1playToEndMissingTrack\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1playToEndMissingTrack\/fragments","value":[{"kind":"identifier","text":"ErrorCodePlayToEndMissingTrack"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1offlineNoTunedUserIdAvailable\/title","value":"ErrorCodeOfflineNoTunedUserIdAvailable"},{"value":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1offlineNoTunedUserIdAvailable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1onWhileTurningOff\/title","value":"ErrorCodeOnWhileTurningOff"},{"value":[{"text":"ErrorCodeOnWhileTurningOff","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1onWhileTurningOff\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1noInternetAvailable\/title","value":"ErrorCodeNoInternetAvailable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1noInternetAvailable\/fragments","value":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailable"}]},{"value":"ErrorCodeLoadTracksOutOfBounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1loadTracksOutOfBounds\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1loadTracksOutOfBounds\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeLoadTracksOutOfBounds"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1nextNoTrackAvailable\/title","value":"ErrorCodeNextNoTrackAvailable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1nextNoTrackAvailable\/fragments","value":[{"text":"ErrorCodeNextNoTrackAvailable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1notMainThread\/title","value":"ErrorCodeNotMainThread"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1notMainThread\/fragments","value":[{"kind":"identifier","text":"ErrorCodeNotMainThread"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotCreateChannelLayout\/title","value":"ErrorCodeCannotCreateChannelLayout","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeCannotCreateChannelLayout"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotCreateChannelLayout\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cancelled\/title","value":"ErrorCodeCancelled"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cancelled\/fragments","value":[{"kind":"identifier","text":"ErrorCodeCancelled"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1previousNoTrackAvailable\/title","value":"ErrorCodePreviousNoTrackAvailable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1previousNoTrackAvailable\/fragments","value":[{"kind":"identifier","text":"ErrorCodePreviousNoTrackAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1noInternetAvailableTooLongOffline\/title","value":"ErrorCodeNoInternetAvailableTooLongOffline"},{"op":"replace","value":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1noInternetAvailableTooLongOffline\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1addTrackNoMetadata\/title","op":"replace","value":"ErrorCodeAddTrackNoMetadata"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1addTrackNoMetadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodeAddTrackNoMetadata"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1moveTrackOutOfBounds\/title","value":"ErrorCodeMoveTrackOutOfBounds"},{"value":[{"kind":"identifier","text":"ErrorCodeMoveTrackOutOfBounds"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1moveTrackOutOfBounds\/fragments"},{"value":"ErrorCodePlayToEndMixEnd","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1playToEndMixEnd\/title","op":"replace"},{"value":[{"text":"ErrorCodePlayToEndMixEnd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1playToEndMixEnd\/fragments"},{"value":"ErrorCodePlayAlreadyPlaying","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1playAlreadyPlaying\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodePlayAlreadyPlaying"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1playAlreadyPlaying\/fragments","op":"replace"},{"op":"replace","value":"ErrorCodeSdkNotOn","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkNotOn\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkNotOn\/fragments","value":[{"text":"ErrorCodeSdkNotOn","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1loadTracksEmptyPlaylist\/title","value":"ErrorCodeLoadTracksEmptyPlaylist"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1loadTracksEmptyPlaylist\/fragments","value":[{"kind":"identifier","text":"ErrorCodeLoadTracksEmptyPlaylist"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1offWhileTurningOn\/title","op":"replace","value":"ErrorCodeOffWhileTurningOn"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1offWhileTurningOn\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeOffWhileTurningOn"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle"},{"value":"ErrorCodeCannotLoadExplicitLyricsTrack","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotLoadExplicitLyricsTrack\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotLoadExplicitLyricsTrack\/fragments","value":[{"kind":"identifier","text":"ErrorCodeCannotLoadExplicitLyricsTrack"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1addTrackPlaylistDoesNotExist\/title","value":"ErrorCodeAddTrackPlaylistDoesNotExist"},{"op":"replace","value":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1addTrackPlaylistDoesNotExist\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1offAlreadyTurningOff\/title","value":"ErrorCodeOffAlreadyTurningOff","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1offAlreadyTurningOff\/fragments","value":[{"text":"ErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotCreateInputBuffer\/title","value":"ErrorCodeCannotCreateInputBuffer"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotCreateInputBuffer\/fragments","value":[{"text":"ErrorCodeCannotCreateInputBuffer","kind":"identifier"}],"op":"replace"},{"value":"ErrorCodeUnable_to_load_mix","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1unable_to_load_mix\/title","op":"replace"},{"value":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1unable_to_load_mix\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1backNoTrackAvailable\/title","value":"ErrorCodeBackNoTrackAvailable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1backNoTrackAvailable\/fragments","value":[{"kind":"identifier","text":"ErrorCodeBackNoTrackAvailable"}]},{"value":"ErrorCodeStartLoopingNoLoopingTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1startLoopingNoLoopingTrack\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1startLoopingNoLoopingTrack\/fragments","value":[{"text":"ErrorCodeStartLoopingNoLoopingTrack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkNotInitialised\/title","op":"replace","value":"ErrorCodeSdkNotInitialised"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkNotInitialised\/fragments","value":[{"text":"ErrorCodeSdkNotInitialised","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkAlreadyInitialised\/title","op":"replace","value":"ErrorCodeSdkAlreadyInitialised"},{"value":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkAlreadyInitialised\/fragments"},{"value":"ErrorCodeOnAlreadyTurningOn","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1onAlreadyTurningOn\/title","op":"replace"},{"value":[{"text":"ErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1onAlreadyTurningOn\/fragments","op":"replace"}]}]}