{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"kind":"article","metadata":{"modules":[{"name":"SocialRadioLite"}],"roleHeading":"Article","role":"article","title":"Getting available broadcasts"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Getting-available-broadcasts-article"},"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Essentials","type":"heading","text":"Essentials"},{"inlineContent":[{"type":"text","text":"When you want to fetch a list of currently available live broadcasts as paged request, you use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/getLiveBroadcasts(limit:start:completion:)"},{"text":" as shown below:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["public class MyApplication {","    \/\/ ...","    func getBroadcasts() -> Void {","        let limit: Int = 10             \/\/ Get a total of 10 broadcasts","        let start: Int = 0              \/\/ Get the first broadcasts","        SocialRadio.instance.getLiveBroadcasts(limit: limit, start: start) { error, liveBroadcasts in","            \/\/ Present the broadcasts on your UI","            let myLiveBroadcasts = myLiveBroadcasts","            myLiveBroadcasts.add(liveBroadcasts)","            if(liveBroadcasts.size < limit) {","                \/\/ There are more broadcasts available!","                getNextLiveBroadcastsPage()","            }","        }","    }","    \/\/ ...","}"]}]}],"abstract":[{"type":"text","text":"How to learn which broadcasts are currently live."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/getting-available-broadcasts-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/getting-available-broadcasts-article"]}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio/getLiveBroadcasts(limit:start:completion:)":{"title":"getLiveBroadcasts(limit:start:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/socialradio\/getlivebroadcasts(limit:start:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/getLiveBroadcasts(limit:start:completion:)","abstract":[{"text":"Queries the live shows, paged.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveBroadcasts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"start","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"liveMixtapes","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioList","text":"SocialRadioList","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"getLiveBroadcastsWithLimit:start:completion:","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1getLiveBroadcasts(limit:start:completion:)\/title","value":"getLiveBroadcastsWithLimit:start:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLiveBroadcastsWithLimit:start:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1getLiveBroadcasts(limit:start:completion:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}