{"primaryContentSections":[{"content":[{"type":"heading","text":"Join","anchor":"Join","level":2},{"inlineContent":[{"type":"text","text":"When you want to join an existing radio broadcast to listen to and interact with it, you use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/joinLiveBroadcast(identifier:completion:)"},{"text":" as shown below:","type":"text"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["public class MyApplication {","    \/\/ ...","    func didPressJoinLiveBroadcastButton(indentifier: String) -> Void {","    SocialRadio.instance.joinLiveBroadcast(identifier: identifier) { error, controller in","            self.present(controller, animated: true)","        }","    }","    \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The UIViewController provided by this function is a fullcreen view that contains the Radio UI and will allow the user tyo curate the playlist, go live with it, end its live session and more. This UI can be minimised and also it can be dismissed by terminating the Radio session."}]},{"inlineContent":[{"type":"text","text":"When you want to programatically force-end a radio session the user has created, use "},{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/endRadioSession(completion:)","type":"reference","isActive":true},{"text":" as shown below:","type":"text"}],"type":"paragraph"},{"code":["public class MyApplication {","    \/\/ ...","    func didPressEndRadioSessionButton() -> Void {","        SocialRadio.instance.endRadioSession()","    }","    \/\/ ...","}"],"syntax":"swift","type":"codeListing"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Joining-a-broadcast-article"},"kind":"article","metadata":{"role":"article","roleHeading":"Article","title":"Joining a broadcast","modules":[{"name":"SocialRadioLite"}]},"abstract":[{"type":"text","text":"How to start playing a broadcast by a user that is currently live"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/joining-a-broadcast-article"]},{"paths":["\/documentation\/socialradiolite\/joining-a-broadcast-article"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio/endRadioSession(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endRadioSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/socialradiolite\/socialradio\/endradiosession(completion:)","role":"symbol","abstract":[{"text":"Ends a Radio session. Be mindful if there is an ongoing Live radio show, this will terminate it without asking.","type":"text"}],"navigatorTitle":[{"text":"endRadioSessionWithCompletion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/endRadioSession(completion:)","title":"endRadioSession(completion:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio/joinLiveBroadcast(identifier:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"joinLiveBroadcast","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"radioViewController","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/joinLiveBroadcast(identifier:completion:)","title":"joinLiveBroadcast(identifier:completion:)","navigatorTitle":[{"kind":"identifier","text":"joinLiveBroadcastWithIdentifier:completion:"}],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/socialradio\/joinlivebroadcast(identifier:completion:)","abstract":[{"text":"Starts playing a live mixtape as a consumer","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1endRadioSession(completion:)\/title","value":"endRadioSessionWithCompletion:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"endRadioSessionWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1endRadioSession(completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1joinLiveBroadcast(identifier:completion:)\/title","op":"replace","value":"joinLiveBroadcastWithIdentifier:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"joinLiveBroadcastWithIdentifier:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1joinLiveBroadcast(identifier:completion:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}