{"kind":"article","sections":[],"abstract":[{"type":"text","text":"Tools to interact with the social layer."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"metadata":{"title":"Moderation","roleHeading":"Article","modules":[{"name":"SocialRadioLite"}],"role":"article"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Moderation-article"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/moderation-article"]},{"paths":["\/documentation\/socialradiolite\/moderation-article"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Essentials","anchor":"Essentials"},{"type":"paragraph","inlineContent":[{"text":"SocialRadio offers moderation of content by allowing the user to report inapropriate mixtapes or users. To do so, you use ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/reportUser(identifier:completion:)"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/reportMixtape(identifier:completion:)","type":"reference","isActive":true},{"text":".","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["public class MyApplication {","    \/\/ ...","    func didPressReportUserButton(identifier: String) {","        SocialRadio.getInstance()?.reportUser(identifier) { error in ","        }","    }","    ","    fun didPressReportMixtapeButton(identifier: String) {","        SocialRadio.getInstance()?.reportMixtape(identifier) { error in ","        }","    }","    \/\/ ...","}"]},{"inlineContent":[{"text":"SocialRadio also offers the possibility of sending users a notification. To do so, you use ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"code":["public class MyApplication {","    \/\/ ...","    func notifyFollowers(identifier: String, title: String, body: String, objectType: String?, objectId: String?) {","        SocialRadio.getInstance()?.notifyFollowers(userIdentifier: identifier, ","                                                   title: title, ","                                                   body: body, ","                                                   objectType: objectType, ","                                                   objectId: objectId) {","        }","    }","    \/\/ ...","}"],"syntax":"swift","type":"codeListing"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio/reportUser(identifier:completion:)":{"role":"symbol","abstract":[{"text":"Submits a report for inappropriate content for a user.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"reportUser","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"reportUserWithIdentifier:completion:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/reportUser(identifier:completion:)","url":"\/documentation\/socialradiolite\/socialradio\/reportuser(identifier:completion:)","title":"reportUser(identifier:completion:)"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)":{"title":"notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"notifyFollowers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"objectType"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"objectId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Submits a request to notify all followers of a user of something."}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradio\/notifyfollowers(useridentifier:title:body:objecttype:objectid:completion:)","navigatorTitle":[{"kind":"identifier","text":"notifyFollowersWithUserIdentifier:title:body:objectType:objectId:completion:"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio/reportMixtape(identifier:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reportMixtape","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Submits a report for inappropriate content for a mixtape."}],"type":"topic","role":"symbol","title":"reportMixtape(identifier:completion:)","url":"\/documentation\/socialradiolite\/socialradio\/reportmixtape(identifier:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/reportMixtape(identifier:completion:)","navigatorTitle":[{"kind":"identifier","text":"reportMixtapeWithIdentifier:completion:"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1reportUser(identifier:completion:)\/title","value":"reportUserWithIdentifier:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reportUserWithIdentifier:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1reportUser(identifier:completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)\/title","value":"notifyFollowersWithUserIdentifier:title:body:objectType:objectId:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"notifyFollowersWithUserIdentifier:title:body:objectType:objectId:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)\/fragments"},{"value":"reportMixtapeWithIdentifier:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1reportMixtape(identifier:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1reportMixtape(identifier:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reportMixtapeWithIdentifier:completion:"}]}]}]}