{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioLogLevel"}],"languages":["swift"]}]},{"parameters":[{"name":"logLevelTrace","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ logs with no filter"}]}]},{"name":"logLevelDebug","content":[{"inlineContent":[{"type":"text","text":"AutomixIQ logs everything except low level details"}],"type":"paragraph"}]},{"name":"logLevelInfo","content":[{"inlineContent":[{"type":"text","text":"AutomixIQ logs everything except low level details and debug statements"}],"type":"paragraph"}]},{"name":"logLevelWarning","content":[{"type":"paragraph","inlineContent":[{"text":"AutomixIQ only logs errors and warnings","type":"text"}]}]},{"name":"logLevelError","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ only logs errors"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"AutomixIQ only logs fatal errors","type":"text"}]}],"name":"logLevelFatal"}],"kind":"parameters"}],"metadata":{"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SocialRadioLite@E@SocialRadioLogLevel","title":"SocialRadioLogLevel","navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"modules":[{"name":"SocialRadioLite"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SocialRadioLogLevel","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiologlevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiologlevel"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"abstract":[{"text":"SocialRadioLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel"},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelDebug","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelError","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelFatal","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelInfo","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelTrace","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelWarning"],"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/init(rawValue:)"],"title":"Initializers","generated":true},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH","doc:\/\/org.cocoapods.SocialRadioLite\/SY"],"kind":"relationships","title":"Conforms To"}],"seeAlsoSections":[{"title":"Initializing SocialRadio for use with Tuned Global’s APIs","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStreamingDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode"],"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs"}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","abstract":[],"role":"symbol","title":"SocialRadioUIConfig","navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/logLevelDebug":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"logLevelDebug","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelDebug"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelDebug","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiologlevel\/logleveldebug","title":"SocialRadioLogLevel.logLevelDebug","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Initialising-SocialRadio-article":{"role":"article","kind":"article","url":"\/documentation\/socialradiolite\/initialising-socialradio-article","title":"Initializing SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Initialising-SocialRadio-article","type":"topic","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStreamingDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"abstract":[{"text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations.","type":"text"}],"navigatorTitle":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStreamingDelegate","url":"\/documentation\/socialradiolite\/socialradiostreamingdelegate","title":"SocialRadioStreamingDelegate"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/logLevelError":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelError","title":"SocialRadioLogLevel.logLevelError","navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelError"}],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/socialradiologlevel\/loglevelerror","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioFeatureSetConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","url":"\/documentation\/socialradiolite\/socialradiofeaturesetconfig","title":"SocialRadioFeatureSetConfig"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiologlevel\/rawrepresentable-implementations","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusObserverDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusObserverDelegate","url":"\/documentation\/socialradiolite\/socialradiostatusobserverdelegate","title":"SocialRadioStatusObserverDelegate"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/logLevelInfo":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"logLevelInfo","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioLogLevelLogLevelInfo","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelInfo","title":"SocialRadioLogLevel.logLevelInfo","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiologlevel\/loglevelinfo","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/logLevelFatal":{"title":"SocialRadioLogLevel.logLevelFatal","type":"topic","url":"\/documentation\/socialradiolite\/socialradiologlevel\/loglevelfatal","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelFatal","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelFatal"}],"navigatorTitle":[{"text":"SocialRadioLogLevelLogLevelFatal","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/logLevelTrace":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"logLevelTrace","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelTrace"}],"kind":"symbol","title":"SocialRadioLogLevel.logLevelTrace","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelTrace","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiologlevel\/logleveltrace","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel","role":"symbol","abstract":[{"type":"text","text":"SocialRadioLogLevel is an enum of all the AutomixIQ available log levels"}],"title":"SocialRadioLogLevel","type":"topic","url":"\/documentation\/socialradiolite\/socialradiologlevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioLogLevel"}],"navigatorTitle":[{"text":"SocialRadioLogLevel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/logLevelWarning":{"type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"logLevelWarning","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioLogLevelLogLevelWarning","kind":"identifier"}],"title":"SocialRadioLogLevel.logLevelWarning","role":"symbol","url":"\/documentation\/socialradiolite\/socialradiologlevel\/loglevelwarning","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelWarning"},"doc://org.cocoapods.SocialRadioLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedRestDelegate":{"title":"SocialRadioTunedRestDelegate","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiotunedrestdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable":{"abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"title":"SocialRadioStatusVariable","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiostatusvariable"},"doc://org.cocoapods.SocialRadioLite/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SY"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioPlaybackMode":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioplaybackmode","title":"SocialRadioPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode","type":"topic","abstract":[{"text":"SocialRadio playback mode","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioPlaybackMode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioConfig":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioConfig","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioconfig","title":"SocialRadioConfig","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioConfig"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIDelegate":{"title":"SocialRadioUIDelegate","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiouidelegate","abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIDelegate","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/Equatable-Implementations","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiologlevel\/equatable-implementations"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/socialradiologlevel\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SocialRadioLogLevel"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SocialRadioLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioLogLevel"}]},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelDebug","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelError","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelFatal","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelInfo","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelTrace","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelWarning"],"title":"Enumeration Cases"}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Initializing SocialRadio for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStreamingDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode"],"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs"}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioLogLevel","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/title","op":"replace","value":"SocialRadioUIConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/fragments","op":"replace","value":[{"text":"SocialRadioUIConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelDebug\/title","value":"SocialRadioLogLevelLogLevelDebug","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelDebug\/fragments","value":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelDebug"}],"op":"replace"},{"value":"SocialRadioStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStreamingDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}]},{"value":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStreamingDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelError\/title","value":"SocialRadioLogLevelLogLevelError","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelError\/fragments","value":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelError"}],"op":"replace"},{"value":"SocialRadioFeatureSetConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/fragments","op":"replace","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/navigatorTitle","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}]},{"value":"SocialRadioStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusObserverDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"value":"SocialRadioLogLevelLogLevelInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelInfo\/title"},{"value":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelInfo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelInfo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelFatal\/title","op":"replace","value":"SocialRadioLogLevelLogLevelFatal"},{"value":[{"text":"SocialRadioLogLevelLogLevelFatal","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelFatal\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelTrace\/title","value":"SocialRadioLogLevelLogLevelTrace","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelTrace\/fragments","value":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelTrace"}],"op":"replace"},{"value":"SocialRadioLogLevel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/fragments","value":[{"text":"SocialRadioLogLevel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/navigatorTitle"},{"value":"SocialRadioLogLevelLogLevelWarning","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelWarning\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelWarning\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelWarning"}]},{"value":"SocialRadioTunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/title"},{"value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/title","op":"replace","value":"SocialRadioStatusVariable"},{"value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/navigatorTitle","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/title","op":"replace","value":"SocialRadioPlaybackMode"},{"value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/navigatorTitle","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}]},{"op":"replace","value":"SocialRadioConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/fragments","op":"replace","value":[{"text":"SocialRadioConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIDelegate\/title","value":"SocialRadioUIDelegate","op":"replace"},{"op":"replace","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}