{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiomixtapetrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiomixtapetrack"]}],"abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/Se","doc:\/\/org.cocoapods.SocialRadioLite\/SE","doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH"],"kind":"relationships"}],"seeAlsoSections":[{"title":"Data models","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioGenericList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"],"generated":true,"anchor":"Data-models"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioMixtapeTrack","title":"SocialRadioMixtapeTrack","modules":[{"name":"SocialRadioLite"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"navigatorTitle":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}]},"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/init(from:)"]},{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/artist","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/availableMarkets","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/bpm","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/color","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/duration","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/explicit","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/images","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/key","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/previewURL","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/service","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/title","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackBpm","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackDuration","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackExplicit","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackRef"],"generated":true,"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}]}]}],"references":{"doc://org.cocoapods.SocialRadioLite/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SE"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTrackModel":{"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTrackModel"}],"navigatorTitle":[{"text":"SocialRadioTrackModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiotrackmodel","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","title":"SocialRadioTrackModel","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/service":{"navigatorTitle":[{"text":"service","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/service","title":"service","kind":"symbol","abstract":[{"text":"The identifier for the type of track","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"service","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/service"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/trackRef":{"role":"symbol","navigatorTitle":[{"text":"trackRef","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/trackref","abstract":[{"text":"The identifier for the track","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"trackRef","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackRef","title":"trackRef","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioGenericList":{"navigatorTitle":[{"text":"SocialRadioGenericList","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioGenericList","title":"SocialRadioGenericList","kind":"symbol","abstract":[{"text":"SocialRadioGenericList models a list of things","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioGenericList","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiogenericlist"},"doc://org.cocoapods.SocialRadioLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH"},"doc://org.cocoapods.SocialRadioLite/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/Se"},"doc://org.cocoapods.SocialRadioLite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioList":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","role":"symbol","abstract":[],"title":"SocialRadioList","url":"\/documentation\/socialradiolite\/socialradiolist","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioList"}],"navigatorTitle":[{"text":"SocialRadioList","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUser":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","abstract":[{"type":"text","text":"SocialRadioUser models a user"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioUser","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiouser","title":"SocialRadioUser","navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/trackExplicit":{"navigatorTitle":[{"text":"trackExplicit","kind":"identifier"}],"type":"topic","title":"trackExplicit","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackExplicit","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackExplicit","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/trackexplicit","abstract":[{"text":"True if this track has explicit content, false otherwise","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/trackBpm":{"role":"symbol","navigatorTitle":[{"text":"trackBpm","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/trackbpm","abstract":[{"text":"The bpm of the track","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"trackBpm","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackBpm","title":"trackBpm","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtape":{"type":"topic","kind":"symbol","title":"SocialRadioMixtape","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtape","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"role":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","url":"\/documentation\/socialradiolite\/socialradiomixtape"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatus":{"navigatorTitle":[{"text":"SocialRadioStatus","kind":"identifier"}],"type":"topic","title":"SocialRadioStatus","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiostatus","abstract":[{"text":"SocialRadioStatus models the State of the AutomixIQ during playback.","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack":{"type":"topic","title":"SocialRadioMixtapeTrack","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/color":{"role":"symbol","navigatorTitle":[{"text":"color","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/color","abstract":[{"text":"The significant color of the artwork of this track as a string representation","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/color","title":"color","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/previewURL":{"role":"symbol","navigatorTitle":[{"text":"previewURL","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/previewurl","abstract":[{"text":"The URL of a sample sound for this track a s a string","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"previewURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/previewURL","title":"previewURL","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/trackDuration":{"role":"symbol","navigatorTitle":[{"text":"trackDuration","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/trackduration","abstract":[{"text":"The track duration","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDuration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackDuration","title":"trackDuration","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/key":{"navigatorTitle":[{"text":"key","kind":"identifier"}],"type":"topic","title":"key","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"key","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/key","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/key","abstract":[{"type":"text","text":"The key of the track"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioArtistModel":{"role":"symbol","navigatorTitle":[{"text":"SocialRadioArtistModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioartistmodel","abstract":[{"type":"text","text":"SocialRadioArtistModel models an artist."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioArtistModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","title":"SocialRadioArtistModel","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/title":{"navigatorTitle":[{"text":"title","kind":"identifier"}],"type":"topic","title":"title","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/title","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/title","abstract":[{"text":"The title","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters","abstract":[{"text":"SocialRadioMixtapeCounters models the set of counters for information about a mixtape","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","title":"SocialRadioMixtapeCounters","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/artist":{"role":"symbol","navigatorTitle":[{"text":"artist","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/artist","abstract":[{"text":"The artist name","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"artist","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/artist","title":"artist","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/bpm":{"role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/bpm","abstract":[{"text":"The bpm of the track","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bpm","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/bpm","title":"bpm","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/init(from:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[],"type":"topic","role":"symbol","title":"init(from:)","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/init(from:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/init(from:)","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeLite":{"navigatorTitle":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"type":"topic","title":"SocialRadioMixtapeLite","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapelite","abstract":[{"type":"text","text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioPluginMetadataModel":{"role":"symbol","navigatorTitle":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiopluginmetadatamodel","abstract":[{"type":"text","text":"SocialRadioPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"text":" ","type":"text"},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioPluginMetadataModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","title":"SocialRadioPluginMetadataModel","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedAuthenticationResponse":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"abstract":[{"text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"title":"SocialRadioTunedAuthenticationResponse","url":"\/documentation\/socialradiolite\/socialradiotunedauthenticationresponse","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/duration":{"type":"topic","title":"duration","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/duration","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/duration","abstract":[{"type":"text","text":"The track duration"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Data-models-article":{"role":"article","url":"\/documentation\/socialradiolite\/data-models-article","abstract":[{"type":"text","text":"How data is passed to and from SocialRadio"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","title":"Data models","kind":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrackImage":{"navigatorTitle":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"type":"topic","title":"SocialRadioMixtapeTrackImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrackimage","abstract":[{"type":"text","text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/explicit":{"role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/explicit","abstract":[{"type":"text","text":"True if this track has explicit content, false otherwise"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"explicit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/explicit","title":"explicit","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioWaveformBlob":{"navigatorTitle":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"type":"topic","title":"SocialRadioWaveformBlob","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiowaveformblob","abstract":[{"text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/images":{"role":"symbol","navigatorTitle":[{"text":"images","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/images","abstract":[{"text":"The set of images available for this track","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"images","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SocialRadioMixtapeTrackImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioMixtapeTrackImage"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/images","title":"images","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/init","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/init","abstract":[]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/availableMarkets":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableMarkets"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"availableMarkets","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/availablemarkets","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/availableMarkets","kind":"symbol","role":"symbol","abstract":[{"text":"A list of ISO2 country codes where the track is playable","type":"text"}],"type":"topic","title":"availableMarkets"},"doc://org.cocoapods.SocialRadioLite/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SocialRadioMixtapeTrack","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/artist","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/availableMarkets","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/color","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/images","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/key","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/previewURL","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/service","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/title","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackBpm","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackDuration","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackExplicit","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/trackRef"]},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/init"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"],"title":"Data models","anchor":"Data-models","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeTrack"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/title","value":"SocialRadioTrackModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioTrackModel"}]},{"value":[{"text":"SocialRadioTrackModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/navigatorTitle","op":"replace"},{"value":"service","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1service\/title","op":"replace"},{"value":[{"kind":"identifier","text":"service"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1service\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1trackRef\/title","op":"replace","value":"trackRef"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1trackRef\/fragments","value":[{"kind":"identifier","text":"trackRef"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/title","value":"SocialRadioList"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/fragments","op":"replace","value":[{"text":"SocialRadioList","kind":"identifier"}]},{"op":"replace","value":[{"text":"SocialRadioList","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/navigatorTitle"},{"value":"SocialRadioUser","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/fragments","value":[{"kind":"identifier","text":"SocialRadioUser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/navigatorTitle","value":[{"text":"SocialRadioUser","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1trackExplicit\/title","op":"replace","value":"trackExplicit"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1trackExplicit\/fragments","op":"replace","value":[{"kind":"identifier","text":"trackExplicit"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1trackBpm\/title","value":"trackBpm"},{"op":"replace","value":[{"text":"trackBpm","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1trackBpm\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/title","value":"SocialRadioMixtape"},{"value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/title","value":"SocialRadioStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/navigatorTitle","value":[{"text":"SocialRadioStatus","kind":"identifier"}]},{"value":"SocialRadioMixtapeTrack","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/title","op":"replace"},{"value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/fragments","op":"replace"},{"value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1color\/title","op":"replace","value":"color"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1color\/fragments","value":[{"text":"color","kind":"identifier"}],"op":"replace"},{"value":"previewURL","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1previewURL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"previewURL"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1previewURL\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1trackDuration\/title","op":"replace","value":"trackDuration"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1trackDuration\/fragments","value":[{"kind":"identifier","text":"trackDuration"}],"op":"replace"},{"op":"replace","value":"key","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1key\/title"},{"value":[{"text":"key","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1key\/fragments"},{"value":"SocialRadioArtistModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/title"},{"value":[{"text":"SocialRadioArtistModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioArtistModel"}]},{"value":"title","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1title\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1title\/fragments","value":[{"text":"title","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/title","value":"SocialRadioMixtapeCounters","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/fragments","op":"replace","value":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}]},{"value":"artist","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1artist\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1artist\/fragments","op":"replace","value":[{"kind":"identifier","text":"artist"}]},{"op":"replace","value":"SocialRadioMixtapeLite","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}]},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/title","value":"SocialRadioPluginMetadataModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/fragments","value":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioPluginMetadataModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/title","value":"SocialRadioTunedAuthenticationResponse"},{"value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/navigatorTitle","value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/title","value":"SocialRadioMixtapeTrackImage"},{"op":"replace","value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/navigatorTitle","value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}]},{"op":"replace","value":"SocialRadioWaveformBlob","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/fragments","value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/navigatorTitle","value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}]},{"op":"replace","value":"images","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1images\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1images\/fragments","value":[{"text":"images","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1availableMarkets\/title","op":"replace","value":"availableMarkets"},{"op":"replace","value":[{"kind":"identifier","text":"availableMarkets"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1availableMarkets\/fragments"}]}]}