{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"seeAlsoSections":[{"title":"Data models","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioGenericList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"],"anchor":"Data-models"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/Se","doc:\/\/org.cocoapods.SocialRadioLite\/SE","doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH"],"type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradiolite\/socialradiomixtapecounters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradiolite\/socialradiomixtapecounters"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/init(from:)"],"anchor":"Initializers"},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixBranchDepth","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixBranchPosition","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixComments","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixLikes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixMlScore","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixPlays","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixRecommendations","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixRemixes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixReposts"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters"},"abstract":[{"text":"SocialRadioMixtapeCounters models the set of counters for information about a mixtape","type":"text"}],"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"roleHeading":"Class","title":"SocialRadioMixtapeCounters","modules":[{"name":"SocialRadioLite"}],"navigatorTitle":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"role":"symbol","externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioMixtapeCounters"},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatus":{"navigatorTitle":[{"text":"SocialRadioStatus","kind":"identifier"}],"type":"topic","title":"SocialRadioStatus","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiostatus","abstract":[{"text":"SocialRadioStatus models the State of the AutomixIQ during playback.","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixRemixes":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixRemixes","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"mixRemixes","abstract":[{"type":"text","text":"The number of times this mixtape has been remixed"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixRemixes","url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixremixes","navigatorTitle":[{"kind":"identifier","text":"mixRemixes"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixPlays":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixPlays","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlays"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixplays","abstract":[{"text":"The number of times this mixtape has been played","type":"text"}],"navigatorTitle":[{"text":"mixPlays","kind":"identifier"}],"kind":"symbol","title":"mixPlays"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters","abstract":[{"text":"SocialRadioMixtapeCounters models the set of counters for information about a mixtape","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","title":"SocialRadioMixtapeCounters","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioList":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","role":"symbol","abstract":[],"title":"SocialRadioList","url":"\/documentation\/socialradiolite\/socialradiolist","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioList"}],"navigatorTitle":[{"text":"SocialRadioList","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP"},"doc://org.cocoapods.SocialRadioLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUser":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","abstract":[{"type":"text","text":"SocialRadioUser models a user"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioUser","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiouser","title":"SocialRadioUser","navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtape":{"type":"topic","kind":"symbol","title":"SocialRadioMixtape","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtape","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"role":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","url":"\/documentation\/socialradiolite\/socialradiomixtape"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTrackModel":{"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTrackModel"}],"navigatorTitle":[{"text":"SocialRadioTrackModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiotrackmodel","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","title":"SocialRadioTrackModel","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioArtistModel":{"role":"symbol","navigatorTitle":[{"text":"SocialRadioArtistModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioartistmodel","abstract":[{"type":"text","text":"SocialRadioArtistModel models an artist."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioArtistModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","title":"SocialRadioArtistModel","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/Se":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedAuthenticationResponse":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"abstract":[{"text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"title":"SocialRadioTunedAuthenticationResponse","url":"\/documentation\/socialradiolite\/socialradiotunedauthenticationresponse","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Data-models-article":{"role":"article","url":"\/documentation\/socialradiolite\/data-models-article","abstract":[{"type":"text","text":"How data is passed to and from SocialRadio"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","title":"Data models","kind":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/init(from:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/init(from:)","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/init(from:)","abstract":[],"kind":"symbol","title":"init(from:)"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixReposts":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mixReposts","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"mixReposts","abstract":[{"type":"text","text":"The number of times this mixtape has been reposted"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixReposts","url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixreposts","navigatorTitle":[{"kind":"identifier","text":"mixReposts"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioGenericList":{"navigatorTitle":[{"text":"SocialRadioGenericList","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioGenericList","title":"SocialRadioGenericList","kind":"symbol","abstract":[{"text":"SocialRadioGenericList models a list of things","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioGenericList","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiogenericlist"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrackImage":{"navigatorTitle":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"type":"topic","title":"SocialRadioMixtapeTrackImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrackimage","abstract":[{"type":"text","text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack":{"type":"topic","title":"SocialRadioMixtapeTrack","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioWaveformBlob":{"navigatorTitle":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"type":"topic","title":"SocialRadioWaveformBlob","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiowaveformblob","abstract":[{"text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixBranchPosition":{"title":"mixBranchPosition","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The position of this mixtape in the remix tree of this mixtape"}],"navigatorTitle":[{"text":"mixBranchPosition","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mixBranchPosition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixBranchPosition","url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixbranchposition"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/init":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/init","role":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/init","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixBranchDepth":{"navigatorTitle":[{"kind":"identifier","text":"mixBranchDepth"}],"role":"symbol","type":"topic","kind":"symbol","title":"mixBranchDepth","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixBranchDepth","abstract":[{"text":"The depth of this mixtape in the remix tree of this mixtape","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mixBranchDepth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixbranchdepth"},"doc://org.cocoapods.SocialRadioLite/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SE"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixRecommendations":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixRecommendations","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mixRecommendations","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixrecommendations","abstract":[{"text":"The number of times this mixtape has been recommended","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"mixRecommendations"}],"kind":"symbol","title":"mixRecommendations"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixComments":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mixComments","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"mixComments","abstract":[{"type":"text","text":"The number of times this mixtape has been commented on"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixComments","url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixcomments","navigatorTitle":[{"kind":"identifier","text":"mixComments"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeLite":{"navigatorTitle":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"type":"topic","title":"SocialRadioMixtapeLite","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapelite","abstract":[{"type":"text","text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixMlScore":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixMlScore","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mixMlScore","kind":"identifier"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixmlscore","abstract":[{"type":"text","text":"The likelyhood this mixtape will be liked according to some ML model"}],"navigatorTitle":[{"kind":"identifier","text":"mixMlScore"}],"kind":"symbol","title":"mixMlScore"},"doc://org.cocoapods.SocialRadioLite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.SocialRadioLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ"},"doc://org.cocoapods.SocialRadioLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixLikes":{"title":"mixLikes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixLikes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixlikes","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixLikes","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mixLikes"}],"role":"symbol","abstract":[{"type":"text","text":"The number of times this mixtape has been liked"}]},"doc://org.cocoapods.SocialRadioLite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioPluginMetadataModel":{"role":"symbol","navigatorTitle":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiopluginmetadatamodel","abstract":[{"type":"text","text":"SocialRadioPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"text":" ","type":"text"},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioPluginMetadataModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","title":"SocialRadioPluginMetadataModel","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SocialRadioMixtapeCounters","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixBranchDepth","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixBranchPosition","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixComments","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixLikes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixMlScore","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixPlays","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixRecommendations","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixRemixes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixReposts"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/init"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"value":[{"generated":true,"anchor":"Data-models","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"],"title":"Data models"}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioMixtapeCounters"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/title","value":"SocialRadioStatus","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/fragments","value":[{"text":"SocialRadioStatus","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SocialRadioStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/navigatorTitle"},{"value":"mixRemixes","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixRemixes\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixRemixes\/fragments","value":[{"kind":"identifier","text":"mixRemixes"}],"op":"replace"},{"value":"mixPlays","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixPlays\/title"},{"op":"replace","value":[{"text":"mixPlays","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixPlays\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/title","value":"SocialRadioMixtapeCounters","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/title","op":"replace","value":"SocialRadioList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/fragments","value":[{"text":"SocialRadioList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/navigatorTitle","value":[{"text":"SocialRadioList","kind":"identifier"}]},{"value":"SocialRadioUser","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/title"},{"value":[{"text":"SocialRadioUser","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioUser"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/title","value":"SocialRadioMixtape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/fragments","value":[{"text":"SocialRadioMixtape","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioMixtape","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/title","op":"replace","value":"SocialRadioTrackModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/fragments","value":[{"kind":"identifier","text":"SocialRadioTrackModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/navigatorTitle","value":[{"text":"SocialRadioTrackModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/title","value":"SocialRadioArtistModel","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioArtistModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/navigatorTitle"},{"value":"SocialRadioTunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/title","op":"replace"},{"op":"replace","value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}]},{"value":"mixReposts","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixReposts\/title"},{"value":[{"kind":"identifier","text":"mixReposts"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixReposts\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/title","value":"SocialRadioMixtapeTrackImage"},{"value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/navigatorTitle","value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}]},{"value":"SocialRadioMixtapeTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/title"},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/fragments"},{"value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/title","value":"SocialRadioWaveformBlob","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/fragments","op":"replace","value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}]},{"value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/navigatorTitle"},{"value":"mixBranchPosition","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixBranchPosition\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixBranchPosition\/fragments","value":[{"text":"mixBranchPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixBranchDepth\/title","value":"mixBranchDepth"},{"op":"replace","value":[{"text":"mixBranchDepth","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixBranchDepth\/fragments"},{"op":"replace","value":"mixRecommendations","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixRecommendations\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixRecommendations\/fragments","value":[{"text":"mixRecommendations","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixComments\/title","value":"mixComments","op":"replace"},{"value":[{"kind":"identifier","text":"mixComments"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixComments\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/title","value":"SocialRadioMixtapeLite"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/fragments","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}]},{"value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/navigatorTitle"},{"value":"mixMlScore","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixMlScore\/title"},{"value":[{"kind":"identifier","text":"mixMlScore"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixMlScore\/fragments"},{"value":"mixLikes","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixLikes\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixLikes\/fragments","value":[{"kind":"identifier","text":"mixLikes"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/title","value":"SocialRadioPluginMetadataModel"},{"op":"replace","value":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/fragments"},{"value":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/navigatorTitle","op":"replace"}]}]}