{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioObjC"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio"],"title":"SocialRadio singleton","anchor":"SocialRadio-singleton","generated":true}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioObjC"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:objc(cs)SocialRadioObjC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioObjC","kind":"identifier"}],"role":"symbol","title":"SocialRadioObjC","modules":[{"name":"SocialRadioLite"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/add(_:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/clearCache(completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/endRadioSession(completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/forceRefreshCredentials(completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:isRecording:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/getLiveBroadcasts(withLimit:start:completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/isAudioDeviceActiveOrRecording(_:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/joinLiveBroadcast(withIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/on()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/play(completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/radioUIViewController()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/remove(_:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/reportMixtape(withIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/reportUser(withIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/setRecordingAudioDataWithFrames(_:numberOfChannels:audioPCMBuffer:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/stopEngine()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/terminate()"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/initialised()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/initialize(with:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/instance()","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/internetAvailable()"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"variants":[{"paths":["\/documentation\/socialradiolite\/socialradioobjc"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/isAudioDeviceActiveOrRecording(_:)":{"abstract":[],"title":"isAudioDeviceActiveOrRecording(_:)","url":"\/documentation\/socialradiolite\/socialradioobjc\/isaudiodeviceactiveorrecording(_:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/isAudioDeviceActiveOrRecording(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAudioDeviceActiveOrRecording","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","text":"ObjCBool"},{"kind":"text","text":">) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/instance()":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/instance()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instance"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)SocialRadioObjC","text":"SocialRadioObjC","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradioobjc\/instance()","abstract":[],"title":"instance()","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/setRecordingAudioDataWithFrames(_:numberOfChannels:audioPCMBuffer:)":{"title":"setRecordingAudioDataWithFrames(_:numberOfChannels:audioPCMBuffer:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRecordingAudioDataWithFrames","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfChannels"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"audioPCMBuffer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer","text":"AVAudioPCMBuffer"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/setRecordingAudioDataWithFrames(_:numberOfChannels:audioPCMBuffer:)","url":"\/documentation\/socialradiolite\/socialradioobjc\/setrecordingaudiodatawithframes(_:numberofchannels:audiopcmbuffer:)","abstract":[]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/radioUIViewController()":{"abstract":[],"title":"radioUIViewController()","url":"\/documentation\/socialradiolite\/socialradioobjc\/radiouiviewcontroller()","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/radioUIViewController()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"radioUIViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadioLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"abstract":[],"title":"startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","url":"\/documentation\/socialradiolite\/socialradioobjc\/startradiosession(withidentifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startRadioSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SocialRadioTrackModel","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioTrackModel"},{"kind":"text","text":"]?, "},{"text":"playTrackIndex","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoplay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"contextType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"contextId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?, "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio","kind":"symbol","title":"SocialRadio","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadio"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadio"}],"type":"topic","url":"\/documentation\/socialradiolite\/socialradio","abstract":[{"type":"text","text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/initialised()":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/initialised()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialised","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradioobjc\/initialised()","abstract":[],"title":"initialised()","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/getLiveBroadcasts(withLimit:start:completion:)":{"url":"\/documentation\/socialradiolite\/socialradioobjc\/getlivebroadcasts(withlimit:start:completion:)","abstract":[],"title":"getLiveBroadcasts(withLimit:start:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLiveBroadcasts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"start","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"SocialRadioList","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioList","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/getLiveBroadcasts(withLimit:start:completion:)"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/add(_:)":{"url":"\/documentation\/socialradiolite\/socialradioobjc\/add(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/add(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:@M@SocialRadioLite@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"add(_:)"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/on()":{"abstract":[],"role":"symbol","title":"on()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/on()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"on","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/socialradiolite\/socialradioobjc\/on()"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/reportMixtape(withIdentifier:completion:)":{"url":"\/documentation\/socialradiolite\/socialradioobjc\/reportmixtape(withidentifier:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/reportMixtape(withIdentifier:completion:)","type":"topic","title":"reportMixtape(withIdentifier:completion:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reportMixtape","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.SocialRadioLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)":{"title":"notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/socialradioobjc\/notifyfollowers(withuseridentifier:title:body:objecttype:objectid:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyFollowers","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withUserIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"objectType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"objectId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/internetAvailable()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/internetAvailable()","url":"\/documentation\/socialradiolite\/socialradioobjc\/internetavailable()","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"internetAvailable","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"internetAvailable()","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:isRecording:)":{"kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/socialradioobjc\/getaudiodata(withframes:numberofchannels:fadestate:audiopcmbuffer:isrecording:)","abstract":[],"title":"getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:isRecording:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:isRecording:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getAudioData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withFrames"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfChannels"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"text":"fadeState","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"text":"audioPCMBuffer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAudioPCMBuffer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isRecording"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","text":"ObjCBool"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/remove(_:)":{"abstract":[],"title":"remove(_:)","url":"\/documentation\/socialradiolite\/socialradioobjc\/remove(_:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/remove(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"remove","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@objc(pl)SocialRadioStatusObserverDelegate"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC","url":"\/documentation\/socialradiolite\/socialradioobjc","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioObjC","kind":"identifier"}],"kind":"symbol","title":"SocialRadioObjC","navigatorTitle":[{"kind":"identifier","text":"SocialRadioObjC"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/initialize(with:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)":{"kind":"symbol","url":"\/documentation\/socialradiolite\/socialradioobjc\/initialize(with:socialradiotunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioConfig","kind":"typeIdentifier","text":"SocialRadioConfig"},{"text":", ","kind":"text"},{"text":"socialRadioTunedRestDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"SocialRadioTunedRestDelegate","preciseIdentifier":"c:@M@SocialRadioLite@objc(pl)SocialRadioTunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@SocialRadioLite@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"abstract":[],"title":"initialize(with:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/initialize(with:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/endRadioSession(completion:)":{"url":"\/documentation\/socialradiolite\/socialradioobjc\/endradiosession(completion:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endRadioSession"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": () -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/endRadioSession(completion:)","role":"symbol","title":"endRadioSession(completion:)","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SocialRadioLite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/joinLiveBroadcast(withIdentifier:completion:)":{"abstract":[],"title":"joinLiveBroadcast(withIdentifier:completion:)","url":"\/documentation\/socialradiolite\/socialradioobjc\/joinlivebroadcast(withidentifier:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/joinLiveBroadcast(withIdentifier:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"joinLiveBroadcast"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/play(completion:)":{"title":"play(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"play"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/play(completion:)","url":"\/documentation\/socialradiolite\/socialradioobjc\/play(completion:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/clearCache(completion:)":{"type":"topic","url":"\/documentation\/socialradiolite\/socialradioobjc\/clearcache(completion:)","abstract":[],"role":"symbol","title":"clearCache(completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/clearCache(completion:)"},"doc://org.cocoapods.SocialRadioLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/forceRefreshCredentials(completion:)":{"abstract":[],"type":"topic","title":"forceRefreshCredentials(completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/forceRefreshCredentials(completion:)","url":"\/documentation\/socialradiolite\/socialradioobjc\/forcerefreshcredentials(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceRefreshCredentials"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/stopEngine()":{"url":"\/documentation\/socialradiolite\/socialradioobjc\/stopengine()","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/stopEngine()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopEngine","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","abstract":[],"title":"stopEngine()"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/terminate()":{"kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"terminate","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/socialradiolite\/socialradioobjc\/terminate()","title":"terminate()","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/terminate()"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC/reportUser(withIdentifier:completion:)":{"abstract":[],"title":"reportUser(withIdentifier:completion:)","url":"\/documentation\/socialradiolite\/socialradioobjc\/reportuser(withidentifier:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC\/reportUser(withIdentifier:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio\/title","value":"SocialRadio"},{"value":[{"text":"SocialRadio","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadio"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}