{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}]}],"kind":"declarations"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)"],"anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogDescriptionFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogDescriptionTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBackgroundColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBorder","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBorderColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBorderRadius","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBackgroundColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBorder","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBorderColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBorderRadius","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogTitleFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogTitleTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/fontFamily","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeHuge","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeLarge","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeMatchMachine","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeRegular","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeSmall","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeTiny","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldBackgroundColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldBorderRadius","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldPlaceholderTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/titleFontSize"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH"],"kind":"relationships"}],"kind":"symbol","seeAlsoSections":[{"title":"Initializing SocialRadio for use with Tuned Global’s APIs","generated":true,"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStreamingDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel"]}],"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUIConfig"}],"roleHeading":"Class","title":"SocialRadioUIConfig","symbolKind":"class","modules":[{"name":"SocialRadioLite"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioUIConfig","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiouiconfig"]},{"paths":["\/documentation\/socialradiolite\/socialradiouiconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/radioUIFontSizeTiny":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeTiny","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"radioUIFontSizeTiny","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"radioUIFontSizeTiny","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/radiouifontsizetiny","type":"topic","role":"symbol","navigatorTitle":[{"text":"radioUIFontSizeTiny","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioFeatureSetConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","url":"\/documentation\/socialradiolite\/socialradiofeaturesetconfig","title":"SocialRadioFeatureSetConfig"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogPrimaryButtonBorderRadius":{"navigatorTitle":[{"kind":"identifier","text":"dialogPrimaryButtonBorderRadius"}],"type":"topic","title":"dialogPrimaryButtonBorderRadius","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonBorderRadius","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBorderRadius","kind":"symbol","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogprimarybuttonborderradius"},"doc://org.cocoapods.SocialRadioLite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable":{"abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"title":"SocialRadioStatusVariable","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiostatusvariable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogPrimaryButtonTextColor":{"title":"dialogPrimaryButtonTextColor","kind":"symbol","navigatorTitle":[{"text":"dialogPrimaryButtonTextColor","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogprimarybuttontextcolor","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonTextColor","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/textFieldBorderRadius":{"title":"textFieldBorderRadius","kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/textfieldborderradius","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldBorderRadius"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"textFieldBorderRadius","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldBorderRadius","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogSecondaryButtonBorderRadius":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonBorderRadius"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBorderRadius","title":"dialogSecondaryButtonBorderRadius","navigatorTitle":[{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogsecondarybuttonborderradius","kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/fontFamily":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"fontFamily","kind":"identifier"}],"title":"fontFamily","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/fontFamily","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fontFamily","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/fontfamily"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIDelegate":{"title":"SocialRadioUIDelegate","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiouidelegate","abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIDelegate","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioPlaybackMode":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioplaybackmode","title":"SocialRadioPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode","type":"topic","abstract":[{"text":"SocialRadio playback mode","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioPlaybackMode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/textFieldPlaceholderTextColor":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textFieldPlaceholderTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldPlaceholderTextColor","title":"textFieldPlaceholderTextColor","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/textfieldplaceholdertextcolor","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textFieldPlaceholderTextColor"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fontFamily"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"titleFontSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeHuge","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"radioUIFontSizeLarge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeRegular"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeSmall","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"radioUIFontSizeTiny","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeMatchMachine"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"textFieldFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"textFieldBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"textFieldBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":", ","kind":"text"},{"text":"textFieldPlaceholderTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogTitleFontBold"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogTitleTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogDescriptionFontBold"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"dialogDescriptionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonFontBold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonBorder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogSecondaryButtonFontBold"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBackgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorderRadius","kind":"externalParam"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBorderColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/init(fontfamily:titlefontsize:radiouifontsizehuge:radiouifontsizelarge:radiouifontsizeregular:radiouifontsizesmall:radiouifontsizetiny:radiouifontsizematchmachine:textfieldfontbold:textfieldbackgroundcolor:textfieldborderradius:textfieldtex-7khup","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","role":"symbol","navigatorTitle":[{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"title":"init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogPrimaryButtonBackgroundColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBackgroundColor","title":"dialogPrimaryButtonBackgroundColor","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogprimarybuttonbackgroundcolor","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel","role":"symbol","abstract":[{"type":"text","text":"SocialRadioLogLevel is an enum of all the AutomixIQ available log levels"}],"title":"SocialRadioLogLevel","type":"topic","url":"\/documentation\/socialradiolite\/socialradiologlevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioLogLevel"}],"navigatorTitle":[{"text":"SocialRadioLogLevel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogPrimaryButtonBorder":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogprimarybuttonborder","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBorder"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"dialogPrimaryButtonBorder"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBorder","kind":"symbol","title":"dialogPrimaryButtonBorder"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogPrimaryButtonFontBold":{"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogprimarybuttonfontbold","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonFontBold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"dialogPrimaryButtonFontBold"}],"title":"dialogPrimaryButtonFontBold","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonFontBold"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/textFieldBackgroundColor":{"title":"textFieldBackgroundColor","role":"symbol","navigatorTitle":[{"text":"textFieldBackgroundColor","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/textfieldbackgroundcolor","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textFieldBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"doc://org.cocoapods.SocialRadioLite/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogPrimaryButtonBorderColor":{"role":"symbol","kind":"symbol","abstract":[],"title":"dialogPrimaryButtonBorderColor","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogprimarybuttonbordercolor","navigatorTitle":[{"text":"dialogPrimaryButtonBorderColor","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogPrimaryButtonBorderColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBorderColor","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/radioUIFontSizeMatchMachine":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeMatchMachine"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeMatchMachine","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/radiouifontsizematchmachine","role":"symbol","navigatorTitle":[{"text":"radioUIFontSizeMatchMachine","kind":"identifier"}],"title":"radioUIFontSizeMatchMachine"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/radioUIFontSizeSmall":{"abstract":[],"title":"radioUIFontSizeSmall","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/radiouifontsizesmall","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeSmall"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeSmall","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeSmall","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/radioUIFontSizeRegular":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeRegular","title":"radioUIFontSizeRegular","navigatorTitle":[{"text":"radioUIFontSizeRegular","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/radiouifontsizeregular","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeRegular","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://org.cocoapods.SocialRadioLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioConfig":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioConfig","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioconfig","title":"SocialRadioConfig","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioConfig"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogSecondaryButtonBorder":{"role":"symbol","kind":"symbol","abstract":[],"title":"dialogSecondaryButtonBorder","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogsecondarybuttonborder","navigatorTitle":[{"text":"dialogSecondaryButtonBorder","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogSecondaryButtonBorder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBorder","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedRestDelegate":{"title":"SocialRadioTunedRestDelegate","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiotunedrestdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Initialising-SocialRadio-article":{"role":"article","kind":"article","url":"\/documentation\/socialradiolite\/initialising-socialradio-article","title":"Initializing SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Initialising-SocialRadio-article","type":"topic","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStreamingDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"abstract":[{"text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations.","type":"text"}],"navigatorTitle":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStreamingDelegate","url":"\/documentation\/socialradiolite\/socialradiostreamingdelegate","title":"SocialRadioStreamingDelegate"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogTitleTextColor":{"title":"dialogTitleTextColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dialogTitleTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogtitletextcolor","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogTitleTextColor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dialogTitleTextColor"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadioLite/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogDescriptionTextColor":{"role":"symbol","kind":"symbol","abstract":[],"title":"dialogDescriptionTextColor","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogdescriptiontextcolor","navigatorTitle":[{"text":"dialogDescriptionTextColor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogDescriptionTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogDescriptionTextColor","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/textFieldTextColor":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/textfieldtextcolor","abstract":[],"type":"topic","title":"textFieldTextColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textFieldTextColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldTextColor","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"textFieldTextColor","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","abstract":[],"role":"symbol","title":"SocialRadioUIConfig","navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusObserverDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusObserverDelegate","url":"\/documentation\/socialradiolite\/socialradiostatusobserverdelegate","title":"SocialRadioStatusObserverDelegate"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogDescriptionFontBold":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dialogDescriptionFontBold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"dialogDescriptionFontBold","type":"topic","navigatorTitle":[{"text":"dialogDescriptionFontBold","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogdescriptionfontbold","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogDescriptionFontBold","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/radioUIFontSizeHuge":{"role":"symbol","kind":"symbol","abstract":[],"title":"radioUIFontSizeHuge","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/radiouifontsizehuge","navigatorTitle":[{"text":"radioUIFontSizeHuge","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeHuge"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeHuge","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/titleFontSize":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"titleFontSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"titleFontSize"}],"abstract":[],"title":"titleFontSize","role":"symbol","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/titlefontsize","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/titleFontSize","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/textFieldFontBold":{"role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldFontBold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"textFieldFontBold"}],"kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/textfieldfontbold","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldFontBold","title":"textFieldFontBold"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogSecondaryButtonTextColor":{"title":"dialogSecondaryButtonTextColor","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonTextColor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonTextColor"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogSecondaryButtonTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogsecondarybuttontextcolor"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogSecondaryButtonFontBold":{"navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonFontBold"}],"type":"topic","title":"dialogSecondaryButtonFontBold","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonFontBold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonFontBold","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogsecondarybuttonfontbold","abstract":[]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogSecondaryButtonBackgroundColor":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogsecondarybuttonbackgroundcolor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonBackgroundColor"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBackgroundColor","title":"dialogSecondaryButtonBackgroundColor"},"doc://org.cocoapods.SocialRadioLite/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/radioUIFontSizeLarge":{"role":"symbol","navigatorTitle":[{"text":"radioUIFontSizeLarge","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeLarge","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/radiouifontsizelarge","title":"radioUIFontSizeLarge","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"radioUIFontSizeLarge","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogSecondaryButtonBorderColor":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBorderColor","title":"dialogSecondaryButtonBorderColor","abstract":[],"type":"topic","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogsecondarybuttonbordercolor","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonBorderColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonBorderColor"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogTitleFontBold":{"navigatorTitle":[{"text":"dialogTitleFontBold","kind":"identifier"}],"title":"dialogTitleFontBold","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogTitleFontBold","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogtitlefontbold","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dialogTitleFontBold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SocialRadioUIConfig"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogDescriptionFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogDescriptionTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBackgroundColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBorder","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBorderColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBorderRadius","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBackgroundColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBorder","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBorderColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonBorderRadius","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogSecondaryButtonTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogTitleFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogTitleTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/fontFamily","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeHuge","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeLarge","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeMatchMachine","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeRegular","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeSmall","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/radioUIFontSizeTiny","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldBackgroundColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldBorderRadius","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldFontBold","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldPlaceholderTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldTextColor","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/titleFontSize"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"],"kind":"relationships"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStreamingDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel"],"generated":true,"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs","title":"Initializing SocialRadio for use with Tuned Global’s APIs"}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUIConfig"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"radioUIFontSizeTiny","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeTiny\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeTiny\/fragments","value":[{"text":"radioUIFontSizeTiny","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/title","value":"SocialRadioFeatureSetConfig","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBorderRadius\/title","value":"dialogPrimaryButtonBorderRadius","op":"replace"},{"value":[{"kind":"identifier","text":"dialogPrimaryButtonBorderRadius"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBorderRadius\/fragments"},{"value":"SocialRadioStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}]},{"op":"replace","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonTextColor\/title","value":"dialogPrimaryButtonTextColor"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonTextColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"dialogPrimaryButtonTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldBorderRadius\/title","value":"textFieldBorderRadius"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldBorderRadius\/fragments","value":[{"kind":"identifier","text":"textFieldBorderRadius"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonBorderRadius\/title","value":"dialogSecondaryButtonBorderRadius"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonBorderRadius\/fragments","value":[{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"}],"op":"replace"},{"value":"fontFamily","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1fontFamily\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1fontFamily\/fragments","value":[{"text":"fontFamily","kind":"identifier"}]},{"value":"SocialRadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}]},{"op":"replace","value":"SocialRadioPlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/fragments","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldPlaceholderTextColor\/title","op":"replace","value":"textFieldPlaceholderTextColor"},{"value":[{"text":"textFieldPlaceholderTextColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldPlaceholderTextColor\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/title","value":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBackgroundColor\/title","op":"replace","value":"dialogPrimaryButtonBackgroundColor"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBackgroundColor\/fragments","op":"replace","value":[{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"}]},{"value":"SocialRadioLogLevel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/fragments","value":[{"text":"SocialRadioLogLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioLogLevel"}]},{"value":"dialogPrimaryButtonBorder","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBorder\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBorder\/fragments","value":[{"text":"dialogPrimaryButtonBorder","kind":"identifier"}]},{"op":"replace","value":"dialogPrimaryButtonFontBold","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonFontBold\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonFontBold\/fragments","value":[{"text":"dialogPrimaryButtonFontBold","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldBackgroundColor\/title","value":"textFieldBackgroundColor","op":"replace"},{"value":[{"text":"textFieldBackgroundColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldBackgroundColor\/fragments"},{"value":"dialogPrimaryButtonBorderColor","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBorderColor\/title","op":"replace"},{"op":"replace","value":[{"text":"dialogPrimaryButtonBorderColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBorderColor\/fragments"},{"value":"radioUIFontSizeMatchMachine","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeMatchMachine\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeMatchMachine\/fragments","op":"replace","value":[{"text":"radioUIFontSizeMatchMachine","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeSmall\/title","op":"replace","value":"radioUIFontSizeSmall"},{"op":"replace","value":[{"kind":"identifier","text":"radioUIFontSizeSmall"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeSmall\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeRegular\/title","value":"radioUIFontSizeRegular","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeRegular\/fragments","op":"replace","value":[{"text":"radioUIFontSizeRegular","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/title","value":"SocialRadioConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/fragments","value":[{"text":"SocialRadioConfig","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SocialRadioConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonBorder\/title","value":"dialogSecondaryButtonBorder","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonBorder\/fragments","op":"replace","value":[{"text":"dialogSecondaryButtonBorder","kind":"identifier"}]},{"value":"SocialRadioTunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/title"},{"value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/fragments"},{"value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/navigatorTitle","op":"replace"},{"value":"SocialRadioStreamingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStreamingDelegate\/title"},{"value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStreamingDelegate\/fragments"},{"value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStreamingDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogTitleTextColor\/title","value":"dialogTitleTextColor"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogTitleTextColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"dialogTitleTextColor"}]},{"value":"dialogDescriptionTextColor","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogDescriptionTextColor\/title","op":"replace"},{"value":[{"text":"dialogDescriptionTextColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogDescriptionTextColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldTextColor\/title","value":"textFieldTextColor"},{"value":[{"text":"textFieldTextColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldTextColor\/fragments"},{"value":"SocialRadioUIConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/navigatorTitle","value":[{"text":"SocialRadioUIConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusObserverDelegate\/title","value":"SocialRadioStatusObserverDelegate","op":"replace"},{"op":"replace","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusObserverDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogDescriptionFontBold\/title","value":"dialogDescriptionFontBold"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogDescriptionFontBold\/fragments","op":"replace","value":[{"kind":"identifier","text":"dialogDescriptionFontBold"}]},{"value":"radioUIFontSizeHuge","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeHuge\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeHuge\/fragments","op":"replace","value":[{"kind":"identifier","text":"radioUIFontSizeHuge"}]},{"value":"titleFontSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1titleFontSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1titleFontSize\/fragments","value":[{"kind":"identifier","text":"titleFontSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldFontBold\/title","value":"textFieldFontBold"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldFontBold\/fragments","value":[{"text":"textFieldFontBold","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonTextColor\/title","value":"dialogSecondaryButtonTextColor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonTextColor\/fragments","value":[{"kind":"identifier","text":"dialogSecondaryButtonTextColor"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonFontBold\/title","value":"dialogSecondaryButtonFontBold","op":"replace"},{"op":"replace","value":[{"text":"dialogSecondaryButtonFontBold","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonFontBold\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonBackgroundColor\/title","op":"replace","value":"dialogSecondaryButtonBackgroundColor"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonBackgroundColor\/fragments","value":[{"text":"dialogSecondaryButtonBackgroundColor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeLarge\/title","op":"replace","value":"radioUIFontSizeLarge"},{"value":[{"text":"radioUIFontSizeLarge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1radioUIFontSizeLarge\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonBorderColor\/title","value":"dialogSecondaryButtonBorderColor","op":"replace"},{"value":[{"kind":"identifier","text":"dialogSecondaryButtonBorderColor"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogSecondaryButtonBorderColor\/fragments"},{"value":"dialogTitleFontBold","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogTitleFontBold\/title"},{"value":[{"kind":"identifier","text":"dialogTitleFontBold"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogTitleFontBold\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}