{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadioLite\/Se","doc:\/\/org.cocoapods.SocialRadioLite\/SE","doc:\/\/org.cocoapods.SocialRadioLite\/SQ","doc:\/\/org.cocoapods.SocialRadioLite\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiomixtapelite"]},{"paths":["\/documentation\/socialradiolite\/socialradiomixtapelite"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeLite"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"title":"SocialRadioMixtapeLite","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioMixtapeLite","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"modules":[{"name":"SocialRadioLite"}]},"abstract":[{"type":"text","text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/init(from:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/href","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/mixId"],"anchor":"Instance-Properties"}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioGenericList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"],"anchor":"Data-models","title":"Data models","generated":true}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioArtistModel":{"role":"symbol","navigatorTitle":[{"text":"SocialRadioArtistModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioartistmodel","abstract":[{"type":"text","text":"SocialRadioArtistModel models an artist."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioArtistModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","title":"SocialRadioArtistModel","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatus":{"navigatorTitle":[{"text":"SocialRadioStatus","kind":"identifier"}],"type":"topic","title":"SocialRadioStatus","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiostatus","abstract":[{"text":"SocialRadioStatus models the State of the AutomixIQ during playback.","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioList":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","role":"symbol","abstract":[],"title":"SocialRadioList","url":"\/documentation\/socialradiolite\/socialradiolist","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioList"}],"navigatorTitle":[{"text":"SocialRadioList","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtape":{"type":"topic","kind":"symbol","title":"SocialRadioMixtape","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtape","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"role":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","url":"\/documentation\/socialradiolite\/socialradiomixtape"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedAuthenticationResponse":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"abstract":[{"text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"title":"SocialRadioTunedAuthenticationResponse","url":"\/documentation\/socialradiolite\/socialradiotunedauthenticationresponse","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Data-models-article":{"role":"article","url":"\/documentation\/socialradiolite\/data-models-article","abstract":[{"type":"text","text":"How data is passed to and from SocialRadio"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","title":"Data models","kind":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeLite/href":{"navigatorTitle":[{"kind":"identifier","text":"href"}],"title":"href","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/href","kind":"symbol","abstract":[{"type":"text","text":"The url for its recipe"}],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapelite\/href","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"href","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTrackModel":{"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTrackModel"}],"navigatorTitle":[{"text":"SocialRadioTrackModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiotrackmodel","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","title":"SocialRadioTrackModel","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeLite/init(from:)":{"abstract":[],"title":"init(from:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapelite\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/init(from:)"},"doc://org.cocoapods.SocialRadioLite/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SE"},"doc://org.cocoapods.SocialRadioLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrackImage":{"navigatorTitle":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"type":"topic","title":"SocialRadioMixtapeTrackImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrackimage","abstract":[{"type":"text","text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape"}]},"doc://org.cocoapods.SocialRadioLite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/objc(pl)NSObject"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack":{"type":"topic","title":"SocialRadioMixtapeTrack","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},"doc://org.cocoapods.SocialRadioLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioPluginMetadataModel":{"role":"symbol","navigatorTitle":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiopluginmetadatamodel","abstract":[{"type":"text","text":"SocialRadioPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"text":" ","type":"text"},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioPluginMetadataModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","title":"SocialRadioPluginMetadataModel","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeLite":{"navigatorTitle":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"type":"topic","title":"SocialRadioMixtapeLite","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapelite","abstract":[{"type":"text","text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields"}]},"doc://org.cocoapods.SocialRadioLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SH"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioGenericList":{"navigatorTitle":[{"text":"SocialRadioGenericList","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioGenericList","title":"SocialRadioGenericList","kind":"symbol","abstract":[{"text":"SocialRadioGenericList models a list of things","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioGenericList","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiogenericlist"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioWaveformBlob":{"navigatorTitle":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"type":"topic","title":"SocialRadioWaveformBlob","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiowaveformblob","abstract":[{"text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeLite/mixId":{"kind":"symbol","title":"mixId","abstract":[{"type":"text","text":"The identifier for the mixtape"}],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapelite\/mixid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"mixId"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/mixId"},"doc://org.cocoapods.SocialRadioLite/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters","abstract":[{"text":"SocialRadioMixtapeCounters models the set of counters for information about a mixtape","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","title":"SocialRadioMixtapeCounters","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUser":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","abstract":[{"type":"text","text":"SocialRadioUser models a user"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioUser","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiouser","title":"SocialRadioUser","navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/Se":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeLite/init":{"kind":"symbol","title":"init","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapelite\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/init"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SocialRadioMixtapeLite"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}]},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/href","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/mixId"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite\/init"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":[{"title":"Data models","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"],"generated":true,"anchor":"Data-models"}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeLite"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/title","value":"SocialRadioArtistModel"},{"value":[{"kind":"identifier","text":"SocialRadioArtistModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioArtistModel"}]},{"value":"SocialRadioStatus","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/fragments","value":[{"text":"SocialRadioStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatus"}],"op":"replace"},{"op":"replace","value":"SocialRadioList","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/fragments","value":[{"text":"SocialRadioList","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SocialRadioList","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/navigatorTitle"},{"op":"replace","value":"SocialRadioMixtape","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/title"},{"value":[{"text":"SocialRadioMixtape","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/title","value":"SocialRadioTunedAuthenticationResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/fragments","value":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite~1href\/title","op":"replace","value":"href"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite~1href\/fragments","value":[{"kind":"identifier","text":"href"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/title","value":"SocialRadioTrackModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/fragments","value":[{"text":"SocialRadioTrackModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/title","op":"replace","value":"SocialRadioMixtapeTrackImage"},{"op":"replace","value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/title","value":"SocialRadioMixtapeTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},{"value":"SocialRadioPluginMetadataModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/fragments","op":"replace","value":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/navigatorTitle","value":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/title","value":"SocialRadioMixtapeLite"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/fragments","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}]},{"value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/title","value":"SocialRadioWaveformBlob"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/fragments","value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite~1mixId\/title","op":"replace","value":"mixId"},{"op":"replace","value":[{"text":"mixId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite~1mixId\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/title","value":"SocialRadioMixtapeCounters","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/fragments","value":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/navigatorTitle","op":"replace"},{"op":"replace","value":"SocialRadioUser","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/fragments","op":"replace","value":[{"text":"SocialRadioUser","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}