{"variants":[{"paths":["\/documentation\/socialradiolite\/starting-a-broadcast-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradiolite\/starting-a-broadcast-article"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Creating-a-draft","text":"Creating a draft"},{"inlineContent":[{"type":"text","text":"When you want to start a radio broadcast with a set of tracks, you use "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","isActive":true},{"type":"text","text":" as shown below:"}],"type":"paragraph"},{"syntax":"swift","code":["public class MyApplication {","    \/\/ ...","    func didPressRadioSessionButton() -> Void {","        let identifiers = myIdentifiers","        SocialRadio.instance.startRadioSession(identifiers: identifiers,","                                               metadata: nil,","                                               playTrackIndex:0,","                                               seconds:0,","                                               autoplay: true,","                                               contextType: nil, contextId: nil) { error, controller in","            self.present(controller, animated: true)","        }","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"The UIViewController provided by this function is a fullcreen view that contains the Radio UI and will allow the user tyo curate the playlist, go live with it, end its live session and more. This UI can be minimised and also it can be dismissed by terminating the Radio session.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you want to programatically force-end a radio session the user has created, use "},{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/endRadioSession(completion:)","isActive":true,"type":"reference"},{"text":" as shown below:","type":"text"}]},{"code":["public class MyApplication {","    \/\/ ...","    func didPressEndRadioSessionButton() -> Void {","        SocialRadio.instance.endRadioSession()","    }","    \/\/ ...","}"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Starting-a-broadcast-article","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Creating a draft for a radio show and presenting the UI to curate it, then going live.","type":"text"}],"metadata":{"title":"Starting a broadcast","roleHeading":"Article","role":"article","modules":[{"name":"SocialRadioLite"}]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","kind":"symbol","role":"symbol","title":"startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","navigatorTitle":[{"kind":"identifier","text":"startRadioSessionWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"url":"\/documentation\/socialradiolite\/socialradio\/startradiosession(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRadioSession"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioTrackModel","text":"SocialRadioTrackModel"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoplay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contextType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"radioViewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"abstract":[{"text":"Starts a Radio session in creation mode, with the tracks and metadata provided.","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio/endRadioSession(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endRadioSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/socialradiolite\/socialradio\/endradiosession(completion:)","role":"symbol","abstract":[{"text":"Ends a Radio session. Be mindful if there is an ongoing Live radio show, this will terminate it without asking.","type":"text"}],"navigatorTitle":[{"text":"endRadioSessionWithCompletion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/endRadioSession(completion:)","title":"endRadioSession(completion:)","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"startRadioSessionWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"startRadioSessionWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1endRadioSession(completion:)\/title","value":"endRadioSessionWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1endRadioSession(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endRadioSessionWithCompletion:"}]}]}]}