{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate"]]},"abstract":[{"type":"text","text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required."}],"variants":[{"paths":["\/documentation\/automixiq\/automixiqstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"required":true,"roleHeading":"Instance Method","externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate(im)asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"streamingDeviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"newSessionId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"symbolKind":"method","modules":[{"name":"AutomixIQ"}],"title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncGetStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"streamingDeviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newSessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"streamingDeviceId","content":[{"type":"paragraph","inlineContent":[{"text":"The id of the device attempting to stream content within the streaming APIs.","type":"text"}]}]},{"name":"sessionId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current session Id if available. If one is provided and no longer valid a renewed one will be returned."}]}]},{"name":"trackId","content":[{"inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ is attempting to stream."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Parameter url: the URL that points to the asset to be played, nil in case of an error.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter newSessionId: the session Id of the stream, nil if not required or not available."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter reportingURLS: the set of reporting URLs if available, nil otherwise."}]}]}]}]}]},{"mentions":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article"],"kind":"mentions"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)":{"abstract":[{"type":"text","text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required."}],"title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"asyncGetStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"streamingDeviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newSessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"title":"AutomixIQStreamingDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate","url":"\/documentation\/automixiq\/automixiqstreamingdelegate","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-with-custom-backend-article":{"url":"\/documentation\/automixiq\/initialising-automixiq-with-custom-backend-article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","title":"Initializing AutomixIQ with a custom backend","kind":"article","type":"topic","abstract":[{"text":"How to validate your client and start using the AutomixIQ SDK with a custom backend","type":"text"}],"role":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","url":"\/documentation\/automixiq","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"asyncGetStreamWithStreamingDeviceId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"streamingDeviceId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sessionId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sessionId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"trackId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"trackId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the device attempting to stream content within the streaming APIs."}]}],"name":"streamingDeviceId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current session Id if available. If one is provided and no longer valid a renewed one will be returned."}]}],"name":"sessionId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ is attempting to stream."}]}],"name":"trackId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter url: the URL that points to the asset to be played, nil in case of an error."}]}]},{"content":[{"inlineContent":[{"text":"Parameter newSessionId: the session Id of the stream, nil if not required or not available.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter reportingURLS: the set of reporting URLs if available, nil otherwise."}]}]}],"type":"unorderedList"}],"name":"completion"}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/title","value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/fragments"},{"value":"AutomixIQStreamingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/navigatorTitle","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}