{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Music-Metadata-Database","level":2,"type":"heading","text":"Music Metadata Database"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the Caches Directory, AutomixIQ keeps a light weight sql database to store the metadata of tracks that have been played for subsequent lookup. This file is called “music.db” and if deleted will be recreated on launch."}]},{"anchor":"Music-Analysis-Database","level":2,"type":"heading","text":"Music Analysis Database"},{"type":"paragraph","inlineContent":[{"text":"In the Caches Directory, AutomixIQ keeps a light weight sql database to store the analysis data of tracks that have been played for subsequent lookup. This analysis is required to produce beat-matched transitions. This file is called “paralysis.db” and if deleted will be recreated on launch.","type":"text"}]},{"anchor":"Playback-Log","level":2,"type":"heading","text":"Playback Log"},{"type":"paragraph","inlineContent":[{"text":"AutomixIQ stores offline playback logs for subsequent reporting on a Core Data database, modelled by the following classes:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlayLog"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlayLogAttributes","isActive":true,"type":"reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlayLogID","type":"reference","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"},{"anchor":"Transition-Playback-Log","level":2,"type":"heading","text":"Transition Playback Log"},{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ stores offline transition playback logs for subsequent reporting on a Core Data database, modelled by the following classes:"}]},{"items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTransitionLog","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTransitionLogAttributes","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTransitionLogID","isActive":true}]}]}],"type":"unorderedList"}]}],"variants":[{"paths":["\/documentation\/automixiq\/persistency-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/persistency-article"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Persistency-article","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Article","role":"article","title":"Persistency","modules":[{"name":"AutomixIQ"}]},"sections":[],"abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"seeAlsoSections":[{"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlayLog","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlayLogAttributes","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlayLogID","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTransitionLog","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTransitionLogAttributes","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTransitionLogID"],"generated":true,"anchor":"Persistency"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlayLogID":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlayLogID"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogID"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlayLogID","title":"AutomixIQPlayLogID","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/automixiq\/automixiqplaylogid"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTransitionLogID":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"title":"AutomixIQTransitionLogID","url":"\/documentation\/automixiq\/automixiqtransitionlogid","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTransitionLogID","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlayLog":{"url":"\/documentation\/automixiq\/automixiqplaylog","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlayLog"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlayLog","title":"AutomixIQPlayLog","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLog"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTransitionLogAttributes":{"title":"AutomixIQTransitionLogAttributes","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTransitionLogAttributes","url":"\/documentation\/automixiq\/automixiqtransitionlogattributes","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTransitionLog":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQTransitionLog","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTransitionLog","kind":"symbol","title":"AutomixIQTransitionLog","navigatorTitle":[{"text":"AutomixIQTransitionLog","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqtransitionlog"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlayLogAttributes":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlayLogAttributes","kind":"identifier"}],"title":"AutomixIQPlayLogAttributes","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"AutomixIQPlayLogAttributes","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlayLogAttributes","role":"symbol","url":"\/documentation\/automixiq\/automixiqplaylogattributes"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Persistency","generated":true,"anchor":"Persistency","identifiers":[]}]}],"traits":[{"interfaceLanguage":"occ"}]}]}