{"kind":"symbol","metadata":{"title":"leftTransitionEndTime","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"leftTransitionEndTime"}],"modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformModel(py)leftTransitionEndTime","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftTransitionEndTime","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftTransitionEndTime","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]}]}],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkwaveformmodel\/lefttransitionendtime"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkwaveformmodel\/lefttransitionendtime"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel\/leftTransitionEndTime","interfaceLanguage":"swift"},"abstract":[{"text":"The time in the track the left transition ends at, in seconds","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel/leftTransitionEndTime":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftTransitionEndTime"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"leftTransitionEndTime","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkwaveformmodel\/lefttransitionendtime","type":"topic","title":"leftTransitionEndTime","abstract":[{"type":"text","text":"The time in the track the left transition ends at, in seconds"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel\/leftTransitionEndTime","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel":{"url":"\/documentation\/socialradio\/automixsdkwaveformmodel","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"kind":"symbol","type":"topic","title":"AutomixSDKWaveformModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"leftTransitionEndTime","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"leftTransitionEndTime"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"text":" ","kind":"text"},{"text":"leftTransitionEndTime","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel~1leftTransitionEndTime\/title","value":"leftTransitionEndTime","op":"replace"},{"value":[{"text":"leftTransitionEndTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel~1leftTransitionEndTime\/fragments"},{"value":"AutomixSDKWaveformModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/title"},{"value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]}]}]}