{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"statusObserverDelegate","kind":"internalParam"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC"]]},"metadata":{"title":"add(_:)","externalID":"c:objc(cs)RadioSDKObjC(im)addStatusObserverDelegate:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"SocialRadio"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"add"},{"text":"(any ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/add(_:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/radiosdkobjc\/add(_:)"]}],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate":{"role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"title":"AutomixSDKStatusObserverDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC","role":"symbol","abstract":[],"title":"RadioSDKObjC","url":"\/documentation\/socialradio\/radiosdkobjc","navigatorTitle":[{"kind":"identifier","text":"RadioSDKObjC"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKObjC"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/add(_:)":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"add"},{"text":"(any ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"url":"\/documentation\/socialradio\/radiosdkobjc\/add(_:)","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/add(_:)","title":"add(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AutomixSDKStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]}]}]}