{"sections":[],"abstract":[{"text":"Pauses playback if playing.","type":"text"},{"text":" ","type":"text"},{"text":"Returns an error if the player is already paused.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}]}]}],"type":"unorderedList"}]}],"kind":"parameters"},{"mentions":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Controlling-playback-article"],"kind":"mentions"}],"variants":[{"paths":["\/documentation\/automixiq\/automixiq\/pause(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiq\/pause(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/pause(completion:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTracks(identifiers:metadata:contextType:contextId:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTrack(identifier:metadata:contextType:contextId:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/playTrackUntilEndThenPause(_:completion:)"],"anchor":"Playback-Control","title":"Playback Control","generated":true}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQ(im)pauseWithCompletion:","role":"symbol","navigatorTitle":[{"text":"pauseWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"symbolKind":"method","modules":[{"name":"AutomixIQ"}],"title":"pause(completion:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/previous(completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/previous(completion:)","type":"topic","navigatorTitle":[{"text":"previousWithCompletion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq\/previous(completion:)","abstract":[{"text":"Moves the player to the beginning of the previous track","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previous","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"previous(completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/skipToTrackAtIndex(_:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipToTrackAtIndex"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixiq\/skiptotrackatindex(_:completion:)","abstract":[{"type":"text","text":"Jumps playback to the beginning of the track at the desired index as soon as possible."}],"navigatorTitle":[{"text":"skipToTrackAtIndex:completion:","kind":"identifier"}],"title":"skipToTrackAtIndex(_:completion:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/skipToTrackAtIndex(_:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","url":"\/documentation\/automixiq","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"url":"\/documentation\/automixiq\/automixiq\/loadtracks(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","abstract":[{"text":"Loads a new playlist into AutomixIQ","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Returns an error if the playlist is empty this opperation will fail and AutomixIQ will be turned off."},{"type":"text","text":" "},{"type":"text","text":"This will stop playback of the currently playing playlist and start the newly loaded one."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadTracks","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","text":"TunedTrackModel","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ":{"navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}],"title":"AutomixIQ","kind":"symbol","url":"\/documentation\/automixiq\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ","type":"topic","abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQ","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/back(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"back"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixiq\/back(completion:)","abstract":[{"type":"text","text":"Moves the player to the beginning of the current track"}],"navigatorTitle":[{"text":"backWithCompletion:","kind":"identifier"}],"title":"back(completion:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/back(completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/playTrackUntilEndThenPause(_:completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/playTrackUntilEndThenPause(_:completion:)","type":"topic","navigatorTitle":[{"text":"playTrackUntilEndThenPause:completion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq\/playtrackuntilendthenpause(_:completion:)","abstract":[{"type":"text","text":"Makes AutomixIQ play a given track until the end and then pause."},{"type":"text","text":" "},{"type":"text","text":"This is useful if you need to play any other content between tracks such as advertisements."},{"type":"text","text":" "},{"type":"text","text":"Returns an error if you call this on the last track’"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playTrackUntilEndThenPause"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"title":"playTrackUntilEndThenPause(_:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/play(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixiq\/play(completion:)","abstract":[{"type":"text","text":"Starts playback if paused."},{"type":"text","text":" "},{"type":"text","text":"Returns an error if the player is already playing."}],"navigatorTitle":[{"kind":"identifier","text":"playWithCompletion:"}],"title":"play(completion:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/play(completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/pause(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixiq\/pause(completion:)","abstract":[{"text":"Pauses playback if playing.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Returns an error if the player is already paused."}],"navigatorTitle":[{"kind":"identifier","text":"pauseWithCompletion:"}],"title":"pause(completion:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/pause(completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/addTracks(identifiers:metadata:contextType:contextId:index:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"addTracksWithIdentifiers:metadata:contextType:contextId:index:completion:"}],"title":"addTracks(identifiers:metadata:contextType:contextId:index:completion:)","kind":"symbol","url":"\/documentation\/automixiq\/automixiq\/addtracks(identifiers:metadata:contexttype:contextid:index:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTracks(identifiers:metadata:contextType:contextId:index:completion:)","type":"topic","abstract":[{"text":"Adds additional tracks to the playlist in AutomixIQ at a given index.","type":"text"},{"text":" ","type":"text"},{"text":"Returns an erorr if the index is out of bounds.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTracks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","text":"TunedTrackModel","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/seekTo(seconds:completion:)":{"navigatorTitle":[{"text":"seekToSeconds:completion:","kind":"identifier"}],"title":"seekTo(seconds:completion:)","kind":"symbol","url":"\/documentation\/automixiq\/automixiq\/seekto(seconds:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/seekTo(seconds:completion:)","type":"topic","abstract":[{"type":"text","text":"Jumps playback on the current track to the desired timestamp as soon as possible."},{"type":"text","text":" "},{"type":"text","text":"This will mix the track with itself so the seek is beat-matched and as seamless as possible, which means the landing position will be close but not exactly the fed timestamp."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekTo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"seconds"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setAutomixPlaySpeed(_:completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setAutomixPlaySpeed(_:completion:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAutomixPlaySpeed:completion:"}],"url":"\/documentation\/automixiq\/automixiq\/setautomixplayspeed(_:completion:)","abstract":[{"type":"text","text":"Sets AutomixIQ’s play speed to a given value between 0.5 and 2, where 0.5 is half speed and 2 is double speed."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setAutomixPlaySpeed","kind":"identifier"},{"text":"(Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"setAutomixPlaySpeed(_:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/removeTrack(at:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/removeTrack(at:completion:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixiq\/removetrack(at:completion:)","navigatorTitle":[{"kind":"identifier","text":"removeTrackAt:completion:"}],"title":"removeTrack(at:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Removes a track at a given index in the AutomixIQ playlist."},{"type":"text","text":" "},{"text":"Returns an erorr if the index is out of bounds.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/toggleReplay(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggleReplay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"deprecated":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/toggleReplay(completion:)","role":"symbol","title":"toggleReplay(completion:)","abstract":[{"text":"If on, after a playlist is done it restarts. Otherwise, it pauses.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This defaults to false on initialisation and should be set to match the state of the consumer’s UI"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixiq\/togglereplay(completion:)","navigatorTitle":[{"kind":"identifier","text":"toggleReplayWithCompletion:"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/next(completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/next(completion:)","type":"topic","navigatorTitle":[{"text":"nextWithCompletion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq\/next(completion:)","abstract":[{"text":"Moves the player to the beginning of the next track","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"next","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"title":"next(completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/moveTrack(at:toIndex:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moveTrack"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"toIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/moveTrack(at:toIndex:completion:)","role":"symbol","title":"moveTrack(at:toIndex:completion:)","abstract":[{"text":"Moves the track from one index to a different index.","type":"text"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixiq\/movetrack(at:toindex:completion:)","navigatorTitle":[{"kind":"identifier","text":"moveTrackAt:toIndex:completion:"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/addTrack(identifier:metadata:contextType:contextId:index:completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTrack(identifier:metadata:contextType:contextId:index:completion:)","type":"topic","navigatorTitle":[{"text":"addTrackWithIdentifier:metadata:contextType:contextId:index:completion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq\/addtrack(identifier:metadata:contexttype:contextid:index:completion:)","abstract":[{"text":"Adds a single track to the AutomixIQ playlist at a given index.","type":"text"},{"text":" ","type":"text"},{"text":"Returns an erorr if the index is out of bounds.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TunedTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"contextType"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"title":"addTrack(identifier:metadata:contextType:contextId:index:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setReplay(on:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setReplay(on:completion:)","navigatorTitle":[{"kind":"identifier","text":"setReplayOn:completion:"}],"abstract":[{"text":"Tells AutomixIQ whether or not it should restart the playlist when reaching the end.","type":"text"},{"text":" ","type":"text"},{"text":"If on then playback will restart at the beginning otherwise it pauses at the end.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setReplay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"kind":"symbol","title":"setReplay(on:completion:)","url":"\/documentation\/automixiq\/automixiq\/setreplay(on:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Controlling-playback-article":{"url":"\/documentation\/automixiq\/controlling-playback-article","abstract":[{"type":"text","text":"How to play, skip, pause and seek through content"}],"title":"Controlling Playback","kind":"article","type":"topic","role":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Controlling-playback-article"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"pauseWithCompletion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"pauseWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTracks(identifiers:metadata:contextType:contextId:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTrack(identifier:metadata:contextType:contextId:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/playTrackUntilEndThenPause(_:completion:)"],"anchor":"Playback-Control","generated":true,"title":"Playback Control"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"pauseWithCompletion:"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^)("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}]}]}],"type":"unorderedList"}],"name":"completion"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1previous(completion:)\/title","value":"previousWithCompletion:"},{"value":[{"text":"- ","kind":"text"},{"text":"previousWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1previous(completion:)\/fragments"},{"value":"skipToTrackAtIndex:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1skipToTrackAtIndex(_:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"skipToTrackAtIndex:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1skipToTrackAtIndex(_:completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title","value":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments"},{"value":"AutomixIQ","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/fragments","value":[{"text":"AutomixIQ","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/navigatorTitle","value":[{"text":"AutomixIQ","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1back(completion:)\/title","value":"backWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1back(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backWithCompletion:"}],"op":"replace"},{"op":"replace","value":"playTrackUntilEndThenPause:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1playTrackUntilEndThenPause(_:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playTrackUntilEndThenPause:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1playTrackUntilEndThenPause(_:completion:)\/fragments"},{"op":"replace","value":"playWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1play(completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1play(completion:)\/fragments"},{"op":"replace","value":"pauseWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1pause(completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pauseWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1pause(completion:)\/fragments"},{"op":"replace","value":"addTracksWithIdentifiers:metadata:contextType:contextId:index:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1addTracks(identifiers:metadata:contextType:contextId:index:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addTracksWithIdentifiers:metadata:contextType:contextId:index:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1addTracks(identifiers:metadata:contextType:contextId:index:completion:)\/fragments"},{"op":"replace","value":"seekToSeconds:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1seekTo(seconds:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"seekToSeconds:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1seekTo(seconds:completion:)\/fragments"},{"op":"replace","value":"setAutomixPlaySpeed:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setAutomixPlaySpeed(_:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAutomixPlaySpeed:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setAutomixPlaySpeed(_:completion:)\/fragments"},{"op":"replace","value":"removeTrackAt:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1removeTrack(at:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeTrackAt:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1removeTrack(at:completion:)\/fragments"},{"op":"replace","value":"toggleReplayWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1toggleReplay(completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toggleReplayWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1toggleReplay(completion:)\/fragments"},{"op":"replace","value":"nextWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1next(completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1next(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nextWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1moveTrack(at:toIndex:completion:)\/title","op":"replace","value":"moveTrackAt:toIndex:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1moveTrack(at:toIndex:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveTrackAt:toIndex:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1addTrack(identifier:metadata:contextType:contextId:index:completion:)\/title","op":"replace","value":"addTrackWithIdentifier:metadata:contextType:contextId:index:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1addTrack(identifier:metadata:contextType:contextId:index:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addTrackWithIdentifier:metadata:contextType:contextId:index:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setReplay(on:completion:)\/title","op":"replace","value":"setReplayOn:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setReplay(on:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setReplayOn:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}