{"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offAlreadyTurningOff","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/offalreadyturningoff"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/offalreadyturningoff"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode"]]},"metadata":{"title":"AutomixSDKErrorCode.offAlreadyTurningOff","role":"symbol","modules":[{"name":"PacemakerRadio"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"externalID":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeOffAlreadyTurningOff","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offAlreadyTurningOff"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offAlreadyTurningOff","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","title":"PacemakerRadio","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode":{"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode","title":"AutomixSDKErrorCode","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/offAlreadyTurningOff":{"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/offalreadyturningoff","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offAlreadyTurningOff","abstract":[],"kind":"symbol","title":"AutomixSDKErrorCode.offAlreadyTurningOff","navigatorTitle":[{"text":"AutomixSDKErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offAlreadyTurningOff","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"AutomixSDKErrorCodeOffAlreadyTurningOff","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOffAlreadyTurningOff"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeOffAlreadyTurningOff"}]}],"kind":"declarations"}},{"value":"AutomixSDKErrorCode","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/fragments","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offAlreadyTurningOff\/title","value":"AutomixSDKErrorCodeOffAlreadyTurningOff","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offAlreadyTurningOff\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOffAlreadyTurningOff"}],"op":"replace"}]}]}