{"metadata":{"title":"type","modules":[{"name":"SocialRadio"}],"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKPlaylistOperation(py)type","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"type"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutomixSDKPlaylistOperationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKPlaylistOperationType"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation\/type","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKPlaylistOperationType","kind":"typeIdentifier","text":"AutomixSDKPlaylistOperationType","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation"]]},"variants":[{"paths":["\/documentation\/socialradio\/automixsdkplaylistoperation\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixsdkplaylistoperation\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The type of operation, Add \/ Remove \/ Move"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperation/type":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKPlaylistOperationType","text":"AutomixSDKPlaylistOperationType"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation\/type","abstract":[{"type":"text","text":"The type of operation, Add \/ Remove \/ Move"}],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkplaylistoperation\/type","title":"type"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperation":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkplaylistoperation","type":"topic","title":"AutomixSDKPlaylistOperation","abstract":[{"type":"text","text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperationType":{"url":"\/documentation\/socialradio\/automixsdkplaylistoperationtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"title":"AutomixSDKPlaylistOperationType","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"type","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKPlaylistOperationType","kind":"typeIdentifier","text":"AutomixSDKPlaylistOperationType","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"type","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation~1type\/title"},{"op":"replace","value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation~1type\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation\/fragments","value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}]},{"value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/title","value":"AutomixSDKPlaylistOperationType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/fragments","value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/navigatorTitle"}]}]}