{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonFontBold"}],"title":"dialogSecondaryButtonFontBold","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioUIConfig(py)dialogSecondaryButtonFontBold","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonFontBold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/dialogSecondaryButtonFontBold","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/socialradio\/socialradiouiconfig\/dialogsecondarybuttonfontbold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiouiconfig\/dialogsecondarybuttonfontbold"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonFontBold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"url":"\/documentation\/socialradio","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig":{"role":"symbol","title":"SocialRadioUIConfig","abstract":[{"text":"Social Radio UI options","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","url":"\/documentation\/socialradio\/socialradiouiconfig","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig/dialogSecondaryButtonFontBold":{"title":"dialogSecondaryButtonFontBold","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/dialogSecondaryButtonFontBold","abstract":[],"type":"topic","url":"\/documentation\/socialradio\/socialradiouiconfig\/dialogsecondarybuttonfontbold","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonFontBold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonFontBold"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dialogSecondaryButtonFontBold","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"dialogSecondaryButtonFontBold"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonFontBold"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SocialRadioUIConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/title"},{"value":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/fragments"},{"value":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/navigatorTitle"},{"value":"dialogSecondaryButtonFontBold","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1dialogSecondaryButtonFontBold\/title"},{"value":[{"kind":"identifier","text":"dialogSecondaryButtonFontBold"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1dialogSecondaryButtonFontBold\/fragments"}]}]}