{"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"metadata":{"modules":[{"name":"SocialRadio"}],"role":"article","title":"Initializing SocialRadio with custom audio and social layer","roleHeading":"Article"},"abstract":[{"type":"text","text":"How to validate your client and start using the SocialRadio SDK with custom audio track data and custom social layer."}],"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Essentials","anchor":"Essentials"},{"type":"paragraph","inlineContent":[{"text":"This document explains how to integrate SocialRadio with your application if it gets its audio data, metadata and social layer from a custom backend.","type":"text"}]},{"level":3,"type":"heading","text":"Initialization with custom audio","anchor":"Initialization-with-custom-audio"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to initialise SocialRadio with custom audio you need the following:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"text":"Tuned Global Store ID","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Tuned Global Application ID","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Device Country Code","type":"text"}]}]}]},{"type":"codeListing","syntax":"swift","code":["func application(_ application: UIApplication, ","                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","    \/\/ ...","","    let automixIQStreamingDelegate: AutomixIQStreamingDelegate = myAutomixIQStreamingDelegate","    let socialRadioTrackMetadataDelegate: SocialRadioTrackMetadataDelegate = mySocialRadioTrackMetadataDelegate","    let socialRadioUIDelegate: SocialRadioUIDelegate = mySocialRadioUIDelegate","    let socialRadioStatusObserverDelegate: SocialRadioStatusObserverDelegate = mySocialRadioStatusObserverDelegate","    let authenticationDelegate: AuthenticationDelegate = myTrackDataBackendAuthenticationDelegate","    let countryCode: String = myCountryCode \/\/ \"US\" ? \"AU\"?","    let storeId: String = myTunedStoreId","    let applicationId: String = myApplicationId","    let myAPIKey: String = myApplicationKey","","    let config = SocialRadioConfig(apiKey: myAPIKey, country: countryCode, storeId: storeId, applicationId: applicationId)","    SocialRadio.initialise(config: config","                           automixIQStreamingDelegate: automixIQStreamingDelegate,","                           socialRadioTrackMetadataDelegate: socialRadioTrackMetadataDelegate","                           socialRadioStatusDelegate: socialRadioStatusObserverDelegate,","                           socialRadioUIDelegate: socialRadioUIDelegate,","                           authenticationDelegate: authenticationDelegate)","    { error in","        if error != nil {","            \/\/ This means you are forbidden to use the Automix SDK or you have no internet connection.","            return","        }","        \/\/ The Automix SDK public functions can be used from this point onwards :)","    }","","    \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"text":"After initialising it, on the completion block, you can use SocialRadio’s singleton to get the Tuned Global’s implementation of the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","type":"reference"},{"text":" to overwrite the module you are interested in with your own implementation, or provide your own ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","type":"reference"},{"text":". Use ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/tunedGlobalSocialLayerDelegates()","type":"reference"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"After you are happy with your complete delegate set, you can set it onto SocialRadio’s singleton. Use ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/setSocialLayerDelegates(_:)","type":"reference"},{"type":"text","text":"."}]},{"code":["","    \/\/ ...","    let mySocialLayerDelegates = SocialRadio.instance.tunedGlobalSocialLayerDelegates()","    mySocialLayerDelegates.mixtapeCommentsDelegate = nil                    \/\/ If you are not interested in this module","    mySocialLayerDelegates.mixtapeLikesDelegate = myMixtapeLikesDelegate    \/\/ For a custom implementation of the delegate","    \/\/ ...","    SocialRadio.instance.setSocialLayerDelegates(mySocialLayerDelegates)","    \/\/ ...",""],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Please refer to each module’s delegation for details:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","type":"reference"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate","isActive":true,"type":"reference"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can also tweak the SocialRadio UI and available feature set by changing flags on the config object. See "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","isActive":true,"type":"reference"},{"type":"text","text":"."}]},{"anchor":"AutomixIQStreamingDelegate","level":4,"type":"heading","text":"AutomixIQStreamingDelegate"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If your custom backend puts fetching metadata and track data behind a login, SocialRadio needs to know if the user in your application is logged in or not via"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/isLoggedIn()","isActive":true,"type":"reference"}]}]}]},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func isLoggedIn() {","        return self.loggedIn","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"If your custom backend only allows playback on a device under certain conditions (for instance it only allows one device to play at any given time), SocialRadio needs to know if a device is allowed to play via","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncCheckDeviceStatus(completion:)","type":"reference","isActive":true}]}]}]},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func asyncCheckDeviceStatus(completion: @escaping (_ error: Error?, _ canContinuePlaying: Bool) -> Void) {","        self.canDeviceContinuePlaying() { allowedToPlay in","            return allowedToPlay","        }","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SocialRadio requires devices to have a unique identifier, provided via"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/getDeviceIdentifier()"}]}]}]},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func getDeviceIdentifier() -> String {","        return self.deviceIdentifier","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This provides hooks to inject cached track audio data and metadata, preventing SocialRadio from having to request this data from your custom backend if they are already available. This also enables offline playback when all required data is available on the device"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"This is done via ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","type":"reference"}]},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func syncGetTrackMetadata(trackId: String?) -> TunedTrackModel? {","        \/\/ If I have this track cached, I should be able to tell its metadata","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.metadataForTrack(trackId)","    }","    \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"text":"and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","type":"reference"}]},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func syncGetCachedTrack(trackId: String) -> Data? {","        \/\/ If I have this track cached, I should be able to decrypt it and send the data","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.unencryptedDataForTrack(trackId)","    }","    \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"text":"SocialRadio will pass every track metadata model it may have downloaded to the client to provide an opportunity to cache it. If you do not need this, you may leave this function empty.","type":"text"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/cacheMetadata(_:)","isActive":true}]},{"syntax":"swift","type":"codeListing","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func cacheMetadata(_ metadata: [TunedTrackModel]) -> Data? {","        self.metadataForTrack[metadata.trackId] = metadata","    }","    \/\/ ...","}"]},{"items":[{"content":[{"inlineContent":[{"text":"SocialRadio will download track metadata as it needs it. When required, it will do so via","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","isActive":true,"type":"reference"}],"type":"paragraph"}]}],"type":"unorderedList"},{"syntax":"swift","type":"codeListing","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func asyncGetTrackMetadata(trackId: String, completion: @escaping (_ error: Error?, _ track: TunedTrackModel?) -> Void) {","        self.getTrackMetadata(trackId: trackId) { error, trackMetadata in","            let automixIQTrackModel = translateMetadata(trackMetadata)","            return completion(error, automixIQTrackModel)","        }","    }","    \/\/ ...","}"]},{"items":[{"content":[{"inlineContent":[{"text":"When SocialRadio needs to download a track, it will ask for the url for it. It supports session IDs if you want urls to expire and return 403s. It will do so via","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)"}],"type":"paragraph"}]}],"type":"unorderedList"},{"syntax":"swift","type":"codeListing","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func asyncGetStream(streamingDeviceId: String, sessionId: String, trackId: String, completion: @escaping (_ error: Error?, _ url: String?, _ newSessionId: String?, _ reportingURLS: Beacons?) -> Void) {","        self.getTrackURL(deviceId: streamingDeviceId, sessionId: sessionId, trackId: trackId) { error, url in ","            return completion(error, url)","        }","    }","    \/\/ ...","}"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When a track finishes downloading, SocialRadio will pass the audio data for you to cache if required. This is done via"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadCompleted(trackId:data:)"}]}]}],"type":"unorderedList"},{"syntax":"swift","type":"codeListing","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func trackDownloadCompleted(trackId: String, data: NSData) {","        self.cacheTrack(trackId: trackId, data: data)","    }","    \/\/ ...","}"]},{"items":[{"content":[{"inlineContent":[{"text":"As a track is being downloaded, SocialRadio will report download progress via","type":"text"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)"}],"type":"paragraph"}]}],"type":"unorderedList"},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func trackDownloadProgressChanged(trackId: String, progress: Swift.Float) {","        self.updateTrackDownloadProgress(trackId: trackId, progress: progress)","    }","    \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Do keep in mind this download is done lazily, as SocialRadio requires data for analysis \/ playback. There is no guarantee a track will download in its entirety if the track is not played in its entirety."}]},{"type":"heading","text":"SocialRadioTrackMetadataDelegate","level":4,"anchor":"SocialRadioTrackMetadataDelegate"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","type":"reference","isActive":true},{"text":" is responsible for getting artwork for tracks, and track recommendations:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SocialRadio will ask you for the URL to a provider of artwork given track Ids:"}]}]}]},{"type":"codeListing","syntax":"swift","code":["public class MySocialRadioTrackMetadataDelegate: NSObject, SocialRadioTrackMetadataDelegate {","    \/\/ ...","    func asyncGetThumborLocation(completion: @escaping(_ url: String?) -> Void) -> Void {","        return self.imageGenerationURL","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"SocialRadio will ask for track recommendations for a given track:","type":"text"}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":"swift","code":["public class MySocialRadioTrackMetadataDelegate: NSObject, SocialRadioTrackMetadataDelegate {","    \/\/ ...","    func asyncGetTrackRecommendations(identifiers: [String],","                                      contextIds: [String]?,","                                      limit: Int, completion: @escaping(_ tracks: [TunedTrackModel]?) -> Void) -> Void {","        return completion(self.trackRecommendations(identifiers)","    }","    \/\/ ...","}"]},{"type":"heading","text":"SocialRadioUIDelegate","level":4,"anchor":"SocialRadioUIDelegate"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"reference"},{"text":" is responsible for providing data required for the Radio UI to function, as well as presenting UI SocialRadio is not able to do on its own.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"SocialRadio allows the user to add one or multiple tracks to a radio show. When that action is triggered, SocialRadio asks this delegate to provide the UI for selecting them. This is done via ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentTracklist(filterOutExplicitContent:completion:)","type":"reference","isActive":true}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":"swift","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func presentTracklist(filterOutExplicitContent: Bool,","                          completion: @escaping (_ tracks: [TunedTrackModel]?,","                                                 _ contextType: String?, _ contextId: Int,","                                                 _ playlistName: String?) -> Void) {","        \/\/ Your implementation for presenting UI that allows to select one or more tracks:","        let tracklist = MyTracklist() { tracks, playlistName in","            \/\/ - Feed the track\/tracks selected as the second paramenter of the completion block,","            \/\/ - If the tracks selected are part of a playlist, feed the name opf that playlist as the thirsd parameter of the completion block.","            completion(tracks, playlistName)","        }","        self.present(filterOutExplicitContent, tracklist, animated: true)","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"At a time where SocialRadio requires a Tuned User Id, if it does not have one it will require the user to authenticate via ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentAuthentication(completion:)","isActive":true}]}]}]},{"type":"codeListing","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func presentAuthentication(completion: @escaping (_ success: Bool) -> Void) {","        \/\/ Present your login here","        let authenticationDialog = MyAuthenticationDialog() { success in","            completion(success)","        }","        self.present(authenticationDialog, animated: true)","    }","    \/\/ ...","}"],"syntax":"swift"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"At times, SocialRadio will need to present a users’ profile. It will do so via "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentProfile(identifier:completion:)"}],"type":"paragraph"}]}]},{"syntax":"swift","type":"codeListing","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func presentProfile(identifier: String?, completion: @escaping () -> Void) {","        \/\/ Present the user profile here","        let profileDialog = MyProfileDialog(identifier: identifier) {","            completion()","        }","        self.present(profileDialog, animated: true)","    }","    \/\/ ...","}"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SocialRadio also notifies this delegate when it will and has minimised the Radio UI, and when it will and has closed the Radio UI. It does so via "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willDismissRadioUI(userInitiated:)"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didDismissRadioUI(userInitiated:)"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willCloseRadioUI(userInitiated:)"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didCloseRadioUI(userInitiated:)"},{"type":"text","text":"."}]}]}],"type":"unorderedList"},{"syntax":"swift","type":"codeListing","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func willDismissRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    ","    func didDismissRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    ","    func willCloseRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    ","    func didCloseRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    \/\/ ...","}"]},{"level":4,"anchor":"SocialRadioStatusObserverDelegate","type":"heading","text":"SocialRadioStatusObserverDelegate"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"reference","isActive":true},{"type":"text","text":" is responsible for updating your player’s UI."}],"type":"paragraph"},{"level":4,"anchor":"AuthenticationDelegate","type":"heading","text":"AuthenticationDelegate"},{"inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","isActive":true},{"text":" is responsible for fetching and refreshing your custom audio backend’s credentials:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"SocialRadio will ask you to refresh your custom audio backend’s credentials should they have expired:","type":"text"}],"type":"paragraph"}]}]},{"code":["public class MyAuthenticationDelegate: NSObject, AuthenticationDelegate {","    func refreshCredentials(oldAccessToken: String?, refreshToken: String?, tokenType: String?,","                                completion: @escaping (_ error: Error?,","                                                       _ credentials: SocialRadioCredentials?) -> Void) {","        self.refreshCredentials(completion)","    }","}"],"syntax":"swift","type":"codeListing"},{"anchor":"Checking-if-SocialRadio-is-initialised","type":"heading","level":3,"text":"Checking if SocialRadio is initialised"},{"inlineContent":[{"text":"To check wether AutomixIQ is currently initialised, use","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialised()","type":"reference"}],"type":"paragraph"}]}]}],"kind":"content"}],"seeAlsoSections":[{"title":"Initialising SocialRadio for use with custom audio and custom social layer","anchor":"Initialising-SocialRadio-for-use-with-custom-audio-and-custom-social-layer","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-and-social-layer-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-and-social-layer-article"]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/didDismissRadioUI(userInitiated:)":{"url":"\/documentation\/socialradio\/socialradiouidelegate\/diddismissradioui(userinitiated:)","abstract":[{"type":"text","text":"Called by SocialRadio when the Radio UI is dismissed"}],"type":"topic","kind":"symbol","title":"didDismissRadioUI(userInitiated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didDismissRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"didDismissRadioUIWithUserInitiated:"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didDismissRadioUI(userInitiated:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/presentAuthentication(completion:)":{"abstract":[{"type":"text","text":"Called by SocialRadio when it wishes to present UI to authenticate a user"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentAuthentication(completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentAuthentication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"presentAuthentication(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"presentAuthenticationWithCompletion:"}],"url":"\/documentation\/socialradio\/socialradiouidelegate\/presentauthentication(completion:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeLikesDelegate":{"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a mixtape."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeLikesDelegate","kind":"identifier"}],"title":"SocialLayerMixtapeLikesDelegate","role":"symbol","navigatorTitle":[{"text":"SocialLayerMixtapeLikesDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayermixtapelikesdelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/cacheMetadata(_:)":{"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/cachemetadata(_:)","abstract":[{"text":"AutomixIQ calls this function to provide a chance to cache metadata to shortcut future requests.","type":"text"}],"type":"topic","kind":"symbol","title":"cacheMetadata(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheMetadata"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"TunedTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"cacheMetadata:"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/cacheMetadata(_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/willDismissRadioUI(userInitiated:)":{"abstract":[{"type":"text","text":"Called by SocialRadio when the Radio UI about to be dismissed"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willDismissRadioUI(userInitiated:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willDismissRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"willDismissRadioUI(userInitiated:)","role":"symbol","navigatorTitle":[{"text":"willDismissRadioUIWithUserInitiated:","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiouidelegate\/willdismissradioui(userinitiated:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/presentProfile(identifier:completion:)":{"url":"\/documentation\/socialradio\/socialradiouidelegate\/presentprofile(identifier:completion:)","abstract":[{"text":"Called by SocialRadio when it wishes to present UI with a user’s information","type":"text"}],"type":"topic","kind":"symbol","title":"presentProfile(identifier:completion:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentProfile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"presentProfileWithIdentifier:completion:"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentProfile(identifier:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/presentTracklist(filterOutExplicitContent:completion:)":{"abstract":[{"type":"text","text":"Called by SocialRadio when it wishes to present UI to select one or many tracks"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentTracklist(filterOutExplicitContent:completion:)","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentTracklist"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filterOutExplicitContent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tracks"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","kind":"typeIdentifier","text":"TunedTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"contextType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"contextId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playlistName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"presentTracklist(filterOutExplicitContent:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"presentTracklistWithFilterOutExplicitContent:completion:"}],"url":"\/documentation\/socialradio\/socialradiouidelegate\/presenttracklist(filteroutexplicitcontent:completion:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerModerationDelegate":{"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding content moderation."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"title":"SocialLayerModerationDelegate","role":"symbol","navigatorTitle":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayermoderationdelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackMetadataDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTrackMetadataDelegate"}],"url":"\/documentation\/socialradio\/socialradiotrackmetadatadelegate","role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Handles track recommendations and artwork","type":"text"}],"title":"SocialRadioTrackMetadataDelegate","navigatorTitle":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AuthenticationDelegate":{"abstract":[{"type":"text","text":"Handles handoff of authentication tokens"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationDelegate"}],"title":"AuthenticationDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AuthenticationDelegate"}],"url":"\/documentation\/socialradio\/authenticationdelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/syncGetTrackMetadata(trackId:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/syncgettrackmetadata(trackid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"TunedTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"syncGetTrackMetadata(trackId:)","type":"topic","navigatorTitle":[{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate":{"abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding commenting a mixtape.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}],"title":"SocialLayerMixtapeCommentsDelegate","role":"symbol","navigatorTitle":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/initialised()":{"url":"\/documentation\/socialradio\/socialradio\/initialised()","abstract":[{"type":"text","text":"Returns the initialised status of the Automix SDK."}],"type":"topic","kind":"symbol","title":"initialised()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialised"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"initialised"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialised()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/getDeviceIdentifier()":{"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/getdeviceidentifier()","abstract":[{"type":"text","text":"Called by Automix to learn the identity of the device requesting to stream audio, for those services that require it."},{"type":"text","text":" "},{"type":"text","text":"An example would be, a service that only allows one device to stream at any one time, would need to know the identity of the device to provide the stream."}],"type":"topic","kind":"symbol","title":"getDeviceIdentifier()","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeviceIdentifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"getDeviceIdentifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/getDeviceIdentifier()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerNotificationsDelegate":{"abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding notifications.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"title":"SocialLayerNotificationsDelegate","role":"symbol","navigatorTitle":[{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayernotificationsdelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"title":"SocialRadioConfig","type":"topic","navigatorTitle":[{"text":"SocialRadioConfig","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioConfig","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","url":"\/documentation\/socialradio\/socialradioconfig","abstract":[{"text":"SocialRadioConfig holds the variables to initialise SocialRadio and describe the desired feature set and UI","type":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"navigatorTitle":[{"kind":"identifier","text":"SocialLayerDelegates"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions."},{"type":"text","text":" "},{"type":"text","text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc."},{"type":"text","text":" "},{"type":"text","text":"See each delegate’s documentation for details."}],"url":"\/documentation\/socialradio\/sociallayerdelegates","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerDelegates"}],"title":"SocialLayerDelegates","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/setSocialLayerDelegates(_:)":{"abstract":[{"text":"Sets the Social Layer delegates","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/setSocialLayerDelegates(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSocialLayerDelegates"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates","text":"SocialLayerDelegates"},{"kind":"text","text":"?)"}],"title":"setSocialLayerDelegates(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setSocialLayerDelegates:"}],"url":"\/documentation\/socialradio\/socialradio\/setsociallayerdelegates(_:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerUserDelegate":{"abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding  users."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerUserDelegate"}],"title":"SocialLayerUserDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialLayerUserDelegate"}],"url":"\/documentation\/socialradio\/sociallayeruserdelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/isLoggedIn()":{"abstract":[{"type":"text","text":"Called by AutomixIQ to learn if it is allowed to stream content that is protected by some form of authentication."},{"type":"text","text":" "},{"type":"text","text":"An example is, an implementation via an API behind OAuth would return true if access and refresh tokens are available, false otherwise"}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/isloggedin()","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/isLoggedIn()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLoggedIn","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"isLoggedIn","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"isLoggedIn()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/trackDownloadProgressChanged(trackId:progress:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"role":"symbol","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/trackdownloadprogresschanged(trackid:progress:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)","title":"trackDownloadProgressChanged(trackId:progress:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerTrackLikesDelegate":{"url":"\/documentation\/socialradio\/sociallayertracklikesdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"type":"topic","title":"SocialLayerTrackLikesDelegate","navigatorTitle":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a track.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/didCloseRadioUI(userInitiated:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called by SocialRadio when the Radio UI is closed"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate\/didcloseradioui(userinitiated:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didCloseRadioUI(userInitiated:)","title":"didCloseRadioUI(userInitiated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/trackDownloadCompleted(trackId:data:)":{"abstract":[{"text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadCompleted(trackId:data:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDownloadCompleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"trackDownloadCompleted(trackId:data:)","role":"symbol","navigatorTitle":[{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/trackdownloadcompleted(trackid:data:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"type":"topic","title":"SocialRadioUIDelegate","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","abstract":[{"type":"text","text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate":{"abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding live mixtapes."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}],"title":"SocialLayerLiveMixtapeDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}],"url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"title":"AutomixIQStreamingDelegate","type":"topic","navigatorTitle":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","url":"\/documentation\/socialradio\/automixiqstreamingdelegate","abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/syncGetCachedTrack(trackId:)":{"abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/syncgetcachedtrack(trackid:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetCachedTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"syncGetCachedTrack(trackId:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerAuthenticationDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}],"url":"\/documentation\/socialradio\/sociallayerauthenticationdelegate","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding authentication"}],"title":"SocialLayerAuthenticationDelegate","navigatorTitle":[{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/asyncGetTrackMetadata(trackId:completion:)":{"abstract":[{"type":"text","text":"Called by AutomixIQ when it requires the metadata of a track in order to load it."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetTrackMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"track"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","text":"TunedTrackModel"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"title":"asyncGetTrackMetadata(trackId:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"asyncGetTrackMetadataWithTrackId:completion:"}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/asyncgettrackmetadata(trackid:completion:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/asyncCheckDeviceStatus(completion:)":{"type":"topic","title":"asyncCheckDeviceStatus(completion:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"asyncCheckDeviceStatusWithCompletion:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncCheckDeviceStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"canContinuePlaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncCheckDeviceStatus(completion:)","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/asynccheckdevicestatus(completion:)","abstract":[{"text":"Called by AutomixIQ regularly while something is being played, this can be used if you have restrictions on the number of devices that can play simultaneously","type":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"title":"SocialRadioStatusObserverDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","role":"collection","type":"topic","title":"SocialRadio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/willCloseRadioUI(userInitiated:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willCloseRadioUIWithUserInitiated:"}],"abstract":[{"text":"Called by SocialRadio when the Radio UI is closed","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate\/willcloseradioui(userinitiated:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willCloseRadioUI(userInitiated:)","title":"willCloseRadioUI(userInitiated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willCloseRadioUI"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate":{"kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"type":"topic","title":"SocialLayerMixtapeBackgroundsDelegate","navigatorTitle":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)":{"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)","abstract":[{"type":"text","text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required."}],"type":"topic","kind":"symbol","title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncGetStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"streamingDeviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"sessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newSessionId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/tunedGlobalSocialLayerDelegates()":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"}],"abstract":[{"text":"Gets the Tuned Global’s backend implementation of the Social Layer delegates","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradio\/tunedglobalsociallayerdelegates()","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/tunedGlobalSocialLayerDelegates()","title":"tunedGlobalSocialLayerDelegates()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SocialLayerDelegates","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate"],"anchor":"Initialising-SocialRadio-for-use-with-custom-audio-and-custom-social-layer","title":"Initialising SocialRadio for use with custom audio and custom social layer","generated":true}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didDismissRadioUI(userInitiated:)\/title","value":"didDismissRadioUIWithUserInitiated:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didDismissRadioUI(userInitiated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didDismissRadioUIWithUserInitiated:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentAuthentication(completion:)\/title","value":"presentAuthenticationWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentAuthentication(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentAuthenticationWithCompletion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/title","value":"SocialLayerMixtapeLikesDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/fragments","value":[{"text":"SocialLayerMixtapeLikesDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/navigatorTitle","value":[{"text":"SocialLayerMixtapeLikesDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1cacheMetadata(_:)\/title","value":"cacheMetadata:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1cacheMetadata(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cacheMetadata:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willDismissRadioUI(userInitiated:)\/title","value":"willDismissRadioUIWithUserInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willDismissRadioUI(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willDismissRadioUIWithUserInitiated:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentProfile(identifier:completion:)\/title","value":"presentProfileWithIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentProfile(identifier:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentProfileWithIdentifier:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentTracklist(filterOutExplicitContent:completion:)\/title","value":"presentTracklistWithFilterOutExplicitContent:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentTracklist(filterOutExplicitContent:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentTracklistWithFilterOutExplicitContent:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/title","value":"SocialLayerModerationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerModerationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/navigatorTitle","value":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/title","value":"SocialRadioTrackMetadataDelegate"},{"op":"replace","value":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/fragments"},{"op":"replace","value":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/navigatorTitle"},{"op":"replace","value":"AuthenticationDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AuthenticationDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AuthenticationDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/title","value":"syncGetTrackMetadataWithTrackId:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/title","value":"SocialLayerMixtapeCommentsDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialised()\/title","value":"initialised","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialised()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initialised"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/title","value":"getDeviceIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDeviceIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/title","value":"SocialLayerNotificationsDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerNotificationsDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/navigatorTitle","value":[{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","value":"SocialRadioConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","value":"SocialLayerDelegates","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"kind":"identifier","text":"SocialLayerDelegates"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1setSocialLayerDelegates(_:)\/title","value":"setSocialLayerDelegates:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1setSocialLayerDelegates(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setSocialLayerDelegates:","kind":"identifier"}],"op":"replace"},{"value":"SocialLayerUserDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/title","op":"replace"},{"value":[{"text":"SocialLayerUserDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/fragments","op":"replace"},{"value":[{"text":"SocialLayerUserDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/navigatorTitle","op":"replace"},{"value":"isLoggedIn","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1isLoggedIn()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isLoggedIn","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1isLoggedIn()\/fragments","op":"replace"},{"value":"trackDownloadProgressChangedWithTrackId:progress:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments","op":"replace"},{"value":"SocialLayerTrackLikesDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/title","op":"replace"},{"value":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/navigatorTitle","op":"replace"},{"value":"didCloseRadioUIWithUserInitiated:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didCloseRadioUI(userInitiated:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didCloseRadioUI(userInitiated:)\/fragments","op":"replace"},{"value":"trackDownloadCompletedWithTrackId:data:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/fragments","op":"replace"},{"value":"SocialRadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","op":"replace"},{"value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","op":"replace"},{"value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","op":"replace"},{"value":"SocialLayerLiveMixtapeDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/title","op":"replace"},{"value":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/navigatorTitle","op":"replace"},{"value":"AutomixIQStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title","op":"replace"},{"value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle","op":"replace"},{"value":"syncGetCachedTrackWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/fragments","op":"replace"},{"value":"SocialLayerAuthenticationDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/title","op":"replace"},{"value":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/fragments","op":"replace"},{"value":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/navigatorTitle","op":"replace"},{"value":"asyncGetTrackMetadataWithTrackId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetTrackMetadataWithTrackId:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/fragments"},{"value":"asyncCheckDeviceStatusWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"asyncCheckDeviceStatusWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/fragments"},{"value":"SocialRadioStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title"},{"value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments"},{"value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle"},{"value":"willCloseRadioUIWithUserInitiated:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willCloseRadioUI(userInitiated:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willCloseRadioUIWithUserInitiated:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willCloseRadioUI(userInitiated:)\/fragments"},{"value":"SocialLayerMixtapeBackgroundsDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/title"},{"value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/title","op":"replace","value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}]},{"value":"tunedGlobalSocialLayerDelegates","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1tunedGlobalSocialLayerDelegates()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tunedGlobalSocialLayerDelegates"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1tunedGlobalSocialLayerDelegates()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}