{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate"]]},"abstract":[{"text":"Retrieves the recipe file","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"method","title":"downloadRecipe(identifier:completion:)","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerLiveMixtapeDelegate(im)downloadRecipeWithIdentifier:completion:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadRecipe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"recipe","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"text":"downloadRecipeWithIdentifier:completion:","kind":"identifier"}],"modules":[{"name":"SocialRadio"}]},"variants":[{"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/downloadrecipe(identifier:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/downloadrecipe(identifier:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/downloadRecipe(identifier:completion:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadRecipe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"recipe","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The mixtape identifier.","type":"text"}],"type":"paragraph"}],"name":"identifier"},{"content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter recipe: the recipe file data."}]}]}],"type":"unorderedList"}],"name":"completion"}],"kind":"parameters"}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate/downloadRecipe(identifier:completion:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/downloadRecipe(identifier:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadRecipe"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"recipe","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"downloadRecipeWithIdentifier:completion:"}],"url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/downloadrecipe(identifier:completion:)","type":"topic","title":"downloadRecipe(identifier:completion:)","required":true,"abstract":[{"text":"Retrieves the recipe file","type":"text"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate":{"role":"symbol","title":"SocialLayerLiveMixtapeDelegate","url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","kind":"symbol","navigatorTitle":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"abstract":[{"text":"(Required) Handles communication between SocialRadio SDK and a backend regarding live mixtapes.","type":"text"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"url":"\/documentation\/socialradio","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"downloadRecipeWithIdentifier:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"downloadRecipeWithIdentifier:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"downloadRecipeWithIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The mixtape identifier.","type":"text"}]}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Parameter recipe: the recipe file data."}],"type":"paragraph"}]}]}],"name":"completion"}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":"downloadRecipeWithIdentifier:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1downloadRecipe(identifier:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1downloadRecipe(identifier:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"downloadRecipeWithIdentifier:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/title","value":"SocialLayerLiveMixtapeDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/fragments","value":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/navigatorTitle","value":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"op":"replace"}]}]}