{"metadata":{"roleHeading":"Case","externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariableReplayOn","role":"symbol","title":"AutomixIQStatusVariable.replayOn","navigatorTitle":[{"text":"AutomixIQStatusVariableReplayOn","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replayOn","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/replayOn","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"replayOn"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/replayon"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/replayon"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"title":"AutomixIQStatusVariable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/replayOn":{"type":"topic","title":"AutomixIQStatusVariable.replayOn","navigatorTitle":[{"text":"AutomixIQStatusVariableReplayOn","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/replayOn","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replayOn","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/replayon"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AutomixIQStatusVariableReplayOn","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableReplayOn"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixIQStatusVariableReplayOn"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title","value":"AutomixIQStatusVariable","op":"replace"},{"value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1replayOn\/title","value":"AutomixIQStatusVariableReplayOn","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1replayOn\/fragments","value":[{"text":"AutomixIQStatusVariableReplayOn","kind":"identifier"}],"op":"replace"}]}]}