{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC"]]},"sections":[],"metadata":{"role":"symbol","externalID":"c:objc(cs)SocialRadioObjC(im)setSocialLayerDelegates:","symbolKind":"method","title":"setSocialLayerDelegates(_:)","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSocialLayerDelegates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SocialLayerDelegates","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/setSocialLayerDelegates(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSocialLayerDelegates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"delegates","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerDelegates","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates"},{"text":"?)","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/socialradio\/socialradioobjc\/setsociallayerdelegates(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC","title":"SocialRadioObjC","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioObjC","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioObjC","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradioobjc","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC/setSocialLayerDelegates(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSocialLayerDelegates","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates","text":"SocialLayerDelegates","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/setSocialLayerDelegates(_:)","url":"\/documentation\/socialradio\/socialradioobjc\/setsociallayerdelegates(_:)","title":"setSocialLayerDelegates(_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"navigatorTitle":[{"text":"SocialLayerDelegates","kind":"identifier"}],"title":"SocialLayerDelegates","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerDelegates","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions."},{"type":"text","text":" "},{"type":"text","text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc."},{"type":"text","text":" "},{"type":"text","text":"See each delegate’s documentation for details."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","type":"topic","url":"\/documentation\/socialradio\/sociallayerdelegates"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","value":"SocialLayerDelegates","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"kind":"identifier","text":"SocialLayerDelegates"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerDelegates"}],"op":"replace"}]}]}