{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/remove(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"statusObserverDelegate"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixIQStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqobjc\/remove(_:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"remove","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"remove(_:)","symbolKind":"method","externalID":"c:objc(cs)AutomixIQObjC(im)removeStatusObserverDelegate:","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Method"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"type":"topic","abstract":[{"text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"navigatorTitle":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"title":"AutomixIQStatusObserverDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/socialradio\/automixiqobjc","role":"symbol","title":"AutomixIQObjC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQObjC","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC/remove(_:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/remove(_:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"AutomixIQStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate"},{"text":")","kind":"text"}],"url":"\/documentation\/socialradio\/automixiqobjc\/remove(_:)","role":"symbol","title":"remove(_:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","type":"topic","title":"SocialRadio","role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title","value":"AutomixIQStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle"}]}]}