{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixtapeBackgroundsDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","text":"SocialLayerMixtapeBackgroundsDelegate"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds."}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"mixtapeBackgroundsDelegate","navigatorTitle":[{"kind":"identifier","text":"mixtapeBackgroundsDelegate"}],"modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates(py)mixtapeBackgroundsDelegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixtapeBackgroundsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialLayerMixtapeBackgroundsDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/mixtapeBackgroundsDelegate"},"variants":[{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/mixtapebackgroundsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/mixtapebackgroundsdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialLayerDelegates"}],"role":"symbol","title":"SocialLayerDelegates","navigatorTitle":[{"kind":"identifier","text":"SocialLayerDelegates"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","abstract":[{"type":"text","text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions."},{"type":"text","text":" "},{"type":"text","text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc."},{"type":"text","text":" "},{"type":"text","text":"See each delegate’s documentation for details."}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayerdelegates","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates/mixtapeBackgroundsDelegate":{"title":"mixtapeBackgroundsDelegate","navigatorTitle":[{"kind":"identifier","text":"mixtapeBackgroundsDelegate"}],"url":"\/documentation\/socialradio\/sociallayerdelegates\/mixtapebackgroundsdelegate","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/mixtapeBackgroundsDelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixtapeBackgroundsDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate","kind":"typeIdentifier","text":"SocialLayerMixtapeBackgroundsDelegate"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerMixtapeBackgroundsDelegate"}],"role":"symbol","title":"SocialLayerMixtapeBackgroundsDelegate","navigatorTitle":[{"kind":"identifier","text":"SocialLayerMixtapeBackgroundsDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate","type":"topic","kind":"symbol","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mixtapeBackgroundsDelegate"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"mixtapeBackgroundsDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate","text":"id<SocialLayerMixtapeBackgroundsDelegate>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixtapeBackgroundsDelegate"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SocialLayerDelegates","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"text":"SocialLayerDelegates","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SocialLayerDelegates"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle"},{"op":"replace","value":"mixtapeBackgroundsDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1mixtapeBackgroundsDelegate\/title"},{"op":"replace","value":[{"text":"mixtapeBackgroundsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1mixtapeBackgroundsDelegate\/fragments"},{"op":"replace","value":"SocialLayerMixtapeBackgroundsDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/title"},{"op":"replace","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerMixtapeBackgroundsDelegate"}],"op":"replace"}]}]}