{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackLikesDelegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerTrackLikesDelegate","kind":"typeIdentifier","text":"SocialLayerTrackLikesDelegate"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a track.","type":"text"}],"variants":[{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/tracklikesdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/tracklikesdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","title":"trackLikesDelegate","navigatorTitle":[{"kind":"identifier","text":"trackLikesDelegate"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackLikesDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerTrackLikesDelegate","text":"SocialLayerTrackLikesDelegate"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"SocialRadio"}],"symbolKind":"property","externalID":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates(py)trackLikesDelegate"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/trackLikesDelegate","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerTrackLikesDelegate":{"navigatorTitle":[{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}],"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a track."}],"type":"topic","url":"\/documentation\/socialradio\/sociallayertracklikesdelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}],"kind":"symbol","title":"SocialLayerTrackLikesDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates/trackLikesDelegate":{"title":"trackLikesDelegate","navigatorTitle":[{"text":"trackLikesDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayerdelegates\/tracklikesdelegate","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a track.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/trackLikesDelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackLikesDelegate"},{"text":": ","kind":"text"},{"text":"SocialLayerTrackLikesDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerTrackLikesDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialLayerDelegates"}],"role":"symbol","title":"SocialLayerDelegates","navigatorTitle":[{"kind":"identifier","text":"SocialLayerDelegates"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","abstract":[{"type":"text","text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions."},{"type":"text","text":" "},{"type":"text","text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc."},{"type":"text","text":" "},{"type":"text","text":"See each delegate’s documentation for details."}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayerdelegates","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"trackLikesDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"trackLikesDelegate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialLayerTrackLikesDelegate","text":"id<SocialLayerTrackLikesDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackLikesDelegate"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/title","value":"SocialLayerTrackLikesDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/fragments","value":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1trackLikesDelegate\/title","value":"trackLikesDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1trackLikesDelegate\/fragments","value":[{"kind":"identifier","text":"trackLikesDelegate"}]},{"op":"replace","value":"SocialLayerDelegates","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"kind":"identifier","text":"SocialLayerDelegates"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerDelegates","kind":"identifier"}]}]}]}