{"kind":"symbol","abstract":[{"text":"Objective-C accessible member for the bpm, 09 if unavailable","type":"text"}],"variants":[{"paths":["\/documentation\/socialradiolite\/socialradiotrackmodel\/bpm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradiolite\/socialradiotrackmodel\/bpm"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bpm","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioTrackModel(py)bpm","roleHeading":"Instance Property","modules":[{"name":"SocialRadioLite"}],"title":"bpm","navigatorTitle":[{"kind":"identifier","text":"bpm"}],"role":"symbol","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bpm"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel\/bpm","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel"]]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTrackModel":{"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTrackModel"}],"navigatorTitle":[{"text":"SocialRadioTrackModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiotrackmodel","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","title":"SocialRadioTrackModel","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTrackModel/bpm":{"abstract":[{"text":"Objective-C accessible member for the bpm, 09 if unavailable","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel\/bpm","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bpm","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","navigatorTitle":[{"text":"bpm","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiotrackmodel\/bpm","title":"bpm","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"bpm","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"bpm","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"bpm"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SocialRadioTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/fragments","value":[{"text":"SocialRadioTrackModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioTrackModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel~1bpm\/title","value":"bpm"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel~1bpm\/fragments","value":[{"kind":"identifier","text":"bpm"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}