{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperation"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixiqplaylistoperation\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqplaylistoperation\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixIQPlaylistOperationType","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQPlaylistOperationType"}],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperation\/type","interfaceLanguage":"swift"},"abstract":[{"text":"The type of operation, Add \/ Remove \/ Move","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixIQPlaylistOperationType","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQPlaylistOperationType"}],"title":"type","navigatorTitle":[{"kind":"identifier","text":"type"}],"roleHeading":"Instance Property","externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQPlaylistOperation(py)type","symbolKind":"property","modules":[{"name":"AutomixIQ"}],"role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaylistOperation":{"type":"topic","url":"\/documentation\/automixiq\/automixiqplaylistoperation","title":"AutomixIQPlaylistOperation","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"abstract":[{"text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperation","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaylistOperation/type":{"type":"topic","title":"type","url":"\/documentation\/automixiq\/automixiqplaylistoperation\/type","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperation\/type","abstract":[{"type":"text","text":"The type of operation, Add \/ Remove \/ Move"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQPlaylistOperationType","kind":"typeIdentifier","text":"AutomixIQPlaylistOperationType"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaylistOperationType":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType","title":"AutomixIQPlaylistOperationType","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}],"role":"symbol","url":"\/documentation\/automixiq\/automixiqplaylistoperationtype","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"type":"topic","role":"collection","kind":"symbol","title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"type","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQPlaylistOperationType","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType","text":"AutomixIQPlaylistOperationType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperation\/title","value":"AutomixIQPlaylistOperation","op":"replace"},{"value":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperation\/fragments"},{"value":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperation\/navigatorTitle"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperation~1type\/title"},{"value":[{"kind":"identifier","text":"type"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperation~1type\/fragments"},{"value":"AutomixIQPlaylistOperationType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType\/title"},{"value":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType\/fragments"},{"value":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}