{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape","roleHeading":"Class","role":"symbol","title":"SocialRadioMixtape","symbolKind":"class","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtape"}]},"abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/Se","doc:\/\/org.cocoapods.SocialRadio\/SE","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtape","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiomixtape"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiomixtape"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/init(from:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/author","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/containsExplicitTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/created","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/deleted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/minEngineVersion","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixIsDraft","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixLength","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixLive","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixPlus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixRecipeHash","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixUserLikes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/recommendedDate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/status","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/tags","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/title","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/tracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/updated","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/waveform"],"anchor":"Instance-Properties"}],"sections":[],"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Data models","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse"],"anchor":"Data-models"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/tags":{"abstract":[{"type":"text","text":"This mixtape’s tags"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tags"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"role":"symbol","title":"tags","url":"\/documentation\/socialradio\/socialradiomixtape\/tags","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/tags","navigatorTitle":[{"kind":"identifier","text":"tags"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/minEngineVersion":{"type":"topic","kind":"symbol","title":"minEngineVersion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minEngineVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/minEngineVersion","url":"\/documentation\/socialradio\/socialradiomixtape\/minengineversion","abstract":[{"text":"The minimum version of the Mix Engine that can play this mixtape","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"minEngineVersion","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"navigatorTitle":[{"kind":"identifier","text":"TunedTrackModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","type":"topic","abstract":[{"type":"text","text":"TunedTrackModel models a track. This metadata is required."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedTrackModel"}],"url":"\/documentation\/socialradio\/tunedtrackmodel","title":"TunedTrackModel","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage":{"kind":"symbol","title":"SocialRadioMixtapeTrackImage","abstract":[{"type":"text","text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","url":"\/documentation\/socialradio\/socialradiomixtapetrackimage"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioList":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioList"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioList","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiolist","type":"topic","abstract":[],"title":"SocialRadioList","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape":{"url":"\/documentation\/socialradio\/socialradiomixtape","abstract":[{"text":"SocialRadioMixtape models a mixtape","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtape","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","kind":"symbol","type":"topic","role":"symbol","title":"SocialRadioMixtape","navigatorTitle":[{"text":"SocialRadioMixtape","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SE"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"SocialRadio status variable type","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusVariable"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"url":"\/documentation\/socialradio\/socialradiostatusvariable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","title":"SocialRadioStatusVariable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatus":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatus"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatus"}],"title":"SocialRadioStatus","url":"\/documentation\/socialradio\/socialradiostatus","kind":"symbol","abstract":[{"type":"text","text":"SocialRadioStatus models the State of the AutomixIQ during playback."}],"role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedPluginMetadataModel":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","title":"TunedPluginMetadataModel","navigatorTitle":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedPluginMetadataModel","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"TunedPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"text":" ","type":"text"},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"url":"\/documentation\/socialradio\/tunedpluginmetadatamodel","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/mixRecipeHash":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixRecipeHash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The hash opf this mixtape"}],"kind":"symbol","url":"\/documentation\/socialradio\/socialradiomixtape\/mixrecipehash","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixRecipeHash","navigatorTitle":[{"text":"mixRecipeHash","kind":"identifier"}],"role":"symbol","type":"topic","title":"mixRecipeHash"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/updated":{"navigatorTitle":[{"text":"updated","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"abstract":[{"text":"The time this mixtape was last updated","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/updated","title":"updated","url":"\/documentation\/socialradio\/socialradiomixtape\/updated","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack":{"navigatorTitle":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"type":"topic","title":"SocialRadioMixtapeTrack","abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"url":"\/documentation\/socialradio\/socialradiomixtapetrack","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack"},"doc://org.cocoapods.SocialRadio/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/mixLength":{"type":"topic","navigatorTitle":[{"text":"mixLength","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixLength","abstract":[{"text":"The duration in seconds of this mixtape","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiomixtape\/mixlength","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixLength","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"mixLength"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/waveform":{"kind":"symbol","abstract":[{"type":"text","text":"The waveform representation for this mixtape"}],"title":"waveform","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveform","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioWaveformBlob","text":"SocialRadioWaveformBlob","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"waveform","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/waveform","url":"\/documentation\/socialradio\/socialradiomixtape\/waveform","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/mixIsDraft":{"title":"mixIsDraft","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixIsDraft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"mixIsDraft"}],"abstract":[{"text":"True if this mixtape is a draft, false otherwise","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiomixtape\/mixisdraft","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixIsDraft"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/author":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiomixtape\/author","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/author","navigatorTitle":[{"text":"author","kind":"identifier"}],"abstract":[{"text":"The author of this mixtape","type":"text"}],"title":"author","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"author","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser","text":"SocialRadioUser","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/Se","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode":{"navigatorTitle":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradioplaybackmode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","type":"topic","title":"SocialRadioPlaybackMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadio playback mode"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/deleted":{"url":"\/documentation\/socialradio\/socialradiomixtape\/deleted","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"deleted","kind":"identifier"}],"role":"symbol","title":"deleted","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/deleted","abstract":[{"text":"true if this mixtape was deleted, false otherwise","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/status":{"abstract":[{"type":"text","text":"The status of this mixtape, i.e. “posted”, “cocreation”, “live”, nil otherwise"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"status","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/status","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"status"}],"url":"\/documentation\/socialradio\/socialradiomixtape\/status","role":"symbol"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Data-models-article":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","title":"Data models","kind":"article","type":"topic","abstract":[{"text":"How data is passed to and from SocialRadio","type":"text"}],"url":"\/documentation\/socialradio\/data-models-article","role":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/tracks":{"url":"\/documentation\/socialradio\/socialradiomixtape\/tracks","kind":"symbol","abstract":[{"type":"text","text":"This mixtape’s tracks"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/tracks","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SocialRadioMixtapeTrack","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtapeTrack"},{"kind":"text","text":"]?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"tracks"}],"title":"tracks"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCredentials":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiocredentials","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioCredentials"}],"abstract":[{"type":"text","text":"SocialRadioCredentials models credentials to access social REST APIs."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","title":"SocialRadioCredentials","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioCredentials"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioWaveformBlob":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","url":"\/documentation\/socialradio\/socialradiowaveformblob","role":"symbol","navigatorTitle":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"type":"topic","title":"SocialRadioWaveformBlob","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/created":{"title":"created","abstract":[{"text":"The time this mixtape was created","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/created","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"created"}],"type":"topic","url":"\/documentation\/socialradio\/socialradiomixtape\/created","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/mixUserLikes":{"title":"mixUserLikes","role":"symbol","url":"\/documentation\/socialradio\/socialradiomixtape\/mixuserlikes","navigatorTitle":[{"kind":"identifier","text":"mixUserLikes"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixUserLikes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"True if this mixtape is liked by logged in user, false otherwise"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixUserLikes"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedArtistModel":{"url":"\/documentation\/socialradio\/tunedartistmodel","navigatorTitle":[{"text":"TunedArtistModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","type":"topic","kind":"symbol","title":"TunedArtistModel","abstract":[{"text":"TunedArtistModel models an artist.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedArtistModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/title":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"The title of this mixtape","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"title","kind":"identifier"}],"title":"title","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/title","url":"\/documentation\/socialradio\/socialradiomixtape\/title","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/mixLive":{"title":"mixLive","abstract":[{"text":"true if this mixtape is live, false otherwise","type":"text"}],"url":"\/documentation\/socialradio\/socialradiomixtape\/mixlive","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixLive","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixLive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"mixLive","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/containsExplicitTracks":{"url":"\/documentation\/socialradio\/socialradiomixtape\/containsexplicittracks","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsExplicitTracks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/containsExplicitTracks","title":"containsExplicitTracks","abstract":[{"text":"true if there is at least one explicit track, false otherwise","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"containsExplicitTracks"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/mixId":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"mixId","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixId","url":"\/documentation\/socialradio\/socialradiomixtape\/mixid","abstract":[{"text":"The identifier for the mixtape","type":"text"}],"kind":"symbol","title":"mixId"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCommentTag":{"abstract":[{"type":"text","text":"SocialRadioCommentTag models a user tag in a comment"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","title":"SocialRadioCommentTag","url":"\/documentation\/socialradio\/socialradiocommenttag","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioCommentTag"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeLite":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","abstract":[{"type":"text","text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeLite"}],"url":"\/documentation\/socialradio\/socialradiomixtapelite","role":"symbol","title":"SocialRadioMixtapeLite","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/init":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiomixtape\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/init"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse":{"title":"TunedAuthenticationResponse","role":"symbol","navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"url":"\/documentation\/socialradio\/tunedauthenticationresponse","kind":"symbol","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAuthenticationResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioGenericList":{"abstract":[{"type":"text","text":"SocialRadioGenericList models a list of things"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioGenericList"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","kind":"symbol","url":"\/documentation\/socialradio\/socialradiogenericlist","title":"SocialRadioGenericList","navigatorTitle":[{"kind":"identifier","text":"SocialRadioGenericList"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/init(from:)":{"kind":"symbol","abstract":[],"title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/socialradio\/socialradiomixtape\/init(from:)","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/init(from:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/recommendedDate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recommendedDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"recommendedDate","kind":"identifier"}],"kind":"symbol","title":"recommendedDate","url":"\/documentation\/socialradio\/socialradiomixtape\/recommendeddate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/recommendedDate","type":"topic","abstract":[{"type":"text","text":"The last time this mixtape was recommended"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","type":"topic","url":"\/documentation\/socialradio\/socialradiouser","abstract":[{"type":"text","text":"SocialRadioUser models a user"}],"title":"SocialRadioUser","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUser"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUser"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/mixPlus":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixPlus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/socialradio\/socialradiomixtape\/mixplus","role":"symbol","title":"mixPlus","navigatorTitle":[{"kind":"identifier","text":"mixPlus"}],"type":"topic","abstract":[{"type":"text","text":"true if this mixtape was created using the studio, false otherwise"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment":{"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioComment models a comment"}],"title":"SocialRadioComment","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioComment"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioComment"}],"url":"\/documentation\/socialradio\/socialradiocomment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SocialRadioMixtape","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/author","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/containsExplicitTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/created","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/deleted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/minEngineVersion","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixIsDraft","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixLength","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixLive","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixPlus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixRecipeHash","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/mixUserLikes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/recommendedDate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/status","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/tags","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/title","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/tracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/updated","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/waveform"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/init"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"anchor":"Data-models","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse"],"generated":true,"title":"Data models"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtape","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1tags\/title","value":"tags","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1tags\/fragments","value":[{"text":"tags","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1minEngineVersion\/title","value":"minEngineVersion","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1minEngineVersion\/fragments","value":[{"kind":"identifier","text":"minEngineVersion"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title","value":"TunedTrackModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments","value":[{"text":"TunedTrackModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle","value":[{"kind":"identifier","text":"TunedTrackModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/title","value":"SocialRadioMixtapeTrackImage","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/navigatorTitle","value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/title","value":"SocialRadioList","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/fragments","value":[{"text":"SocialRadioList","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/navigatorTitle","value":[{"text":"SocialRadioList","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/title","value":"SocialRadioMixtape","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/navigatorTitle","value":[{"text":"SocialRadioMixtape","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title","value":"SocialRadioStatusVariable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/title","value":"SocialRadioStatus","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/title","value":"TunedPluginMetadataModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/fragments","value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/navigatorTitle","value":[{"kind":"identifier","text":"TunedPluginMetadataModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixRecipeHash\/title","value":"mixRecipeHash","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixRecipeHash\/fragments","value":[{"text":"mixRecipeHash","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1updated\/title","value":"updated","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1updated\/fragments","value":[{"kind":"identifier","text":"updated"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/title","value":"SocialRadioMixtapeTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/fragments","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixLength\/title","value":"mixLength","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixLength\/fragments","value":[{"kind":"identifier","text":"mixLength"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1waveform\/title","value":"waveform","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1waveform\/fragments","value":[{"text":"waveform","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixIsDraft\/title","value":"mixIsDraft","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixIsDraft\/fragments","value":[{"text":"mixIsDraft","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1author\/title","value":"author","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1author\/fragments","value":[{"kind":"identifier","text":"author"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/title","value":"SocialRadioPlaybackMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/fragments","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/navigatorTitle","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1deleted\/title","value":"deleted","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1deleted\/fragments","value":[{"kind":"identifier","text":"deleted"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1status\/title","value":"status","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1status\/fragments","value":[{"text":"status","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1tracks\/title","value":"tracks","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1tracks\/fragments","value":[{"text":"tracks","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/title","value":"SocialRadioCredentials","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/fragments","value":[{"text":"SocialRadioCredentials","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/navigatorTitle","value":[{"text":"SocialRadioCredentials","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/title","value":"SocialRadioWaveformBlob","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/fragments","value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1created\/title","value":"created","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1created\/fragments","value":[{"kind":"identifier","text":"created"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixUserLikes\/title","value":"mixUserLikes","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixUserLikes\/fragments","value":[{"text":"mixUserLikes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/title","value":"TunedArtistModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/fragments","value":[{"text":"TunedArtistModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/navigatorTitle","value":[{"kind":"identifier","text":"TunedArtistModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1title\/title","value":"title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1title\/fragments","value":[{"text":"title","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixLive\/title","value":"mixLive","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixLive\/fragments","value":[{"kind":"identifier","text":"mixLive"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1containsExplicitTracks\/title","value":"containsExplicitTracks","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1containsExplicitTracks\/fragments","value":[{"text":"containsExplicitTracks","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixId\/title","value":"mixId","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixId\/fragments","value":[{"text":"mixId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/title","value":"SocialRadioCommentTag","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/fragments","value":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/title","value":"SocialRadioMixtapeLite","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/fragments","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/navigatorTitle","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/title","value":"TunedAuthenticationResponse","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/fragments","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/navigatorTitle","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1recommendedDate\/title","value":"recommendedDate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1recommendedDate\/fragments","value":[{"text":"recommendedDate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/title","value":"SocialRadioUser","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/fragments","value":[{"kind":"identifier","text":"SocialRadioUser"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUser"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixPlus\/title","value":"mixPlus","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1mixPlus\/fragments","value":[{"kind":"identifier","text":"mixPlus"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/title","value":"SocialRadioComment","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/fragments","value":[{"text":"SocialRadioComment","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioComment"}],"op":"replace"}]}]}