{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig\/equaliserConfig"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"]]},"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig(py)equaliserConfig","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"equaliserConfig","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQEqualiserConfig","text":"AutomixIQEqualiserConfig","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"equaliserConfig","kind":"identifier"}],"title":"equaliserConfig","role":"symbol","modules":[{"name":"AutomixIQ"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"equaliserConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQEqualiserConfig","text":"AutomixIQEqualiserConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQEqualiserConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqconfig\/equaliserconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqconfig\/equaliserconfig"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQEqualiserConfig":{"abstract":[],"type":"topic","url":"\/documentation\/automixiq\/automixiqequaliserconfig","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQEqualiserConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQEqualiserConfig","navigatorTitle":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}],"title":"AutomixIQEqualiserConfig"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig/equaliserConfig":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"equaliserConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQEqualiserConfig","text":"AutomixIQEqualiserConfig"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig\/equaliserConfig","url":"\/documentation\/automixiq\/automixiqconfig\/equaliserconfig","title":"equaliserConfig","navigatorTitle":[{"kind":"identifier","text":"equaliserConfig"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQConfig","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"AutomixIQConfig","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"AutomixIQConfig","url":"\/documentation\/automixiq\/automixiqconfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"equaliserConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"equaliserConfig","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQEqualiserConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQEqualiserConfig","kind":"typeIdentifier","text":"AutomixIQEqualiserConfig"},{"kind":"text","text":" * "},{"kind":"identifier","text":"equaliserConfig"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQEqualiserConfig\/title","value":"AutomixIQEqualiserConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQEqualiserConfig\/fragments","value":[{"kind":"identifier","text":"AutomixIQEqualiserConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQEqualiserConfig\/navigatorTitle","value":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig~1equaliserConfig\/title","value":"equaliserConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig~1equaliserConfig\/fragments","value":[{"text":"equaliserConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title","value":"AutomixIQConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments","value":[{"kind":"identifier","text":"AutomixIQConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle","value":[{"text":"AutomixIQConfig","kind":"identifier"}]}]}]}