{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/moveTrackOutOfBounds"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errorcode\/movetrackoutofbounds"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/errorcode\/movetrackoutofbounds"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveTrackOutOfBounds"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"sections":[],"metadata":{"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeMoveTrackOutOfBounds"}],"externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeMoveTrackOutOfBounds","symbolKind":"case","title":"ErrorCode.moveTrackOutOfBounds","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveTrackOutOfBounds"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/moveTrackOutOfBounds":{"title":"ErrorCode.moveTrackOutOfBounds","url":"\/documentation\/socialradio\/errorcode\/movetrackoutofbounds","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/moveTrackOutOfBounds","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveTrackOutOfBounds"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeMoveTrackOutOfBounds"}],"abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"abstract":[],"role":"symbol","title":"ErrorCode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCodeMoveTrackOutOfBounds"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeMoveTrackOutOfBounds"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodeMoveTrackOutOfBounds"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1moveTrackOutOfBounds\/title","op":"replace","value":"ErrorCodeMoveTrackOutOfBounds"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1moveTrackOutOfBounds\/fragments","op":"replace","value":[{"text":"ErrorCodeMoveTrackOutOfBounds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]}]}]}