{"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekNoTrackAvailable"}],"symbolKind":"case","navigatorTitle":[{"text":"ErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"roleHeading":"Case","title":"ErrorCode.seekNoTrackAvailable","externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeSeekNoTrackAvailable","modules":[{"name":"SocialRadio"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/seekNoTrackAvailable","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errorcode\/seeknotrackavailable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/errorcode\/seeknotrackavailable"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekNoTrackAvailable"}]}]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/seekNoTrackAvailable":{"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/errorcode\/seeknotrackavailable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/seekNoTrackAvailable","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekNoTrackAvailable"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSeekNoTrackAvailable"}],"title":"ErrorCode.seekNoTrackAvailable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"abstract":[],"role":"symbol","title":"ErrorCode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ErrorCodeSeekNoTrackAvailable","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ErrorCodeSeekNoTrackAvailable"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1seekNoTrackAvailable\/title","value":"ErrorCodeSeekNoTrackAvailable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1seekNoTrackAvailable\/fragments","value":[{"text":"ErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"}]}]}