{"variants":[{"paths":["\/documentation\/socialradio\/automixiqconfig\/init(apikey:country:storeid:applicationid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqconfig\/init(apikey:country:storeid:applicationid:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"storeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig\/init(apiKey:country:storeId:applicationId:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"country"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storeId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(apiKey:country:storeId:applicationId:)","externalID":"c:@M@SocialRadio@objc(cs)AutomixIQConfig(im)initWithApiKey:country:storeId:applicationId:","roleHeading":"Initializer","modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithApiKey:country:storeId:applicationId:"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig/init(apiKey:country:storeId:applicationId:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/socialradio\/automixiqconfig\/init(apikey:country:storeid:applicationid:)","title":"init(apiKey:country:storeId:applicationId:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig\/init(apiKey:country:storeId:applicationId:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithApiKey:country:storeId:applicationId:","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig":{"abstract":[],"url":"\/documentation\/socialradio\/automixiqconfig","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQConfig"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","role":"symbol","title":"AutomixIQConfig","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithApiKey:country:storeId:applicationId:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithApiKey:country:storeId:applicationId:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithApiKey:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"apiKey","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"country:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"country","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"storeId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"storeId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"applicationId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"applicationId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"initWithApiKey:country:storeId:applicationId:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig~1init(apiKey:country:storeId:applicationId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithApiKey:country:storeId:applicationId:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig~1init(apiKey:country:storeId:applicationId:)\/fragments"},{"value":"AutomixIQConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/title"},{"value":[{"text":"AutomixIQConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}