{"metadata":{"symbolKind":"method","modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Method","externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(im)placeholderWaveformDataForTrackWithIdentifier:","navigatorTitle":[{"text":"placeholderWaveformDataForTrackWithIdentifier:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderWaveformDataForTrack","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKWaveformModel"},{"kind":"text","text":"?"}],"role":"symbol","title":"placeholderWaveformDataForTrack(identifier:)"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderWaveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel","text":"AutomixSDKWaveformModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKWaveformModel"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of a track"}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"returns the waveform data"}]}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdk\/placeholderwaveformdatafortrack(identifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdk\/placeholderwaveformdatafortrack(identifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Gets the placeholder waveform data for a track."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/placeholderWaveformDataForTrack(identifier:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"url":"\/documentation\/automixiq\/automixsdk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"kind":"symbol","type":"topic","title":"AutomixSDK","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/placeholderWaveformDataForTrack(identifier:)":{"abstract":[{"text":"Gets the placeholder waveform data for a track.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/placeholderWaveformDataForTrack(identifier:)","navigatorTitle":[{"text":"placeholderWaveformDataForTrackWithIdentifier:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderWaveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKWaveformModel","kind":"typeIdentifier","text":"AutomixSDKWaveformModel"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","title":"placeholderWaveformDataForTrack(identifier:)","url":"\/documentation\/automixiq\/automixsdk\/placeholderwaveformdatafortrack(identifier:)","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKWaveformModel":{"url":"\/documentation\/automixiq\/automixsdkwaveformmodel","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"title":"AutomixSDKWaveformModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"placeholderWaveformDataForTrackWithIdentifier:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"placeholderWaveformDataForTrackWithIdentifier:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKWaveformModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel","text":"AutomixSDKWaveformModel"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"placeholderWaveformDataForTrackWithIdentifier:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"text":"The identifier of a track","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title","value":"AutomixSDK","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments","value":[{"text":"AutomixSDK","kind":"identifier"}]},{"op":"replace","value":[{"text":"AutomixSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1placeholderWaveformDataForTrack(identifier:)\/title","value":"placeholderWaveformDataForTrackWithIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1placeholderWaveformDataForTrack(identifier:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"placeholderWaveformDataForTrackWithIdentifier:","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/title"},{"value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}