{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackInternalError","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeAddTrackInternalError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackInternalError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeAddTrackInternalError"}],"role":"symbol","title":"ErrorCode.addTrackInternalError","roleHeading":"Case","modules":[{"name":"SocialRadio"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackInternalError","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errorcode\/addtrackinternalerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/errorcode\/addtrackinternalerror"]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/addTrackInternalError":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackInternalError"}],"url":"\/documentation\/socialradio\/errorcode\/addtrackinternalerror","title":"ErrorCode.addTrackInternalError","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackInternalError","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeAddTrackInternalError"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","type":"topic","url":"\/documentation\/socialradio","kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/socialradio\/errorcode","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ErrorCodeAddTrackInternalError","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ErrorCodeAddTrackInternalError","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ErrorCodeAddTrackInternalError","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeAddTrackInternalError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackInternalError\/title"},{"value":[{"text":"ErrorCodeAddTrackInternalError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackInternalError\/fragments"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle"}]}]}