{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveCreation"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/socialradio\/socialradioplaybackmode\/livecreation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradioplaybackmode\/livecreation"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/liveCreation"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode"]]},"metadata":{"roleHeading":"Case","title":"SocialRadioPlaybackMode.liveCreation","externalID":"c:@M@SocialRadio@E@SocialRadioPlaybackMode@SocialRadioPlaybackModeLiveCreation","symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioPlaybackModeLiveCreation"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveCreation","kind":"identifier"}],"modules":[{"name":"SocialRadio"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode":{"title":"SocialRadioPlaybackMode","type":"topic","url":"\/documentation\/socialradio\/socialradioplaybackmode","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","abstract":[{"type":"text","text":"SocialRadio playback mode"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioPlaybackMode"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode/liveCreation":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveCreation"}],"title":"SocialRadioPlaybackMode.liveCreation","type":"topic","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode\/liveCreation","navigatorTitle":[{"kind":"identifier","text":"SocialRadioPlaybackModeLiveCreation"}],"url":"\/documentation\/socialradio\/socialradioplaybackmode\/livecreation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SocialRadioPlaybackModeLiveCreation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioPlaybackModeLiveCreation"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SocialRadioPlaybackModeLiveCreation","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/title","op":"replace","value":"SocialRadioPlaybackMode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode~1liveCreation\/title","op":"replace","value":"SocialRadioPlaybackModeLiveCreation"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode~1liveCreation\/fragments","op":"replace","value":[{"text":"SocialRadioPlaybackModeLiveCreation","kind":"identifier"}]}]}]}