{"abstract":[{"text":"true if the track is explicit, false otherwise","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel\/IsExplicit-53fcn"},"metadata":{"roleHeading":"Instance Property","title":"IsExplicit","externalID":"s:11SocialRadio19AutomixIQTrackModelC10IsExplicitSbSgvp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"IsExplicit","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?","kind":"text"}],"symbolKind":"property","role":"symbol","modules":[{"name":"SocialRadio"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/socialradio\/automixiqtrackmodel\/isexplicit-53fcn"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsExplicit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}]}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTrackModel":{"url":"\/documentation\/socialradio\/automixiqtrackmodel","kind":"symbol","type":"topic","role":"symbol","title":"AutomixIQTrackModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel","abstract":[{"type":"text","text":"AutomixIQTrackModel models a track. This metadata is required."}],"navigatorTitle":[{"text":"AutomixIQTrackModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQTrackModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTrackModel/IsExplicit-53fcn":{"type":"topic","kind":"symbol","abstract":[{"text":"true if the track is explicit, false otherwise","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/automixiqtrackmodel\/isexplicit-53fcn","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel\/IsExplicit-53fcn","title":"IsExplicit","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsExplicit","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AutomixIQTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/fragments","op":"replace","value":[{"text":"AutomixIQTrackModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQTrackModel"}]}]}]}