{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/socialradio\/automixiqtrackmodel\/tracknumber-2exa5"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqtrackmodel\/tracknumber-2exa5"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"trackNumber","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"trackNumber","externalID":"c:@M@SocialRadio@objc(cs)AutomixIQTrackModel(py)trackNumber","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel\/trackNumber-2exa5","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Objective-C accessible member for the track number"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTrackModel":{"url":"\/documentation\/socialradio\/automixiqtrackmodel","kind":"symbol","type":"topic","role":"symbol","title":"AutomixIQTrackModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel","abstract":[{"type":"text","text":"AutomixIQTrackModel models a track. This metadata is required."}],"navigatorTitle":[{"text":"AutomixIQTrackModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQTrackModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTrackModel/trackNumber-2exa5":{"title":"trackNumber","navigatorTitle":[{"text":"trackNumber","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel\/trackNumber-2exa5","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixiqtrackmodel\/tracknumber-2exa5","abstract":[{"text":"Objective-C accessible member for the track number","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackNumber"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"trackNumber","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"trackNumber","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"trackNumber","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"AutomixIQTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/title"},{"value":[{"text":"AutomixIQTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/fragments"},{"value":[{"text":"AutomixIQTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/navigatorTitle"},{"value":"trackNumber","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel~1trackNumber-2exa5\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel~1trackNumber-2exa5\/fragments","value":[{"text":"trackNumber","kind":"identifier"}],"op":"replace"}]}]}