{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType"]]},"sections":[],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"SocialRadio"}],"role":"collectionGroup"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/Equatable-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqplaybackeventtype\/equatable-implementations"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/!=(_:_:)":{"abstract":[],"url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/!=(_:_:)","role":"symbol","title":"!=(_:_:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType":{"abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"url":"\/documentation\/socialradio\/automixiqplaybackeventtype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType","role":"symbol","title":"AutomixIQPlaybackEventType","type":"topic"}},"variantOverrides":[{"patch":[{"value":"AutomixIQPlaybackEventType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/title"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/fragments"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}