{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate\/loggedInUser()"},"metadata":{"navigatorTitle":[{"text":"loggedInUser","kind":"identifier"}],"required":true,"title":"loggedInUser()","roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(pl)SocialBackendDelegate(im)loggedInUser","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loggedInUser","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SocialRadioUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser"},{"text":"?","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loggedInUser","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SocialRadioUser","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialbackenddelegate\/loggedinuser()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialbackenddelegate\/loggedinuser()"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser":{"title":"SocialRadioUser","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUser","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioUser models a user"}],"navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiouser","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialBackendDelegate/loggedInUser()":{"navigatorTitle":[{"kind":"identifier","text":"loggedInUser"}],"abstract":[],"kind":"symbol","url":"\/documentation\/socialradio\/socialbackenddelegate\/loggedinuser()","title":"loggedInUser()","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate\/loggedInUser()","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loggedInUser"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"SocialRadioUser","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser"},{"kind":"text","text":"?"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialBackendDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialBackendDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","role":"symbol","title":"SocialBackendDelegate","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/socialbackenddelegate","navigatorTitle":[{"kind":"identifier","text":"SocialBackendDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"loggedInUser","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loggedInUser"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"SocialRadioUser","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUser"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"loggedInUser"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/title","value":"SocialRadioUser","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/fragments","value":[{"kind":"identifier","text":"SocialRadioUser"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUser"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate~1loggedInUser()\/title","value":"loggedInUser","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate~1loggedInUser()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loggedInUser"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/title","value":"SocialBackendDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/fragments","value":[{"kind":"identifier","text":"SocialBackendDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/navigatorTitle","value":[{"text":"SocialBackendDelegate","kind":"identifier"}],"op":"replace"}]}]}