{"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@SocialRadio@E@AutomixSDKLogLevel@AutomixSDKLogLevelLogLevelWarning","title":"AutomixSDKLogLevel.logLevelWarning","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"logLevelWarning","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelWarning"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelWarning"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"logLevelWarning","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkloglevel\/loglevelwarning"]},{"paths":["\/documentation\/socialradio\/automixsdkloglevel\/loglevelwarning"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel":{"kind":"symbol","title":"AutomixSDKLogLevel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevel"}],"abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"url":"\/documentation\/socialradio\/automixsdkloglevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKLogLevel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/logLevelWarning":{"url":"\/documentation\/socialradio\/automixsdkloglevel\/loglevelwarning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelWarning","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelWarning","kind":"identifier"}],"title":"AutomixSDKLogLevel.logLevelWarning","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelWarning","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"AutomixSDKLogLevelLogLevelWarning","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AutomixSDKLogLevelLogLevelWarning","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"AutomixSDKLogLevelLogLevelWarning","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/title","op":"replace","value":"AutomixSDKLogLevel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelWarning\/title","value":"AutomixSDKLogLevelLogLevelWarning"},{"value":[{"text":"AutomixSDKLogLevelLogLevelWarning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelWarning\/fragments"}]}]}