{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelError"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"]]},"metadata":{"roleHeading":"Case","role":"symbol","title":"AutomixSDKLogLevel.logLevelError","symbolKind":"case","externalID":"c:@M@SocialRadio@E@AutomixSDKLogLevel@AutomixSDKLogLevelLogLevelError","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelError","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelError","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkloglevel\/loglevelerror"]},{"paths":["\/documentation\/socialradio\/automixsdkloglevel\/loglevelerror"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelError","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel":{"kind":"symbol","title":"AutomixSDKLogLevel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevel"}],"abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"url":"\/documentation\/socialradio\/automixsdkloglevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKLogLevel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/logLevelError":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelError","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"AutomixSDKLogLevel.logLevelError","navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelError","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/automixsdkloglevel\/loglevelerror","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKLogLevelLogLevelError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"AutomixSDKLogLevelLogLevelError","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelError"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/fragments","op":"replace","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},{"value":"AutomixSDKLogLevelLogLevelError","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelError\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelError\/fragments","op":"replace","value":[{"text":"AutomixSDKLogLevelLogLevelError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}