{"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel(im)init","title":"init","modules":[{"name":"SocialRadio"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"paths":["\/documentation\/socialradio\/automixiqwaveformmodel\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel/init":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/init","role":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqwaveformmodel\/init","kind":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"url":"\/documentation\/socialradio","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","role":"symbol","title":"AutomixIQWaveformModel","navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/automixiqwaveformmodel","abstract":[{"type":"text","text":"AutomixIQWaveformModel models the waveform of a track."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQWaveformModel"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","value":"AutomixIQWaveformModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}