{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate\/waveformDataAvailable(identifier:)"},"variants":[{"paths":["\/documentation\/automixiq\/automixiqstatusobserverdelegate\/waveformdataavailable(identifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqstatusobserverdelegate\/waveformdataavailable(identifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"]]},"abstract":[{"type":"text","text":"Called when waveform data for a track is available"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate(im)waveformDataAvailableWithIdentifier:","navigatorTitle":[{"text":"waveformDataAvailableWithIdentifier:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"AutomixIQ"}],"title":"waveformDataAvailable(identifier:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waveformDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The identifier of the track","type":"text"}]}],"name":"identifier"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","title":"AutomixIQStatusObserverDelegate","role":"symbol","type":"topic","abstract":[{"text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"navigatorTitle":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate/waveformDataAvailable(identifier:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"waveformDataAvailableWithIdentifier:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waveformDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate\/waveformdataavailable(identifier:)","abstract":[{"text":"Called when waveform data for a track is available","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate\/waveformDataAvailable(identifier:)","title":"waveformDataAvailable(identifier:)","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"waveformDataAvailableWithIdentifier:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"waveformDataAvailableWithIdentifier:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"waveformDataAvailableWithIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The identifier of the track","type":"text"}],"type":"paragraph"}],"name":"identifier"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title","value":"AutomixIQStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate~1waveformDataAvailable(identifier:)\/title","value":"waveformDataAvailableWithIdentifier:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate~1waveformDataAvailable(identifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"waveformDataAvailableWithIdentifier:","kind":"identifier"}]}]}]}