{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"waveformDataForTrack(withIdentifier:applyTransitions:)","symbolKind":"method","modules":[{"name":"SocialRadio"}],"externalID":"c:objc(cs)AutomixSDKObjC(im)waveformDataForTrackWithIdentifier:applyTransitions:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"applyTransitions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"text":"AutomixSDKWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformModel"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifier","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyTransitions"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","text":"AutomixSDKWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformModel","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkobjc\/waveformdatafortrack(withidentifier:applytransitions:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC\/waveformDataForTrack(withIdentifier:applyTransitions:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel":{"url":"\/documentation\/socialradio\/automixsdkwaveformmodel","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"kind":"symbol","type":"topic","title":"AutomixSDKWaveformModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKObjC":{"title":"AutomixSDKObjC","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKObjC"}],"url":"\/documentation\/socialradio\/automixsdkobjc","role":"symbol","navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKObjC/waveformDataForTrack(withIdentifier:applyTransitions:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"waveformDataForTrack"},{"kind":"text","text":"("},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"applyTransitions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"AutomixSDKWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformModel"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC\/waveformDataForTrack(withIdentifier:applyTransitions:)","abstract":[],"title":"waveformDataForTrack(withIdentifier:applyTransitions:)","url":"\/documentation\/socialradio\/automixsdkobjc\/waveformdatafortrack(withidentifier:applytransitions:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AutomixSDKWaveformModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}]}]}]}