{"metadata":{"symbolKind":"method","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioFollowCounters(im)init","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiofollowcounters\/init"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters\/init","interfaceLanguage":"occ"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFollowCounters":{"kind":"symbol","abstract":[{"text":"SocialRadioUser models the user and its follower’s counters","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioFollowCounters"}],"title":"SocialRadioFollowCounters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioFollowCounters"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters","url":"\/documentation\/socialradio\/socialradiofollowcounters"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFollowCounters/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/socialradio\/socialradiofollowcounters\/init","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters\/init","abstract":[],"title":"init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"SocialRadioFollowCounters","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters\/title"},{"value":[{"kind":"identifier","text":"SocialRadioFollowCounters"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioFollowCounters"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}