{"variants":[{"paths":["\/documentation\/socialradio\/socialradiofollowcounters\/source"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiofollowcounters\/source"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters\/source","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SocialRadio"}],"title":"source","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialRadioUserCounters","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUserCounters","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioFollowCounters(py)source","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"source","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"The user ’s counters"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialRadioUserCounters","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUserCounters"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFollowCounters":{"kind":"symbol","abstract":[{"text":"SocialRadioUser models the user and its follower’s counters","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioFollowCounters"}],"title":"SocialRadioFollowCounters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioFollowCounters"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters","url":"\/documentation\/socialradio\/socialradiofollowcounters"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFollowCounters/source":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUserCounters","text":"SocialRadioUserCounters"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiofollowcounters\/source","kind":"symbol","abstract":[{"type":"text","text":"The user ’s counters"}],"title":"source","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters\/source","navigatorTitle":[{"kind":"identifier","text":"source"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUserCounters":{"title":"SocialRadioUserCounters","role":"symbol","url":"\/documentation\/socialradio\/socialradiousercounters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUserCounters"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioUserCounters models a user’s counters"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUserCounters"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"source","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"source"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUserCounters","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters","text":"SocialRadioUserCounters","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"source","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters\/title","value":"SocialRadioFollowCounters","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters\/fragments","value":[{"text":"SocialRadioFollowCounters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters\/navigatorTitle","value":[{"text":"SocialRadioFollowCounters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters~1source\/title","value":"source","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters~1source\/fragments","value":[{"kind":"identifier","text":"source"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/title","value":"SocialRadioUserCounters","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/fragments","value":[{"text":"SocialRadioUserCounters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUserCounters"}],"op":"replace"}]}]}