{"sections":[],"abstract":[{"text":"The user’s folowers’ counters","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targets"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SocialRadioUserCounters","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUserCounters","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters"},{"kind":"text","text":"]?"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioFollowCounters(py)targets","symbolKind":"property","roleHeading":"Instance Property","title":"targets","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"targets","kind":"identifier"},{"text":": [","kind":"text"},{"text":"SocialRadioUserCounters","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUserCounters"},{"text":"]?","kind":"text"}],"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"targets","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/socialradio\/socialradiofollowcounters\/targets"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiofollowcounters\/targets"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters\/targets","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFollowCounters/targets":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiofollowcounters\/targets","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters\/targets","type":"topic","abstract":[{"text":"The user’s folowers’ counters","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targets"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SocialRadioUserCounters","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioUserCounters"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"targets"}],"title":"targets"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUserCounters":{"title":"SocialRadioUserCounters","role":"symbol","url":"\/documentation\/socialradio\/socialradiousercounters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUserCounters"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioUserCounters models a user’s counters"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUserCounters"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFollowCounters":{"kind":"symbol","abstract":[{"text":"SocialRadioUser models the user and its follower’s counters","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioFollowCounters"}],"title":"SocialRadioFollowCounters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioFollowCounters"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFollowCounters","url":"\/documentation\/socialradio\/socialradiofollowcounters"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"targets","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"targets","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SocialRadioUserCounters *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"targets"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"targets","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters~1targets\/title","op":"replace"},{"value":[{"text":"targets","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters~1targets\/fragments","op":"replace"},{"value":"SocialRadioUserCounters","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioUserCounters"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioUserCounters"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/navigatorTitle","op":"replace"},{"value":"SocialRadioFollowCounters","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters\/title","op":"replace"},{"value":[{"text":"SocialRadioFollowCounters","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters\/fragments","op":"replace"},{"value":[{"text":"SocialRadioFollowCounters","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFollowCounters\/navigatorTitle","op":"replace"}]}]}