{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonBorder"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioUIConfig(py)dialogSecondaryButtonBorder","symbolKind":"property","role":"symbol","modules":[{"name":"SocialRadio"}],"title":"dialogSecondaryButtonBorder","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonBorder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/dialogSecondaryButtonBorder"},"variants":[{"paths":["\/documentation\/socialradio\/socialradiouiconfig\/dialogsecondarybuttonborder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiouiconfig\/dialogsecondarybuttonborder"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig":{"abstract":[{"type":"text","text":"Social Radio UI options"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}],"title":"SocialRadioUIConfig","role":"symbol","navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiouiconfig","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","role":"collection","type":"topic","title":"SocialRadio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig/dialogSecondaryButtonBorder":{"type":"topic","title":"dialogSecondaryButtonBorder","navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonBorder"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonBorder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/dialogSecondaryButtonBorder","url":"\/documentation\/socialradio\/socialradiouiconfig\/dialogsecondarybuttonborder","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"dialogSecondaryButtonBorder","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"dialogSecondaryButtonBorder","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/title","value":"SocialRadioUIConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/fragments","value":[{"text":"SocialRadioUIConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1dialogSecondaryButtonBorder\/title","value":"dialogSecondaryButtonBorder","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1dialogSecondaryButtonBorder\/fragments","value":[{"text":"dialogSecondaryButtonBorder","kind":"identifier"}]}]}]}