{"metadata":{"title":"TunedAutomixPlaybackMode.automix","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automix","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"TunedAutomixPlaybackModeAutomix","kind":"identifier"}],"role":"symbol","externalID":"c:@M@SocialRadio@E@TunedAutomixPlaybackMode@TunedAutomixPlaybackModeAutomix","modules":[{"name":"SocialRadio"}],"roleHeading":"Case"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automix"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode\/automix","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedautomixplaybackmode\/automix"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/tunedautomixplaybackmode\/automix"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode":{"abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"title":"TunedAutomixPlaybackMode","kind":"symbol","url":"\/documentation\/socialradio\/tunedautomixplaybackmode","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"navigatorTitle":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode/automix":{"title":"TunedAutomixPlaybackMode.automix","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedAutomixPlaybackModeAutomix"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automix"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode\/automix","abstract":[],"url":"\/documentation\/socialradio\/tunedautomixplaybackmode\/automix","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"TunedAutomixPlaybackModeAutomix","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"TunedAutomixPlaybackModeAutomix"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"TunedAutomixPlaybackModeAutomix","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TunedAutomixPlaybackMode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/title"},{"value":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/fragments"},{"value":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/navigatorTitle"},{"value":"TunedAutomixPlaybackModeAutomix","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode~1automix\/title"},{"value":[{"kind":"identifier","text":"TunedAutomixPlaybackModeAutomix"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode~1automix\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}