{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"logLevel"},{"text":": ","kind":"text"},{"text":"TunedLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","preciseIdentifier":"c:@M@SocialRadio@E@TunedLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The log level."}],"type":"paragraph"}],"name":"logLevel"},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"text":"The message it wishes to log.","type":"text"}]}]}]}],"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"variants":[{"paths":["\/documentation\/socialradio\/tunedrestdelegate\/logautomixiqmessage(loglevel:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/tunedrestdelegate\/logautomixiqmessage(loglevel:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logAutomixIQMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@E@TunedLogLevel","kind":"typeIdentifier","text":"TunedLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"externalID":"c:@M@SocialRadio@objc(pl)TunedRestDelegate(im)logAutomixIQMessageWithLogLevel:message:","roleHeading":"Instance Method","title":"logAutomixIQMessage(logLevel:message:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate\/logAutomixIQMessage(logLevel:message:)"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"role":"symbol","title":"TunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","kind":"symbol","url":"\/documentation\/socialradio\/tunedrestdelegate","type":"topic","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate/logAutomixIQMessage(logLevel:message:)":{"url":"\/documentation\/socialradio\/tunedrestdelegate\/logautomixiqmessage(loglevel:message:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"title":"logAutomixIQMessage(logLevel:message:)","navigatorTitle":[{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logAutomixIQMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"logLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@TunedLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedLogLevel","kind":"identifier"}],"role":"symbol","title":"TunedLogLevel","navigatorTitle":[{"text":"TunedLogLevel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","abstract":[{"text":"TunedLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio\/tunedloglevel","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"logAutomixIQMessageWithLogLevel:message:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"logAutomixIQMessageWithLogLevel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@TunedLogLevel","text":"TunedLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel"},{"text":") ","kind":"text"},{"text":"logLevel","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"message:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"logLevel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The log level."}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message it wishes to log."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","value":"TunedRestDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle","op":"replace"},{"value":"logAutomixIQMessageWithLogLevel:message:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/title","op":"replace","value":"TunedLogLevel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/fragments","op":"replace","value":[{"text":"TunedLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedLogLevel"}]}]}]}