{"topicSections":[{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/!=(_:_:)"],"generated":true}],"metadata":{"role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"AutomixIQ"}],"roleHeading":"API Collection"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/!=(_:_:)":{"role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/!=(_:_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","title":"AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType":{"url":"\/documentation\/automixiq\/automixiqplaybackeventtype","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"title":"AutomixIQPlaybackEventType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"abstract":[{"text":"AutomixIQPlaybackEventType is an enum of all the available playback events","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/title","op":"replace","value":"AutomixIQPlaybackEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/fragments","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}