{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Terminates \/ deinitialises SocialRadio. Call this on applicationWillTerminate, or whenever you no longer need it.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio"]]},"metadata":{"title":"terminate()","role":"symbol","modules":[{"name":"SocialRadioLite"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"terminate"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"terminate"}],"externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadio(im)terminate","symbolKind":"method"},"variants":[{"paths":["\/documentation\/socialradiolite\/socialradio\/terminate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradiolite\/socialradio\/terminate()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/terminate()"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"terminate","kind":"identifier"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio/terminate()":{"abstract":[{"type":"text","text":"Terminates \/ deinitialises SocialRadio. Call this on applicationWillTerminate, or whenever you no longer need it."}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"terminate","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"terminate","kind":"identifier"}],"title":"terminate()","role":"symbol","url":"\/documentation\/socialradiolite\/socialradio\/terminate()","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio\/terminate()"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio","kind":"symbol","title":"SocialRadio","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadio"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadio"}],"type":"topic","url":"\/documentation\/socialradiolite\/socialradio","abstract":[{"type":"text","text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"terminate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"terminate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"terminate","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1terminate()\/title","op":"replace","value":"terminate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio~1terminate()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"terminate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SocialRadio","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio\/fragments","value":[{"text":"SocialRadio","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadio"}]}]}]}