{"seeAlsoSections":[{"anchor":"Initialising-SocialRadio-for-use-with-a-custom-backend","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials"],"title":"Initialising SocialRadio for use with a custom backend","generated":true}],"abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with a custom backend.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-backend-article","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"kind":"article","sections":[],"metadata":{"role":"article","roleHeading":"Article","title":"Initializing SocialRadio with a custom backend","modules":[{"name":"SocialRadio"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/initialising-socialradio-with-custom-backend-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/initialising-socialradio-with-custom-backend-article"]}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Essentials","level":2,"type":"heading","text":"Essentials"},{"inlineContent":[{"type":"text","text":"This document explains how to integrate SocialRadio with your application if it gets its audio data, metadata and social layer from a custom backend."}],"type":"paragraph"},{"anchor":"Initialization-with-custom-backend","level":3,"type":"heading","text":"Initialization with custom backend"},{"inlineContent":[{"text":"In order to initialise SocialRadio against Tuned Global’s API and services you need the following:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Tuned Global Store ID","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tuned Global Application ID"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Device Country Code"}]}]}]},{"syntax":"swift","code":["func application(_ application: UIApplication, ","                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","    \/\/ ...","","    let automixIQStreamingDelegate: AutomixIQStreamingDelegate = myAutomixIQStreamingDelegate","    let socialRadioStreamingDelegate: SocialRadioStreamingDelegate = mySocialRadioStreamingDelegate","    let socialRadioUIDelegate: SocialRadioUIDelegate = mySocialRadioUIDelegate","    let socialRadioStatusObserverDelegate: SocialRadioStatusObserverDelegate = mySocialRadioStatusObserverDelegate","    let socialBackendDelegate: SocialBackendDelegate = mySocialBackendDelegate","    let countryCode: String = myCountryCode \/\/ \"US\" ? \"AU\"?","    let storeId: String = myTunedStoreId","    let applicationId: String = myApplicationId","    let myAPIKey: String = myApplicationKey","","    let config = SocialRadioConfig(apiKey: myAPIKey, country: countryCode, storeId: storeId, applicationId: applicationId)","    SocialRadio.initialise(config: config","                           automixIQStreamingDelegate: automixIQStreamingDelegate,","                           socialRadioStatusDelegate: socialRadioStatusObserverDelegate,","                           socialRadioUIDelegate: socialRadioUIDelegate,","                           socialBackendDelegate: socialBackendDelegate)","    { error in","        if error != nil {","            \/\/ This means you are forbidden to use the Automix SDK or you have no internet connection.","            return","        }","        \/\/ The Automix SDK public functions can be used from this point onwards :)","    }","","    \/\/ ...","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"You can tweak the SocialRadio UI and available feature set by changing flags on the cofing object. See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig"},{"type":"text","text":"."}],"type":"paragraph"},{"anchor":"AutomixIQStreamingDelegate","level":4,"type":"heading","text":"AutomixIQStreamingDelegate"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If your custom backend puts fetching metadata and track data behind a login, SocialRadio needs to know if the user in your application is logged in or not via"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/isLoggedIn()","isActive":true}]}]}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func isLoggedIn() {","        return self.loggedIn","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If your custom backend only allows playback on a device under certain conditions (for instance in only allows one device to play at any given time), SocialRadio needs to know if a device is allowed to play via"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncCheckDeviceStatus(completion:)"}]}]}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func asyncCheckDeviceStatus(completion: @escaping (_ error: Error?, _ canContinuePlaying: Bool) -> Void) {","        self.canDeviceContinuePlaying() { allowedToPlay in","            return allowedToPlay","        }","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"SocialRadio requires devices to have a unique identifier, provided via","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/getDeviceIdentifier()","type":"reference"}],"type":"paragraph"}]}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func getDeviceIdentifier() -> String {","        return self.deviceIdentifier","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"This provides hooks to inject cached track audio data and metadata, preventing SocialRadio from having to request this data from your custom backend if they are already available. This also enables offline playback when all required data is available on the device","type":"text"}]}]}]},{"inlineContent":[{"text":"This is done via ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","isActive":true,"type":"reference"}],"type":"paragraph"},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func syncGetTrackMetadata(trackId: String?) -> TunedTrackModel? {","        \/\/ If I have this track cached, I should be able to tell its metadata","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.metadataForTrack(trackId)","    }","    \/\/ ...","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"and "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","isActive":true}],"type":"paragraph"},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func syncGetCachedTrack(trackId: String) -> Data? {","        \/\/ If I have this track cached, I should be able to decrypt it and send the data","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.unencryptedDataForTrack(trackId)","    }","    \/\/ ...","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"SocialRadio will pass every track metadata model it may have downloaded to the client to provide an opportunity to cache it. If you do not need this, you may leave this function empty."},{"type":"text","text":" "},{"type":"text","text":"``AutomixIQStreamingDelegate\/cacheMetadata(_:)`"}],"type":"paragraph"},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func cacheMetadata(_ metadata: [TunedTrackModel]) -> Data? {","        self.metadataForTrack[metadata.trackId] = metadata","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"SocialRadio will download track metadata as it needs it. When required, it will do so via"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)"}],"type":"paragraph"}]}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func asyncGetTrackMetadata(trackId: String, completion: @escaping (_ error: Error?, _ track: TunedTrackModel?) -> Void) {","        self.getTrackMetadata(trackId: trackId) { error, trackMetadata in","            let automixIQTrackModel = translateMetadata(trackMetadata)","            return completion(error, automixIQTrackModel)","        }","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"When SocialRadio needs to download a track, it will ask for the url for it. It supports session IDs if you want urls to expire and return 403s. It will do so via"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","type":"reference","isActive":true}],"type":"paragraph"}]}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func asyncGetStream(streamingDeviceId: String, sessionId: String, trackId: String, completion: @escaping (_ error: Error?, _ url: String?, _ newSessionId: String?, _ reportingURLS: Beacons?) -> Void) {","        self.getTrackURL(deviceId: streamingDeviceId, sessionId: sessionId, trackId: trackId) { error, url in ","            return completion(error, url)","        }","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"When a track finishes downloading, SocialRadio will pass the audio data for you to cache if required. This is done via","type":"text"},{"text":" ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadCompleted(trackId:data:)","type":"reference","isActive":true}]}]}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func trackDownloadCompleted(trackId: String, data: NSData) {","        self.cacheTrack(trackId: trackId, data: data)","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"As a track is being downloaded, SocialRadio will report download progress via"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)"}]}]}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func trackDownloadProgressChanged(trackId: String, progress: Swift.Float) {","        self.updateTrackDownloadProgress(trackId: trackId, progress: progress)","    }","    \/\/ ...","}"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"Do keep in mind this download is done lazily, as SocialRadio requires data for analysis \/ playback. There is no guarantee a track will download in its entirety if the track is not played in its entirety."}],"type":"paragraph"},{"anchor":"SocialRadioStreamingDelegate","level":4,"type":"heading","text":"SocialRadioStreamingDelegate"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","isActive":true},{"type":"text","text":" is responsible for getting artwork for tracks, and track recommendations:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"SocialRadio will ask you for the URL to a provider of artwork given track Ids:","type":"text"}]}]}]},{"syntax":"swift","code":["public class MySocialRadioStreamingDelegate: NSObject, SocialRadioStreamingDelegate {","    \/\/ ...","    func asyncGetThumborLocation(completion: @escaping(_ url: String?) -> Void) -> Void {","        return self.imageGenerationURL","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"SocialRadio will ask for track recommendations for a given track:","type":"text"}]}]}]},{"syntax":"swift","code":["public class MySocialRadioStreamingDelegate: NSObject, SocialRadioStreamingDelegate {","    \/\/ ...","    func asyncGetTrackRecommendations(identifiers: [String],","                                      contextIds: [String]?,","                                      limit: Int, completion: @escaping(_ tracks: [TunedTrackModel]?) -> Void) -> Void {","        return completion(self.trackRecommendations(identifiers)","    }","    \/\/ ...","}"],"type":"codeListing"},{"anchor":"SocialRadioUIDelegate","level":4,"type":"heading","text":"SocialRadioUIDelegate"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"},{"type":"text","text":" is responsible for providing data required for the Radio UI to function, as well as presenting UI SocialRadio is not able to do on its own."}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SocialRadio allows the user to add one or multiple tracks to a radio show. When that action is triggered, SocialRadio asks this delegate to provide the UI for selecting them. This is done via "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentTracklist(filterOutExplicitContent:completion:)","type":"reference","isActive":true}]}]}]},{"syntax":"swift","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func presentTracklist(filterOutExplicitContent: Bool,","                          completion: @escaping (_ tracks: [TunedTrackModel]?,","                                                 _ contextType: String?, _ contextId: Int,","                                                 _ playlistName: String?) -> Void) {","        \/\/ Your implementation for presenting UI that allows to select one or more tracks:","        let tracklist = MyTracklist() { tracks, playlistName in","            \/\/ - Feed the track\/tracks selected as the second paramenter of the completion block,","            \/\/ - If the tracks selected are part of a playlist, feed the name opf that playlist as the thirsd parameter of the completion block.","            completion(tracks, playlistName)","        }","        self.present(filterOutExplicitContent, tracklist, animated: true)","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"At a time where SocialRadio requires a Tuned User Id, if it does not have one it will require the user to authenticate via "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentAuthentication(completion:)","isActive":true}],"type":"paragraph"}]}]},{"syntax":"swift","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func presentAuthentication(completion: @escaping (_ success: Bool) -> Void) {","        \/\/ Present your login here","        let authenticationDialog = MyAuthenticationDialog() { success in","            completion(success)","        }","        self.present(authenticationDialog, animated: true)","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"At times, SocialRadio will need to present a users’ profile. It will do so via ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentProfile(identifier:completion:)","isActive":true,"type":"reference"}]}]}]},{"syntax":"swift","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func presentProfile(identifier: String?, completion: @escaping () -> Void) {","        \/\/ Present the user profile here","        let profileDialog = MyProfileDialog(identifier: identifier) {","            completion()","        }","        self.present(profileDialog, animated: true)","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"At times, SocialRadio will need to know if a track is part of the user’s “Liked” playlist. It will ask the client application to do so via "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/isTrackLiked(identifier:completion:)","isActive":true}]}]}]},{"syntax":"swift","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func isTrackLiked(identifier: String, completion: @escaping (Bool) -> Void) {","        let likedPlaylist = myLikedPlaylist","        completion(myLikedPlaylist.contains(identifier))","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"SocialRadio allows for a user to flag\/unflag a track as Liked. When that happens, it will do so via ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/setTrackLiked(identifier:liked:completion:)","isActive":true,"type":"reference"}],"type":"paragraph"}]}]},{"syntax":"swift","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func setTrackLiked(identifier: String, liked: Bool,","                       completion: @escaping (_ error: Error?,","                                              _ success: Bool) -> Void) -> Void {","        let likedPlaylist = myLikedPlaylist","        if(liked) {","            likedPlaylist.add(identifier)","        } else {","            likedPlaylist.remove(identifier)","        }","        completion(null, true)","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"SocialRadio also notifies this delegate when it will and has minimised the Radio UI, and whe it will and has closed the Radio UI. It does so via ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willDismissRadioUI(userInitiated:)"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didDismissRadioUI(userInitiated:)"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willCloseRadioUI(userInitiated:)"},{"type":"text","text":", "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didCloseRadioUI(userInitiated:)"},{"type":"text","text":"."}]}]}]},{"syntax":"swift","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func willDismissRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    ","    func didDismissRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    ","    func willCloseRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    ","    func didCloseRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    \/\/ ...","}"],"type":"codeListing"},{"anchor":"SocialRadioStatusObserverDelegate","level":4,"type":"heading","text":"SocialRadioStatusObserverDelegate"},{"inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","isActive":true,"type":"reference"},{"type":"text","text":" is responsible for updating your player’s UI."}],"type":"paragraph"},{"anchor":"SocialBackendDelegate","level":4,"type":"heading","text":"SocialBackendDelegate"},{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","type":"reference","isActive":true},{"text":" is responsible for fetching and refreshing your social backend’s credentials:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"SocialRadio will at timed want to know which user is logged in:","type":"text"}],"type":"paragraph"}]}]},{"syntax":"swift","code":["public class MySocialBackendDelegate: NSObject, SocialBackendDelegate {","    func loggedInUser() -> SocialRadioUser? {","        retun self.loggedInUser","    }","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"SocialRadio will ask you to refresh your custom backend’s credentials should they have expired:","type":"text"}],"type":"paragraph"}]}]},{"syntax":"swift","code":["public class MySocialBackendDelegate: NSObject, SocialBackendDelegate {","    func refreshSocialCredentials(oldAccessToken: String?, refreshToken: String?, tokenType: String?,","                                        completion: @escaping (_ error: Error?,","                                                            _ credentials: SocialRadioSocialCredentials?) -> Void) {","        self.refreshCredentials(completion)","    }","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Should your backend respond with a different model than those defined in this documentation, this function allows you to map the responses to align with SocialRadio models","type":"text"}]}]}]},{"syntax":"swift","code":["public class MySocialBackendDelegate: NSObject, SocialBackendDelegate {","    func translateEndpointResponse(endpoint: String?,","                                   pathParameters: [String:String]?,","                                   queryParameters: [URLQueryItem]?,","                                   body: [String: Any]?,","                                   error: Error?, statusCode: Int, response: Any?, responseData: Data?, httpsResponse: HTTPURLResponse?,","                                   completion: @escaping (_ error: Error?, _ statusCode: Int, _ response: Any?, _ responseData: Data?) -> Void)","    {","        return completion(error, statusCode, response, responseData)","    }","}"],"type":"codeListing"},{"anchor":"Checking-if-SocialRadio-is-initialised","level":3,"type":"heading","text":"Checking if SocialRadio is initialised"},{"inlineContent":[{"text":"To check wether AutomixIQ is currently initialised, use","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialised()"}],"type":"paragraph"}]}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/asyncGetTrackMetadata(trackId:completion:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetTrackMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"track"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","kind":"typeIdentifier","text":"TunedTrackModel"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetTrackMetadataWithTrackId:completion:"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ when it requires the metadata of a track in order to load it."}],"title":"asyncGetTrackMetadata(trackId:completion:)","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/asyncgettrackmetadata(trackid:completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/trackDownloadProgressChanged(trackId:progress:)":{"navigatorTitle":[{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}],"title":"trackDownloadProgressChanged(trackId:progress:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/trackdownloadprogresschanged(trackid:progress:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/didCloseRadioUI(userInitiated:)":{"navigatorTitle":[{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate\/didcloseradioui(userinitiated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","title":"didCloseRadioUI(userInitiated:)","required":true,"abstract":[{"type":"text","text":"Called by SocialRadio when the Radio UI is closed"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didCloseRadioUI(userInitiated:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioSocialCredentials":{"title":"SocialRadioSocialCredentials","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioSocialCredentials"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioSocialCredentials"}],"abstract":[{"text":"SocialRadioSocialCredentials models credentials to access social REST APIs.","type":"text"}],"url":"\/documentation\/socialradio\/socialradiosocialcredentials","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialBackendDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialBackendDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","role":"symbol","title":"SocialBackendDelegate","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/socialbackenddelegate","navigatorTitle":[{"kind":"identifier","text":"SocialBackendDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/presentTracklist(filterOutExplicitContent:completion:)":{"abstract":[{"type":"text","text":"Called by SocialRadio when it wishes to present UI to select one or many tracks"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentTracklist"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filterOutExplicitContent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","text":"TunedTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"contextType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"contextId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playlistName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"url":"\/documentation\/socialradio\/socialradiouidelegate\/presenttracklist(filteroutexplicitcontent:completion:)","navigatorTitle":[{"kind":"identifier","text":"presentTracklistWithFilterOutExplicitContent:completion:"}],"title":"presentTracklist(filterOutExplicitContent:completion:)","type":"topic","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentTracklist(filterOutExplicitContent:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioConfig"}],"url":"\/documentation\/socialradio\/socialradioconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioConfig"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","abstract":[],"title":"SocialRadioConfig","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"kind":"symbol","type":"topic","title":"AutomixIQStreamingDelegate","url":"\/documentation\/socialradio\/automixiqstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStreamingDelegate":{"title":"SocialRadioStreamingDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations."}],"url":"\/documentation\/socialradio\/socialradiostreamingdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/didDismissRadioUI(userInitiated:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didDismissRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didDismissRadioUIWithUserInitiated:","kind":"identifier"}],"role":"symbol","title":"didDismissRadioUI(userInitiated:)","abstract":[{"text":"Called by SocialRadio when the Radio UI is dismissed","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate\/diddismissradioui(userinitiated:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didDismissRadioUI(userInitiated:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/initialised()":{"url":"\/documentation\/socialradio\/socialradio\/initialised()","title":"initialised()","navigatorTitle":[{"text":"initialised","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the initialised status of the Automix SDK."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialised()","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialised","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"kind":"symbol","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"url":"\/documentation\/socialradio\/socialradiouidelegate","title":"SocialRadioUIDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/isTrackLiked(identifier:completion:)":{"navigatorTitle":[{"text":"isTrackLikedWithIdentifier:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTrackLiked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"isLiked","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/isTrackLiked(identifier:completion:)","url":"\/documentation\/socialradio\/socialradiouidelegate\/istrackliked(identifier:completion:)","title":"isTrackLiked(identifier:completion:)","role":"symbol","abstract":[{"type":"text","text":"Called by SocialRadio when it needs to know wether a track is liked or not"}],"required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/presentAuthentication(completion:)":{"kind":"symbol","role":"symbol","title":"presentAuthentication(completion:)","type":"topic","abstract":[{"type":"text","text":"Called by SocialRadio when it wishes to present UI to authenticate a user"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentAuthentication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentAuthentication(completion:)","url":"\/documentation\/socialradio\/socialradiouidelegate\/presentauthentication(completion:)","navigatorTitle":[{"kind":"identifier","text":"presentAuthenticationWithCompletion:"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"title":"SocialRadioStatusObserverDelegate","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/setTrackLiked(identifier:liked:completion:)":{"abstract":[{"type":"text","text":"Called by SocialRadio when it needs add or remove a track with a given identifier from liked"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTrackLiked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"liked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"url":"\/documentation\/socialradio\/socialradiouidelegate\/settrackliked(identifier:liked:completion:)","navigatorTitle":[{"kind":"identifier","text":"setTrackLikedWithIdentifier:liked:completion:"}],"title":"setTrackLiked(identifier:liked:completion:)","type":"topic","kind":"symbol","required":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/setTrackLiked(identifier:liked:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/trackDownloadCompleted(trackId:data:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDownloadCompleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device."}],"required":true,"navigatorTitle":[{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadCompleted(trackId:data:)","role":"symbol","title":"trackDownloadCompleted(trackId:data:)","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/trackdownloadcompleted(trackid:data:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","kind":"symbol","type":"topic","title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)","abstract":[{"text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"streamingDeviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newSessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}],"required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/asyncCheckDeviceStatus(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncCheckDeviceStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"canContinuePlaying","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"asyncCheckDeviceStatus(completion:)","type":"topic","abstract":[{"text":"Called by AutomixIQ regularly while something is being played, this can be used if you have restrictions on the number of devices that can play simultaneously","type":"text"}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/asynccheckdevicestatus(completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncCheckDeviceStatus(completion:)","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"text":"asyncCheckDeviceStatusWithCompletion:","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/presentProfile(identifier:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentProfile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/socialradio\/socialradiouidelegate\/presentprofile(identifier:completion:)","kind":"symbol","role":"symbol","abstract":[{"text":"Called by SocialRadio when it wishes to present UI with a user’s information","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentProfile(identifier:completion:)","required":true,"type":"topic","title":"presentProfile(identifier:completion:)","navigatorTitle":[{"text":"presentProfileWithIdentifier:completion:","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/syncGetTrackMetadata(trackId:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetTrackMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","text":"TunedTrackModel"},{"kind":"text","text":"?"}],"type":"topic","title":"syncGetTrackMetadata(trackId:)","role":"symbol","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/syncgettrackmetadata(trackid:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}],"kind":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/isLoggedIn()":{"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/isloggedin()","title":"isLoggedIn()","navigatorTitle":[{"kind":"identifier","text":"isLoggedIn"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/isLoggedIn()","abstract":[{"type":"text","text":"Called by AutomixIQ to learn if it is allowed to stream content that is protected by some form of authentication."},{"type":"text","text":" "},{"type":"text","text":"An example is, an implementation via an API behind OAuth would return true if access and refresh tokens are available, false otherwise"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoggedIn"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/getDeviceIdentifier()":{"type":"topic","kind":"symbol","abstract":[{"text":"Called by Automix to learn the identity of the device requesting to stream audio, for those services that require it.","type":"text"},{"text":" ","type":"text"},{"text":"An example would be, a service that only allows one device to stream at any one time, would need to know the identity of the device to provide the stream.","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/getdeviceidentifier()","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/getDeviceIdentifier()","title":"getDeviceIdentifier()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getDeviceIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"getDeviceIdentifier","kind":"identifier"}],"required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/syncGetCachedTrack(trackId:)":{"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/syncgetcachedtrack(trackid:)","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetCachedTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"title":"syncGetCachedTrack(trackId:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","abstract":[{"text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available.","type":"text"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/willDismissRadioUI(userInitiated:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"willDismissRadioUIWithUserInitiated:","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiouidelegate\/willdismissradioui(userinitiated:)","role":"symbol","title":"willDismissRadioUI(userInitiated:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willDismissRadioUI(userInitiated:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willDismissRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Called by SocialRadio when the Radio UI about to be dismissed","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/willCloseRadioUI(userInitiated:)":{"url":"\/documentation\/socialradio\/socialradiouidelegate\/willcloseradioui(userinitiated:)","required":true,"role":"symbol","type":"topic","navigatorTitle":[{"text":"willCloseRadioUIWithUserInitiated:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willCloseRadioUI(userInitiated:)","abstract":[{"type":"text","text":"Called by SocialRadio when the Radio UI is closed"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"willCloseRadioUI(userInitiated:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"anchor":"Initialising-SocialRadio-for-use-with-a-custom-backend","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioSocialCredentials"],"title":"Initialising SocialRadio for use with a custom backend"}],"path":"\/seeAlsoSections"},{"op":"replace","value":"asyncGetTrackMetadataWithTrackId:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetTrackMetadataWithTrackId:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/fragments"},{"op":"replace","value":"trackDownloadProgressChangedWithTrackId:progress:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments"},{"op":"replace","value":"didCloseRadioUIWithUserInitiated:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didCloseRadioUI(userInitiated:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCloseRadioUIWithUserInitiated:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didCloseRadioUI(userInitiated:)\/fragments"},{"op":"replace","value":"SocialRadioSocialCredentials","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioSocialCredentials\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioSocialCredentials"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioSocialCredentials\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioSocialCredentials"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioSocialCredentials\/navigatorTitle"},{"op":"replace","value":"SocialBackendDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/title"},{"op":"replace","value":[{"text":"SocialBackendDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialBackendDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentTracklist(filterOutExplicitContent:completion:)\/title","op":"replace","value":"presentTracklistWithFilterOutExplicitContent:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentTracklist(filterOutExplicitContent:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"presentTracklistWithFilterOutExplicitContent:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","op":"replace","value":"SocialRadioConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title","op":"replace","value":"AutomixIQStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/title","op":"replace","value":"SocialRadioStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didDismissRadioUI(userInitiated:)\/title","op":"replace","value":"didDismissRadioUIWithUserInitiated:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didDismissRadioUI(userInitiated:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didDismissRadioUIWithUserInitiated:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialised()\/title","op":"replace","value":"initialised"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialised()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"initialised","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","op":"replace","value":"SocialRadioUIDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","op":"replace","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1isTrackLiked(identifier:completion:)\/title","op":"replace","value":"isTrackLikedWithIdentifier:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1isTrackLiked(identifier:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isTrackLikedWithIdentifier:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentAuthentication(completion:)\/title","op":"replace","value":"presentAuthenticationWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentAuthentication(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"presentAuthenticationWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","op":"replace","value":"SocialRadioStatusObserverDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1setTrackLiked(identifier:liked:completion:)\/title","op":"replace","value":"setTrackLikedWithIdentifier:liked:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1setTrackLiked(identifier:liked:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setTrackLikedWithIdentifier:liked:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/title","op":"replace","value":"trackDownloadCompletedWithTrackId:data:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/title","op":"replace","value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/title","op":"replace","value":"asyncCheckDeviceStatusWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncCheckDeviceStatusWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentProfile(identifier:completion:)\/title","op":"replace","value":"presentProfileWithIdentifier:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentProfile(identifier:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentProfileWithIdentifier:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/title","op":"replace","value":"syncGetTrackMetadataWithTrackId:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1isLoggedIn()\/title","op":"replace","value":"isLoggedIn"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1isLoggedIn()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isLoggedIn","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/title","op":"replace","value":"getDeviceIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getDeviceIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/title","op":"replace","value":"syncGetCachedTrackWithTrackId:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willDismissRadioUI(userInitiated:)\/title","op":"replace","value":"willDismissRadioUIWithUserInitiated:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willDismissRadioUI(userInitiated:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"willDismissRadioUIWithUserInitiated:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willCloseRadioUI(userInitiated:)\/title","op":"replace","value":"willCloseRadioUIWithUserInitiated:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willCloseRadioUI(userInitiated:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willCloseRadioUIWithUserInitiated:"}]}]}]}