{"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate\/asyncGetThumborLocation(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate\/asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)"],"anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiostreamingdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiostreamingdelegate"]}],"metadata":{"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"role":"symbol","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"roleHeading":"Protocol","externalID":"c:@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate","title":"SocialRadioStreamingDelegate"},"seeAlsoSections":[{"title":"Initializing SocialRadio for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel"],"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs","generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStreamingDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"abstract":[{"text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"title":"SocialRadioStatusObserverDelegate","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioConfig"}],"url":"\/documentation\/socialradio\/socialradioconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioConfig"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","abstract":[],"title":"SocialRadioConfig","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","title":"SocialRadioStatusVariable","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiostatusvariable","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-article":{"kind":"article","type":"topic","role":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","abstract":[{"type":"text","text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs"}],"url":"\/documentation\/socialradio\/initialising-socialradio-article","title":"Initializing SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStreamingDelegate":{"title":"SocialRadioStreamingDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations."}],"url":"\/documentation\/socialradio\/socialradiostreamingdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/socialradiofeaturesetconfig","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","title":"SocialRadioFeatureSetConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioLogLevel":{"url":"\/documentation\/socialradio\/socialradiologlevel","kind":"symbol","title":"SocialRadioLogLevel","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"abstract":[{"text":"SocialRadioLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioLogLevel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStreamingDelegate/asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)":{"required":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate\/asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)","role":"symbol","abstract":[{"type":"text","text":"Called by the AutomixIQ SDK when it needs tracks recommendations based on a set of identifiers"}],"url":"\/documentation\/socialradio\/socialradiostreamingdelegate\/asyncgettrackrecommendations(identifiers:contextids:limit:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetTrackRecommendations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"contextIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","text":"TunedTrackModel"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:"}],"title":"asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"title":"SocialRadioUIConfig","url":"\/documentation\/socialradio\/socialradiouiconfig","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUIConfig"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStreamingDelegate/asyncGetThumborLocation(completion:)":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"asyncGetThumborLocationWithCompletion:"}],"url":"\/documentation\/socialradio\/socialradiostreamingdelegate\/asyncgetthumborlocation(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetThumborLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called by the AutomixIQ SDK when it needs the URL for thumbor. Return nil on completion if there is none"}],"title":"asyncGetThumborLocation(completion:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate\/asyncGetThumborLocation(completion:)"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradioplaybackmode","navigatorTitle":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"SocialRadio playback mode","type":"text"}],"title":"SocialRadioPlaybackMode","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","role":"symbol","title":"TunedRestDelegate","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/tunedrestdelegate","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"kind":"symbol","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"url":"\/documentation\/socialradio\/socialradiouidelegate","title":"SocialRadioUIDelegate","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SocialRadioStreamingDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate\/asyncGetThumborLocation(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate\/asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)"]}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"title":"Initializing SocialRadio for use with Tuned Global’s APIs","anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStreamingDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SocialRadioStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","op":"replace"},{"value":"SocialRadioConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","op":"replace"},{"value":[{"text":"SocialRadioConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","op":"replace"},{"value":"SocialRadioStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title","op":"replace"},{"value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments","op":"replace"},{"value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle","op":"replace"},{"value":"SocialRadioStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/fragments","op":"replace"},{"value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/navigatorTitle","op":"replace"},{"value":"SocialRadioFeatureSetConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/title","op":"replace"},{"value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/fragments","op":"replace"},{"value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/navigatorTitle","op":"replace"},{"value":"SocialRadioLogLevel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/navigatorTitle","op":"replace"},{"value":"asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate~1asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate~1asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)\/fragments","op":"replace"},{"value":"SocialRadioUIConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/title","op":"replace"},{"value":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/fragments","op":"replace"},{"value":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/navigatorTitle","op":"replace"},{"value":"asyncGetThumborLocationWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate~1asyncGetThumborLocation(completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetThumborLocationWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate~1asyncGetThumborLocation(completion:)\/fragments","op":"replace"},{"value":"SocialRadioPlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/navigatorTitle","op":"replace"},{"value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","op":"replace"},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle","op":"replace"},{"value":"SocialRadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","op":"replace"},{"value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}