{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waveformDataForTrack"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyTransitions"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel","text":"AutomixIQWaveformModel"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/automixiqobjc\/waveformdatafortrack(withidentifier:applytransitions:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/waveformDataForTrack(withIdentifier:applyTransitions:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waveformDataForTrack"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyTransitions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixIQWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel"},{"kind":"text","text":"?"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)AutomixIQObjC(im)waveformDataForTrackWithIdentifier:applyTransitions:","title":"waveformDataForTrack(withIdentifier:applyTransitions:)","modules":[{"name":"SocialRadio"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQObjC","kind":"identifier"}],"title":"AutomixIQObjC","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","url":"\/documentation\/socialradio\/automixiqobjc","abstract":[],"navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC/waveformDataForTrack(withIdentifier:applyTransitions:)":{"kind":"symbol","role":"symbol","type":"topic","abstract":[],"title":"waveformDataForTrack(withIdentifier:applyTransitions:)","url":"\/documentation\/socialradio\/automixiqobjc\/waveformdatafortrack(withidentifier:applytransitions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"waveformDataForTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyTransitions"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"AutomixIQWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/waveformDataForTrack(withIdentifier:applyTransitions:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQWaveformModel"}],"role":"symbol","title":"AutomixIQWaveformModel","kind":"symbol","url":"\/documentation\/socialradio\/automixiqwaveformmodel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","title":"SocialRadio","url":"\/documentation\/socialradio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","value":"AutomixIQWaveformModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle"}]}]}