{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiq\/init"]}],"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQ(im)init","title":"init","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/init","interfaceLanguage":"occ"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/init":{"url":"\/documentation\/automixiq\/automixiq\/init","title":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ":{"abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}],"type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq\/automixiq","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ","navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/title","op":"replace","value":"AutomixIQ"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}]}]}]}