{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waveformDataForTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applyEnterTransition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applyExitTransition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","text":"AutomixIQWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The identifier of a track","type":"text"}],"type":"paragraph"}],"name":"identifier"},{"content":[{"inlineContent":[{"text":"True if you want the transition to the start of the track to be applied to the waveform data, false otherwise","type":"text"}],"type":"paragraph"}],"name":"applyEnterTransition"},{"content":[{"inlineContent":[{"text":"True if you want the transition to the end of the track to be applied to the waveform data, false otherwise","type":"text"}],"type":"paragraph"}],"name":"applyExitTransition"}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"returns the waveform data"}]}]}],"type":"unorderedList"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiq\/waveformdatafortrack(identifier:applyentertransition:applyexittransition:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiq\/waveformdatafortrack(identifier:applyentertransition:applyexittransition:)"]}],"metadata":{"navigatorTitle":[{"text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waveformDataForTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applyEnterTransition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applyExitTransition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel","text":"AutomixIQWaveformModel"},{"kind":"text","text":"?"}],"title":"waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)","modules":[{"name":"SocialRadio"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)AutomixIQ(im)waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)"},"abstract":[{"type":"text","text":"Gets the waveform data for a track."}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQ","kind":"identifier"}],"title":"AutomixIQ","abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiq","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"url":"\/documentation\/socialradio\/automixiqwaveformmodel","role":"symbol","kind":"symbol","type":"topic","title":"AutomixIQWaveformModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQWaveformModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)":{"navigatorTitle":[{"text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"applyEnterTransition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"applyExitTransition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel"},{"text":"?","kind":"text"}],"type":"topic","title":"waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)","url":"\/documentation\/socialradio\/automixiq\/waveformdatafortrack(identifier:applyentertransition:applyexittransition:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Gets the waveform data for a track."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel","text":"AutomixIQWaveformModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel"},{"text":" *) ","kind":"text"},{"text":"waveformDataForTrackWithIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"applyEnterTransition:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"applyEnterTransition","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"applyExitTransition:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"applyExitTransition","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"text":"The identifier of a track","type":"text"}]}]},{"name":"applyEnterTransition","content":[{"type":"paragraph","inlineContent":[{"text":"True if you want the transition to the start of the track to be applied to the waveform data, false otherwise","type":"text"}]}]},{"name":"applyExitTransition","content":[{"type":"paragraph","inlineContent":[{"text":"True if you want the transition to the end of the track to be applied to the waveform data, false otherwise","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"AutomixIQ","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle","op":"replace"},{"value":"AutomixIQWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle","op":"replace"},{"value":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)\/fragments","op":"replace"}]}]}