{"metadata":{"externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioMixtape(py)waveform","modules":[{"name":"SocialRadioLite"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"waveform"}],"title":"waveform","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveform","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioWaveformBlob","text":"SocialRadioWaveformBlob"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape\/waveform"},"abstract":[{"type":"text","text":"The waveform representation for this mixtape"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"waveform","kind":"identifier"},{"kind":"text","text":": "},{"text":"SocialRadioWaveformBlob","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioWaveformBlob","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/socialradiolite\/socialradiomixtape\/waveform"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiomixtape\/waveform"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape"]]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioWaveformBlob":{"navigatorTitle":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"type":"topic","title":"SocialRadioWaveformBlob","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiowaveformblob","abstract":[{"text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtape":{"type":"topic","kind":"symbol","title":"SocialRadioMixtape","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtape","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"role":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","url":"\/documentation\/socialradiolite\/socialradiomixtape"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtape/waveform":{"title":"waveform","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"waveform","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioWaveformBlob"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape\/waveform","role":"symbol","abstract":[{"text":"The waveform representation for this mixtape","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"waveform"}],"kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtape\/waveform"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"waveform"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"waveform","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"SocialRadioWaveformBlob","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioWaveformBlob","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"waveform"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SocialRadioWaveformBlob","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/fragments","value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}]},{"value":"SocialRadioMixtape","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtape"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape~1waveform\/title","op":"replace","value":"waveform"},{"value":[{"text":"waveform","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape~1waveform\/fragments"}]}]}