{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlist","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"AutomixIQStatusVariable.playlist","role":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariablePlaylist","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playlist","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@AutomixIQStatusVariable@AutomixIQStatusVariablePlaylist","modules":[{"name":"AutomixIQ"}]},"variants":[{"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/playlist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/playlist"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlist"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable":{"url":"\/documentation\/automixiq\/automixiqstatusvariable","kind":"symbol","role":"symbol","type":"topic","title":"AutomixIQStatusVariable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusVariable"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playlist":{"title":"AutomixIQStatusVariable.playlist","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylist"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlist"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playlist","url":"\/documentation\/automixiq\/automixiqstatusvariable\/playlist"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AutomixIQStatusVariablePlaylist","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylist"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"AutomixIQStatusVariablePlaylist","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AutomixIQStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/navigatorTitle","op":"replace"},{"value":"AutomixIQStatusVariablePlaylist","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playlist\/title","op":"replace"},{"value":[{"text":"AutomixIQStatusVariablePlaylist","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playlist\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}