{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack\/color"},"abstract":[{"type":"text","text":"The significant color of the artwork of this track as a string representation"}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiomixtapetrack\/color"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiomixtapetrack\/color"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","title":"color","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioMixtapeTrack(py)color","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"color","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack/color":{"title":"color","type":"topic","kind":"symbol","abstract":[{"text":"The significant color of the artwork of this track as a string representation","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack\/color","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"color","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"color","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiomixtapetrack\/color","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","type":"topic","abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"kind":"symbol","url":"\/documentation\/socialradio\/socialradiomixtapetrack","navigatorTitle":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"title":"SocialRadioMixtapeTrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"color"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"color"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"color"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack~1color\/title","value":"color"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack~1color\/fragments","value":[{"kind":"identifier","text":"color"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/title","value":"SocialRadioMixtapeTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/fragments","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}