{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList\/init"},"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/automixsdklist\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"init","symbolKind":"method","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKList(im)init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList"]]},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKList":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList","url":"\/documentation\/socialradio\/automixsdklist","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKList"}],"title":"AutomixSDKList"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKList/init":{"title":"init","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList\/init","role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/automixsdklist\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKList\/title","value":"AutomixSDKList"},{"value":[{"text":"AutomixSDKList","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKList\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKList\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKList"}]}]}]}