{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"metadata":{"role":"symbol","externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariablePlaylistDiff","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"SocialRadio"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylistDiff"}],"title":"AutomixIQStatusVariable.playlistDiff"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playlistDiff","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/playlistdiff"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/playlistdiff"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable","title":"AutomixIQStatusVariable","kind":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","type":"topic","abstract":[{"type":"text","text":"AutomixIQ status variable type"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playlistDiff":{"navigatorTitle":[{"text":"AutomixIQStatusVariablePlaylistDiff","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playlistDiff","role":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixiqstatusvariable\/playlistdiff","title":"AutomixIQStatusVariable.playlistDiff","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"url":"\/documentation\/socialradio","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixIQStatusVariablePlaylistDiff","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylistDiff"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"AutomixIQStatusVariablePlaylistDiff","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixIQStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments"},{"op":"replace","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariablePlaylistDiff","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playlistDiff\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlaylistDiff","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playlistDiff\/fragments"}]}]}