{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayeruserdelegate\/getuserfollows(identifiers:loggedinuseridentifier:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayeruserdelegate\/getuserfollows(identifiers:loggedinuseridentifier:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate\/getUserFollows(identifiers:loggedInUserIdentifier:completion:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUserFollows"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"loggedInUserIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userFollows"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"identifiers","content":[{"type":"paragraph","inlineContent":[{"text":"List of user identifiers to check.","type":"text"}]}]},{"name":"loggedInUserIdentifier","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the logged-in user.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter userFollows: A mapping from user ID to follow status.","type":"text"}]}]}],"type":"unorderedList"}],"name":"completion"}],"kind":"parameters"}],"abstract":[{"text":"Retrieves follow statuses for a list of users.","type":"text"}],"metadata":{"modules":[{"name":"SocialRadio"}],"required":true,"title":"getUserFollows(identifiers:loggedInUserIdentifier:completion:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getUserFollowsWithIdentifiers:loggedInUserIdentifier:completion:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserFollows"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"loggedInUserIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"userFollows","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"externalID":"c:@M@SocialRadio@objc(pl)SocialLayerUserDelegate(im)getUserFollowsWithIdentifiers:loggedInUserIdentifier:completion:"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerUserDelegate/getUserFollows(identifiers:loggedInUserIdentifier:completion:)":{"url":"\/documentation\/socialradio\/sociallayeruserdelegate\/getuserfollows(identifiers:loggedinuseridentifier:completion:)","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getUserFollowsWithIdentifiers:loggedInUserIdentifier:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserFollows"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"loggedInUserIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"userFollows","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Retrieves follow statuses for a list of users.","type":"text"}],"title":"getUserFollows(identifiers:loggedInUserIdentifier:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate\/getUserFollows(identifiers:loggedInUserIdentifier:completion:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"url":"\/documentation\/socialradio","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerUserDelegate":{"url":"\/documentation\/socialradio\/sociallayeruserdelegate","title":"SocialLayerUserDelegate","navigatorTitle":[{"kind":"identifier","text":"SocialLayerUserDelegate"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding  users."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerUserDelegate"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"getUserFollowsWithIdentifiers:loggedInUserIdentifier:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getUserFollowsWithIdentifiers:loggedInUserIdentifier:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getUserFollowsWithIdentifiers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifiers"},{"kind":"text","text":" "},{"kind":"identifier","text":"loggedInUserIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"loggedInUserIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"List of user identifiers to check."}],"type":"paragraph"}],"name":"identifiers"},{"name":"loggedInUserIdentifier","content":[{"inlineContent":[{"type":"text","text":"The ID of the logged-in user."}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter userFollows: A mapping from user ID to follow status."}]}]}],"type":"unorderedList"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate~1getUserFollows(identifiers:loggedInUserIdentifier:completion:)\/title","op":"replace","value":"getUserFollowsWithIdentifiers:loggedInUserIdentifier:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate~1getUserFollows(identifiers:loggedInUserIdentifier:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getUserFollowsWithIdentifiers:loggedInUserIdentifier:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/title","op":"replace","value":"SocialLayerUserDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/fragments","op":"replace","value":[{"text":"SocialLayerUserDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialLayerUserDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}