{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postComment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"mixIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"tags","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SocialRadioCommentTag","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioCommentTag"},{"text":"], ","kind":"text"},{"text":"trackIndex10","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"mixTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"comment","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioComment","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioComment"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the user posting the comment.","type":"text"}]}],"name":"userIdentifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the mixtape.","type":"text"}]}],"name":"mixIdentifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Comment text.","type":"text"}]}],"name":"text"},{"content":[{"inlineContent":[{"text":"List of tags for the comment.","type":"text"}],"type":"paragraph"}],"name":"tags"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional track index."}]}],"name":"trackIndex10"},{"content":[{"inlineContent":[{"text":"Optional timestamp in the mix.","type":"text"}],"type":"paragraph"}],"name":"mixTimestamp"},{"content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Posts a comment to a mixtape.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayermixtapecommentsdelegate\/postcomment(useridentifier:mixidentifier:text:tags:trackindex10:mixtimestamp:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayermixtapecommentsdelegate\/postcomment(useridentifier:mixidentifier:text:tags:trackindex10:mixtimestamp:completion:)"]}],"metadata":{"navigatorTitle":[{"text":"postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeCommentsDelegate(im)postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Method","title":"postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postComment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mixIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tags"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioCommentTag","text":"SocialRadioCommentTag"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"trackIndex10"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mixTimestamp"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"comment","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioComment","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioComment","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioComment"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioComment"}],"abstract":[{"text":"SocialRadioComment models a comment","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","type":"topic","title":"SocialRadioComment","url":"\/documentation\/socialradio\/socialradiocomment"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate":{"role":"symbol","title":"SocialLayerMixtapeCommentsDelegate","kind":"symbol","navigatorTitle":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}],"abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding commenting a mixtape.","type":"text"}],"url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCommentTag":{"url":"\/documentation\/socialradio\/socialradiocommenttag","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioCommentTag"}],"type":"topic","role":"symbol","abstract":[{"text":"SocialRadioCommentTag models a user tag in a comment","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","navigatorTitle":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"title":"SocialRadioCommentTag"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate/postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postComment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mixIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"tags","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SocialRadioCommentTag","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioCommentTag"},{"text":"], ","kind":"text"},{"text":"trackIndex10","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"mixTimestamp","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"comment","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioComment","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioComment"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Posts a comment to a mixtape.","type":"text"}],"navigatorTitle":[{"text":"postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate\/postcomment(useridentifier:mixidentifier:text:tags:trackindex10:mixtimestamp:completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)","title":"postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)","kind":"symbol","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"postCommentWithUserIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"userIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mixIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"mixIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"text:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tags:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<SocialRadioCommentTag *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"tags","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"trackIndex10:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"trackIndex10","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mixTimestamp:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" *) ","kind":"text"},{"text":"mixTimestamp","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"SocialRadioComment","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioComment"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the user posting the comment."}]}],"name":"userIdentifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the mixtape.","type":"text"}]}],"name":"mixIdentifier"},{"content":[{"inlineContent":[{"text":"Comment text.","type":"text"}],"type":"paragraph"}],"name":"text"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List of tags for the comment."}]}],"name":"tags"},{"content":[{"inlineContent":[{"text":"Optional track index.","type":"text"}],"type":"paragraph"}],"name":"trackIndex10"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional timestamp in the mix."}]}],"name":"mixTimestamp"},{"content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}],"name":"completion"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SocialRadioComment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/title"},{"value":[{"kind":"identifier","text":"SocialRadioComment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioComment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/navigatorTitle"},{"value":"SocialLayerMixtapeCommentsDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/title"},{"value":[{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/fragments"},{"value":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/navigatorTitle"},{"value":"SocialRadioCommentTag","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/title"},{"value":[{"text":"SocialRadioCommentTag","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/navigatorTitle"},{"value":"postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)\/fragments"}]}]}