{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayStart","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@M@SocialRadio@E@AutomixIQPlaybackEventType@AutomixIQPlaybackEventTypeTrackPlayStart","title":"AutomixIQPlaybackEventType.trackPlayStart","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayStart"}],"modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayStart"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType"]]},"variants":[{"paths":["\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplaystart"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplaystart"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","title":"SocialRadio","url":"\/documentation\/socialradio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"title":"AutomixIQPlaybackEventType","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType","kind":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqplaybackeventtype"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/trackPlayStart":{"url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplaystart","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayStart","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayStart"}],"title":"AutomixIQPlaybackEventType.trackPlayStart","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AutomixIQPlaybackEventTypeTrackPlayStart","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/title","value":"AutomixIQPlaybackEventType"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/navigatorTitle","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayStart\/title","value":"AutomixIQPlaybackEventTypeTrackPlayStart"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayStart\/fragments","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"op":"replace"}]}]}