{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"willCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/willCloseRadioUI(userInitiated:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate"]]},"abstract":[{"type":"text","text":"Called by AutomixSDK when the Radio UI is closed"}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"willCloseRadioUI","kind":"identifier"},{"kind":"text","text":"("},{"text":"userInitiated","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@SocialRadio@objc(pl)RadioUIDelegate(im)willCloseRadioUIWithUserInitiated:","required":true,"title":"willCloseRadioUI(userInitiated:)","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"willCloseRadioUIWithUserInitiated:","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/socialradio\/radiouidelegate\/willcloseradioui(userinitiated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/radiouidelegate\/willcloseradioui(userinitiated:)"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/willCloseRadioUI(userInitiated:)":{"title":"willCloseRadioUI(userInitiated:)","required":true,"kind":"symbol","url":"\/documentation\/socialradio\/radiouidelegate\/willcloseradioui(userinitiated:)","abstract":[{"text":"Called by AutomixSDK when the Radio UI is closed","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"willCloseRadioUI"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"willCloseRadioUIWithUserInitiated:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/willCloseRadioUI(userInitiated:)","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate":{"role":"symbol","title":"RadioUIDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioUIDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RadioUIDelegate"}],"abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"url":"\/documentation\/socialradio\/radiouidelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"willCloseRadioUIWithUserInitiated:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willCloseRadioUIWithUserInitiated:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"willCloseRadioUIWithUserInitiated:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"userInitiated"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1willCloseRadioUI(userInitiated:)\/title","value":"willCloseRadioUIWithUserInitiated:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1willCloseRadioUI(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willCloseRadioUIWithUserInitiated:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/title","value":"RadioUIDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/fragments","value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/navigatorTitle","value":[{"text":"RadioUIDelegate","kind":"identifier"}]}]}]}