{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"externalID":"c:@M@SocialRadio@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeMixPlaybackEnded","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}],"roleHeading":"Case","modules":[{"name":"SocialRadio"}],"role":"symbol","title":"AutomixSDKPlaybackEventType.mixPlaybackEnded"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkplaybackeventtype\/mixplaybackended"]},{"paths":["\/documentation\/socialradio\/automixsdkplaybackeventtype\/mixplaybackended"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType":{"abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype","title":"AutomixSDKPlaybackEventType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/mixPlaybackEnded":{"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/mixplaybackended","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","type":"topic","title":"AutomixSDKPlaybackEventType.mixPlaybackEnded","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/fragments","op":"replace","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"op":"replace"},{"op":"replace","value":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}]}]}]}