{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel\/Meta","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The value of the metadata"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Meta"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedpluginmetadatamodel\/meta"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/tunedpluginmetadatamodel\/meta"]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"Meta","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"Meta","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)TunedPluginMetadataModel(py)Meta","title":"Meta"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedPluginMetadataModel":{"type":"topic","navigatorTitle":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"url":"\/documentation\/socialradio\/tunedpluginmetadatamodel","kind":"symbol","title":"TunedPluginMetadataModel","abstract":[{"text":"TunedPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"text":" ","type":"text"},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedPluginMetadataModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","title":"SocialRadio","url":"\/documentation\/socialradio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedPluginMetadataModel/Meta":{"navigatorTitle":[{"kind":"identifier","text":"Meta"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Meta"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/socialradio\/tunedpluginmetadatamodel\/meta","kind":"symbol","title":"Meta","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel\/Meta","type":"topic","abstract":[{"type":"text","text":"The value of the metadata"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"Meta","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"Meta","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"Meta","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"TunedPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/fragments","value":[{"kind":"identifier","text":"TunedPluginMetadataModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/navigatorTitle","value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}]},{"op":"replace","value":"Meta","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel~1Meta\/title"},{"value":[{"kind":"identifier","text":"Meta"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel~1Meta\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}