{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"artistName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"isExplicit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isAd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"releaseName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"tempo","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The identifier of the track"}],"type":"paragraph"}],"name":"trackId"},{"name":"artistName","content":[{"inlineContent":[{"type":"text","text":"The name of the main artist of the track"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The title of the track","type":"text"}],"type":"paragraph"}],"name":"name"},{"content":[{"inlineContent":[{"type":"text","text":"The track duration in seconds"}],"type":"paragraph"}],"name":"duration"},{"content":[{"inlineContent":[{"text":"True if the track contains explicit lyrics, false otherwise","type":"text"}],"type":"paragraph"}],"name":"isExplicit"},{"name":"isAd","content":[{"type":"paragraph","inlineContent":[{"text":"True if the track is an Ad, false otherwise","type":"text"}]}]},{"name":"trackNumber","content":[{"inlineContent":[{"text":"The index of the track in the album it was released in","type":"text"}],"type":"paragraph"}]},{"name":"releaseName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The nemae of the release this track’s in"}]}]},{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key of this track as a String in Camelot format, i.e. 8m, nil if unavailable"}]}]},{"name":"tempo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The bpm of this track as a float"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url of the artwork image for this track as a String"}]}],"name":"image"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel\/init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Initialises a Track Model"}],"sections":[],"metadata":{"title":"init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"artistName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isExplicit"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isAd","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"trackNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"releaseName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"tempo"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)TunedTrackModel(im)initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedtrackmodel\/init(trackid:artistname:name:duration:isexplicit:isad:tracknumber:releasename:key:tempo:image:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/tunedtrackmodel\/init(trackid:artistname:name:duration:isexplicit:isad:tracknumber:releasename:key:tempo:image:)"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel/init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)":{"title":"init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"artistName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isExplicit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAd"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"releaseName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"tempo","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/socialradio\/tunedtrackmodel\/init(trackid:artistname:name:duration:isexplicit:isad:tracknumber:releasename:key:tempo:image:)","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel\/init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)","abstract":[{"text":"Initialises a Track Model","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"url":"\/documentation\/socialradio\/tunedtrackmodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}],"kind":"symbol","title":"TunedTrackModel","abstract":[{"type":"text","text":"TunedTrackModel models a track. This metadata is required."}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithTrackId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackId"},{"kind":"text","text":" "},{"kind":"identifier","text":"artistName:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"artistName"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration:"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"duration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isExplicit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isExplicit"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isAd"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackNumber:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"trackNumber","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"releaseName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"releaseName"},{"kind":"text","text":" "},{"kind":"identifier","text":"key:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tempo:"},{"kind":"text","text":"("},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tempo"},{"text":" ","kind":"text"},{"text":"image:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"trackId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the track"}]}]},{"name":"artistName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the main artist of the track"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The title of the track"}],"type":"paragraph"}],"name":"name"},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"text":"The track duration in seconds","type":"text"}]}]},{"name":"isExplicit","content":[{"inlineContent":[{"type":"text","text":"True if the track contains explicit lyrics, false otherwise"}],"type":"paragraph"}]},{"name":"isAd","content":[{"inlineContent":[{"type":"text","text":"True if the track is an Ad, false otherwise"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The index of the track in the album it was released in"}],"type":"paragraph"}],"name":"trackNumber"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The nemae of the release this track’s in"}]}],"name":"releaseName"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The key of this track as a String in Camelot format, i.e. 8m, nil if unavailable","type":"text"}]}],"name":"key"},{"name":"tempo","content":[{"inlineContent":[{"type":"text","text":"The bpm of this track as a float"}],"type":"paragraph"}]},{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The url of the artwork image for this track as a String"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel~1init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel~1init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)\/fragments"},{"value":"TunedTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title"},{"value":[{"text":"TunedTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle","value":[{"text":"TunedTrackModel","kind":"identifier"}],"op":"replace"}]}]}