{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/authenticationDelegate","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerAuthenticationDelegate","text":"SocialLayerAuthenticationDelegate"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"authenticationDelegate"}],"symbolKind":"property","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Property","title":"authenticationDelegate","externalID":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates(py)authenticationDelegate"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialLayerAuthenticationDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerAuthenticationDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/authenticationdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/authenticationdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates"]]},"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding authentication"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"url":"\/documentation\/socialradio\/sociallayerdelegates","title":"SocialLayerDelegates","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","role":"symbol","abstract":[{"text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions.","type":"text"},{"text":" ","type":"text"},{"text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc.","type":"text"},{"text":" ","type":"text"},{"text":"See each delegate’s documentation for details.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerDelegates"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialLayerDelegates"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerAuthenticationDelegate":{"url":"\/documentation\/socialradio\/sociallayerauthenticationdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding authentication"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","title":"SocialLayerAuthenticationDelegate","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates/authenticationDelegate":{"type":"topic","role":"symbol","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding authentication","type":"text"}],"title":"authenticationDelegate","navigatorTitle":[{"kind":"identifier","text":"authenticationDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/authenticationDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialLayerAuthenticationDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerAuthenticationDelegate"}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayerdelegates\/authenticationdelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"authenticationDelegate","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"authenticationDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialLayerAuthenticationDelegate","kind":"typeIdentifier","text":"id<SocialLayerAuthenticationDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","value":"SocialLayerDelegates"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"kind":"identifier","text":"SocialLayerDelegates"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","value":[{"text":"SocialLayerDelegates","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/title","value":"SocialLayerAuthenticationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/navigatorTitle","value":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1authenticationDelegate\/title","value":"authenticationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1authenticationDelegate\/fragments","value":[{"text":"authenticationDelegate","kind":"identifier"}]}]}]}