{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/adindex"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/adindex"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adIndex","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariableAdIndex","role":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariableAdIndex","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"case","roleHeading":"Case","title":"AutomixIQStatusVariable.adIndex","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adIndex","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adIndex","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/adIndex":{"role":"symbol","type":"topic","kind":"symbol","title":"AutomixIQStatusVariable.adIndex","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"adIndex"}],"abstract":[],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/adindex","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableAdIndex"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adIndex"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"title":"AutomixIQStatusVariable","kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/automixiqstatusvariable","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AutomixIQStatusVariableAdIndex","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableAdIndex"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixIQStatusVariableAdIndex","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1adIndex\/title","value":"AutomixIQStatusVariableAdIndex","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1adIndex\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableAdIndex"}],"op":"replace"},{"value":"AutomixIQStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title","op":"replace"},{"value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}