{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotStartAudioEngine"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/errorcode\/cannotstartaudioengine"]},{"paths":["\/documentation\/socialradiolite\/errorcode\/cannotstartaudioengine"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode"]]},"kind":"symbol","metadata":{"title":"ErrorCode.cannotStartAudioEngine","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotStartAudioEngine"}],"modules":[{"name":"SocialRadioLite"}],"externalID":"c:@M@SocialRadioLite@E@ErrorCode@ErrorCodeCannotStartAudioEngine","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotStartAudioEngine"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotStartAudioEngine"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/cannotStartAudioEngine":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotStartAudioEngine"}],"title":"ErrorCode.cannotStartAudioEngine","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotStartAudioEngine","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/cannotstartaudioengine","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotStartAudioEngine","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"ErrorCodeCannotStartAudioEngine","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"ErrorCodeCannotStartAudioEngine","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodeCannotStartAudioEngine"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotStartAudioEngine\/title","value":"ErrorCodeCannotStartAudioEngine"},{"value":[{"kind":"identifier","text":"ErrorCodeCannotStartAudioEngine"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotStartAudioEngine\/fragments"}]}]}