{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cannotCreateChannelLayout","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Case","symbolKind":"case","title":"ErrorCode.cannotCreateChannelLayout","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotCreateChannelLayout"}],"modules":[{"name":"SocialRadioLite"}],"externalID":"c:@M@SocialRadioLite@E@ErrorCode@ErrorCodeCannotCreateChannelLayout","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cannotCreateChannelLayout","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotCreateChannelLayout","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/errorcode\/cannotcreatechannellayout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/errorcode\/cannotcreatechannellayout"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode"]]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/cannotCreateChannelLayout":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotCreateChannelLayout"}],"title":"ErrorCode.cannotCreateChannelLayout","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/cannotCreateChannelLayout","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/cannotcreatechannellayout","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotCreateChannelLayout","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ErrorCodeCannotCreateChannelLayout","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeCannotCreateChannelLayout"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeCannotCreateChannelLayout","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotCreateChannelLayout\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1cannotCreateChannelLayout\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeCannotCreateChannelLayout"}]},{"value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}]}]}]}