{"variants":[{"paths":["\/documentation\/socialradiolite\/errorcode\/loadtracksemptyplaylist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradiolite\/errorcode\/loadtracksemptyplaylist"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/loadTracksEmptyPlaylist","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"ErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@SocialRadioLite@E@ErrorCode@ErrorCodeLoadTracksEmptyPlaylist","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"loadTracksEmptyPlaylist","kind":"identifier"}],"role":"symbol","title":"ErrorCode.loadTracksEmptyPlaylist","modules":[{"name":"SocialRadioLite"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTracksEmptyPlaylist"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/loadTracksEmptyPlaylist":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeLoadTracksEmptyPlaylist"}],"title":"ErrorCode.loadTracksEmptyPlaylist","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/loadTracksEmptyPlaylist","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/loadtracksemptyplaylist","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracksEmptyPlaylist","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ErrorCodeLoadTracksEmptyPlaylist","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"ErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1loadTracksEmptyPlaylist\/title","value":"ErrorCodeLoadTracksEmptyPlaylist","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1loadTracksEmptyPlaylist\/fragments","value":[{"kind":"identifier","text":"ErrorCodeLoadTracksEmptyPlaylist"}],"op":"replace"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}