{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/socialradiolite\/errorcode\/movetrackoutofbounds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradiolite\/errorcode\/movetrackoutofbounds"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moveTrackOutOfBounds"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/moveTrackOutOfBounds","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeMoveTrackOutOfBounds"}],"title":"ErrorCode.moveTrackOutOfBounds","externalID":"c:@M@SocialRadioLite@E@ErrorCode@ErrorCodeMoveTrackOutOfBounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveTrackOutOfBounds","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"SocialRadioLite"}],"symbolKind":"case"},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/moveTrackOutOfBounds":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeMoveTrackOutOfBounds"}],"title":"ErrorCode.moveTrackOutOfBounds","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/moveTrackOutOfBounds","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/movetrackoutofbounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveTrackOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ErrorCodeMoveTrackOutOfBounds","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ErrorCodeMoveTrackOutOfBounds","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ErrorCodeMoveTrackOutOfBounds","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"ErrorCodeMoveTrackOutOfBounds","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1moveTrackOutOfBounds\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1moveTrackOutOfBounds\/fragments","value":[{"text":"ErrorCodeMoveTrackOutOfBounds","kind":"identifier"}]},{"value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]},{"value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle","op":"replace"}]}]}