{"variants":[{"paths":["\/documentation\/socialradiolite\/errorcode\/offlinenotuneduseridavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/errorcode\/offlinenotuneduseridavailable"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offlineNoTunedUserIdAvailable","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"ErrorCode.offlineNoTunedUserIdAvailable","symbolKind":"case","externalID":"c:@M@SocialRadioLite@E@ErrorCode@ErrorCodeOfflineNoTunedUserIdAvailable","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}],"modules":[{"name":"SocialRadioLite"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/offlineNoTunedUserIdAvailable":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeOfflineNoTunedUserIdAvailable"}],"title":"ErrorCode.offlineNoTunedUserIdAvailable","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/offlineNoTunedUserIdAvailable","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/offlinenotuneduseridavailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"ErrorCodeOfflineNoTunedUserIdAvailable","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeOfflineNoTunedUserIdAvailable"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodeOfflineNoTunedUserIdAvailable"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}]},{"op":"replace","value":"ErrorCodeOfflineNoTunedUserIdAvailable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1offlineNoTunedUserIdAvailable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1offlineNoTunedUserIdAvailable\/fragments","value":[{"kind":"identifier","text":"ErrorCodeOfflineNoTunedUserIdAvailable"}],"op":"replace"}]}]}