{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/errorcode\/pausealreadypaused"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/errorcode\/pausealreadypaused"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/pauseAlreadyPaused","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pauseAlreadyPaused","kind":"identifier"}]}]}],"metadata":{"title":"ErrorCode.pauseAlreadyPaused","roleHeading":"Case","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseAlreadyPaused","kind":"identifier"}],"externalID":"c:@M@SocialRadioLite@E@ErrorCode@ErrorCodePauseAlreadyPaused","modules":[{"name":"SocialRadioLite"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/pauseAlreadyPaused":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}],"title":"ErrorCode.pauseAlreadyPaused","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/pauseAlreadyPaused","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/pausealreadypaused","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseAlreadyPaused","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodePauseAlreadyPaused"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ErrorCodePauseAlreadyPaused","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1pauseAlreadyPaused\/title","op":"replace","value":"ErrorCodePauseAlreadyPaused"},{"value":[{"text":"ErrorCodePauseAlreadyPaused","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1pauseAlreadyPaused\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}