{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"SocialRadioLite"}],"externalID":"c:@M@SocialRadioLite@E@ErrorCode@ErrorCodeSdkNotInitialisedVersionNoLongerSupported","role":"symbol","title":"ErrorCode.sdkNotInitialisedVersionNoLongerSupported","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkNotInitialisedVersionNoLongerSupported"}]},"variants":[{"paths":["\/documentation\/socialradiolite\/errorcode\/sdknotinitialisedversionnolongersupported"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/errorcode\/sdknotinitialisedversionnolongersupported"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkNotInitialisedVersionNoLongerSupported"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode"]]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/sdkNotInitialisedVersionNoLongerSupported":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"title":"ErrorCode.sdkNotInitialisedVersionNoLongerSupported","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/sdknotinitialisedversionnolongersupported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle"},{"op":"replace","value":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/title"},{"value":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/fragments"}]}]}