{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/startLoopingNoLoopingTrack","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"startLoopingNoLoopingTrack","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradiolite\/errorcode\/startloopingnoloopingtrack"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/errorcode\/startloopingnoloopingtrack"]}],"metadata":{"role":"symbol","title":"ErrorCode.startLoopingNoLoopingTrack","modules":[{"name":"SocialRadioLite"}],"symbolKind":"case","externalID":"c:@M@SocialRadioLite@E@ErrorCode@ErrorCodeStartLoopingNoLoopingTrack","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"startLoopingNoLoopingTrack","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"ErrorCodeStartLoopingNoLoopingTrack","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode/startLoopingNoLoopingTrack":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode\/startLoopingNoLoopingTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLoopingNoLoopingTrack","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradiolite\/errorcode\/startloopingnoloopingtrack","title":"ErrorCode.startLoopingNoLoopingTrack","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"ErrorCodeStartLoopingNoLoopingTrack","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ErrorCodeStartLoopingNoLoopingTrack","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeStartLoopingNoLoopingTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1startLoopingNoLoopingTrack\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode~1startLoopingNoLoopingTrack\/fragments"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}