{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/unable_to_load_mix","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unable_to_load_mix","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/errorcode\/unable_to_load_mix"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/errorcode\/unable_to_load_mix"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unable_to_load_mix"}],"role":"symbol","navigatorTitle":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeUnable_to_load_mix","title":"ErrorCode.unable_to_load_mix"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/unable_to_load_mix":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/unable_to_load_mix","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unable_to_load_mix","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode\/unable_to_load_mix","type":"topic","title":"ErrorCode.unable_to_load_mix"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"type":"topic","title":"ErrorCode","url":"\/documentation\/socialradio\/errorcode","role":"symbol","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodeUnable_to_load_mix"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1unable_to_load_mix\/title","value":"ErrorCodeUnable_to_load_mix"},{"op":"replace","value":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1unable_to_load_mix\/fragments"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}