{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TunedAutomixPlaybackModeLiveConsumption"}],"role":"symbol","roleHeading":"Case","title":"TunedAutomixPlaybackMode.liveConsumption","symbolKind":"case","externalID":"c:@M@SocialRadio@E@TunedAutomixPlaybackMode@TunedAutomixPlaybackModeLiveConsumption","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveConsumption","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode"]]},"variants":[{"paths":["\/documentation\/socialradio\/tunedautomixplaybackmode\/liveconsumption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/tunedautomixplaybackmode\/liveconsumption"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode\/liveConsumption","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveConsumption"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode/liveConsumption":{"title":"TunedAutomixPlaybackMode.liveConsumption","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode\/liveConsumption","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedAutomixPlaybackModeLiveConsumption"}],"kind":"symbol","url":"\/documentation\/socialradio\/tunedautomixplaybackmode\/liveconsumption","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveConsumption"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode":{"role":"symbol","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"navigatorTitle":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","url":"\/documentation\/socialradio\/tunedautomixplaybackmode","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"title":"TunedAutomixPlaybackMode"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"TunedAutomixPlaybackModeLiveConsumption","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TunedAutomixPlaybackModeLiveConsumption"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"TunedAutomixPlaybackModeLiveConsumption","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"TunedAutomixPlaybackModeLiveConsumption","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode~1liveConsumption\/title"},{"value":[{"text":"TunedAutomixPlaybackModeLiveConsumption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode~1liveConsumption\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/title","value":"TunedAutomixPlaybackMode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/fragments","value":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/navigatorTitle","value":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}]}]}]}