{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType\/Moved"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqplaylistoperationtype\/moved"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqplaylistoperationtype\/moved"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Moved","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Moved"}],"title":"AutomixIQPlaylistOperationType.Moved","roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@AutomixIQPlaylistOperationType@AutomixIQPlaylistOperationTypeMoved","symbolKind":"case","modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperationTypeMoved"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType"]]},"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaylistOperationType/Moved":{"abstract":[],"url":"\/documentation\/automixiq\/automixiqplaylistoperationtype\/moved","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Moved"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType\/Moved","navigatorTitle":[{"text":"AutomixIQPlaylistOperationTypeMoved","kind":"identifier"}],"kind":"symbol","title":"AutomixIQPlaylistOperationType.Moved"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaylistOperationType":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaylistOperationType","url":"\/documentation\/automixiq\/automixiqplaylistoperationtype","title":"AutomixIQPlaylistOperationType"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","url":"\/documentation\/automixiq","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"AutomixIQPlaylistOperationTypeMoved","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AutomixIQPlaylistOperationTypeMoved","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixIQPlaylistOperationTypeMoved"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixIQPlaylistOperationTypeMoved","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType~1Moved\/title"},{"op":"replace","value":[{"text":"AutomixIQPlaylistOperationTypeMoved","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType~1Moved\/fragments"},{"op":"replace","value":"AutomixIQPlaylistOperationType","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType\/fragments"},{"op":"replace","value":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaylistOperationType\/navigatorTitle"}]}]}