{"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQEqualiserConfig(im)init","title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqequaliserconfig\/init"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQEqualiserConfig":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQEqualiserConfig"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqequaliserconfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig","role":"symbol","abstract":[],"title":"AutomixIQEqualiserConfig","kind":"symbol","navigatorTitle":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQEqualiserConfig/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqequaliserconfig\/init","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/init","role":"symbol","abstract":[],"title":"init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig\/title","op":"replace","value":"AutomixIQEqualiserConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig\/fragments","op":"replace","value":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]}]}]}