{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveConsumption"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkplaybackmode\/liveconsumption"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkplaybackmode\/liveconsumption"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode\/liveConsumption","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode"]]},"metadata":{"modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@E@AutomixSDKPlaybackMode@AutomixSDKPlaybackModeLiveConsumption","role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackModeLiveConsumption"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveConsumption"}],"title":"AutomixSDKPlaybackMode.liveConsumption"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackMode/liveConsumption":{"url":"\/documentation\/socialradio\/automixsdkplaybackmode\/liveconsumption","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackModeLiveConsumption"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveConsumption"}],"abstract":[],"title":"AutomixSDKPlaybackMode.liveConsumption","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode\/liveConsumption"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackMode":{"abstract":[{"type":"text","text":"AutomixIQ playback mode"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","title":"AutomixSDKPlaybackMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkplaybackmode"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKPlaybackModeLiveConsumption"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaybackModeLiveConsumption"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"AutomixSDKPlaybackModeLiveConsumption","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"value":"AutomixSDKPlaybackModeLiveConsumption","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode~1liveConsumption\/title","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKPlaybackModeLiveConsumption","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode~1liveConsumption\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/title","op":"replace","value":"AutomixSDKPlaybackMode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/fragments","op":"replace","value":[{"text":"AutomixSDKPlaybackMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}