{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canReorderTracks"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable"]]},"metadata":{"externalID":"c:@M@SocialRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableCanReorderTracks","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanReorderTracks"}],"symbolKind":"case","roleHeading":"Case","title":"AutomixSDKStatusVariable.canReorderTracks","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canReorderTracks"}],"modules":[{"name":"SocialRadio"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkstatusvariable\/canreordertracks"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkstatusvariable\/canreordertracks"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable\/canReorderTracks","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable/canReorderTracks":{"role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkstatusvariable\/canreordertracks","title":"AutomixSDKStatusVariable.canReorderTracks","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"canReorderTracks","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariableCanReorderTracks","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable\/canReorderTracks","type":"topic","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable":{"title":"AutomixSDKStatusVariable","url":"\/documentation\/socialradio\/automixsdkstatusvariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"AutomixSDKStatusVariableCanReorderTracks","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"AutomixSDKStatusVariableCanReorderTracks","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"AutomixSDKStatusVariableCanReorderTracks","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable~1canReorderTracks\/title","value":"AutomixSDKStatusVariableCanReorderTracks","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanReorderTracks"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable~1canReorderTracks\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/navigatorTitle","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}