{"sections":[],"metadata":{"modules":[{"name":"PacemakerRadio"}],"externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig(py)maximumTimerStatusUpdatesPerSecond","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"maximumTimerStatusUpdatesPerSecond","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maximumTimerStatusUpdatesPerSecond","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","title":"maximumTimerStatusUpdatesPerSecond"},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig\/maximumTimerStatusUpdatesPerSecond","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig\/maximumtimerstatusupdatespersecond"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig\/maximumtimerstatusupdatespersecond"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maximumTimerStatusUpdatesPerSecond","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]}]}],"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKFeatureSetConfig/maximumTimerStatusUpdatesPerSecond":{"kind":"symbol","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maximumTimerStatusUpdatesPerSecond"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTimerStatusUpdatesPerSecond"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"maximumTimerStatusUpdatesPerSecond","url":"\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig\/maximumtimerstatusupdatespersecond","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig\/maximumTimerStatusUpdatesPerSecond"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","title":"PacemakerRadio","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKFeatureSetConfig":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","abstract":[],"title":"RadioSDKFeatureSetConfig","url":"\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig","role":"symbol","navigatorTitle":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maximumTimerStatusUpdatesPerSecond"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"maximumTimerStatusUpdatesPerSecond","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumTimerStatusUpdatesPerSecond"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig~1maximumTimerStatusUpdatesPerSecond\/title","value":"maximumTimerStatusUpdatesPerSecond","op":"replace"},{"value":[{"kind":"identifier","text":"maximumTimerStatusUpdatesPerSecond"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig~1maximumTimerStatusUpdatesPerSecond\/fragments"},{"value":"RadioSDKFeatureSetConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/fragments","value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/navigatorTitle","op":"replace","value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]}]}]}