{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus"},"kind":"symbol","abstract":[{"text":"AutomixIQStatus models the State of the AutomixIQ during playback.","type":"text"}],"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSCopying","doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"]}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/init()"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/adIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/adTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/adTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canBack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canMixNow","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canOnOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canPlayPause","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canReorderTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canSeek","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canSkipToNext","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canSkipToPrevious","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/explicitLyricsFiltering","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/mixing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/muted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/nextTransitionDuration","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/normalisedVolume","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playSpeed","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playbackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingAd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playlist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playlistDiff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/readyToPlay","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/replayOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/vinylStartStop"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/copy(with:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/variableValue(_:)"]},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/allStatusVariables()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/automixIQStatusVariableName(_:)"]}],"variants":[{"paths":["\/documentation\/socialradio\/automixiqstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}]}]}],"seeAlsoSections":[{"generated":true,"anchor":"AutomixIQ","title":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperationType"]}],"metadata":{"navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"symbolKind":"class","title":"AutomixIQStatus","modules":[{"name":"SocialRadio"}],"role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQStatus"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQObjC"}],"url":"\/documentation\/socialradio\/automixiqobjc","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"type":"topic","title":"AutomixIQObjC","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"title":"AutomixIQWaveformModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqwaveformmodel","role":"symbol","navigatorTitle":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedPluginMetadataModel":{"kind":"symbol","abstract":[{"type":"text","text":"TunedPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"type":"text","text":" "},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"role":"symbol","type":"topic","url":"\/documentation\/socialradio\/tunedpluginmetadatamodel","navigatorTitle":[{"kind":"identifier","text":"TunedPluginMetadataModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedPluginMetadataModel"}],"title":"TunedPluginMetadataModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/failedTrackLoadIdentifiers":{"kind":"symbol","title":"failedTrackLoadIdentifiers","url":"\/documentation\/socialradio\/automixiqstatus\/failedtrackloadidentifiers","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTrackLoadIdentifiers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"abstract":[{"type":"text","text":"Represents the tracks that failed loading for any reason"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/failedTrackLoadIdentifiers"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playingTrackIndex":{"kind":"symbol","url":"\/documentation\/socialradio\/automixiqstatus\/playingtrackindex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"playingTrackIndex"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackIndex","title":"playingTrackIndex","role":"symbol","abstract":[{"text":"Represents the position of the currently playing track in the playlist if not mixing, the front track of the two mixed together if mixing. This would be the track a UI needs to show as playing or active.","type":"text"},{"text":" ","type":"text"},{"text":"If seeking, it reports seek landing track index until jump is complete. This should be use on the UI.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperationType":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}],"url":"\/documentation\/socialradio\/automixiqplaylistoperationtype","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperationType","title":"AutomixIQPlaylistOperationType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation":{"role":"symbol","abstract":[{"type":"text","text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"url":"\/documentation\/socialradio\/automixiqplaylistoperation","type":"topic","title":"AutomixIQPlaylistOperation","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/adIndex":{"navigatorTitle":[{"kind":"identifier","text":"adIndex"}],"abstract":[],"title":"adIndex","url":"\/documentation\/socialradio\/automixiqstatus\/adindex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/adIndex"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/mixing":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/mixing","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"mixing","url":"\/documentation\/socialradio\/automixiqstatus\/mixing","abstract":[{"type":"text","text":"Represents if more than one track is concurrently playing from Automix SDK (mixing), true if it is, false otherwise."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mixing"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/nextTransitionDuration":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTransitionDuration"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"title":"nextTransitionDuration","navigatorTitle":[{"kind":"identifier","text":"nextTransitionDuration"}],"role":"symbol","abstract":[{"type":"text","text":"Represents the duration of the upcoming transition, 0 if no transition available"}],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/automixiqstatus\/nexttransitionduration","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/nextTransitionDuration"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/vinylStartStop":{"abstract":[{"type":"text","text":"Represents wether the engine does the vinyl sound effects when play\/pause"}],"url":"\/documentation\/socialradio\/automixiqstatus\/vinylstartstop","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/vinylStartStop","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinylStartStop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"vinylStartStop"}],"kind":"symbol","title":"vinylStartStop","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}],"url":"\/documentation\/socialradio\/automixiqstatus","role":"symbol","abstract":[{"text":"AutomixIQStatus models the State of the AutomixIQ during playback.","type":"text"}],"title":"AutomixIQStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatus"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/canPlayPause":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canPlayPause","navigatorTitle":[{"kind":"identifier","text":"canPlayPause"}],"role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/automixiqstatus\/canplaypause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayPause"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"type":"text","text":"Represents wether the engine is ready to receive a play or pause command."}],"title":"canPlayPause"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/requestedPauseTrackIdentifier":{"url":"\/documentation\/socialradio\/automixiqstatus\/requestedpausetrackidentifier","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/requestedPauseTrackIdentifier","title":"requestedPauseTrackIdentifier","abstract":[{"text":"Represents the track Automix SDK is currently flagged to be paused at the end, nil if none is","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"requestedPauseTrackIdentifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestedPauseTrackIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"type":"topic","url":"\/documentation\/socialradio\/tunedrestdelegate","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"title":"TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/canMixNow":{"title":"canMixNow","type":"topic","abstract":[{"type":"text","text":"Represents wether the ‘next’ action would lead to a proper mix or a regular jumps. Depends on wether we had enough time to analyze the next track or not."}],"url":"\/documentation\/socialradio\/automixiqstatus\/canmixnow","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canMixNow","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canMixNow","kind":"symbol","navigatorTitle":[{"text":"canMixNow","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playingTrackTotalTime":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackTotalTime","type":"topic","url":"\/documentation\/socialradio\/automixiqstatus\/playingtracktotaltime","abstract":[{"text":"Represents the total playback time of the playing track.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playingTrackTotalTime"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackTotalTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"playingTrackTotalTime"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playingTrackIdentifier":{"abstract":[{"text":"Represents the identifier of the currently playing track if not mixing, the front track of the two mixed together if mixing. This would be the track a UI needs to show as playing or active.","type":"text"}],"title":"playingTrackIdentifier","url":"\/documentation\/socialradio\/automixiqstatus\/playingtrackidentifier","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackIdentifier","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"playingTrackIdentifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel":{"url":"\/documentation\/socialradio\/tunedloglevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","role":"symbol","title":"TunedLogLevel","abstract":[{"type":"text","text":"TunedLogLevel is an enum of all the AutomixIQ available log levels"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedLogLevel"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedLogLevel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","role":"collection","url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/allStatusVariables()":{"type":"topic","url":"\/documentation\/socialradio\/automixiqstatus\/allstatusvariables()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/allStatusVariables()","title":"allStatusVariables()","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allStatusVariables"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"allStatusVariables"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/adTrackCurrentTime":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixiqstatus\/adtrackcurrenttime","abstract":[{"text":"Represents the current playback time of the playing Ad","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adTrackCurrentTime","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"title":"adTrackCurrentTime","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/adTrackCurrentTime","navigatorTitle":[{"text":"adTrackCurrentTime","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","title":"AutomixIQMusicCacheDelegate","kind":"symbol","abstract":[{"text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"url":"\/documentation\/socialradio\/automixiqmusiccachedelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/canSkipToPrevious":{"url":"\/documentation\/socialradio\/automixiqstatus\/canskiptoprevious","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Represents wether the engine is ready to skip to a previous track.","type":"text"}],"title":"canSkipToPrevious","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canSkipToPrevious","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSkipToPrevious","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"canSkipToPrevious","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}],"abstract":[{"type":"text","text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}],"url":"\/documentation\/socialradio\/automixiq","title":"AutomixIQ","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/readyToPlay":{"navigatorTitle":[{"text":"readyToPlay","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readyToPlay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Represents wether the mix is readsy to play or currently loading.","type":"text"}],"url":"\/documentation\/socialradio\/automixiqstatus\/readytoplay","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/readyToPlay","title":"readyToPlay"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/canReorderTracks":{"kind":"symbol","abstract":[{"text":"Represents wether the engine is ready to receive a reorder tracks command.","type":"text"}],"url":"\/documentation\/socialradio\/automixiqstatus\/canreordertracks","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canReorderTracks","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canReorderTracks","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"canReorderTracks","navigatorTitle":[{"text":"canReorderTracks","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/replayOn":{"navigatorTitle":[{"text":"replayOn","kind":"identifier"}],"type":"topic","title":"replayOn","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replayOn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/socialradio\/automixiqstatus\/replayon","role":"symbol","abstract":[{"type":"text","text":"Represents wether the engine will replay the current playlist when it ends."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/replayOn"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/init()":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/init()","type":"topic","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatus\/init()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/preferredTransitionDurationSeconds":{"title":"preferredTransitionDurationSeconds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredTransitionDurationSeconds","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"abstract":[{"text":"Represents the preferred Automix SDK transition duration, 0 if disabled.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/preferredTransitionDurationSeconds","navigatorTitle":[{"text":"preferredTransitionDurationSeconds","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/automixiqstatus\/preferredtransitiondurationseconds","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/copy(with:)":{"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/copy(with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10ObjectiveC6NSZoneV","kind":"typeIdentifier","text":"NSZone"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"title":"copy(with:)","url":"\/documentation\/socialradio\/automixiqstatus\/copy(with:)","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/adTrackTotalTime":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"adTrackTotalTime"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/adTrackTotalTime","title":"adTrackTotalTime","url":"\/documentation\/socialradio\/automixiqstatus\/adtracktotaltime","abstract":[{"text":"Represents the total playback time of the playing Ad.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"adTrackTotalTime"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAuthenticationResponse","kind":"identifier"}],"navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"url":"\/documentation\/socialradio\/tunedauthenticationresponse","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"title":"TunedAuthenticationResponse","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/canBack":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canBack","type":"topic","title":"canBack","role":"symbol","url":"\/documentation\/socialradio\/automixiqstatus\/canback","navigatorTitle":[{"text":"canBack","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Represents wether the engine is ready to skip to the beginning of the current track.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canBack","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/automixIQStatusVariableName(_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixIQStatusVariableName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQStatusVariable","text":"AutomixIQStatusVariable"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"automixIQStatusVariableName(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/automixIQStatusVariableName(_:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"automixIQStatusVariableName:"}],"url":"\/documentation\/socialradio\/automixiqstatus\/automixiqstatusvariablename(_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/explicitLyricsFiltering":{"role":"symbol","url":"\/documentation\/socialradio\/automixiqstatus\/explicitlyricsfiltering","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/explicitLyricsFiltering","title":"explicitLyricsFiltering","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"explicitLyricsFiltering"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"explicitLyricsFiltering"}],"abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playingTrackCurrentTime":{"url":"\/documentation\/socialradio\/automixiqstatus\/playingtrackcurrenttime","title":"playingTrackCurrentTime","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackCurrentTime","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"playingTrackCurrentTime","kind":"identifier"}],"abstract":[{"text":"Represents the current playback time of the playing track. If seeking, it reports seek landing time until jump is complete. This should be use on the UI.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackCurrentTime"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ-article":{"role":"article","abstract":[{"type":"text","text":"Availablity of underlying technologies and APIs."}],"type":"topic","kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","title":"AutomixIQ","url":"\/documentation\/socialradio\/automixiq-article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playlistDiff":{"navigatorTitle":[{"kind":"identifier","text":"playlistDiff"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqstatus\/playlistdiff","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playlistDiff","abstract":[],"kind":"symbol","role":"symbol","title":"playlistDiff","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlistDiff"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQPlaylistOperation","text":"AutomixIQPlaylistOperation"},{"kind":"text","text":"]]?"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playbackMode":{"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"playbackMode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playbackMode","kind":"symbol","title":"playbackMode","url":"\/documentation\/socialradio\/automixiqstatus\/playbackmode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/canSeek":{"kind":"symbol","title":"canSeek","abstract":[{"type":"text","text":"Represents wether the engine is ready to receive a seek command."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canSeek"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"canSeek"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canSeek","url":"\/documentation\/socialradio\/automixiqstatus\/canseek"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedTrackModel"}],"url":"\/documentation\/socialradio\/tunedtrackmodel","abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"title":"TunedTrackModel","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedTrackModel"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/variableValue(_:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/variableValue(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"variableValue:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"variableValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQStatusVariable","text":"AutomixIQStatusVariable"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"}],"kind":"symbol","type":"topic","title":"variableValue(_:)","role":"symbol","url":"\/documentation\/socialradio\/automixiqstatus\/variablevalue(_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"title":"AutomixIQStatusObserverDelegate","url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playingTrackOriginalSessionId":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackOriginalSessionId","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackOriginalSessionId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"playingTrackOriginalSessionId","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatus\/playingtrackoriginalsessionid","kind":"symbol","title":"playingTrackOriginalSessionId","role":"symbol"},"doc://org.cocoapods.SocialRadio/objc(pl)NSCopying":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode":{"kind":"symbol","url":"\/documentation\/socialradio\/tunedautomixplaybackmode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"navigatorTitle":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"title":"TunedAutomixPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/normalisedVolume":{"url":"\/documentation\/socialradio\/automixiqstatus\/normalisedvolume","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalisedVolume","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/normalisedVolume","type":"topic","navigatorTitle":[{"text":"normalisedVolume","kind":"identifier"}],"role":"symbol","title":"normalisedVolume","abstract":[{"text":"Represents the Automix SDK volume from 1 to 0. Note the device’s iOS Volume acts as a master over this one: if iOS’volume is 0, no sound will be put out regardless of this value.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playingAd":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingAd","role":"symbol","type":"topic","title":"playingAd","navigatorTitle":[{"kind":"identifier","text":"playingAd"}],"url":"\/documentation\/socialradio\/automixiqstatus\/playingad","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"title":"AutomixIQConfig","url":"\/documentation\/socialradio\/automixiqconfig","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQConfig"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/mixId":{"title":"mixId","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/mixId","type":"topic","url":"\/documentation\/socialradio\/automixiqstatus\/mixid","navigatorTitle":[{"kind":"identifier","text":"mixId"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/transitionStartTimeSeconds":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionStartTimeSeconds"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"navigatorTitle":[{"kind":"identifier","text":"transitionStartTimeSeconds"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/transitionStartTimeSeconds","role":"symbol","title":"transitionStartTimeSeconds","url":"\/documentation\/socialradio\/automixiqstatus\/transitionstarttimeseconds","abstract":[{"type":"text","text":"Represents the track time in seconds in which the next (or current) transition starts"}]},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playingTrackStreamingProgress":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"playingTrackStreamingProgress","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"kind":"symbol","title":"playingTrackStreamingProgress","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackStreamingProgress","abstract":[{"type":"text","text":"Represents the percentage of downloaded track."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"playingTrackStreamingProgress","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatus\/playingtrackstreamingprogress"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedArtistModel":{"kind":"symbol","title":"TunedArtistModel","url":"\/documentation\/socialradio\/tunedartistmodel","abstract":[{"text":"TunedArtistModel models an artist.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedArtistModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","navigatorTitle":[{"text":"TunedArtistModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/canSkipToNext":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canSkipToNext","title":"canSkipToNext","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSkipToNext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/socialradio\/automixiqstatus\/canskiptonext","role":"symbol","navigatorTitle":[{"text":"canSkipToNext","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents wether the engine is ready to skip to the next track. If playing the last track of the playlist and “repeat” is off, this will be false."}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/canOnOff":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canOnOff","title":"canOnOff","url":"\/documentation\/socialradio\/automixiqstatus\/canonoff","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canOnOff","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"canOnOff","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Represents if the SDK can be turned On or off. It is true if not other On \/ Off action is ongoing, flase otherwise. When this switch is true, On \/Off actions return an error.","type":"text"}]},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/muted":{"navigatorTitle":[{"text":"muted","kind":"identifier"}],"type":"topic","title":"muted","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/muted","abstract":[{"type":"text","text":"Represents whether Automix SDK is muted or not. True if muted, false otherwise."}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"muted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/socialradio\/automixiqstatus\/muted"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playSpeed":{"url":"\/documentation\/socialradio\/automixiqstatus\/playspeed","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playSpeed","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playSpeed","abstract":[{"type":"text","text":"Represents the Automix SDK play speed as a factor, from 0.5 to 2"}],"kind":"symbol","navigatorTitle":[{"text":"playSpeed","kind":"identifier"}],"role":"symbol","title":"playSpeed"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/requestedLoopTrackIdentifier":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/requestedLoopTrackIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestedLoopTrackIdentifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestedLoopTrackIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"requestedLoopTrackIdentifier","abstract":[{"type":"text","text":"Represents the track Automix SDK is currently looping, nil if none is looping"}],"url":"\/documentation\/socialradio\/automixiqstatus\/requestedlooptrackidentifier"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playlist":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlist"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playlist","title":"playlist","abstract":[{"text":"Represents the list of track identifiers in the order they will be played","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"playlist"}],"url":"\/documentation\/socialradio\/automixiqstatus\/playlist"},"doc://org.cocoapods.SocialRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"type":"topic","title":"AutomixIQStatusVariable","url":"\/documentation\/socialradio\/automixiqstatusvariable","kind":"symbol","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playing":{"role":"symbol","abstract":[{"text":"Represents if sound is playing from Automix SDK, true if it is, false otherwise.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"playing","type":"topic","navigatorTitle":[{"text":"playing","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playing","url":"\/documentation\/socialradio\/automixiqstatus\/playing","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"AutomixIQStatus"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatus"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/adIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/adTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/adTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canBack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canMixNow","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canOnOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canPlayPause","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canReorderTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canSeek","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canSkipToNext","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canSkipToPrevious","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/explicitLyricsFiltering","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/mixing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/muted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/nextTransitionDuration","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/normalisedVolume","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playSpeed","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playbackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingAd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playlist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playlistDiff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/readyToPlay","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/replayOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/vinylStartStop"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/copy(with:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/init()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/variableValue(_:)"],"title":"Instance Methods"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/allStatusVariables()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/automixIQStatusVariableName(_:)"],"title":"Type Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSCopying"],"type":"conformsTo","title":"Conforms To"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperationType"],"generated":true,"anchor":"AutomixIQ","title":"AutomixIQ"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","op":"replace","value":"AutomixIQWaveformModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","op":"replace","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/title","op":"replace","value":"TunedPluginMetadataModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/fragments","op":"replace","value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedPluginMetadataModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1failedTrackLoadIdentifiers\/title","op":"replace","value":"failedTrackLoadIdentifiers"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1failedTrackLoadIdentifiers\/fragments","op":"replace","value":[{"kind":"identifier","text":"failedTrackLoadIdentifiers"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackIndex\/title","op":"replace","value":"playingTrackIndex"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackIndex\/fragments","op":"replace","value":[{"kind":"identifier","text":"playingTrackIndex"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperationType\/title","op":"replace","value":"AutomixIQPlaylistOperationType"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperationType\/fragments","op":"replace","value":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperationType\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/title","op":"replace","value":"AutomixIQPlaylistOperation"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/fragments","op":"replace","value":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1adIndex\/title","op":"replace","value":"adIndex"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1adIndex\/fragments","op":"replace","value":[{"text":"adIndex","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1mixing\/title","op":"replace","value":"mixing"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1mixing\/fragments","op":"replace","value":[{"text":"mixing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1nextTransitionDuration\/title","op":"replace","value":"nextTransitionDuration"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1nextTransitionDuration\/fragments","op":"replace","value":[{"kind":"identifier","text":"nextTransitionDuration"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1vinylStartStop\/title","op":"replace","value":"vinylStartStop"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1vinylStartStop\/fragments","op":"replace","value":[{"kind":"identifier","text":"vinylStartStop"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title","op":"replace","value":"AutomixIQStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments","op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canPlayPause\/title","op":"replace","value":"canPlayPause"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canPlayPause\/fragments","op":"replace","value":[{"kind":"identifier","text":"canPlayPause"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1requestedPauseTrackIdentifier\/title","op":"replace","value":"requestedPauseTrackIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1requestedPauseTrackIdentifier\/fragments","op":"replace","value":[{"text":"requestedPauseTrackIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","op":"replace","value":"TunedRestDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle","op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canMixNow\/title","op":"replace","value":"canMixNow"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canMixNow\/fragments","op":"replace","value":[{"text":"canMixNow","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackTotalTime\/title","op":"replace","value":"playingTrackTotalTime"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackTotalTime\/fragments","op":"replace","value":[{"text":"playingTrackTotalTime","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackIdentifier\/title","op":"replace","value":"playingTrackIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"playingTrackIdentifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/title","op":"replace","value":"TunedLogLevel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/fragments","op":"replace","value":[{"text":"TunedLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedLogLevel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1allStatusVariables()\/title","op":"replace","value":"allStatusVariables"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1allStatusVariables()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allStatusVariables"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1adTrackCurrentTime\/title","op":"replace","value":"adTrackCurrentTime"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1adTrackCurrentTime\/fragments","op":"replace","value":[{"text":"adTrackCurrentTime","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/title","op":"replace","value":"AutomixIQMusicCacheDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canSkipToPrevious\/title","op":"replace","value":"canSkipToPrevious"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canSkipToPrevious\/fragments","op":"replace","value":[{"kind":"identifier","text":"canSkipToPrevious"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title","op":"replace","value":"AutomixIQ"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments","op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1readyToPlay\/title","op":"replace","value":"readyToPlay"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1readyToPlay\/fragments","op":"replace","value":[{"text":"readyToPlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canReorderTracks\/title","op":"replace","value":"canReorderTracks"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canReorderTracks\/fragments","op":"replace","value":[{"text":"canReorderTracks","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1replayOn\/title","op":"replace","value":"replayOn"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1replayOn\/fragments","op":"replace","value":[{"text":"replayOn","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1preferredTransitionDurationSeconds\/title","op":"replace","value":"preferredTransitionDurationSeconds"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1preferredTransitionDurationSeconds\/fragments","op":"replace","value":[{"text":"preferredTransitionDurationSeconds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1copy(with:)\/title","op":"replace","value":"copyWithZone:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1copy(with:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1adTrackTotalTime\/title","op":"replace","value":"adTrackTotalTime"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1adTrackTotalTime\/fragments","op":"replace","value":[{"kind":"identifier","text":"adTrackTotalTime"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/title","op":"replace","value":"TunedAuthenticationResponse"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/fragments","op":"replace","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/navigatorTitle","op":"replace","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canBack\/title","op":"replace","value":"canBack"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canBack\/fragments","op":"replace","value":[{"text":"canBack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1automixIQStatusVariableName(_:)\/title","op":"replace","value":"automixIQStatusVariableName:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1automixIQStatusVariableName(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"automixIQStatusVariableName:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1explicitLyricsFiltering\/title","op":"replace","value":"explicitLyricsFiltering"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1explicitLyricsFiltering\/fragments","op":"replace","value":[{"text":"explicitLyricsFiltering","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackCurrentTime\/title","op":"replace","value":"playingTrackCurrentTime"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackCurrentTime\/fragments","op":"replace","value":[{"kind":"identifier","text":"playingTrackCurrentTime"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playlistDiff\/title","op":"replace","value":"playlistDiff"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playlistDiff\/fragments","op":"replace","value":[{"text":"playlistDiff","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playbackMode\/title","op":"replace","value":"playbackMode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playbackMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"playbackMode"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canSeek\/title","op":"replace","value":"canSeek"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canSeek\/fragments","op":"replace","value":[{"text":"canSeek","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title","op":"replace","value":"TunedTrackModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1variableValue(_:)\/title","op":"replace","value":"variableValue:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1variableValue(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"variableValue:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title","op":"replace","value":"AutomixIQStatusObserverDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackOriginalSessionId\/title","op":"replace","value":"playingTrackOriginalSessionId"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackOriginalSessionId\/fragments","op":"replace","value":[{"text":"playingTrackOriginalSessionId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/title","op":"replace","value":"TunedAutomixPlaybackMode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/fragments","op":"replace","value":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1normalisedVolume\/title","op":"replace","value":"normalisedVolume"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1normalisedVolume\/fragments","op":"replace","value":[{"kind":"identifier","text":"normalisedVolume"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingAd\/title","op":"replace","value":"playingAd"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingAd\/fragments","op":"replace","value":[{"text":"playingAd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/title","op":"replace","value":"AutomixIQConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/fragments","op":"replace","value":[{"text":"AutomixIQConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1mixId\/title","op":"replace","value":"mixId"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1mixId\/fragments","op":"replace","value":[{"text":"mixId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1transitionStartTimeSeconds\/title","op":"replace","value":"transitionStartTimeSeconds"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1transitionStartTimeSeconds\/fragments","op":"replace","value":[{"text":"transitionStartTimeSeconds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackStreamingProgress\/title","op":"replace","value":"playingTrackStreamingProgress"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackStreamingProgress\/fragments","op":"replace","value":[{"text":"playingTrackStreamingProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/title","op":"replace","value":"TunedArtistModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedArtistModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/navigatorTitle","op":"replace","value":[{"text":"TunedArtistModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canSkipToNext\/title","op":"replace","value":"canSkipToNext"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canSkipToNext\/fragments","op":"replace","value":[{"text":"canSkipToNext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canOnOff\/title","op":"replace","value":"canOnOff"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canOnOff\/fragments","op":"replace","value":[{"kind":"identifier","text":"canOnOff"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1muted\/title","op":"replace","value":"muted"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1muted\/fragments","op":"replace","value":[{"text":"muted","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playSpeed\/title","op":"replace","value":"playSpeed"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playSpeed\/fragments","op":"replace","value":[{"kind":"identifier","text":"playSpeed"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1requestedLoopTrackIdentifier\/title","op":"replace","value":"requestedLoopTrackIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1requestedLoopTrackIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"requestedLoopTrackIdentifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playlist\/title","op":"replace","value":"playlist"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playlist\/fragments","op":"replace","value":[{"kind":"identifier","text":"playlist"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title","op":"replace","value":"AutomixIQStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playing\/title","op":"replace","value":"playing"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playing\/fragments","op":"replace","value":[{"text":"playing","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}