{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/tunedadmodel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/tunedadmodel"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","doc:\/\/org.cocoapods.AutomixIQ\/s7CVarArgP","doc:\/\/org.cocoapods.AutomixIQ\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AutomixIQ\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AutomixIQ\/Se","doc:\/\/org.cocoapods.AutomixIQ\/SE","doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Class","modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"text":"TunedAdModel","kind":"identifier"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAdModel","kind":"identifier"}],"role":"symbol","title":"TunedAdModel","externalID":"c:@M@AutomixIQ@objc(cs)TunedAdModel"},"abstract":[{"text":"TunedAdModel models a Ad.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAdModel"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/init(adId:url:duration:name:artists:image:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/init(from:)"],"title":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/adDuration","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/adId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/artists","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/duration","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/image","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/name","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/url"],"title":"Instance Properties"}],"references":{"doc://org.cocoapods.AutomixIQ/SH":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/Se":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/SQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel/image":{"kind":"symbol","title":"image","navigatorTitle":[{"kind":"identifier","text":"image"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/image","url":"\/documentation\/automixiq\/tunedadmodel\/image","abstract":[{"text":"The artwork of this ad","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel/artists":{"title":"artists","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/artists","role":"symbol","url":"\/documentation\/automixiq\/tunedadmodel\/artists","type":"topic","abstract":[{"text":"The artists of this ad","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"artists"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedArtistModel","text":"TunedArtistModel"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"artists"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","role":"collection","url":"\/documentation\/automixiq","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel/adId":{"abstract":[{"type":"text","text":"The identifier of a track as an integer"}],"role":"symbol","type":"topic","url":"\/documentation\/automixiq\/tunedadmodel\/adid","title":"adId","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/adId","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"adId"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel/name":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/automixiq\/tunedadmodel\/name","abstract":[{"text":"The title of this Ad","type":"text"}],"title":"name","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"name"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/name"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel/adDuration":{"abstract":[{"type":"text","text":"Objective-C accessible member for the duration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/adDuration","title":"adDuration","type":"topic","role":"symbol","url":"\/documentation\/automixiq\/tunedadmodel\/adduration","navigatorTitle":[{"kind":"identifier","text":"adDuration"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel","kind":"symbol","url":"\/documentation\/automixiq\/tunedadmodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAdModel","kind":"identifier"}],"title":"TunedAdModel","role":"symbol","type":"topic","abstract":[{"type":"text","text":"TunedAdModel models a Ad."}],"navigatorTitle":[{"text":"TunedAdModel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel/url":{"navigatorTitle":[{"kind":"identifier","text":"url"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","url":"\/documentation\/automixiq\/tunedadmodel\/url","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/url","abstract":[{"text":"The url where this ad is downloaded from","type":"text"}],"title":"url","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel/init(from:)":{"title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/init(from:)","kind":"symbol","role":"symbol","url":"\/documentation\/automixiq\/tunedadmodel\/init(from:)","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel/duration":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/duration","url":"\/documentation\/automixiq\/tunedadmodel\/duration","abstract":[{"type":"text","text":"The duration of this ad"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","kind":"symbol","title":"duration"},"doc://org.cocoapods.AutomixIQ/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/SE":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel/init(adId:url:duration:name:artists:image:)":{"role":"symbol","navigatorTitle":[{"text":"initWithAdId:url:duration:name:artists:image:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Initialises an Ad Model","type":"text"}],"url":"\/documentation\/automixiq\/tunedadmodel\/init(adid:url:duration:name:artists:image:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/init(adId:url:duration:name:artists:image:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"adId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"artists","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedArtistModel","text":"TunedArtistModel","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(adId:url:duration:name:artists:image:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TunedAdModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"TunedAdModel","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"TunedAdModel","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/adDuration","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/adId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/artists","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/image","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/name","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/url"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel\/init(adId:url:duration:name:artists:image:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(cs)NSObject"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAdModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1image\/title","value":"image"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1image\/fragments","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1artists\/title","value":"artists"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1artists\/fragments","value":[{"text":"artists","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1adId\/title","value":"adId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1adId\/fragments","value":[{"kind":"identifier","text":"adId"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1adDuration\/title","value":"adDuration"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1adDuration\/fragments","value":[{"text":"adDuration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel\/title","value":"TunedAdModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel\/fragments","value":[{"text":"TunedAdModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel\/navigatorTitle","value":[{"text":"TunedAdModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1url\/fragments","value":[{"kind":"identifier","text":"url"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1init(adId:url:duration:name:artists:image:)\/title","value":"initWithAdId:url:duration:name:artists:image:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel~1init(adId:url:duration:name:artists:image:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdId:url:duration:name:artists:image:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}