{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bpm"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack"]]},"variants":[{"paths":["\/documentation\/socialradio\/automixsdkmixtapetrack\/bpm"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"The bpm of the track","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","title":"bpm","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bpm","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"s:11SocialRadio22AutomixSDKMixtapeTrackC3bpmSfSgvp","role":"symbol","modules":[{"name":"SocialRadio"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack\/bpm","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack/bpm":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack\/bpm","title":"bpm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bpm","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtapetrack\/bpm","abstract":[{"text":"The bpm of the track","type":"text"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack":{"url":"\/documentation\/socialradio\/automixsdkmixtapetrack","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack","role":"symbol","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"title":"AutomixSDKMixtapeTrack"}},"variantOverrides":[{"patch":[{"value":"AutomixSDKMixtapeTrack","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/navigatorTitle","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}