{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack\/trackDuration","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/socialradio\/automixsdkmixtapetrack\/trackduration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkmixtapetrack\/trackduration"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackDuration"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"trackDuration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"trackDuration","kind":"identifier"}],"title":"trackDuration","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtapeTrack(py)trackDuration","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"SocialRadio"}]},"abstract":[{"type":"text","text":"The track duration"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack/trackDuration":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack\/trackDuration","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackDuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}],"kind":"symbol","title":"trackDuration","url":"\/documentation\/socialradio\/automixsdkmixtapetrack\/trackduration","navigatorTitle":[{"kind":"identifier","text":"trackDuration"}],"abstract":[{"type":"text","text":"The track duration"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack":{"url":"\/documentation\/socialradio\/automixsdkmixtapetrack","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack","role":"symbol","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"title":"AutomixSDKMixtapeTrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"trackDuration","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"trackDuration"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackDuration"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack~1trackDuration\/title","value":"trackDuration"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack~1trackDuration\/fragments","value":[{"text":"trackDuration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/title","value":"AutomixSDKMixtapeTrack"},{"value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}