{"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates(py)notificationsDelegate","navigatorTitle":[{"kind":"identifier","text":"notificationsDelegate"}],"role":"symbol","modules":[{"name":"SocialRadio"}],"title":"notificationsDelegate","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notificationsDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerNotificationsDelegate","kind":"typeIdentifier","text":"SocialLayerNotificationsDelegate"},{"text":"?","kind":"text"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding notifications."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates"]]},"variants":[{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/notificationsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayerdelegates\/notificationsdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/notificationsDelegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationsDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerNotificationsDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","kind":"typeIdentifier","text":"SocialLayerNotificationsDelegate"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates/notificationsDelegate":{"title":"notificationsDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/notificationsDelegate","type":"topic","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding notifications.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"notificationsDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayerdelegates\/notificationsdelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationsDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialLayerNotificationsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerNotificationsDelegate"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerNotificationsDelegate":{"title":"SocialLayerNotificationsDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","type":"topic","abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding notifications."}],"role":"symbol","navigatorTitle":[{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayernotificationsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"role":"symbol","abstract":[{"text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions.","type":"text"},{"text":" ","type":"text"},{"text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc.","type":"text"},{"text":" ","type":"text"},{"text":"See each delegate’s documentation for details.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SocialLayerDelegates"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","url":"\/documentation\/socialradio\/sociallayerdelegates","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerDelegates"}],"title":"SocialLayerDelegates"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"notificationsDelegate","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"notificationsDelegate"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialLayerNotificationsDelegate","kind":"typeIdentifier","text":"id<SocialLayerNotificationsDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationsDelegate"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"notificationsDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1notificationsDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"notificationsDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1notificationsDelegate\/fragments"},{"op":"replace","value":"SocialLayerNotificationsDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/title"},{"op":"replace","value":[{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialLayerNotificationsDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/navigatorTitle"},{"op":"replace","value":"SocialLayerDelegates","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title"},{"op":"replace","value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments"},{"op":"replace","value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}