{"abstract":[{"type":"text","text":"true if the track is explicit, false otherwise"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel\/IsExplicit-bn1x","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"SocialRadio"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"s:11SocialRadio20AutomixSDKTrackModelC10IsExplicitSbSgvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IsExplicit","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?","kind":"text"}],"title":"IsExplicit"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsExplicit"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/socialradio\/automixsdktrackmodel\/isexplicit-bn1x"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/automixsdktrackmodel","kind":"symbol","title":"AutomixSDKTrackModel","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel/IsExplicit-bn1x":{"title":"IsExplicit","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"IsExplicit","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel\/IsExplicit-bn1x","url":"\/documentation\/socialradio\/automixsdktrackmodel\/isexplicit-bn1x","type":"topic","role":"symbol","abstract":[{"type":"text","text":"true if the track is explicit, false otherwise"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AutomixSDKTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/fragments","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/navigatorTitle","op":"replace"}]}]}