{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate"]]},"metadata":{"role":"symbol","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQPlaybackEventType"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"originalSessionId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQStatus","text":"AutomixIQStatus"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"playbackEventWithType:identifier:originalSessionId:status:"}],"symbolKind":"method","title":"playbackEvent(type:identifier:originalSessionId:status:)","externalID":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate(im)playbackEventWithType:identifier:originalSessionId:status:","roleHeading":"Instance Method"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Called when a playback event of AutomixIQ happens","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate\/playbackEvent(type:identifier:originalSessionId:status:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqstatusobserverdelegate\/playbackevent(type:identifier:originalsessionid:status:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqstatusobserverdelegate\/playbackevent(type:identifier:originalsessionid:status:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"playbackEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType","kind":"typeIdentifier","text":"AutomixIQPlaybackEventType","preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQPlaybackEventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"originalSessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","kind":"typeIdentifier","text":"AutomixIQStatus","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQStatus"},{"text":"?)","kind":"text"}]}]},{"parameters":[{"name":"type","content":[{"inlineContent":[{"text":"The playback event type","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The track identifier this event refers to","type":"text"}],"type":"paragraph"}],"name":"identifier"},{"content":[{"inlineContent":[{"text":"The initial session id for the track this event refers to. AutomixIQ may use more session ids as needed if the session expires and it needs more data.","type":"text"}],"type":"paragraph"}],"name":"originalSessionId"},{"content":[{"inlineContent":[{"text":"The current status of AutomixIQ","type":"text"}],"type":"paragraph"}],"name":"status"}],"kind":"parameters"}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","navigatorTitle":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"type":"topic","title":"AutomixIQStatusObserverDelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate/playbackEvent(type:identifier:originalSessionId:status:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate\/playbackEvent(type:identifier:originalSessionId:status:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQPlaybackEventType"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"originalSessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQStatus"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"playbackEventWithType:identifier:originalSessionId:status:","kind":"identifier"}],"type":"topic","title":"playbackEvent(type:identifier:originalSessionId:status:)","abstract":[{"type":"text","text":"Called when a playback event of AutomixIQ happens"}],"url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate\/playbackevent(type:identifier:originalsessionid:status:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"type":"topic","title":"AutomixIQStatus","abstract":[{"text":"AutomixIQStatus models the State of the AutomixIQ during playback.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatus"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","url":"\/documentation\/socialradio\/automixiqstatus"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType":{"navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqplaybackeventtype","title":"AutomixIQPlaybackEventType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"playbackEventWithType:identifier:originalSessionId:status:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"playbackEventWithType:identifier:originalSessionId:status:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"playbackEventWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQPlaybackEventType","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"identifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"identifier","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"originalSessionId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"originalSessionId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"status:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AutomixIQStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQStatus","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"The playback event type","type":"text"}]}]},{"name":"identifier","content":[{"inlineContent":[{"text":"The track identifier this event refers to","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The initial session id for the track this event refers to. AutomixIQ may use more session ids as needed if the session expires and it needs more data.","type":"text"}],"type":"paragraph"}],"name":"originalSessionId"},{"content":[{"inlineContent":[{"type":"text","text":"The current status of AutomixIQ"}],"type":"paragraph"}],"name":"status"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title","value":"AutomixIQStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate~1playbackEvent(type:identifier:originalSessionId:status:)\/title","value":"playbackEventWithType:identifier:originalSessionId:status:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate~1playbackEvent(type:identifier:originalSessionId:status:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playbackEventWithType:identifier:originalSessionId:status:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title","value":"AutomixIQStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/title","value":"AutomixIQPlaybackEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}]}]}]}