{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiomixtapetrack\/init"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack\/init"},"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioMixtapeTrack(im)init","symbolKind":"method","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack/init":{"type":"topic","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack\/init","url":"\/documentation\/socialradio\/socialradiomixtapetrack\/init","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack":{"url":"\/documentation\/socialradio\/socialradiomixtapetrack","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","kind":"symbol","type":"topic","role":"symbol","title":"SocialRadioMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","title":"SocialRadio","role":"collection","type":"topic","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/title","value":"SocialRadioMixtapeTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/fragments","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}