{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotLoadExplicitLyricsTrack"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotLoadExplicitLyricsTrack"},"metadata":{"navigatorTitle":[{"text":"ErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeCannotLoadExplicitLyricsTrack","modules":[{"name":"AutomixIQ"}],"roleHeading":"Case","role":"symbol","title":"ErrorCode.cannotLoadExplicitLyricsTrack"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/errorcode\/cannotloadexplicitlyricstrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode\/cannotloadexplicitlyricstrack"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"url":"\/documentation\/automixiq\/errorcode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","title":"ErrorCode","type":"topic","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotLoadExplicitLyricsTrack":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotLoadExplicitLyricsTrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotLoadExplicitLyricsTrack"}],"type":"topic","title":"ErrorCode.cannotLoadExplicitLyricsTrack","kind":"symbol","role":"symbol","url":"\/documentation\/automixiq\/errorcode\/cannotloadexplicitlyricstrack","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotLoadExplicitLyricsTrack"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","type":"topic","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"title":"AutomixIQ","url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCodeCannotLoadExplicitLyricsTrack"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeCannotLoadExplicitLyricsTrack"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodeCannotLoadExplicitLyricsTrack"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotLoadExplicitLyricsTrack\/title","op":"replace","value":"ErrorCodeCannotLoadExplicitLyricsTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotLoadExplicitLyricsTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeCannotLoadExplicitLyricsTrack"}]}]}]}