{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/accessing-waveform-data-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/accessing-waveform-data-article"]}],"metadata":{"roleHeading":"Article","modules":[{"name":"AutomixIQ"}],"title":"Accessing waveform data","role":"article"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"content":[{"type":"heading","anchor":"Overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"As AutomixIQ analyses tracks to generate transitions, it also makes waveform data available to be accessed by the client application for rendering on screen. Once data is available, the corresponding method is called "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate\/waveformDataAvailable(identifier:)"}]},{"type":"heading","anchor":"Setting-resolution","level":2,"text":"Setting resolution"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The resolution of the waveform data can be set with a maximum of 1024 points (defaults to 256) by calling the method"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setWaveformPointsPerTrack(_:)","isActive":true}],"type":"paragraph"}]}]},{"type":"heading","anchor":"Accessing-placeholder-data","level":2,"text":"Accessing placeholder data"},{"type":"paragraph","inlineContent":[{"text":"Whilst AutomixIQ is analysing the track and does not have the waveform data ready, you can access placeholder waveform data by calling ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/placeholderWaveformDataForTrack(identifier:)","isActive":true,"type":"reference"},{"text":". This function returns an ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel","isActive":true,"type":"reference"},{"text":" object.","type":"text"}]},{"type":"heading","anchor":"Accessing-waveform-data","level":2,"text":"Accessing waveform data"},{"type":"paragraph","inlineContent":[{"text":"When the waveform data is available, you can access it by calling ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/waveformDataForTrack(identifier:applyTransitions:)","isActive":true,"type":"reference"},{"text":". This function returns an ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel","isActive":true,"type":"reference"},{"text":" object.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"kind":"article","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Accessing-waveform-data-article"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQWaveformModel":{"abstract":[{"type":"text","text":"AutomixIQWaveformModel models the waveform of a track."}],"url":"\/documentation\/automixiq\/automixiqwaveformmodel","title":"AutomixIQWaveformModel","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQWaveformModel"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel","navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setWaveformPointsPerTrack(_:)":{"url":"\/documentation\/automixiq\/automixiq\/setwaveformpointspertrack(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setWaveformPointsPerTrack","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"setWaveformPointsPerTrack:","kind":"identifier"}],"kind":"symbol","title":"setWaveformPointsPerTrack(_:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setWaveformPointsPerTrack(_:)","abstract":[{"type":"text","text":"Sets the resolution of the waveform data for a track"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate/waveformDataAvailable(identifier:)":{"abstract":[{"type":"text","text":"Called when waveform data for a track is available"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waveformDataAvailable"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"waveformDataAvailableWithIdentifier:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate\/waveformDataAvailable(identifier:)","title":"waveformDataAvailable(identifier:)","url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate\/waveformdataavailable(identifier:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/placeholderWaveformDataForTrack(identifier:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/placeholderWaveformDataForTrack(identifier:)","type":"topic","kind":"symbol","role":"symbol","title":"placeholderWaveformDataForTrack(identifier:)","abstract":[{"type":"text","text":"Gets the placeholder waveform data for a track."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderWaveformDataForTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQWaveformModel","kind":"typeIdentifier","text":"AutomixIQWaveformModel"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"placeholderWaveformDataForTrackWithIdentifier:"}],"url":"\/documentation\/automixiq\/automixiq\/placeholderwaveformdatafortrack(identifier:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/waveformDataForTrack(identifier:applyTransitions:)":{"navigatorTitle":[{"kind":"identifier","text":"waveformDataForTrackWithIdentifier:applyTransitions:"}],"abstract":[{"text":"Gets the waveform data for a track.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/waveformDataForTrack(identifier:applyTransitions:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"applyTransitions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQWaveformModel"},{"text":"?","kind":"text"}],"url":"\/documentation\/automixiq\/automixiq\/waveformdatafortrack(identifier:applytransitions:)","title":"waveformDataForTrack(identifier:applyTransitions:)","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/title","value":"AutomixIQWaveformModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/fragments","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/navigatorTitle","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setWaveformPointsPerTrack(_:)\/title","value":"setWaveformPointsPerTrack:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setWaveformPointsPerTrack(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setWaveformPointsPerTrack:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate~1waveformDataAvailable(identifier:)\/title","value":"waveformDataAvailableWithIdentifier:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate~1waveformDataAvailable(identifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"waveformDataAvailableWithIdentifier:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1placeholderWaveformDataForTrack(identifier:)\/title","value":"placeholderWaveformDataForTrackWithIdentifier:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1placeholderWaveformDataForTrack(identifier:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"placeholderWaveformDataForTrackWithIdentifier:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1waveformDataForTrack(identifier:applyTransitions:)\/title","op":"replace","value":"waveformDataForTrackWithIdentifier:applyTransitions:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1waveformDataForTrack(identifier:applyTransitions:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"waveformDataForTrackWithIdentifier:applyTransitions:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}