{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqobjc\/waveformdatafortrack(withidentifier:applyentertransition:applyexittransition:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waveformDataForTrack"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applyEnterTransition"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applyExitTransition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/waveformDataForTrack(withIdentifier:applyEnterTransition:applyExitTransition:)"},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"applyEnterTransition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"applyExitTransition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel"},{"text":"?","kind":"text"}],"externalID":"c:objc(cs)AutomixIQObjC(im)waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","title":"waveformDataForTrack(withIdentifier:applyEnterTransition:applyExitTransition:)","symbolKind":"method","modules":[{"name":"SocialRadio"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","kind":"symbol","url":"\/documentation\/socialradio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","title":"AutomixIQObjC","url":"\/documentation\/socialradio\/automixiqobjc","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQObjC"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"AutomixIQWaveformModel models the waveform of a track."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","url":"\/documentation\/socialradio\/automixiqwaveformmodel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQWaveformModel"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"title":"AutomixIQWaveformModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC/waveformDataForTrack(withIdentifier:applyEnterTransition:applyExitTransition:)":{"type":"topic","title":"waveformDataForTrack(withIdentifier:applyEnterTransition:applyExitTransition:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waveformDataForTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applyEnterTransition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"applyExitTransition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"AutomixIQWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/socialradio\/automixiqobjc\/waveformdatafortrack(withidentifier:applyentertransition:applyexittransition:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/waveformDataForTrack(withIdentifier:applyEnterTransition:applyExitTransition:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","value":"AutomixIQWaveformModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}]}]}]}