{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSCopying","doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/init()"],"anchor":"Initializers","title":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canBack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canMixNow","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canOnOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canPlayPause","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canReorderTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canSeek","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canSkipToNext","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canSkipToPrevious","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/explicitLyricsFiltering","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/mixing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/muted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/nextTransitionDuration","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/normalisedVolume","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playSpeed","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playbackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playlist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playlistDiff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/readyToPlay","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/replayOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/vinylStartStop"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/copy(with:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/variableValue(_:)"],"generated":true},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/allStatusVariables()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/automixSDKStatusVariableName(_:)"],"anchor":"Type-Methods"}],"seeAlsoSections":[{"title":"Data models","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKGenericList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation"],"generated":true,"anchor":"Data-models"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKStatus","role":"symbol","roleHeading":"Class","title":"AutomixSDKStatus","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"modules":[{"name":"SocialRadio"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkstatus"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/canSkipToPrevious":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSkipToPrevious"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canSkipToPrevious","navigatorTitle":[{"kind":"identifier","text":"canSkipToPrevious"}],"title":"canSkipToPrevious","url":"\/documentation\/socialradio\/automixsdkstatus\/canskiptoprevious","kind":"symbol","type":"topic","abstract":[{"text":"Represents wether the engine is ready to skip to a previous track.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformBlob":{"role":"symbol","abstract":[{"type":"text","text":"AutomixSDKWaveformBlob models the data to create a waveform shape representing a track"}],"title":"AutomixSDKWaveformBlob","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"url":"\/documentation\/socialradio\/automixsdkwaveformblob","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/explicitLyricsFiltering":{"kind":"symbol","title":"explicitLyricsFiltering","role":"symbol","type":"topic","navigatorTitle":[{"text":"explicitLyricsFiltering","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/explicitlyricsfiltering","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"explicitLyricsFiltering","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/explicitLyricsFiltering"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/preferredTransitionDurationSeconds":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredTransitionDurationSeconds"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/preferredTransitionDurationSeconds","navigatorTitle":[{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"title":"preferredTransitionDurationSeconds","url":"\/documentation\/socialradio\/automixsdkstatus\/preferredtransitiondurationseconds","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the preferred Automix SDK transition duration, 0 if disabled."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/transitionStartTimeSeconds":{"kind":"symbol","title":"transitionStartTimeSeconds","role":"symbol","type":"topic","navigatorTitle":[{"text":"transitionStartTimeSeconds","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/transitionstarttimeseconds","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"transitionStartTimeSeconds","kind":"identifier"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Represents the track time in seconds in which the next (or current) transition starts"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/transitionStartTimeSeconds"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/requestedLoopTrackIdentifier":{"navigatorTitle":[{"text":"requestedLoopTrackIdentifier","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the track Automix SDK is currently looping, nil if none is looping"}],"title":"requestedLoopTrackIdentifier","url":"\/documentation\/socialradio\/automixsdkstatus\/requestedlooptrackidentifier","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/requestedLoopTrackIdentifier","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestedLoopTrackIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.SocialRadio/objc(pl)NSCopying":{"title":"NSCopying","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSCopying","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPluginMetadataModel":{"url":"\/documentation\/socialradio\/automixsdkpluginmetadatamodel","abstract":[{"type":"text","text":"AutomixSDKPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"type":"text","text":" "},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"title":"AutomixSDKPluginMetadataModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPluginMetadataModel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playingTrackIdentifier":{"navigatorTitle":[{"text":"playingTrackIdentifier","kind":"identifier"}],"abstract":[{"text":"Represents the identifier of the currently playing track if not mixing, the front track of the two mixed together if mixing. This would be the track a UI needs to show as playing or active.","type":"text"}],"title":"playingTrackIdentifier","url":"\/documentation\/socialradio\/automixsdkstatus\/playingtrackidentifier","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackIdentifier","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playlist":{"navigatorTitle":[{"text":"playlist","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the list of track identifiers in the order they will be played"}],"title":"playlist","url":"\/documentation\/socialradio\/automixsdkstatus\/playlist","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playlist","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playlist","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playingTrackTotalTime":{"kind":"symbol","title":"playingTrackTotalTime","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playingTrackTotalTime"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/playingtracktotaltime","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackTotalTime","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"abstract":[{"text":"Represents the total playback time of the playing track.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackTotalTime"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/requestedPauseTrackIdentifier":{"navigatorTitle":[{"text":"requestedPauseTrackIdentifier","kind":"identifier"}],"abstract":[{"text":"Represents the track Automix SDK is currently flagged to be paused at the end, nil if none is","type":"text"}],"title":"requestedPauseTrackIdentifier","url":"\/documentation\/socialradio\/automixsdkstatus\/requestedpausetrackidentifier","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/requestedPauseTrackIdentifier","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestedPauseTrackIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playlistDiff":{"kind":"symbol","title":"playlistDiff","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playlistDiff"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/playlistdiff","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : [","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKPlaylistOperation","kind":"typeIdentifier","text":"AutomixSDKPlaylistOperation"},{"text":"]]?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playlistDiff"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/muted":{"kind":"symbol","title":"muted","role":"symbol","type":"topic","navigatorTitle":[{"text":"muted","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/muted","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"muted"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Represents whether Automix SDK is muted or not. True if muted, false otherwise.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/muted"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeCounters":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters","navigatorTitle":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkmixtapecounters","title":"AutomixSDKMixtapeCounters","abstract":[{"type":"text","text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playing":{"navigatorTitle":[{"text":"playing","kind":"identifier"}],"abstract":[{"text":"Represents if sound is playing from Automix SDK, true if it is, false otherwise.","type":"text"}],"title":"playing","url":"\/documentation\/socialradio\/automixsdkstatus\/playing","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playing","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playing"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/canSkipToNext":{"kind":"symbol","title":"canSkipToNext","role":"symbol","type":"topic","navigatorTitle":[{"text":"canSkipToNext","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/canskiptonext","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"canSkipToNext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Represents wether the engine is ready to skip to the next track. If playing the last track of the playlist and “repeat” is off, this will be false.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canSkipToNext"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrackImage":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrackImage","navigatorTitle":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkmixtapetrackimage","title":"AutomixSDKMixtapeTrackImage","abstract":[{"text":"AutomixSDKMixtapeTrackImage models the image for a track in a mixtape","type":"text"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/canBack":{"navigatorTitle":[{"text":"canBack","kind":"identifier"}],"abstract":[{"text":"Represents wether the engine is ready to skip to the beginning of the current track.","type":"text"}],"title":"canBack","url":"\/documentation\/socialradio\/automixsdkstatus\/canback","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canBack","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canBack","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperation":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation","navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkplaylistoperation","title":"AutomixSDKPlaylistOperation","abstract":[{"type":"text","text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKUser":{"url":"\/documentation\/socialradio\/automixsdkuser","abstract":[{"type":"text","text":"AutomixSDKUser models a user"}],"title":"AutomixSDKUser","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKUser","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKUser"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKArtistModel":{"url":"\/documentation\/socialradio\/automixsdkartistmodel","abstract":[{"type":"text","text":"AutomixSDKArtistModel models an artist."}],"title":"AutomixSDKArtistModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKArtistModel","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKArtistModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/canPlayPause":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"canPlayPause","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canPlayPause","navigatorTitle":[{"text":"canPlayPause","kind":"identifier"}],"title":"canPlayPause","url":"\/documentation\/socialradio\/automixsdkstatus\/canplaypause","kind":"symbol","type":"topic","abstract":[{"text":"Represents wether the engine is ready to receive a play or pause command.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKGenericList":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKGenericList"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKGenericList","navigatorTitle":[{"text":"AutomixSDKGenericList","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkgenericlist","title":"AutomixSDKGenericList","abstract":[{"type":"text","text":"AutomixSDKGenericList models a list of things"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/copy(with:)":{"navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"abstract":[],"title":"copy(with:)","url":"\/documentation\/socialradio\/automixsdkstatus\/copy(with:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/copy(with:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copy"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Data-models-article":{"kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","url":"\/documentation\/socialradio\/data-models-article","title":"Data models","abstract":[{"text":"How data is passed to and from SocialRadio","type":"text"}],"role":"article","type":"topic"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse":{"url":"\/documentation\/socialradio\/tunedauthenticationresponse","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"title":"TunedAuthenticationResponse","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAuthenticationResponse"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playingTrackStreamingProgress":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"playingTrackStreamingProgress","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackStreamingProgress","navigatorTitle":[{"text":"playingTrackStreamingProgress","kind":"identifier"}],"title":"playingTrackStreamingProgress","url":"\/documentation\/socialradio\/automixsdkstatus\/playingtrackstreamingprogress","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the percentage of downloaded track."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/canReorderTracks":{"navigatorTitle":[{"kind":"identifier","text":"canReorderTracks"}],"abstract":[{"type":"text","text":"Represents wether the engine is ready to receive a reorder tracks command."}],"title":"canReorderTracks","url":"\/documentation\/socialradio\/automixsdkstatus\/canreordertracks","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canReorderTracks","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"canReorderTracks","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playingTrackOriginalSessionId":{"navigatorTitle":[{"kind":"identifier","text":"playingTrackOriginalSessionId"}],"abstract":[],"title":"playingTrackOriginalSessionId","url":"\/documentation\/socialradio\/automixsdkstatus\/playingtrackoriginalsessionid","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackOriginalSessionId","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackOriginalSessionId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/nextTransitionDuration":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"nextTransitionDuration","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/nextTransitionDuration","navigatorTitle":[{"kind":"identifier","text":"nextTransitionDuration"}],"title":"nextTransitionDuration","url":"\/documentation\/socialradio\/automixsdkstatus\/nexttransitionduration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the duration of the upcoming transition, 0 if no transition available"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"title":"AutomixSDKMixtapeTrack","url":"\/documentation\/socialradio\/automixsdkmixtapetrack","kind":"symbol","abstract":[{"text":"AutomixSDKMixtapeTrack models a track in a mixtape","type":"text"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playingTrackCurrentTime":{"navigatorTitle":[{"kind":"identifier","text":"playingTrackCurrentTime"}],"abstract":[{"type":"text","text":"Represents the current playback time of the playing track. If seeking, it reports seek landing time until jump is complete. This should be use on the UI."}],"title":"playingTrackCurrentTime","url":"\/documentation\/socialradio\/automixsdkstatus\/playingtrackcurrenttime","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackCurrentTime","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"playingTrackCurrentTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape":{"abstract":[{"text":"AutomixSDKMixtape models a mixtape","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape","role":"symbol","title":"AutomixSDKMixtape","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtape"}],"url":"\/documentation\/socialradio\/automixsdkmixtape","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtape"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/mixing":{"url":"\/documentation\/socialradio\/automixsdkstatus\/mixing","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mixing","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"mixing","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents if more than one track is concurrently playing from Automix SDK (mixing), true if it is, false otherwise."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/mixing","title":"mixing","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/canMixNow":{"navigatorTitle":[{"kind":"identifier","text":"canMixNow"}],"abstract":[{"text":"Represents wether the ‘next’ action would lead to a proper mix or a regular jumps. Depends on wether we had enough time to analyze the next track or not.","type":"text"}],"title":"canMixNow","url":"\/documentation\/socialradio\/automixsdkstatus\/canmixnow","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canMixNow","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canMixNow"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/vinylStartStop":{"kind":"symbol","title":"vinylStartStop","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"vinylStartStop"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/vinylstartstop","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"vinylStartStop","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Represents wether the engine does the vinyl sound effects when play\/pause"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/vinylStartStop"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/automixSDKStatusVariableName(_:)":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"automixSDKStatusVariableName:","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/automixsdkstatusvariablename(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixSDKStatusVariableName"},{"text":"(","kind":"text"},{"text":"AutomixSDKStatusVariable","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKStatusVariable"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","title":"automixSDKStatusVariableName(_:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/automixSDKStatusVariableName(_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus":{"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkstatus","role":"symbol","title":"AutomixSDKStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatus"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"title":"init()","url":"\/documentation\/socialradio\/automixsdkstatus\/init()","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playbackMode":{"kind":"symbol","title":"playbackMode","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playbackMode"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/playbackmode","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playbackMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playbackMode"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/readyToPlay":{"navigatorTitle":[{"kind":"identifier","text":"readyToPlay"}],"abstract":[{"type":"text","text":"Represents wether the mix is readsy to play or currently loading."}],"title":"readyToPlay","url":"\/documentation\/socialradio\/automixsdkstatus\/readytoplay","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/readyToPlay","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"readyToPlay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playSpeed":{"navigatorTitle":[{"kind":"identifier","text":"playSpeed"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkstatus\/playspeed","title":"playSpeed","role":"symbol","abstract":[{"type":"text","text":"Represents the Automix SDK play speed as a factor, from 0.5 to 2"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playSpeed","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playSpeed"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel":{"url":"\/documentation\/socialradio\/automixsdkwaveformmodel","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"title":"AutomixSDKWaveformModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKList":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKList"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKList"}],"url":"\/documentation\/socialradio\/automixsdklist","title":"AutomixSDKList","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/canSeek":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canSeek","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSeek"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"canSeek"}],"kind":"symbol","title":"canSeek","url":"\/documentation\/socialradio\/automixsdkstatus\/canseek","type":"topic","abstract":[{"type":"text","text":"Represents wether the engine is ready to receive a seek command."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/canOnOff":{"kind":"symbol","title":"canOnOff","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canOnOff"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/canonoff","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"canOnOff","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Represents if the SDK can be turned On or off. It is true if not other On \/ Off action is ongoing, flase otherwise. When this switch is true, On \/Off actions return an error."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canOnOff"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/normalisedVolume":{"kind":"symbol","title":"normalisedVolume","role":"symbol","type":"topic","navigatorTitle":[{"text":"normalisedVolume","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/normalisedvolume","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"normalisedVolume","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"abstract":[{"type":"text","text":"Represents the Automix SDK volume from 1 to 0. Note the device’s iOS Volume acts as a master over this one: if iOS’volume is 0, no sound will be put out regardless of this value."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/normalisedVolume"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/allStatusVariables()":{"navigatorTitle":[{"text":"allStatusVariables","kind":"identifier"}],"abstract":[],"title":"allStatusVariables()","url":"\/documentation\/socialradio\/automixsdkstatus\/allstatusvariables()","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/allStatusVariables()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"allStatusVariables","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel":{"url":"\/documentation\/socialradio\/automixsdktrackmodel","abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}],"title":"AutomixSDKTrackModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","type":"topic","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/variableValue(_:)":{"kind":"symbol","title":"variableValue(_:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"variableValue:"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/variablevalue(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"variableValue","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKStatusVariable","kind":"typeIdentifier","text":"AutomixSDKStatusVariable"},{"text":") -> ","kind":"text"},{"kind":"keyword","text":"Any"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/variableValue(_:)"},"doc://org.cocoapods.SocialRadio/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/mixId":{"kind":"symbol","title":"mixId","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mixId"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/mixid","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixId"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/mixId"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/replayOn":{"navigatorTitle":[{"text":"replayOn","kind":"identifier"}],"abstract":[{"text":"Represents wether the engine will replay the current playlist when it ends.","type":"text"}],"title":"replayOn","url":"\/documentation\/socialradio\/automixsdkstatus\/replayon","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/replayOn","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"replayOn","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/failedTrackLoadIdentifiers":{"kind":"symbol","title":"failedTrackLoadIdentifiers","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"url":"\/documentation\/socialradio\/automixsdkstatus\/failedtrackloadidentifiers","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failedTrackLoadIdentifiers"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"abstract":[{"type":"text","text":"Represents the tracks that failed loading for any reason"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/failedTrackLoadIdentifiers"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus/playingTrackIndex":{"navigatorTitle":[{"text":"playingTrackIndex","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the position of the currently playing track in the playlist if not mixing, the front track of the two mixed together if mixing. This would be the track a UI needs to show as playing or active."},{"text":" ","type":"text"},{"text":"If seeking, it reports seek landing track index until jump is complete. This should be use on the UI.","type":"text"}],"title":"playingTrackIndex","url":"\/documentation\/socialradio\/automixsdkstatus\/playingtrackindex","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackIndex","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playingTrackIndex","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeLite":{"url":"\/documentation\/socialradio\/automixsdkmixtapelite","abstract":[{"type":"text","text":"AutomixSDKMixtapeLite models a mixtape with the minimum required fields"}],"title":"AutomixSDKMixtapeLite","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeLite","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKStatus"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatus"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canBack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canMixNow","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canOnOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canPlayPause","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canReorderTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canSeek","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canSkipToNext","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/canSkipToPrevious","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/explicitLyricsFiltering","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/mixing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/muted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/nextTransitionDuration","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/normalisedVolume","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playSpeed","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playbackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playingTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playlist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/playlistDiff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/readyToPlay","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/replayOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/vinylStartStop"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/copy(with:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/init()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/variableValue(_:)"],"anchor":"Instance-Methods","generated":true},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/allStatusVariables()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus\/automixSDKStatusVariableName(_:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSCopying"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation"],"anchor":"Data-models","generated":true,"title":"Data models"}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatus"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canSkipToPrevious\/title","value":"canSkipToPrevious","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"canSkipToPrevious"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canSkipToPrevious\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/title","value":"AutomixSDKWaveformBlob"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1explicitLyricsFiltering\/title","op":"replace","value":"explicitLyricsFiltering"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1explicitLyricsFiltering\/fragments","value":[{"text":"explicitLyricsFiltering","kind":"identifier"}]},{"op":"replace","value":"preferredTransitionDurationSeconds","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1preferredTransitionDurationSeconds\/title"},{"value":[{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1preferredTransitionDurationSeconds\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1transitionStartTimeSeconds\/title","op":"replace","value":"transitionStartTimeSeconds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1transitionStartTimeSeconds\/fragments","value":[{"kind":"identifier","text":"transitionStartTimeSeconds"}]},{"op":"replace","value":"requestedLoopTrackIdentifier","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1requestedLoopTrackIdentifier\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1requestedLoopTrackIdentifier\/fragments","value":[{"text":"requestedLoopTrackIdentifier","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKPluginMetadataModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPluginMetadataModel\/title"},{"value":[{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPluginMetadataModel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPluginMetadataModel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}]},{"value":"playingTrackIdentifier","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackIdentifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackIdentifier\/fragments","value":[{"kind":"identifier","text":"playingTrackIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playlist\/title","value":"playlist"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playlist\/fragments","value":[{"kind":"identifier","text":"playlist"}],"op":"replace"},{"value":"playingTrackTotalTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackTotalTime\/title"},{"value":[{"kind":"identifier","text":"playingTrackTotalTime"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackTotalTime\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1requestedPauseTrackIdentifier\/title","value":"requestedPauseTrackIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1requestedPauseTrackIdentifier\/fragments","op":"replace","value":[{"text":"requestedPauseTrackIdentifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playlistDiff\/title","value":"playlistDiff","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playlistDiff\/fragments","value":[{"text":"playlistDiff","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1muted\/title","op":"replace","value":"muted"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1muted\/fragments","op":"replace","value":[{"kind":"identifier","text":"muted"}]},{"value":"AutomixSDKMixtapeCounters","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeCounters\/title"},{"value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeCounters\/fragments"},{"value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeCounters\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playing\/title","op":"replace","value":"playing"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playing\/fragments","value":[{"kind":"identifier","text":"playing"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canSkipToNext\/title","value":"canSkipToNext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canSkipToNext\/fragments","value":[{"kind":"identifier","text":"canSkipToNext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrackImage\/title","value":"AutomixSDKMixtapeTrackImage"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrackImage\/fragments","op":"replace","value":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}]},{"value":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrackImage\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canBack\/title","value":"canBack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canBack\/fragments","value":[{"text":"canBack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}]},{"value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/title","value":"AutomixSDKUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/fragments","value":[{"text":"AutomixSDKUser","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKUser"}]},{"value":"AutomixSDKArtistModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/title","op":"replace"},{"value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/navigatorTitle"},{"op":"replace","value":"canPlayPause","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canPlayPause\/title"},{"op":"replace","value":[{"text":"canPlayPause","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canPlayPause\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1copy(with:)\/title","value":"copyWithZone:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1copy(with:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/title","value":"TunedAuthenticationResponse"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/fragments","op":"replace","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/navigatorTitle","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}]},{"op":"replace","value":"playingTrackStreamingProgress","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackStreamingProgress\/title"},{"op":"replace","value":[{"text":"playingTrackStreamingProgress","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackStreamingProgress\/fragments"},{"value":"canReorderTracks","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canReorderTracks\/title","op":"replace"},{"value":[{"kind":"identifier","text":"canReorderTracks"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canReorderTracks\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackOriginalSessionId\/title","op":"replace","value":"playingTrackOriginalSessionId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackOriginalSessionId\/fragments","value":[{"kind":"identifier","text":"playingTrackOriginalSessionId"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1nextTransitionDuration\/title","value":"nextTransitionDuration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1nextTransitionDuration\/fragments","value":[{"kind":"identifier","text":"nextTransitionDuration"}]},{"value":"AutomixSDKMixtapeTrack","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/fragments","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}]},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/navigatorTitle"},{"value":"playingTrackCurrentTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackCurrentTime\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackCurrentTime\/fragments","value":[{"kind":"identifier","text":"playingTrackCurrentTime"}]},{"value":"AutomixSDKMixtape","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/title"},{"value":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtape"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1mixing\/title","value":"mixing","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1mixing\/fragments","op":"replace","value":[{"kind":"identifier","text":"mixing"}]},{"value":"canMixNow","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canMixNow\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canMixNow\/fragments","value":[{"text":"canMixNow","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1vinylStartStop\/title","value":"vinylStartStop"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1vinylStartStop\/fragments","value":[{"text":"vinylStartStop","kind":"identifier"}]},{"op":"replace","value":"automixSDKStatusVariableName:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1automixSDKStatusVariableName(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1automixSDKStatusVariableName(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"automixSDKStatusVariableName:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus\/title","value":"AutomixSDKStatus"},{"value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus\/navigatorTitle","value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"op":"replace"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1init()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playbackMode\/title","value":"playbackMode","op":"replace"},{"value":[{"kind":"identifier","text":"playbackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playbackMode\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1readyToPlay\/title","op":"replace","value":"readyToPlay"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1readyToPlay\/fragments","value":[{"kind":"identifier","text":"readyToPlay"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playSpeed\/title","value":"playSpeed"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playSpeed\/fragments","value":[{"text":"playSpeed","kind":"identifier"}]},{"value":"AutomixSDKWaveformModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}]},{"value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKList\/title","value":"AutomixSDKList"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKList\/fragments","value":[{"text":"AutomixSDKList","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKList"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKList\/navigatorTitle","op":"replace"},{"value":"canSeek","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canSeek\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canSeek\/fragments","op":"replace","value":[{"text":"canSeek","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canOnOff\/title","value":"canOnOff","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1canOnOff\/fragments","value":[{"kind":"identifier","text":"canOnOff"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1normalisedVolume\/title","value":"normalisedVolume","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1normalisedVolume\/fragments","value":[{"text":"normalisedVolume","kind":"identifier"}]},{"value":"allStatusVariables","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1allStatusVariables()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"allStatusVariables","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1allStatusVariables()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}]},{"op":"replace","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1variableValue(_:)\/title","value":"variableValue:"},{"value":[{"kind":"text","text":"- "},{"text":"variableValue:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1variableValue(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1mixId\/title","op":"replace","value":"mixId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1mixId\/fragments","value":[{"text":"mixId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1replayOn\/title","value":"replayOn","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"replayOn"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1replayOn\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1failedTrackLoadIdentifiers\/title","value":"failedTrackLoadIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1failedTrackLoadIdentifiers\/fragments","value":[{"kind":"identifier","text":"failedTrackLoadIdentifiers"}]},{"value":"playingTrackIndex","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackIndex\/title"},{"value":[{"text":"playingTrackIndex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus~1playingTrackIndex\/fragments"},{"value":"AutomixSDKMixtapeLite","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeLite\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeLite\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeLite\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"op":"replace"}]}]}