{"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/init(apiKey:country:storeId:applicationId:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/apiKey","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/applicationId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/country","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/storeId"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkconfig"]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"],"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs","title":"Initializing SocialRadio for use with Tuned Global’s APIs"}],"metadata":{"modules":[{"name":"SocialRadio"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKConfig"}],"roleHeading":"Class","symbolKind":"class","title":"AutomixSDKConfig","navigatorTitle":[{"text":"AutomixSDKConfig","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKConfig","role":"symbol"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedMusicCacheDelegate":{"role":"symbol","abstract":[{"text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","title":"TunedMusicCacheDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"url":"\/documentation\/socialradio\/tunedmusiccachedelegate","kind":"symbol","navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKUIConfig"}],"abstract":[],"title":"RadioSDKUIConfig","role":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig/storeId":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"storeId"}],"type":"topic","title":"storeId","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/storeId","url":"\/documentation\/socialradio\/automixsdkconfig\/storeid","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperationType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}],"type":"topic","abstract":[],"url":"\/documentation\/socialradio\/automixsdkplaylistoperationtype","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","title":"AutomixSDKPlaylistOperationType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackMode":{"url":"\/documentation\/socialradio\/automixsdkplaybackmode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"navigatorTitle":[{"text":"AutomixSDKPlaybackMode","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQ playback mode"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","title":"AutomixSDKPlaybackMode","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig/country":{"kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/automixsdkconfig\/country","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"country","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"country","kind":"identifier"}],"title":"country","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/country"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig/applicationId":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"applicationId"}],"type":"topic","title":"applicationId","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/applicationId","url":"\/documentation\/socialradio\/automixsdkconfig\/applicationid","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-article":{"title":"Initializing SocialRadio","role":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","type":"topic","url":"\/documentation\/socialradio\/initialising-socialradio-article","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}],"kind":"article"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKFeatureSetConfig":{"title":"RadioSDKFeatureSetConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/radiosdkfeaturesetconfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable":{"title":"AutomixSDKStatusVariable","url":"\/documentation\/socialradio\/automixsdkstatusvariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"title":"TunedRestDelegate","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedRestDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","url":"\/documentation\/socialradio\/tunedrestdelegate","kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig/init(apiKey:country:storeId:applicationId:)":{"type":"topic","url":"\/documentation\/socialradio\/automixsdkconfig\/init(apikey:country:storeid:applicationid:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithApiKey:country:storeId:applicationId:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"title":"init(apiKey:country:storeId:applicationId:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/init(apiKey:country:storeId:applicationId:)","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKConfig","kind":"identifier"}],"title":"AutomixSDKConfig","navigatorTitle":[{"text":"AutomixSDKConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","url":"\/documentation\/socialradio\/automixsdkconfig","kind":"symbol","type":"topic","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate":{"url":"\/documentation\/socialradio\/radiouidelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioUIDelegate"}],"navigatorTitle":[{"text":"RadioUIDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate","title":"RadioUIDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel":{"type":"topic","url":"\/documentation\/socialradio\/automixsdkloglevel","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","title":"AutomixSDKLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKLogLevel"}],"abstract":[{"type":"text","text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKConfig":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDKConfig","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/radiosdkconfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","title":"RadioSDKConfig","navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate":{"type":"topic","url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","title":"AutomixSDKStatusObserverDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate":{"title":"AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/automixsdkstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","type":"topic","abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig/apiKey":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"apiKey"}],"title":"apiKey","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/apiKey","url":"\/documentation\/socialradio\/automixsdkconfig\/apikey"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixSDKConfig","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixSDKConfig","kind":"identifier"}]},{"op":"replace","value":[{"text":"AutomixSDKConfig","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/apiKey","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/applicationId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/country","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/storeId"],"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig\/init(apiKey:country:storeId:applicationId:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"value":[{"title":"Initializing SocialRadio for use with Tuned Global’s APIs","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"],"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKConfig"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/fragments","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},{"op":"replace","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title","op":"replace","value":"RadioSDKUIConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}]},{"op":"replace","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1storeId\/title","op":"replace","value":"storeId"},{"value":[{"text":"storeId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1storeId\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/title","value":"AutomixSDKPlaylistOperationType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/navigatorTitle","value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/title","value":"AutomixSDKPlaybackMode"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKPlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1country\/title","op":"replace","value":"country"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1country\/fragments","value":[{"kind":"identifier","text":"country"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1applicationId\/title","value":"applicationId","op":"replace"},{"value":[{"kind":"identifier","text":"applicationId"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1applicationId\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/title","value":"RadioSDKFeatureSetConfig"},{"op":"replace","value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/navigatorTitle","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","value":"TunedRestDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle"},{"op":"replace","value":"initWithApiKey:country:storeId:applicationId:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1init(apiKey:country:storeId:applicationId:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1init(apiKey:country:storeId:applicationId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithApiKey:country:storeId:applicationId:","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/title","value":"RadioUIDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/fragments","value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/title","op":"replace","value":"AutomixSDKLogLevel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/title","value":"RadioSDKConfig","op":"replace"},{"value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"RadioSDKConfig"}]},{"op":"replace","value":"AutomixSDKStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate"},{"op":"replace","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1apiKey\/title","op":"replace","value":"apiKey"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig~1apiKey\/fragments","value":[{"kind":"identifier","text":"apiKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}