{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]}]},{"kind":"parameters","parameters":[{"name":"trackPlayStart","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Start of track playback"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track has played for 5 seconds"}]}],"name":"trackPlayPlayed5Secs"},{"name":"trackPlayHeartbeat30Secs","content":[{"inlineContent":[{"text":"Track has played for 30 seconds, this is called every 30 seconds of playback","type":"text"}],"type":"paragraph"}]},{"name":"trackPlayStartMixingIntoNext","content":[{"inlineContent":[{"type":"text","text":"Track has started transitioning into the next track"}],"type":"paragraph"}]},{"name":"trackPlaySkipped","content":[{"inlineContent":[{"type":"text","text":"Track has been skipped to the next track (this is also called when seeking through the same track)"}],"type":"paragraph"}]},{"name":"trackPlayFinished","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track has finished playback (if transitioning this is called at the end of the transition for the first track)"}]}]},{"name":"mixPlaybackEnded","content":[{"type":"paragraph","inlineContent":[{"text":"Queue has reached the end and there are no more tracks to play","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkplaybackeventtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixsdkplaybackeventtype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"externalID":"c:@M@SocialRadio@E@AutomixSDKPlaybackEventType","modules":[{"name":"SocialRadio"}],"roleHeading":"Enumeration","role":"symbol","title":"AutomixSDKPlaybackEventType","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH","doc:\/\/org.cocoapods.SocialRadio\/SY"],"type":"conformsTo"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Persistency-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLog","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLogAttributes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLogID","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLog","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLogAttributes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLogID"],"anchor":"Persistency","generated":true,"title":"Persistency"}],"abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTransitionLogAttributes":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixSDKTransitionLogAttributes","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/automixsdktransitionlogattributes","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLogAttributes","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLogAttributes","kind":"identifier"}],"title":"AutomixSDKTransitionLogAttributes"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/RawRepresentable-Implementations","role":"collectionGroup"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/trackPlayPlayed5Secs":{"role":"symbol","kind":"symbol","title":"AutomixSDKPlaybackEventType.trackPlayPlayed5Secs","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackPlayPlayed5Secs","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs"}],"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/trackplayplayed5secs"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Persistency-article":{"kind":"article","title":"Persistency","type":"topic","url":"\/documentation\/socialradio\/persistency-article","abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Persistency-article","role":"article"},"doc://org.cocoapods.SocialRadio/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTransitionLogID":{"type":"topic","kind":"symbol","title":"AutomixSDKTransitionLogID","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTransitionLogID"}],"url":"\/documentation\/socialradio\/automixsdktransitionlogid","role":"symbol","navigatorTitle":[{"text":"AutomixSDKTransitionLogID","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLogID"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlayLogID":{"kind":"symbol","title":"AutomixSDKPlayLogID","type":"topic","url":"\/documentation\/socialradio\/automixsdkplaylogid","navigatorTitle":[{"text":"AutomixSDKPlayLogID","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLogID","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlayLogID"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/mixPlaybackEnded":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","type":"topic","role":"symbol","url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/mixplaybackended","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlaybackEnded"}],"abstract":[],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"title":"AutomixSDKPlaybackEventType.mixPlaybackEnded"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/trackPlayFinished":{"type":"topic","title":"AutomixSDKPlaybackEventType.trackPlayFinished","abstract":[],"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/trackplayfinished","kind":"symbol","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayFinished"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlayLogAttributes":{"kind":"symbol","title":"AutomixSDKPlayLogAttributes","type":"topic","url":"\/documentation\/socialradio\/automixsdkplaylogattributes","navigatorTitle":[{"text":"AutomixSDKPlayLogAttributes","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLogAttributes","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlayLogAttributes","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/init(rawvalue:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/init(rawValue:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://org.cocoapods.SocialRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/trackPlayStart":{"title":"AutomixSDKPlaybackEventType.trackPlayStart","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayStart","kind":"symbol","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayStart"}],"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/trackplaystart"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/trackPlaySkipped":{"role":"symbol","kind":"symbol","title":"AutomixSDKPlaybackEventType.trackPlaySkipped","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlaySkipped","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlaySkipped"}],"type":"topic","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/trackplayskipped"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTransitionLog":{"url":"\/documentation\/socialradio\/automixsdktransitionlog","title":"AutomixSDKTransitionLog","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLog","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTransitionLog"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLog"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlayLog":{"kind":"symbol","title":"AutomixSDKPlayLog","type":"topic","url":"\/documentation\/socialradio\/automixsdkplaylog","navigatorTitle":[{"text":"AutomixSDKPlayLog","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLog","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlayLog"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/trackPlayStartMixingIntoNext":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackPlayStartMixingIntoNext","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext"}],"type":"topic","kind":"symbol","title":"AutomixSDKPlaybackEventType.trackPlayStartMixingIntoNext","url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/trackplaystartmixingintonext","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/trackPlayHeartbeat30Secs":{"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/trackplayheartbeat30secs","role":"symbol","abstract":[],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayHeartbeat30Secs","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs","title":"AutomixSDKPlaybackEventType.trackPlayHeartbeat30Secs","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"title":"AutomixSDKPlaybackEventType","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/Equatable-Implementations","kind":"article","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/socialradio\/automixsdkplaybackeventtype\/equatable-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"AutomixSDKPlaybackEventType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Persistency-article"],"title":"Persistency","generated":true,"anchor":"Persistency"}]},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayPlayed5Secs\/title"},{"value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayPlayed5Secs\/fragments"},{"op":"replace","value":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayFinished\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayFinished"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayFinished\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayFinished"}]},{"value":"AutomixSDKPlaybackEventTypeTrackPlayStart","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayStart\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayStart\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayStart"}]},{"op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayStartMixingIntoNext\/title","op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayStartMixingIntoNext\/fragments","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}]},{"value":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayHeartbeat30Secs\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType~1trackPlayHeartbeat30Secs\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/navigatorTitle","op":"replace"}]}]}