{"metadata":{"modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(pl)RadioUIDelegate","title":"RadioUIDelegate","role":"symbol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioUIDelegate"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"RadioUIDelegate"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioUIDelegate"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/radiouidelegate"]},{"paths":["\/documentation\/socialradio\/radiouidelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"],"title":"Initializing SocialRadio for use with Tuned Global’s APIs","generated":true,"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate"},"abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/didCloseRadioUI(userInitiated:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/didDismissRadioUI(userInitiated:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/isTrackLiked(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/presentAuthentication(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/presentProfile(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/presentTracklist(filterOutExplicitContent:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/setTrackLiked(identifier:liked:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/willCloseRadioUI(userInitiated:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/willDismissRadioUI(userInitiated:)"],"generated":true}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/setTrackLiked(identifier:liked:completion:)":{"title":"setTrackLiked(identifier:liked:completion:)","required":true,"url":"\/documentation\/socialradio\/radiouidelegate\/settrackliked(identifier:liked:completion:)","type":"topic","navigatorTitle":[{"text":"setTrackLikedWithIdentifier:liked:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setTrackLiked","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"liked"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"success","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/setTrackLiked(identifier:liked:completion:)","abstract":[{"type":"text","text":"Called by AutomixSDK when it needs add or remove a track with a given identifier from liked"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate":{"url":"\/documentation\/socialradio\/radiouidelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioUIDelegate"}],"navigatorTitle":[{"text":"RadioUIDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate","title":"RadioUIDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKConfig":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDKConfig","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/radiosdkconfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","title":"RadioSDKConfig","navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKFeatureSetConfig":{"title":"RadioSDKFeatureSetConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/radiosdkfeaturesetconfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate":{"type":"topic","url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","title":"AutomixSDKStatusObserverDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperationType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}],"type":"topic","abstract":[],"url":"\/documentation\/socialradio\/automixsdkplaylistoperationtype","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","title":"AutomixSDKPlaylistOperationType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/presentProfile(identifier:completion:)":{"navigatorTitle":[{"text":"presentProfileWithIdentifier:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/presentProfile(identifier:completion:)","kind":"symbol","title":"presentProfile(identifier:completion:)","type":"topic","url":"\/documentation\/socialradio\/radiouidelegate\/presentprofile(identifier:completion:)","required":true,"abstract":[{"type":"text","text":"Called by AutomixSDK when it wishes to present UI with a user’s information"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentProfile"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedMusicCacheDelegate":{"role":"symbol","abstract":[{"text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","title":"TunedMusicCacheDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"url":"\/documentation\/socialradio\/tunedmusiccachedelegate","kind":"symbol","navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-article":{"title":"Initializing SocialRadio","role":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","type":"topic","url":"\/documentation\/socialradio\/initialising-socialradio-article","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}],"kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate":{"title":"AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/automixsdkstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","type":"topic","abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/presentTracklist(filterOutExplicitContent:completion:)":{"title":"presentTracklist(filterOutExplicitContent:completion:)","required":true,"url":"\/documentation\/socialradio\/radiouidelegate\/presenttracklist(filteroutexplicitcontent:completion:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentTracklistWithFilterOutExplicitContent:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentTracklist","kind":"identifier"},{"text":"(","kind":"text"},{"text":"filterOutExplicitContent","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"tracks","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"playlistName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/presentTracklist(filterOutExplicitContent:completion:)","abstract":[{"text":"Called by AutomixSDK when it wishes to present UI to select one or many tracks","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKUIConfig"}],"abstract":[],"title":"RadioSDKUIConfig","role":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"title":"TunedRestDelegate","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedRestDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","url":"\/documentation\/socialradio\/tunedrestdelegate","kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel":{"type":"topic","url":"\/documentation\/socialradio\/automixsdkloglevel","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","title":"AutomixSDKLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKLogLevel"}],"abstract":[{"type":"text","text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/willDismissRadioUI(userInitiated:)":{"navigatorTitle":[{"text":"willDismissRadioUIWithUserInitiated:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/willDismissRadioUI(userInitiated:)","kind":"symbol","title":"willDismissRadioUI(userInitiated:)","type":"topic","url":"\/documentation\/socialradio\/radiouidelegate\/willdismissradioui(userinitiated:)","required":true,"abstract":[{"type":"text","text":"Called by AutomixSDK when the Radio UI about to be dismissed"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"willDismissRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable":{"title":"AutomixSDKStatusVariable","url":"\/documentation\/socialradio\/automixsdkstatusvariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/didDismissRadioUI(userInitiated:)":{"title":"didDismissRadioUI(userInitiated:)","required":true,"url":"\/documentation\/socialradio\/radiouidelegate\/diddismissradioui(userinitiated:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didDismissRadioUIWithUserInitiated:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didDismissRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/didDismissRadioUI(userInitiated:)","abstract":[{"type":"text","text":"Called by AutomixSDK when the Radio UI is dismissed"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/isTrackLiked(identifier:completion:)":{"navigatorTitle":[{"text":"isTrackLikedWithIdentifier:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/isTrackLiked(identifier:completion:)","kind":"symbol","title":"isTrackLiked(identifier:completion:)","type":"topic","url":"\/documentation\/socialradio\/radiouidelegate\/istrackliked(identifier:completion:)","required":true,"abstract":[{"text":"Called by AutomixSDK when it needs to know wether a track is liked or not","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTrackLiked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"isLiked","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackMode":{"url":"\/documentation\/socialradio\/automixsdkplaybackmode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"navigatorTitle":[{"text":"AutomixSDKPlaybackMode","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQ playback mode"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","title":"AutomixSDKPlaybackMode","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/presentAuthentication(completion:)":{"title":"presentAuthentication(completion:)","required":true,"url":"\/documentation\/socialradio\/radiouidelegate\/presentauthentication(completion:)","type":"topic","navigatorTitle":[{"text":"presentAuthenticationWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentAuthentication","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"success"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/presentAuthentication(completion:)","abstract":[{"text":"Called by AutomixSDK when it wishes to present UI to authenticate a user","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/didCloseRadioUI(userInitiated:)":{"url":"\/documentation\/socialradio\/radiouidelegate\/didcloseradioui(userinitiated:)","title":"didCloseRadioUI(userInitiated:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/didCloseRadioUI(userInitiated:)","kind":"symbol","abstract":[{"text":"Called by AutomixSDK when the Radio UI is closed","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCloseRadioUI"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didCloseRadioUIWithUserInitiated:"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate/willCloseRadioUI(userInitiated:)":{"type":"topic","url":"\/documentation\/socialradio\/radiouidelegate\/willcloseradioui(userinitiated:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/willCloseRadioUI(userInitiated:)","navigatorTitle":[{"kind":"identifier","text":"willCloseRadioUIWithUserInitiated:"}],"abstract":[{"type":"text","text":"Called by AutomixSDK when the Radio UI is closed"}],"title":"willCloseRadioUI(userInitiated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKConfig","kind":"identifier"}],"title":"AutomixSDKConfig","navigatorTitle":[{"text":"AutomixSDKConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","url":"\/documentation\/socialradio\/automixsdkconfig","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"RadioUIDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"RadioUIDelegate","kind":"identifier"}]},{"value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/didCloseRadioUI(userInitiated:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/didDismissRadioUI(userInitiated:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/isTrackLiked(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/presentAuthentication(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/presentProfile(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/presentTracklist(filterOutExplicitContent:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/setTrackLiked(identifier:liked:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/willCloseRadioUI(userInitiated:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate\/willDismissRadioUI(userInitiated:)"],"generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":[{"generated":true,"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"],"title":"Initializing SocialRadio for use with Tuned Global’s APIs"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioUIDelegate"}]}]}},{"value":"setTrackLikedWithIdentifier:liked:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1setTrackLiked(identifier:liked:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTrackLikedWithIdentifier:liked:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1setTrackLiked(identifier:liked:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/title","value":"RadioUIDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/fragments","value":[{"kind":"identifier","text":"RadioUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/navigatorTitle","value":[{"text":"RadioUIDelegate","kind":"identifier"}]},{"value":"RadioSDKConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/title"},{"value":[{"kind":"identifier","text":"RadioSDKConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"RadioSDKConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/navigatorTitle","op":"replace"},{"value":"RadioSDKFeatureSetConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/fragments","op":"replace","value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/title","op":"replace","value":"AutomixSDKStatusObserverDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"op":"replace","value":"AutomixSDKPlaylistOperationType","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/navigatorTitle","value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1presentProfile(identifier:completion:)\/title","value":"presentProfileWithIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1presentProfile(identifier:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentProfileWithIdentifier:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate"},{"value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/fragments"},{"value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/navigatorTitle"},{"value":"presentTracklistWithFilterOutExplicitContent:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1presentTracklist(filterOutExplicitContent:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentTracklistWithFilterOutExplicitContent:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1presentTracklist(filterOutExplicitContent:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title","value":"RadioSDKUIConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","op":"replace","value":"TunedRestDelegate"},{"value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel"},{"value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/navigatorTitle","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1willDismissRadioUI(userInitiated:)\/title","value":"willDismissRadioUIWithUserInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1willDismissRadioUI(userInitiated:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willDismissRadioUIWithUserInitiated:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/fragments","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1didDismissRadioUI(userInitiated:)\/title","value":"didDismissRadioUIWithUserInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1didDismissRadioUI(userInitiated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didDismissRadioUIWithUserInitiated:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1isTrackLiked(identifier:completion:)\/title","value":"isTrackLikedWithIdentifier:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isTrackLikedWithIdentifier:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1isTrackLiked(identifier:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/title","op":"replace","value":"AutomixSDKPlaybackMode"},{"value":[{"text":"AutomixSDKPlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}]},{"value":"presentAuthenticationWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1presentAuthentication(completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1presentAuthentication(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentAuthenticationWithCompletion:"}],"op":"replace"},{"op":"replace","value":"didCloseRadioUIWithUserInitiated:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1didCloseRadioUI(userInitiated:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1didCloseRadioUI(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"}]},{"op":"replace","value":"willCloseRadioUIWithUserInitiated:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1willCloseRadioUI(userInitiated:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate~1willCloseRadioUI(userInitiated:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willCloseRadioUIWithUserInitiated:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/title","value":"AutomixSDKConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/fragments","op":"replace","value":[{"text":"AutomixSDKConfig","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/navigatorTitle"}]}]}