{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/radiosdkobjc"]}],"sections":[],"seeAlsoSections":[{"title":"RadioSDK singleton","anchor":"RadioSDK-singleton","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKObjC"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKObjC"}],"externalID":"c:objc(cs)RadioSDKObjC","navigatorTitle":[{"text":"RadioSDKObjC","kind":"identifier"}],"title":"RadioSDKObjC","modules":[{"name":"SocialRadio"}],"roleHeading":"Class","role":"symbol"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/add(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/endRadioSession(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/forceRefreshCredentials(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:isRecording:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/getAutomixStreamingDelegate()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/getLiveShows(withLimit:start:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/isAudioDeviceActiveOrRecording(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/joinLiveMixtape(withIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/play(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/radioUIViewController()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/remove(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/reportMixtape(withIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/reportUser(withIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/setMusicCacheDelegate(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/setRecordingAudioDataWithFrames(_:numberOfChannels:audioPCMBuffer:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/stopEngine()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/initialised()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/instance()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/internetAvailable()"],"anchor":"Type-Methods"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"type":"conformsTo"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/joinLiveMixtape(withIdentifier:completion:)":{"abstract":[],"url":"\/documentation\/socialradio\/radiosdkobjc\/joinlivemixtape(withidentifier:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/joinLiveMixtape(withIdentifier:completion:)","kind":"symbol","role":"symbol","title":"joinLiveMixtape(withIdentifier:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"joinLiveMixtape","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?, "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/play(completion:)":{"abstract":[],"type":"topic","kind":"symbol","title":"play(completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/play(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"url":"\/documentation\/socialradio\/radiosdkobjc\/play(completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/forceRefreshCredentials(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forceRefreshCredentials"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/forceRefreshCredentials(completion:)","type":"topic","abstract":[],"role":"symbol","title":"forceRefreshCredentials(completion:)","url":"\/documentation\/socialradio\/radiosdkobjc\/forcerefreshcredentials(completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/internetAvailable()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/internetAvailable()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"internetAvailable"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"internetAvailable()","url":"\/documentation\/socialradio\/radiosdkobjc\/internetavailable()","role":"symbol","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRadioSession"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel"},{"kind":"text","text":"]?, "},{"text":"playTrackIndex","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"type":"topic","title":"startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/radiosdkobjc\/startradiosession(withidentifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/isAudioDeviceActiveOrRecording(_:)":{"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAudioDeviceActiveOrRecording"},{"text":"(","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","text":"ObjCBool","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/isAudioDeviceActiveOrRecording(_:)","title":"isAudioDeviceActiveOrRecording(_:)","url":"\/documentation\/socialradio\/radiosdkobjc\/isaudiodeviceactiveorrecording(_:)","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/instance()":{"type":"topic","url":"\/documentation\/socialradio\/radiosdkobjc\/instance()","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/instance()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"instance","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)RadioSDKObjC","text":"RadioSDKObjC"},{"kind":"text","text":"?"}],"title":"instance()","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/stopEngine()":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopEngine","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/stopEngine()","title":"stopEngine()","url":"\/documentation\/socialradio\/radiosdkobjc\/stopengine()","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/remove(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"(any ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/remove(_:)","type":"topic","url":"\/documentation\/socialradio\/radiosdkobjc\/remove(_:)","abstract":[],"kind":"symbol","role":"symbol","title":"remove(_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/setMusicCacheDelegate(_:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/setMusicCacheDelegate(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMusicCacheDelegate","kind":"identifier"},{"kind":"text","text":"((any "},{"text":"TunedMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate"},{"text":")?)","kind":"text"}],"url":"\/documentation\/socialradio\/radiosdkobjc\/setmusiccachedelegate(_:)","title":"setMusicCacheDelegate(_:)","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/add(_:)":{"url":"\/documentation\/socialradio\/radiosdkobjc\/add(_:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","title":"add(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"add"},{"kind":"text","text":"(any "},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/add(_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)":{"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notifyFollowers"},{"text":"(","kind":"text"},{"text":"withUserIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"body","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"objectType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"objectId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)","title":"notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)","url":"\/documentation\/socialradio\/radiosdkobjc\/notifyfollowers(withuseridentifier:title:body:objecttype:objectid:completion:)","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC","title":"RadioSDKObjC","url":"\/documentation\/socialradio\/radiosdkobjc","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKObjC"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKObjC"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RadioSDKConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedDelegate"},{"text":": any ","kind":"text"},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate"},{"text":", ","kind":"text"},{"text":"radioUIDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"RadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)RadioUIDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"url":"\/documentation\/socialradio\/radiosdkobjc\/initialize(with:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)","title":"initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/reportUser(withIdentifier:completion:)":{"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"reportUser","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/reportUser(withIdentifier:completion:)","title":"reportUser(withIdentifier:completion:)","url":"\/documentation\/socialradio\/radiosdkobjc\/reportuser(withidentifier:completion:)","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/radioUIViewController()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/radioUIViewController()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"radioUIViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"url":"\/documentation\/socialradio\/radiosdkobjc\/radiouiviewcontroller()","title":"radioUIViewController()","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:isRecording:)":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAudioData","kind":"identifier"},{"kind":"text","text":"("},{"text":"withFrames","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"numberOfChannels","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"fadeState"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"audioPCMBuffer"},{"text":": ","kind":"text"},{"text":"AVAudioPCMBuffer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer"},{"text":", ","kind":"text"},{"text":"isRecording","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:10ObjectiveC8ObjCBoolV","text":"ObjCBool","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:isRecording:)","title":"getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:isRecording:)","url":"\/documentation\/socialradio\/radiosdkobjc\/getaudiodata(withframes:numberofchannels:fadestate:audiopcmbuffer:isrecording:)","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/getLiveShows(withLimit:start:completion:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/socialradio\/radiosdkobjc\/getliveshows(withlimit:start:completion:)","title":"getLiveShows(withLimit:start:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveShows"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withLimit"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"start"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?, ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKList","kind":"typeIdentifier","text":"AutomixSDKList"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/getLiveShows(withLimit:start:completion:)","type":"topic"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK":{"kind":"symbol","title":"RadioSDK","type":"topic","url":"\/documentation\/socialradio\/radiosdk","navigatorTitle":[{"kind":"identifier","text":"RadioSDK"}],"abstract":[{"text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDK","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/reportMixtape(withIdentifier:completion:)":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reportMixtape","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/reportMixtape(withIdentifier:completion:)","title":"reportMixtape(withIdentifier:completion:)","url":"\/documentation\/socialradio\/radiosdkobjc\/reportmixtape(withidentifier:completion:)","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/initialised()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/initialised()","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialised","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/socialradio\/radiosdkobjc\/initialised()","title":"initialised()","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/endRadioSession(completion:)":{"url":"\/documentation\/socialradio\/radiosdkobjc\/endradiosession(completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/endRadioSession(completion:)","title":"endRadioSession(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"endRadioSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/setRecordingAudioDataWithFrames(_:numberOfChannels:audioPCMBuffer:)":{"title":"setRecordingAudioDataWithFrames(_:numberOfChannels:audioPCMBuffer:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/setRecordingAudioDataWithFrames(_:numberOfChannels:audioPCMBuffer:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRecordingAudioDataWithFrames","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"text":"audioPCMBuffer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer","text":"AVAudioPCMBuffer"},{"text":")","kind":"text"}],"url":"\/documentation\/socialradio\/radiosdkobjc\/setrecordingaudiodatawithframes(_:numberofchannels:audiopcmbuffer:)"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/getAutomixStreamingDelegate()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/getAutomixStreamingDelegate()","url":"\/documentation\/socialradio\/radiosdkobjc\/getautomixstreamingdelegate()","role":"symbol","title":"getAutomixStreamingDelegate()","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"RadioSDK","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/fragments","value":[{"text":"RadioSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDK"}],"op":"replace"}]}]}