{"abstract":[{"type":"text","text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"sections":[],"seeAlsoSections":[{"generated":true,"title":"RadioSDK singleton","anchor":"RadioSDK-singleton","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC"]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/addStatusObserverDelegate(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/clearCache(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/endRadioSession(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/forceRefreshCredentials(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/getLiveShows(limit:start:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/joinLiveMixtape(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/radioUIViewController()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/removeStatusObserverDelegate(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/reportMixtape(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/reportUser(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/setMusicCacheDelegate(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/terminate()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/instance"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/initialised()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/radiosdk"]},{"paths":["\/documentation\/socialradio\/radiosdk"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDK","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)RadioSDK","roleHeading":"Class","symbolKind":"class","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDK"}],"navigatorTitle":[{"text":"RadioSDK","kind":"identifier"}],"role":"symbol","title":"RadioSDK"},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/setMusicCacheDelegate(_:)":{"abstract":[{"type":"text","text":"Adds a new music cache delegate"}],"title":"setMusicCacheDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMusicCacheDelegate"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setMusicCacheDelegate:"}],"url":"\/documentation\/socialradio\/radiosdk\/setmusiccachedelegate(_:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/setMusicCacheDelegate(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/addStatusObserverDelegate(_:)":{"url":"\/documentation\/socialradio\/radiosdk\/addstatusobserverdelegate(_:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/addStatusObserverDelegate(_:)","title":"addStatusObserverDelegate(_:)","kind":"symbol","abstract":[{"type":"text","text":"Adds a new status observer delegate"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addStatusObserverDelegate"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addStatusObserverDelegate:"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/forceRefreshCredentials(completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/forceRefreshCredentials(completion:)","navigatorTitle":[{"text":"forceRefreshCredentialsWithCompletion:","kind":"identifier"}],"url":"\/documentation\/socialradio\/radiosdk\/forcerefreshcredentials(completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"forceRefreshCredentials","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"role":"symbol","title":"forceRefreshCredentials(completion:)","abstract":[{"type":"text","text":"Forces AutomixSDK to ask its delegate for new credentials"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/joinLiveMixtape(identifier:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"joinLiveMixtape","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"radioViewController"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/joinLiveMixtape(identifier:completion:)","navigatorTitle":[{"kind":"identifier","text":"joinLiveMixtapeWithIdentifier:completion:"}],"url":"\/documentation\/socialradio\/radiosdk\/joinlivemixtape(identifier:completion:)","abstract":[{"text":"Starts playing a live mixtape as a consumer","type":"text"}],"kind":"symbol","title":"joinLiveMixtape(identifier:completion:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/reportMixtape(identifier:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportMixtape"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/reportMixtape(identifier:completion:)","abstract":[{"text":"Submits a report for inappropriate content for a mixtape.","type":"text"}],"kind":"symbol","title":"reportMixtape(identifier:completion:)","url":"\/documentation\/socialradio\/radiosdk\/reportmixtape(identifier:completion:)","navigatorTitle":[{"text":"reportMixtapeWithIdentifier:completion:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/clearCache(completion:)":{"title":"clearCache(completion:)","url":"\/documentation\/socialradio\/radiosdk\/clearcache(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearCacheWithCompletion:"}],"kind":"symbol","abstract":[{"type":"text","text":"Clears AutomixIQ backing files and recreates them empty"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/clearCache(completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Initialiser for Radio SDK to work against a Tuned Global’s Store and Tuned Global’s APIs.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"url":"\/documentation\/socialradio\/radiosdk\/initialise(config:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKConfig","text":"RadioSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedDelegate"},{"kind":"text","text":": "},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":", ","kind":"text"},{"text":"radioUIDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)RadioUIDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"title":"initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/removeStatusObserverDelegate(_:)":{"title":"removeStatusObserverDelegate(_:)","abstract":[{"text":"Removes a status observer delegate","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeStatusObserverDelegate","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/removeStatusObserverDelegate(_:)","navigatorTitle":[{"text":"removeStatusObserverDelegate:","kind":"identifier"}],"url":"\/documentation\/socialradio\/radiosdk\/removestatusobserverdelegate(_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/getLiveShows(limit:start:completion:)":{"title":"getLiveShows(limit:start:completion:)","navigatorTitle":[{"text":"getLiveShowsWithLimit:start:completion:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Queries the live shows, paged."}],"url":"\/documentation\/socialradio\/radiosdk\/getliveshows(limit:start:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/getLiveShows(limit:start:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLiveShows","kind":"identifier"},{"text":"(","kind":"text"},{"text":"limit","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"start"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"liveMixtapes","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKList","text":"AutomixSDKList","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/reportUser(identifier:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"reportUser","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/reportUser(identifier:completion:)","navigatorTitle":[{"text":"reportUserWithIdentifier:completion:","kind":"identifier"}],"url":"\/documentation\/socialradio\/radiosdk\/reportuser(identifier:completion:)","title":"reportUser(identifier:completion:)","kind":"symbol","type":"topic","abstract":[{"text":"Submits a report for inappropriate content for a user.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/radioUIViewController()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIViewController"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/socialradio\/radiosdk\/radiouiviewcontroller()","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/radioUIViewController()","role":"symbol","type":"topic","kind":"symbol","title":"radioUIViewController()","navigatorTitle":[{"text":"radioUIViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the view controller rendering the radio UI if either a creation or consumpsion session has already started."},{"text":" ","type":"text"},{"text":"In order to start a creation session, call startRadioSession()","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"In order top start a consumption session, call joinLiveMixtape()"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/init":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/init","abstract":[],"kind":"symbol","title":"init","type":"topic","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/socialradio\/radiosdk\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC","title":"RadioSDKObjC","url":"\/documentation\/socialradio\/radiosdkobjc","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKObjC"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKObjC"}]},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Starts a Radio session in creation mode, with the tracks and metadata provided."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startRadioSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"playTrackIndex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoplay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"contextType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"radioViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"startRadioSessionWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"url":"\/documentation\/socialradio\/radiosdk\/startradiosession(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","type":"topic","title":"startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK":{"kind":"symbol","title":"RadioSDK","type":"topic","url":"\/documentation\/socialradio\/radiosdk","navigatorTitle":[{"kind":"identifier","text":"RadioSDK"}],"abstract":[{"text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDK","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/initialised()":{"type":"topic","title":"initialised()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialised"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"initialised"}],"url":"\/documentation\/socialradio\/radiosdk\/initialised()","abstract":[{"type":"text","text":"Returns the initialised status of the Automix SDK."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/initialised()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"notifyFollowers","kind":"identifier"},{"kind":"text","text":"("},{"text":"userIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"objectType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"objectId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","navigatorTitle":[{"kind":"identifier","text":"notifyFollowersWithUserIdentifier:title:body:objectType:objectId:completion:"}],"url":"\/documentation\/socialradio\/radiosdk\/notifyfollowers(useridentifier:title:body:objecttype:objectid:completion:)","title":"notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","kind":"symbol","type":"topic","abstract":[{"text":"Submits a request to notify all followers of a user of something.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/endRadioSession(completion:)":{"url":"\/documentation\/socialradio\/radiosdk\/endradiosession(completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/endRadioSession(completion:)","title":"endRadioSession(completion:)","kind":"symbol","abstract":[{"type":"text","text":"Ends a Radio session. Be mindful if there is an ongoing Live radio show, this will terminate it without asking."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"endRadioSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"endRadioSessionWithCompletion:"}]},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/terminate()":{"title":"terminate()","abstract":[{"text":"Terminates \/ deinitialises SocialRadio. Call this on applicationWillTerminate, or whenever you no longer need it.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"terminate"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"terminate","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/socialradio\/radiosdk\/terminate()","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/terminate()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/instance":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"instance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDK","text":"RadioSDK"}],"navigatorTitle":[{"text":"instance","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/instance","role":"symbol","type":"topic","url":"\/documentation\/socialradio\/radiosdk\/instance","kind":"symbol","abstract":[{"type":"text","text":"Returns the singleton instance."}],"title":"instance"},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"RadioSDK","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"RadioSDK","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"RadioSDK","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/addStatusObserverDelegate(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/clearCache(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/endRadioSession(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/forceRefreshCredentials(completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/getLiveShows(limit:start:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/init","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/joinLiveMixtape(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/radioUIViewController()","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/removeStatusObserverDelegate(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/reportMixtape(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/reportUser(identifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/setMusicCacheDelegate(_:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/terminate()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"generated":true,"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/instance"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/initialised()"]}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDK"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"value":"setMusicCacheDelegate:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1setMusicCacheDelegate(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1setMusicCacheDelegate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setMusicCacheDelegate:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1addStatusObserverDelegate(_:)\/title","value":"addStatusObserverDelegate:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addStatusObserverDelegate:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1addStatusObserverDelegate(_:)\/fragments"},{"value":"forceRefreshCredentialsWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1forceRefreshCredentials(completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1forceRefreshCredentials(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"forceRefreshCredentialsWithCompletion:"}]},{"op":"replace","value":"joinLiveMixtapeWithIdentifier:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1joinLiveMixtape(identifier:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1joinLiveMixtape(identifier:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"joinLiveMixtapeWithIdentifier:completion:","kind":"identifier"}]},{"value":"reportMixtapeWithIdentifier:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1reportMixtape(identifier:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reportMixtapeWithIdentifier:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1reportMixtape(identifier:completion:)\/fragments"},{"op":"replace","value":"clearCacheWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1clearCache(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"clearCacheWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1clearCache(completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)\/title","value":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"op":"replace"},{"value":"removeStatusObserverDelegate:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1removeStatusObserverDelegate(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeStatusObserverDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1removeStatusObserverDelegate(_:)\/fragments"},{"value":"getLiveShowsWithLimit:start:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1getLiveShows(limit:start:completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1getLiveShows(limit:start:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLiveShowsWithLimit:start:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1reportUser(identifier:completion:)\/title","value":"reportUserWithIdentifier:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1reportUser(identifier:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"reportUserWithIdentifier:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1radioUIViewController()\/title","value":"radioUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1radioUIViewController()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"radioUIViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title","value":"startRadioSessionWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1startRadioSession(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startRadioSessionWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}]},{"op":"replace","value":"RadioSDK","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/fragments","value":[{"text":"RadioSDK","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"RadioSDK"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1initialised()\/title","value":"initialised","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1initialised()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"initialised","kind":"identifier"}]},{"value":"notifyFollowersWithUserIdentifier:title:body:objectType:objectId:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"notifyFollowersWithUserIdentifier:title:body:objectType:objectId:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1endRadioSession(completion:)\/title","op":"replace","value":"endRadioSessionWithCompletion:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endRadioSessionWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1endRadioSession(completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1terminate()\/title","value":"terminate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1terminate()\/fragments","value":[{"kind":"text","text":"- "},{"text":"terminate","kind":"identifier"}],"op":"replace"},{"value":"instance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1instance\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1instance\/fragments","value":[{"text":"instance","kind":"identifier"}],"op":"replace"}]}]}