{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/stopLoopingNoLoopingTrack"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeStopLoopingNoLoopingTrack"}],"roleHeading":"Case","title":"ErrorCode.stopLoopingNoLoopingTrack","modules":[{"name":"AutomixIQ"}],"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLoopingNoLoopingTrack","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeStopLoopingNoLoopingTrack"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/errorcode\/stoploopingnoloopingtrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode\/stoploopingnoloopingtrack"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLoopingNoLoopingTrack"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","type":"topic","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/stopLoopingNoLoopingTrack":{"kind":"symbol","navigatorTitle":[{"text":"ErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/errorcode\/stoploopingnoloopingtrack","role":"symbol","title":"ErrorCode.stopLoopingNoLoopingTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLoopingNoLoopingTrack","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/stopLoopingNoLoopingTrack"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"title":"ErrorCode","abstract":[],"url":"\/documentation\/automixiq\/errorcode","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ErrorCodeStopLoopingNoLoopingTrack","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeStopLoopingNoLoopingTrack"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodeStopLoopingNoLoopingTrack"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ErrorCodeStopLoopingNoLoopingTrack","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1stopLoopingNoLoopingTrack\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeStopLoopingNoLoopingTrack"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1stopLoopingNoLoopingTrack\/fragments"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"ErrorCode"}]}]}]}