{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate"]]},"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"metadata":{"title":"logAutomixSDKMessage(logLevel:message:)","role":"symbol","modules":[{"name":"SocialRadio"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logAutomixSDKMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"logLevel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKLogLevel","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKLogLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"externalID":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate(im)logAutomixSDKMessageWithLogLevel:message:","roleHeading":"Instance Method","navigatorTitle":[{"text":"logAutomixSDKMessageWithLogLevel:message:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logAutomixSDKMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"logLevel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKLogLevel","text":"AutomixSDKLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The log level"}]}],"name":"logLevel"},{"name":"message","content":[{"inlineContent":[{"text":"The message it wishes to log.","type":"text"}],"type":"paragraph"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate\/logAutomixSDKMessage(logLevel:message:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkstreamingdelegate\/logautomixsdkmessage(loglevel:message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkstreamingdelegate\/logautomixsdkmessage(loglevel:message:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate":{"title":"AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/automixsdkstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","type":"topic","abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel":{"type":"topic","url":"\/documentation\/socialradio\/automixsdkloglevel","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","title":"AutomixSDKLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKLogLevel"}],"abstract":[{"type":"text","text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate/logAutomixSDKMessage(logLevel:message:)":{"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"navigatorTitle":[{"text":"logAutomixSDKMessageWithLogLevel:message:","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkstreamingdelegate\/logautomixsdkmessage(loglevel:message:)","kind":"symbol","title":"logAutomixSDKMessage(logLevel:message:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate\/logAutomixSDKMessage(logLevel:message:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"logAutomixSDKMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"text":"AutomixSDKLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKLogLevel"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"logAutomixSDKMessageWithLogLevel:message:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"logAutomixSDKMessageWithLogLevel:message:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"logAutomixSDKMessageWithLogLevel:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKLogLevel","text":"AutomixSDKLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"},{"kind":"text","text":") "},{"kind":"internalParam","text":"logLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"message:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The log level","type":"text"}],"type":"paragraph"}],"name":"logLevel"},{"content":[{"inlineContent":[{"text":"The message it wishes to log.","type":"text"}],"type":"paragraph"}],"name":"message"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"op":"replace","value":"logAutomixSDKMessageWithLogLevel:message:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate~1logAutomixSDKMessage(logLevel:message:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logAutomixSDKMessageWithLogLevel:message:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate~1logAutomixSDKMessage(logLevel:message:)\/fragments","op":"replace"}]}]}