{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstatus\/playspeed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqstatus\/playspeed"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Represents the Automix SDK play speed as a factor, from 0.5 to 2","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playSpeed"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus\/playSpeed"},"metadata":{"title":"playSpeed","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"playSpeed"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playSpeed"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus(py)playSpeed","modules":[{"name":"AutomixIQ"}],"role":"symbol"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus":{"title":"AutomixIQStatus","url":"\/documentation\/automixiq\/automixiqstatus","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatus"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}],"role":"symbol","abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus/playSpeed":{"url":"\/documentation\/automixiq\/automixiqstatus\/playspeed","title":"playSpeed","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus\/playSpeed","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playSpeed","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"playSpeed","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents the Automix SDK play speed as a factor, from 0.5 to 2"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","title":"AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"playSpeed","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"playSpeed","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"playSpeed","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixIQStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/fragments","value":[{"text":"AutomixIQStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/navigatorTitle","value":[{"text":"AutomixIQStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus~1playSpeed\/title","value":"playSpeed","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus~1playSpeed\/fragments","value":[{"kind":"identifier","text":"playSpeed"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}