{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/addAds(withMetadata:afterTrackIdentifier:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAds","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withMetadata"},{"text":" ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"TunedAdModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel"},{"text":"], ","kind":"text"},{"text":"afterTrackIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"languages":["swift"]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addAds","kind":"identifier"},{"kind":"text","text":"("},{"text":"withMetadata","kind":"externalParam"},{"kind":"text","text":" "},{"text":"metadata","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"afterTrackIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addAds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","text":"TunedAdModel","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"afterTrackIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"role":"symbol","title":"addAds(withMetadata:afterTrackIdentifier:completion:)","roleHeading":"Instance Method","externalID":"c:objc(cs)AutomixIQObjC(im)addAdsWithMetadata:afterTrackIdentifier:completion:","modules":[{"name":"SocialRadio"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqobjc\/addads(withmetadata:aftertrackidentifier:completion:)"]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAdModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAdModel"}],"role":"symbol","url":"\/documentation\/socialradio\/tunedadmodel","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","type":"topic","abstract":[{"type":"text","text":"TunedAdModel models a Ad."}],"navigatorTitle":[{"kind":"identifier","text":"TunedAdModel"}],"title":"TunedAdModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC/addAds(withMetadata:afterTrackIdentifier:completion:)":{"url":"\/documentation\/socialradio\/automixiqobjc\/addads(withmetadata:aftertrackidentifier:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addAds","kind":"identifier"},{"kind":"text","text":"("},{"text":"withMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"afterTrackIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/addAds(withMetadata:afterTrackIdentifier:completion:)","role":"symbol","title":"addAds(withMetadata:afterTrackIdentifier:completion:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","title":"SocialRadio","role":"collection","url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","url":"\/documentation\/socialradio\/automixiqobjc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQObjC"}],"abstract":[],"title":"AutomixIQObjC"}},"variantOverrides":[{"patch":[{"value":"TunedAdModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/fragments","value":[{"text":"TunedAdModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/navigatorTitle","value":[{"kind":"identifier","text":"TunedAdModel"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}