{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/initialise(with:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQConfig","text":"AutomixIQConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig"},{"text":", ","kind":"text"},{"text":"tunedRestDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQMusicCacheDelegate","text":"AutomixIQMusicCacheDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]},{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQConfig","text":"AutomixIQConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig"},{"text":", ","kind":"text"},{"text":"tunedRestDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQMusicCacheDelegate","text":"AutomixIQMusicCacheDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate"},{"text":")?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQConfig","kind":"typeIdentifier","text":"AutomixIQConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStatusDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixIQStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQMusicCacheDelegate","kind":"typeIdentifier","text":"AutomixIQMusicCacheDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","title":"initialise(with:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","externalID":"c:objc(cs)AutomixIQObjC(cm)initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","roleHeading":"Type Method","modules":[{"name":"SocialRadio"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqobjc\/initialise(with:tunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)"]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","title":"SocialRadio","role":"collection","url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","url":"\/documentation\/socialradio\/tunedrestdelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"title":"TunedRestDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC/initialise(with:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/initialise(with:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","url":"\/documentation\/socialradio\/automixiqobjc\/initialise(with:tunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQConfig","text":"AutomixIQConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automixIQStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"AutomixIQMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQMusicCacheDelegate"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"abstract":[],"title":"initialise(with:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig":{"url":"\/documentation\/socialradio\/automixiqconfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQConfig"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","kind":"symbol","abstract":[],"role":"symbol","title":"AutomixIQConfig","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate":{"type":"topic","navigatorTitle":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"title":"AutomixIQMusicCacheDelegate","role":"symbol","url":"\/documentation\/socialradio\/automixiqmusiccachedelegate","abstract":[{"type":"text","text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","url":"\/documentation\/socialradio\/automixiqobjc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQObjC"}],"abstract":[],"title":"AutomixIQObjC"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"type":"topic","navigatorTitle":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"title":"AutomixIQStatusObserverDelegate","role":"symbol","url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","op":"replace","value":"TunedRestDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/title","op":"replace","value":"AutomixIQConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/navigatorTitle","value":[{"text":"AutomixIQConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/title","op":"replace","value":"AutomixIQMusicCacheDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/navigatorTitle","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title","op":"replace","value":"AutomixIQStatusObserverDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]}]}]}