{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelTrace","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkloglevel\/logleveltrace"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkloglevel\/logleveltrace"]}],"sections":[],"metadata":{"title":"AutomixSDKLogLevel.logLevelTrace","role":"symbol","externalID":"c:@M@SocialRadio@E@AutomixSDKLogLevel@AutomixSDKLogLevelLogLevelTrace","navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelTrace","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelTrace"}],"roleHeading":"Case","symbolKind":"case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelTrace"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel":{"url":"\/documentation\/socialradio\/automixsdkloglevel","navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels"}],"kind":"symbol","title":"AutomixSDKLogLevel","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/logLevelTrace":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelTrace"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelTrace","title":"AutomixSDKLogLevel.logLevelTrace","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkloglevel\/logleveltrace","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"AutomixSDKLogLevelLogLevelTrace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"AutomixSDKLogLevelLogLevelTrace","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel"},{"value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/navigatorTitle","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelTrace\/title","value":"AutomixSDKLogLevelLogLevelTrace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelTrace\/fragments","value":[{"text":"AutomixSDKLogLevelLogLevelTrace","kind":"identifier"}],"op":"replace"}]}]}