{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK\/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","interfaceLanguage":"swift"},"abstract":[{"text":"Turns the AutomixIQ player on and starts playback if required as soon as possible at a given track and playback time within the provided playlist.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the playlist is empty this operation will fail and AutomixIQ will be turned off."},{"text":" ","type":"text"},{"text":"Returns an error if the engine has not been initialised or has already been turned on.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automixOn"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifiers"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"text":"seconds","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"contextType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The list of track identifiers that form the playlist you are loading the player with.","type":"text"}],"type":"paragraph"}],"name":"identifiers"},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of AutomixSDKTrackModel objects you can pass to the engine so it doesn’t make additional API requests for the corresponding track identifiers metadata. Can be nil."}]}]},{"name":"playTrackIndex","content":[{"inlineContent":[{"type":"text","text":"The index of the track to begin playback at."}],"type":"paragraph"}]},{"name":"seconds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The time within the selected track to begin playback at, in seconds."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If true, playback will start as soon as possible. Otherwise, playback will start only when calling -(void)play."}]}],"name":"autoplay"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A string representing the source of these tracks, for logging purposes (‘playlist’, ‘album’, etc).","type":"text"}]}],"name":"contextType"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the source of these tracks, for logging purposes."}]}],"name":"contextId"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}]}]}],"metadata":{"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDK(im)automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","title":"automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","navigatorTitle":[{"kind":"identifier","text":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"modules":[{"name":"SocialRadio"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automixOn"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"contextType"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"contextId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdk\/automixon(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdk\/automixon(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)"]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDK/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"url":"\/documentation\/socialradio\/automixsdk\/automixon(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Turns the AutomixIQ player on and starts playback if required as soon as possible at a given track and playback time within the provided playlist."},{"type":"text","text":" "},{"type":"text","text":"If the playlist is empty this operation will fail and AutomixIQ will be turned off."},{"type":"text","text":" "},{"text":"Returns an error if the engine has not been initialised or has already been turned on.","type":"text"}],"title":"automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","navigatorTitle":[{"kind":"identifier","text":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK\/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"automixOn","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"playTrackIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"seconds"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoplay"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDK":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"title":"AutomixSDK","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDK"}],"url":"\/documentation\/socialradio\/automixsdk","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel":{"abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","title":"AutomixSDKTrackModel","url":"\/documentation\/socialradio\/automixsdktrackmodel","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"automixOnIdentifiers:"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"identifiers","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<AutomixSDKTrackModel *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"metadata"},{"text":" ","kind":"text"},{"text":"playTrackIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@int32_t","text":"int32_t","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"playTrackIndex","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"seconds:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"seconds"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoplay:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"autoplay"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextType:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"contextType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"contextId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"contextId"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The list of track identifiers that form the playlist you are loading the player with."}],"type":"paragraph"}],"name":"identifiers"},{"name":"metadata","content":[{"inlineContent":[{"text":"An array of AutomixSDKTrackModel objects you can pass to the engine so it doesn’t make additional API requests for the corresponding track identifiers metadata. Can be nil.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The index of the track to begin playback at."}],"type":"paragraph"}],"name":"playTrackIndex"},{"name":"seconds","content":[{"inlineContent":[{"text":"The time within the selected track to begin playback at, in seconds.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If true, playback will start as soon as possible. Otherwise, playback will start only when calling -(void)play."}]}],"name":"autoplay"},{"content":[{"inlineContent":[{"text":"A string representing the source of these tracks, for logging purposes (‘playlist’, ‘album’, etc).","type":"text"}],"type":"paragraph"}],"name":"contextType"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the source of these tracks, for logging purposes."}]}],"name":"contextId"},{"name":"completion","content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK~1automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title","value":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK~1automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK\/title","value":"AutomixSDK","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK\/fragments","value":[{"kind":"identifier","text":"AutomixSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK\/navigatorTitle","value":[{"text":"AutomixSDK","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel"},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/fragments"},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/navigatorTitle"}]}]}