{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdk\/removestatusobserverdelegate(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdk\/removestatusobserverdelegate(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK\/removeStatusObserverDelegate(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeStatusObserverDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"statusObserverDelegate"},{"kind":"text","text":": "},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate to remove.","type":"text"}]}],"name":"statusObserverDelegate"}]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeStatusObserverDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"removeStatusObserverDelegate:"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixSDK(im)removeStatusObserverDelegate:","title":"removeStatusObserverDelegate(_:)","modules":[{"name":"SocialRadio"}],"role":"symbol"},"kind":"symbol","abstract":[{"text":"Removes a status observer delegate","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDK/removeStatusObserverDelegate(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeStatusObserverDelegate"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Removes a status observer delegate","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeStatusObserverDelegate:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK\/removeStatusObserverDelegate(_:)","title":"removeStatusObserverDelegate(_:)","type":"topic","url":"\/documentation\/socialradio\/automixsdk\/removestatusobserverdelegate(_:)","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDK":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"title":"AutomixSDK","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDK"}],"url":"\/documentation\/socialradio\/automixsdk","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate":{"role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"title":"AutomixSDKStatusObserverDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"removeStatusObserverDelegate:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeStatusObserverDelegate:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeStatusObserverDelegate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"id<AutomixSDKStatusObserverDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"statusObserverDelegate"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate to remove."}]}],"name":"statusObserverDelegate"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"removeStatusObserverDelegate:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK~1removeStatusObserverDelegate(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"removeStatusObserverDelegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK~1removeStatusObserverDelegate(_:)\/fragments"},{"value":"AutomixSDK","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK\/title"},{"value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK\/fragments"},{"value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}