{"variants":[{"paths":["\/documentation\/automixiq\/errorcode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"topicSections":[{"title":"Operators","anchor":"Operators","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/!=(_:_:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"kind":"article","metadata":{"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"AutomixIQ"}]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"url":"\/documentation\/automixiq","title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","url":"\/documentation\/automixiq\/errorcode","abstract":[],"kind":"symbol","title":"ErrorCode","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/!=(_:_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/errorcode\/!=(_:_:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/!=(_:_:)","abstract":[],"title":"!=(_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","value":"ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"ErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}