{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/errorcode\/offlinenotuneduseridavailable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode\/offlinenotuneduseridavailable"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offlineNoTunedUserIdAvailable"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"ErrorCode.offlineNoTunedUserIdAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offlineNoTunedUserIdAvailable"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeOfflineNoTunedUserIdAvailable"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/offlineNoTunedUserIdAvailable":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offlineNoTunedUserIdAvailable","abstract":[],"title":"ErrorCode.offlineNoTunedUserIdAvailable","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode\/offlinenotuneduseridavailable","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"url":"\/documentation\/automixiq","title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","url":"\/documentation\/automixiq\/errorcode","abstract":[],"kind":"symbol","title":"ErrorCode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ErrorCodeOfflineNoTunedUserIdAvailable","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeOfflineNoTunedUserIdAvailable","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offlineNoTunedUserIdAvailable\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offlineNoTunedUserIdAvailable\/fragments","value":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","op":"replace"}]}]}