{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncClearLikedTracksCache","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"syncClearLikedTracksCache","kind":"identifier"}],"roleHeading":"Instance Method","required":true,"title":"syncClearLikedTracksCache()","role":"symbol","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerTrackLikesDelegate(im)syncClearLikedTracksCache","symbolKind":"method","modules":[{"name":"SocialRadio"}]},"kind":"symbol","abstract":[{"type":"text","text":"Clears the local cache of liked tracks."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate\/syncClearLikedTracksCache()"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"syncClearLikedTracksCache","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/sociallayertracklikesdelegate\/syncclearlikedtrackscache()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayertracklikesdelegate\/syncclearlikedtrackscache()"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerTrackLikesDelegate/syncClearLikedTracksCache()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncClearLikedTracksCache","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"syncClearLikedTracksCache"}],"url":"\/documentation\/socialradio\/sociallayertracklikesdelegate\/syncclearlikedtrackscache()","required":true,"role":"symbol","title":"syncClearLikedTracksCache()","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate\/syncClearLikedTracksCache()","abstract":[{"type":"text","text":"Clears the local cache of liked tracks."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerTrackLikesDelegate":{"title":"SocialLayerTrackLikesDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a track."}],"url":"\/documentation\/socialradio\/sociallayertracklikesdelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"url":"\/documentation\/socialradio","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"syncClearLikedTracksCache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"syncClearLikedTracksCache","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"syncClearLikedTracksCache"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate~1syncClearLikedTracksCache()\/title","op":"replace","value":"syncClearLikedTracksCache"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate~1syncClearLikedTracksCache()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"syncClearLikedTracksCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/title","op":"replace","value":"SocialLayerTrackLikesDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}]}]}]}