{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackMode"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/playbackmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/playbackmode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","title":"AutomixIQStatusVariable.playbackMode","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackMode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariablePlaybackMode","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariablePlaybackMode"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playbackMode"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"url":"\/documentation\/socialradio\/automixiqstatusvariable","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQStatusVariable"}],"role":"symbol","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"type":"topic","title":"AutomixIQStatusVariable","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playbackMode":{"navigatorTitle":[{"text":"AutomixIQStatusVariablePlaybackMode","kind":"identifier"}],"title":"AutomixIQStatusVariable.playbackMode","url":"\/documentation\/socialradio\/automixiqstatusvariable\/playbackmode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackMode","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playbackMode","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixIQStatusVariablePlaybackMode","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaybackMode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AutomixIQStatusVariablePlaybackMode","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixIQStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title"},{"value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments"},{"value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle"},{"value":"AutomixIQStatusVariablePlaybackMode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playbackMode\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaybackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playbackMode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}