{"metadata":{"title":"trackNumber","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"trackNumber","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQTrackModel(py)trackNumber"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTrackModel\/trackNumber-8u47e"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTrackModel"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqtrackmodel\/tracknumber-8u47e"]},{"paths":["\/documentation\/automixiq\/automixiqtrackmodel\/tracknumber-8u47e"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackNumber"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Objective-C accessible member for the track number","type":"text"}],"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTrackModel":{"title":"AutomixIQTrackModel","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTrackModel"}],"url":"\/documentation\/automixiq\/automixiqtrackmodel","abstract":[{"type":"text","text":"AutomixIQTrackModel models a track. This metadata is required."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTrackModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQTrackModel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTrackModel/trackNumber-8u47e":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTrackModel\/trackNumber-8u47e","role":"symbol","url":"\/documentation\/automixiq\/automixiqtrackmodel\/tracknumber-8u47e","navigatorTitle":[{"kind":"identifier","text":"trackNumber"}],"title":"trackNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","abstract":[{"type":"text","text":"Objective-C accessible member for the track number"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"trackNumber","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"trackNumber"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"trackNumber","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixIQTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTrackModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTrackModel\/fragments","value":[{"text":"AutomixIQTrackModel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixIQTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTrackModel\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTrackModel~1trackNumber-8u47e\/title","value":"trackNumber","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTrackModel~1trackNumber-8u47e\/fragments","value":[{"kind":"identifier","text":"trackNumber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}