{"seeAlsoSections":[{"anchor":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate"],"title":"AutomixIQ","generated":true}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqmusiccachedelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqmusiccachedelegate"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/getCachedTrack(trackId:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/getTrackMetadata(trackId:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)"],"title":"Instance Methods","generated":true}],"abstract":[{"type":"text","text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@SocialRadio@objc(pl)AutomixIQMusicCacheDelegate","navigatorTitle":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"title":"AutomixIQMusicCacheDelegate","symbolKind":"protocol","modules":[{"name":"SocialRadio"}],"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"role":"symbol"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate":{"navigatorTitle":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqmusiccachedelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"abstract":[{"text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"title":"AutomixIQMusicCacheDelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig":{"navigatorTitle":[{"text":"AutomixIQConfig","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqconfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQConfig","kind":"identifier"}],"abstract":[],"title":"AutomixIQConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedPluginMetadataModel":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedPluginMetadataModel"}],"role":"symbol","abstract":[{"text":"TunedPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"title":"TunedPluginMetadataModel","kind":"symbol","url":"\/documentation\/socialradio\/tunedpluginmetadatamodel","type":"topic","navigatorTitle":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse":{"navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"url":"\/documentation\/socialradio\/tunedauthenticationresponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAuthenticationResponse"}],"abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"title":"TunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ-article":{"url":"\/documentation\/socialradio\/automixiq-article","abstract":[{"text":"Availablity of underlying technologies and APIs.","type":"text"}],"title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","role":"article","kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"url":"\/documentation\/socialradio\/automixiqplaylistoperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"abstract":[{"type":"text","text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"title":"AutomixIQPlaylistOperation","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode":{"url":"\/documentation\/socialradio\/tunedautomixplaybackmode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"type":"topic","role":"symbol","title":"TunedAutomixPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable","role":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"kind":"symbol","title":"AutomixIQStatusVariable","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"abstract":[{"text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"title":"AutomixIQStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedArtistModel":{"navigatorTitle":[{"kind":"identifier","text":"TunedArtistModel"}],"url":"\/documentation\/socialradio\/tunedartistmodel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedArtistModel"}],"abstract":[{"type":"text","text":"TunedArtistModel models an artist."}],"title":"TunedArtistModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate/getTrackMetadata(trackId:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getTrackMetadataWithTrackId:"}],"title":"getTrackMetadata(trackId:)","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/getTrackMetadata(trackId:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqmusiccachedelegate\/gettrackmetadata(trackid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTrackMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"TunedTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel"},{"kind":"text","text":"?"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}],"url":"\/documentation\/socialradio\/automixiq","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}],"abstract":[{"type":"text","text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate/trackDownloadCompleted(trackId:data:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}],"title":"trackDownloadCompleted(trackId:data:)","abstract":[{"type":"text","text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqmusiccachedelegate\/trackdownloadcompleted(trackid:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadCompleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"url":"\/documentation\/socialradio\/automixiqobjc","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQObjC"}],"abstract":[],"title":"AutomixIQObjC","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqwaveformmodel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"kind":"symbol","title":"AutomixIQWaveformModel","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"title":"AutomixIQStatus","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate/trackDownloadProgressChanged(trackId:progress:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"title":"trackDownloadProgressChanged(trackId:progress:)","abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadProgressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"url":"\/documentation\/socialradio\/tunedtrackmodel","abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"type":"topic","role":"symbol","title":"TunedTrackModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate/getCachedTrack(trackId:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getCachedTrackWithTrackId:"}],"title":"getCachedTrack(trackId:)","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/getCachedTrack(trackId:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqmusiccachedelegate\/getcachedtrack(trackid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCachedTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel":{"navigatorTitle":[{"text":"TunedLogLevel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","kind":"symbol","abstract":[{"type":"text","text":"TunedLogLevel is an enum of all the AutomixIQ available log levels"}],"title":"TunedLogLevel","url":"\/documentation\/socialradio\/tunedloglevel","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedLogLevel"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"url":"\/documentation\/socialradio\/tunedrestdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"title":"TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixIQMusicCacheDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/getCachedTrack(trackId:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/getTrackMetadata(trackId:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"generated":true,"title":"AutomixIQ","anchor":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixIQMusicCacheDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/title"},{"value":[{"kind":"identifier","text":"AutomixIQConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/fragments"},{"value":[{"text":"AutomixIQConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/navigatorTitle"},{"value":"TunedPluginMetadataModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/fragments","value":[{"kind":"identifier","text":"TunedPluginMetadataModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/navigatorTitle","value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}]},{"value":"TunedAuthenticationResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/title"},{"value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/fragments"},{"value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/navigatorTitle"},{"value":"AutomixIQPlaylistOperation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},{"value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/navigatorTitle"},{"op":"replace","value":"TunedAutomixPlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/title"},{"value":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/fragments"},{"op":"replace","value":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title","op":"replace","value":"AutomixIQStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]},{"value":"AutomixIQStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle"},{"value":"TunedArtistModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/title"},{"value":[{"kind":"identifier","text":"TunedArtistModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/fragments"},{"op":"replace","value":[{"text":"TunedArtistModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/navigatorTitle"},{"value":"getTrackMetadataWithTrackId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1getTrackMetadata(trackId:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getTrackMetadataWithTrackId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1getTrackMetadata(trackId:)\/fragments"},{"op":"replace","value":"AutomixIQ","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle"},{"op":"replace","value":"trackDownloadCompletedWithTrackId:data:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1trackDownloadCompleted(trackId:data:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1trackDownloadCompleted(trackId:data:)\/fragments"},{"op":"replace","value":"AutomixIQWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatus","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle"},{"op":"replace","value":"trackDownloadProgressChangedWithTrackId:progress:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments"},{"op":"replace","value":"TunedTrackModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle","value":[{"kind":"identifier","text":"TunedTrackModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1getCachedTrack(trackId:)\/title","op":"replace","value":"getCachedTrackWithTrackId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1getCachedTrack(trackId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCachedTrackWithTrackId:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/title","op":"replace","value":"TunedLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/fragments","value":[{"kind":"identifier","text":"TunedLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/navigatorTitle","value":[{"kind":"identifier","text":"TunedLogLevel"}]},{"op":"replace","value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TunedRestDelegate"}]}]}]}