{"metadata":{"title":"ErrorCode.addTrackPlaylistDoesNotExist","navigatorTitle":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeAddTrackPlaylistDoesNotExist","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackPlaylistDoesNotExist"}],"symbolKind":"case","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackPlaylistDoesNotExist","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/automixiq\/errorcode\/addtrackplaylistdoesnotexist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/errorcode\/addtrackplaylistdoesnotexist"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/addTrackPlaylistDoesNotExist":{"navigatorTitle":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackPlaylistDoesNotExist","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/addtrackplaylistdoesnotexist","abstract":[],"title":"ErrorCode.addTrackPlaylistDoesNotExist","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","kind":"symbol","url":"\/documentation\/automixiq\/errorcode","abstract":[],"title":"ErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorCode"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ErrorCodeAddTrackPlaylistDoesNotExist","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeAddTrackPlaylistDoesNotExist"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodeAddTrackPlaylistDoesNotExist"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ErrorCodeAddTrackPlaylistDoesNotExist","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackPlaylistDoesNotExist\/title"},{"op":"replace","value":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackPlaylistDoesNotExist\/fragments"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle"}]}]}