{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightTransitionDuration","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqwaveformmodel\/righttransitionduration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqwaveformmodel\/righttransitionduration"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel"]]},"sections":[],"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel(py)rightTransitionDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTransitionDuration"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"title":"rightTransitionDuration","modules":[{"name":"SocialRadio"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"rightTransitionDuration"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/rightTransitionDuration"},"abstract":[{"type":"text","text":"The duration of the right transition, in seconds"}],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel/rightTransitionDuration":{"url":"\/documentation\/socialradio\/automixiqwaveformmodel\/righttransitionduration","navigatorTitle":[{"kind":"identifier","text":"rightTransitionDuration"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTransitionDuration"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/rightTransitionDuration","kind":"symbol","abstract":[{"text":"The duration of the right transition, in seconds","type":"text"}],"title":"rightTransitionDuration","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"kind":"symbol","title":"AutomixIQWaveformModel","url":"\/documentation\/socialradio\/automixiqwaveformmodel","abstract":[{"type":"text","text":"AutomixIQWaveformModel models the waveform of a track."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"role":"collection","kind":"symbol","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","title":"SocialRadio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"rightTransitionDuration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"rightTransitionDuration","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTransitionDuration"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel~1rightTransitionDuration\/title","op":"replace","value":"rightTransitionDuration"},{"value":[{"kind":"identifier","text":"rightTransitionDuration"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel~1rightTransitionDuration\/fragments"},{"value":"AutomixIQWaveformModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title"},{"value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments"},{"value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}