{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqequaliserconfig"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqequaliserconfig"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQEqualiserConfig","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/highPassFrequency","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/lowPassFrequency"],"generated":true,"title":"Instance Properties"}],"metadata":{"symbolKind":"class","modules":[{"name":"SocialRadio"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"AutomixIQEqualiserConfig"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQEqualiserConfig","title":"AutomixIQEqualiserConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQEqualiserConfig","kind":"identifier"}],"role":"symbol"},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"type":"conformsTo"}],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQEqualiserConfig/init":{"role":"symbol","url":"\/documentation\/socialradio\/automixiqequaliserconfig\/init","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/init","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQEqualiserConfig/highPassFrequency":{"navigatorTitle":[{"kind":"identifier","text":"highPassFrequency"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/highPassFrequency","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highPassFrequency"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"url":"\/documentation\/socialradio\/automixiqequaliserconfig\/highpassfrequency","kind":"symbol","title":"highPassFrequency"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQEqualiserConfig":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQEqualiserConfig"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQEqualiserConfig"}],"title":"AutomixIQEqualiserConfig","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixiqequaliserconfig"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQEqualiserConfig/lowPassFrequency":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowPassFrequency"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"lowPassFrequency"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/lowPassFrequency","role":"symbol","url":"\/documentation\/socialradio\/automixiqequaliserconfig\/lowpassfrequency","title":"lowPassFrequency"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AutomixIQEqualiserConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/highPassFrequency","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/lowPassFrequency"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig\/init"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQEqualiserConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig~1highPassFrequency\/title","value":"highPassFrequency"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig~1highPassFrequency\/fragments","value":[{"text":"highPassFrequency","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig\/title","value":"AutomixIQEqualiserConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig\/fragments","value":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig\/navigatorTitle","value":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig~1lowPassFrequency\/title","value":"lowPassFrequency"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig~1lowPassFrequency\/fragments","value":[{"kind":"identifier","text":"lowPassFrequency"}]}]}]}