{"kind":"symbol","metadata":{"roleHeading":"Initializer","modules":[{"name":"SocialRadioLite"}],"role":"symbol","symbolKind":"init","title":"init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"featureSetConfig","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioFeatureSetConfig","text":"SocialRadioFeatureSetConfig","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uiConfig"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioUIConfig","text":"SocialRadioUIConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automaticallyLogPlayback"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:","kind":"identifier"}],"externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioConfig(im)initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradioconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:automaticallylogplayback:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradioconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:automaticallylogplayback:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"country"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"storeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"featureSetConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SocialRadioFeatureSetConfig","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioFeatureSetConfig","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig"},{"kind":"text","text":" = SocialRadioFeatureSetConfig(), "},{"kind":"externalParam","text":"uiConfig"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","text":"SocialRadioUIConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioUIConfig"},{"kind":"text","text":" = SocialRadioUIConfig(), "},{"text":"automaticallyLogPlayback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = false)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig\/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioFeatureSetConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","url":"\/documentation\/socialradiolite\/socialradiofeaturesetconfig","title":"SocialRadioFeatureSetConfig"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioConfig":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioConfig","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioconfig","title":"SocialRadioConfig","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioConfig"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioConfig/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:)":{"url":"\/documentation\/socialradiolite\/socialradioconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:automaticallylogplayback:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storeId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"featureSetConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioFeatureSetConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioFeatureSetConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"uiConfig"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioUIConfig","text":"SocialRadioUIConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automaticallyLogPlayback"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig\/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:)","type":"topic","role":"symbol","title":"init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:)","kind":"symbol","navigatorTitle":[{"text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","abstract":[],"role":"symbol","title":"SocialRadioUIConfig","navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithApiKey:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"apiKey","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"country:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"country","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"storeId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"applicationId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureSetConfig:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","kind":"typeIdentifier","text":"SocialRadioFeatureSetConfig","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioFeatureSetConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"featureSetConfig"},{"kind":"text","text":" "},{"text":"uiConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","text":"SocialRadioUIConfig","preciseIdentifier":"c:@M@SocialRadioLite@objc(cs)SocialRadioUIConfig","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"uiConfig","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"automaticallyLogPlayback:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"automaticallyLogPlayback"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SocialRadioFeatureSetConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/fragments","op":"replace","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/navigatorTitle","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}]},{"value":"SocialRadioConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/title","op":"replace"},{"value":[{"text":"SocialRadioConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/navigatorTitle","value":[{"text":"SocialRadioConfig","kind":"identifier"}]},{"value":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig~1init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig~1init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:automaticallyLogPlayback:","kind":"identifier"}]},{"value":"SocialRadioUIConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/title","op":"replace"},{"value":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}