{"sections":[],"metadata":{"title":"tracks","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape(py)tracks","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tracks","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SocialRadioMixtapeTrack","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtapeTrack"},{"kind":"text","text":"]?"}],"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"tracks","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/tracks","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"This mixtape’s tracks"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tracks"},{"text":": [","kind":"text"},{"text":"SocialRadioMixtapeTrack","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtapeTrack","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack"},{"kind":"text","text":"]?"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiomixtape\/tracks"]},{"paths":["\/documentation\/socialradio\/socialradiomixtape\/tracks"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape/tracks":{"url":"\/documentation\/socialradio\/socialradiomixtape\/tracks","title":"tracks","navigatorTitle":[{"kind":"identifier","text":"tracks"}],"abstract":[{"text":"This mixtape’s tracks","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tracks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtapeTrack","text":"SocialRadioMixtapeTrack"},{"kind":"text","text":"]?"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape\/tracks"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack":{"navigatorTitle":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"title":"SocialRadioMixtapeTrack","role":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiomixtapetrack","abstract":[{"text":"SocialRadioMixtapeTrack models a track in a mixtape","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"title":"SocialRadio","kind":"symbol","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape":{"abstract":[{"text":"SocialRadioMixtape models a mixtape","type":"text"}],"role":"symbol","kind":"symbol","title":"SocialRadioMixtape","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","url":"\/documentation\/socialradio\/socialradiomixtape","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SocialRadioMixtape","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"tracks"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"tracks","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<SocialRadioMixtapeTrack *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"tracks","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1tracks\/title","value":"tracks","op":"replace"},{"value":[{"text":"tracks","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape~1tracks\/fragments"},{"op":"replace","value":"SocialRadioMixtapeTrack","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/title","op":"replace","value":"SocialRadioMixtape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/fragments","value":[{"text":"SocialRadioMixtape","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/navigatorTitle","value":[{"text":"SocialRadioMixtape","kind":"identifier"}]}]}]}