{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel\/TrackId"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedtrackmodel\/trackid"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrackId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"SocialRadio"}],"symbolKind":"property","role":"symbol","externalID":"s:11SocialRadio15TunedTrackModelC0D2IdSivp","title":"TrackId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrackId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"abstract":[{"text":"The identifier of a track as an integer","type":"text"}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","kind":"symbol","title":"TunedTrackModel","url":"\/documentation\/socialradio\/tunedtrackmodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel/TrackId":{"role":"symbol","type":"topic","abstract":[{"text":"The identifier of a track as an integer","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel\/TrackId","title":"TrackId","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrackId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/socialradio\/tunedtrackmodel\/trackid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TunedTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title"},{"value":[{"text":"TunedTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments"},{"value":[{"text":"TunedTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle"}]}]}