{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Join","text":"Join","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"When you want to join an existing radio broadcast to listen to and interact with it, you use ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/joinLiveBroadcast(identifier:completion:)","isActive":true},{"text":" as shown below:","type":"text"}]},{"code":["public class MyApplication {","    \/\/ ...","    func didPressJoinLiveBroadcastButton(indentifier: String) -> Void {","    SocialRadio.instance.joinLiveBroadcast(identifier: identifier) { error, controller in","            self.present(controller, animated: true)","        }","    }","    \/\/ ...","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The UIViewController provided by this function is a fullcreen view that contains the Radio UI and will allow the user tyo curate the playlist, go live with it, end its live session and more. This UI can be minimised and also it can be dismissed by terminating the Radio session."}]},{"type":"paragraph","inlineContent":[{"text":"When you want to programatically force-end a radio session the user has created, use ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/endRadioSession(completion:)","type":"reference"},{"text":" as shown below:","type":"text"}]},{"code":["public class MyApplication {","    \/\/ ...","    func didPressEndRadioSessionButton() -> Void {","        SocialRadio.instance.endRadioSession()","    }","    \/\/ ...","}"],"syntax":"swift","type":"codeListing"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"How to start playing a broadcast by a user that is currently live","type":"text"}],"metadata":{"modules":[{"name":"SocialRadio"}],"role":"article","title":"Joining a broadcast","roleHeading":"Article"},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Joining-a-broadcast-article"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/joining-a-broadcast-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/joining-a-broadcast-article"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/endRadioSession(completion:)":{"role":"symbol","navigatorTitle":[{"text":"endRadioSessionWithCompletion:","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradio\/endradiosession(completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/endRadioSession(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endRadioSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"endRadioSession(completion:)","type":"topic","abstract":[{"type":"text","text":"Ends a Radio session. Be mindful if there is an ongoing Live radio show, this will terminate it without asking."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/joinLiveBroadcast(identifier:completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/joinLiveBroadcast(identifier:completion:)","title":"joinLiveBroadcast(identifier:completion:)","role":"symbol","abstract":[{"type":"text","text":"Starts playing a live mixtape as a consumer"}],"navigatorTitle":[{"text":"joinLiveBroadcastWithIdentifier:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"joinLiveBroadcast","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"radioViewController"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/socialradio\/socialradio\/joinlivebroadcast(identifier:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1endRadioSession(completion:)\/title","value":"endRadioSessionWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1endRadioSession(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endRadioSessionWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1joinLiveBroadcast(identifier:completion:)\/title","value":"joinLiveBroadcastWithIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1joinLiveBroadcast(identifier:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"joinLiveBroadcastWithIdentifier:completion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}