{"kind":"symbol","abstract":[{"text":"The moment in the mixtape that was playing when the comment was made","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiocomment\/mixtimestamp"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixTimestamp","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment\/mixTimestamp"},"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"s:11SocialRadio0aB7CommentC12mixTimestampSfSgvp","modules":[{"name":"SocialRadio"}],"title":"mixTimestamp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixTimestamp","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":"?","kind":"text"}],"symbolKind":"property"},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment/mixTimestamp":{"abstract":[{"text":"The moment in the mixtape that was playing when the comment was made","type":"text"}],"url":"\/documentation\/socialradio\/socialradiocomment\/mixtimestamp","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment\/mixTimestamp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixTimestamp","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"mixTimestamp"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment":{"abstract":[{"text":"SocialRadioComment models a comment","type":"text"}],"title":"SocialRadioComment","url":"\/documentation\/socialradio\/socialradiocomment","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioComment","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioComment","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","role":"collection","type":"topic","title":"SocialRadio","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/title","value":"SocialRadioComment","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/fragments","value":[{"text":"SocialRadioComment","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/navigatorTitle","value":[{"text":"SocialRadioComment","kind":"identifier"}],"op":"replace"}]}]}