{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiq\/initialise(config:tunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiq\/initialise(config:tunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)"]}],"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQ(cm)initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","title":"initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","modules":[{"name":"AutomixIQ"}],"role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"text":"initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig"},{"text":", ","kind":"text"},{"text":"tunedRestDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"symbolKind":"method"},"abstract":[{"text":"Initialiser for AutomixIQ to work against a Tuned Global backend","type":"text"},{"text":" ","type":"text"},{"text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"anchor":"Initialization","title":"Initialization","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)"],"generated":true}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","text":"AutomixIQConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStatusDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","text":"AutomixIQMusicCacheDelegate"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")? = nil)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"config","content":[{"inlineContent":[{"text":"The AutomixIQ Configuration","type":"text"}],"type":"paragraph"}]},{"name":"tunedRestDelegate","content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of feeding and renewing Tuned Global OAuth2 access tokens. See TunedRestDelegate."}],"type":"paragraph"}]},{"name":"automixIQStatusDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixIQStatusObserverDelegate."}]}]},{"name":"musicCacheDelegate","content":[{"inlineContent":[{"text":"The delegate in charge of saving and feeding in cached music to and from AutomixIQ","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","role":"collection","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","title":"AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"title":"AutomixIQStatusObserverDelegate","url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"title":"TunedRestDelegate","url":"\/documentation\/automixiq\/tunedrestdelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedRestDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"url":"\/documentation\/automixiq\/automixiqconfig","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQConfig"}],"abstract":[],"title":"AutomixIQConfig","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ":{"title":"AutomixIQ","abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ","navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/automixiq","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQ","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","text":"AutomixIQConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"automixIQStreamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate","text":"AutomixIQStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)","navigatorTitle":[{"kind":"identifier","text":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:"}],"title":"initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)","type":"topic","abstract":[{"type":"text","text":"Initialiser for AutomixIQ to work against any custom set of APIs."},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feeds all data and metadata the AutomixIQ needs."}],"kind":"symbol","url":"\/documentation\/automixiq\/automixiq\/initialise(config:automixiqstreamingdelegate:automixiqstatusdelegate:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate":{"abstract":[{"type":"text","text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","role":"symbol","navigatorTitle":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"type":"topic","title":"AutomixIQMusicCacheDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqmusiccachedelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)":{"url":"\/documentation\/automixiq\/automixiq\/initialise(config:tunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedRestDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedRestDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Initialiser for AutomixIQ to work against a Tuned Global backend","type":"text"},{"text":" ","type":"text"},{"text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID.","type":"text"}],"type":"topic","title":"initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"Initialization","title":"Initialization","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)"],"generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"initialiseWithConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","text":"AutomixIQConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":" "},{"kind":"identifier","text":"tunedRestDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)TunedRestDelegate","text":"id<TunedRestDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tunedRestDelegate"},{"text":" ","kind":"text"},{"text":"automixIQStatusDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<AutomixIQStatusObserverDelegate>","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"musicCacheDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<AutomixIQMusicCacheDelegate>","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"musicCacheDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The AutomixIQ Configuration","type":"text"}],"type":"paragraph"}],"name":"config"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of feeding and renewing Tuned Global OAuth2 access tokens. See TunedRestDelegate."}]}],"name":"tunedRestDelegate"},{"content":[{"inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixIQStatusObserverDelegate.","type":"text"}],"type":"paragraph"}],"name":"automixIQStatusDelegate"},{"content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of saving and feeding in cached music to and from AutomixIQ"}],"type":"paragraph"}],"name":"musicCacheDelegate"},{"content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"}],"name":"completion"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"AutomixIQStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title"},{"value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle"},{"value":"TunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title","value":"AutomixIQConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments","value":[{"kind":"identifier","text":"AutomixIQConfig"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle"},{"op":"replace","value":"AutomixIQ","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/navigatorTitle"},{"op":"replace","value":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)\/fragments"},{"op":"replace","value":"AutomixIQMusicCacheDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/fragments"},{"op":"replace","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/navigatorTitle"},{"op":"replace","value":"initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)\/fragments"}]}]}