{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/failedtrackloadidentifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/failedtrackloadidentifiers"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/failedTrackLoadIdentifiers","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"role":"symbol","title":"SocialRadioStatusVariable.failedTrackLoadIdentifiers","externalID":"c:@M@SocialRadio@E@SocialRadioStatusVariable@SocialRadioStatusVariableFailedTrackLoadIdentifiers","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers"}],"modules":[{"name":"SocialRadio"}]},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"title":"SocialRadioStatusVariable","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiostatusvariable","abstract":[{"type":"text","text":"SocialRadio status variable type"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable/failedTrackLoadIdentifiers":{"type":"topic","url":"\/documentation\/socialradio\/socialradiostatusvariable\/failedtrackloadidentifiers","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"role":"symbol","title":"SocialRadioStatusVariable.failedTrackLoadIdentifiers","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/failedTrackLoadIdentifiers","abstract":[],"navigatorTitle":[{"text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SocialRadioStatusVariableFailedTrackLoadIdentifiers","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SocialRadioStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle"},{"op":"replace","value":"SocialRadioStatusVariableFailedTrackLoadIdentifiers","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1failedTrackLoadIdentifiers\/title"},{"op":"replace","value":[{"text":"SocialRadioStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1failedTrackLoadIdentifiers\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}