{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeTrackOutOfBounds","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/removeTrackOutOfBounds"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"ErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}],"externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeRemoveTrackOutOfBounds","roleHeading":"Case","symbolKind":"case","modules":[{"name":"SocialRadio"}],"title":"ErrorCode.removeTrackOutOfBounds","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeTrackOutOfBounds","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errorcode\/removetrackoutofbounds"]},{"paths":["\/documentation\/socialradio\/errorcode\/removetrackoutofbounds"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/removeTrackOutOfBounds":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeRemoveTrackOutOfBounds"}],"title":"ErrorCode.removeTrackOutOfBounds","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/removeTrackOutOfBounds","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"removeTrackOutOfBounds","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/errorcode\/removetrackoutofbounds","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","title":"ErrorCode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/socialradio\/errorcode","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ErrorCodeRemoveTrackOutOfBounds","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1removeTrackOutOfBounds\/title","value":"ErrorCodeRemoveTrackOutOfBounds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1removeTrackOutOfBounds\/fragments","value":[{"kind":"identifier","text":"ErrorCodeRemoveTrackOutOfBounds"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}]}]}]}