{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel(py)duration","role":"symbol","modules":[{"name":"SocialRadio"}],"title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"duration"}],"symbolKind":"property"},"abstract":[{"type":"text","text":"Objective-C accessible member for the track duration"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel\/duration-5yno7","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdktrackmodel\/duration-5yno7"]},{"paths":["\/documentation\/socialradio\/automixsdktrackmodel\/duration-5yno7"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel":{"url":"\/documentation\/socialradio\/automixsdktrackmodel","abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}],"title":"AutomixSDKTrackModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","type":"topic","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel/duration-5yno7":{"url":"\/documentation\/socialradio\/automixsdktrackmodel\/duration-5yno7","abstract":[{"type":"text","text":"Objective-C accessible member for the track duration"}],"title":"duration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel\/duration-5yno7","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"duration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/fragments","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel~1duration-5yno7\/title","op":"replace","value":"duration"},{"op":"replace","value":[{"kind":"identifier","text":"duration"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel~1duration-5yno7\/fragments"}]}]}