{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canMixNow","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"variants":[{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/canmixnow"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/canmixnow"]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canMixNow"}],"roleHeading":"Case","navigatorTitle":[{"text":"AutomixIQStatusVariableCanMixNow","kind":"identifier"}],"title":"AutomixIQStatusVariable.canMixNow","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariableCanMixNow","role":"symbol","symbolKind":"case"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"canMixNow","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canMixNow":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canMixNow"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/canmixnow","kind":"symbol","title":"AutomixIQStatusVariable.canMixNow","abstract":[],"type":"topic","navigatorTitle":[{"text":"AutomixIQStatusVariableCanMixNow","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canMixNow","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","title":"SocialRadio","url":"\/documentation\/socialradio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","url":"\/documentation\/socialradio\/automixiqstatusvariable","title":"AutomixIQStatusVariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQStatusVariable"}],"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AutomixIQStatusVariableCanMixNow","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AutomixIQStatusVariableCanMixNow","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AutomixIQStatusVariableCanMixNow","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canMixNow\/title","value":"AutomixIQStatusVariableCanMixNow"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanMixNow"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canMixNow\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title","value":"AutomixIQStatusVariable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}