{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/playingtracktotaltime"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/playingtracktotaltime"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/playingTrackTotalTime"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackTotalTime","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"title":"SocialRadioStatusVariable.playingTrackTotalTime","modules":[{"name":"SocialRadio"}],"role":"symbol","externalID":"c:@M@SocialRadio@E@SocialRadioStatusVariable@SocialRadioStatusVariablePlayingTrackTotalTime","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playingTrackTotalTime","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"SocialRadioStatusVariablePlayingTrackTotalTime","kind":"identifier"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"title":"SocialRadioStatusVariable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiostatusvariable","abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable/playingTrackTotalTime":{"title":"SocialRadioStatusVariable.playingTrackTotalTime","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playingTrackTotalTime"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/playingTrackTotalTime","navigatorTitle":[{"text":"SocialRadioStatusVariablePlayingTrackTotalTime","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiostatusvariable\/playingtracktotaltime"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SocialRadioStatusVariablePlayingTrackTotalTime","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SocialRadioStatusVariablePlayingTrackTotalTime","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SocialRadioStatusVariablePlayingTrackTotalTime","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SocialRadioStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1playingTrackTotalTime\/title","value":"SocialRadioStatusVariablePlayingTrackTotalTime","op":"replace"},{"value":[{"text":"SocialRadioStatusVariablePlayingTrackTotalTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1playingTrackTotalTime\/fragments"}]}]}