{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialise(config:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Initialiser for Radio SDK to work against a custom backend and APIs."},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","kind":"typeIdentifier","text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"text":", ","kind":"text"},{"text":"automixIQStreamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","text":"AutomixIQStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate"},{"text":", ","kind":"text"},{"text":"socialRadioStreamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","text":"SocialRadioStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate"},{"text":", ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialBackendDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialBackendDelegate","text":"SocialBackendDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The SocialRadio configuration.","type":"text"}],"type":"paragraph"}],"name":"config"},{"content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of feeding all data and metadata the SocialRadio needs. See AutomixIQStreamingDelegate"}],"type":"paragraph"}],"name":"automixIQStreamingDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of fetching artwork and recommendations for tracks"}]}],"name":"socialRadioStreamingDelegate"},{"name":"socialRadioStatusDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from SocialRadio. See SocialRadioStatusObserverDelegate."}]}]},{"name":"socialRadioUIDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of presenting user interfaces the SocialRadio needs"}]}]},{"name":"socialBackendDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate to enable log in and storing credentials for your custom social layer."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradio\/initialise(config:automixiqstreamingdelegate:socialradiostreamingdelegate:socialradiostatusdelegate:socialradiouidelegate:socialbackenddelegate:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradio\/initialise(config:automixiqstreamingdelegate:socialradiostreamingdelegate:socialradiostatusdelegate:socialradiouidelegate:socialbackenddelegate:completion:)"]}],"metadata":{"role":"symbol","modules":[{"name":"SocialRadio"}],"title":"initialise(config:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)","symbolKind":"method","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"automixIQStreamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialRadioStreamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialBackendDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialBackendDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialBackendDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadio(cm)initialiseWithConfig:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:","navigatorTitle":[{"kind":"identifier","text":"initialiseWithConfig:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStreamingDelegate":{"title":"SocialRadioStreamingDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations."}],"url":"\/documentation\/socialradio\/socialradiostreamingdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/initialise(config:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Initialiser for Radio SDK to work against a custom backend and APIs."},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialise(config:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)","url":"\/documentation\/socialradio\/socialradio\/initialise(config:automixiqstreamingdelegate:socialradiostreamingdelegate:socialradiostatusdelegate:socialradiouidelegate:socialbackenddelegate:completion:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","text":"SocialRadioConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"automixIQStreamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate","text":"AutomixIQStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialRadioStreamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate","text":"SocialRadioStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialBackendDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialBackendDelegate","text":"SocialBackendDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"initialiseWithConfig:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:","kind":"identifier"}],"title":"initialise(config:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"title":"SocialRadioStatusObserverDelegate","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"kind":"symbol","type":"topic","title":"AutomixIQStreamingDelegate","url":"\/documentation\/socialradio\/automixiqstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio":{"role":"symbol","navigatorTitle":[{"text":"SocialRadio","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio","kind":"symbol","url":"\/documentation\/socialradio\/socialradio","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadio","kind":"identifier"}],"title":"SocialRadio","abstract":[{"type":"text","text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"kind":"symbol","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"url":"\/documentation\/socialradio\/socialradiouidelegate","title":"SocialRadioUIDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialBackendDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialBackendDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","role":"symbol","title":"SocialBackendDelegate","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/socialbackenddelegate","navigatorTitle":[{"kind":"identifier","text":"SocialBackendDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioConfig"}],"url":"\/documentation\/socialradio\/socialradioconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioConfig"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","abstract":[],"title":"SocialRadioConfig","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initialiseWithConfig:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initialiseWithConfig:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"initialiseWithConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SocialRadioConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"automixIQStreamingDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate","kind":"typeIdentifier","text":"id<AutomixIQStreamingDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"automixIQStreamingDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialRadioStreamingDelegate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate","kind":"typeIdentifier","text":"id<SocialRadioStreamingDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"socialRadioStreamingDelegate"},{"kind":"text","text":" "},{"text":"socialRadioStatusDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SocialRadioStatusObserverDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"text":") ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"socialRadioUIDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SocialRadioUIDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialRadioUIDelegate"},{"text":") ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"socialBackendDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<SocialBackendDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialBackendDelegate"},{"text":") ","kind":"text"},{"text":"socialBackendDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The SocialRadio configuration."}],"type":"paragraph"}],"name":"config"},{"content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of feeding all data and metadata the SocialRadio needs. See AutomixIQStreamingDelegate"}],"type":"paragraph"}],"name":"automixIQStreamingDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of fetching artwork and recommendations for tracks","type":"text"}]}],"name":"socialRadioStreamingDelegate"},{"content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from SocialRadio. See SocialRadioStatusObserverDelegate."}],"type":"paragraph"}],"name":"socialRadioStatusDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of presenting user interfaces the SocialRadio needs","type":"text"}]}],"name":"socialRadioUIDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate to enable log in and storing credentials for your custom social layer."}]}],"name":"socialBackendDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}],"name":"completion"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SocialRadioStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/title"},{"op":"replace","value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/navigatorTitle"},{"op":"replace","value":"initialiseWithConfig:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialise(config:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initialiseWithConfig:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialise(config:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)\/fragments"},{"op":"replace","value":"SocialRadioStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle"},{"op":"replace","value":"SocialRadio","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/title"},{"op":"replace","value":[{"text":"SocialRadio","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadio"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/navigatorTitle"},{"op":"replace","value":"SocialRadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title"},{"op":"replace","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle"},{"op":"replace","value":"SocialBackendDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialBackendDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialBackendDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/navigatorTitle"},{"op":"replace","value":"SocialRadioConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title"},{"op":"replace","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments"},{"op":"replace","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle"}]}]}