{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiq\/automixiqerror(code:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiq\/automixiqerror(code:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixIQError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","preciseIdentifier":"c:@M@AutomixIQ@E@ErrorCode","text":"ErrorCode"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/automixIQError(code:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQ(cm)automixIQErrorWithCode:","title":"automixIQError(code:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixIQError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorCode","preciseIdentifier":"c:@M@AutomixIQ@E@ErrorCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"text":"automixIQErrorWithCode:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ":{"title":"AutomixIQ","navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}],"abstract":[{"type":"text","text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"url":"\/documentation\/automixiq\/automixiq","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"abstract":[],"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","title":"ErrorCode","url":"\/documentation\/automixiq\/errorcode","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/automixIQError(code:)":{"kind":"symbol","url":"\/documentation\/automixiq\/automixiq\/automixiqerror(code:)","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"automixIQErrorWithCode:","kind":"identifier"}],"title":"automixIQError(code:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automixIQError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ErrorCode","preciseIdentifier":"c:@M@AutomixIQ@E@ErrorCode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/automixIQError(code:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"automixIQErrorWithCode:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"automixIQErrorWithCode:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"automixIQErrorWithCode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@ErrorCode","text":"ErrorCode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"code"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/title","op":"replace","value":"AutomixIQ"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/fragments","op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1automixIQError(code:)\/title","op":"replace","value":"automixIQErrorWithCode:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1automixIQError(code:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"automixIQErrorWithCode:","kind":"identifier"}]}]}]}