{"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqtunedmusiccachedelegate"]},{"paths":["\/documentation\/automixiq\/automixiqtunedmusiccachedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs","title":"Initializing AutomixIQ for use with Tuned Global’s APIs","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"abstract":[{"text":"AutomixIQTunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/getCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/getTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate","modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"symbolKind":"protocol","title":"AutomixIQTunedMusicCacheDelegate","roleHeading":"Protocol"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"role":"symbol","title":"AutomixIQConfig","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"abstract":[],"url":"\/documentation\/automixiq\/automixiqconfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQConfig","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate/trackDownloadCompleted(trackId:data:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackDownloadCompleted"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device."}],"type":"topic","url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate\/trackdownloadcompleted(trackid:data:)","required":true,"title":"trackDownloadCompleted(trackId:data:)","navigatorTitle":[{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate/getTrackMetadata(trackId:)":{"url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate\/gettrackmetadata(trackid:)","required":true,"title":"getTrackMetadata(trackId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTrackMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AutomixIQTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQTrackModel"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/getTrackMetadata(trackId:)","navigatorTitle":[{"text":"getTrackMetadataWithTrackId:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-article":{"role":"article","kind":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","url":"\/documentation\/automixiq\/initialising-automixiq-article","type":"topic","abstract":[{"type":"text","text":"How to validate your client and start using the AutomixIQ SDK with Tuned Global APIs"}],"title":"Initializing AutomixIQ"},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","title":"NSObject"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate/trackDownloadProgressChanged(trackId:progress:)":{"abstract":[{"text":"Called by AutomixIQ when a track download progress has changed.","type":"text"}],"required":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadProgressChanged"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"title":"trackDownloadProgressChanged(trackId:progress:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate":{"role":"symbol","title":"AutomixIQTunedMusicCacheDelegate","navigatorTitle":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQTunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate/getCachedTrack(trackId:)":{"url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate\/getcachedtrack(trackid:)","required":true,"title":"getCachedTrack(trackId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCachedTrack"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/getCachedTrack(trackId:)","navigatorTitle":[{"text":"getCachedTrackWithTrackId:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate":{"type":"topic","title":"AutomixIQTunedRestDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqtunedrestdelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AutomixIQTunedMusicCacheDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}]},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/getCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/getTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)"],"generated":true}],"path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Initializing AutomixIQ for use with Tuned Global’s APIs","generated":true,"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"]}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title","value":"AutomixIQConfig"},{"op":"replace","value":[{"text":"AutomixIQConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}]},{"value":"trackDownloadCompletedWithTrackId:data:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1trackDownloadCompleted(trackId:data:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1trackDownloadCompleted(trackId:data:)\/fragments"},{"op":"replace","value":"getTrackMetadataWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1getTrackMetadata(trackId:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1getTrackMetadata(trackId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getTrackMetadataWithTrackId:","kind":"identifier"}],"op":"replace"},{"value":"trackDownloadProgressChangedWithTrackId:progress:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"op":"replace"},{"op":"replace","value":"AutomixIQTunedMusicCacheDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/fragments","op":"replace","value":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1getCachedTrack(trackId:)\/title","value":"getCachedTrackWithTrackId:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCachedTrackWithTrackId:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1getCachedTrack(trackId:)\/fragments"},{"op":"replace","value":"AutomixIQTunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/fragments","value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}