{"variants":[{"paths":["\/documentation\/automixiq\/automixiqloglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqloglevel"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelDebug","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelError","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelFatal","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelInfo","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelTrace","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelWarning"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/Equatable-Implementations","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/RawRepresentable-Implementations"]}],"abstract":[{"type":"text","text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH","doc:\/\/org.cocoapods.AutomixIQ\/SY"],"kind":"relationships"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate"],"title":"Initializing AutomixIQ for use with a custom backend","anchor":"Initializing-AutomixIQ-for-use-with-a-custom-backend"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixIQLogLevel","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ logs with no filter"}]}],"name":"logLevelTrace"},{"name":"logLevelDebug","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ logs everything except low level details"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ logs everything except low level details and debug statements"}]}],"name":"logLevelInfo"},{"name":"logLevelWarning","content":[{"type":"paragraph","inlineContent":[{"text":"AutomixIQ only logs errors and warnings","type":"text"}]}]},{"name":"logLevelError","content":[{"inlineContent":[{"type":"text","text":"AutomixIQ only logs errors"}],"type":"paragraph"}]},{"name":"logLevelFatal","content":[{"inlineContent":[{"type":"text","text":"AutomixIQ only logs fatal errors"}],"type":"paragraph"}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"title":"AutomixIQLogLevel","externalID":"c:@M@AutomixIQ@E@AutomixIQLogLevel","role":"symbol","modules":[{"name":"AutomixIQ"}],"roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixIQLogLevel","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate":{"url":"\/documentation\/automixiq\/automixiqstreamingdelegate","abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate","type":"topic","kind":"symbol","title":"AutomixIQStreamingDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/Equatable-Implementations":{"url":"\/documentation\/automixiq\/automixiqloglevel\/equatable-implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/Equatable-Implementations","title":"Equatable Implementations"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-with-custom-backend-article":{"kind":"article","title":"Initializing AutomixIQ with a custom backend","abstract":[{"text":"How to validate your client and start using the AutomixIQ SDK with a custom backend","type":"text"}],"role":"article","url":"\/documentation\/automixiq\/initialising-automixiq-with-custom-backend-article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/logLevelFatal":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelFatal","abstract":[],"type":"topic","url":"\/documentation\/automixiq\/automixiqloglevel\/loglevelfatal","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelFatal"}],"navigatorTitle":[{"text":"AutomixIQLogLevelLogLevelFatal","kind":"identifier"}],"title":"AutomixIQLogLevel.logLevelFatal","role":"symbol","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/init(rawValue:)":{"url":"\/documentation\/automixiq\/automixiqloglevel\/init(rawvalue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/init(rawValue:)","kind":"symbol","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/logLevelInfo":{"navigatorTitle":[{"text":"AutomixIQLogLevelLogLevelInfo","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelInfo","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelInfo"}],"url":"\/documentation\/automixiq\/automixiqloglevel\/loglevelinfo","title":"AutomixIQLogLevel.logLevelInfo","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/RawRepresentable-Implementations","kind":"article","abstract":[],"type":"topic","url":"\/documentation\/automixiq\/automixiqloglevel\/rawrepresentable-implementations","role":"collectionGroup"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel":{"url":"\/documentation\/automixiq\/automixiqloglevel","navigatorTitle":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel","title":"AutomixIQLogLevel","abstract":[{"text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQLogLevel"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/logLevelError":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelError"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelError","type":"topic","abstract":[],"navigatorTitle":[{"text":"AutomixIQLogLevelLogLevelError","kind":"identifier"}],"title":"AutomixIQLogLevel.logLevelError","kind":"symbol","url":"\/documentation\/automixiq\/automixiqloglevel\/loglevelerror","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/logLevelDebug":{"title":"AutomixIQLogLevel.logLevelDebug","navigatorTitle":[{"kind":"identifier","text":"AutomixIQLogLevelLogLevelDebug"}],"url":"\/documentation\/automixiq\/automixiqloglevel\/logleveldebug","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelDebug","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelDebug"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/logLevelTrace":{"role":"symbol","title":"AutomixIQLogLevel.logLevelTrace","navigatorTitle":[{"text":"AutomixIQLogLevelLogLevelTrace","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelTrace","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqloglevel\/logleveltrace","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelTrace"},"doc://org.cocoapods.AutomixIQ/SY":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/SQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/logLevelWarning":{"url":"\/documentation\/automixiq\/automixiqloglevel\/loglevelwarning","navigatorTitle":[{"text":"AutomixIQLogLevelLogLevelWarning","kind":"identifier"}],"title":"AutomixIQLogLevel.logLevelWarning","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"logLevelWarning","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelWarning"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixIQLogLevel","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelDebug","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelError","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelFatal","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelInfo","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelTrace","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelWarning"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate"],"generated":true,"anchor":"Initializing-AutomixIQ-for-use-with-a-custom-backend","title":"Initializing AutomixIQ for use with a custom backend"}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQLogLevel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/title","value":"AutomixIQStreamingDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/fragments","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/navigatorTitle"},{"value":"AutomixIQLogLevelLogLevelFatal","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelFatal\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelFatal\/fragments","value":[{"text":"AutomixIQLogLevelLogLevelFatal","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelInfo\/title","op":"replace","value":"AutomixIQLogLevelLogLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelInfo\/fragments","value":[{"kind":"identifier","text":"AutomixIQLogLevelLogLevelInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/title","value":"AutomixIQLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/fragments","value":[{"text":"AutomixIQLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelError\/title","value":"AutomixIQLogLevelLogLevelError"},{"value":[{"text":"AutomixIQLogLevelLogLevelError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelError\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelDebug\/title","op":"replace","value":"AutomixIQLogLevelLogLevelDebug"},{"value":[{"text":"AutomixIQLogLevelLogLevelDebug","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelDebug\/fragments"},{"op":"replace","value":"AutomixIQLogLevelLogLevelTrace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelTrace\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelTrace\/fragments","op":"replace","value":[{"text":"AutomixIQLogLevelLogLevelTrace","kind":"identifier"}]},{"op":"replace","value":"AutomixIQLogLevelLogLevelWarning","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelWarning\/title"},{"op":"replace","value":[{"text":"AutomixIQLogLevelLogLevelWarning","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelWarning\/fragments"}]}]}