{"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/uniqueDeviceIdentifier()"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"]}],"seeAlsoSections":[{"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs","title":"Initializing AutomixIQ for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"],"generated":true}],"metadata":{"role":"symbol","title":"AutomixIQTunedRestDelegate","navigatorTitle":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate","roleHeading":"Protocol","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"symbolKind":"protocol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/automixiq\/automixiqtunedrestdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqtunedrestdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate/logAutomixIQMessage(logLevel:message:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","abstract":[{"text":"Called by AutomixIQ when it wishes to output a log message","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixIQLogLevel","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQLogLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/automixiq\/automixiqtunedrestdelegate\/logautomixiqmessage(loglevel:message:)","title":"logAutomixIQMessage(logLevel:message:)","navigatorTitle":[{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate":{"type":"topic","title":"AutomixIQTunedRestDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqtunedrestdelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"role":"symbol","title":"AutomixIQConfig","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"abstract":[],"url":"\/documentation\/automixiq\/automixiqconfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQConfig","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate":{"role":"symbol","title":"AutomixIQTunedMusicCacheDelegate","navigatorTitle":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQTunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)":{"url":"\/documentation\/automixiq\/automixiqtunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)","title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","role":"symbol","abstract":[{"text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"asyncGetAuthenticatedDevice","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedDeviceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}]},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","title":"NSObject"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate/uniqueDeviceIdentifier()":{"url":"\/documentation\/automixiq\/automixiqtunedrestdelegate\/uniquedeviceidentifier()","title":"uniqueDeviceIdentifier()","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/uniqueDeviceIdentifier()","required":true,"abstract":[{"type":"text","text":"Called by AutomixIQ to request the unique identifier for the users device as a string."},{"text":" ","type":"text"},{"type":"text","text":"On iOS this is generally the Identifier for Vendor."},{"text":" ","type":"text"},{"text":"It can be any string as long as it is unique","type":"text"},{"type":"text","text":" "},{"type":"text","text":"AutomixIQ will use this string as the UniqueId if it needs to register the device for playback"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uniqueDeviceIdentifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","navigatorTitle":[{"text":"uniqueDeviceIdentifier","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","abstract":[{"type":"text","text":"Called by AutomixIQ when initialised against a Tuned Global backend or when its access token has expired."}],"type":"topic","kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/automixiq\/automixiqtunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:refreshtoken:tokentype:completion:)","title":"tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tunedRestTokenExpired"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"tunedUserId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"oldAccessToken"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"refreshToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tokenType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"credentials"},{"text":": ","kind":"text"},{"text":"AutomixIQTunedAuthenticationResponse","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQTunedAuthenticationResponse","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"tunedUserId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-article":{"role":"article","kind":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","url":"\/documentation\/automixiq\/initialising-automixiq-article","type":"topic","abstract":[{"type":"text","text":"How to validate your client and start using the AutomixIQ SDK with Tuned Global APIs"}],"title":"Initializing AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"AutomixIQTunedRestDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/uniqueDeviceIdentifier()"],"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"],"type":"inheritsFrom"}]},{"value":[{"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"],"title":"Initializing AutomixIQ for use with Tuned Global’s APIs","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedRestDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"logAutomixIQMessageWithLogLevel:message:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/title","value":"AutomixIQTunedRestDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/fragments","value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}]},{"value":"AutomixIQConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title"},{"value":[{"kind":"identifier","text":"AutomixIQConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle","value":[{"text":"AutomixIQConfig","kind":"identifier"}],"op":"replace"},{"value":"AutomixIQTunedMusicCacheDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/fragments"},{"value":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/title","op":"replace","value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1uniqueDeviceIdentifier()\/title","op":"replace","value":"uniqueDeviceIdentifier"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"uniqueDeviceIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1uniqueDeviceIdentifier()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/title","op":"replace","value":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/fragments"}]}]}