{"seeAlsoSections":[{"generated":true,"anchor":"Persistency","title":"Persistency","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLog","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogAttributes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogID","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLog","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogAttributes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogID","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"SocialRadio"}],"role":"article","roleHeading":"Article","title":"Persistency"},"kind":"article","primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Music-Metadata-Database","level":2,"text":"Music Metadata Database"},{"type":"paragraph","inlineContent":[{"text":"In the Caches Directory, AutomixIQ keeps a light weight sql database to store the metadata of tracks that have been played for subsequent lookup. This file is called “music.db” and if deleted will be recreated on launch.","type":"text"}]},{"type":"heading","anchor":"Music-Analysis-Database","level":2,"text":"Music Analysis Database"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the Caches Directory, AutomixIQ keeps a light weight sql database to store the analysis data of tracks that have been played for subsequent lookup. This analysis is required to produce beat-matched transitions. This file is called “paralysis.db” and if deleted will be recreated on launch."}]},{"type":"heading","anchor":"Playback-Log","level":2,"text":"Playback Log"},{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ stores offline playback logs for subsequent reporting on a Core Data database, modelled by the following classes:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLog"}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogAttributes"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogID","type":"reference"}]}]}]},{"type":"heading","anchor":"Transition-Playback-Log","level":2,"text":"Transition Playback Log"},{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ stores offline transition playback logs for subsequent reporting on a Core Data database, modelled by the following classes:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLog","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogAttributes","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogID","type":"reference","isActive":true}]}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/persistency-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/persistency-article"]}],"abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Persistency-article","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"title":"AutomixIQPlaybackEventType","kind":"symbol","url":"\/documentation\/socialradio\/automixiqplaybackeventtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlayLogAttributes":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogAttributes","title":"AutomixIQPlayLogAttributes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}],"url":"\/documentation\/socialradio\/automixiqplaylogattributes"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTransitionLog":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQTransitionLog","kind":"identifier"}],"kind":"symbol","title":"AutomixIQTransitionLog","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLog","role":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixiqtransitionlog","navigatorTitle":[{"text":"AutomixIQTransitionLog","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTransitionLogID":{"url":"\/documentation\/socialradio\/automixiqtransitionlogid","type":"topic","role":"symbol","kind":"symbol","title":"AutomixIQTransitionLogID","navigatorTitle":[{"text":"AutomixIQTransitionLogID","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogID","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQTransitionLogID","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlayLogID":{"url":"\/documentation\/socialradio\/automixiqplaylogid","type":"topic","role":"symbol","kind":"symbol","title":"AutomixIQPlayLogID","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogID"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogID","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlayLogID"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTransitionLogAttributes":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogAttributes","url":"\/documentation\/socialradio\/automixiqtransitionlogattributes","title":"AutomixIQTransitionLogAttributes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQTransitionLogAttributes","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AutomixIQTransitionLogAttributes","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlayLog":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLog","title":"AutomixIQPlayLog","navigatorTitle":[{"text":"AutomixIQPlayLog","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlayLog","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/automixiqplaylog","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"anchor":"Persistency","generated":true,"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType"]}],"path":"\/seeAlsoSections","op":"replace"},{"value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/fragments","op":"replace"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/navigatorTitle","op":"replace"}]}]}