{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQWaveformModel(im)init","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method"},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixiqwaveformmodel\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQWaveformModel/init":{"kind":"symbol","url":"\/documentation\/automixiq\/automixiqwaveformmodel\/init","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel\/init","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"title":"init","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","kind":"symbol","title":"AutomixIQ","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQWaveformModel":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQWaveformModel"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"type":"topic","title":"AutomixIQWaveformModel","kind":"symbol","url":"\/documentation\/automixiq\/automixiqwaveformmodel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/title","value":"AutomixIQWaveformModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/fragments","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}