{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/tunedartistmodel\/init"]}],"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"title":"init","role":"symbol","externalID":"c:@M@AutomixIQ@objc(cs)TunedArtistModel(im)init"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel\/init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedArtistModel/init":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/automixiq\/tunedartistmodel\/init","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel\/init","title":"init","type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedArtistModel":{"abstract":[{"text":"TunedArtistModel models an artist.","type":"text"}],"role":"symbol","url":"\/documentation\/automixiq\/tunedartistmodel","kind":"symbol","title":"TunedArtistModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedArtistModel"}],"navigatorTitle":[{"kind":"identifier","text":"TunedArtistModel"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","url":"\/documentation\/automixiq","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","title":"AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TunedArtistModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel\/title","op":"replace"},{"value":[{"text":"TunedArtistModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel\/fragments","op":"replace"},{"value":[{"text":"TunedArtistModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel\/navigatorTitle","op":"replace"}]}]}