{"metadata":{"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"cocreators","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"cocreators","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtape(py)cocreators","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cocreators"},{"text":": [","kind":"text"},{"text":"AutomixSDKUser","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKUser","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"abstract":[{"text":"The list of cocreators for this mixtape","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cocreators","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKUser","text":"AutomixSDKUser"},{"text":"]?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/cocreators","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/automixsdkmixtape\/cocreators"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkmixtape\/cocreators"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/cocreators":{"abstract":[{"text":"The list of cocreators for this mixtape","type":"text"}],"navigatorTitle":[{"text":"cocreators","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/cocreators","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/cocreators","type":"topic","title":"cocreators","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cocreators","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AutomixSDKUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKUser"},{"text":"]?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape":{"abstract":[{"text":"AutomixSDKMixtape models a mixtape","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtape","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape","title":"AutomixSDKMixtape","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKUser":{"abstract":[{"text":"AutomixSDKUser models a user","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKUser","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKUser"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkuser","title":"AutomixSDKUser","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"cocreators","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cocreators","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<AutomixSDKUser *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cocreators"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1cocreators\/title","value":"cocreators"},{"value":[{"kind":"identifier","text":"cocreators"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1cocreators\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/title","value":"AutomixSDKMixtape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/fragments","value":[{"kind":"identifier","text":"AutomixSDKMixtape"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/navigatorTitle","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}]},{"value":"AutomixSDKUser","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/fragments","value":[{"kind":"identifier","text":"AutomixSDKUser"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/navigatorTitle","value":[{"text":"AutomixSDKUser","kind":"identifier"}]}]}]}