{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack"]]},"variants":[{"paths":["\/documentation\/socialradio\/socialradiomixtapetrack\/isadvertisement"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack\/isAdvertisement"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAdvertisement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"True if this track is an ad, false otherwise"}],"metadata":{"externalID":"s:11SocialRadio0aB12MixtapeTrackC15isAdvertisementSbSgvp","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAdvertisement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?"}],"role":"symbol","title":"isAdvertisement","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack/isAdvertisement":{"abstract":[{"text":"True if this track is an ad, false otherwise","type":"text"}],"url":"\/documentation\/socialradio\/socialradiomixtapetrack\/isadvertisement","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAdvertisement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack\/isAdvertisement","role":"symbol","title":"isAdvertisement"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"title":"SocialRadioMixtapeTrack","kind":"symbol","url":"\/documentation\/socialradio\/socialradiomixtapetrack","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/title","value":"SocialRadioMixtapeTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/navigatorTitle","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}]}]}]}