{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqplaybackmode\/init(rawvalue:)"]}],"metadata":{"externalID":"s:11SocialRadio21AutomixIQPlaybackModeO8rawValueACSgSi_tcfc","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Initializer","title":"init(rawValue:)","modules":[{"name":"SocialRadio"}],"symbolKind":"init"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/init(rawValue:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode/init(rawValue:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/init(rawValue:)","kind":"symbol","type":"topic","title":"init(rawValue:)","url":"\/documentation\/socialradio\/automixiqplaybackmode\/init(rawvalue:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode":{"title":"AutomixIQPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqplaybackmode","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQPlaybackMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"AutomixIQPlaybackMode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackMode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQPlaybackMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}