{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@SocialRadio@E@AutomixIQPlaybackMode@AutomixIQPlaybackModeLiveConsumption","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveConsumption"}],"roleHeading":"Case","navigatorTitle":[{"text":"AutomixIQPlaybackModeLiveConsumption","kind":"identifier"}],"symbolKind":"case","title":"AutomixIQPlaybackMode.liveConsumption","role":"symbol","modules":[{"name":"SocialRadio"}]},"variants":[{"paths":["\/documentation\/socialradio\/automixiqplaybackmode\/liveconsumption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqplaybackmode\/liveconsumption"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/liveConsumption"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"liveConsumption","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode/liveConsumption":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackModeLiveConsumption","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqplaybackmode\/liveconsumption","title":"AutomixIQPlaybackMode.liveConsumption","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/liveConsumption","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveConsumption","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode":{"title":"AutomixIQPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqplaybackmode","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQPlaybackMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AutomixIQPlaybackModeLiveConsumption","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixIQPlaybackModeLiveConsumption","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixIQPlaybackModeLiveConsumption"}],"platforms":["iOS"]}]}},{"op":"replace","value":"AutomixIQPlaybackModeLiveConsumption","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode~1liveConsumption\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode~1liveConsumption\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackModeLiveConsumption"}]},{"value":"AutomixIQPlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/fragments","value":[{"text":"AutomixIQPlaybackMode","kind":"identifier"}],"op":"replace"},{"value":[{"text":"AutomixIQPlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}