{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"AutomixIQ"}],"roleHeading":"Article","role":"article","title":"Initializing AutomixIQ"},"sections":[],"abstract":[{"text":"How to validate your client and start using the AutomixIQ SDK with Tuned Global APIs","type":"text"}],"variants":[{"paths":["\/documentation\/automixiq\/initialising-automixiq-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/initialising-automixiq-article"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"],"title":"Initializing AutomixIQ for use with Tuned Global’s APIs","generated":true,"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs"}],"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Essentials","text":"Essentials"},{"type":"paragraph","inlineContent":[{"text":"This document explains how to integrate AutomixIQ with your application if it is already using Tuned Global’s backend to access tracks and metadata","type":"text"}]},{"type":"heading","level":3,"anchor":"Initialization-with-Tuned-Globals-API","text":"Initialization with Tuned Global’s API"},{"inlineContent":[{"text":"In order to initialise AutomixIQ against Tuned Global’s API and services you need the following:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Tuned Global Store ID","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Tuned Global Application ID","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Device Country Code","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optionally you may also implement a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate"}]}]}]},{"syntax":"swift","type":"codeListing","code":["func application(_ application: UIApplication, ","                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","    \/\/ ...","","    let tunedRestDelegate: TunedRestDelegate = myTunedRestDelegate","    let musicCacheDelegate: AutomixIQMusicCacheDelegate = myMusicCacheDelegate","    let automixIQStatusObserverDelegate: AutomixIQStatusObserverDelegate = myAutomixIQStatusObserverDelegate","    let countryCode: String = myCountryCode \/\/ \"US\" ? \"AU\"?","    let storeId: String = myTunedStoreId","    let applicationId: String = myApplicationId","    let myAPIKey: String = myApplicationKey","    let config = AutomixIQConfig(apiKey: myAPIKey, country: countryCode, storeId: storeId, applicationId: applicationId)","    AutomixIQ.initialise(config: config,","              tunedRestDelegate: tunedRestDelegate,","                         automixIQStatusDelegate: automixIQStatusObserverDelegate,","                         musicCacheDelegate: musicCacheDelegate)","    { error in","        if error != nil {","            \/\/ This means you are forbidden to use the Automix SDK or you have no internet connection.","            return","        }","        \/\/ The Automix SDK public functions can be used from this point onwards :)","    }","","    \/\/ ...","}"]},{"type":"heading","level":4,"text":"TunedRestDelegate","anchor":"TunedRestDelegate"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"AutomixIQ requires your applications OAuth2 access & refresh tokens in order to take over playback, provided via"},{"type":"text","text":" "},{"type":"codeVoice","code":"TunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)"}],"type":"paragraph"}]}]},{"syntax":"swift","type":"codeListing","code":["public class MyTunedRestDelegate: NSObject, TunedRestDelegate {","    \/\/ ...","    public func tunedRestTokenExpired(deviceIdentifierForVendor: String, countryCode: String,","                                      tunedUserId: String?,","                                      oldAccessToken: String?, refreshToken: String?, tokenType: String?,","                                      completion: @escaping (Error?, TunedAuthenticationResponse?, _ tunedUserId: String?) -> Void)","    {","        let response: TunedAuthenticationResponse = TunedAuthenticationResponse.init()","        response.access_token = myAccessToken","        response.token_type = myTokenType","        response.expires_in = myTokenExpiresIn","        response.refresh_token = myRefreshToken","        response.tuned_user_id = myTunedUserId","        completion(response, nil)","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"AutomixIQ requires your client’s authenticated device, provided via","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)"}]}]}]},{"type":"codeListing","code":["public class MyTunedRestDelegate: NSObject, TunedRestDelegate {","    \/\/ ...","    public func asyncGetAuthenticatedDevice(deviceIdentifierForVendor: String, completion: @escaping (_ error: Error?, _ tunedDeviceId: String?) -> Void) -> Void {","        \/\/ ...","        let myTunedDeviceId = String(tunedDeviceId)","        return completion(nil, myTunedDeviceId)","    }","    \/\/ ...","}"],"syntax":"swift"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"AutomixIQ requires a unique device identifier, generally the identifierForVendor provided by Apple should work: Provided via","type":"text"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/uniqueDeviceIdentifier()","isActive":true}],"type":"paragraph"}]}]},{"type":"codeListing","code":["public class MyTunedRestDelegate: NSObject, TunedRestDelegate {","    \/\/ ...","    public func uniqueDeviceIdentifier() -> Void) -> String {","        \/\/ ...","        let myUniqueIdentifier = String(identifierForVendor)","        return myUniqueIdentifier","    }","    \/\/ ...","}"],"syntax":"swift"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"AutomixIQ needs to learn if it should log playback events to Tuned’s backend on your behalf or if you will implement logging yourself: Provided via","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/automaticallyLogPlayback()"}],"type":"paragraph"}]}]},{"type":"codeListing","code":["public class MyTunedRestDelegate: NSObject, TunedRestDelegate {","    \/\/ ...","    public func automaticallyLogPlayback() -> Bool {","        return false","    }","    \/\/ ...","}"],"syntax":"swift"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Should you need access to the AutomixIQ log in order to debug your implementation, you can print its output via this delegate as well. You can do that via","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","type":"reference"}]}]}]},{"type":"codeListing","code":["public class MyTunedRestDelegate: NSObject, TunedRestDelegate {","    \/\/ ...","    public func logAutomixIQMessage(logLevel: TunedLogLevel, message: String) {","        #if DEBUG","            NSLog(message)","        #endif","    }","    \/\/ ...","}"],"syntax":"swift"},{"type":"heading","anchor":"AutomixIQMusicCacheDelegate","text":"AutomixIQMusicCacheDelegate","level":4},{"type":"paragraph","inlineContent":[{"text":"AutomixIQ can be used for offline playback using cached music data. In order to provide and update cached music data and metadata, set the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate"},{"text":" of AutomixIQ using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setMusicCacheDelegate(_:)"},{"text":". This is optional and can be nil.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"This provides hooks to inject cached track audio data and metadata, preventing AutomixIQ from having to request this data from Tuned Global’s API if they are already available. This also enables offline playback when all required data is available on the device","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is done via "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getTrackMetadata(trackId:)"}]},{"syntax":"swift","type":"codeListing","code":["public class MyMusicCacheDelegate: NSObject, AutomixIQMusicCacheDelegate {","    \/\/ ...","    public func getTrackMetadata(trackId: String?) -> TunedTrackModel? {","        \/\/ If I have this track cached, I should be able to tell its metadata","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.metadataForTrack(trackId)","    }","    \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"text":"and ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getCachedTrack(trackId:)","isActive":true,"type":"reference"}]},{"syntax":"swift","type":"codeListing","code":["public class MyMusicCacheDelegate: NSObject, AutomixIQMusicCacheDelegate {","    \/\/ ...","    public func getCachedTrack(trackId: String) -> Data? {","        \/\/ If I have this track cached, I should be able to decrypt it and send the data","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.unencryptedDataForTrack(trackId)","    }","    \/\/ ...","}"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"AutomixIQ will download the tracks it needs to play when they are not provided from your cache. It will do so lazily (as required for playback or transition analysis). When a track finishes downloading, AutomixIQ will pass the audio data back to your application to cache if required.","type":"text"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is done via "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","type":"reference"}]},{"type":"codeListing","syntax":"swift","code":["public class MyMusicCacheDelegate: NSObject, AutomixIQMusicCacheDelegate {","    \/\/ ...","    public func trackDownloadCompleted(trackId: String, data: Data) {","        \/\/ Automix SDK finished downloading a track. If I have offline playback or encrypted cache capabilities I should act accordingly here","        return self.cacheTrack(trackId, data:data)","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ will also notify your delegate of download progress."}]}]}]},{"type":"paragraph","inlineContent":[{"text":"This is done via ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)"}]},{"type":"codeListing","syntax":"swift","code":["public class MyMusicCacheDelegate: NSObject, AutomixIQMusicCacheDelegate {","    \/\/ ...","    public func trackDownloadProgressChanged(trackId: String, progress: Swift.Float) {","        self.updateTrackDownloadProgress(identifier: trackId, progress: progress)","        return","    }","    \/\/ ...","}"]},{"type":"heading","anchor":"AutomixIQStatusObserverDelegate","level":4,"text":"AutomixIQStatusObserverDelegate"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","isActive":true},{"type":"text","text":" is responsible for updating your player’s UI, please refer to "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","isActive":true}]},{"type":"heading","anchor":"Checking-if-AutomixIQ-is-initialised","level":3,"text":"Checking if AutomixIQ is initialised"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To check wether AutomixIQ is currently initialised, use"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialised()"}]}]}]}],"kind":"content"}],"kind":"article","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","type":"topic","abstract":[{"text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"title":"AutomixIQStatusObserverDelegate","kind":"symbol","url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate","navigatorTitle":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/logAutomixIQMessage(logLevel:message:)":{"type":"topic","url":"\/documentation\/automixiq\/tunedrestdelegate\/logautomixiqmessage(loglevel:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"logAutomixIQMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"logLevel","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TunedLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@TunedLogLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","abstract":[{"text":"Called by AutomixIQ when it wishes to output a log message","type":"text"}],"title":"logAutomixIQMessage(logLevel:message:)","navigatorTitle":[{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate/getTrackMetadata(trackId:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getTrackMetadata(trackId:)","role":"symbol","url":"\/documentation\/automixiq\/automixiqmusiccachedelegate\/gettrackmetadata(trackid:)","kind":"symbol","required":true,"navigatorTitle":[{"text":"getTrackMetadataWithTrackId:","kind":"identifier"}],"title":"getTrackMetadata(trackId:)","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getTrackMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"TunedTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"type":"topic","url":"\/documentation\/automixiq\/tunedrestdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedRestDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"title":"TunedRestDelegate","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/initialised()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialised()","role":"symbol","url":"\/documentation\/automixiq\/automixiq\/initialised()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initialised"}],"title":"initialised()","abstract":[{"text":"Returns whether or not AutomixIQ is initialised.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialised"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate":{"url":"\/documentation\/automixiq\/automixiqmusiccachedelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","abstract":[{"type":"text","text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"title":"AutomixIQMusicCacheDelegate","navigatorTitle":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate/trackDownloadCompleted(trackId:data:)":{"title":"trackDownloadCompleted(trackId:data:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadCompleted(trackId:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadCompleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":")"}],"abstract":[{"text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}],"url":"\/documentation\/automixiq\/automixiqmusiccachedelegate\/trackdownloadcompleted(trackid:data:)","kind":"symbol","required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"asyncGetAuthenticatedDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedDeviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}],"abstract":[{"text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required.","type":"text"},{"text":" ","type":"text"},{"text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”.","type":"text"}],"type":"topic","url":"\/documentation\/automixiq\/tunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate/getCachedTrack(trackId:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/getCachedTrack(trackId:)","title":"getCachedTrack(trackId:)","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getCachedTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"getCachedTrackWithTrackId:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"type":"topic","url":"\/documentation\/automixiq\/automixiqmusiccachedelegate\/getcachedtrack(trackid:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/automaticallyLogPlayback()":{"url":"\/documentation\/automixiq\/tunedrestdelegate\/automaticallylogplayback()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticallyLogPlayback","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/automaticallyLogPlayback()","abstract":[{"text":"Called by AutomixIQ to learn if it should log playback events to Tuned’s backend on your behalf or if you will implement logging yourself.","type":"text"}],"title":"automaticallyLogPlayback()","required":true,"navigatorTitle":[{"text":"automaticallyLogPlayback","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/uniqueDeviceIdentifier()":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/uniqueDeviceIdentifier()","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueDeviceIdentifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"text":"Called by AutomixIQ to request the unique identifier for the users device as a string.","type":"text"},{"text":" ","type":"text"},{"text":"On iOS this is generally the Identifier for Vendor.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It can be any string as long as it is unique"},{"type":"text","text":" "},{"type":"text","text":"AutomixIQ will use this string as the UniqueId if it needs to register the device for playback"}],"title":"uniqueDeviceIdentifier()","navigatorTitle":[{"text":"uniqueDeviceIdentifier","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/automixiq\/tunedrestdelegate\/uniquedeviceidentifier()","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","title":"AutomixIQConfig","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQConfig"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"abstract":[],"type":"topic","url":"\/documentation\/automixiq\/automixiqconfig","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Updating-custom-player's-UI-article":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","type":"topic","abstract":[{"type":"text","text":"How to create a UI to reflect the AutomixIQ player"}],"title":"Updating your player UI","kind":"article","url":"\/documentation\/automixiq\/updating-custom-player's-ui-article","role":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setMusicCacheDelegate(_:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setMusicCacheDelegate(_:)","title":"setMusicCacheDelegate(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMusicCacheDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate","text":"AutomixIQMusicCacheDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setMusicCacheDelegate:","kind":"identifier"}],"abstract":[{"text":"Adds a new music cache delegate","type":"text"}],"type":"topic","url":"\/documentation\/automixiq\/automixiq\/setmusiccachedelegate(_:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate/trackDownloadProgressChanged(trackId:progress:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadProgressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"title":"trackDownloadProgressChanged(trackId:progress:)","navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixiqmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"title":"AutomixIQ","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"generated":true,"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs","title":"Initializing AutomixIQ for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":"AutomixIQStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/title","value":"logAutomixIQMessageWithLogLevel:message:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1getTrackMetadata(trackId:)\/title","value":"getTrackMetadataWithTrackId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1getTrackMetadata(trackId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getTrackMetadataWithTrackId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title","value":"TunedRestDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/navigatorTitle","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialised()\/title","value":"initialised"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialised()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initialised"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/title","value":"AutomixIQMusicCacheDelegate"},{"op":"replace","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/fragments"},{"op":"replace","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/navigatorTitle"},{"op":"replace","value":"trackDownloadCompletedWithTrackId:data:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1trackDownloadCompleted(trackId:data:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1trackDownloadCompleted(trackId:data:)\/fragments"},{"op":"replace","value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/fragments"},{"op":"replace","value":"getCachedTrackWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1getCachedTrack(trackId:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getCachedTrackWithTrackId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1getCachedTrack(trackId:)\/fragments"},{"op":"replace","value":"automaticallyLogPlayback","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1automaticallyLogPlayback()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"automaticallyLogPlayback","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1automaticallyLogPlayback()\/fragments"},{"op":"replace","value":"uniqueDeviceIdentifier","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1uniqueDeviceIdentifier()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"uniqueDeviceIdentifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1uniqueDeviceIdentifier()\/fragments"},{"op":"replace","value":"AutomixIQConfig","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title"},{"op":"replace","value":[{"text":"AutomixIQConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle"},{"op":"replace","value":"setMusicCacheDelegate:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setMusicCacheDelegate(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMusicCacheDelegate:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setMusicCacheDelegate(_:)\/fragments"},{"op":"replace","value":"trackDownloadProgressChangedWithTrackId:progress:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments"}]}]}