{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SocialLayerDelegates","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/tunedGlobalSocialLayerDelegates()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)SocialRadioObjC(im)tunedGlobalSocialLayerDelegates","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tunedGlobalSocialLayerDelegates"},{"text":"() -> ","kind":"text"},{"text":"SocialLayerDelegates","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates","kind":"typeIdentifier"}],"symbolKind":"method","role":"symbol","title":"tunedGlobalSocialLayerDelegates()"},"variants":[{"paths":["\/documentation\/socialradio\/socialradioobjc\/tunedglobalsociallayerdelegates()"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialLayerDelegates"}],"role":"symbol","title":"SocialLayerDelegates","navigatorTitle":[{"kind":"identifier","text":"SocialLayerDelegates"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","abstract":[{"type":"text","text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions."},{"type":"text","text":" "},{"type":"text","text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc."},{"type":"text","text":" "},{"type":"text","text":"See each delegate’s documentation for details."}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayerdelegates","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC/tunedGlobalSocialLayerDelegates()":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/tunedGlobalSocialLayerDelegates()","title":"tunedGlobalSocialLayerDelegates()","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tunedGlobalSocialLayerDelegates"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates","kind":"typeIdentifier","text":"SocialLayerDelegates"}],"url":"\/documentation\/socialradio\/socialradioobjc\/tunedglobalsociallayerdelegates()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioObjC","kind":"identifier"}],"role":"symbol","title":"SocialRadioObjC","navigatorTitle":[{"text":"SocialRadioObjC","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC","url":"\/documentation\/socialradio\/socialradioobjc","type":"topic","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","value":"SocialLayerDelegates","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}