{"variants":[{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/playing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/playing"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariablePlaying","title":"AutomixIQStatusVariable.playing","role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaying"}],"modules":[{"name":"SocialRadio"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playing","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playing":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixiqstatusvariable\/playing","title":"AutomixIQStatusVariable.playing","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaying"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playing","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable","title":"AutomixIQStatusVariable","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixIQStatusVariablePlaying","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaying"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AutomixIQStatusVariablePlaying","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixIQStatusVariablePlaying","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playing\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlaying","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playing\/fragments"},{"op":"replace","value":"AutomixIQStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments"},{"op":"replace","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}