{"sections":[],"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"AutomixIQ"}],"title":"automixOn(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","externalID":"c:objc(cs)AutomixIQObjC(im)automixOnWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automixOn","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TunedTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixiqobjc\/automixon(withidentifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/automixOn(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automixOn","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"identifiers","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"trackMetadataArray","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel","text":"TunedTrackModel","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"index","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"languages":["swift"]},{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixOn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifiers"},{"kind":"text","text":" "},{"kind":"internalParam","text":"identifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":" "},{"kind":"internalParam","text":"trackMetadataArray"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","text":"TunedTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"playTrackIndex"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contextType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}]}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC/automixOn(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"url":"\/documentation\/automixiq\/automixiqobjc\/automixon(withidentifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/automixOn(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automixOn","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TunedTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"role":"symbol","title":"automixOn(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedTrackModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedTrackModel"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedTrackModel"}],"title":"TunedTrackModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel","abstract":[{"type":"text","text":"TunedTrackModel models a track. This metadata is required."}],"url":"\/documentation\/automixiq\/tunedtrackmodel"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQObjC","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}],"title":"AutomixIQObjC","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC","abstract":[],"url":"\/documentation\/automixiq\/automixiqobjc"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","url":"\/documentation\/automixiq","title":"AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TunedTrackModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/navigatorTitle","op":"replace"}]}]}