{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate"]]},"abstract":[{"text":"Called by Automix to learn the identity of the device requesting to stream audio, for those services that require it.","type":"text"},{"text":" ","type":"text"},{"text":"An example would be, a service that only allows one device to stream at any one time, would need to know the identity of the device to provide the stream.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/getDeviceIdentifier()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getDeviceIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate(im)getDeviceIdentifier","title":"getDeviceIdentifier()","required":true,"symbolKind":"method","navigatorTitle":[{"text":"getDeviceIdentifier","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstreamingdelegate\/getdeviceidentifier()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqstreamingdelegate\/getdeviceidentifier()"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeviceIdentifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The unique identifier of the device that will be streaming content, nil if unknown or unnecessary","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/getDeviceIdentifier()":{"kind":"symbol","abstract":[{"type":"text","text":"Called by Automix to learn the identity of the device requesting to stream audio, for those services that require it."},{"type":"text","text":" "},{"type":"text","text":"An example would be, a service that only allows one device to stream at any one time, would need to know the identity of the device to provide the stream."}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeviceIdentifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/getDeviceIdentifier()","title":"getDeviceIdentifier()","url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/getdeviceidentifier()","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getDeviceIdentifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate":{"role":"symbol","abstract":[{"text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"url":"\/documentation\/automixiq\/automixiqstreamingdelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"title":"AutomixIQStreamingDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-with-custom-backend-article":{"role":"article","abstract":[{"text":"How to validate your client and start using the AutomixIQ SDK with a custom backend","type":"text"}],"url":"\/documentation\/automixiq\/initialising-automixiq-with-custom-backend-article","kind":"article","title":"Initializing AutomixIQ with a custom backend","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"getDeviceIdentifier","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDeviceIdentifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"getDeviceIdentifier","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The unique identifier of the device that will be streaming content, nil if unknown or unnecessary","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/title","op":"replace","value":"getDeviceIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDeviceIdentifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/title","op":"replace","value":"AutomixIQStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}