{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/explicitLyricsFiltering"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"explicitLyricsFiltering"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/explicitlyricsfiltering"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/explicitlyricsfiltering"]}],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"explicitLyricsFiltering","kind":"identifier"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"AutomixIQ"}],"title":"AutomixIQStatusVariable.explicitLyricsFiltering","externalID":"c:@M@AutomixIQ@E@AutomixIQStatusVariable@AutomixIQStatusVariableExplicitLyricsFiltering","navigatorTitle":[{"text":"AutomixIQStatusVariableExplicitLyricsFiltering","kind":"identifier"}],"symbolKind":"case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable"]]},"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusVariable"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"title":"AutomixIQStatusVariable","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/explicitLyricsFiltering":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/explicitLyricsFiltering","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixiqstatusvariable\/explicitlyricsfiltering","title":"AutomixIQStatusVariable.explicitLyricsFiltering","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableExplicitLyricsFiltering"}],"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"explicitLyricsFiltering"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","role":"collection","url":"\/documentation\/automixiq","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AutomixIQStatusVariableExplicitLyricsFiltering"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixIQStatusVariableExplicitLyricsFiltering","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixIQStatusVariableExplicitLyricsFiltering"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/title","value":"AutomixIQStatusVariable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/fragments","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/navigatorTitle"},{"value":"AutomixIQStatusVariableExplicitLyricsFiltering","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1explicitLyricsFiltering\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableExplicitLyricsFiltering"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1explicitLyricsFiltering\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}