{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingAd"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingAd"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"AutomixIQStatusVariablePlayingAd","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingAd","kind":"identifier"}],"role":"symbol","externalID":"c:@M@AutomixIQ@E@AutomixIQStatusVariable@AutomixIQStatusVariablePlayingAd","symbolKind":"case","title":"AutomixIQStatusVariable.playingAd","modules":[{"name":"AutomixIQ"}],"roleHeading":"Case"},"variants":[{"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/playingad"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/playingad"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","role":"collection","url":"\/documentation\/automixiq","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusVariable"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"title":"AutomixIQStatusVariable","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/playingAd":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingAd"}],"abstract":[],"type":"topic","title":"AutomixIQStatusVariable.playingAd","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/playingAd","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingAd"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixiqstatusvariable\/playingad"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AutomixIQStatusVariablePlayingAd"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingAd"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AutomixIQStatusVariablePlayingAd","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/title","op":"replace","value":"AutomixIQStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingAd\/title","value":"AutomixIQStatusVariablePlayingAd"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1playingAd\/fragments","value":[{"text":"AutomixIQStatusVariablePlayingAd","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}