{"metadata":{"symbolKind":"case","externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodePlayToEndMixEnd","title":"AutomixSDKErrorCode.playToEndMixEnd","roleHeading":"Case","role":"symbol","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodePlayToEndMixEnd","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playToEndMixEnd"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMixEnd","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playToEndMixEnd","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/playtoendmixend"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/playtoendmixend"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"title":"AutomixSDKErrorCode","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/playToEndMixEnd":{"navigatorTitle":[{"text":"AutomixSDKErrorCodePlayToEndMixEnd","kind":"identifier"}],"type":"topic","title":"AutomixSDKErrorCode.playToEndMixEnd","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMixEnd","url":"\/documentation\/socialradio\/automixsdkerrorcode\/playtoendmixend","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playToEndMixEnd"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixSDKErrorCodePlayToEndMixEnd","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"AutomixSDKErrorCodePlayToEndMixEnd","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayToEndMixEnd"}]}]}},{"value":"AutomixSDKErrorCode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKErrorCodePlayToEndMixEnd","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playToEndMixEnd\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayToEndMixEnd"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playToEndMixEnd\/fragments","op":"replace"}]}]}