{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/sdknotinitialised"]},{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/sdknotinitialised"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialised","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeSdkNotInitialised","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sdkNotInitialised","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotInitialised"}],"title":"AutomixSDKErrorCode.sdkNotInitialised","modules":[{"name":"SocialRadio"}],"role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotInitialised","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"title":"AutomixSDKErrorCode","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/sdkNotInitialised":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/sdknotinitialised","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkNotInitialised","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkNotInitialised"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotInitialised","title":"AutomixSDKErrorCode.sdkNotInitialised","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"AutomixSDKErrorCodeSdkNotInitialised","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotInitialised"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"AutomixSDKErrorCodeSdkNotInitialised","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle"},{"value":"AutomixSDKErrorCodeSdkNotInitialised","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkNotInitialised\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkNotInitialised\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeSdkNotInitialised","kind":"identifier"}]}]}]}