{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)SocialRadio(cm)isManagingNowPlayingDictionary","role":"symbol","title":"isManagingNowPlayingDictionary()","symbolKind":"method","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"isManagingNowPlayingDictionary","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isManagingNowPlayingDictionary"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/isManagingNowPlayingDictionary()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Returns wether Social Radio is actively managing the MPNowPlayingDictionary and Now Playing widget commands, as set by the feature set config object.","type":"text"},{"text":" ","type":"text"},{"text":"This can only be true if a radio session is ongoing.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isManagingNowPlayingDictionary"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradio\/ismanagingnowplayingdictionary()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradio\/ismanagingnowplayingdictionary()"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"role":"collection","title":"SocialRadio","url":"\/documentation\/socialradio","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/isManagingNowPlayingDictionary()":{"title":"isManagingNowPlayingDictionary()","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isManagingNowPlayingDictionary","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns wether Social Radio is actively managing the MPNowPlayingDictionary and Now Playing widget commands, as set by the feature set config object."},{"type":"text","text":" "},{"type":"text","text":"This can only be true if a radio session is ongoing."}],"url":"\/documentation\/socialradio\/socialradio\/ismanagingnowplayingdictionary()","navigatorTitle":[{"text":"isManagingNowPlayingDictionary","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/isManagingNowPlayingDictionary()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio":{"url":"\/documentation\/socialradio\/socialradio","kind":"symbol","title":"SocialRadio","role":"symbol","navigatorTitle":[{"text":"SocialRadio","kind":"identifier"}],"abstract":[{"text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadio","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isManagingNowPlayingDictionary","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isManagingNowPlayingDictionary"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isManagingNowPlayingDictionary","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isManagingNowPlayingDictionary","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1isManagingNowPlayingDictionary()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isManagingNowPlayingDictionary"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1isManagingNowPlayingDictionary()\/fragments"},{"value":"SocialRadio","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/title"},{"value":[{"kind":"identifier","text":"SocialRadio"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadio"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/navigatorTitle"}]}]}