{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/getAutomixStreamingDelegate()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/radiosdkobjc\/getautomixstreamingdelegate()"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"kind":"text","text":"() -> any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate","text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier"}],"modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"method","title":"getAutomixStreamingDelegate()","roleHeading":"Instance Method","externalID":"c:objc(cs)RadioSDKObjC(im)getAutomixStreamingDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC","title":"RadioSDKObjC","url":"\/documentation\/socialradio\/radiosdkobjc","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKObjC"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKObjC"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKObjC/getAutomixStreamingDelegate()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKObjC\/getAutomixStreamingDelegate()","url":"\/documentation\/socialradio\/radiosdkobjc\/getautomixstreamingdelegate()","role":"symbol","title":"getAutomixStreamingDelegate()","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate":{"title":"AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/automixsdkstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","type":"topic","abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AutomixSDKStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}]},{"value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/navigatorTitle"}]}]}