{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"liveConsumption","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackmode\/liveconsumption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackmode\/liveconsumption"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackMode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackMode\/liveConsumption","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveConsumption"}],"roleHeading":"Case","externalID":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackMode@AutomixSDKPlaybackModeLiveConsumption","role":"symbol","modules":[{"name":"PacemakerRadio"}],"symbolKind":"case","title":"AutomixSDKPlaybackMode.liveConsumption","navigatorTitle":[{"text":"AutomixSDKPlaybackModeLiveConsumption","kind":"identifier"}]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","title":"PacemakerRadio","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackMode":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackMode","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaybackmode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"type":"topic","navigatorTitle":[{"text":"AutomixSDKPlaybackMode","kind":"identifier"}],"title":"AutomixSDKPlaybackMode"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackMode/liveConsumption":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackMode\/liveConsumption","title":"AutomixSDKPlaybackMode.liveConsumption","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackModeLiveConsumption"}],"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"liveConsumption","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkplaybackmode\/liveconsumption"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKPlaybackModeLiveConsumption"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixSDKPlaybackModeLiveConsumption","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKPlaybackModeLiveConsumption"}]}]},"path":"\/primaryContentSections\/0"},{"value":"AutomixSDKPlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackMode\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKPlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackMode~1liveConsumption\/title","value":"AutomixSDKPlaybackModeLiveConsumption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackMode~1liveConsumption\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackModeLiveConsumption"}]}]}]}