{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/init(fontfamily:titlefontsize:radiouifontsizehuge:radiouifontsizelarge:radiouifontsizeregular:radiouifontsizesmall:radiouifontsizetiny:radiouifontsizematchmachine:textfieldfontbold:textfieldbackgroundcolor:textfieldborderradius:textfieldtex-7khup"]},{"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/init(fontfamily:titlefontsize:radiouifontsizehuge:radiouifontsizelarge:radiouifontsizeregular:radiouifontsizesmall:radiouifontsizetiny:radiouifontsizematchmachine:textfieldfontbold:textfieldbackgroundcolor:textfieldborderradius:textfieldtex-7khup"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"fontFamily","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"HelveticaNeue\", "},{"kind":"externalParam","text":"titleFontSize"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 14, ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeHuge"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = 40, ","kind":"text"},{"text":"radioUIFontSizeLarge","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = 16, ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeRegular"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":" = 14, ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeSmall"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":" = 12, ","kind":"text"},{"text":"radioUIFontSizeTiny","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" = 10, ","kind":"text"},{"text":"radioUIFontSizeMatchMachine","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" = 20, "},{"text":"textFieldFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"textFieldBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" = UIColor.init(white: 0.2, alpha: 1), ","kind":"text"},{"text":"textFieldBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":" = 5, ","kind":"text"},{"text":"textFieldTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = UIColor.white, "},{"text":"textFieldPlaceholderTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = UIColor.black, "},{"text":"dialogTitleFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"dialogTitleTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = UIColor.white, "},{"kind":"externalParam","text":"dialogDescriptionFontBold"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"dialogDescriptionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" = UIColor.white, "},{"kind":"externalParam","text":"dialogPrimaryButtonFontBold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" = UIColor.clear, ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorderRadius"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":" = -1, ","kind":"text"},{"text":"dialogPrimaryButtonTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" = UIColor.white, ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorder"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = true, "},{"text":"dialogPrimaryButtonBorderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" = UIColor.white, "},{"text":"dialogSecondaryButtonFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"dialogSecondaryButtonBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = UIColor.clear, "},{"text":"dialogSecondaryButtonBorderRadius","kind":"externalParam"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":" = -1, ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" = UIColor.white, ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBorderColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = UIColor.clear)"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig(im)initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fontFamily","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"titleFontSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeHuge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"radioUIFontSizeLarge","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"radioUIFontSizeRegular","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeSmall","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeTiny"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeMatchMachine","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"textFieldFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textFieldBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"text":"textFieldTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldPlaceholderTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogTitleFontBold"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogTitleTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogDescriptionFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogDescriptionTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogPrimaryButtonBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonBorderColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogSecondaryButtonTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBorder"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogSecondaryButtonBorderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"PacemakerRadio"}],"title":"init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)"},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig"]]},"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig":{"navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkuiconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKUIConfig"}],"type":"topic","title":"RadioSDKUIConfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","title":"PacemakerRadio","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)":{"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","type":"topic","navigatorTitle":[{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"title":"init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fontFamily"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"titleFontSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeHuge"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeLarge","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"radioUIFontSizeRegular","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"radioUIFontSizeSmall","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"radioUIFontSizeTiny","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeMatchMachine","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"textFieldFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldBackgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"text":"textFieldBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"text":"textFieldPlaceholderTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogTitleFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"dialogTitleTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogDescriptionFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogDescriptionTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogPrimaryButtonBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonBorderRadius","kind":"externalParam"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogPrimaryButtonBorder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogPrimaryButtonBorderColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorderRadius","kind":"externalParam"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogSecondaryButtonBorderColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"url":"\/documentation\/pacemakerradio\/radiosdkuiconfig\/init(fontfamily:titlefontsize:radiouifontsizehuge:radiouifontsizelarge:radiouifontsizeregular:radiouifontsizesmall:radiouifontsizetiny:radiouifontsizematchmachine:textfieldfontbold:textfieldbackgroundcolor:textfieldborderradius:textfieldtex-7khup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithFontFamily:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fontFamily"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleFontSize:"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"titleFontSize","kind":"internalParam"},{"kind":"text","text":" "},{"text":"radioUIFontSizeHuge:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"radioUIFontSizeHuge","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeLarge:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"radioUIFontSizeLarge","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeRegular:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"radioUIFontSizeRegular","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeSmall:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"radioUIFontSizeSmall"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeTiny:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"radioUIFontSizeTiny"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeMatchMachine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"radioUIFontSizeMatchMachine","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textFieldFontBold:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"textFieldFontBold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textFieldBackgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"textFieldBackgroundColor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"textFieldBorderRadius:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textFieldBorderRadius","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textFieldTextColor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textFieldTextColor"},{"text":" ","kind":"text"},{"text":"textFieldPlaceholderTextColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textFieldPlaceholderTextColor"},{"text":" ","kind":"text"},{"text":"dialogTitleFontBold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dialogTitleFontBold"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogTitleTextColor:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"dialogTitleTextColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogDescriptionFontBold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"dialogDescriptionFontBold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dialogDescriptionTextColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"dialogDescriptionTextColor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dialogPrimaryButtonFontBold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"dialogPrimaryButtonFontBold","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor:"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dialogPrimaryButtonBackgroundColor"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonBorderRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"dialogPrimaryButtonBorderRadius","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonTextColor:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dialogPrimaryButtonTextColor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBorder:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"dialogPrimaryButtonBorder","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBorderColor:"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"text":"dialogPrimaryButtonBorderColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonFontBold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"dialogSecondaryButtonFontBold","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonBackgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" *) "},{"text":"dialogSecondaryButtonBackgroundColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogSecondaryButtonBorderRadius:"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"text":"dialogSecondaryButtonBorderRadius","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogSecondaryButtonTextColor:"},{"text":"(","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dialogSecondaryButtonTextColor"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBorder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"dialogSecondaryButtonBorder"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonBorderColor:"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dialogSecondaryButtonBorderColor"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/title","op":"replace","value":"RadioSDKUIConfig"},{"value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/fragments"},{"value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/title","value":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:"}],"op":"replace"}]}]}