{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automixSDKError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","text":"AutomixSDKErrorCode","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKErrorCode"},{"text":") -> ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"SocialRadio"}],"symbolKind":"method","title":"automixSDKError(code:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"automixSDKError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKErrorCode","text":"AutomixSDKErrorCode"},{"text":") -> ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"}],"role":"symbol","navigatorTitle":[{"text":"automixSDKErrorWithCode:","kind":"identifier"}],"roleHeading":"Type Method","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDK(cm)automixSDKErrorWithCode:"},"variants":[{"paths":["\/documentation\/socialradio\/automixsdk\/automixsdkerror(code:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdk\/automixsdkerror(code:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK\/automixSDKError(code:)"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDK":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK","navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdk","title":"AutomixSDK","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"abstract":[{"text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"url":"\/documentation\/socialradio\/automixsdkerrorcode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"title":"AutomixSDKErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","abstract":[],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDK/automixSDKError(code:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDK\/automixSDKError(code:)","title":"automixSDKError(code:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"automixSDKError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixSDKErrorCode","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKErrorCode"},{"kind":"text","text":") -> "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"}],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/automixsdk\/automixsdkerror(code:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"automixSDKErrorWithCode:","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"automixSDKErrorWithCode:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"automixSDKErrorWithCode:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" *) ","kind":"text"},{"text":"automixSDKErrorWithCode:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKErrorCode","text":"AutomixSDKErrorCode","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"},{"text":") ","kind":"text"},{"text":"code","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK\/title","value":"AutomixSDK"},{"value":[{"text":"AutomixSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDK"}]},{"value":"AutomixSDKErrorCode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace"},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK~1automixSDKError(code:)\/title","value":"automixSDKErrorWithCode:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDK~1automixSDKError(code:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"automixSDKErrorWithCode:","kind":"identifier"}]}]}]}