{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expires_in","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"sections":[],"metadata":{"externalID":"s:9AutomixIQ27TunedAuthenticationResponseC10expires_inSiSgvp","modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expires_in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"title":"expires_in","roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"abstract":[{"type":"text","text":"The expiry time"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse"]]},"variants":[{"paths":["\/documentation\/automixiq\/tunedauthenticationresponse\/expires_in"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse\/expires_in"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAuthenticationResponse":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse","type":"topic","url":"\/documentation\/automixiq\/tunedauthenticationresponse","navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAuthenticationResponse"}],"kind":"symbol","abstract":[{"text":"TunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"title":"TunedAuthenticationResponse"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"title":"AutomixIQ","kind":"symbol","type":"topic","url":"\/documentation\/automixiq","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAuthenticationResponse/expires_in":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse\/expires_in","url":"\/documentation\/automixiq\/tunedauthenticationresponse\/expires_in","type":"topic","kind":"symbol","title":"expires_in","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expires_in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"The expiry time"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/title","op":"replace","value":"TunedAuthenticationResponse"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/navigatorTitle","op":"replace","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}]}]}]}