{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"normalisedVolume"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/normalisedVolume","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"normalisedVolume","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariableNormalisedVolume","role":"symbol","title":"AutomixIQStatusVariable.normalisedVolume","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableNormalisedVolume"}],"roleHeading":"Case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/normalisedvolume"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/normalisedvolume"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","role":"symbol","type":"topic","title":"AutomixIQStatusVariable","url":"\/documentation\/socialradio\/automixiqstatusvariable","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusVariable"}],"abstract":[{"type":"text","text":"AutomixIQ status variable type"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/normalisedVolume":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableNormalisedVolume"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/normalisedVolume","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixiqstatusvariable\/normalisedvolume","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"normalisedVolume","kind":"identifier"}],"title":"AutomixIQStatusVariable.normalisedVolume"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixIQStatusVariableNormalisedVolume","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableNormalisedVolume"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixIQStatusVariableNormalisedVolume","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixIQStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title"},{"value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments"},{"value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle"},{"value":"AutomixIQStatusVariableNormalisedVolume","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1normalisedVolume\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableNormalisedVolume"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1normalisedVolume\/fragments"}]}]}