{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Artists"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKArtistModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel","text":"AutomixSDKArtistModel","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel\/Artists","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The artists of a track - the first one is the one to be presented by a UI"}],"sections":[],"metadata":{"title":"Artists","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel(py)Artists","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"Artists","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKArtistModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKArtistModel"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"Artists","kind":"identifier"}],"role":"symbol","modules":[{"name":"SocialRadio"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdktrackmodel\/artists"]},{"paths":["\/documentation\/socialradio\/automixsdktrackmodel\/artists"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel/Artists":{"abstract":[{"type":"text","text":"The artists of a track - the first one is the one to be presented by a UI"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel\/Artists","kind":"symbol","role":"symbol","type":"topic","title":"Artists","navigatorTitle":[{"kind":"identifier","text":"Artists"}],"url":"\/documentation\/socialradio\/automixsdktrackmodel\/artists","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Artists"},{"kind":"text","text":": ["},{"text":"AutomixSDKArtistModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKArtistModel","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKArtistModel":{"type":"topic","title":"AutomixSDKArtistModel","role":"symbol","abstract":[{"type":"text","text":"AutomixSDKArtistModel models an artist."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKArtistModel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkartistmodel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel":{"abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","title":"AutomixSDKTrackModel","url":"\/documentation\/socialradio\/automixsdktrackmodel","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"Artists","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Artists"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<AutomixSDKArtistModel *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"Artists","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Artists","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel~1Artists\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel~1Artists\/fragments","value":[{"text":"Artists","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKArtistModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/title","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKArtistModel"}]},{"value":"AutomixSDKTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/title"},{"op":"replace","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/navigatorTitle"}]}]}