{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/addtrackplaylistdoesnotexist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/addtrackplaylistdoesnotexist"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackPlaylistDoesNotExist"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"roleHeading":"Case","title":"AutomixSDKErrorCode.addTrackPlaylistDoesNotExist","externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist","symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"url":"\/documentation\/socialradio\/automixsdkerrorcode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"title":"AutomixSDKErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","abstract":[],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/addTrackPlaylistDoesNotExist":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/addtrackplaylistdoesnotexist","kind":"symbol","title":"AutomixSDKErrorCode.addTrackPlaylistDoesNotExist","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode"},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackPlaylistDoesNotExist\/title","value":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackPlaylistDoesNotExist\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist"}]}]}]}