{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeNoInternetAvailableTooLongOffline","modules":[{"name":"SocialRadio"}],"title":"AutomixSDKErrorCode.noInternetAvailableTooLongOffline","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline"}],"role":"symbol","symbolKind":"case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/nointernetavailabletoolongoffline"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/nointernetavailabletoolongoffline"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/noInternetAvailableTooLongOffline":{"type":"topic","abstract":[],"title":"AutomixSDKErrorCode.noInternetAvailableTooLongOffline","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","url":"\/documentation\/socialradio\/automixsdkerrorcode\/nointernetavailabletoolongoffline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"url":"\/documentation\/socialradio\/automixsdkerrorcode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"title":"AutomixSDKErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","abstract":[],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1noInternetAvailableTooLongOffline\/title","value":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1noInternetAvailableTooLongOffline\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}