{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"radioUIViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The view controller if a session has started, nil otherwise.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/socialradio\/socialradio\/radiouiviewcontroller()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradio\/radiouiviewcontroller()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SocialRadio"}],"title":"radioUIViewController()","roleHeading":"Instance Method","externalID":"c:@M@SocialRadio@objc(cs)SocialRadio(im)radioUIViewController","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"radioUIViewController","kind":"identifier"}],"symbolKind":"method"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/radioUIViewController()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio"]]},"sections":[],"abstract":[{"type":"text","text":"Returns the view controller rendering the radio UI if either a creation or consumpsion session has already started."},{"type":"text","text":" "},{"type":"text","text":"In order to start a creation session, call startRadioSession()"},{"type":"text","text":" "},{"type":"text","text":"In order top start a consumption session, call joinLiveBroadcast()"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","type":"topic","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadio","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio","url":"\/documentation\/socialradio\/socialradio","type":"topic","abstract":[{"type":"text","text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"role":"symbol","navigatorTitle":[{"text":"SocialRadio","kind":"identifier"}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/radioUIViewController()":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIViewController"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the view controller rendering the radio UI if either a creation or consumpsion session has already started."},{"type":"text","text":" "},{"type":"text","text":"In order to start a creation session, call startRadioSession()"},{"type":"text","text":" "},{"type":"text","text":"In order top start a consumption session, call joinLiveBroadcast()"}],"title":"radioUIViewController()","kind":"symbol","url":"\/documentation\/socialradio\/socialradio\/radiouiviewcontroller()","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/radioUIViewController()","navigatorTitle":[{"kind":"identifier","text":"radioUIViewController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"radioUIViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"radioUIViewController","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"radioUIViewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The view controller if a session has started, nil otherwise.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/title","value":"SocialRadio"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/fragments","value":[{"kind":"identifier","text":"SocialRadio"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/navigatorTitle","value":[{"text":"SocialRadio","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1radioUIViewController()\/title","value":"radioUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1radioUIViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"radioUIViewController"}]}]}]}