{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","title":"init","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioMixtapeLite(im)init","modules":[{"name":"SocialRadio"}]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite\/init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiomixtapelite\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeLite":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","type":"topic","title":"SocialRadioMixtapeLite","abstract":[{"text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiomixtapelite","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeLite/init":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"title":"init","url":"\/documentation\/socialradio\/socialradiomixtapelite\/init","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite\/init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/title","value":"SocialRadioMixtapeLite","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/fragments","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}],"op":"replace"}]}]}