{"variants":[{"paths":["\/documentation\/socialradio\/socialradioobjc\/initialise(with:automixiqstreamingdelegate:socialradiotrackmetadatadelegate:socialradiostatusdelegate:socialradiouidelegate:authenticationdelegate:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automixIQStreamingDelegate"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate","text":"AutomixIQStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialRadioTrackMetadataDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioTrackMetadataDelegate","text":"SocialRadioTrackMetadataDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate"},{"kind":"text","text":", "},{"text":"authenticationDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"AuthenticationDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AuthenticationDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}]},{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStreamingDelegate"},{"kind":"text","text":": any "},{"text":"AutomixIQStreamingDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"socialRadioTrackMetadataDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioTrackMetadataDelegate","text":"SocialRadioTrackMetadataDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","kind":"typeIdentifier","text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"SocialRadioUIDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate"},{"text":", ","kind":"text"},{"text":"authenticationDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","text":"AuthenticationDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AuthenticationDelegate"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialise(with:automixIQStreamingDelegate:socialRadioTrackMetadataDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:authenticationDelegate:completion:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"externalID":"c:objc(cs)SocialRadioObjC(cm)initialiseWithConfig:automixIQStreamingDelegate:socialRadioTrackMetadataDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:authenticationDelegate:completion:","title":"initialise(with:automixIQStreamingDelegate:socialRadioTrackMetadataDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:authenticationDelegate:completion:)","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"automixIQStreamingDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate"},{"kind":"text","text":", "},{"text":"socialRadioTrackMetadataDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"SocialRadioTrackMetadataDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioTrackMetadataDelegate"},{"text":", ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AuthenticationDelegate","text":"AuthenticationDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"url":"\/documentation\/socialradio\/socialradioconfig","title":"SocialRadioConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioConfig"}],"abstract":[{"type":"text","text":"SocialRadioConfig holds the variables to initialise SocialRadio and describe the desired feature set and UI"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioConfig"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackMetadataDelegate":{"navigatorTitle":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"title":"SocialRadioTrackMetadataDelegate","abstract":[{"text":"Handles track recommendations and artwork","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiotrackmetadatadelegate","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","title":"SocialRadioStatusObserverDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"abstract":[],"navigatorTitle":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC":{"abstract":[],"title":"SocialRadioObjC","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioObjC","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradioobjc","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC","navigatorTitle":[{"text":"SocialRadioObjC","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC/initialise(with:automixIQStreamingDelegate:socialRadioTrackMetadataDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:authenticationDelegate:completion:)":{"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialise(with:automixIQStreamingDelegate:socialRadioTrackMetadataDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:authenticationDelegate:completion:)","title":"initialise(with:automixIQStreamingDelegate:socialRadioTrackMetadataDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:authenticationDelegate:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStreamingDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioTrackMetadataDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"SocialRadioTrackMetadataDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioTrackMetadataDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate"},{"text":", ","kind":"text"},{"text":"authenticationDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"AuthenticationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AuthenticationDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"type":"topic","url":"\/documentation\/socialradio\/socialradioobjc\/initialise(with:automixiqstreamingdelegate:socialradiotrackmetadatadelegate:socialradiostatusdelegate:socialradiouidelegate:authenticationdelegate:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","url":"\/documentation\/socialradio\/automixiqstreamingdelegate","title":"AutomixIQStreamingDelegate","kind":"symbol","abstract":[{"text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","url":"\/documentation\/socialradio\/socialradiouidelegate","title":"SocialRadioUIDelegate","kind":"symbol","abstract":[{"type":"text","text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AuthenticationDelegate":{"abstract":[{"text":"Handles handoff of authentication tokens","type":"text"}],"title":"AuthenticationDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/authenticationdelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","navigatorTitle":[{"text":"AuthenticationDelegate","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SocialRadioConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title"},{"op":"replace","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments"},{"op":"replace","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle"},{"op":"replace","value":"SocialRadioTrackMetadataDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/title"},{"op":"replace","value":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioTrackMetadataDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/navigatorTitle"},{"op":"replace","value":"SocialRadioStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title"},{"op":"replace","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title"},{"op":"replace","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle"},{"op":"replace","value":"SocialRadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","op":"replace","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/title","value":"AuthenticationDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/fragments","value":[{"text":"AuthenticationDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AuthenticationDelegate"}],"op":"replace"}]}]}