{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqplaybackeventtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqplaybackeventtype"]}],"seeAlsoSections":[{"title":"Persistency","anchor":"Persistency","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Persistency-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLog","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogAttributes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogID","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLog","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogAttributes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogID"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"externalID":"c:@M@SocialRadio@E@AutomixIQPlaybackEventType","roleHeading":"Enumeration","role":"symbol","title":"AutomixIQPlaybackEventType"},"abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH","doc:\/\/org.cocoapods.SocialRadio\/SY"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"languages":["swift"]}]},{"parameters":[{"name":"trackPlayStart","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Start of track playback"}]}]},{"name":"trackPlayPlayed5Secs","content":[{"inlineContent":[{"type":"text","text":"Track has played for 5 seconds"}],"type":"paragraph"}]},{"name":"trackPlayHeartbeat30Secs","content":[{"inlineContent":[{"type":"text","text":"Track has played for 30 seconds, this is called every 30 seconds of playback"}],"type":"paragraph"}]},{"name":"trackPlayStartMixingIntoNext","content":[{"type":"paragraph","inlineContent":[{"text":"Track has started transitioning into the next track","type":"text"}]}]},{"name":"trackPlaySkipped","content":[{"inlineContent":[{"text":"Track has been skipped to the next track (this is also called when seeking through the same track)","type":"text"}],"type":"paragraph"}]},{"name":"trackPlayFinished","content":[{"inlineContent":[{"type":"text","text":"Track has finished playback (if transitioning this is called at the end of the transition for the first track)"}],"type":"paragraph"}]},{"name":"mixPlaybackEnded","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Queue has reached the end and there are no more tracks to play"}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/trackPlayHeartbeat30Secs":{"abstract":[],"title":"AutomixIQPlaybackEventType.trackPlayHeartbeat30Secs","type":"topic","url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplayheartbeat30secs","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayHeartbeat30Secs"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayHeartbeat30Secs","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayHeartbeat30Secs"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/trackPlayStart":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayStart","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStart"}],"url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplaystart","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayStart"}],"title":"AutomixIQPlaybackEventType.trackPlayStart","type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Persistency-article":{"role":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Persistency-article","abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"kind":"article","url":"\/documentation\/socialradio\/persistency-article","type":"topic","title":"Persistency"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/Equatable-Implementations":{"url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/equatable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","role":"collectionGroup"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/init(rawValue:)","url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/init(rawvalue:)","kind":"symbol"},"doc://org.cocoapods.SocialRadio/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/trackPlayStartMixingIntoNext":{"url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplaystartmixingintonext","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayStartMixingIntoNext","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext","type":"topic","title":"AutomixIQPlaybackEventType.trackPlayStartMixingIntoNext","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTransitionLogID":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/socialradio\/automixiqtransitionlogid","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogID","title":"AutomixIQTransitionLogID","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQTransitionLogID"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTransitionLogAttributes":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLogAttributes","abstract":[],"kind":"symbol","url":"\/documentation\/socialradio\/automixiqtransitionlogattributes","type":"topic","title":"AutomixIQTransitionLogAttributes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlayLogAttributes":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogAttributes","navigatorTitle":[{"text":"AutomixIQPlayLogAttributes","kind":"identifier"}],"role":"symbol","title":"AutomixIQPlayLogAttributes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlayLogAttributes","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/socialradio\/automixiqplaylogattributes"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlayLogID":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogID"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLogID","abstract":[],"kind":"symbol","url":"\/documentation\/socialradio\/automixiqplaylogid","type":"topic","title":"AutomixIQPlayLogID","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlayLogID"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/trackPlayPlayed5Secs":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayPlayed5Secs"}],"title":"AutomixIQPlaybackEventType.trackPlayPlayed5Secs","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplayplayed5secs","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/mixPlaybackEnded":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixPlaybackEnded"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/mixPlaybackEnded","title":"AutomixIQPlaybackEventType.mixPlaybackEnded","type":"topic","url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/mixplaybackended","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType":{"role":"symbol","kind":"symbol","title":"AutomixIQPlaybackEventType","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType","type":"topic","url":"\/documentation\/socialradio\/automixiqplaybackeventtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"abstract":[{"text":"AutomixIQPlaybackEventType is an enum of all the available playback events","type":"text"}],"navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/RawRepresentable-Implementations":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","abstract":[]},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlayLog":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlayLog"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLog"}],"title":"AutomixIQPlayLog","url":"\/documentation\/socialradio\/automixiqplaylog","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlayLog","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/trackPlayFinished":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayFinished","kind":"symbol","url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplayfinished","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayFinished"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayFinished"}],"role":"symbol","title":"AutomixIQPlaybackEventType.trackPlayFinished","type":"topic","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTransitionLog":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLog"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTransitionLog","title":"AutomixIQTransitionLog","type":"topic","url":"\/documentation\/socialradio\/automixiqtransitionlog","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQTransitionLog"}],"abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/trackPlaySkipped":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlaySkipped"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlaySkipped","title":"AutomixIQPlaybackEventType.trackPlaySkipped","type":"topic","url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/trackplayskipped","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlaySkipped"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AutomixIQPlaybackEventType","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext"],"generated":true,"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":[{"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Persistency-article"],"anchor":"Persistency","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AutomixIQPlaybackEventTypeTrackPlayHeartbeat30Secs","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayHeartbeat30Secs\/title","op":"replace"},{"value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayHeartbeat30Secs","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayHeartbeat30Secs\/fragments","op":"replace"},{"value":"AutomixIQPlaybackEventTypeTrackPlayStart","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayStart\/title","op":"replace"},{"value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayStart\/fragments","op":"replace"},{"value":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayStartMixingIntoNext\/title","op":"replace"},{"value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayStartMixingIntoNext\/fragments","op":"replace"},{"value":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/title","op":"replace"},{"value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/fragments","op":"replace"},{"value":"AutomixIQPlaybackEventTypeMixPlaybackEnded","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/fragments","op":"replace"},{"value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/fragments","op":"replace"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/navigatorTitle","op":"replace"},{"value":"AutomixIQPlaybackEventTypeTrackPlayFinished","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayFinished\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayFinished"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlayFinished\/fragments","op":"replace"},{"value":"AutomixIQPlaybackEventTypeTrackPlaySkipped","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlaySkipped\/title","op":"replace"},{"value":[{"text":"AutomixIQPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1trackPlaySkipped\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}