{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"SocialRadioLite"}],"externalID":"c:@M@SocialRadioLite@E@SocialRadioPlaybackMode@SocialRadioPlaybackModeLiveConsumption","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveConsumption"}],"navigatorTitle":[{"text":"SocialRadioPlaybackModeLiveConsumption","kind":"identifier"}],"title":"SocialRadioPlaybackMode.liveConsumption","role":"symbol","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradioplaybackmode\/liveconsumption"]},{"paths":["\/documentation\/socialradiolite\/socialradioplaybackmode\/liveconsumption"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode\/liveConsumption","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"liveConsumption","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode"]]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioPlaybackMode":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioplaybackmode","title":"SocialRadioPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode","type":"topic","abstract":[{"text":"SocialRadio playback mode","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioPlaybackMode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioPlaybackMode/liveConsumption":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioPlaybackModeLiveConsumption","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioplaybackmode\/liveconsumption","title":"SocialRadioPlaybackMode.liveConsumption","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode\/liveConsumption","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveConsumption"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SocialRadioPlaybackModeLiveConsumption"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SocialRadioPlaybackModeLiveConsumption"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SocialRadioPlaybackModeLiveConsumption","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"SocialRadioPlaybackMode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/title"},{"value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/navigatorTitle","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"op":"replace"},{"value":"SocialRadioPlaybackModeLiveConsumption","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode~1liveConsumption\/title"},{"value":[{"kind":"identifier","text":"SocialRadioPlaybackModeLiveConsumption"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode~1liveConsumption\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}