{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel"]]},"variants":[{"paths":["\/documentation\/automixiq\/tunedartistmodel\/name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/tunedartistmodel\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel\/Name"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"Name","kind":"identifier"}],"title":"Name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"externalID":"c:@M@AutomixIQ@objc(cs)TunedArtistModel(py)Name","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"AutomixIQ"}],"role":"symbol"},"sections":[],"abstract":[{"type":"text","text":"The artist name."}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedArtistModel/Name":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel\/Name","type":"topic","navigatorTitle":[{"text":"Name","kind":"identifier"}],"kind":"symbol","title":"Name","url":"\/documentation\/automixiq\/tunedartistmodel\/name","abstract":[{"type":"text","text":"The artist name."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedArtistModel":{"type":"topic","kind":"symbol","title":"TunedArtistModel","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedArtistModel","kind":"identifier"}],"url":"\/documentation\/automixiq\/tunedartistmodel","abstract":[{"type":"text","text":"TunedArtistModel models an artist."}],"navigatorTitle":[{"text":"TunedArtistModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedArtistModel"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","url":"\/documentation\/automixiq","role":"collection","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"Name"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"Name","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"Name"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel~1Name\/title","op":"replace","value":"Name"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel~1Name\/fragments","op":"replace","value":[{"text":"Name","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel\/title","op":"replace","value":"TunedArtistModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel\/fragments","op":"replace","value":[{"text":"TunedArtistModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedArtistModel\/navigatorTitle","op":"replace","value":[{"text":"TunedArtistModel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}