{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBackgroundColor"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiouiconfig\/dialogprimarybuttonbackgroundcolor"]},{"paths":["\/documentation\/socialradiolite\/socialradiouiconfig\/dialogprimarybuttonbackgroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioUIConfig(py)dialogPrimaryButtonBackgroundColor","modules":[{"name":"SocialRadioLite"}],"navigatorTitle":[{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"title":"dialogPrimaryButtonBackgroundColor"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/dialogPrimaryButtonBackgroundColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/dialogPrimaryButtonBackgroundColor","title":"dialogPrimaryButtonBackgroundColor","abstract":[],"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/dialogprimarybuttonbackgroundcolor","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","abstract":[],"role":"symbol","title":"SocialRadioUIConfig","navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"dialogPrimaryButtonBackgroundColor"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBackgroundColor\/title","value":"dialogPrimaryButtonBackgroundColor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1dialogPrimaryButtonBackgroundColor\/fragments","value":[{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/title","op":"replace","value":"SocialRadioUIConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/fragments","value":[{"text":"SocialRadioUIConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/navigatorTitle","value":[{"text":"SocialRadioUIConfig","kind":"identifier"}]}]}]}