{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldTextColor","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiouiconfig\/textfieldtextcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiouiconfig\/textfieldtextcolor"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textFieldTextColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"textFieldTextColor","kind":"identifier"}],"modules":[{"name":"SocialRadioLite"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textFieldTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"title":"textFieldTextColor","roleHeading":"Instance Property","externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioUIConfig(py)textFieldTextColor","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","abstract":[],"role":"symbol","title":"SocialRadioUIConfig","navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig/textFieldTextColor":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig\/textfieldtextcolor","abstract":[],"type":"topic","title":"textFieldTextColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textFieldTextColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig\/textFieldTextColor","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"textFieldTextColor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"textFieldTextColor","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"textFieldTextColor"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" * "},{"text":"textFieldTextColor","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SocialRadioUIConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/fragments","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldTextColor\/title","op":"replace","value":"textFieldTextColor"},{"value":[{"text":"textFieldTextColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig~1textFieldTextColor\/fragments"}]}]}