{"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPluginMetadataModel\/init(from:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","title":"init(from:)","symbolKind":"init","role":"symbol","externalID":"s:9AutomixIQ0A21IQPluginMetadataModelC4fromACs7Decoder_p_tKcfc","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"modules":[{"name":"AutomixIQ"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Decodable.init(from:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPluginMetadataModel"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqpluginmetadatamodel\/init(from:)"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPluginMetadataModel/init(from:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/automixiq\/automixiqpluginmetadatamodel\/init(from:)","type":"topic","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPluginMetadataModel\/init(from:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPluginMetadataModel":{"title":"AutomixIQPluginMetadataModel","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixIQPluginMetadataModel","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqpluginmetadatamodel","abstract":[{"text":"AutomixIQPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"type":"text","text":" "},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPluginMetadataModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPluginMetadataModel"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AutomixIQPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPluginMetadataModel\/title"},{"value":[{"text":"AutomixIQPluginMetadataModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPluginMetadataModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPluginMetadataModel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQPluginMetadataModel"}],"op":"replace"}]}]}