{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"config"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioTunedRestDelegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"SocialRadioTunedRestDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioTunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"]},{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","text":"SocialRadioConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig"},{"kind":"text","text":", "},{"text":"socialRadioTunedRestDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioTunedRestDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate","text":"SocialRadioTunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradioobjc\/initialize(with:socialradiotunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)"]}],"kind":"symbol","metadata":{"role":"symbol","title":"initialize(with:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","roleHeading":"Type Method","externalID":"c:objc(cs)SocialRadioObjC(cm)initializeWithConfig:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","text":"SocialRadioConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialRadioTunedRestDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioTunedRestDelegate","text":"SocialRadioTunedRestDelegate"},{"text":", ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","kind":"typeIdentifier","text":"SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"modules":[{"name":"SocialRadio"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialize(with:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedRestDelegate":{"title":"SocialRadioTunedRestDelegate","kind":"symbol","url":"\/documentation\/socialradio\/socialradiotunedrestdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC":{"title":"SocialRadioObjC","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC","navigatorTitle":[{"text":"SocialRadioObjC","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/socialradioobjc","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioObjC"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC/initialize(with:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)":{"role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialize(with:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/socialradioobjc\/initialize(with:socialradiotunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)","title":"initialize(with:socialRadioTunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","kind":"typeIdentifier","text":"SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioTunedRestDelegate"},{"text":": any ","kind":"text"},{"text":"SocialRadioTunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioTunedRestDelegate"},{"kind":"text","text":", "},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","kind":"typeIdentifier","text":"SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"kind":"symbol","abstract":[],"url":"\/documentation\/socialradio\/socialradioconfig","navigatorTitle":[{"kind":"identifier","text":"SocialRadioConfig"}],"type":"topic","title":"SocialRadioConfig","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioConfig","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","title":"SocialRadioStatusObserverDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"abstract":[],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"topic","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"title":"SocialRadioUIDelegate","url":"\/documentation\/socialradio\/socialradiouidelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SocialRadioTunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate\/fragments","value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}]},{"value":"SocialRadioConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","value":[{"text":"SocialRadioConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioConfig"}]},{"value":"SocialRadioStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"value":"SocialRadioUIDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title"},{"value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"op":"replace"}]}]}