{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"uiConfig"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uiConfig"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig","kind":"typeIdentifier","text":"RadioSDKUIConfig"}],"title":"uiConfig","roleHeading":"Instance Property","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(cs)RadioSDKConfig(py)uiConfig","symbolKind":"property"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uiConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RadioSDKUIConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/socialradio\/radiosdkconfig\/uiconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/radiosdkconfig\/uiconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig\/uiConfig"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RadioSDKUIConfig","kind":"identifier"}],"title":"RadioSDKUIConfig","url":"\/documentation\/socialradio\/radiosdkuiconfig","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKUIConfig"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKConfig/uiConfig":{"url":"\/documentation\/socialradio\/radiosdkconfig\/uiconfig","type":"topic","title":"uiConfig","navigatorTitle":[{"kind":"identifier","text":"uiConfig"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig\/uiConfig","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uiConfig"},{"text":": ","kind":"text"},{"text":"RadioSDKUIConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKConfig":{"abstract":[],"navigatorTitle":[{"text":"RadioSDKConfig","kind":"identifier"}],"title":"RadioSDKConfig","url":"\/documentation\/socialradio\/radiosdkconfig","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKConfig","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"uiConfig"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"uiConfig"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"RadioSDKUIConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"uiConfig"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title","value":"RadioSDKUIConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"op":"replace"},{"value":"uiConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig~1uiConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig~1uiConfig\/fragments","value":[{"kind":"identifier","text":"uiConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/title","value":"RadioSDKConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/fragments","value":[{"text":"RadioSDKConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/navigatorTitle","op":"replace","value":[{"text":"RadioSDKConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}