{"metadata":{"role":"collectionGroup","modules":[{"name":"SocialRadio"}],"title":"Equatable Implementations","roleHeading":"API Collection"},"kind":"article","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiologlevel\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel\/Equatable-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Operators","generated":true,"title":"Operators","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel\/!=(_:_:)"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"url":"\/documentation\/socialradio","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioLogLevel/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/socialradio\/socialradiologlevel\/!=(_:_:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel\/!=(_:_:)","abstract":[],"kind":"symbol","type":"topic","title":"!=(_:_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioLogLevel":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioLogLevel"}],"url":"\/documentation\/socialradio\/socialradiologlevel","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel","abstract":[{"text":"SocialRadio’s available log levels","type":"text"}],"kind":"symbol","type":"topic","title":"SocialRadioLogLevel","navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SocialRadioLogLevel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/title","op":"replace"},{"value":[{"text":"SocialRadioLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/navigatorTitle","op":"replace"}]}]}