{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/noInternetAvailableTooLongOffline"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeNoInternetAvailableTooLongOffline","navigatorTitle":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"AutomixIQ"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}],"title":"ErrorCode.noInternetAvailableTooLongOffline"},"variants":[{"paths":["\/documentation\/automixiq\/errorcode\/nointernetavailabletoolongoffline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/errorcode\/nointernetavailabletoolongoffline"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection","url":"\/documentation\/automixiq","type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"url":"\/documentation\/automixiq\/errorcode","title":"ErrorCode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/noInternetAvailableTooLongOffline":{"abstract":[],"url":"\/documentation\/automixiq\/errorcode\/nointernetavailabletoolongoffline","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailableTooLongOffline"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/noInternetAvailableTooLongOffline","title":"ErrorCode.noInternetAvailableTooLongOffline","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noInternetAvailableTooLongOffline"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ErrorCodeNoInternetAvailableTooLongOffline","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"ErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1noInternetAvailableTooLongOffline\/title","value":"ErrorCodeNoInternetAvailableTooLongOffline"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1noInternetAvailableTooLongOffline\/fragments","value":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}]}]}]}