{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate"]]},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"getCachedTrackWithTrackId:","kind":"identifier"}],"role":"symbol","modules":[{"name":"AutomixIQ"}],"title":"getCachedTrack(trackId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCachedTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate(im)getCachedTrackWithTrackId:","required":true,"roleHeading":"Instance Method"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/getCachedTrack(trackId:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCachedTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"trackId","content":[{"inlineContent":[{"text":"The id of the track that AutomixIQ is streaming.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The entire unencrypted track data, nil if not available."}],"type":"paragraph"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqtunedmusiccachedelegate\/getcachedtrack(trackid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqtunedmusiccachedelegate\/getcachedtrack(trackid:)"]}],"abstract":[{"text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available.","type":"text"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate/getCachedTrack(trackId:)":{"url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate\/getcachedtrack(trackid:)","required":true,"title":"getCachedTrack(trackId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCachedTrack"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate\/getCachedTrack(trackId:)","navigatorTitle":[{"text":"getCachedTrackWithTrackId:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate":{"role":"symbol","title":"AutomixIQTunedMusicCacheDelegate","navigatorTitle":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQTunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"getCachedTrackWithTrackId:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getCachedTrackWithTrackId:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getCachedTrackWithTrackId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"trackId","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":{"parameters":[{"name":"trackId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ is streaming."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The entire unencrypted track data, nil if not available."}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1getCachedTrack(trackId:)\/title","op":"replace","value":"getCachedTrackWithTrackId:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate~1getCachedTrack(trackId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCachedTrackWithTrackId:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/title","value":"AutomixIQTunedMusicCacheDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/fragments","value":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/navigatorTitle","value":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}]}]}]}