{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/uniqueDeviceIdentifier()"]}],"seeAlsoSections":[{"title":"AutomixIQ","anchor":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperationType"],"generated":true}],"metadata":{"symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:@M@SocialRadio@objc(pl)AutomixIQTunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"title":"AutomixIQTunedRestDelegate","role":"symbol","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/socialradio\/automixiqtunedrestdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqtunedrestdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tunedRestTokenExpired"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedUserId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"oldAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"refreshToken"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tokenType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"credentials"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQTunedAuthenticationResponse","text":"AutomixIQTunedAuthenticationResponse"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedUserId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"}],"kind":"symbol","abstract":[{"text":"Called by AutomixIQ when initialised against a Tuned Global backend or when its access token has expired.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","role":"symbol","url":"\/documentation\/socialradio\/automixiqtunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:refreshtoken:tokentype:completion:)","type":"topic","title":"tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate":{"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"url":"\/documentation\/socialradio\/automixiqtunedrestdelegate","title":"AutomixIQTunedRestDelegate","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate/uniqueDeviceIdentifier()":{"url":"\/documentation\/socialradio\/automixiqtunedrestdelegate\/uniquedeviceidentifier()","kind":"symbol","title":"uniqueDeviceIdentifier()","abstract":[{"type":"text","text":"Called by AutomixIQ to request the unique identifier for the users device as a string."},{"text":" ","type":"text"},{"text":"On iOS this is generally the Identifier for Vendor.","type":"text"},{"text":" ","type":"text"},{"text":"It can be any string as long as it is unique","type":"text"},{"type":"text","text":" "},{"type":"text","text":"AutomixIQ will use this string as the UniqueId if it needs to register the device for playback"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uniqueDeviceIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"uniqueDeviceIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/uniqueDeviceIdentifier()","type":"topic","required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedMusicCacheDelegate":{"abstract":[{"text":"AutomixIQTunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"url":"\/documentation\/socialradio\/automixiqtunedmusiccachedelegate","title":"AutomixIQTunedMusicCacheDelegate","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedMusicCacheDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"navigatorTitle":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","title":"AutomixIQStreamingDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation":{"kind":"symbol","url":"\/documentation\/socialradio\/automixiqplaylistoperation","role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"title":"AutomixIQPlaylistOperation","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)":{"title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"asyncGetAuthenticatedDevice","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tunedDeviceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/socialradio\/automixiqtunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required."},{"type":"text","text":" "},{"type":"text","text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”."}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQArtistModel":{"title":"AutomixIQArtistModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQArtistModel","abstract":[{"type":"text","text":"AutomixIQArtistModel models an artist."}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQArtistModel","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqartistmodel","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQArtistModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPluginMetadataModel":{"kind":"symbol","url":"\/documentation\/socialradio\/automixiqpluginmetadatamodel","role":"symbol","navigatorTitle":[{"text":"AutomixIQPluginMetadataModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPluginMetadataModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPluginMetadataModel","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"text":" ","type":"text"},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"title":"AutomixIQPluginMetadataModel","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQWaveformModel"}],"role":"symbol","url":"\/documentation\/socialradio\/automixiqwaveformmodel","title":"AutomixIQWaveformModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate/logAutomixIQMessage(logLevel:message:)":{"kind":"symbol","title":"logAutomixIQMessage(logLevel:message:)","url":"\/documentation\/socialradio\/automixiqtunedrestdelegate\/logautomixiqmessage(loglevel:message:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logAutomixIQMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"logLevel","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQLogLevel","text":"AutomixIQLogLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","abstract":[],"title":"AutomixIQObjC","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQObjC","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqobjc","navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperationType":{"title":"AutomixIQPlaylistOperationType","kind":"symbol","url":"\/documentation\/socialradio\/automixiqplaylistoperationtype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperationType","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedAuthenticationResponse":{"title":"AutomixIQTunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedAuthenticationResponse","abstract":[{"type":"text","text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request"}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQTunedAuthenticationResponse","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqtunedauthenticationresponse","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedAuthenticationResponse"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTrackModel":{"url":"\/documentation\/socialradio\/automixiqtrackmodel","kind":"symbol","type":"topic","role":"symbol","title":"AutomixIQTrackModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel","abstract":[{"type":"text","text":"AutomixIQTrackModel models a track. This metadata is required."}],"navigatorTitle":[{"text":"AutomixIQTrackModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQTrackModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"kind":"symbol","title":"AutomixIQ","type":"topic","url":"\/documentation\/socialradio\/automixiq","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}],"navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}],"abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"title":"AutomixIQStatusObserverDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ-article":{"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","abstract":[{"text":"Availablity of underlying technologies and APIs.","type":"text"}],"role":"article","url":"\/documentation\/socialradio\/automixiq-article","type":"topic","kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode":{"title":"AutomixIQPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqplaybackmode","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQPlaybackMode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","type":"topic","navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatus","title":"AutomixIQStatus","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}],"abstract":[{"text":"AutomixIQStatus models the State of the AutomixIQ during playback.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"title":"AutomixIQStatusVariable","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusVariable"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQLogLevel":{"type":"topic","title":"AutomixIQLogLevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixIQLogLevel","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"abstract":[{"type":"text","text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels"}],"url":"\/documentation\/socialradio\/automixiqloglevel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQConfig","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqconfig","title":"AutomixIQConfig","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"AutomixIQTunedRestDelegate","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate\/uniqueDeviceIdentifier()"]}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperationType"],"title":"AutomixIQ","generated":true}]},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/title","value":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/title","value":"AutomixIQTunedRestDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}]},{"op":"replace","value":"uniqueDeviceIdentifier","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1uniqueDeviceIdentifier()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1uniqueDeviceIdentifier()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"uniqueDeviceIdentifier"}]},{"value":"AutomixIQTunedMusicCacheDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedMusicCacheDelegate\/title"},{"value":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedMusicCacheDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedMusicCacheDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title","value":"AutomixIQStreamingDelegate"},{"op":"replace","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQPlaylistOperation","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/title","value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/fragments"},{"value":"AutomixIQArtistModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQArtistModel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQArtistModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQArtistModel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQArtistModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQArtistModel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPluginMetadataModel\/title","value":"AutomixIQPluginMetadataModel","op":"replace"},{"op":"replace","value":[{"text":"AutomixIQPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPluginMetadataModel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQPluginMetadataModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPluginMetadataModel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","value":"AutomixIQWaveformModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle"},{"value":"logAutomixIQMessageWithLogLevel:message:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperationType\/title","value":"AutomixIQPlaylistOperationType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperationType\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperationType\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}]},{"value":"AutomixIQTunedAuthenticationResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedAuthenticationResponse\/title"},{"value":[{"text":"AutomixIQTunedAuthenticationResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedAuthenticationResponse\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedAuthenticationResponse\/navigatorTitle","value":[{"text":"AutomixIQTunedAuthenticationResponse","kind":"identifier"}],"op":"replace"},{"value":"AutomixIQTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/fragments","value":[{"text":"AutomixIQTrackModel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title","value":"AutomixIQ"},{"value":[{"text":"AutomixIQ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQ"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title","value":"AutomixIQStatusObserverDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/title","value":"AutomixIQPlaybackMode"},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/navigatorTitle"},{"value":"AutomixIQStatus","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatus"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title","value":"AutomixIQStatusVariable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"op":"replace"},{"value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","op":"replace"},{"value":"AutomixIQLogLevel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/fragments","value":[{"kind":"identifier","text":"AutomixIQLogLevel"}]},{"value":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/title","value":"AutomixIQConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/fragments","value":[{"text":"AutomixIQConfig","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/navigatorTitle"}]}]}