{"abstract":[{"type":"text","text":"AutomixIQ playback mode"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/automix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/liveConsumption","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/liveCreation"]},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/init(rawValue:)"]},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH","doc:\/\/org.cocoapods.SocialRadio\/SY"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlaybackMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"AutomixIQ","anchor":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperationType"]}],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@M@SocialRadio@E@AutomixIQPlaybackMode","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackMode"}],"title":"AutomixIQPlaybackMode","role":"symbol","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixIQPlaybackMode","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/socialradio\/automixiqplaybackmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqplaybackmode"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode/init(rawValue:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/init(rawValue:)","kind":"symbol","type":"topic","title":"init(rawValue:)","url":"\/documentation\/socialradio\/automixiqplaybackmode\/init(rawvalue:)"},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation":{"kind":"symbol","url":"\/documentation\/socialradio\/automixiqplaylistoperation","role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"title":"AutomixIQPlaylistOperation","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedRestDelegate":{"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"url":"\/documentation\/socialradio\/automixiqtunedrestdelegate","title":"AutomixIQTunedRestDelegate","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTrackModel":{"url":"\/documentation\/socialradio\/automixiqtrackmodel","kind":"symbol","type":"topic","role":"symbol","title":"AutomixIQTrackModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel","abstract":[{"type":"text","text":"AutomixIQTrackModel models a track. This metadata is required."}],"navigatorTitle":[{"text":"AutomixIQTrackModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQTrackModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPluginMetadataModel":{"kind":"symbol","url":"\/documentation\/socialradio\/automixiqpluginmetadatamodel","role":"symbol","navigatorTitle":[{"text":"AutomixIQPluginMetadataModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPluginMetadataModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPluginMetadataModel","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"text":" ","type":"text"},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"title":"AutomixIQPluginMetadataModel","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"title":"AutomixIQStatusVariable","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusVariable"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","type":"topic","navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatus","title":"AutomixIQStatus","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}],"abstract":[{"text":"AutomixIQStatus models the State of the AutomixIQ during playback.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"kind":"symbol","title":"AutomixIQ","type":"topic","url":"\/documentation\/socialradio\/automixiq","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}],"navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}],"abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode/liveCreation":{"url":"\/documentation\/socialradio\/automixiqplaybackmode\/livecreation","type":"topic","title":"AutomixIQPlaybackMode.liveCreation","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/liveCreation","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackModeLiveCreation","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"liveCreation","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQArtistModel":{"title":"AutomixIQArtistModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQArtistModel","abstract":[{"type":"text","text":"AutomixIQArtistModel models an artist."}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQArtistModel","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqartistmodel","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQArtistModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQConfig","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqconfig","title":"AutomixIQConfig","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ-article":{"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","abstract":[{"text":"Availablity of underlying technologies and APIs.","type":"text"}],"role":"article","url":"\/documentation\/socialradio\/automixiq-article","type":"topic","kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQWaveformModel"}],"role":"symbol","url":"\/documentation\/socialradio\/automixiqwaveformmodel","title":"AutomixIQWaveformModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"navigatorTitle":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","title":"AutomixIQStreamingDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"title":"AutomixIQStatusObserverDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode/Equatable-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","url":"\/documentation\/socialradio\/automixiqplaybackmode\/equatable-implementations","kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQLogLevel":{"type":"topic","title":"AutomixIQLogLevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixIQLogLevel","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"abstract":[{"type":"text","text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels"}],"url":"\/documentation\/socialradio\/automixiqloglevel"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedAuthenticationResponse":{"title":"AutomixIQTunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedAuthenticationResponse","abstract":[{"type":"text","text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request"}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQTunedAuthenticationResponse","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqtunedauthenticationresponse","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedAuthenticationResponse"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode":{"title":"AutomixIQPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqplaybackmode","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQPlaybackMode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode/automix":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"automix","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/automix","title":"AutomixIQPlaybackMode.automix","type":"topic","url":"\/documentation\/socialradio\/automixiqplaybackmode\/automix","navigatorTitle":[{"text":"AutomixIQPlaybackModeAutomix","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQTunedMusicCacheDelegate":{"abstract":[{"text":"AutomixIQTunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"url":"\/documentation\/socialradio\/automixiqtunedmusiccachedelegate","title":"AutomixIQTunedMusicCacheDelegate","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedMusicCacheDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperationType":{"title":"AutomixIQPlaylistOperationType","kind":"symbol","url":"\/documentation\/socialradio\/automixiqplaylistoperationtype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperationType","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode/liveConsumption":{"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackModeLiveConsumption","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqplaybackmode\/liveconsumption","title":"AutomixIQPlaybackMode.liveConsumption","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/liveConsumption","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveConsumption","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","abstract":[],"title":"AutomixIQObjC","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQObjC","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqobjc","navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackMode/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/socialradio\/automixiqplaybackmode\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/RawRepresentable-Implementations"},"doc://org.cocoapods.SocialRadio/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SY","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"AutomixIQPlaybackMode","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixIQPlaybackMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackMode"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/automix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/liveConsumption","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackMode\/liveCreation"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":[{"title":"AutomixIQ","generated":true,"anchor":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQTunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperationType"]}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/title","value":"AutomixIQPlaylistOperation","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/title","value":"AutomixIQTunedRestDelegate"},{"value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedRestDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/title","op":"replace","value":"AutomixIQTrackModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/fragments","value":[{"text":"AutomixIQTrackModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTrackModel\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQTrackModel","kind":"identifier"}]},{"op":"replace","value":"AutomixIQPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPluginMetadataModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPluginMetadataModel\/fragments","value":[{"kind":"identifier","text":"AutomixIQPluginMetadataModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPluginMetadataModel\/navigatorTitle","value":[{"text":"AutomixIQPluginMetadataModel","kind":"identifier"}]},{"op":"replace","value":"AutomixIQStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title","value":"AutomixIQStatus","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments"},{"value":[{"text":"AutomixIQStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title","op":"replace","value":"AutomixIQ"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle","value":[{"text":"AutomixIQ","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"AutomixIQPlaybackModeLiveCreation","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode~1liveCreation\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode~1liveCreation\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackModeLiveCreation"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQArtistModel\/title","value":"AutomixIQArtistModel","op":"replace"},{"value":[{"text":"AutomixIQArtistModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQArtistModel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQArtistModel\/navigatorTitle","value":[{"text":"AutomixIQArtistModel","kind":"identifier"}]},{"value":"AutomixIQConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/fragments","value":[{"kind":"identifier","text":"AutomixIQConfig"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","op":"replace","value":"AutomixIQWaveformModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle","op":"replace"},{"value":"AutomixIQStreamingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]},{"value":"AutomixIQStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title"},{"value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/title","op":"replace","value":"AutomixIQLogLevel"},{"value":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/navigatorTitle"},{"op":"replace","value":"AutomixIQTunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedAuthenticationResponse\/title"},{"value":[{"kind":"identifier","text":"AutomixIQTunedAuthenticationResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedAuthenticationResponse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedAuthenticationResponse\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQTunedAuthenticationResponse"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/title","op":"replace","value":"AutomixIQPlaybackMode"},{"value":[{"text":"AutomixIQPlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode\/navigatorTitle","value":[{"text":"AutomixIQPlaybackMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode~1automix\/title","value":"AutomixIQPlaybackModeAutomix","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode~1automix\/fragments","value":[{"text":"AutomixIQPlaybackModeAutomix","kind":"identifier"}],"op":"replace"},{"value":"AutomixIQTunedMusicCacheDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedMusicCacheDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedMusicCacheDelegate\/fragments","op":"replace","value":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQTunedMusicCacheDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperationType\/title","value":"AutomixIQPlaylistOperationType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperationType\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperationType"}]},{"op":"replace","value":[{"text":"AutomixIQPlaylistOperationType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperationType\/navigatorTitle"},{"value":"AutomixIQPlaybackModeLiveConsumption","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode~1liveConsumption\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackMode~1liveConsumption\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackModeLiveConsumption"}]}]}]}