{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SocialRadioTunedRestDelegate","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiotunedrestdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiotunedrestdelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"]}],"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/uniqueDeviceIdentifier()"]}],"seeAlsoSections":[{"generated":true,"title":"Initializing SocialRadio for use with Tuned Global’s APIs","anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel"]}],"metadata":{"title":"SocialRadioTunedRestDelegate","externalID":"c:@M@SocialRadio@objc(pl)SocialRadioTunedRestDelegate","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"symbolKind":"protocol","roleHeading":"Protocol","role":"symbol"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"title":"SocialRadioStatusVariable","url":"\/documentation\/socialradio\/socialradiostatusvariable","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusVariable"}],"abstract":[{"type":"text","text":"SocialRadio status variable type"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedRestDelegate/uniqueDeviceIdentifier()":{"title":"uniqueDeviceIdentifier()","kind":"symbol","url":"\/documentation\/socialradio\/socialradiotunedrestdelegate\/uniquedeviceidentifier()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"uniqueDeviceIdentifier","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"uniqueDeviceIdentifier"}],"abstract":[{"text":"Called by AutomixIQ to request the unique identifier for the users device as a string.","type":"text"},{"type":"text","text":" "},{"text":"On iOS this is generally the Identifier for Vendor.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It can be any string as long as it is unique"},{"type":"text","text":" "},{"text":"AutomixIQ will use this string as the UniqueId if it needs to register the device for playback","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/uniqueDeviceIdentifier()","role":"symbol","required":true,"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiofeaturesetconfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","abstract":[],"type":"topic","kind":"symbol","title":"SocialRadioFeatureSetConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStreamingDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"url":"\/documentation\/socialradio\/socialradiostreamingdelegate","title":"SocialRadioStreamingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"abstract":[{"text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","title":"SocialRadioStatusObserverDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"abstract":[],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","abstract":[],"title":"SocialRadioUIConfig","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioUIConfig","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiouiconfig","navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedRestDelegate/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)":{"kind":"symbol","title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","required":true,"url":"\/documentation\/socialradio\/socialradiotunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncGetAuthenticatedDevice","kind":"identifier"},{"kind":"text","text":"("},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tunedDeviceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}],"abstract":[{"type":"text","text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required."},{"type":"text","text":" "},{"type":"text","text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”."}],"type":"topic"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioLogLevel":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel","type":"topic","navigatorTitle":[{"text":"SocialRadioLogLevel","kind":"identifier"}],"title":"SocialRadioLogLevel","url":"\/documentation\/socialradio\/socialradiologlevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioLogLevel","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioLogLevel is an enum of all the AutomixIQ available log levels"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode":{"title":"SocialRadioPlaybackMode","navigatorTitle":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","kind":"symbol","abstract":[{"type":"text","text":"SocialRadio playback mode"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradioplaybackmode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-article":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","type":"topic","url":"\/documentation\/socialradio\/initialising-socialradio-article","title":"Initializing SocialRadio","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}],"kind":"article","role":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"kind":"symbol","abstract":[],"url":"\/documentation\/socialradio\/socialradioconfig","navigatorTitle":[{"kind":"identifier","text":"SocialRadioConfig"}],"type":"topic","title":"SocialRadioConfig","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioConfig","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"topic","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"title":"SocialRadioUIDelegate","url":"\/documentation\/socialradio\/socialradiouidelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedRestDelegate":{"title":"SocialRadioTunedRestDelegate","kind":"symbol","url":"\/documentation\/socialradio\/socialradiotunedrestdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedRestDelegate/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)":{"kind":"symbol","title":"tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","required":true,"url":"\/documentation\/socialradio\/socialradiotunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:refreshtoken:tokentype:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tunedRestTokenExpired"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"tunedUserId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"oldAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"refreshToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"tokenType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"credentials","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioTunedAuthenticationResponse","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioTunedAuthenticationResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"tunedUserId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when initialised against a Tuned Global backend or when its access token has expired."}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedRestDelegate/logAutomixIQMessage(logLevel:message:)":{"title":"logAutomixIQMessage(logLevel:message:)","kind":"symbol","url":"\/documentation\/socialradio\/socialradiotunedrestdelegate\/logautomixiqmessage(loglevel:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"logAutomixIQMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"logLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@SocialRadioLogLevel","kind":"typeIdentifier","text":"SocialRadioLogLevel"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","role":"symbol","required":true,"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SocialRadioTunedRestDelegate","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/uniqueDeviceIdentifier()"]}],"op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":[{"generated":true,"title":"Initializing SocialRadio for use with Tuned Global’s APIs","anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTunedRestDelegate"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title","value":"SocialRadioStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle","op":"replace"},{"value":"uniqueDeviceIdentifier","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1uniqueDeviceIdentifier()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1uniqueDeviceIdentifier()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"uniqueDeviceIdentifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/title","value":"SocialRadioFeatureSetConfig","op":"replace"},{"op":"replace","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/title","op":"replace","value":"SocialRadioStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/fragments","op":"replace","value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}]},{"value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","op":"replace","value":"SocialRadioStatusObserverDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","op":"replace","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","value":"SocialRadioUIConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/title"},{"value":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/title","value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/fragments"},{"value":"SocialRadioLogLevel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/title"},{"value":[{"text":"SocialRadioLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/title","value":"SocialRadioPlaybackMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/navigatorTitle","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","value":"SocialRadioConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","value":[{"text":"SocialRadioConfig","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SocialRadioConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","op":"replace","value":"SocialRadioUIDelegate"},{"value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}]},{"value":"SocialRadioTunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate\/fragments","op":"replace"},{"value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/title","value":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/title","op":"replace","value":"logAutomixIQMessageWithLogLevel:message:"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"op":"replace"}]}]}