{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"symbolKind":"class","roleHeading":"Class","modules":[{"name":"SocialRadio"}],"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioTrackModel","title":"SocialRadioTrackModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTrackModel"}],"navigatorTitle":[{"text":"SocialRadioTrackModel","kind":"identifier"}]},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/init(from:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Artists","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Duration-335o7","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Image","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/IsExplicit-4e2z6","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Name","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/ReleaseName","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/TrackId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/TrackNumber-1d0r6","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/bpm","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/duration-8yx99","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/isExplicit-37vid","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/key","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/trackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/trackNumber-3g9rh"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/encode(to:)"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/Se","doc:\/\/org.cocoapods.SocialRadio\/SE","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"seeAlsoSections":[{"anchor":"Data-models","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeCounters","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob"],"title":"Data models"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiotrackmodel"]},{"paths":["\/documentation\/socialradio\/socialradiotrackmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioTrackModel"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/IsExplicit-4e2z6":{"abstract":[{"text":"true if the track is explicit, false otherwise","type":"text"}],"url":"\/documentation\/socialradio\/socialradiotrackmodel\/isexplicit-4e2z6","type":"topic","title":"IsExplicit","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/IsExplicit-4e2z6","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IsExplicit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/Duration-335o7":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiotrackmodel\/duration-335o7","title":"Duration","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Duration-335o7","abstract":[{"type":"text","text":"The duration of a track in seconds"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Duration"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioList":{"type":"topic","url":"\/documentation\/socialradio\/socialradiolist","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","navigatorTitle":[{"kind":"identifier","text":"SocialRadioList"}],"role":"symbol","kind":"symbol","title":"SocialRadioList"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/trackNumber-3g9rh":{"title":"trackNumber","url":"\/documentation\/socialradio\/socialradiotrackmodel\/tracknumber-3g9rh","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"trackNumber","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/trackNumber-3g9rh","abstract":[{"type":"text","text":"Objective-C accessible member for the track number"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPluginMetadataModel":{"type":"topic","url":"\/documentation\/socialradio\/socialradiopluginmetadatamodel","abstract":[{"text":"SocialRadioPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPluginMetadataModel","navigatorTitle":[{"kind":"identifier","text":"SocialRadioPluginMetadataModel"}],"role":"symbol","kind":"symbol","title":"SocialRadioPluginMetadataModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/init(from:)":{"type":"topic","title":"init(from:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/socialradiotrackmodel\/init(from:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/init(from:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)":{"type":"topic","title":"init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/socialradiotrackmodel\/init(trackid:artistname:name:duration:isexplicit:tracknumber:releasename:key:tempo:image:)","abstract":[{"text":"Initialises a Track Model","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"artistName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isExplicit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"trackNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"releaseName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"tempo","kind":"externalParam"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/trackIdentifier":{"navigatorTitle":[{"text":"trackIdentifier","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Objective-C accessible member for the track identifier as String","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackIdentifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/socialradio\/socialradiotrackmodel\/trackidentifier","title":"trackIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/trackIdentifier"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/encode(to:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/encode(to:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP","text":"Encoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[],"url":"\/documentation\/socialradio\/socialradiotrackmodel\/encode(to:)","kind":"symbol","title":"encode(to:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/Name":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Name","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Name"}],"title":"Name","url":"\/documentation\/socialradio\/socialradiotrackmodel\/name","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Name","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The title of a track"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/Se":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/Image":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","title":"Image","abstract":[{"type":"text","text":"The url of the artwork image for this track as a String"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"Image","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/socialradio\/socialradiotrackmodel\/image"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/TrackNumber-1d0r6":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiotrackmodel\/tracknumber-1d0r6","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/TrackNumber-1d0r6","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The index of this track in the album it belongs to"}],"title":"TrackNumber","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeLite":{"type":"topic","url":"\/documentation\/socialradio\/socialradiomixtapelite","abstract":[{"text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeLite"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","navigatorTitle":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"SocialRadioMixtapeLite"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage":{"abstract":[{"type":"text","text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","title":"SocialRadioMixtapeTrackImage","url":"\/documentation\/socialradio\/socialradiomixtapetrackimage","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser":{"abstract":[{"text":"SocialRadioUser models a user","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioUser"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","title":"SocialRadioUser","url":"\/documentation\/socialradio\/socialradiouser","navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/bpm":{"title":"bpm","url":"\/documentation\/socialradio\/socialradiotrackmodel\/bpm","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bpm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"bpm"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/bpm","abstract":[{"type":"text","text":"Objective-C accessible member for the bpm, 09 if unavailable"}]},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioWaveformBlob":{"abstract":[{"type":"text","text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","title":"SocialRadioWaveformBlob","url":"\/documentation\/socialradio\/socialradiowaveformblob","navigatorTitle":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/key":{"url":"\/documentation\/socialradio\/socialradiotrackmodel\/key","kind":"symbol","title":"key","abstract":[{"type":"text","text":"Objective-C accessible member for the key, nil if unavailable"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"key"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"key","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/key","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/TrackId":{"role":"symbol","url":"\/documentation\/socialradio\/socialradiotrackmodel\/trackid","title":"TrackId","kind":"symbol","abstract":[{"text":"The identifier of a track as an integer","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"TrackId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/TrackId","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/duration-8yx99":{"navigatorTitle":[{"text":"duration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/duration-8yx99","kind":"symbol","abstract":[{"text":"Objective-C accessible member for the track duration","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/socialradio\/socialradiotrackmodel\/duration-8yx99","title":"duration"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioArtistModel":{"type":"topic","url":"\/documentation\/socialradio\/socialradioartistmodel","abstract":[{"type":"text","text":"SocialRadioArtistModel models an artist."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioArtistModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioArtistModel","navigatorTitle":[{"text":"SocialRadioArtistModel","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"SocialRadioArtistModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/Artists":{"abstract":[{"type":"text","text":"The artists of a track - the first one is the one to be presented by a UI"}],"url":"\/documentation\/socialradio\/socialradiotrackmodel\/artists","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Artists"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioArtistModel","text":"SocialRadioArtistModel"},{"kind":"text","text":"]?"}],"role":"symbol","kind":"symbol","title":"Artists","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Artists","navigatorTitle":[{"text":"Artists","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatus":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"SocialRadioStatus models the State of the AutomixIQ during playback."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatus"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","title":"SocialRadioStatus","url":"\/documentation\/socialradio\/socialradiostatus","type":"topic","navigatorTitle":[{"text":"SocialRadioStatus","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape":{"kind":"symbol","role":"symbol","abstract":[{"text":"SocialRadioMixtape models a mixtape","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioMixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","title":"SocialRadioMixtape","type":"topic","url":"\/documentation\/socialradio\/socialradiomixtape","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel":{"title":"SocialRadioTrackModel","url":"\/documentation\/socialradio\/socialradiotrackmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioTrackModel","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedAuthenticationResponse":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"abstract":[{"type":"text","text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request"}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiotunedauthenticationresponse","role":"symbol","navigatorTitle":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}],"title":"SocialRadioTunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse"},"doc://org.cocoapods.SocialRadio/SH":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioGenericList":{"abstract":[{"type":"text","text":"SocialRadioGenericList models a list of things"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioGenericList"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","title":"SocialRadioGenericList","url":"\/documentation\/socialradio\/socialradiogenericlist","navigatorTitle":[{"text":"SocialRadioGenericList","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeCounters":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"url":"\/documentation\/socialradio\/socialradiomixtapecounters","title":"SocialRadioMixtapeCounters","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeCounters","role":"symbol","abstract":[{"text":"SocialRadioMixtapeCounters models the set of counters for information about a mixtape","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Data-models-article":{"abstract":[{"type":"text","text":"How data is passed to and from SocialRadio"}],"kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","title":"Data models","url":"\/documentation\/socialradio\/data-models-article","role":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/isExplicit-37vid":{"title":"isExplicit","url":"\/documentation\/socialradio\/socialradiotrackmodel\/isexplicit-37vid","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isExplicit"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isExplicit","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/isExplicit-37vid","abstract":[{"type":"text","text":"Objective-C accessible member for IsExplicit"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/ReleaseName":{"title":"ReleaseName","abstract":[{"type":"text","text":"The name of the album this track belongs to"}],"type":"topic","url":"\/documentation\/socialradio\/socialradiotrackmodel\/releasename","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReleaseName"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ReleaseName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/ReleaseName","role":"symbol"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","url":"\/documentation\/socialradio\/socialradiomixtapetrack","type":"topic","title":"SocialRadioMixtapeTrack","navigatorTitle":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/SE":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SE","type":"unresolvable","title":"Swift.Encodable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SocialRadioTrackModel","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SocialRadioTrackModel","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Artists","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Image","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Name","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/ReleaseName","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/bpm","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/duration-8yx99","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/isExplicit-37vid","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/key","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/trackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/trackNumber-3g9rh"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Data models","anchor":"Data-models","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeCounters","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob"]}]},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTrackModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/title","value":"SocialRadioList","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/fragments","op":"replace","value":[{"text":"SocialRadioList","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioList"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1trackNumber-3g9rh\/title","value":"trackNumber"},{"value":[{"text":"trackNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1trackNumber-3g9rh\/fragments","op":"replace"},{"op":"replace","value":"SocialRadioPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPluginMetadataModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPluginMetadataModel\/fragments","op":"replace","value":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}]},{"op":"replace","value":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPluginMetadataModel\/navigatorTitle"},{"value":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/fragments"},{"value":"trackIdentifier","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1trackIdentifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"trackIdentifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1trackIdentifier\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Name\/title","value":"Name"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Name\/fragments","value":[{"kind":"identifier","text":"Name"}],"op":"replace"},{"value":"Image","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Image"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Image\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/title","value":"SocialRadioMixtapeLite"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/fragments","op":"replace","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}]},{"op":"replace","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/navigatorTitle"},{"value":"SocialRadioMixtapeTrackImage","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/title","value":"SocialRadioUser"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/fragments","op":"replace","value":[{"text":"SocialRadioUser","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUser"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1bpm\/title","value":"bpm","op":"replace"},{"value":[{"kind":"identifier","text":"bpm"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1bpm\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/title","value":"SocialRadioWaveformBlob"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/fragments","value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/navigatorTitle","op":"replace"},{"op":"replace","value":"key","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1key\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1key\/fragments","value":[{"text":"key","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1duration-8yx99\/title","op":"replace","value":"duration"},{"op":"replace","value":[{"text":"duration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1duration-8yx99\/fragments"},{"value":"SocialRadioArtistModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioArtistModel\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioArtistModel\/fragments","value":[{"kind":"identifier","text":"SocialRadioArtistModel"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioArtistModel\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Artists\/title","value":"Artists","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Artists\/fragments","op":"replace","value":[{"kind":"identifier","text":"Artists"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/title","value":"SocialRadioStatus","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/fragments","op":"replace","value":[{"text":"SocialRadioStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/title","value":"SocialRadioMixtape"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/navigatorTitle","op":"replace"},{"value":"SocialRadioTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/title"},{"value":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse\/title","op":"replace","value":"SocialRadioTunedAuthenticationResponse"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse\/fragments","op":"replace","value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}]},{"value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse\/navigatorTitle"},{"value":"SocialRadioMixtapeCounters","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeCounters\/title"},{"value":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeCounters\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeCounters\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1isExplicit-37vid\/title","value":"isExplicit","op":"replace"},{"value":[{"kind":"identifier","text":"isExplicit"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1isExplicit-37vid\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1ReleaseName\/title","value":"ReleaseName","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1ReleaseName\/fragments","op":"replace","value":[{"text":"ReleaseName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/title","value":"SocialRadioMixtapeTrack","op":"replace"},{"op":"replace","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/navigatorTitle","op":"replace"}]}]}