{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel\/logLevelDebug"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/socialradio\/socialradiologlevel\/logleveldebug"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiologlevel\/logleveldebug"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel"]]},"kind":"symbol","metadata":{"title":"SocialRadioLogLevel.logLevelDebug","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelDebug","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@SocialRadio@E@SocialRadioLogLevel@SocialRadioLogLevelLogLevelDebug","navigatorTitle":[{"text":"SocialRadioLogLevelLogLevelDebug","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelDebug","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioLogLevel":{"type":"topic","title":"SocialRadioLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioLogLevel"}],"url":"\/documentation\/socialradio\/socialradiologlevel","navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"kind":"symbol","abstract":[{"text":"SocialRadio’s available log levels","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioLogLevel/logLevelDebug":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiologlevel\/logleveldebug","title":"SocialRadioLogLevel.logLevelDebug","navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelDebug"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel\/logLevelDebug","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelDebug"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SocialRadioLogLevelLogLevelDebug","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SocialRadioLogLevelLogLevelDebug","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"SocialRadioLogLevelLogLevelDebug","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/title","value":"SocialRadioLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/fragments","value":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioLogLevel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel~1logLevelDebug\/title","op":"replace","value":"SocialRadioLogLevelLogLevelDebug"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel~1logLevelDebug\/fragments","op":"replace","value":[{"text":"SocialRadioLogLevelLogLevelDebug","kind":"identifier"}]}]}]}