{"kind":"symbol","abstract":[{"text":"AutomixSDKMixtape models a mixtape","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKGenericList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation"],"title":"Data models","generated":true,"anchor":"Data-models"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtape","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtape","title":"AutomixSDKMixtape","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"roleHeading":"Class","symbolKind":"class","modules":[{"name":"SocialRadio"}],"role":"symbol"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/Se","doc:\/\/org.cocoapods.SocialRadio\/SE","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtape","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkmixtape"]},{"paths":["\/documentation\/socialradio\/automixsdkmixtape"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/init(from:)"],"generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/author","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/cocreators","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/containsExplicitTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/counters","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/created","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/deleted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/descr","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/href","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/id","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/minEngineVersion","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixIsDraft","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixLastForeignUpdate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixLength","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixLive","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixPlus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixRecipeHash","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixUserLikes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/originMix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/recommendedDate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/status","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/tags","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/title","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/tracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/updated","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/waveform"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/tags":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"tags","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"text":"tags","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/tags","url":"\/documentation\/socialradio\/automixsdkmixtape\/tags","type":"topic","kind":"symbol","role":"symbol","title":"tags","abstract":[{"text":"This mixtape’s tags","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Data-models-article":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","abstract":[{"text":"How data is passed to and from SocialRadio","type":"text"}],"kind":"article","url":"\/documentation\/socialradio\/data-models-article","role":"article","title":"Data models"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/cocreators":{"abstract":[{"text":"The list of cocreators for this mixtape","type":"text"}],"navigatorTitle":[{"text":"cocreators","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/cocreators","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/cocreators","type":"topic","title":"cocreators","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cocreators","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AutomixSDKUser","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKUser"},{"text":"]?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/href":{"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/href","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"href"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"href"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/href","title":"href","abstract":[{"text":"The url for its recipe","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"url":"\/documentation\/socialradio\/automixsdkmixtapetrack","title":"AutomixSDKMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperation":{"abstract":[{"text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkplaylistoperation","title":"AutomixSDKPlaylistOperation","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/descr":{"url":"\/documentation\/socialradio\/automixsdkmixtape\/descr","title":"descr","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/descr","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"descr"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"The description of this mixtape","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"descr"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/containsExplicitTracks":{"abstract":[{"type":"text","text":"true if there is at least one explicit track, false otherwise"}],"url":"\/documentation\/socialradio\/automixsdkmixtape\/containsexplicittracks","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"containsExplicitTracks"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsExplicitTracks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/containsExplicitTracks","title":"containsExplicitTracks","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/title":{"title":"title","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/title","abstract":[{"text":"The title of this mixtape","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"title","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/title","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/tracks":{"type":"topic","abstract":[{"type":"text","text":"This mixtape’s tracks"}],"navigatorTitle":[{"text":"tracks","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/tracks","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/tracks","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tracks"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtapeTrack","text":"AutomixSDKMixtapeTrack"},{"kind":"text","text":"]?"}],"role":"symbol","title":"tracks"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/minEngineVersion":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minEngineVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/minEngineVersion","abstract":[{"type":"text","text":"The minimum version of the Pacemaker Engine that can play this mixtape"}],"title":"minEngineVersion","navigatorTitle":[{"text":"minEngineVersion","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/minengineversion"},"doc://org.cocoapods.SocialRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKList":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList","url":"\/documentation\/socialradio\/automixsdklist","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKList"}],"title":"AutomixSDKList"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/author":{"title":"author","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/author","url":"\/documentation\/socialradio\/automixsdkmixtape\/author","abstract":[{"text":"The author of this mixtape","type":"text"}],"navigatorTitle":[{"text":"author","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"author","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKUser","text":"AutomixSDKUser"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","abstract":[{"text":"AutomixSDKWaveformModel models the waveform of a track.","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkwaveformmodel","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"title":"AutomixSDKWaveformModel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/mixPlus":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixPlus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixPlus","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/mixplus","title":"mixPlus","navigatorTitle":[{"kind":"identifier","text":"mixPlus"}],"abstract":[{"type":"text","text":"true if this mixtape was created using the studio, false otherwise"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/Se":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/mixRecipeHash":{"url":"\/documentation\/socialradio\/automixsdkmixtape\/mixrecipehash","navigatorTitle":[{"kind":"identifier","text":"mixRecipeHash"}],"title":"mixRecipeHash","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mixRecipeHash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixRecipeHash","abstract":[{"type":"text","text":"The hash opf this mixtape"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/created":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"created","role":"symbol","abstract":[{"text":"The time this mixtape was created","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/created","navigatorTitle":[{"kind":"identifier","text":"created"}],"url":"\/documentation\/socialradio\/automixsdkmixtape\/created"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrackImage":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrackImage","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrackImage models the image for a track in a mixtape"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtapetrackimage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"title":"AutomixSDKMixtapeTrackImage","navigatorTitle":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKGenericList":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKGenericList","abstract":[{"text":"AutomixSDKGenericList models a list of things","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkgenericlist","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKGenericList"}],"title":"AutomixSDKGenericList","navigatorTitle":[{"text":"AutomixSDKGenericList","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/counters":{"abstract":[{"type":"text","text":"This mixtape’s counters"}],"navigatorTitle":[{"text":"counters","kind":"identifier"}],"title":"counters","url":"\/documentation\/socialradio\/automixsdkmixtape\/counters","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/counters","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"counters","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutomixSDKMixtapeCounters","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtapeCounters"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/recommendedDate":{"title":"recommendedDate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/recommendedDate","navigatorTitle":[{"kind":"identifier","text":"recommendedDate"}],"type":"topic","url":"\/documentation\/socialradio\/automixsdkmixtape\/recommendeddate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recommendedDate"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The last time this mixtape was recommended"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/originMix":{"type":"topic","abstract":[{"text":"The mixtape this was remixed from, nil if its an original","type":"text"}],"title":"originMix","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/originMix","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originMix","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtapeLite","text":"AutomixSDKMixtapeLite"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"originMix"}],"url":"\/documentation\/socialradio\/automixsdkmixtape\/originmix","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/SE":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/mixId":{"abstract":[],"title":"mixId","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixId","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mixId"}],"url":"\/documentation\/socialradio\/automixsdkmixtape\/mixid","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel":{"abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdktrackmodel","title":"AutomixSDKTrackModel","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/mixLive":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixLive","role":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkmixtape\/mixlive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mixLive","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"mixLive","kind":"identifier"}],"abstract":[{"text":"true if this mixtape is live, false otherwise","type":"text"}],"kind":"symbol","title":"mixLive"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPluginMetadataModel":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"text":" ","type":"text"},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"url":"\/documentation\/socialradio\/automixsdkpluginmetadatamodel","title":"AutomixSDKPluginMetadataModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPluginMetadataModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus":{"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"kind":"symbol","title":"AutomixSDKStatus","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/automixsdkstatus","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/init(from:)":{"url":"\/documentation\/socialradio\/automixsdkmixtape\/init(from:)","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/init(from:)","title":"init(from:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/deleted":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"deleted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/deleted","abstract":[{"type":"text","text":"true if this mixtape was deleted, false otherwise"}],"title":"deleted","navigatorTitle":[{"kind":"identifier","text":"deleted"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/deleted"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/status":{"navigatorTitle":[{"text":"status","kind":"identifier"}],"abstract":[{"text":"The status of this mixtape, i.e. “posted”, “cocreation”, “live”, nil otherwise","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/status","title":"status","role":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/status","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/mixIsDraft":{"title":"mixIsDraft","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mixIsDraft","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixIsDraft","navigatorTitle":[{"text":"mixIsDraft","kind":"identifier"}],"abstract":[{"type":"text","text":"True if this mixtape is a draft, false otherwise"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/mixisdraft"},"doc://org.cocoapods.SocialRadio/SH":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse":{"navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"title":"TunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TunedAuthenticationResponse","kind":"identifier"}],"abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/tunedauthenticationresponse"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/waveform":{"abstract":[{"type":"text","text":"The waveform representation for this mixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/waveform","title":"waveform","url":"\/documentation\/socialradio\/automixsdkmixtape\/waveform","navigatorTitle":[{"text":"waveform","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waveform"},{"kind":"text","text":": "},{"text":"AutomixSDKWaveformBlob","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformBlob","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/id":{"title":"id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/socialradio\/automixsdkmixtape\/id","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/id","abstract":[{"type":"text","text":"The identifier for the mixtape"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape":{"abstract":[{"text":"AutomixSDKMixtape models a mixtape","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtape","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape","title":"AutomixSDKMixtape","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/mixLastForeignUpdate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixLastForeignUpdate","role":"symbol","title":"mixLastForeignUpdate","url":"\/documentation\/socialradio\/automixsdkmixtape\/mixlastforeignupdate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mixLastForeignUpdate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"text":"The last time this mixtpae was updated by anothe rcreator","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mixLastForeignUpdate"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKUser":{"abstract":[{"text":"AutomixSDKUser models a user","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKUser","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKUser"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkuser","title":"AutomixSDKUser","type":"topic"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeLite":{"abstract":[{"type":"text","text":"AutomixSDKMixtapeLite models a mixtape with the minimum required fields"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeLite","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtapelite","title":"AutomixSDKMixtapeLite","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformBlob":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKWaveformBlob models the data to create a waveform shape representing a track"}],"url":"\/documentation\/socialradio\/automixsdkwaveformblob","title":"AutomixSDKWaveformBlob","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKArtistModel":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKArtistModel","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKArtistModel models an artist."}],"url":"\/documentation\/socialradio\/automixsdkartistmodel","title":"AutomixSDKArtistModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKArtistModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/updated":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"updated","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"url":"\/documentation\/socialradio\/automixsdkmixtape\/updated","abstract":[{"type":"text","text":"The time this mixtape was last updated"}],"type":"topic","kind":"symbol","title":"updated","navigatorTitle":[{"kind":"identifier","text":"updated"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/updated"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/mixUserLikes":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixUserLikes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mixUserLikes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtape\/mixuserlikes","abstract":[{"type":"text","text":"True if this mixtape is liked by logged in user, false otherwise"}],"title":"mixUserLikes","navigatorTitle":[{"kind":"identifier","text":"mixUserLikes"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/mixLength":{"navigatorTitle":[{"kind":"identifier","text":"mixLength"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixLength","type":"topic","abstract":[{"type":"text","text":"The duration in seconds of this mixtape"}],"title":"mixLength","url":"\/documentation\/socialradio\/automixsdkmixtape\/mixlength","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixLength","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeCounters":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters","abstract":[{"text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtapecounters","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"title":"AutomixSDKMixtapeCounters","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/init":{"abstract":[],"url":"\/documentation\/socialradio\/automixsdkmixtape\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/init","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"AutomixSDKMixtape","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/author","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/cocreators","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/containsExplicitTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/counters","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/created","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/deleted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/descr","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/href","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/id","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/minEngineVersion","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixIsDraft","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixLastForeignUpdate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixLength","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixLive","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixPlus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixRecipeHash","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/mixUserLikes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/originMix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/recommendedDate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/status","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/tags","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/title","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/tracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/updated","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/waveform"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/init"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperation"],"title":"Data models","anchor":"Data-models"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtape","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"tags","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1tags\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"tags"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1tags\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1cocreators\/title","op":"replace","value":"cocreators"},{"value":[{"kind":"identifier","text":"cocreators"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1cocreators\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1href\/title","value":"href"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1href\/fragments","op":"replace","value":[{"kind":"identifier","text":"href"}]},{"value":"AutomixSDKMixtapeTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/title"},{"value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation\/fragments","value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperation\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}]},{"value":"descr","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1descr\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1descr\/fragments","value":[{"text":"descr","kind":"identifier"}],"op":"replace"},{"value":"containsExplicitTracks","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1containsExplicitTracks\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1containsExplicitTracks\/fragments","op":"replace","value":[{"text":"containsExplicitTracks","kind":"identifier"}]},{"value":"title","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1title\/title"},{"value":[{"text":"title","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1title\/fragments","op":"replace"},{"value":"tracks","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1tracks\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1tracks\/fragments","value":[{"text":"tracks","kind":"identifier"}]},{"op":"replace","value":"minEngineVersion","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1minEngineVersion\/title"},{"value":[{"text":"minEngineVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1minEngineVersion\/fragments"},{"value":"AutomixSDKList","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKList\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKList\/fragments","value":[{"kind":"identifier","text":"AutomixSDKList"}]},{"value":[{"kind":"identifier","text":"AutomixSDKList"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKList\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1author\/title","op":"replace","value":"author"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1author\/fragments","value":[{"text":"author","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKWaveformModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/title"},{"value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixPlus\/title","value":"mixPlus"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixPlus\/fragments","op":"replace","value":[{"text":"mixPlus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixRecipeHash\/title","value":"mixRecipeHash"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixRecipeHash\/fragments","value":[{"kind":"identifier","text":"mixRecipeHash"}],"op":"replace"},{"value":"created","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1created\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1created\/fragments","op":"replace","value":[{"kind":"identifier","text":"created"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrackImage\/title","value":"AutomixSDKMixtapeTrackImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrackImage\/fragments","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrackImage\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1counters\/title","value":"counters","op":"replace"},{"value":[{"kind":"identifier","text":"counters"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1counters\/fragments"},{"op":"replace","value":"recommendedDate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1recommendedDate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1recommendedDate\/fragments","value":[{"kind":"identifier","text":"recommendedDate"}],"op":"replace"},{"op":"replace","value":"originMix","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1originMix\/title"},{"value":[{"text":"originMix","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1originMix\/fragments"},{"value":"mixId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixId\/title"},{"op":"replace","value":[{"text":"mixId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/fragments","op":"replace","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/navigatorTitle"},{"op":"replace","value":"mixLive","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixLive\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixLive\/fragments","value":[{"text":"mixLive","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPluginMetadataModel\/title","value":"AutomixSDKPluginMetadataModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPluginMetadataModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPluginMetadataModel\/navigatorTitle","value":[{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus\/title","value":"AutomixSDKStatus"},{"op":"replace","value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1deleted\/title","value":"deleted","op":"replace"},{"value":[{"kind":"identifier","text":"deleted"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1deleted\/fragments","op":"replace"},{"value":"status","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1status\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1status\/fragments","value":[{"text":"status","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixIsDraft\/title","value":"mixIsDraft","op":"replace"},{"value":[{"text":"mixIsDraft","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixIsDraft\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/title","op":"replace","value":"TunedAuthenticationResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/fragments","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/navigatorTitle","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1waveform\/title","value":"waveform","op":"replace"},{"value":[{"text":"waveform","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1waveform\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1id\/title","value":"id","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1id\/fragments","op":"replace","value":[{"text":"id","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/title","value":"AutomixSDKMixtape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/fragments","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/navigatorTitle","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixLastForeignUpdate\/title","value":"mixLastForeignUpdate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixLastForeignUpdate\/fragments","value":[{"kind":"identifier","text":"mixLastForeignUpdate"}],"op":"replace"},{"value":"AutomixSDKUser","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/fragments","value":[{"kind":"identifier","text":"AutomixSDKUser"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/navigatorTitle","value":[{"text":"AutomixSDKUser","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeLite\/title","op":"replace","value":"AutomixSDKMixtapeLite"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeLite\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeLite\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/title","value":"AutomixSDKWaveformBlob"},{"value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/fragments"},{"value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/title","value":"AutomixSDKArtistModel","op":"replace"},{"value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1updated\/title","op":"replace","value":"updated"},{"op":"replace","value":[{"kind":"identifier","text":"updated"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1updated\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixUserLikes\/title","value":"mixUserLikes","op":"replace"},{"value":[{"text":"mixUserLikes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixUserLikes\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixLength\/title","value":"mixLength"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1mixLength\/fragments","value":[{"kind":"identifier","text":"mixLength"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeCounters\/title","value":"AutomixSDKMixtapeCounters"},{"op":"replace","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeCounters\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeCounters\/navigatorTitle"}]}]}