{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelDebug","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelError","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelFatal","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelInfo","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelTrace","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelWarning"],"anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/RawRepresentable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType"],"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs","generated":true,"title":"Initializing SocialRadio for use with Tuned Global’s APIs"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkloglevel"]},{"paths":["\/documentation\/socialradio\/automixsdkloglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH","doc:\/\/org.cocoapods.SocialRadio\/SY"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"identifier"}]}],"kind":"declarations"},{"parameters":[{"name":"logLevelTrace","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ logs with no filter"}]}]},{"content":[{"inlineContent":[{"text":"AutomixIQ logs everything except low level details","type":"text"}],"type":"paragraph"}],"name":"logLevelDebug"},{"name":"logLevelInfo","content":[{"type":"paragraph","inlineContent":[{"text":"AutomixIQ logs everything except low level details and debug statements","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"AutomixIQ only logs errors and warnings"}],"type":"paragraph"}],"name":"logLevelWarning"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ only logs errors"}]}],"name":"logLevelError"},{"content":[{"type":"paragraph","inlineContent":[{"text":"AutomixIQ only logs fatal errors","type":"text"}]}],"name":"logLevelFatal"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKLogLevel"}],"symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevel"}],"modules":[{"name":"SocialRadio"}],"roleHeading":"Enumeration","role":"symbol","title":"AutomixSDKLogLevel","externalID":"c:@M@SocialRadio@E@AutomixSDKLogLevel"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate":{"role":"symbol","type":"topic","title":"AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","url":"\/documentation\/socialradio\/automixsdkstreamingdelegate","kind":"symbol"},"doc://org.cocoapods.SocialRadio/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedRestDelegate"}],"title":"TunedRestDelegate","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"url":"\/documentation\/socialradio\/tunedrestdelegate","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SY"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/logLevelFatal":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelFatal","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelFatal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"logLevelFatal","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkloglevel\/loglevelfatal","title":"AutomixSDKLogLevel.logLevelFatal","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKUIConfig"}],"url":"\/documentation\/socialradio\/radiosdkuiconfig","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"title":"RadioSDKUIConfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/Equatable-Implementations":{"kind":"article","url":"\/documentation\/socialradio\/automixsdkloglevel\/equatable-implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/Equatable-Implementations","title":"Equatable Implementations"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/socialradio\/automixsdkloglevel\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig":{"role":"symbol","type":"topic","title":"AutomixSDKConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKConfig"}],"navigatorTitle":[{"text":"AutomixSDKConfig","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","url":"\/documentation\/socialradio\/automixsdkconfig","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"title":"AutomixSDKStatusVariable","url":"\/documentation\/socialradio\/automixsdkstatusvariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKConfig":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","title":"RadioSDKConfig","abstract":[],"url":"\/documentation\/socialradio\/radiosdkconfig","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKConfig"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedMusicCacheDelegate":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"title":"TunedMusicCacheDelegate","abstract":[{"text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"url":"\/documentation\/socialradio\/tunedmusiccachedelegate","navigatorTitle":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/logLevelWarning":{"url":"\/documentation\/socialradio\/automixsdkloglevel\/loglevelwarning","navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelWarning","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"logLevelWarning","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelWarning","title":"AutomixSDKLogLevel.logLevelWarning","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-article":{"role":"article","title":"Initializing SocialRadio","type":"topic","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}],"url":"\/documentation\/socialradio\/initialising-socialradio-article","kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/logLevelInfo":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelInfo","kind":"identifier"}],"title":"AutomixSDKLogLevel.logLevelInfo","url":"\/documentation\/socialradio\/automixsdkloglevel\/loglevelinfo","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelInfo","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelInfo"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKFeatureSetConfig":{"role":"symbol","type":"topic","title":"RadioSDKFeatureSetConfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"navigatorTitle":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/radiosdkfeaturesetconfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/logLevelTrace":{"kind":"symbol","abstract":[],"url":"\/documentation\/socialradio\/automixsdkloglevel\/logleveltrace","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}],"title":"AutomixSDKLogLevel.logLevelTrace","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelTrace","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelTrace","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackMode":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"title":"AutomixSDKPlaybackMode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"url":"\/documentation\/socialradio\/automixsdkplaybackmode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}]},"doc://org.cocoapods.SocialRadio/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKLogLevel"}],"title":"AutomixSDKLogLevel","url":"\/documentation\/socialradio\/automixsdkloglevel","abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperationType":{"role":"symbol","type":"topic","title":"AutomixSDKPlaylistOperationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}],"navigatorTitle":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","url":"\/documentation\/socialradio\/automixsdkplaylistoperationtype","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/logLevelDebug":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelDebug","kind":"identifier"}],"title":"AutomixSDKLogLevel.logLevelDebug","url":"\/documentation\/socialradio\/automixsdkloglevel\/logleveldebug","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelDebug","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"logLevelDebug","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/logLevelError":{"url":"\/documentation\/socialradio\/automixsdkloglevel\/loglevelerror","navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelError","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelError"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelError","title":"AutomixSDKLogLevel.logLevelError","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/init(rawValue:)","url":"\/documentation\/socialradio\/automixsdkloglevel\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","title":"init(rawValue:)","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate":{"title":"AutomixSDKStatusObserverDelegate","url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate":{"role":"symbol","title":"RadioUIDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioUIDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RadioUIDelegate"}],"abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"url":"\/documentation\/socialradio\/radiouidelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"AutomixSDKLogLevel","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelDebug","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelError","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelFatal","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelInfo","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelTrace","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel\/logLevelWarning"],"anchor":"Enumeration-Cases","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":[{"title":"Initializing SocialRadio for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType"],"generated":true,"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKLogLevel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/fragments","op":"replace","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","value":"TunedRestDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle","op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelFatal\/title","value":"AutomixSDKLogLevelLogLevelFatal"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelFatal\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelFatal"}]},{"op":"replace","value":"RadioSDKUIConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}]},{"op":"replace","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/title","value":"AutomixSDKConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/fragments","op":"replace","value":[{"text":"AutomixSDKConfig","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]},{"op":"replace","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/title","value":"RadioSDKConfig"},{"value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace"},{"value":"TunedMusicCacheDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/title"},{"value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/fragments"},{"value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixSDKLogLevelLogLevelWarning","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelWarning\/title"},{"value":[{"text":"AutomixSDKLogLevelLogLevelWarning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelWarning\/fragments"},{"value":"AutomixSDKLogLevelLogLevelInfo","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelInfo\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelInfo\/fragments","value":[{"text":"AutomixSDKLogLevelLogLevelInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/title","op":"replace","value":"RadioSDKFeatureSetConfig"},{"value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelTrace\/title","value":"AutomixSDKLogLevelLogLevelTrace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelTrace\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}],"op":"replace"},{"op":"replace","value":"AutomixSDKPlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel"},{"op":"replace","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/title","value":"AutomixSDKPlaylistOperationType","op":"replace"},{"value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/fragments","op":"replace"},{"value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelDebug\/title","value":"AutomixSDKLogLevelLogLevelDebug","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelDebug\/fragments","op":"replace","value":[{"text":"AutomixSDKLogLevelLogLevelDebug","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKLogLevelLogLevelError","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelError\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel~1logLevelError\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelError"}],"op":"replace"},{"value":"AutomixSDKStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace"},{"op":"replace","value":"RadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/title"},{"value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/navigatorTitle","value":[{"text":"RadioUIDelegate","kind":"identifier"}]}]}]}