{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogDescriptionFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogDescriptionTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBackgroundColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBorder","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBorderColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBorderRadius","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBackgroundColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorder","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorderColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorderRadius","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogTitleFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogTitleTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/fontFamily","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeHuge","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeLarge","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeMatchMachine","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeRegular","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeSmall","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeTiny","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldBackgroundColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldBorderRadius","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldPlaceholderTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/titleFontSize"],"title":"Instance Properties","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"title":"Conforms To"}],"metadata":{"role":"symbol","title":"RadioSDKUIConfig","externalID":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDKUIConfig","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"RadioSDKUIConfig"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/radiosdkuiconfig"]},{"paths":["\/documentation\/socialradio\/radiosdkuiconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKUIConfig","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"],"title":"Initializing SocialRadio for use with Tuned Global’s APIs","anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogSecondaryButtonBackgroundColor":{"abstract":[],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonbackgroundcolor","title":"dialogSecondaryButtonBackgroundColor","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"dialogSecondaryButtonBackgroundColor","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/fontFamily":{"title":"fontFamily","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/fontFamily","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fontFamily"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/fontfamily","navigatorTitle":[{"text":"fontFamily","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/radioUIFontSizeTiny":{"abstract":[],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/radiouifontsizetiny","title":"radioUIFontSizeTiny","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeTiny","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeTiny"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeTiny"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKUIConfig"}],"url":"\/documentation\/socialradio\/radiosdkuiconfig","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"title":"RadioSDKUIConfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogPrimaryButtonFontBold":{"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonFontBold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogprimarybuttonfontbold","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonFontBold","title":"dialogPrimaryButtonFontBold","kind":"symbol","navigatorTitle":[{"text":"dialogPrimaryButtonFontBold","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedMusicCacheDelegate":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"title":"TunedMusicCacheDelegate","abstract":[{"text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"url":"\/documentation\/socialradio\/tunedmusiccachedelegate","navigatorTitle":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/radioUIFontSizeMatchMachine":{"abstract":[],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/radiouifontsizematchmachine","title":"radioUIFontSizeMatchMachine","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeMatchMachine","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeMatchMachine","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeMatchMachine"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/textFieldBackgroundColor":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/textfieldbackgroundcolor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldBackgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"title":"textFieldBackgroundColor","navigatorTitle":[{"text":"textFieldBackgroundColor","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldBackgroundColor","abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/radioUIFontSizeRegular":{"abstract":[],"title":"radioUIFontSizeRegular","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeRegular","url":"\/documentation\/socialradio\/radiosdkuiconfig\/radiouifontsizeregular","navigatorTitle":[{"text":"radioUIFontSizeRegular","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeRegular"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaylistOperationType":{"role":"symbol","type":"topic","title":"AutomixSDKPlaylistOperationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}],"navigatorTitle":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","url":"\/documentation\/socialradio\/automixsdkplaylistoperationtype","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogTitleTextColor":{"abstract":[],"title":"dialogTitleTextColor","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogTitleTextColor","url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogtitletextcolor","navigatorTitle":[{"kind":"identifier","text":"dialogTitleTextColor"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dialogTitleTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/textFieldPlaceholderTextColor":{"abstract":[],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/textfieldplaceholdertextcolor","title":"textFieldPlaceholderTextColor","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldPlaceholderTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textFieldPlaceholderTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"textFieldPlaceholderTextColor","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/radioUIFontSizeSmall":{"abstract":[],"title":"radioUIFontSizeSmall","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeSmall","url":"\/documentation\/socialradio\/radiosdkuiconfig\/radiouifontsizesmall","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeSmall"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeSmall"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/radioUIFontSizeHuge":{"abstract":[],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/radiouifontsizehuge","title":"radioUIFontSizeHuge","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeHuge","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeHuge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeHuge"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/textFieldFontBold":{"abstract":[],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/textfieldfontbold","title":"textFieldFontBold","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textFieldFontBold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"textFieldFontBold","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldFontBold","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogPrimaryButtonBorderRadius":{"abstract":[],"title":"dialogPrimaryButtonBorderRadius","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBorderRadius","url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogprimarybuttonborderradius","navigatorTitle":[{"text":"dialogPrimaryButtonBorderRadius","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dialogPrimaryButtonBorderRadius","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig":{"role":"symbol","type":"topic","title":"AutomixSDKConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKConfig"}],"navigatorTitle":[{"text":"AutomixSDKConfig","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","url":"\/documentation\/socialradio\/automixsdkconfig","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"title":"AutomixSDKStatusVariable","url":"\/documentation\/socialradio\/automixsdkstatusvariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate":{"title":"AutomixSDKStatusObserverDelegate","url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackMode":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"title":"AutomixSDKPlaybackMode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"url":"\/documentation\/socialradio\/automixsdkplaybackmode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogSecondaryButtonFontBold":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonfontbold","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonFontBold"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonFontBold"}],"title":"dialogSecondaryButtonFontBold","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonFontBold","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/textFieldTextColor":{"kind":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig\/textfieldtextcolor","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldTextColor","title":"textFieldTextColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textFieldTextColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"textFieldTextColor"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/init(fontfamily:titlefontsize:radiouifontsizehuge:radiouifontsizelarge:radiouifontsizeregular:radiouifontsizesmall:radiouifontsizetiny:radiouifontsizematchmachine:textfieldfontbold:textfieldbackgroundcolor:textfieldborderradius:textfieldtex-7khup","navigatorTitle":[{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","title":"init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"fontFamily","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"titleFontSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeHuge"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeLarge","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeRegular"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"radioUIFontSizeSmall","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"radioUIFontSizeTiny","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeMatchMachine"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"textFieldFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"textFieldBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textFieldBorderRadius"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"textFieldTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textFieldPlaceholderTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogTitleFontBold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogTitleTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogDescriptionFontBold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogDescriptionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonFontBold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorderRadius"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogPrimaryButtonBorder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBorderColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonBorderRadius","kind":"externalParam"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogSecondaryButtonTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonBorderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogPrimaryButtonBorderColor":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogprimarybuttonbordercolor","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonBorderColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"title":"dialogPrimaryButtonBorderColor","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBorderColor","navigatorTitle":[{"kind":"identifier","text":"dialogPrimaryButtonBorderColor"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogDescriptionFontBold":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogDescriptionFontBold","role":"symbol","abstract":[],"title":"dialogDescriptionFontBold","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dialogDescriptionFontBold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"dialogDescriptionFontBold"}],"kind":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogdescriptionfontbold","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate":{"role":"symbol","type":"topic","title":"AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","url":"\/documentation\/socialradio\/automixsdkstreamingdelegate","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKFeatureSetConfig":{"role":"symbol","type":"topic","title":"RadioSDKFeatureSetConfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"navigatorTitle":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/radiosdkfeaturesetconfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogTitleFontBold":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogtitlefontbold","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dialogTitleFontBold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"dialogTitleFontBold","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogTitleFontBold","navigatorTitle":[{"kind":"identifier","text":"dialogTitleFontBold"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogSecondaryButtonBorder":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorder","role":"symbol","abstract":[],"title":"dialogSecondaryButtonBorder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonBorder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonBorder"}],"kind":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonborder","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogDescriptionTextColor":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogdescriptiontextcolor","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dialogDescriptionTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"title":"dialogDescriptionTextColor","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogDescriptionTextColor","navigatorTitle":[{"kind":"identifier","text":"dialogDescriptionTextColor"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogSecondaryButtonBorderRadius":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorderRadius","role":"symbol","abstract":[],"title":"dialogSecondaryButtonBorderRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"navigatorTitle":[{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonborderradius","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/radioUIFontSizeLarge":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/radiouifontsizelarge","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"radioUIFontSizeLarge","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"radioUIFontSizeLarge","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeLarge","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeLarge"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKLogLevel"}],"title":"AutomixSDKLogLevel","url":"\/documentation\/socialradio\/automixsdkloglevel","abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/textFieldBorderRadius":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/textfieldborderradius","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textFieldBorderRadius","kind":"identifier"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"title":"textFieldBorderRadius","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldBorderRadius","navigatorTitle":[{"kind":"identifier","text":"textFieldBorderRadius"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogPrimaryButtonBorder":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogPrimaryButtonBorder"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogprimarybuttonborder","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBorder","title":"dialogPrimaryButtonBorder","navigatorTitle":[{"text":"dialogPrimaryButtonBorder","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/titleFontSize":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/titleFontSize","role":"symbol","abstract":[],"title":"titleFontSize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleFontSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"titleFontSize","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig\/titlefontsize","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogSecondaryButtonTextColor":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttontextcolor","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"dialogSecondaryButtonTextColor","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonTextColor","navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonTextColor"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogPrimaryButtonBackgroundColor":{"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogprimarybuttonbackgroundcolor","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"title":"dialogPrimaryButtonBackgroundColor","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBackgroundColor","navigatorTitle":[{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogSecondaryButtonBorderColor":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorderColor","role":"symbol","abstract":[],"title":"dialogSecondaryButtonBorderColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBorderColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonBorderColor"}],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonbordercolor","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedRestDelegate"}],"title":"TunedRestDelegate","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"url":"\/documentation\/socialradio\/tunedrestdelegate","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioUIDelegate":{"role":"symbol","title":"RadioUIDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioUIDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RadioUIDelegate"}],"abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"url":"\/documentation\/socialradio\/radiouidelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-article":{"role":"article","title":"Initializing SocialRadio","type":"topic","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}],"url":"\/documentation\/socialradio\/initialising-socialradio-article","kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKConfig":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","title":"RadioSDKConfig","abstract":[],"url":"\/documentation\/socialradio\/radiosdkconfig","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKConfig"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogPrimaryButtonTextColor":{"role":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogprimarybuttontextcolor","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonTextColor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogPrimaryButtonTextColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","navigatorTitle":[{"text":"dialogPrimaryButtonTextColor","kind":"identifier"}],"title":"dialogPrimaryButtonTextColor"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"RadioSDKUIConfig","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogDescriptionFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogDescriptionTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBackgroundColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBorder","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBorderColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonBorderRadius","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogPrimaryButtonTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBackgroundColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorder","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorderColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorderRadius","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogTitleFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogTitleTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/fontFamily","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeHuge","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeLarge","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeMatchMachine","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeRegular","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeSmall","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeTiny","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldBackgroundColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldBorderRadius","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldFontBold","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldPlaceholderTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/textFieldTextColor","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/titleFontSize"],"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaylistOperationType","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel"],"generated":true,"title":"Initializing SocialRadio for use with Tuned Global’s APIs","anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKUIConfig"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBackgroundColor\/title","op":"replace","value":"dialogSecondaryButtonBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBackgroundColor\/fragments","value":[{"kind":"identifier","text":"dialogSecondaryButtonBackgroundColor"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1fontFamily\/title","op":"replace","value":"fontFamily"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1fontFamily\/fragments","op":"replace","value":[{"text":"fontFamily","kind":"identifier"}]},{"value":"radioUIFontSizeTiny","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeTiny\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeTiny\/fragments","value":[{"kind":"identifier","text":"radioUIFontSizeTiny"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title","op":"replace","value":"RadioSDKUIConfig"},{"value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle","op":"replace","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonFontBold\/title","value":"dialogPrimaryButtonFontBold"},{"op":"replace","value":[{"text":"dialogPrimaryButtonFontBold","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonFontBold\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/title","op":"replace","value":"TunedMusicCacheDelegate"},{"value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeMatchMachine\/title","value":"radioUIFontSizeMatchMachine","op":"replace"},{"value":[{"text":"radioUIFontSizeMatchMachine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeMatchMachine\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldBackgroundColor\/title","op":"replace","value":"textFieldBackgroundColor"},{"value":[{"text":"textFieldBackgroundColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldBackgroundColor\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeRegular\/title","op":"replace","value":"radioUIFontSizeRegular"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeRegular\/fragments","op":"replace","value":[{"text":"radioUIFontSizeRegular","kind":"identifier"}]},{"value":"AutomixSDKPlaylistOperationType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/title"},{"value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaylistOperationType\/navigatorTitle","value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogTitleTextColor\/title","value":"dialogTitleTextColor","op":"replace"},{"value":[{"kind":"identifier","text":"dialogTitleTextColor"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogTitleTextColor\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldPlaceholderTextColor\/title","op":"replace","value":"textFieldPlaceholderTextColor"},{"value":[{"text":"textFieldPlaceholderTextColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldPlaceholderTextColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeSmall\/title","value":"radioUIFontSizeSmall"},{"value":[{"text":"radioUIFontSizeSmall","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeSmall\/fragments"},{"value":"radioUIFontSizeHuge","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeHuge\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeHuge\/fragments","value":[{"text":"radioUIFontSizeHuge","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldFontBold\/title","value":"textFieldFontBold"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldFontBold\/fragments","value":[{"text":"textFieldFontBold","kind":"identifier"}]},{"value":"dialogPrimaryButtonBorderRadius","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonBorderRadius\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonBorderRadius\/fragments","value":[{"text":"dialogPrimaryButtonBorderRadius","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/title","value":"AutomixSDKConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/fragments","value":[{"kind":"identifier","text":"AutomixSDKConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKConfig"}]},{"value":"AutomixSDKStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/fragments","op":"replace","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/navigatorTitle","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"AutomixSDKStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/title"},{"op":"replace","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/title","value":"AutomixSDKPlaybackMode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/fragments","value":[{"text":"AutomixSDKPlaybackMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackMode\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}]},{"op":"replace","value":"dialogSecondaryButtonFontBold","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonFontBold\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonFontBold\/fragments","value":[{"text":"dialogSecondaryButtonFontBold","kind":"identifier"}]},{"value":"textFieldTextColor","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldTextColor\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldTextColor\/fragments","value":[{"kind":"identifier","text":"textFieldTextColor"}],"op":"replace"},{"op":"replace","value":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}]},{"op":"replace","value":"dialogPrimaryButtonBorderColor","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonBorderColor\/title"},{"value":[{"text":"dialogPrimaryButtonBorderColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonBorderColor\/fragments"},{"value":"dialogDescriptionFontBold","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogDescriptionFontBold\/title"},{"value":[{"kind":"identifier","text":"dialogDescriptionFontBold"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogDescriptionFontBold\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/fragments","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/title","value":"RadioSDKFeatureSetConfig","op":"replace"},{"value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogTitleFontBold\/title","value":"dialogTitleFontBold","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogTitleFontBold\/fragments","value":[{"text":"dialogTitleFontBold","kind":"identifier"}],"op":"replace"},{"value":"dialogSecondaryButtonBorder","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBorder\/title","op":"replace"},{"value":[{"text":"dialogSecondaryButtonBorder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBorder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogDescriptionTextColor\/title","value":"dialogDescriptionTextColor"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogDescriptionTextColor\/fragments","op":"replace","value":[{"text":"dialogDescriptionTextColor","kind":"identifier"}]},{"value":"dialogSecondaryButtonBorderRadius","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBorderRadius\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBorderRadius\/fragments","value":[{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"radioUIFontSizeLarge","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeLarge\/title"},{"value":[{"text":"radioUIFontSizeLarge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeLarge\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/title","op":"replace","value":"AutomixSDKLogLevel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/fragments","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"op":"replace"},{"value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldBorderRadius\/title","value":"textFieldBorderRadius"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1textFieldBorderRadius\/fragments","value":[{"text":"textFieldBorderRadius","kind":"identifier"}],"op":"replace"},{"value":"dialogPrimaryButtonBorder","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonBorder\/title"},{"value":[{"kind":"identifier","text":"dialogPrimaryButtonBorder"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonBorder\/fragments","op":"replace"},{"value":"titleFontSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1titleFontSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1titleFontSize\/fragments","value":[{"kind":"identifier","text":"titleFontSize"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonTextColor\/title","value":"dialogSecondaryButtonTextColor","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonTextColor\/fragments","value":[{"text":"dialogSecondaryButtonTextColor","kind":"identifier"}],"op":"replace"},{"value":"dialogPrimaryButtonBackgroundColor","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonBackgroundColor\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonBackgroundColor\/fragments","op":"replace","value":[{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"}]},{"value":"dialogSecondaryButtonBorderColor","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBorderColor\/title"},{"value":[{"text":"dialogSecondaryButtonBorderColor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBorderColor\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title","value":"TunedRestDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/title","value":"RadioUIDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/fragments","value":[{"kind":"identifier","text":"RadioUIDelegate"}]},{"value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioUIDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/title","value":"RadioSDKConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/fragments","op":"replace","value":[{"text":"RadioSDKConfig","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonTextColor\/title","op":"replace","value":"dialogPrimaryButtonTextColor"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogPrimaryButtonTextColor\/fragments","value":[{"kind":"identifier","text":"dialogPrimaryButtonTextColor"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}