{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"SocialRadio"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"artistName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isExplicit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"trackNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"releaseName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tempo"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"role":"symbol","title":"init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel(im)initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","symbolKind":"init"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel"]]},"abstract":[{"text":"Initialises a Track Model","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdktrackmodel\/init(trackid:artistname:name:duration:isexplicit:tracknumber:releasename:key:tempo:image:)"]},{"paths":["\/documentation\/socialradio\/automixsdktrackmodel\/init(trackid:artistname:name:duration:isexplicit:tracknumber:releasename:key:tempo:image:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"artistName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isExplicit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"trackNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"releaseName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tempo","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"trackId","content":[{"inlineContent":[{"type":"text","text":"The identifier of the track"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the main artist of the track"}]}],"name":"artistName"},{"name":"name","content":[{"inlineContent":[{"type":"text","text":"The title of the track"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The track duration in seconds"}],"type":"paragraph"}],"name":"duration"},{"content":[{"inlineContent":[{"text":"True if the track contains explicit lyrics, false otherwise","type":"text"}],"type":"paragraph"}],"name":"isExplicit"},{"name":"trackNumber","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index of the track in the album it was released in"}]}]},{"name":"releaseName","content":[{"type":"paragraph","inlineContent":[{"text":"The nemae of the release this track’s in","type":"text"}]}]},{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key of this track as a String in Camelot format, i.e. 8m, nil if unavailable"}]}]},{"name":"tempo","content":[{"inlineContent":[{"type":"text","text":"The bpm of this track as a float"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url of the artwork image for this track as a String"}]}],"name":"image"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"artistName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isExplicit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"trackNumber"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"releaseName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"tempo"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/socialradio\/automixsdktrackmodel\/init(trackid:artistname:name:duration:isexplicit:tracknumber:releasename:key:tempo:image:)","abstract":[{"type":"text","text":"Initialises a Track Model"}],"type":"topic","kind":"symbol","title":"init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","navigatorTitle":[{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel":{"abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdktrackmodel","title":"AutomixSDKTrackModel","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTrackId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"trackId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"artistName:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"artistName"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"name"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration:"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"duration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isExplicit:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isExplicit"},{"text":" ","kind":"text"},{"text":"trackNumber:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"trackNumber","kind":"internalParam"},{"kind":"text","text":" "},{"text":"releaseName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"releaseName"},{"kind":"text","text":" "},{"kind":"identifier","text":"key:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"key","kind":"internalParam"},{"kind":"text","text":" "},{"text":"tempo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":") "},{"text":"tempo","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"image:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"trackId","content":[{"inlineContent":[{"text":"The identifier of the track","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The name of the main artist of the track","type":"text"}]}],"name":"artistName"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The title of the track"}]}],"name":"name"},{"content":[{"inlineContent":[{"text":"The track duration in seconds","type":"text"}],"type":"paragraph"}],"name":"duration"},{"name":"isExplicit","content":[{"type":"paragraph","inlineContent":[{"text":"True if the track contains explicit lyrics, false otherwise","type":"text"}]}]},{"name":"trackNumber","content":[{"inlineContent":[{"type":"text","text":"The index of the track in the album it was released in"}],"type":"paragraph"}]},{"name":"releaseName","content":[{"inlineContent":[{"type":"text","text":"The nemae of the release this track’s in"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The key of this track as a String in Camelot format, i.e. 8m, nil if unavailable","type":"text"}],"type":"paragraph"}],"name":"key"},{"name":"tempo","content":[{"type":"paragraph","inlineContent":[{"text":"The bpm of this track as a float","type":"text"}]}]},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url of the artwork image for this track as a String"}]}]}]}},{"op":"replace","value":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/title","op":"replace","value":"AutomixSDKTrackModel"},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/navigatorTitle","op":"replace"}]}]}