{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate"]]},"metadata":{"roleHeading":"Instance Method","required":true,"navigatorTitle":[{"text":"statusChangedWithVariables:status:","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate(im)statusChangedWithVariables:status:","role":"symbol","modules":[{"name":"SocialRadio"}],"title":"statusChanged(variables:status:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"variables"},{"text":": [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"], ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Called when the status of AutomixIQ changes"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"variables","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of AutomixSDKStatusVariable that changed since last time this method was called, or since AutomixIQ was initialised."}]}],"name":"variables"},{"name":"status","content":[{"inlineContent":[{"type":"text","text":"The current status of AutomixIQ"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkstatusobserverdelegate\/statuschanged(variables:status:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkstatusobserverdelegate\/statuschanged(variables:status:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate\/statusChanged(variables:status:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatus":{"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}],"type":"topic","title":"AutomixSDKStatus","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus","url":"\/documentation\/socialradio\/automixsdkstatus"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate/statusChanged(variables:status:)":{"abstract":[{"type":"text","text":"Called when the status of AutomixIQ changes"}],"type":"topic","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"statusChangedWithVariables:status:"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate\/statusChanged(variables:status:)","title":"statusChanged(variables:status:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"statusChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"variables","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"text":"AutomixSDKStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKStatus"},{"text":")","kind":"text"}],"url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate\/statuschanged(variables:status:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate":{"role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"title":"AutomixSDKStatusObserverDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"statusChangedWithVariables:status:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"statusChangedWithVariables:status:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"statusChangedWithVariables:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"text":"variables","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatus","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"status","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":{"parameters":[{"name":"variables","content":[{"inlineContent":[{"text":"A list of AutomixSDKStatusVariable that changed since last time this method was called, or since AutomixIQ was initialised.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The current status of AutomixIQ"}],"type":"paragraph"}],"name":"status"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus\/title","op":"replace","value":"AutomixSDKStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatus"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatus\/navigatorTitle"},{"op":"replace","value":"statusChangedWithVariables:status:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate~1statusChanged(variables:status:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"statusChangedWithVariables:status:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate~1statusChanged(variables:status:)\/fragments"},{"value":"AutomixSDKStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/fragments","op":"replace","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]}]}]}