{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"playlistDiff","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : [","kind":"text"},{"text":"AutomixIQPlaylistOperation","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQPlaylistOperation","kind":"typeIdentifier"},{"text":"]]?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"playlistDiff","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQStatus(py)playlistDiff","modules":[{"name":"SocialRadio"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlistDiff"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : ["},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQPlaylistOperation","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","text":"AutomixIQPlaylistOperation"},{"kind":"text","text":"]]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqstatus\/playlistdiff"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqstatus\/playlistdiff"]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playlistDiff","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}],"title":"AutomixIQStatus","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatus"}],"url":"\/documentation\/socialradio\/automixiqstatus","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation":{"navigatorTitle":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixiqplaylistoperation","role":"symbol","abstract":[{"type":"text","text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","title":"AutomixIQPlaylistOperation"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playlistDiff":{"type":"topic","url":"\/documentation\/socialradio\/automixiqstatus\/playlistdiff","abstract":[],"kind":"symbol","title":"playlistDiff","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlistDiff"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : ["},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQPlaylistOperation","kind":"typeIdentifier","text":"AutomixIQPlaylistOperation"},{"kind":"text","text":"]]?"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playlistDiff","navigatorTitle":[{"kind":"identifier","text":"playlistDiff"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"url":"\/documentation\/socialradio","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"playlistDiff"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"playlistDiff","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSArray<AutomixIQPlaylistOperation *> *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"playlistDiff"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title","op":"replace","value":"AutomixIQStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments","op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/title","op":"replace","value":"AutomixIQPlaylistOperation"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playlistDiff\/title","op":"replace","value":"playlistDiff"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playlistDiff\/fragments","op":"replace","value":[{"kind":"identifier","text":"playlistDiff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}