{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/automixiqconfig\/equaliserconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqconfig\/equaliserconfig"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"equaliserConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQEqualiserConfig","text":"AutomixIQEqualiserConfig"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"SocialRadio"}],"symbolKind":"property","navigatorTitle":[{"text":"equaliserConfig","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQConfig(py)equaliserConfig","title":"equaliserConfig"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig\/equaliserConfig"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"equaliserConfig"},{"text":": ","kind":"text"},{"text":"AutomixIQEqualiserConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQEqualiserConfig"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQEqualiserConfig":{"type":"topic","url":"\/documentation\/socialradio\/automixiqequaliserconfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig","title":"AutomixIQEqualiserConfig","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQEqualiserConfig","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQEqualiserConfig"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig/equaliserConfig":{"role":"symbol","title":"equaliserConfig","navigatorTitle":[{"kind":"identifier","text":"equaliserConfig"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig\/equaliserConfig","url":"\/documentation\/socialradio\/automixiqconfig\/equaliserconfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"equaliserConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQEqualiserConfig","text":"AutomixIQEqualiserConfig"}],"abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig":{"type":"topic","url":"\/documentation\/socialradio\/automixiqconfig","abstract":[],"title":"AutomixIQConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQConfig","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQConfig","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"equaliserConfig"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"equaliserConfig","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AutomixIQEqualiserConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQEqualiserConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQEqualiserConfig","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"equaliserConfig","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"AutomixIQEqualiserConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig\/fragments","value":[{"kind":"identifier","text":"AutomixIQEqualiserConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQEqualiserConfig\/navigatorTitle","value":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig~1equaliserConfig\/title","value":"equaliserConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig~1equaliserConfig\/fragments","value":[{"text":"equaliserConfig","kind":"identifier"}]},{"value":"AutomixIQConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}]},{"value":[{"text":"AutomixIQConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/navigatorTitle"}]}]}