{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)"},"variants":[{"paths":["\/documentation\/automixiq\/automixiq\/initialise(config:automixiqtunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiq\/initialise(config:automixiqtunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Initialiser for AutomixIQ to work against a Tuned Global backend","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"metadata":{"roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixIQConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automixIQTunedRestDelegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate","text":"AutomixIQTunedRestDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate","text":"AutomixIQTunedMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQ(cm)initialiseWithConfig:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","title":"initialise(config:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","navigatorTitle":[{"kind":"identifier","text":"initialiseWithConfig:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"title":"Initialization","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)"],"generated":true,"anchor":"Initialization"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","text":"AutomixIQConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"automixIQTunedRestDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate","kind":"typeIdentifier","text":"AutomixIQTunedRestDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automixIQStatusDelegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixIQStatusObserverDelegate"},{"kind":"text","text":"?, "},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","text":"AutomixIQTunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The AutomixIQ Configuration","type":"text"}],"type":"paragraph"}],"name":"config"},{"content":[{"inlineContent":[{"text":"The delegate in charge of feeding and renewing Tuned Global OAuth2 access tokens. See AutomixIQTunedRestDelegate.","type":"text"}],"type":"paragraph"}],"name":"automixIQTunedRestDelegate"},{"content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixIQStatusObserverDelegate."}],"type":"paragraph"}],"name":"automixIQStatusDelegate"},{"name":"musicCacheDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of saving and feeding in cached music to and from AutomixIQ","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate":{"type":"topic","title":"AutomixIQTunedRestDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqtunedrestdelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"role":"symbol","title":"AutomixIQConfig","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"abstract":[],"url":"\/documentation\/automixiq\/automixiqconfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQConfig","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ":{"abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQ","kind":"identifier"}],"title":"AutomixIQ","url":"\/documentation\/automixiq\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/initialise(config:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)":{"type":"topic","title":"initialise(config:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","kind":"typeIdentifier","text":"AutomixIQConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automixIQTunedRestDelegate"},{"kind":"text","text":": "},{"text":"AutomixIQTunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate"},{"text":", ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixIQStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": "},{"text":"AutomixIQTunedMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixiq\/initialise(config:automixiqtunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","navigatorTitle":[{"text":"initialiseWithConfig:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"abstract":[{"text":"Initialiser for AutomixIQ to work against a Tuned Global backend","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate":{"role":"symbol","title":"AutomixIQTunedMusicCacheDelegate","navigatorTitle":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQTunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)":{"type":"topic","title":"initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixIQConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig"},{"text":", ","kind":"text"},{"text":"automixIQStreamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate","kind":"typeIdentifier","text":"AutomixIQStreamingDelegate"},{"text":", ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixiq\/initialise(config:automixiqstreamingdelegate:automixiqstatusdelegate:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)","navigatorTitle":[{"text":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:","kind":"identifier"}],"abstract":[{"text":"Initialiser for AutomixIQ to work against any custom set of APIs.","type":"text"},{"type":"text","text":" "},{"text":"This method takes in delegates to update the UI and feeds all data and metadata the AutomixIQ needs.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"title":"AutomixIQStatusObserverDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"initialiseWithConfig:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"initialiseWithConfig:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Initialization","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)"],"title":"Initialization"}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"initialiseWithConfig:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AutomixIQConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"text":" ","kind":"text"},{"text":"automixIQTunedRestDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<AutomixIQTunedRestDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate"},{"text":") ","kind":"text"},{"text":"automixIQTunedRestDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"text":"automixIQStatusDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","text":"id<AutomixIQStatusObserverDelegate>"},{"kind":"text","text":") "},{"text":"automixIQStatusDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"musicCacheDelegate:"},{"kind":"text","text":"("},{"text":"id<AutomixIQTunedMusicCacheDelegate>","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"musicCacheDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"config","content":[{"inlineContent":[{"type":"text","text":"The AutomixIQ Configuration"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of feeding and renewing Tuned Global OAuth2 access tokens. See AutomixIQTunedRestDelegate.","type":"text"}]}],"name":"automixIQTunedRestDelegate"},{"name":"automixIQStatusDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixIQStatusObserverDelegate."}]}]},{"name":"musicCacheDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of saving and feeding in cached music to and from AutomixIQ"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":"AutomixIQTunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/title"},{"value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/fragments"},{"op":"replace","value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title","value":"AutomixIQConfig"},{"value":[{"text":"AutomixIQConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQConfig","kind":"identifier"}]},{"value":"AutomixIQ","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/title","op":"replace"},{"op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)\/title","value":"initialiseWithConfig:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/title","op":"replace","value":"AutomixIQTunedMusicCacheDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/fragments","op":"replace","value":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/navigatorTitle","value":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)\/title","op":"replace","value":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:"}]},{"value":"AutomixIQStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}