{"metadata":{"externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeCannotRestoreAudioSession","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotRestoreAudioSession"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"AutomixIQ"}],"title":"ErrorCode.cannotRestoreAudioSession","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotRestoreAudioSession"}]},"variants":[{"paths":["\/documentation\/automixiq\/errorcode\/cannotrestoreaudiosession"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode\/cannotrestoreaudiosession"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotRestoreAudioSession","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotRestoreAudioSession"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"type":"topic","kind":"symbol","title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotRestoreAudioSession":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotRestoreAudioSession"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotRestoreAudioSession","title":"ErrorCode.cannotRestoreAudioSession","role":"symbol","url":"\/documentation\/automixiq\/errorcode\/cannotrestoreaudiosession","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"ErrorCodeCannotRestoreAudioSession","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","title":"AutomixIQ","url":"\/documentation\/automixiq","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"ErrorCodeCannotRestoreAudioSession","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodeCannotRestoreAudioSession"}]}]},"path":"\/primaryContentSections\/0"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotRestoreAudioSession\/title","value":"ErrorCodeCannotRestoreAudioSession"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotRestoreAudioSession\/fragments","value":[{"text":"ErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}