{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadTracksOutOfBounds"}]}]}],"sections":[],"metadata":{"modules":[{"name":"AutomixIQ"}],"roleHeading":"Case","title":"ErrorCode.loadTracksOutOfBounds","externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeLoadTracksOutOfBounds","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"loadTracksOutOfBounds","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeLoadTracksOutOfBounds"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksOutOfBounds"},"variants":[{"paths":["\/documentation\/automixiq\/errorcode\/loadtracksoutofbounds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/errorcode\/loadtracksoutofbounds"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","title":"AutomixIQ","url":"\/documentation\/automixiq","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"type":"topic","kind":"symbol","title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/loadTracksOutOfBounds":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"loadTracksOutOfBounds","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode\/loadtracksoutofbounds","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeLoadTracksOutOfBounds"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksOutOfBounds","role":"symbol","title":"ErrorCode.loadTracksOutOfBounds","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodeLoadTracksOutOfBounds"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ErrorCodeLoadTracksOutOfBounds","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ErrorCodeLoadTracksOutOfBounds","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}]},{"op":"replace","value":"ErrorCodeLoadTracksOutOfBounds","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1loadTracksOutOfBounds\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeLoadTracksOutOfBounds"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1loadTracksOutOfBounds\/fragments"}]}]}