{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"metadata":{"title":"ErrorCode.offAlreadyTurningOff","symbolKind":"case","externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeOffAlreadyTurningOff","navigatorTitle":[{"text":"ErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"offAlreadyTurningOff","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offAlreadyTurningOff"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"offAlreadyTurningOff","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/errorcode\/offalreadyturningoff"]},{"paths":["\/documentation\/automixiq\/errorcode\/offalreadyturningoff"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/offAlreadyTurningOff":{"kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/offalreadyturningoff","navigatorTitle":[{"text":"ErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"title":"ErrorCode.offAlreadyTurningOff","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offAlreadyTurningOff","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"offAlreadyTurningOff"}],"abstract":[],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","title":"AutomixIQ","url":"\/documentation\/automixiq","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"type":"topic","kind":"symbol","title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCodeOffAlreadyTurningOff"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"ErrorCodeOffAlreadyTurningOff","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offAlreadyTurningOff\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offAlreadyTurningOff\/fragments","value":[{"text":"ErrorCodeOffAlreadyTurningOff","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}