{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"didNotAddAdIndexPassedAlready"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/errorcode\/didnotaddadindexpassedalready"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode\/didnotaddadindexpassedalready"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeDidNotAddAdIndexPassedAlready","modules":[{"name":"AutomixIQ"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didNotAddAdIndexPassedAlready","kind":"identifier"}],"title":"ErrorCode.didNotAddAdIndexPassedAlready","navigatorTitle":[{"text":"ErrorCodeDidNotAddAdIndexPassedAlready","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/didNotAddAdIndexPassedAlready","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/didNotAddAdIndexPassedAlready":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeDidNotAddAdIndexPassedAlready"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/didNotAddAdIndexPassedAlready","title":"ErrorCode.didNotAddAdIndexPassedAlready","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didNotAddAdIndexPassedAlready"}],"url":"\/documentation\/automixiq\/errorcode\/didnotaddadindexpassedalready","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"title":"ErrorCode","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","kind":"symbol","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"url":"\/documentation\/automixiq","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ErrorCodeDidNotAddAdIndexPassedAlready","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ErrorCodeDidNotAddAdIndexPassedAlready","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ErrorCodeDidNotAddAdIndexPassedAlready","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1didNotAddAdIndexPassedAlready\/title","value":"ErrorCodeDidNotAddAdIndexPassedAlready","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1didNotAddAdIndexPassedAlready\/fragments","value":[{"text":"ErrorCodeDidNotAddAdIndexPassedAlready","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}