{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/nextTrack0SecondsAnchorTime","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"nextTrack0SecondsAnchorTime","externalID":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel(py)nextTrack0SecondsAnchorTime","roleHeading":"Instance Property","modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqwaveformmodel\/nexttrack0secondsanchortime"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqwaveformmodel\/nexttrack0secondsanchortime"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel"]]},"abstract":[{"type":"text","text":"The time in the current track where the next track’s starting duration would be. This is not where the next track would begin playback as the first few seconds may be muted to create a better transition."},{"type":"text","text":" "},{"type":"text","text":"This is helpful to align waveforms when rendering transitions."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel/nextTrack0SecondsAnchorTime":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The time in the current track where the next track’s starting duration would be. This is not where the next track would begin playback as the first few seconds may be muted to create a better transition."},{"type":"text","text":" "},{"type":"text","text":"This is helpful to align waveforms when rendering transitions."}],"navigatorTitle":[{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/nextTrack0SecondsAnchorTime","role":"symbol","type":"topic","title":"nextTrack0SecondsAnchorTime","kind":"symbol","url":"\/documentation\/socialradio\/automixiqwaveformmodel\/nexttrack0secondsanchortime"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"title":"AutomixIQWaveformModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQWaveformModel"}],"role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/automixiqwaveformmodel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"nextTrack0SecondsAnchorTime","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"nextTrack0SecondsAnchorTime"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTrack0SecondsAnchorTime"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel~1nextTrack0SecondsAnchorTime\/title","value":"nextTrack0SecondsAnchorTime","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel~1nextTrack0SecondsAnchorTime\/fragments","value":[{"kind":"identifier","text":"nextTrack0SecondsAnchorTime"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","value":"AutomixIQWaveformModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"op":"replace"}]}]}