{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"abstract":[{"text":"AutomixIQPlaybackEventType is an enum of all the available playback events","type":"text"}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH","doc:\/\/org.cocoapods.AutomixIQ\/SY"]}],"metadata":{"externalID":"c:@M@AutomixIQ@E@AutomixIQPlaybackEventType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"symbolKind":"enum","role":"symbol","modules":[{"name":"AutomixIQ"}],"title":"AutomixIQPlaybackEventType","roleHeading":"Enumeration","navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/init(rawValue:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/Equatable-Implementations","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/RawRepresentable-Implementations"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","seeAlsoSections":[{"generated":true,"anchor":"Updating-custom-players-UI","title":"Updating custom player’s UI","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Start of track playback"}]}],"name":"trackPlayStart"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track has played for 5 seconds"}]}],"name":"trackPlayPlayed5Secs"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track has played for 30 seconds, this is called every 30 seconds of playback"}]}],"name":"trackPlayHeartbeat30Secs"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track has started transitioning into the next track"}]}],"name":"trackPlayStartMixingIntoNext"},{"name":"trackPlaySkipped","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track has been skipped to the next track (this is also called when seeking through the same track)"}]}]},{"name":"trackPlayFinished","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track has finished playback (if transitioning this is called at the end of the transition for the first track)"}]}]},{"name":"mixPlaybackEnded","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Queue has reached the end and there are no more tracks to play"}]}]}]},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/rawrepresentable-implementations","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","url":"\/documentation\/automixiq","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlayPlayed5Secs":{"type":"topic","url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayplayed5secs","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayPlayed5Secs"}],"role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"}],"title":"AutomixIQPlaybackEventType.trackPlayPlayed5Secs","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/Equatable-Implementations":{"type":"topic","url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/equatable-implementations","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/Equatable-Implementations","title":"Equatable Implementations"},"doc://org.cocoapods.AutomixIQ/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlayStart":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStart"}],"url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplaystart","type":"topic","kind":"symbol","title":"AutomixIQPlaybackEventType.trackPlayStart","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStart","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayStart"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlayFinished":{"abstract":[],"title":"AutomixIQPlaybackEventType.trackPlayFinished","url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayfinished","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayFinished","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayFinished","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayFinished"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlayStartMixingIntoNext":{"type":"topic","url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplaystartmixingintonext","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackPlayStartMixingIntoNext","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext","title":"AutomixIQPlaybackEventType.trackPlayStartMixingIntoNext"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType":{"type":"topic","title":"AutomixIQPlaybackEventType","url":"\/documentation\/automixiq\/automixiqplaybackeventtype","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/mixPlaybackEnded":{"type":"topic","title":"AutomixIQPlaybackEventType.mixPlaybackEnded","url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/mixplaybackended","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/mixPlaybackEnded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlaybackEnded"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}],"abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"type":"topic","url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"title":"AutomixIQStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlaySkipped":{"type":"topic","url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayskipped","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlaySkipped","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"title":"AutomixIQPlaybackEventType.trackPlaySkipped","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlaySkipped"},"doc://org.cocoapods.AutomixIQ/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/init(rawValue:)":{"abstract":[],"url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/init(rawvalue:)","type":"topic","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Updating-custom-player's-UI-article":{"abstract":[{"type":"text","text":"How to create a UI to reflect the AutomixIQ player"}],"url":"\/documentation\/automixiq\/updating-custom-player's-ui-article","type":"topic","kind":"article","title":"Updating your player UI","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","role":"article"},"doc://org.cocoapods.AutomixIQ/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SY"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlayHeartbeat30Secs":{"type":"topic","url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayheartbeat30secs","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayHeartbeat30Secs","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayHeartbeat30Secs"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayHeartbeat30Secs","title":"AutomixIQPlaybackEventType.trackPlayHeartbeat30Secs"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixIQPlaybackEventType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStartMixingIntoNext"],"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Updating custom player’s UI","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"],"anchor":"Updating-custom-players-UI"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/fragments"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayStart","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayStart\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStart"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayStart\/fragments"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayFinished","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayFinished\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayFinished"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayFinished\/fragments"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayStartMixingIntoNext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStartMixingIntoNext"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayStartMixingIntoNext\/fragments"},{"op":"replace","value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/navigatorTitle"},{"op":"replace","value":"AutomixIQPlaybackEventTypeMixPlaybackEnded","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/fragments"},{"op":"replace","value":"AutomixIQStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlaySkipped","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlaySkipped\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlaySkipped"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlaySkipped\/fragments"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayHeartbeat30Secs","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayHeartbeat30Secs\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayHeartbeat30Secs"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayHeartbeat30Secs\/fragments"}]}]}