{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionStartTimeSeconds"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/transitionstarttimeseconds"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/transitionstarttimeseconds"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/transitionStartTimeSeconds"},"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionStartTimeSeconds","kind":"identifier"}],"title":"AutomixIQStatusVariable.transitionStartTimeSeconds","roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@AutomixIQStatusVariable@AutomixIQStatusVariableTransitionStartTimeSeconds","navigatorTitle":[{"text":"AutomixIQStatusVariableTransitionStartTimeSeconds","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"symbolKind":"case"},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/automixiq","title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/transitionStartTimeSeconds":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionStartTimeSeconds"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/transitionStartTimeSeconds","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableTransitionStartTimeSeconds"}],"abstract":[],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/transitionstarttimeseconds","kind":"symbol","role":"symbol","title":"AutomixIQStatusVariable.transitionStartTimeSeconds"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable":{"abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"kind":"symbol","title":"AutomixIQStatusVariable","role":"symbol","navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AutomixIQStatusVariableTransitionStartTimeSeconds"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableTransitionStartTimeSeconds"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"AutomixIQStatusVariableTransitionStartTimeSeconds","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1transitionStartTimeSeconds\/title","value":"AutomixIQStatusVariableTransitionStartTimeSeconds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1transitionStartTimeSeconds\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableTransitionStartTimeSeconds"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/title","value":"AutomixIQStatusVariable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/fragments","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]}]}]}