{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioUserCounters(im)init","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","title":"init"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters\/init"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/socialradio\/socialradiousercounters\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUserCounters":{"title":"SocialRadioUserCounters","role":"symbol","url":"\/documentation\/socialradio\/socialradiousercounters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUserCounters"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioUserCounters models a user’s counters"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUserCounters"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUserCounters/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/socialradio\/socialradiousercounters\/init","title":"init","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters\/init","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/title","value":"SocialRadioUserCounters"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/fragments","value":[{"text":"SocialRadioUserCounters","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUserCounters"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}