{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiousercounters\/userid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiousercounters\/userid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters\/userId"},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioUserCounters(py)userId","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Property","title":"userId","navigatorTitle":[{"text":"userId","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters"]]},"abstract":[{"type":"text","text":"The user identifier"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUserCounters/userId":{"type":"topic","title":"userId","role":"symbol","navigatorTitle":[{"text":"userId","kind":"identifier"}],"abstract":[{"type":"text","text":"The user identifier"}],"url":"\/documentation\/socialradio\/socialradiousercounters\/userid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters\/userId","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUserCounters":{"title":"SocialRadioUserCounters","role":"symbol","url":"\/documentation\/socialradio\/socialradiousercounters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUserCounters"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioUserCounters models a user’s counters"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUserCounters","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUserCounters"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"userId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"userId"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"userId"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters~1userId\/title","op":"replace","value":"userId"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters~1userId\/fragments","value":[{"kind":"identifier","text":"userId"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/title","value":"SocialRadioUserCounters"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/fragments","value":[{"text":"SocialRadioUserCounters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUserCounters\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUserCounters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}