{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextNoTrackAvailable"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/nextNoTrackAvailable"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errorcode\/nextnotrackavailable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/errorcode\/nextnotrackavailable"]}],"metadata":{"roleHeading":"Case","externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeNextNoTrackAvailable","modules":[{"name":"SocialRadio"}],"title":"ErrorCode.nextNoTrackAvailable","symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"ErrorCodeNextNoTrackAvailable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextNoTrackAvailable"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"title":"ErrorCode","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"type":"topic","url":"\/documentation\/socialradio\/errorcode","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/nextNoTrackAvailable":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/nextNoTrackAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextNoTrackAvailable"}],"url":"\/documentation\/socialradio\/errorcode\/nextnotrackavailable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNextNoTrackAvailable"}],"kind":"symbol","title":"ErrorCode.nextNoTrackAvailable","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodeNextNoTrackAvailable"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodeNextNoTrackAvailable"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodeNextNoTrackAvailable"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}]},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle"},{"op":"replace","value":"ErrorCodeNextNoTrackAvailable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1nextNoTrackAvailable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeNextNoTrackAvailable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1nextNoTrackAvailable\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}