{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqplaylistoperation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqplaylistoperation"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate"],"title":"AutomixIQ","anchor":"AutomixIQ","generated":true}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"title":"AutomixIQPlaylistOperation","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@SocialRadio@objc(cs)AutomixIQPlaylistOperation","modules":[{"name":"SocialRadio"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},"sections":[],"abstract":[{"text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/fromIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/toIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/trackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/trackInstance","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/type"],"anchor":"Instance-Properties","generated":true}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"kind":"relationships","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedPluginMetadataModel":{"navigatorTitle":[{"kind":"identifier","text":"TunedPluginMetadataModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","url":"\/documentation\/socialradio\/tunedpluginmetadatamodel","type":"topic","title":"TunedPluginMetadataModel","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedPluginMetadataModel"}],"abstract":[{"text":"TunedPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"text":" ","type":"text"},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"title":"AutomixIQObjC","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/socialradio\/automixiqobjc","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQObjC","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation/trackInstance":{"url":"\/documentation\/socialradio\/automixiqplaylistoperation\/trackinstance","abstract":[{"type":"text","text":"The unique identifier for this track in this playlist, i.e. if the same track happens to appear twice in a playlist this identifier will differ."}],"title":"trackInstance","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackInstance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/trackInstance","navigatorTitle":[{"text":"trackInstance","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig":{"title":"AutomixIQConfig","url":"\/documentation\/socialradio\/automixiqconfig","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQConfig","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQConfig","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"role":"symbol","abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"title":"TunedTrackModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","url":"\/documentation\/socialradio\/tunedtrackmodel","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation/init":{"title":"init","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/init","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/socialradio\/automixiqplaylistoperation\/init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode":{"title":"TunedAutomixPlaybackMode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"url":"\/documentation\/socialradio\/tunedautomixplaybackmode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"navigatorTitle":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation/type":{"title":"type","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/type","kind":"symbol","abstract":[{"type":"text","text":"The type of operation, Add \/ Remove \/ Move"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqplaylistoperation\/type","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutomixIQPlaylistOperationType","preciseIdentifier":"c:@M@SocialRadio@E@AutomixIQPlaylistOperationType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"type","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation":{"role":"symbol","title":"AutomixIQPlaylistOperation","abstract":[{"type":"text","text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","url":"\/documentation\/socialradio\/automixiqplaylistoperation","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},"doc://org.cocoapods.SocialRadio/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation/fromIndex":{"navigatorTitle":[{"text":"fromIndex","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/fromIndex","url":"\/documentation\/socialradio\/automixiqplaylistoperation\/fromindex","title":"fromIndex","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The index int the playlist the track was removed from or was moved from, -1 otherwise."}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate":{"title":"AutomixIQMusicCacheDelegate","url":"\/documentation\/socialradio\/automixiqmusiccachedelegate","abstract":[{"type":"text","text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","abstract":[{"type":"text","text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"type":"topic","url":"\/documentation\/socialradio\/automixiq","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQ","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"title":"AutomixIQWaveformModel","url":"\/documentation\/socialradio\/automixiqwaveformmodel","abstract":[{"text":"AutomixIQWaveformModel models the waveform of a track.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse":{"navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","url":"\/documentation\/socialradio\/tunedauthenticationresponse","type":"topic","title":"TunedAuthenticationResponse","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAuthenticationResponse"}],"abstract":[{"text":"TunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"title":"TunedRestDelegate","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"url":"\/documentation\/socialradio\/tunedrestdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedArtistModel":{"navigatorTitle":[{"kind":"identifier","text":"TunedArtistModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","url":"\/documentation\/socialradio\/tunedartistmodel","type":"topic","title":"TunedArtistModel","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedArtistModel"}],"abstract":[{"type":"text","text":"TunedArtistModel models an artist."}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"title":"AutomixIQStatusVariable","url":"\/documentation\/socialradio\/automixiqstatusvariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"role":"symbol","title":"AutomixIQStatusObserverDelegate","abstract":[{"text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation/toIndex":{"title":"toIndex","url":"\/documentation\/socialradio\/automixiqplaylistoperation\/toindex","abstract":[{"text":"The index int the playlist the track was added to or was moved to, -1 otherwise.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"toIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"toIndex"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/toIndex","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ-article":{"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","kind":"article","abstract":[{"type":"text","text":"Availablity of underlying technologies and APIs."}],"type":"topic","url":"\/documentation\/socialradio\/automixiq-article","role":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"url":"\/documentation\/socialradio","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel":{"title":"TunedLogLevel","abstract":[{"type":"text","text":"TunedLogLevel is an enum of all the AutomixIQ available log levels"}],"url":"\/documentation\/socialradio\/tunedloglevel","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedLogLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TunedLogLevel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","url":"\/documentation\/socialradio\/automixiqstatus","type":"topic","title":"AutomixIQStatus","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation/trackIdentifier":{"title":"trackIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/trackIdentifier","kind":"symbol","abstract":[{"type":"text","text":"The identifier of the track."}],"type":"topic","url":"\/documentation\/socialradio\/automixiqplaylistoperation\/trackidentifier","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"trackIdentifier","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixIQPlaylistOperation","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/fromIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/toIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/trackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/trackInstance","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/type"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation\/init"],"anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"],"anchor":"AutomixIQ","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaylistOperation","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TunedPluginMetadataModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/title"},{"value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/fragments"},{"value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/navigatorTitle"},{"op":"replace","value":"trackInstance","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1trackInstance\/title"},{"op":"replace","value":[{"text":"trackInstance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1trackInstance\/fragments"},{"op":"replace","value":"AutomixIQConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/navigatorTitle"},{"op":"replace","value":"TunedTrackModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle"},{"op":"replace","value":"TunedAutomixPlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/navigatorTitle"},{"op":"replace","value":"type","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1type\/title"},{"op":"replace","value":[{"kind":"identifier","text":"type"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1type\/fragments"},{"op":"replace","value":"AutomixIQPlaylistOperation","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/navigatorTitle"},{"op":"replace","value":"fromIndex","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1fromIndex\/title"},{"op":"replace","value":[{"kind":"identifier","text":"fromIndex"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1fromIndex\/fragments"},{"op":"replace","value":"AutomixIQMusicCacheDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQ","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle"},{"op":"replace","value":"AutomixIQWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle"},{"op":"replace","value":"TunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/navigatorTitle"},{"op":"replace","value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle"},{"op":"replace","value":"TunedArtistModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle"},{"op":"replace","value":"toIndex","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1toIndex\/title"},{"op":"replace","value":[{"kind":"identifier","text":"toIndex"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1toIndex\/fragments"},{"op":"replace","value":"TunedLogLevel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatus","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle"},{"op":"replace","value":"trackIdentifier","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1trackIdentifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"trackIdentifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation~1trackIdentifier\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}