{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canBack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canMixNow","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canOnOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canPlayPause","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canReorderTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canSeek","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canSkipToNext","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canSkipToPrevious","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/explicitLyricsFiltering","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/mixing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/muted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/nextTransitionDuration","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/normalisedVolume","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playSpeed","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playbackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingAd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playlist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playlistDiff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/readyToPlay","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/replayOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/vinylStartStop"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/init(rawValue:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/RawRepresentable-Implementations"]}],"seeAlsoSections":[{"generated":true,"anchor":"AutomixIQ","title":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH","doc:\/\/org.cocoapods.SocialRadio\/SY"]}],"variants":[{"paths":["\/documentation\/socialradio\/automixiqstatusvariable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqstatusvariable"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"AutomixIQStatusVariable","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusVariable"}],"externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable","symbolKind":"enum","role":"symbol","roleHeading":"Enumeration"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusVariable"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"sections":[],"abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/vinylStartStop":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinylStartStop"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableVinylStartStop"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/vinylstartstop","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/vinylStartStop","type":"topic","abstract":[],"title":"AutomixIQStatusVariable.vinylStartStop","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/requestedLoopTrackIdentifier":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/requestedLoopTrackIdentifier","title":"AutomixIQStatusVariable.requestedLoopTrackIdentifier","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableRequestedLoopTrackIdentifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestedLoopTrackIdentifier","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/requestedlooptrackidentifier","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatus","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","type":"topic","abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"title":"AutomixIQStatus","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/adTrackTotalTime":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adTrackTotalTime","title":"AutomixIQStatusVariable.adTrackTotalTime","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableAdTrackTotalTime"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"adTrackTotalTime"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/adtracktotaltime","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/requestedPauseTrackIdentifier":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/requestedPauseTrackIdentifier","title":"AutomixIQStatusVariable.requestedPauseTrackIdentifier","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableRequestedPauseTrackIdentifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestedPauseTrackIdentifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/requestedpausetrackidentifier","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playingTrackTotalTime":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackTotalTime"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackTotalTime"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playingtracktotaltime","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackTotalTime","type":"topic","title":"AutomixIQStatusVariable.playingTrackTotalTime","kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","title":"AutomixIQObjC","navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQObjC"}],"url":"\/documentation\/socialradio\/automixiqobjc","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/explicitLyricsFiltering":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/explicitLyricsFiltering","title":"AutomixIQStatusVariable.explicitLyricsFiltering","navigatorTitle":[{"text":"AutomixIQStatusVariableExplicitLyricsFiltering","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"explicitLyricsFiltering"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/explicitlyricsfiltering","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canSeek":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canSeek","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSeek","kind":"identifier"}],"title":"AutomixIQStatusVariable.canSeek","abstract":[],"navigatorTitle":[{"text":"AutomixIQStatusVariableCanSeek","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/canseek","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playingAd":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingAd","title":"AutomixIQStatusVariable.playingAd","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingAd"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingAd"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playingad","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/socialradio\/automixiqstatusvariable\/rawrepresentable-implementations","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/adTrackCurrentTime":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adTrackCurrentTime","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adTrackCurrentTime","kind":"identifier"}],"abstract":[],"title":"AutomixIQStatusVariable.adTrackCurrentTime","navigatorTitle":[{"text":"AutomixIQStatusVariableAdTrackCurrentTime","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/adtrackcurrenttime","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedArtistModel":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedArtistModel","kind":"identifier"}],"navigatorTitle":[{"text":"TunedArtistModel","kind":"identifier"}],"url":"\/documentation\/socialradio\/tunedartistmodel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","type":"topic","abstract":[{"type":"text","text":"TunedArtistModel models an artist."}],"kind":"symbol","title":"TunedArtistModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"title":"TunedRestDelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","url":"\/documentation\/socialradio\/tunedrestdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canOnOff":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canOnOff","title":"AutomixIQStatusVariable.canOnOff","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableCanOnOff"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canOnOff"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/canonoff","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/nextTransitionDuration":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/nextTransitionDuration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTransitionDuration"}],"title":"AutomixIQStatusVariable.nextTransitionDuration","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableNextTransitionDuration"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/nexttransitionduration","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playingTrackIdentifier":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackIdentifier","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackIdentifier"}],"abstract":[],"title":"AutomixIQStatusVariable.playingTrackIdentifier","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackIdentifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playingtrackidentifier","type":"topic"},"doc://org.cocoapods.SocialRadio/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SY"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playlist":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playlist","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlist"}],"abstract":[],"title":"AutomixIQStatusVariable.playlist","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylist"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playlist","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playlistDiff":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playlistDiff","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlistDiff"}],"abstract":[],"title":"AutomixIQStatusVariable.playlistDiff","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylistDiff"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playlistdiff","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canBack":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canBack","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canBack"}],"abstract":[],"title":"AutomixIQStatusVariable.canBack","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableCanBack"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/canback","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/mixing":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/mixing","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixing"}],"abstract":[],"title":"AutomixIQStatusVariable.mixing","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableMixing"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/mixing","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/muted":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/muted","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"muted"}],"abstract":[],"title":"AutomixIQStatusVariable.muted","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableMuted"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/muted","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playingTrackOriginalSessionId":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackOriginalSessionId","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackOriginalSessionId"}],"abstract":[],"title":"AutomixIQStatusVariable.playingTrackOriginalSessionId","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackOriginalSessionId"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playingtrackoriginalsessionid","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canSkipToPrevious":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canSkipToPrevious"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableCanSkipToPrevious"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/canskiptoprevious","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canSkipToPrevious","type":"topic","abstract":[],"title":"AutomixIQStatusVariable.canSkipToPrevious","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAuthenticationResponse"}],"title":"TunedAuthenticationResponse","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"url":"\/documentation\/socialradio\/tunedauthenticationresponse","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ-article":{"role":"article","url":"\/documentation\/socialradio\/automixiq-article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","type":"topic","abstract":[{"text":"Availablity of underlying technologies and APIs.","type":"text"}],"title":"AutomixIQ","kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/normalisedVolume":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/normalisedVolume","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"normalisedVolume","kind":"identifier"}],"title":"AutomixIQStatusVariable.normalisedVolume","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableNormalisedVolume"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/normalisedvolume","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedLogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"TunedLogLevel"}],"url":"\/documentation\/socialradio\/tunedloglevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","type":"topic","kind":"symbol","title":"TunedLogLevel","abstract":[{"text":"TunedLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"title":"AutomixIQStatusVariable","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","url":"\/documentation\/socialradio\/automixiqstatusvariable","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"AutomixIQ status variable type","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canSkipToNext":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canSkipToNext","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canSkipToNext"}],"abstract":[],"title":"AutomixIQStatusVariable.canSkipToNext","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableCanSkipToNext"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/canskiptonext","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedPluginMetadataModel":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedPluginMetadataModel"}],"navigatorTitle":[{"kind":"identifier","text":"TunedPluginMetadataModel"}],"url":"\/documentation\/socialradio\/tunedpluginmetadatamodel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","type":"topic","kind":"symbol","title":"TunedPluginMetadataModel","abstract":[{"text":"TunedPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"text":" ","type":"text"},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playingTrackIndex":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackIndex","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackIndex","kind":"identifier"}],"title":"AutomixIQStatusVariable.playingTrackIndex","abstract":[],"navigatorTitle":[{"text":"AutomixIQStatusVariablePlayingTrackIndex","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playingtrackindex","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/preferredTransitionDurationSeconds":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/preferredTransitionDurationSeconds","title":"AutomixIQStatusVariable.preferredTransitionDurationSeconds","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePreferredTransitionDurationSeconds"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/preferredtransitiondurationseconds","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canReorderTracks":{"navigatorTitle":[{"text":"AutomixIQStatusVariableCanReorderTracks","kind":"identifier"}],"title":"AutomixIQStatusVariable.canReorderTracks","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canReorderTracks","url":"\/documentation\/socialradio\/automixiqstatusvariable\/canreordertracks","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canReorderTracks","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}],"title":"TunedTrackModel","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","url":"\/documentation\/socialradio\/tunedtrackmodel","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"TunedTrackModel models a track. This metadata is required."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","type":"topic","kind":"symbol","title":"AutomixIQStatusObserverDelegate","abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/transitionStartTimeSeconds":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionStartTimeSeconds","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableTransitionStartTimeSeconds","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/transitionstarttimeseconds","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/transitionStartTimeSeconds","type":"topic","abstract":[],"title":"AutomixIQStatusVariable.transitionStartTimeSeconds","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/Equatable-Implementations","url":"\/documentation\/socialradio\/automixiqstatusvariable\/equatable-implementations","type":"topic","kind":"article","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playingTrackStreamingProgress":{"navigatorTitle":[{"text":"AutomixIQStatusVariablePlayingTrackStreamingProgress","kind":"identifier"}],"title":"AutomixIQStatusVariable.playingTrackStreamingProgress","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackStreamingProgress","url":"\/documentation\/socialradio\/automixiqstatusvariable\/playingtrackstreamingprogress","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackStreamingProgress","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/adIndex":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adIndex","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adIndex","kind":"identifier"}],"abstract":[],"title":"AutomixIQStatusVariable.adIndex","navigatorTitle":[{"text":"AutomixIQStatusVariableAdIndex","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/adindex","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canPlayPause":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canPlayPause","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlayPause","kind":"identifier"}],"abstract":[],"title":"AutomixIQStatusVariable.canPlayPause","navigatorTitle":[{"text":"AutomixIQStatusVariableCanPlayPause","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/canplaypause","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/mixId":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/mixId","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixId","kind":"identifier"}],"abstract":[],"title":"AutomixIQStatusVariable.mixId","navigatorTitle":[{"text":"AutomixIQStatusVariableMixId","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/mixid","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playing":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playing","title":"AutomixIQStatusVariable.playing","navigatorTitle":[{"text":"AutomixIQStatusVariablePlaying","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playing","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playing","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/replayOn":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableReplayOn"}],"title":"AutomixIQStatusVariable.replayOn","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/replayOn","url":"\/documentation\/socialradio\/automixiqstatusvariable\/replayon","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"replayOn"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/readyToPlay":{"navigatorTitle":[{"text":"AutomixIQStatusVariableReadyToPlay","kind":"identifier"}],"title":"AutomixIQStatusVariable.readyToPlay","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/readyToPlay","url":"\/documentation\/socialradio\/automixiqstatusvariable\/readytoplay","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"readyToPlay","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaylistOperation":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}],"url":"\/documentation\/socialradio\/automixiqplaylistoperation","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","type":"topic","kind":"symbol","title":"AutomixIQPlaylistOperation","abstract":[{"text":"AutomixIQPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","type":"topic","url":"\/documentation\/socialradio","kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQConfig":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","title":"AutomixIQConfig","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQConfig"}],"url":"\/documentation\/socialradio\/automixiqconfig","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","title":"AutomixIQMusicCacheDelegate","navigatorTitle":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"url":"\/documentation\/socialradio\/automixiqmusiccachedelegate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}]},"doc://org.cocoapods.SocialRadio/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","title":"AutomixIQ","navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}],"url":"\/documentation\/socialradio\/automixiq","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/failedTrackLoadIdentifiers":{"navigatorTitle":[{"text":"AutomixIQStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}],"title":"AutomixIQStatusVariable.failedTrackLoadIdentifiers","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/failedTrackLoadIdentifiers","url":"\/documentation\/socialradio\/automixiqstatusvariable\/failedtrackloadidentifiers","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playbackMode":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playbackMode","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackMode"}],"title":"AutomixIQStatusVariable.playbackMode","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaybackMode"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playbackmode","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playingTrackCurrentTime":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackCurrentTime","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackCurrentTime","kind":"identifier"}],"title":"AutomixIQStatusVariable.playingTrackCurrentTime","abstract":[],"navigatorTitle":[{"text":"AutomixIQStatusVariablePlayingTrackCurrentTime","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/playingtrackcurrenttime","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"title":"AutomixIQWaveformModel","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","url":"\/documentation\/socialradio\/automixiqwaveformmodel","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"AutomixIQWaveformModel models the waveform of a track."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/init(rawValue:)","url":"\/documentation\/socialradio\/automixiqstatusvariable\/init(rawvalue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"title":"TunedAutomixPlaybackMode","abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"url":"\/documentation\/socialradio\/tunedautomixplaybackmode","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/canMixNow":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canMixNow","title":"AutomixIQStatusVariable.canMixNow","navigatorTitle":[{"text":"AutomixIQStatusVariableCanMixNow","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"canMixNow","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/canmixnow","kind":"symbol","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/playSpeed":{"navigatorTitle":[{"text":"AutomixIQStatusVariablePlaySpeed","kind":"identifier"}],"title":"AutomixIQStatusVariable.playSpeed","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playSpeed","url":"\/documentation\/socialradio\/automixiqstatusvariable\/playspeed","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playSpeed","kind":"identifier"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixIQStatusVariable","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/adTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canBack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canMixNow","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canOnOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canPlayPause","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canReorderTracks","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canSeek","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canSkipToNext","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/canSkipToPrevious","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/explicitLyricsFiltering","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/mixId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/mixing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/muted","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/nextTransitionDuration","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/normalisedVolume","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playSpeed","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playbackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playing","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingAd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackCurrentTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackIndex","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playingTrackTotalTime","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playlist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/playlistDiff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/readyToPlay","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/replayOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/vinylStartStop"],"generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"AutomixIQ","anchor":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQConfig","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaylistOperation","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate"],"generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixIQStatusVariableVinylStartStop","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1vinylStartStop\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableVinylStartStop"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1vinylStartStop\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableRequestedLoopTrackIdentifier","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1requestedLoopTrackIdentifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableRequestedLoopTrackIdentifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1requestedLoopTrackIdentifier\/fragments"},{"op":"replace","value":"AutomixIQStatus","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title"},{"op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments"},{"op":"replace","value":[{"text":"AutomixIQStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle"},{"value":"AutomixIQStatusVariableAdTrackTotalTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1adTrackTotalTime\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableAdTrackTotalTime","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1adTrackTotalTime\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableRequestedPauseTrackIdentifier","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1requestedPauseTrackIdentifier\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableRequestedPauseTrackIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1requestedPauseTrackIdentifier\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlayingTrackTotalTime","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackTotalTime\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlayingTrackTotalTime","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackTotalTime\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableExplicitLyricsFiltering","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1explicitLyricsFiltering\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableExplicitLyricsFiltering","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1explicitLyricsFiltering\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableCanSeek","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canSeek\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanSeek"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canSeek\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlayingAd","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingAd\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingAd"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingAd\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableAdTrackCurrentTime","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1adTrackCurrentTime\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableAdTrackCurrentTime","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1adTrackCurrentTime\/fragments"},{"op":"replace","value":"TunedArtistModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/title"},{"op":"replace","value":[{"text":"TunedArtistModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/fragments"},{"op":"replace","value":[{"text":"TunedArtistModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/navigatorTitle"},{"op":"replace","value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariableCanOnOff","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canOnOff\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanOnOff"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canOnOff\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableNextTransitionDuration","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1nextTransitionDuration\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableNextTransitionDuration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1nextTransitionDuration\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlayingTrackIdentifier","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackIdentifier\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlayingTrackIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackIdentifier\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlaylist","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playlist\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlaylist","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playlist\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlaylistDiff","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playlistDiff\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaylistDiff"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playlistDiff\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableCanBack","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canBack\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanBack"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canBack\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableMixing","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1mixing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableMixing"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1mixing\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableMuted","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1muted\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableMuted"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1muted\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlayingTrackOriginalSessionId","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackOriginalSessionId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackOriginalSessionId"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackOriginalSessionId\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableCanSkipToPrevious","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canSkipToPrevious\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableCanSkipToPrevious","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canSkipToPrevious\/fragments"},{"op":"replace","value":"TunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/title"},{"op":"replace","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariableNormalisedVolume","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1normalisedVolume\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableNormalisedVolume"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1normalisedVolume\/fragments"},{"op":"replace","value":"TunedLogLevel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canSkipToNext\/title","value":"AutomixIQStatusVariableCanSkipToNext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canSkipToNext\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanSkipToNext"}]},{"op":"replace","value":"TunedPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/title"},{"op":"replace","value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/fragments"},{"op":"replace","value":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariablePlayingTrackIndex","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackIndex\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlayingTrackIndex"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackIndex\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1preferredTransitionDurationSeconds\/title","value":"AutomixIQStatusVariablePreferredTransitionDurationSeconds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1preferredTransitionDurationSeconds\/fragments","value":[{"text":"AutomixIQStatusVariablePreferredTransitionDurationSeconds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canReorderTracks\/title","value":"AutomixIQStatusVariableCanReorderTracks"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canReorderTracks\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanReorderTracks"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title","value":"TunedTrackModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments","value":[{"text":"TunedTrackModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle","value":[{"text":"TunedTrackModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title","value":"AutomixIQStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1transitionStartTimeSeconds\/title","value":"AutomixIQStatusVariableTransitionStartTimeSeconds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1transitionStartTimeSeconds\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableTransitionStartTimeSeconds"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackStreamingProgress\/title","value":"AutomixIQStatusVariablePlayingTrackStreamingProgress"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackStreamingProgress\/fragments","value":[{"text":"AutomixIQStatusVariablePlayingTrackStreamingProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1adIndex\/title","value":"AutomixIQStatusVariableAdIndex"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableAdIndex","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1adIndex\/fragments"},{"op":"replace","value":"AutomixIQStatusVariableCanPlayPause","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canPlayPause\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canPlayPause\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanPlayPause"}]},{"op":"replace","value":"AutomixIQStatusVariableMixId","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1mixId\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1mixId\/fragments","value":[{"text":"AutomixIQStatusVariableMixId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playing\/title","value":"AutomixIQStatusVariablePlaying"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playing\/fragments","value":[{"text":"AutomixIQStatusVariablePlaying","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1replayOn\/title","value":"AutomixIQStatusVariableReplayOn"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableReplayOn","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1replayOn\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1readyToPlay\/title","value":"AutomixIQStatusVariableReadyToPlay"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1readyToPlay\/fragments","value":[{"text":"AutomixIQStatusVariableReadyToPlay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/title","value":"AutomixIQPlaylistOperation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaylistOperation"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaylistOperation\/navigatorTitle","value":[{"text":"AutomixIQPlaylistOperation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"AutomixIQConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/title"},{"value":[{"kind":"identifier","text":"AutomixIQConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQConfig\/navigatorTitle","value":[{"text":"AutomixIQConfig","kind":"identifier"}]},{"op":"replace","value":"AutomixIQMusicCacheDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/navigatorTitle","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title","value":"AutomixIQ","op":"replace"},{"op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQ"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1failedTrackLoadIdentifiers\/title","value":"AutomixIQStatusVariableFailedTrackLoadIdentifiers"},{"op":"replace","value":[{"text":"AutomixIQStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1failedTrackLoadIdentifiers\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playbackMode\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playbackMode\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlayingTrackCurrentTime","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackCurrentTime\/title"},{"op":"replace","value":[{"text":"AutomixIQStatusVariablePlayingTrackCurrentTime","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playingTrackCurrentTime\/fragments"},{"op":"replace","value":"AutomixIQWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments"},{"op":"replace","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/title","value":"TunedAutomixPlaybackMode"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/navigatorTitle"},{"op":"replace","value":"AutomixIQStatusVariableCanMixNow","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canMixNow\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariableCanMixNow"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1canMixNow\/fragments"},{"op":"replace","value":"AutomixIQStatusVariablePlaySpeed","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playSpeed\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePlaySpeed"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1playSpeed\/fragments"}]}]}