{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Getting-available-broadcasts-article","interfaceLanguage":"swift"},"kind":"article","metadata":{"modules":[{"name":"SocialRadio"}],"role":"article","roleHeading":"Article","title":"Getting available broadcasts"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/getting-available-broadcasts-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/getting-available-broadcasts-article"]}],"abstract":[{"type":"text","text":"How to learn which broadcasts are currently live."}],"primaryContentSections":[{"kind":"content","content":[{"text":"Essentials","anchor":"Essentials","level":2,"type":"heading"},{"inlineContent":[{"text":"When you want to fetch a list of currently available live broadcasts as paged request, you use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/getLiveBroadcasts(limit:start:completion:)"},{"text":" as shown below:","type":"text"}],"type":"paragraph"},{"syntax":"swift","code":["public class MyApplication {","    \/\/ ...","    func getBroadcasts() -> Void {","        let limit: Int = 10             \/\/ Get a total of 10 broadcasts","        let start: Int = 0              \/\/ Get the first broadcasts","        SocialRadio.instance.getLiveBroadcasts(limit: limit, start: start) { error, liveBroadcasts in","            \/\/ Present the broadcasts on your UI","            let myLiveBroadcasts = myLiveBroadcasts","            myLiveBroadcasts.add(liveBroadcasts)","            if(liveBroadcasts.size < limit) {","                \/\/ There are more broadcasts available!","                getNextLiveBroadcastsPage()","            }","        }","    }","    \/\/ ...","}"],"type":"codeListing"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/getLiveBroadcasts(limit:start:completion:)":{"abstract":[{"type":"text","text":"Queries the live shows, paged."}],"url":"\/documentation\/socialradio\/socialradio\/getlivebroadcasts(limit:start:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getLiveBroadcasts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"start"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"liveMixtapes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioList","text":"SocialRadioList"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"title":"getLiveBroadcasts(limit:start:completion:)","navigatorTitle":[{"kind":"identifier","text":"getLiveBroadcastsWithLimit:start:completion:"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/getLiveBroadcasts(limit:start:completion:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1getLiveBroadcasts(limit:start:completion:)\/title","value":"getLiveBroadcastsWithLimit:start:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1getLiveBroadcasts(limit:start:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getLiveBroadcastsWithLimit:start:completion:","kind":"identifier"}]}]}]}