{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"vinylStartStop"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/vinylStartStop","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@AutomixIQ@E@AutomixIQStatusVariable@AutomixIQStatusVariableVinylStartStop","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariableVinylStartStop"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vinylStartStop","kind":"identifier"}],"title":"AutomixIQStatusVariable.vinylStartStop","modules":[{"name":"AutomixIQ"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/vinylstartstop"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/vinylstartstop"]}],"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/vinylStartStop":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/vinylStartStop","title":"AutomixIQStatusVariable.vinylStartStop","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vinylStartStop","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableVinylStartStop","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable\/vinylstartstop","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"url":"\/documentation\/automixiq","title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusvariable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable","type":"topic","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"AutomixIQStatusVariable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixIQStatusVariableVinylStartStop","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableVinylStartStop"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixIQStatusVariableVinylStartStop"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixIQStatusVariableVinylStartStop","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1vinylStartStop\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariableVinylStartStop"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1vinylStartStop\/fragments"},{"value":"AutomixIQStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}