{"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadCompleted(trackId:data:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackDownloadCompleted"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":")"}],"required":true,"role":"symbol","symbolKind":"method","modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}],"roleHeading":"Instance Method","title":"trackDownloadCompleted(trackId:data:)","externalID":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate(im)trackDownloadCompletedWithTrackId:data:"},"abstract":[{"text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadcompleted(trackid:data:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadcompleted(trackid:data:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trackDownloadCompleted","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The id of the track that the AutomixIQ SDK is streaming."}],"type":"paragraph"}],"name":"trackId"},{"content":[{"inlineContent":[{"type":"text","text":"The track data as an array of bytes."}],"type":"paragraph"}],"name":"data"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"title":"AutomixSDKStreamingDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","type":"topic","abstract":[{"type":"text","text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/trackDownloadCompleted(trackId:data:)":{"navigatorTitle":[{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackDownloadCompleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":")","kind":"text"}],"title":"trackDownloadCompleted(trackId:data:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadCompleted(trackId:data:)","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadcompleted(trackid:data:)","type":"topic","abstract":[{"type":"text","text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"trackDownloadCompletedWithTrackId:data:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"trackId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"data:"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"data"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"trackId","content":[{"inlineContent":[{"type":"text","text":"The id of the track that the AutomixIQ SDK is streaming."}],"type":"paragraph"}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"text":"The track data as an array of bytes.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"AutomixSDKStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/title","value":"trackDownloadCompletedWithTrackId:data:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}