{"sections":[],"metadata":{"modules":[{"name":"AutomixIQ"}],"title":"storeId","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"storeId"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"storeId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig(py)storeId"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig\/storeId","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkconfig\/storeid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkconfig\/storeid"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"storeId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKConfig/storeId":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"storeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"storeId","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"storeId"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig\/storeId","url":"\/documentation\/automixiq\/automixsdkconfig\/storeid","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKConfig":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKConfig"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","url":"\/documentation\/automixiq\/automixsdkconfig","abstract":[],"title":"AutomixSDKConfig","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKConfig","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","kind":"symbol","title":"AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"storeId","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"storeId"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"storeId"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig~1storeId\/title","value":"storeId"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig~1storeId\/fragments","value":[{"text":"storeId","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"AutomixSDKConfig","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/fragments","value":[{"kind":"identifier","text":"AutomixSDKConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKConfig","kind":"identifier"}]}]}]}