{"variants":[{"paths":["\/documentation\/socialradio\/automixsdkobjc\/initialise(with:streamingdelegate:statusdelegate:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC\/initialise(with:streamingDelegate:statusDelegate:completion:)"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKConfig","text":"AutomixSDKConfig"},{"text":", ","kind":"text"},{"text":"streamingDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","kind":"typeIdentifier","text":"CompletionWithError"},{"text":"?)","kind":"text"}],"modules":[{"name":"SocialRadio"}],"title":"initialise(with:streamingDelegate:statusDelegate:completion:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AutomixSDKObjC(cm)initialiseWithConfig:streamingDelegate:statusDelegate:completion:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKConfig","text":"AutomixSDKConfig","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"streamingDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier","text":"AutomixSDKStreamingDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/CompletionWithError"},{"kind":"text","text":"? = nil)"}]},{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","kind":"typeIdentifier","text":"AutomixSDKConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"streamingDelegate"},{"kind":"text","text":": any "},{"text":"AutomixSDKStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?) "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/CompletionWithError":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/CompletionWithError","title":"CompletionWithError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CompletionWithError"}],"navigatorTitle":[{"kind":"identifier","text":"CompletionWithError"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/socialradio\/completionwitherror","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate":{"title":"AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/automixsdkstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","type":"topic","abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKObjC/initialise(with:streamingDelegate:statusDelegate:completion:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC\/initialise(with:streamingDelegate:statusDelegate:completion:)","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamingDelegate"},{"text":": any ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/automixsdkobjc\/initialise(with:streamingdelegate:statusdelegate:completion:)","title":"initialise(with:streamingDelegate:statusDelegate:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusObserverDelegate":{"type":"topic","url":"\/documentation\/socialradio\/automixsdkstatusobserverdelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusObserverDelegate","title":"AutomixSDKStatusObserverDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKObjC":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC","url":"\/documentation\/socialradio\/automixsdkobjc","navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"role":"symbol","title":"AutomixSDKObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKObjC","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKConfig","kind":"identifier"}],"title":"AutomixSDKConfig","navigatorTitle":[{"text":"AutomixSDKConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKConfig","url":"\/documentation\/socialradio\/automixsdkconfig","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AutomixSDKStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/title","op":"replace","value":"AutomixSDKStatusObserverDelegate"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/title","value":"AutomixSDKConfig","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKConfig\/navigatorTitle"}]}]}