{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC\/loadTracks(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkobjc\/loadtracks(withidentifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadTracks","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifiers"},{"text":" ","kind":"text"},{"text":"identifiers","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":" "},{"kind":"internalParam","text":"trackMetadataArray"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","text":"AutomixSDKTrackModel"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"playTrackIndex"},{"text":" ","kind":"text"},{"text":"index","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contextType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","kind":"typeIdentifier","text":"CompletionWithError"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadTracks","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifiers","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"identifiers","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":" "},{"text":"trackMetadataArray","kind":"internalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoplay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"contextType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC"]]},"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)AutomixSDKObjC(im)loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","role":"symbol","modules":[{"name":"SocialRadio"}],"title":"loadTracks(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadTracks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"playTrackIndex"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"text":"?)","kind":"text"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKObjC":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC","url":"\/documentation\/socialradio\/automixsdkobjc","navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"role":"symbol","title":"AutomixSDKObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKObjC","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel":{"url":"\/documentation\/socialradio\/automixsdktrackmodel","abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}],"title":"AutomixSDKTrackModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","type":"topic","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/CompletionWithError":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/CompletionWithError","title":"CompletionWithError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CompletionWithError"}],"navigatorTitle":[{"kind":"identifier","text":"CompletionWithError"}],"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/socialradio\/completionwitherror","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKObjC/loadTracks(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracks","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifiers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"playTrackIndex","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"seconds"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoplay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"contextType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"contextId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"type":"topic","title":"loadTracks(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKObjC\/loadTracks(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","url":"\/documentation\/socialradio\/automixsdkobjc\/loadtracks(withidentifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel"},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/navigatorTitle","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]}]}]}