{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable\/explicitLyricsFiltering","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"AutomixSDKStatusVariableExplicitLyricsFiltering","kind":"identifier"}],"title":"AutomixSDKStatusVariable.explicitLyricsFiltering","modules":[{"name":"SocialRadio"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"explicitLyricsFiltering"}],"externalID":"c:@M@SocialRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableExplicitLyricsFiltering","roleHeading":"Case","role":"symbol"},"variants":[{"paths":["\/documentation\/socialradio\/automixsdkstatusvariable\/explicitlyricsfiltering"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkstatusvariable\/explicitlyricsfiltering"]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"explicitLyricsFiltering","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable/explicitLyricsFiltering":{"abstract":[],"url":"\/documentation\/socialradio\/automixsdkstatusvariable\/explicitlyricsfiltering","title":"AutomixSDKStatusVariable.explicitLyricsFiltering","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable\/explicitLyricsFiltering","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"explicitLyricsFiltering"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AutomixSDKStatusVariableExplicitLyricsFiltering","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStatusVariable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStatusVariable","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"title":"AutomixSDKStatusVariable","url":"\/documentation\/socialradio\/automixsdkstatusvariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKStatusVariableExplicitLyricsFiltering"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableExplicitLyricsFiltering"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariableExplicitLyricsFiltering"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable~1explicitLyricsFiltering\/title","value":"AutomixSDKStatusVariableExplicitLyricsFiltering","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable~1explicitLyricsFiltering\/fragments","value":[{"text":"AutomixSDKStatusVariableExplicitLyricsFiltering","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}