{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/postCreateMixtape(mixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:)"},"abstract":[{"type":"text","text":"Creates a  mixtape."}],"variants":[{"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/postcreatemixtape(mixdictionary:isprivate:recipejsonstring:tracksjsonstring:mixhash:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/postcreatemixtape(mixdictionary:isprivate:recipejsonstring:tracksjsonstring:mixhash:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postCreateMixtape","kind":"identifier"},{"text":"(","kind":"text"},{"text":"mixDictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"isPrivate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recipeJSONString","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tracksJSONString","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"mixHash","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mix","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape","text":"SocialRadioMixtape","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Metadata and configuration for the mix."}],"type":"paragraph"}],"name":"mixDictionary"},{"content":[{"inlineContent":[{"text":"Flag indicating whether the mix is private.","type":"text"}],"type":"paragraph"}],"name":"isPrivate"},{"content":[{"inlineContent":[{"type":"text","text":"Optional JSON string for recipe data."}],"type":"paragraph"}],"name":"recipeJSONString"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional JSON string for track data.","type":"text"}]}],"name":"tracksJSONString"},{"content":[{"inlineContent":[{"type":"text","text":"The hash of the mix file"}],"type":"paragraph"}],"name":"mixHash"},{"content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Parameter mix: The created ","type":"text"},{"type":"codeVoice","code":"SocialRadioMixtape"},{"text":" object.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}],"name":"completion"}],"kind":"parameters"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postCreateMixtape","kind":"identifier"},{"text":"(","kind":"text"},{"text":"mixDictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"isPrivate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"recipeJSONString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"tracksJSONString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"mixHash","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mix"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioMixtape","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(pl)SocialLayerLiveMixtapeDelegate(im)postCreateMixtapeWithMixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:","navigatorTitle":[{"kind":"identifier","text":"postCreateMixtapeWithMixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:"}],"roleHeading":"Instance Method","title":"postCreateMixtape(mixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:)","required":true},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate":{"navigatorTitle":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"abstract":[{"text":"(Required) Handles communication between SocialRadio SDK and a backend regarding live mixtapes.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate","title":"SocialLayerLiveMixtapeDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape":{"title":"SocialRadioMixtape","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","url":"\/documentation\/socialradio\/socialradiomixtape","abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate/postCreateMixtape(mixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:)":{"title":"postCreateMixtape(mixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:)","required":true,"navigatorTitle":[{"text":"postCreateMixtapeWithMixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/postcreatemixtape(mixdictionary:isprivate:recipejsonstring:tracksjsonstring:mixhash:completion:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Creates a  mixtape."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/postCreateMixtape(mixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postCreateMixtape"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mixDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isPrivate"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recipeJSONString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tracksJSONString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"mixHash","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mix","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioMixtape","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"postCreateMixtapeWithMixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"postCreateMixtapeWithMixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"postCreateMixtapeWithMixDictionary:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,id>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mixDictionary"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPrivate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isPrivate"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipeJSONString:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"recipeJSONString"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracksJSONString:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tracksJSONString"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixHash:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mixHash"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","kind":"typeIdentifier","text":"SocialRadioMixtape"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Metadata and configuration for the mix.","type":"text"}],"type":"paragraph"}],"name":"mixDictionary"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Flag indicating whether the mix is private.","type":"text"}]}],"name":"isPrivate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional JSON string for recipe data.","type":"text"}]}],"name":"recipeJSONString"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional JSON string for track data.","type":"text"}]}],"name":"tracksJSONString"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The hash of the mix file","type":"text"}]}],"name":"mixHash"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter mix: The created ","type":"text"},{"code":"SocialRadioMixtape","type":"codeVoice"},{"text":" object.","type":"text"}]}]}]}],"name":"completion"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/title","value":"SocialLayerLiveMixtapeDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/title","value":"SocialRadioMixtape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtape"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/navigatorTitle","value":[{"text":"SocialRadioMixtape","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1postCreateMixtape(mixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:)\/title","value":"postCreateMixtapeWithMixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1postCreateMixtape(mixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"postCreateMixtapeWithMixDictionary:isPrivate:recipeJSONString:tracksJSONString:mixHash:completion:","kind":"identifier"}]}]}]}