{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionWithErrorAndPlaybackState"},{"kind":"text","text":" = ((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?, "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus","kind":"typeIdentifier","text":"AutomixIQStatus","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/automixiq\/completionwitherrorandplaybackstate"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithErrorAndPlaybackState","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"metadata":{"externalID":"c:AutomixIQ.h@T@CompletionWithErrorAndPlaybackState","navigatorTitle":[{"text":"CompletionWithErrorAndPlaybackState","kind":"identifier"}],"symbolKind":"typealias","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionWithErrorAndPlaybackState","kind":"identifier"}],"roleHeading":"Type Alias","title":"CompletionWithErrorAndPlaybackState","role":"symbol"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/CompletionWithErrorAndPlaybackState":{"url":"\/documentation\/automixiq\/completionwitherrorandplaybackstate","abstract":[],"navigatorTitle":[{"text":"CompletionWithErrorAndPlaybackState","kind":"identifier"}],"title":"CompletionWithErrorAndPlaybackState","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionWithErrorAndPlaybackState","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithErrorAndPlaybackState","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus":{"abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}],"url":"\/documentation\/automixiq\/automixiqstatus","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus","role":"symbol","title":"AutomixIQStatus","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatus"}]}},"variantOverrides":[{"patch":[{"value":"AutomixIQStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/title"},{"value":[{"text":"AutomixIQStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}