{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backNoTrackAvailable","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"variants":[{"paths":["\/documentation\/socialradio\/errorcode\/backnotrackavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/errorcode\/backnotrackavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/backNoTrackAvailable","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SocialRadio"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backNoTrackAvailable","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"title":"ErrorCode.backNoTrackAvailable","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeBackNoTrackAvailable"},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/backNoTrackAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backNoTrackAvailable","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"role":"symbol","abstract":[],"title":"ErrorCode.backNoTrackAvailable","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/backNoTrackAvailable","url":"\/documentation\/socialradio\/errorcode\/backnotrackavailable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"kind":"symbol","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"role":"symbol","title":"ErrorCode","url":"\/documentation\/socialradio\/errorcode","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","type":"topic","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ErrorCodeBackNoTrackAvailable","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeBackNoTrackAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1backNoTrackAvailable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1backNoTrackAvailable\/fragments","value":[{"kind":"identifier","text":"ErrorCodeBackNoTrackAvailable"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"}]}]}