{"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setPreferredTransitionDurationSeconds(_:completion:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setFilterExplicit(filterExplicit:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setVinylStartStopEnabled(_:completion:)"],"anchor":"Settings","generated":true,"title":"Settings"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setPreferredTransitionDurationSeconds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"duration"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The desired transition duration in seconds"}]}],"name":"duration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}]}]}]}],"name":"completion"}]},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Controlling-playback-article"]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPreferredTransitionDurationSeconds","kind":"identifier"},{"kind":"text","text":"(Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"text":"setPreferredTransitionDurationSeconds:completion:","kind":"identifier"}],"symbolKind":"method","title":"setPreferredTransitionDurationSeconds(_:completion:)","externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQ(im)setPreferredTransitionDurationSeconds:completion:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Sets AutomixIQ’s preferred transition duration - transitions will not be exactly this duration but AutomixIQ will favour transitions with duration close to this one.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Setting it to 0 disables this hint and allows the engine to select the transition duration based on trained genre-based transition data."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiq\/setpreferredtransitiondurationseconds(_:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiq\/setpreferredtransitiondurationseconds(_:completion:)"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setPreferredTransitionDurationSeconds(_:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredTransitionDurationSeconds"},{"kind":"text","text":"(Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"setPreferredTransitionDurationSeconds:completion:"}],"url":"\/documentation\/automixiq\/automixiq\/setpreferredtransitiondurationseconds(_:completion:)","title":"setPreferredTransitionDurationSeconds(_:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setPreferredTransitionDurationSeconds(_:completion:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Sets AutomixIQ’s preferred transition duration - transitions will not be exactly this duration but AutomixIQ will favour transitions with duration close to this one."},{"type":"text","text":" "},{"type":"text","text":"Setting it to 0 disables this hint and allows the engine to select the transition duration based on trained genre-based transition data."}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ","type":"topic","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Controlling-playback-article":{"url":"\/documentation\/automixiq\/controlling-playback-article","title":"Controlling Playback","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Controlling-playback-article","kind":"article","role":"article","abstract":[{"text":"How to play, skip, pause and seek through content","type":"text"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setFilterExplicit(filterExplicit:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"setFilterExplicitWithFilterExplicit:completion:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFilterExplicit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filterExplicit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setFilterExplicit(filterExplicit:completion:)","kind":"symbol","title":"setFilterExplicit(filterExplicit:completion:)","abstract":[{"type":"text","text":"Sets the filter explicit lyrics flag."},{"type":"text","text":" "},{"type":"text","text":"When set to on, AutomixIQ will skip over the tracks that have the explicit content flag set in their metadata by mixing the currently playing track with the first available non-explicit track in the queue."}],"url":"\/documentation\/automixiq\/automixiq\/setfilterexplicit(filterexplicit:completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQ","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq","title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ","kind":"symbol","role":"symbol","abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setVinylStartStopEnabled(_:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVinylStartStopEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"setVinylStartStopEnabled:completion:"}],"url":"\/documentation\/automixiq\/automixiq\/setvinylstartstopenabled(_:completion:)","title":"setVinylStartStopEnabled(_:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setVinylStartStopEnabled(_:completion:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Enables \/ Disables vinyl pause sound effect."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setPreferredTransitionDurationSeconds:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPreferredTransitionDurationSeconds:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setFilterExplicit(filterExplicit:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setVinylStartStopEnabled(_:completion:)"],"generated":true,"anchor":"Settings","title":"Settings"}],"op":"replace"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setPreferredTransitionDurationSeconds:","kind":"identifier"},{"kind":"text","text":"("},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"text":"duration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The desired transition duration in seconds","type":"text"}],"type":"paragraph"}],"name":"duration"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}]}]}],"type":"unorderedList"}],"name":"completion"}],"kind":"parameters"}},{"op":"replace","value":"setPreferredTransitionDurationSeconds:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setPreferredTransitionDurationSeconds(_:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setPreferredTransitionDurationSeconds(_:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setPreferredTransitionDurationSeconds:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setFilterExplicit(filterExplicit:completion:)\/title","value":"setFilterExplicitWithFilterExplicit:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setFilterExplicit(filterExplicit:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFilterExplicitWithFilterExplicit:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/title","op":"replace","value":"AutomixIQ"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setVinylStartStopEnabled(_:completion:)\/title","op":"replace","value":"setVinylStartStopEnabled:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setVinylStartStopEnabled(_:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVinylStartStopEnabled:completion:"}]}]}]}