{"metadata":{"symbolKind":"method","role":"symbol","title":"setMusicCacheDelegate(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMusicCacheDelegate","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQMusicCacheDelegate","text":"AutomixIQMusicCacheDelegate","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"externalID":"c:objc(cs)AutomixIQObjC(im)setMusicCacheDelegate:","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMusicCacheDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"musicCacheDelegate","kind":"internalParam"},{"text":": (any ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQMusicCacheDelegate"},{"text":")?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/setMusicCacheDelegate(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqobjc\/setmusiccachedelegate(_:)"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate":{"title":"AutomixIQMusicCacheDelegate","kind":"symbol","abstract":[{"text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","url":"\/documentation\/socialradio\/automixiqmusiccachedelegate","navigatorTitle":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC/setMusicCacheDelegate(_:)":{"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/automixiqobjc\/setmusiccachedelegate(_:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC\/setMusicCacheDelegate(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMusicCacheDelegate","kind":"identifier"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQMusicCacheDelegate","text":"AutomixIQMusicCacheDelegate","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"setMusicCacheDelegate(_:)","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQObjC":{"role":"symbol","title":"AutomixIQObjC","navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqobjc","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQObjC","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQObjC","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"AutomixIQMusicCacheDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}