{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Switching-between-AutomixIQ-player-and-any-other-player-article"},"sections":[],"abstract":[{"type":"text","text":"How to toggle the AutomixIQ player on and off"}],"kind":"article","metadata":{"modules":[{"name":"AutomixIQ"}],"roleHeading":"Article","title":"Switching between AutomixIQ player and any other player","role":"article"},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Essentials","anchor":"Essentials"},{"type":"paragraph","inlineContent":[{"text":"AutomixIQ’s player can be started and stopped. When it is started, it will take over any other player and start playing the tracks it is fed, other player should be paused at this time. When it is stopped, AutomixIQ’s player will stop rendering audio and any other player can be resumed.","type":"text"}]},{"type":"heading","level":3,"text":"Turn AutomixIQ on","anchor":"Turn-AutomixIQ-on"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When AutomixIQ’s player is started, it takes over the application’s Audio Session and sets it up at a sample rate of 44100, category “.playback”, IOBufferDuration of ~0.006 and 2 output channels (stereo)."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To start the player, use either"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/automixOn(completion:)"},{"text":" ","type":"text"},{"text":"to start it with no content (and wait for content to be provided via the playback control methods, see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Controlling-playback-article"},{"text":"):","type":"text"}]}]}]},{"type":"codeListing","code":["    \/\/ ...","    AutomixIQ.instance.automixOn() { error in","        if error != nil {","            \/\/ Something went wrong, playback did not start","            NSLog(error.localizedDescription)","            return","        }","        self.started = true","        \/\/ We are now waiting for content.","        \/\/ ...","    }","","    \/\/ ..."],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":", or"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"to start it with the content provided in the method signature,","type":"text"}]}]}]},{"type":"codeListing","code":["    \/\/ ...","","    let electronicMusicPlaylist = [\"116484855\",\"66906273\",\"120584575\",\"116887896\"]","    let cachedMetadata = [trackMetadata1, trackMetadata2, trackMetadata3, trackMetadata4]","    AutomixIQ.instance.automixOn(identifiers: electronicMusicPlaylist,","                                  metadata: cachedMetadata,","                                  playTrackIndex:0, seconds:0, autoplay: true,","                                  contextType: \"playlist\", contextId: \"some-playlist-id\") { error in","        if error != nil {","            \/\/ Something went wrong, playback did not start","            NSLog(error.localizedDescription)","            return","        }","        self.started = true","        \/\/ We are now playling the playlist as a mix.","        \/\/ ...","    }","","    \/\/ ..."],"syntax":"swift"},{"type":"heading","level":3,"text":"Turn AutomixIQ off","anchor":"Turn-AutomixIQ-off"},{"type":"paragraph","inlineContent":[{"text":"When stopped, AutomixIQ restores the AVAudioSession with the settings it found when starting.","type":"text"},{"text":" ","type":"text"},{"text":"To stop the player, use","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/automixOff(completion:)","isActive":true}],"type":"paragraph"}]}]},{"type":"codeListing","code":["    \/\/ ...","","    AutomixIQObjC.instance()?.automixOff { error, status in","        if error != nil {","            \/\/ Something went wrong, playback did not stop","            NSLog(error.localizedDescription)","            return","        }","        self.started = false","        \/\/ We are no longer playing.","        \/\/ ...","    }","","    \/\/ ..."],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This function reports the status of AutomixIQ at the time it was stopped, in case you want to have another player pick up playback where AutomixIQ left it. See "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"},{"type":"text","text":"."}]},{"type":"heading","level":3,"text":"Checking if AutomixIQ is on \/ off","anchor":"Checking-if-AutomixIQ-is-on--off"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To check whether AutomixIQ is currently on, use"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/on()","isActive":true}],"type":"paragraph"}]}]}]}],"variants":[{"paths":["\/documentation\/automixiq\/switching-between-automixiq-player-and-any-other-player-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/switching-between-automixiq-player-and-any-other-player-article"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/automixOff(completion:)":{"abstract":[{"type":"text","text":"Turns the AutomixIQ player off."},{"type":"text","text":" "},{"type":"text","text":"In order to turn it back on you will have to call -(void)automixOnWithIdentifiers:playTrackIndex:seconds:autoplay:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/automixOff(completion:)","url":"\/documentation\/automixiq\/automixiq\/automixoff(completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automixOff","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"automixOffWithCompletion:","kind":"identifier"}],"title":"automixOff(completion:)","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"title":"automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","url":"\/documentation\/automixiq\/automixiq\/automixon(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixOn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","text":"TunedTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"playTrackIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contextType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"role":"symbol","abstract":[{"type":"text","text":"Turns the AutomixIQ player on and starts playback if required as soon as possible at a given track and playback time within the provided playlist."},{"type":"text","text":" "},{"type":"text","text":"If the playlist is empty this operation will fail and AutomixIQ will be turned off."},{"type":"text","text":" "},{"type":"text","text":"Returns an error if the engine has not been initialised or has already been turned on."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Controlling-playback-article":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Controlling-playback-article","type":"topic","title":"Controlling Playback","kind":"article","abstract":[{"type":"text","text":"How to play, skip, pause and seek through content"}],"role":"article","url":"\/documentation\/automixiq\/controlling-playback-article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/on()":{"url":"\/documentation\/automixiq\/automixiq\/on()","title":"on()","navigatorTitle":[{"kind":"identifier","text":"on"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/on()","type":"topic","role":"symbol","abstract":[{"text":"Returns the on\/off status of AutomixIQ.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/automixOn(completion:)":{"abstract":[{"type":"text","text":"Turns AutomixIQ on."},{"type":"text","text":" "},{"type":"text","text":"Returns an error if the engine has not been initialised or has already been turned on."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/automixOn(completion:)","url":"\/documentation\/automixiq\/automixiq\/automixon(completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixOn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"automixOnCompletion:"}],"title":"automixOn(completion:)","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","title":"AutomixIQStatusObserverDelegate","role":"symbol","type":"topic","abstract":[{"text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"navigatorTitle":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1automixOff(completion:)\/title","op":"replace","value":"automixOffWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1automixOff(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"automixOffWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title","op":"replace","value":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1on()\/title","op":"replace","value":"on"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1on()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"on","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1automixOn(completion:)\/title","op":"replace","value":"automixOnCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1automixOn(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"automixOnCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title","op":"replace","value":"AutomixIQStatusObserverDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments","op":"replace","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}