{"abstract":[{"type":"text","text":"The Id of the authenticated user in Tuned Global’s backend"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tuned_user_id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedAuthenticationResponse\/tuned_user_id"},"sections":[],"variants":[{"paths":["\/documentation\/automixiq\/automixiqtunedauthenticationresponse\/tuned_user_id"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqtunedauthenticationresponse\/tuned_user_id"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQTunedAuthenticationResponse(py)tuned_user_id","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"tuned_user_id"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tuned_user_id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"tuned_user_id","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedAuthenticationResponse"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedAuthenticationResponse/tuned_user_id":{"navigatorTitle":[{"kind":"identifier","text":"tuned_user_id"}],"abstract":[{"type":"text","text":"The Id of the authenticated user in Tuned Global’s backend"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"tuned_user_id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedAuthenticationResponse\/tuned_user_id","url":"\/documentation\/automixiq\/automixiqtunedauthenticationresponse\/tuned_user_id","title":"tuned_user_id","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedAuthenticationResponse":{"title":"AutomixIQTunedAuthenticationResponse","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixIQTunedAuthenticationResponse","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqtunedauthenticationresponse","abstract":[{"type":"text","text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedAuthenticationResponse","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixIQTunedAuthenticationResponse","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"tuned_user_id","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"tuned_user_id","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"tuned_user_id"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedAuthenticationResponse~1tuned_user_id\/title","op":"replace","value":"tuned_user_id"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedAuthenticationResponse~1tuned_user_id\/fragments","op":"replace","value":[{"text":"tuned_user_id","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedAuthenticationResponse\/title","op":"replace","value":"AutomixIQTunedAuthenticationResponse"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedAuthenticationResponse\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedAuthenticationResponse"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQTunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedAuthenticationResponse\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}