{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialRadioStatusVariableName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"variable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioStatusVariable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","preciseIdentifier":"c:@M@SocialRadio@E@SocialRadioStatusVariable"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"socialRadioStatusVariableName:"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioStatus(cm)socialRadioStatusVariableName:","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"socialRadioStatusVariableName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@SocialRadioStatusVariable","text":"SocialRadioStatusVariable"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"socialRadioStatusVariableName(_:)","roleHeading":"Type Method","role":"symbol","modules":[{"name":"SocialRadio"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiostatus\/socialradiostatusvariablename(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiostatus\/socialradiostatusvariablename(_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus\/socialRadioStatusVariableName(_:)"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatus/socialRadioStatusVariableName(_:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus\/socialRadioStatusVariableName(_:)","title":"socialRadioStatusVariableName(_:)","url":"\/documentation\/socialradio\/socialradiostatus\/socialradiostatusvariablename(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"socialRadioStatusVariableName","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SocialRadioStatusVariable","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@SocialRadioStatusVariable"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"socialRadioStatusVariableName:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","type":"topic","abstract":[{"type":"text","text":"SocialRadio status variable type"}],"kind":"symbol","role":"symbol","url":"\/documentation\/socialradio\/socialradiostatusvariable","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"title":"SocialRadioStatusVariable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatus":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","title":"SocialRadioStatus","kind":"symbol","url":"\/documentation\/socialradio\/socialradiostatus","role":"symbol","type":"topic","abstract":[{"type":"text","text":"SocialRadioStatus models the State of the AutomixIQ during playback."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"socialRadioStatusVariableName:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"socialRadioStatusVariableName:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"socialRadioStatusVariableName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@SocialRadioStatusVariable","text":"SocialRadioStatusVariable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"variable","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"socialRadioStatusVariableName:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus~1socialRadioStatusVariableName(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"socialRadioStatusVariableName:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus~1socialRadioStatusVariableName(_:)\/fragments"},{"op":"replace","value":"SocialRadioStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments"},{"op":"replace","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle"},{"op":"replace","value":"SocialRadioStatus","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/title"},{"op":"replace","value":[{"text":"SocialRadioStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}