{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqloglevel\/!=(_:_:)"]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@AutomixIQ@E@AutomixIQLogLevel","modules":[{"name":"AutomixIQ","relatedModules":["Swift"]}],"extendedModule":"Swift","title":"!=(_:_:)","symbolKind":"op","roleHeading":"Operator"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/!=(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/Equatable-Implementations"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel":{"url":"\/documentation\/automixiq\/automixiqloglevel","navigatorTitle":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel","title":"AutomixIQLogLevel","abstract":[{"text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQLogLevel"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/Equatable-Implementations":{"url":"\/documentation\/automixiq\/automixiqloglevel\/equatable-implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/Equatable-Implementations","title":"Equatable Implementations"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/!=(_:_:)":{"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"title":"!=(_:_:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/!=(_:_:)","role":"symbol","url":"\/documentation\/automixiq\/automixiqloglevel\/!=(_:_:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/title","op":"replace","value":"AutomixIQLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/fragments","value":[{"kind":"identifier","text":"AutomixIQLogLevel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/navigatorTitle","value":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}