{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelWarning"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"logLevelWarning","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixiqloglevel\/loglevelwarning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqloglevel\/loglevelwarning"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelWarning"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQLogLevelLogLevelWarning"}],"externalID":"c:@M@AutomixIQ@E@AutomixIQLogLevel@AutomixIQLogLevelLogLevelWarning","modules":[{"name":"AutomixIQ"}],"title":"AutomixIQLogLevel.logLevelWarning","role":"symbol","symbolKind":"case"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel/logLevelWarning":{"url":"\/documentation\/automixiq\/automixiqloglevel\/loglevelwarning","navigatorTitle":[{"text":"AutomixIQLogLevelLogLevelWarning","kind":"identifier"}],"title":"AutomixIQLogLevel.logLevelWarning","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"logLevelWarning","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel\/logLevelWarning"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel":{"url":"\/documentation\/automixiq\/automixiqloglevel","navigatorTitle":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel","title":"AutomixIQLogLevel","abstract":[{"text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQLogLevel"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AutomixIQLogLevelLogLevelWarning"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AutomixIQLogLevelLogLevelWarning","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixIQLogLevelLogLevelWarning","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelWarning\/title","op":"replace","value":"AutomixIQLogLevelLogLevelWarning"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel~1logLevelWarning\/fragments","value":[{"kind":"identifier","text":"AutomixIQLogLevelLogLevelWarning"}]},{"op":"replace","value":"AutomixIQLogLevel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/title"},{"value":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/navigatorTitle"}]}]}