{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/endRadioSession(completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradio\/endradiosession(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradio\/endradiosession(completion:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Ends a Radio session. Be mindful if there is an ongoing Live radio show, this will terminate it without asking.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endRadioSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}],"name":"completion"}]}],"metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","title":"endRadioSession(completion:)","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"kind":"identifier","text":"endRadioSessionWithCompletion:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endRadioSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadio(im)endRadioSessionWithCompletion:"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/endRadioSession(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"endRadioSessionWithCompletion:"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/endRadioSession(completion:)","abstract":[{"text":"Ends a Radio session. Be mindful if there is an ongoing Live radio show, this will terminate it without asking.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradio\/endradiosession(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endRadioSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"title":"endRadioSession(completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradio","title":"SocialRadio","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadio"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio","abstract":[{"type":"text","text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadio"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"endRadioSessionWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"endRadioSessionWithCompletion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"endRadioSessionWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}],"name":"completion"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1endRadioSession(completion:)\/title","value":"endRadioSessionWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1endRadioSession(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"endRadioSessionWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/title","value":"SocialRadio"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/fragments","value":[{"kind":"identifier","text":"SocialRadio"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadio"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}