{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errorcode\/cannotloadexplicitlyricstrack"]},{"paths":["\/documentation\/socialradio\/errorcode\/cannotloadexplicitlyricstrack"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotLoadExplicitLyricsTrack"},"metadata":{"externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeCannotLoadExplicitLyricsTrack","role":"symbol","title":"ErrorCode.cannotLoadExplicitLyricsTrack","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotLoadExplicitLyricsTrack"}],"modules":[{"name":"SocialRadio"}],"roleHeading":"Case","navigatorTitle":[{"text":"ErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotLoadExplicitLyricsTrack"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotLoadExplicitLyricsTrack":{"kind":"symbol","url":"\/documentation\/socialradio\/errorcode\/cannotloadexplicitlyricstrack","navigatorTitle":[{"text":"ErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotLoadExplicitLyricsTrack","title":"ErrorCode.cannotLoadExplicitLyricsTrack","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotLoadExplicitLyricsTrack"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"abstract":[],"title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","role":"symbol","url":"\/documentation\/socialradio\/errorcode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"title":"SocialRadio","kind":"symbol","url":"\/documentation\/socialradio"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"ErrorCodeCannotLoadExplicitLyricsTrack","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotLoadExplicitLyricsTrack\/title","op":"replace","value":"ErrorCodeCannotLoadExplicitLyricsTrack"},{"op":"replace","value":[{"text":"ErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotLoadExplicitLyricsTrack\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}