{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"text":"AutomixSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig"},{"kind":"text","text":", "},{"text":"tunedDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"modules":[{"name":"AutomixIQ"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(cm)initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:","symbolKind":"method","title":"initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","role":"symbol"},"abstract":[{"type":"text","text":"Initialiser for AutomixIQ to work against a Tuned Global backend"},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig","text":"AutomixSDKConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","kind":"typeIdentifier","text":"TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate"},{"text":"? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The AutomixIQ Configuration","type":"text"}]}],"name":"config"},{"name":"tunedDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of feeding and renewing Tuned Global OAuth2 access tokens. See TunedRestDelegate.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixSDKStatusObserverDelegate.","type":"text"}]}],"name":"statusDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of saving and feeding in cached music to and from AutomixIQ"}]}],"name":"musicCacheDelegate"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdk\/initialise(config:tuneddelegate:statusdelegate:musiccachedelegate:completion:)"]},{"paths":["\/documentation\/automixiq\/automixsdk\/initialise(config:tuneddelegate:statusdelegate:musiccachedelegate:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"anchor":"Initialization","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:streamingDelegate:statusDelegate:completion:)"],"title":"Initialization"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKConfig":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKConfig"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","url":"\/documentation\/automixiq\/automixsdkconfig","abstract":[],"title":"AutomixSDKConfig","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKConfig","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","kind":"symbol","abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"role":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"title":"AutomixSDKStatusObserverDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedMusicCacheDelegate":{"kind":"symbol","navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"url":"\/documentation\/automixiq\/tunedmusiccachedelegate","title":"TunedMusicCacheDelegate","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)":{"abstract":[{"text":"Initialiser for AutomixIQ to work against a Tuned Global backend","type":"text"},{"text":" ","type":"text"},{"text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/initialise(config:tuneddelegate:statusdelegate:musiccachedelegate:completion:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig","kind":"typeIdentifier","text":"AutomixSDKConfig"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier","text":"TunedMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","navigatorTitle":[{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"type":"topic","title":"initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/initialise(config:streamingDelegate:statusDelegate:completion:)":{"url":"\/documentation\/automixiq\/automixsdk\/initialise(config:streamingdelegate:statusdelegate:completion:)","title":"initialise(config:streamingDelegate:statusDelegate:completion:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig","text":"AutomixSDKConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"streamingDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initialiseWithConfig:streamingDelegate:statusDelegate:completion:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:streamingDelegate:statusDelegate:completion:)","abstract":[{"text":"Initialiser for AutomixIQ to work against any custom set of APIs.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method takes in delegates to update the UI and feeds all data and metadata the AutomixIQ needs."}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdk","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"role":"symbol","title":"AutomixSDK"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"kind":"symbol","title":"TunedRestDelegate","url":"\/documentation\/automixiq\/tunedrestdelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"TunedRestDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"anchor":"Initialization","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:streamingDelegate:statusDelegate:completion:)"],"title":"Initialization"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"initialiseWithConfig:"},{"text":"(","kind":"text"},{"text":"AutomixSDKConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tunedDelegate:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)TunedRestDelegate","kind":"typeIdentifier","text":"id<TunedRestDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tunedDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"statusDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","text":"id<AutomixSDKStatusObserverDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"statusDelegate"},{"text":" ","kind":"text"},{"text":"musicCacheDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<TunedMusicCacheDelegate>","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":") "},{"text":"musicCacheDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The AutomixIQ Configuration"}],"type":"paragraph"}],"name":"config"},{"content":[{"inlineContent":[{"text":"The delegate in charge of feeding and renewing Tuned Global OAuth2 access tokens. See TunedRestDelegate.","type":"text"}],"type":"paragraph"}],"name":"tunedDelegate"},{"name":"statusDelegate","content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixSDKStatusObserverDelegate."}],"type":"paragraph"}]},{"name":"musicCacheDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of saving and feeding in cached music to and from AutomixIQ"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/title","value":"AutomixSDKConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/fragments","op":"replace","value":[{"text":"AutomixSDKConfig","kind":"identifier"}]},{"value":[{"text":"AutomixSDKConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","op":"replace","value":"AutomixSDKStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/navigatorTitle"},{"value":"TunedMusicCacheDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/fragments","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/navigatorTitle","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace"},{"value":"initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(config:streamingDelegate:statusDelegate:completion:)\/title","value":"initialiseWithConfig:streamingDelegate:statusDelegate:completion:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:streamingDelegate:statusDelegate:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(config:streamingDelegate:statusDelegate:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title","value":"AutomixSDK"},{"value":[{"kind":"identifier","text":"AutomixSDK"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDK"}]},{"value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title","op":"replace"},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments","op":"replace"},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/navigatorTitle","op":"replace"}]}]}