{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackBpm"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"property","title":"trackBpm","roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtapeTrack(py)trackBpm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackBpm"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackBpm"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack\/trackBpm","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"text":"The bpm of the track","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkmixtapetrack\/trackbpm"]},{"paths":["\/documentation\/socialradio\/automixsdkmixtapetrack\/trackbpm"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack/trackBpm":{"role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkmixtapetrack\/trackbpm","abstract":[{"type":"text","text":"The bpm of the track"}],"navigatorTitle":[{"kind":"identifier","text":"trackBpm"}],"title":"trackBpm","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack\/trackBpm","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackBpm"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeTrack":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"url":"\/documentation\/socialradio\/automixsdkmixtapetrack","title":"AutomixSDKMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeTrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"trackBpm","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"trackBpm","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"text":"trackBpm","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"trackBpm","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack~1trackBpm\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack~1trackBpm\/fragments","value":[{"kind":"identifier","text":"trackBpm"}]},{"value":"AutomixSDKMixtapeTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeTrack\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}