{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedstoresettings\/maxstudiotransitionlength"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxStudioTransitionLength"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":"?"}],"externalID":"s:11SocialRadio18TunedStoreSettingsC25maxStudioTransitionLengthSfSgvp","symbolKind":"property","title":"maxStudioTransitionLength","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Property","role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxStudioTransitionLength","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/maxStudioTransitionLength","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TunedStoreSettings","kind":"identifier"}],"title":"TunedStoreSettings","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings","navigatorTitle":[{"text":"TunedStoreSettings","kind":"identifier"}],"url":"\/documentation\/socialradio\/tunedstoresettings","abstract":[{"type":"text","text":"Tuned Store settings"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedStoreSettings/maxStudioTransitionLength":{"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/tunedstoresettings\/maxstudiotransitionlength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxStudioTransitionLength"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":"?"}],"role":"symbol","title":"maxStudioTransitionLength","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedStoreSettings\/maxStudioTransitionLength","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings\/title","op":"replace","value":"TunedStoreSettings"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedStoreSettings"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedStoreSettings\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedStoreSettings"}]}]}]}