{"metadata":{"role":"symbol","title":"AutomixIQStatusVariable.canReorderTracks","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@AutomixIQStatusVariable@AutomixIQStatusVariableCanReorderTracks","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"canReorderTracks","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"AutomixIQStatusVariableCanReorderTracks","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/canreordertracks"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqstatusvariable\/canreordertracks"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canReorderTracks"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canReorderTracks"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable/canReorderTracks":{"abstract":[],"title":"AutomixIQStatusVariable.canReorderTracks","url":"\/documentation\/automixiq\/automixiqstatusvariable\/canreordertracks","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable\/canReorderTracks","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canReorderTracks","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariableCanReorderTracks","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusVariable":{"abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"title":"AutomixIQStatusVariable","url":"\/documentation\/automixiq\/automixiqstatusvariable","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusVariable","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","url":"\/documentation\/automixiq","role":"collection","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AutomixIQStatusVariableCanReorderTracks"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixIQStatusVariableCanReorderTracks","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AutomixIQStatusVariableCanReorderTracks","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canReorderTracks\/title","value":"AutomixIQStatusVariableCanReorderTracks"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable~1canReorderTracks\/fragments","value":[{"text":"AutomixIQStatusVariableCanReorderTracks","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/title","value":"AutomixIQStatusVariable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/fragments","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusVariable\/navigatorTitle","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}