{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePreferredTransitionDurationSeconds"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"roleHeading":"Case","symbolKind":"case","modules":[{"name":"SocialRadio"}],"role":"symbol","title":"AutomixIQStatusVariable.preferredTransitionDurationSeconds","externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariablePreferredTransitionDurationSeconds"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/preferredTransitionDurationSeconds","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/preferredtransitiondurationseconds"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/preferredtransitiondurationseconds"]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/preferredTransitionDurationSeconds":{"url":"\/documentation\/socialradio\/automixiqstatusvariable\/preferredtransitiondurationseconds","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariablePreferredTransitionDurationSeconds"}],"kind":"symbol","title":"AutomixIQStatusVariable.preferredTransitionDurationSeconds","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/preferredTransitionDurationSeconds","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","role":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixIQStatusVariable","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusVariable","kind":"identifier"}],"abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"title":"AutomixIQStatusVariable","url":"\/documentation\/socialradio\/automixiqstatusvariable","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AutomixIQStatusVariablePreferredTransitionDurationSeconds"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixIQStatusVariablePreferredTransitionDurationSeconds","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixIQStatusVariablePreferredTransitionDurationSeconds"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1preferredTransitionDurationSeconds\/title","value":"AutomixIQStatusVariablePreferredTransitionDurationSeconds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1preferredTransitionDurationSeconds\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariablePreferredTransitionDurationSeconds"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title","value":"AutomixIQStatusVariable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}