{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/tunedautomixplaybackmode\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","modules":[{"name":"SocialRadio"}],"symbolKind":"init","role":"symbol","externalID":"s:11SocialRadio24TunedAutomixPlaybackModeO8rawValueACSgSi_tcfc","roleHeading":"Initializer"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode\/init(rawValue:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio","role":"collection","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic","title":"init(rawValue:)","url":"\/documentation\/socialradio\/tunedautomixplaybackmode\/init(rawvalue:)","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode\/init(rawValue:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAutomixPlaybackMode":{"navigatorTitle":[{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQ playback mode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAutomixPlaybackMode","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAutomixPlaybackMode","kind":"identifier"}],"title":"TunedAutomixPlaybackMode","url":"\/documentation\/socialradio\/tunedautomixplaybackmode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TunedAutomixPlaybackMode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/title"},{"value":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/fragments"},{"value":[{"kind":"identifier","text":"TunedAutomixPlaybackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAutomixPlaybackMode\/navigatorTitle"}]}]}