{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel\/adDuration"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Objective-C accessible member for the duration","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedadmodel\/adduration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/tunedadmodel\/adduration"]}],"sections":[],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)TunedAdModel(py)adDuration","navigatorTitle":[{"text":"adDuration","kind":"identifier"}],"role":"symbol","title":"adDuration","modules":[{"name":"SocialRadio"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAdModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAdModel"}],"abstract":[{"type":"text","text":"TunedAdModel models a Ad."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedAdModel"}],"title":"TunedAdModel","url":"\/documentation\/socialradio\/tunedadmodel","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAdModel/adDuration":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/socialradio\/tunedadmodel\/adduration","navigatorTitle":[{"kind":"identifier","text":"adDuration"}],"kind":"symbol","abstract":[{"type":"text","text":"Objective-C accessible member for the duration"}],"title":"adDuration","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel\/adDuration"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"adDuration","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"adDuration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"adDuration","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"TunedAdModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TunedAdModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/fragments","op":"replace"},{"value":[{"text":"TunedAdModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/navigatorTitle","op":"replace"},{"value":"adDuration","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel~1adDuration\/title","op":"replace"},{"value":[{"text":"adDuration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel~1adDuration\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}