{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Called by AutomixIQ when a track download progress has changed.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadProgressChanged"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"progress"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ is streaming."}],"type":"paragraph"}],"name":"trackId"},{"name":"progress","content":[{"inlineContent":[{"type":"text","text":"The track download progress, between 0 (none) and 1 (complete)."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/socialradio\/tunedmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/tunedmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","required":true,"navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"modules":[{"name":"SocialRadio"}],"role":"symbol","externalID":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate(im)trackDownloadProgressChangedWithTrackId:progress:","title":"trackDownloadProgressChanged(trackId:progress:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadProgressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedMusicCacheDelegate/trackDownloadProgressChanged(trackId:progress:)":{"url":"\/documentation\/socialradio\/tunedmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","title":"trackDownloadProgressChanged(trackId:progress:)","type":"topic","navigatorTitle":[{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}],"required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedMusicCacheDelegate":{"url":"\/documentation\/socialradio\/tunedmusiccachedelegate","navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"kind":"symbol","type":"topic","title":"TunedMusicCacheDelegate","abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"trackDownloadProgressChangedWithTrackId:progress:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"trackId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"progress:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"progress","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The id of the track that AutomixIQ is streaming.","type":"text"}]}],"name":"trackId"},{"content":[{"inlineContent":[{"type":"text","text":"The track download progress, between 0 (none) and 1 (complete)."}],"type":"paragraph"}],"name":"progress"}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":"trackDownloadProgressChangedWithTrackId:progress:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/title","op":"replace","value":"TunedMusicCacheDelegate"},{"value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]}]}]}