{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel"]]},"metadata":{"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformModel(im)init"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkwaveformmodel\/init"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel\/init"},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel/init":{"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel\/init","role":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkwaveformmodel\/init","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","abstract":[{"text":"AutomixSDKWaveformModel models the waveform of a track.","type":"text"}],"title":"AutomixSDKWaveformModel","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"url":"\/documentation\/socialradio\/automixsdkwaveformmodel","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/title","value":"AutomixSDKWaveformModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/fragments","op":"replace","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},{"value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/navigatorTitle"}]}]}