{"abstract":[{"text":"The time in the current track where the next track’s starting duration would be. This is not where the next track would begin playback as the first few seconds may be muted to create a better transition.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This is helpful to align waveforms when rendering transitions."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel\/nextTrack0SecondsAnchorTime"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkwaveformmodel\/nexttrack0secondsanchortime"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkwaveformmodel\/nexttrack0secondsanchortime"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTrack0SecondsAnchorTime"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"roleHeading":"Instance Property","title":"nextTrack0SecondsAnchorTime","modules":[{"name":"SocialRadio"}],"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformModel(py)nextTrack0SecondsAnchorTime","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"nextTrack0SecondsAnchorTime"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","abstract":[{"text":"AutomixSDKWaveformModel models the waveform of a track.","type":"text"}],"title":"AutomixSDKWaveformModel","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"url":"\/documentation\/socialradio\/automixsdkwaveformmodel","kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel/nextTrack0SecondsAnchorTime":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel\/nextTrack0SecondsAnchorTime","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTrack0SecondsAnchorTime"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"kind":"symbol","title":"nextTrack0SecondsAnchorTime","role":"symbol","url":"\/documentation\/socialradio\/automixsdkwaveformmodel\/nexttrack0secondsanchortime","abstract":[{"type":"text","text":"The time in the current track where the next track’s starting duration would be. This is not where the next track would begin playback as the first few seconds may be muted to create a better transition."},{"type":"text","text":" "},{"text":"This is helpful to align waveforms when rendering transitions.","type":"text"}],"navigatorTitle":[{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"nextTrack0SecondsAnchorTime","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"AutomixSDKWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/fragments","op":"replace","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/navigatorTitle","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel~1nextTrack0SecondsAnchorTime\/title","op":"replace","value":"nextTrack0SecondsAnchorTime"},{"value":[{"kind":"identifier","text":"nextTrack0SecondsAnchorTime"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel~1nextTrack0SecondsAnchorTime\/fragments","op":"replace"}]}]}