{"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/socialradiocredentials\/init(dictionary:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials\/init(dictionary:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"dictionary"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"title":"init(dictionary:)","modules":[{"name":"SocialRadio"}],"externalID":"s:11SocialRadio0aB11CredentialsC10dictionaryACSgSDySSypG_tcfc","symbolKind":"init","role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"url":"\/documentation\/socialradio","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCredentials":{"kind":"symbol","role":"symbol","title":"SocialRadioCredentials","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioCredentials"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioCredentials"}],"abstract":[{"type":"text","text":"SocialRadioCredentials models credentials to access social REST APIs."}],"url":"\/documentation\/socialradio\/socialradiocredentials"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCredentials/init(dictionary:)":{"url":"\/documentation\/socialradio\/socialradiocredentials\/init(dictionary:)","abstract":[],"title":"init(dictionary:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials\/init(dictionary:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"dictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SocialRadioCredentials","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/fragments","value":[{"kind":"identifier","text":"SocialRadioCredentials"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioCredentials"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}