{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"]]},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"didCloseRadioUIWithUserInitiated:"}],"title":"didCloseRadioUI(userInitiated:)","role":"symbol","externalID":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate(im)didCloseRadioUIWithUserInitiated:","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCloseRadioUI"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiouidelegate\/didcloseradioui(userinitiated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiouidelegate\/didcloseradioui(userinitiated:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"Called by SocialRadio when the Radio UI is closed","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didCloseRadioUI(userInitiated:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCloseRadioUI"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInitiated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"mentions":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-article"],"kind":"mentions"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/didCloseRadioUI(userInitiated:)":{"url":"\/documentation\/socialradio\/socialradiouidelegate\/didcloseradioui(userinitiated:)","title":"didCloseRadioUI(userInitiated:)","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didCloseRadioUI(userInitiated:)","abstract":[{"text":"Called by SocialRadio when the Radio UI is closed","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-article":{"kind":"article","title":"Initializing SocialRadio","role":"article","url":"\/documentation\/socialradio\/initialising-socialradio-article","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-with-custom-audio-and-social-layer-article":{"url":"\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-and-social-layer-article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","kind":"article","type":"topic","role":"article","title":"Initializing SocialRadio with custom audio and social layer","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with custom audio track data and custom social layer.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-with-custom-audio-article":{"url":"\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-article","type":"topic","title":"Initializing SocialRadio with custom audio","role":"article","kind":"article","abstract":[{"type":"text","text":"How to validate your client and start using the SocialRadio SDK with custom audio track data."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","title":"SocialRadio","role":"collection","type":"topic","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"kind":"symbol","title":"SocialRadioUIDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate","type":"topic","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"didCloseRadioUIWithUserInitiated:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didCloseRadioUIWithUserInitiated:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"userInitiated","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"didCloseRadioUIWithUserInitiated:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didCloseRadioUI(userInitiated:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didCloseRadioUI(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"}]},{"value":"SocialRadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle"}]}]}