{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Initializer","symbolKind":"init","externalID":"s:9AutomixIQ18TunedStoreSettingsC4fromACs7Decoder_p_tKcfc","modules":[{"name":"AutomixIQ"}],"title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedStoreSettings\/init(from:)"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Decodable.init(from:)"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/automixiq\/tunedstoresettings\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedStoreSettings"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedStoreSettings":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedStoreSettings","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedStoreSettings"}],"title":"TunedStoreSettings","role":"symbol","url":"\/documentation\/automixiq\/tunedstoresettings","type":"topic","abstract":[{"type":"text","text":"Tuned Store settings"}],"navigatorTitle":[{"kind":"identifier","text":"TunedStoreSettings"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedStoreSettings/init(from:)":{"url":"\/documentation\/automixiq\/tunedstoresettings\/init(from:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedStoreSettings\/init(from:)","title":"init(from:)","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","type":"topic","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"title":"AutomixIQ","url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedStoreSettings\/title","op":"replace","value":"TunedStoreSettings"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedStoreSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedStoreSettings"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedStoreSettings\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedStoreSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}