{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"}],"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding content moderation."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/sociallayermoderationdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayermoderationdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate\/postReportUser(identifier:completion:)"],"title":"Instance Methods","generated":true}],"seeAlsoSections":[{"anchor":"Initialising-SocialRadio-for-use-with-custom-audio-and-custom-social-layer","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate"],"title":"Initialising SocialRadio for use with custom audio and custom social layer","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"sections":[],"kind":"symbol","metadata":{"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SocialLayerModerationDelegate"}],"externalID":"c:@M@SocialRadio@objc(pl)SocialLayerModerationDelegate","role":"symbol","title":"SocialLayerModerationDelegate","roleHeading":"Protocol","modules":[{"name":"SocialRadio"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"navigatorTitle":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"title":"SocialRadioUIDelegate","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","abstract":[{"type":"text","text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"url":"\/documentation\/socialradio\/socialradiouidelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUIDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerTrackLikesDelegate":{"title":"SocialLayerTrackLikesDelegate","navigatorTitle":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayertracklikesdelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a track.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"type":"topic","url":"\/documentation\/socialradio\/automixiqstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","abstract":[{"text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"role":"symbol","title":"AutomixIQStreamingDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerModerationDelegate/postReportUser(identifier:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"postReportUserWithIdentifier:completion:"}],"kind":"symbol","type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postReportUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"text":"Reports a user.","type":"text"}],"url":"\/documentation\/socialradio\/sociallayermoderationdelegate\/postreportuser(identifier:completion:)","title":"postReportUser(identifier:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate\/postReportUser(identifier:completion:)","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"navigatorTitle":[{"text":"SocialLayerDelegates","kind":"identifier"}],"title":"SocialLayerDelegates","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerDelegates","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayerdelegates","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","role":"symbol","kind":"symbol","abstract":[{"text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions.","type":"text"},{"text":" ","type":"text"},{"text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc.","type":"text"},{"text":" ","type":"text"},{"text":"See each delegate’s documentation for details.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeLikesDelegate":{"abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a mixtape.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeLikesDelegate","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SocialLayerMixtapeLikesDelegate","kind":"identifier"}],"title":"SocialLayerMixtapeLikesDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","url":"\/documentation\/socialradio\/sociallayermixtapelikesdelegate","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerNotificationsDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","url":"\/documentation\/socialradio\/sociallayernotificationsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding notifications.","type":"text"}],"navigatorTitle":[{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"title":"SocialLayerNotificationsDelegate"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AuthenticationDelegate":{"kind":"symbol","abstract":[{"text":"Handles handoff of authentication tokens","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/authenticationdelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","title":"AuthenticationDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate":{"url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","title":"SocialLayerMixtapeBackgroundsDelegate","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate":{"role":"symbol","navigatorTitle":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"title":"SocialLayerLiveMixtapeDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding live mixtapes."}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerAuthenticationDelegate":{"title":"SocialLayerAuthenticationDelegate","type":"topic","abstract":[{"text":"(Required) Handles communication between SocialRadio SDK and a backend regarding authentication","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","role":"symbol","url":"\/documentation\/socialradio\/sociallayerauthenticationdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerUserDelegate":{"role":"symbol","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding  users."}],"title":"SocialLayerUserDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerUserDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","url":"\/documentation\/socialradio\/sociallayeruserdelegate","navigatorTitle":[{"text":"SocialLayerUserDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerModerationDelegate":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayermoderationdelegate","title":"SocialLayerModerationDelegate","kind":"symbol","abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding content moderation."}],"navigatorTitle":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","title":"SocialRadioStatusObserverDelegate","kind":"symbol","url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-with-custom-audio-and-social-layer-article":{"url":"\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-and-social-layer-article","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","role":"article","kind":"article","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with custom audio track data and custom social layer.","type":"text"}],"title":"Initializing SocialRadio with custom audio and social layer"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackMetadataDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiotrackmetadatadelegate","title":"SocialRadioTrackMetadataDelegate","navigatorTitle":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Handles track recommendations and artwork","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate":{"title":"SocialLayerMixtapeCommentsDelegate","type":"topic","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding commenting a mixtape.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","role":"symbol","url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SocialLayerModerationDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate\/postReportUser(identifier:completion:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Initialising-SocialRadio-for-use-with-custom-audio-and-custom-social-layer","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate"],"title":"Initialising SocialRadio for use with custom audio and custom social layer","generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerModerationDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SocialRadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments"},{"op":"replace","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle"},{"op":"replace","value":"SocialLayerTrackLikesDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/title"},{"op":"replace","value":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/fragments"},{"op":"replace","value":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments"},{"op":"replace","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle"},{"op":"replace","value":"postReportUserWithIdentifier:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate~1postReportUser(identifier:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"postReportUserWithIdentifier:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate~1postReportUser(identifier:completion:)\/fragments"},{"op":"replace","value":"SocialLayerDelegates","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title"},{"op":"replace","value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments"},{"op":"replace","value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle"},{"op":"replace","value":"SocialLayerMixtapeLikesDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialLayerMixtapeLikesDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/fragments"},{"op":"replace","value":[{"text":"SocialLayerMixtapeLikesDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/navigatorTitle"},{"op":"replace","value":"SocialLayerNotificationsDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/title"},{"op":"replace","value":[{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/fragments"},{"op":"replace","value":[{"text":"SocialLayerNotificationsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/title","op":"replace","value":"AuthenticationDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AuthenticationDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AuthenticationDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/title","op":"replace","value":"SocialLayerMixtapeBackgroundsDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/fragments","op":"replace","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/title","op":"replace","value":"SocialLayerLiveMixtapeDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/title","op":"replace","value":"SocialLayerAuthenticationDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/fragments","op":"replace","value":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/title","op":"replace","value":"SocialLayerUserDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialLayerUserDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialLayerUserDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/title","op":"replace","value":"SocialLayerModerationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerModerationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/navigatorTitle","value":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","value":"SocialRadioStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/title","value":"SocialRadioTrackMetadataDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/fragments","value":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/navigatorTitle","value":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/title","value":"SocialLayerMixtapeCommentsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/navigatorTitle","value":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}