{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getNewUserImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"Code to be executed upon completion.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Parameter uuid: The UUID of the new background."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter image: The newly generated image.","type":"text"}]}]}],"type":"unorderedList"}]}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate\/getNewUserImage(completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate\/getnewuserimage(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate\/getnewuserimage(completion:)"]}],"metadata":{"symbolKind":"method","title":"getNewUserImage(completion:)","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate(im)getNewUserImageWithCompletion:","roleHeading":"Instance Method","role":"symbol","required":true,"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"getNewUserImageWithCompletion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getNewUserImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"abstract":[{"text":"Retrieves a new user-specific background image.","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate/getNewUserImage(completion:)":{"title":"getNewUserImage(completion:)","abstract":[{"text":"Retrieves a new user-specific background image.","type":"text"}],"navigatorTitle":[{"text":"getNewUserImageWithCompletion:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate\/getNewUserImage(completion:)","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate\/getnewuserimage(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getNewUserImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate":{"url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds.","type":"text"}],"navigatorTitle":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"role":"symbol","title":"SocialLayerMixtapeBackgroundsDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","url":"\/documentation\/socialradio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"getNewUserImageWithCompletion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getNewUserImageWithCompletion:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"getNewUserImageWithCompletion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Code to be executed upon completion.","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter uuid: The UUID of the new background."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter image: The newly generated image."}]}]}]}],"name":"completion"}]},"op":"replace"},{"op":"replace","value":"getNewUserImageWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate~1getNewUserImage(completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getNewUserImageWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate~1getNewUserImage(completion:)\/fragments"},{"op":"replace","value":"SocialLayerMixtapeBackgroundsDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialLayerMixtapeBackgroundsDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/fragments"},{"op":"replace","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}