{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/tunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"]]},"metadata":{"navigatorTitle":[{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@SocialRadio@objc(pl)TunedRestDelegate(im)asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","symbolKind":"method","modules":[{"name":"SocialRadio"}],"title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asyncGetAuthenticatedDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tunedDeviceId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncGetAuthenticatedDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tunedDeviceId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The unique identifier of the device"}],"type":"paragraph"}],"name":"deviceIdentifierForVendor"},{"content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Parameter tunedDeviceId: The device id within the Tuned Global backend as a String, nil if there was an error.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}],"name":"completion"}]},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required."},{"type":"text","text":" "},{"type":"text","text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”."}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"title":"TunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/tunedrestdelegate","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-article":{"title":"Initializing SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-article","type":"topic","url":"\/documentation\/socialradio\/initialising-socialradio-article","abstract":[{"type":"text","text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs"}],"kind":"article","role":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)":{"title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"asyncGetAuthenticatedDevice","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedDeviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"url":"\/documentation\/socialradio\/tunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)","abstract":[{"text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required.","type":"text"},{"type":"text","text":" "},{"text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”.","type":"text"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"deviceIdentifierForVendor","content":[{"inlineContent":[{"text":"The unique identifier of the device","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter tunedDeviceId: The device id within the Tuned Global backend as a String, nil if there was an error."}]}]}],"type":"unorderedList"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"TunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title"},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments"},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle"},{"value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/fragments"}]}]}