{"metadata":{"title":"postUpdateMixtapeMetadata(identifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)","navigatorTitle":[{"kind":"identifier","text":"postUpdateMixtapeMetadataWithIdentifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:"}],"symbolKind":"method","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postUpdateMixtapeMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"encodedRecipe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mixDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"oldMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tracksJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","required":true,"externalID":"c:@M@SocialRadio@objc(pl)SocialLayerLiveMixtapeDelegate(im)postUpdateMixtapeMetadataWithIdentifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/postUpdateMixtapeMetadata(identifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postUpdateMixtapeMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"encodedRecipe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mixDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"oldMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tracksJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The mixtape ID.","type":"text"}]}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional new title for the mix."}]}],"name":"newTitle"},{"content":[{"inlineContent":[{"text":"Encoded recipe string.","type":"text"}],"type":"paragraph"}],"name":"encodedRecipe"},{"content":[{"inlineContent":[{"type":"text","text":"Updated mix metadata."}],"type":"paragraph"}],"name":"mixDictionary"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Previous hash of the mix."}]}],"name":"oldMixHash"},{"content":[{"inlineContent":[{"text":"New hash after changes.","type":"text"}],"type":"paragraph"}],"name":"newMixHash"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The JSON string representing the recipe’s metadata.","type":"text"}]}],"name":"recipeJSONString"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JSON string representing the tracks in the recipe’s metadata.."}]}],"name":"tracksJSONString"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]}],"name":"completion"}]}],"abstract":[{"type":"text","text":"Attempts to commit a co-creation mixtape."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/postupdatemixtapemetadata(identifier:newtitle:encodedrecipe:mixdictionary:oldmixhash:newmixhash:recipejsonstring:tracksjsonstring:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/postupdatemixtapemetadata(identifier:newtitle:encodedrecipe:mixdictionary:oldmixhash:newmixhash:recipejsonstring:tracksjsonstring:completion:)"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate/postUpdateMixtapeMetadata(identifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)":{"abstract":[{"type":"text","text":"Attempts to commit a co-creation mixtape."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/postUpdateMixtapeMetadata(identifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)","kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/postupdatemixtapemetadata(identifier:newtitle:encodedrecipe:mixdictionary:oldmixhash:newmixhash:recipejsonstring:tracksjsonstring:completion:)","title":"postUpdateMixtapeMetadata(identifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postUpdateMixtapeMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"encodedRecipe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mixDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"oldMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tracksJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"postUpdateMixtapeMetadataWithIdentifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate":{"abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding live mixtapes."}],"url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"type":"topic","title":"SocialLayerLiveMixtapeDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"postUpdateMixtapeMetadataWithIdentifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"postUpdateMixtapeMetadataWithIdentifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"postUpdateMixtapeMetadataWithIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"newTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"newTitle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"encodedRecipe:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"encodedRecipe","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mixDictionary:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"mixDictionary","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"oldMixHash:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"oldMixHash","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"newMixHash:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"newMixHash","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"recipeJSONString:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"recipeJSONString","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tracksJSONString:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tracksJSONString","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The mixtape ID."}],"type":"paragraph"}],"name":"identifier"},{"content":[{"inlineContent":[{"text":"Optional new title for the mix.","type":"text"}],"type":"paragraph"}],"name":"newTitle"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Encoded recipe string."}]}],"name":"encodedRecipe"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Updated mix metadata."}]}],"name":"mixDictionary"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Previous hash of the mix."}]}],"name":"oldMixHash"},{"content":[{"inlineContent":[{"type":"text","text":"New hash after changes."}],"type":"paragraph"}],"name":"newMixHash"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The JSON string representing the recipe’s metadata.","type":"text"}]}],"name":"recipeJSONString"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JSON string representing the tracks in the recipe’s metadata.."}]}],"name":"tracksJSONString"},{"content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"}],"name":"completion"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"postUpdateMixtapeMetadataWithIdentifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1postUpdateMixtapeMetadata(identifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1postUpdateMixtapeMetadata(identifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"postUpdateMixtapeMetadataWithIdentifier:newTitle:encodedRecipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/title","value":"SocialLayerLiveMixtapeDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/fragments","value":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}