{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errorcode\/nointernetavailabletoolongoffline"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/errorcode\/nointernetavailabletoolongoffline"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noInternetAvailableTooLongOffline"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailableTooLongOffline","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeNoInternetAvailableTooLongOffline","modules":[{"name":"SocialRadio"}],"title":"ErrorCode.noInternetAvailableTooLongOffline","navigatorTitle":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}]},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","title":"ErrorCode","type":"topic","url":"\/documentation\/socialradio\/errorcode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/noInternetAvailableTooLongOffline":{"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noInternetAvailableTooLongOffline"}],"kind":"symbol","url":"\/documentation\/socialradio\/errorcode\/nointernetavailabletoolongoffline","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailableTooLongOffline"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailableTooLongOffline","title":"ErrorCode.noInternetAvailableTooLongOffline","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","kind":"symbol","url":"\/documentation\/socialradio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCodeNoInternetAvailableTooLongOffline"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailableTooLongOffline"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1noInternetAvailableTooLongOffline\/title","value":"ErrorCodeNoInternetAvailableTooLongOffline","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1noInternetAvailableTooLongOffline\/fragments","value":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailableTooLongOffline"}],"op":"replace"}]}]}