{"abstract":[{"text":"The artists of a track - the first one is the one to be presented by a UI","type":"text"}],"kind":"symbol","metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"Artists"}],"modules":[{"name":"SocialRadio"}],"title":"Artists","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Artists","kind":"identifier"},{"kind":"text","text":": ["},{"text":"SocialRadioArtistModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioArtistModel","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioTrackModel(py)Artists","role":"symbol","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Artists"},{"kind":"text","text":": ["},{"text":"SocialRadioArtistModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioArtistModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioArtistModel","kind":"typeIdentifier"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiotrackmodel\/artists"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiotrackmodel\/artists"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Artists"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel":{"title":"SocialRadioTrackModel","url":"\/documentation\/socialradio\/socialradiotrackmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioTrackModel","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioArtistModel":{"type":"topic","url":"\/documentation\/socialradio\/socialradioartistmodel","abstract":[{"type":"text","text":"SocialRadioArtistModel models an artist."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioArtistModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioArtistModel","navigatorTitle":[{"text":"SocialRadioArtistModel","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"SocialRadioArtistModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/Artists":{"abstract":[{"type":"text","text":"The artists of a track - the first one is the one to be presented by a UI"}],"url":"\/documentation\/socialradio\/socialradiotrackmodel\/artists","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Artists"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioArtistModel","text":"SocialRadioArtistModel"},{"kind":"text","text":"]?"}],"role":"symbol","kind":"symbol","title":"Artists","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Artists","navigatorTitle":[{"text":"Artists","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"Artists"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"Artists","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SocialRadioArtistModel *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"Artists"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/title","value":"SocialRadioTrackModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/fragments","value":[{"kind":"identifier","text":"SocialRadioTrackModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioTrackModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioArtistModel\/title","value":"SocialRadioArtistModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioArtistModel\/fragments","value":[{"text":"SocialRadioArtistModel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SocialRadioArtistModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioArtistModel\/navigatorTitle"},{"value":"Artists","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Artists\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Artists\/fragments","value":[{"text":"Artists","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}