{"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioTrackModel(py)Image","title":"Image","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"modules":[{"name":"SocialRadio"}]},"variants":[{"paths":["\/documentation\/socialradio\/socialradiotrackmodel\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiotrackmodel\/image"]}],"abstract":[{"type":"text","text":"The url of the artwork image for this track as a String"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"Image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Image","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel":{"title":"SocialRadioTrackModel","url":"\/documentation\/socialradio\/socialradiotrackmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioTrackModel","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/Image":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/Image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","title":"Image","abstract":[{"type":"text","text":"The url of the artwork image for this track as a String"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"Image","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/socialradio\/socialradiotrackmodel\/image"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"Image","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"Image"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"Image","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SocialRadioTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/title"},{"value":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/navigatorTitle","value":[{"text":"SocialRadioTrackModel","kind":"identifier"}],"op":"replace"},{"value":"Image","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Image\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel~1Image\/fragments","value":[{"kind":"identifier","text":"Image"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}