{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiotrackmodel\/tracknumber-1d0r6"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/TrackNumber-1d0r6"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"SocialRadio"}],"externalID":"s:11SocialRadio0aB10TrackModelC0C6NumberSiSgvp","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrackNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"TrackNumber","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The index of this track in the album it belongs to"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel":{"title":"SocialRadioTrackModel","url":"\/documentation\/socialradio\/socialradiotrackmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioTrackModel","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackModel/TrackNumber-1d0r6":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiotrackmodel\/tracknumber-1d0r6","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackModel\/TrackNumber-1d0r6","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The index of this track in the album it belongs to"}],"title":"TrackNumber","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SocialRadioTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/fragments","value":[{"text":"SocialRadioTrackModel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackModel\/navigatorTitle"}]}]}