{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"applyTransitions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The identifier of a track","type":"text"}]}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"True if you want the transition to be applied to the waveform data, false if you want the original waveform data","type":"text"}]}],"name":"applyTransitions"}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"returns the waveform data"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/automixiq\/waveformdatafortrack(identifier:applytransitions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiq\/waveformdatafortrack(identifier:applytransitions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/waveformDataForTrack(identifier:applyTransitions:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","title":"waveformDataForTrack(identifier:applyTransitions:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"applyTransitions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel"},{"text":"?","kind":"text"}],"modules":[{"name":"SocialRadio"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"waveformDataForTrackWithIdentifier:applyTransitions:","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQ(im)waveformDataForTrackWithIdentifier:applyTransitions:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Gets the waveform data for a track.","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"title":"AutomixIQWaveformModel","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"AutomixIQWaveformModel models the waveform of a track."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","url":"\/documentation\/socialradio\/automixiqwaveformmodel","type":"topic","navigatorTitle":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ/waveformDataForTrack(identifier:applyTransitions:)":{"title":"waveformDataForTrack(identifier:applyTransitions:)","kind":"symbol","role":"symbol","abstract":[{"text":"Gets the waveform data for a track.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applyTransitions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"AutomixIQWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/waveformDataForTrack(identifier:applyTransitions:)","url":"\/documentation\/socialradio\/automixiq\/waveformdatafortrack(identifier:applytransitions:)","type":"topic","navigatorTitle":[{"text":"waveformDataForTrackWithIdentifier:applyTransitions:","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"kind":"symbol","title":"AutomixIQ","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","url":"\/documentation\/socialradio\/automixiq","abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQ","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"url":"\/documentation\/socialradio","role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"waveformDataForTrackWithIdentifier:applyTransitions:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"waveformDataForTrackWithIdentifier:applyTransitions:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","text":"AutomixIQWaveformModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"waveformDataForTrackWithIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"applyTransitions:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"applyTransitions","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The identifier of a track","type":"text"}]}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"True if you want the transition to be applied to the waveform data, false if you want the original waveform data","type":"text"}]}],"name":"applyTransitions"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"AutomixIQWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title"},{"op":"replace","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments"},{"op":"replace","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle"},{"op":"replace","value":"waveformDataForTrackWithIdentifier:applyTransitions:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1waveformDataForTrack(identifier:applyTransitions:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"waveformDataForTrackWithIdentifier:applyTransitions:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1waveformDataForTrack(identifier:applyTransitions:)\/fragments"},{"op":"replace","value":"AutomixIQ","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title"},{"op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments"},{"op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}