{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":" ","kind":"text"},{"text":"encoder","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]}]}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiotunedauthenticationresponse\/encode(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse\/encode(to:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"s:11SocialRadio0aB27TunedAuthenticationResponseC6encode2toys7Encoder_p_tKF","title":"encode(to:)","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier","text":"Encoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Encodable.encode(to:)"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedAuthenticationResponse":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"abstract":[{"type":"text","text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request"}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiotunedauthenticationresponse","role":"symbol","navigatorTitle":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}],"title":"SocialRadioTunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedAuthenticationResponse/encode(to:)":{"url":"\/documentation\/socialradio\/socialradiotunedauthenticationresponse\/encode(to:)","role":"symbol","kind":"symbol","title":"encode(to:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse\/encode(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Encoder","preciseIdentifier":"s:s7EncoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse\/title","value":"SocialRadioTunedAuthenticationResponse","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse\/fragments","value":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse\/navigatorTitle","value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}],"op":"replace"}]}]}