{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse\/tuned_user_id","interfaceLanguage":"swift"},"abstract":[{"text":"The Id of the authenticated user in Tuned Global’s backend","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tuned_user_id"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tuned_user_id","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioTunedAuthenticationResponse(py)tuned_user_id","title":"tuned_user_id","symbolKind":"property","role":"symbol","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"tuned_user_id","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiotunedauthenticationresponse\/tuned_user_id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiotunedauthenticationresponse\/tuned_user_id"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedAuthenticationResponse":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"abstract":[{"type":"text","text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request"}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiotunedauthenticationresponse","role":"symbol","navigatorTitle":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}],"title":"SocialRadioTunedAuthenticationResponse","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedAuthenticationResponse/tuned_user_id":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tuned_user_id","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"tuned_user_id","kind":"identifier"}],"type":"topic","title":"tuned_user_id","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedAuthenticationResponse\/tuned_user_id","kind":"symbol","abstract":[{"text":"The Id of the authenticated user in Tuned Global’s backend","type":"text"}],"url":"\/documentation\/socialradio\/socialradiotunedauthenticationresponse\/tuned_user_id"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"tuned_user_id"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"tuned_user_id"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"tuned_user_id","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse\/title","value":"SocialRadioTunedAuthenticationResponse"},{"value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"op":"replace"},{"value":"tuned_user_id","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse~1tuned_user_id\/title"},{"value":[{"kind":"identifier","text":"tuned_user_id"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedAuthenticationResponse~1tuned_user_id\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}