{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackIndexX10","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"?"}]}]}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiocomment\/trackindexx10"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment\/trackIndexX10","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The track index that was playing when the comment was made, x10 for some reason"}],"sections":[],"metadata":{"externalID":"s:11SocialRadio0aB7CommentC13trackIndexX10SiSgvp","symbolKind":"property","role":"symbol","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackIndexX10"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"title":"trackIndexX10","roleHeading":"Instance Property"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment":{"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioComment models a comment"}],"title":"SocialRadioComment","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioComment"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioComment"}],"url":"\/documentation\/socialradio\/socialradiocomment"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment/trackIndexX10":{"url":"\/documentation\/socialradio\/socialradiocomment\/trackindexx10","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackIndexX10","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The track index that was playing when the comment was made, x10 for some reason"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment\/trackIndexX10","title":"trackIndexX10"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","title":"SocialRadio"}},"variantOverrides":[{"patch":[{"value":"SocialRadioComment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/title"},{"value":[{"kind":"identifier","text":"SocialRadioComment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioComment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}