{"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canOnOff","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)AutomixIQStatus(py)canOnOff","navigatorTitle":[{"text":"canOnOff","kind":"identifier"}],"role":"symbol","title":"canOnOff"},"sections":[],"abstract":[{"text":"Represents if the SDK can be turned On or off. It is true if not other On \/ Off action is ongoing, flase otherwise. When this switch is true, On \/Off actions return an error.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canOnOff","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/automixiqstatus\/canonoff"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqstatus\/canonoff"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canOnOff"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"kind":"symbol","navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"title":"AutomixIQStatus","abstract":[{"text":"AutomixIQStatus models the State of the AutomixIQ during playback.","type":"text"}],"url":"\/documentation\/socialradio\/automixiqstatus","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/canOnOff":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/canOnOff","title":"canOnOff","type":"topic","navigatorTitle":[{"text":"canOnOff","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canOnOff","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/socialradio\/automixiqstatus\/canonoff","abstract":[{"text":"Represents if the SDK can be turned On or off. It is true if not other On \/ Off action is ongoing, flase otherwise. When this switch is true, On \/Off actions return an error.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"canOnOff"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"canOnOff"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"canOnOff"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title","value":"AutomixIQStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canOnOff\/title","value":"canOnOff"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1canOnOff\/fragments","value":[{"kind":"identifier","text":"canOnOff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}