{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logAutomixSDKMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"logLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKLogLevel"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"logAutomixSDKMessage(logLevel:message:)","externalID":"c:@M@SocialRadio@objc(pl)TunedRestDelegate(im)logAutomixSDKMessageWithLogLevel:message:","role":"symbol","required":true,"modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"logAutomixSDKMessageWithLogLevel:message:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate\/logAutomixSDKMessage(logLevel:message:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedrestdelegate\/logautomixsdkmessage(loglevel:message:)"]},{"paths":["\/documentation\/socialradio\/tunedrestdelegate\/logautomixsdkmessage(loglevel:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logAutomixSDKMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"logLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","text":"AutomixSDKLogLevel"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"logLevel","content":[{"inlineContent":[{"type":"text","text":"The log level."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The message it wishes to log.","type":"text"}],"type":"paragraph"}],"name":"message"}]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate/logAutomixSDKMessage(logLevel:message:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logAutomixSDKMessage"},{"text":"(","kind":"text"},{"text":"logLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKLogLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"logAutomixSDKMessageWithLogLevel:message:"}],"abstract":[{"text":"Called by AutomixIQ when it wishes to output a log message","type":"text"}],"title":"logAutomixSDKMessage(logLevel:message:)","role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/tunedrestdelegate\/logautomixsdkmessage(loglevel:message:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate\/logAutomixSDKMessage(logLevel:message:)","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","title":"TunedRestDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"url":"\/documentation\/socialradio\/tunedrestdelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKLogLevel":{"url":"\/documentation\/socialradio\/automixsdkloglevel","navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels"}],"kind":"symbol","title":"AutomixSDKLogLevel","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"logAutomixSDKMessageWithLogLevel:message:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logAutomixSDKMessageWithLogLevel:message:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"logAutomixSDKMessageWithLogLevel:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKLogLevel","kind":"typeIdentifier","text":"AutomixSDKLogLevel","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKLogLevel"},{"text":") ","kind":"text"},{"text":"logLevel","kind":"internalParam"},{"kind":"text","text":" "},{"text":"message:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"logLevel","content":[{"type":"paragraph","inlineContent":[{"text":"The log level.","type":"text"}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message it wishes to log."}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate~1logAutomixSDKMessage(logLevel:message:)\/title","value":"logAutomixSDKMessageWithLogLevel:message:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"logAutomixSDKMessageWithLogLevel:message:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate~1logAutomixSDKMessage(logLevel:message:)\/fragments"},{"value":"TunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKLogLevel\/navigatorTitle"}]}]}