{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setMusicCacheDelegate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"musicCacheDelegate","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"musicCacheDelegate","content":[{"inlineContent":[{"type":"text","text":"The delegate to add."}],"type":"paragraph"}]}]}],"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)RadioSDK(im)setMusicCacheDelegate:","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"setMusicCacheDelegate:","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMusicCacheDelegate","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier","text":"TunedMusicCacheDelegate"},{"text":")","kind":"text"}],"title":"setMusicCacheDelegate(_:)","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Adds a new music cache delegate","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/setMusicCacheDelegate(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/socialradio\/radiosdk\/setmusiccachedelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/radiosdk\/setmusiccachedelegate(_:)"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK/setMusicCacheDelegate(_:)":{"title":"setMusicCacheDelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"setMusicCacheDelegate:"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK\/setMusicCacheDelegate(_:)","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/radiosdk\/setmusiccachedelegate(_:)","abstract":[{"type":"text","text":"Adds a new music cache delegate"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMusicCacheDelegate"},{"text":"(","kind":"text"},{"text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDK":{"type":"topic","title":"RadioSDK","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDK","url":"\/documentation\/socialradio\/radiosdk","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDK"}],"abstract":[{"type":"text","text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"navigatorTitle":[{"text":"RadioSDK","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedMusicCacheDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedMusicCacheDelegate","url":"\/documentation\/socialradio\/tunedmusiccachedelegate","navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"title":"TunedMusicCacheDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setMusicCacheDelegate:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setMusicCacheDelegate:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setMusicCacheDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<TunedMusicCacheDelegate>","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":") "},{"text":"musicCacheDelegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"musicCacheDelegate","content":[{"inlineContent":[{"text":"The delegate to add.","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1setMusicCacheDelegate(_:)\/title","value":"setMusicCacheDelegate:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setMusicCacheDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK~1setMusicCacheDelegate(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/title","value":"RadioSDK"},{"value":[{"text":"RadioSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDK\/navigatorTitle","value":[{"text":"RadioSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/title","op":"replace","value":"TunedMusicCacheDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/fragments","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedMusicCacheDelegate\/navigatorTitle","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace"}]}]}