{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedauthenticationresponse\/expires_in"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expires_in","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse\/expires_in","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expires_in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"externalID":"s:11SocialRadio27TunedAuthenticationResponseC10expires_inSiSgvp","title":"expires_in","symbolKind":"property","modules":[{"name":"SocialRadio"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The expiry time"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","url":"\/documentation\/socialradio\/tunedauthenticationresponse","navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"title":"TunedAuthenticationResponse","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAuthenticationResponse","kind":"identifier"}],"abstract":[{"text":"TunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse/expires_in":{"title":"expires_in","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expires_in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"url":"\/documentation\/socialradio\/tunedauthenticationresponse\/expires_in","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse\/expires_in","abstract":[{"type":"text","text":"The expiry time"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","kind":"symbol","url":"\/documentation\/socialradio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/title","value":"TunedAuthenticationResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/fragments","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/navigatorTitle","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}]}]}]}