{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser"]]},"sections":[],"metadata":{"symbolKind":"method","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioUser(im)init","roleHeading":"Instance Method","role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"SocialRadio"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiouser\/init"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser/init":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"init","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/socialradiouser\/init"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","title":"SocialRadioUser","role":"symbol","url":"\/documentation\/socialradio\/socialradiouser","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUser"}],"navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"abstract":[{"text":"SocialRadioUser models a user","type":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","title":"SocialRadio","url":"\/documentation\/socialradio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/title","value":"SocialRadioUser"},{"value":[{"kind":"identifier","text":"SocialRadioUser"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/navigatorTitle","value":[{"text":"SocialRadioUser","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}