{"metadata":{"symbolKind":"method","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKArtistModel(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","title":"init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/automixsdkartistmodel\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel\/init"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKArtistModel":{"url":"\/documentation\/socialradio\/automixsdkartistmodel","abstract":[{"type":"text","text":"AutomixSDKArtistModel models an artist."}],"title":"AutomixSDKArtistModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKArtistModel","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKArtistModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKArtistModel/init":{"abstract":[],"title":"init","url":"\/documentation\/socialradio\/automixsdkartistmodel\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKArtistModel\/init","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AutomixSDKArtistModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/fragments","value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKArtistModel\/navigatorTitle","op":"replace"}]}]}