{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig\/init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"allowFX"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowAudioEffects"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowBackgrounds"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowCommenting"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowVoiceOver"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowSongSuggestions"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowInvites"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowPublicBroadcasts"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowStudio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deeplinkToUser"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maximumTimerStatusUpdatesPerSecond"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"title":"init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:)","role":"symbol","roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:"}],"modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioFeatureSetConfig(im)initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"allowFX","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowAudioEffects","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowBackgrounds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowCommenting","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowVoiceOver","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowSongSuggestions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowInvites","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowPublicBroadcasts","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowStudio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"deeplinkToUser","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"\", ","kind":"text"},{"text":"maximumTimerStatusUpdatesPerSecond","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" = 60)","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiofeaturesetconfig\/init(allowfx:allowaudioeffects:allowbackgrounds:allowcommenting:allowvoiceover:allowsongsuggestions:allowinvites:allowpublicbroadcasts:allowstudio:deeplinktouser:maximumtimerstatusupdatespersecond:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiofeaturesetconfig\/init(allowfx:allowaudioeffects:allowbackgrounds:allowcommenting:allowvoiceover:allowsongsuggestions:allowinvites:allowpublicbroadcasts:allowstudio:deeplinktouser:maximumtimerstatusupdatespersecond:)"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig/init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"allowFX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"allowAudioEffects","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowBackgrounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowCommenting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowVoiceOver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowSongSuggestions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowInvites","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowPublicBroadcasts","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowStudio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"deeplinkToUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"maximumTimerStatusUpdatesPerSecond","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:)","navigatorTitle":[{"text":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig\/init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:)","role":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiofeaturesetconfig\/init(allowfx:allowaudioeffects:allowbackgrounds:allowcommenting:allowvoiceover:allowsongsuggestions:allowinvites:allowpublicbroadcasts:allowstudio:deeplinktouser:maximumtimerstatusupdatespersecond:)","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioFeatureSetConfig":{"navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiofeaturesetconfig","kind":"symbol","abstract":[{"type":"text","text":"Social Radio’s feature set options"}],"title":"SocialRadioFeatureSetConfig","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioFeatureSetConfig"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithAllowFX:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"allowFX","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowAudioEffects:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allowAudioEffects"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowBackgrounds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allowBackgrounds"},{"kind":"text","text":" "},{"text":"allowCommenting:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowCommenting","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowVoiceOver:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowVoiceOver","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowSongSuggestions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowSongSuggestions","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowInvites:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowInvites","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowPublicBroadcasts:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowPublicBroadcasts","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowStudio:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowStudio","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"deeplinkToUser:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"deeplinkToUser","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"maximumTimerStatusUpdatesPerSecond:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"maximumTimerStatusUpdatesPerSecond","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig~1init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:)\/title","value":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig~1init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:maximumTimerStatusUpdatesPerSecond:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/title","value":"SocialRadioFeatureSetConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/fragments","value":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioFeatureSetConfig\/navigatorTitle","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}