{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cannotSetupAVAudioSession","kind":"identifier"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cannotSetupAVAudioSession","kind":"identifier"}],"role":"symbol","title":"AutomixSDKErrorCode.cannotSetupAVAudioSession","modules":[{"name":"AutomixIQ"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotSetupAVAudioSession"}],"roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeCannotSetupAVAudioSession"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/cannotsetupavaudiosession"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/cannotsetupavaudiosession"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cannotSetupAVAudioSession":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/cannotsetupavaudiosession","title":"AutomixSDKErrorCode.cannotSetupAVAudioSession","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotSetupAVAudioSession"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotSetupAVAudioSession"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","title":"AutomixIQ","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","type":"topic","abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode","kind":"symbol","title":"AutomixSDKErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AutomixSDKErrorCodeCannotSetupAVAudioSession","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotSetupAVAudioSession"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotSetupAVAudioSession"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotSetupAVAudioSession\/title","op":"replace","value":"AutomixSDKErrorCodeCannotSetupAVAudioSession"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotSetupAVAudioSession\/fragments","value":[{"text":"AutomixSDKErrorCodeCannotSetupAVAudioSession","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]}]}]}