{"metadata":{"title":"AutomixIQPlaybackEventType.trackPlayPlayed5Secs","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@AutomixIQ@E@AutomixIQPlaybackEventType@AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"trackPlayPlayed5Secs","kind":"identifier"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlayPlayed5Secs","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayplayed5secs"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayplayed5secs"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType":{"navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqplaybackeventtype","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"role":"symbol","title":"AutomixIQPlaybackEventType","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlayPlayed5Secs":{"type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"AutomixIQPlaybackEventType.trackPlayPlayed5Secs","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlayPlayed5Secs","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayplayed5secs","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayPlayed5Secs"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/title"},{"value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/fragments"},{"value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/title","value":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs"},{"op":"replace","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayPlayed5Secs\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}