{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiq\/addtrack(identifier:metadata:contexttype:contextid:index:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiq\/addtrack(identifier:metadata:contexttype:contextid:index:completion:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTrack(identifier:metadata:contextType:contextId:index:completion:)","interfaceLanguage":"swift"},"abstract":[{"text":"Adds a single track to the AutomixIQ playlist at a given index.","type":"text"},{"text":" ","type":"text"},{"text":"Returns an erorr if the index is out of bounds.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","text":"TunedTrackModel","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"contextType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track identifier to be added."}]}]},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"TunedTrackModel object you can pass to the engine so it doesn’t make additional API requests for the corresponding track identifier metadata. Can be nil."}]}]},{"name":"contextType","content":[{"inlineContent":[{"text":"A string representing the source of these tracks, for logging purposes (‘playlist’, ‘album’, etc).","type":"text"}],"type":"paragraph"}]},{"name":"contextId","content":[{"type":"paragraph","inlineContent":[{"text":"The id of the source of these tracks, for logging purposes.","type":"text"}]}]},{"name":"index","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index at which this track will be added. If index == 0, it will be the first track of the playlist. If index == playlist.size() the track will be added last. If inbetween, it’ll push tracks from the index onwards back in the playlist to make room."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ"]]},"seeAlsoSections":[{"anchor":"Playback-Control","title":"Playback Control","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTracks(identifiers:metadata:contextType:contextId:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/pause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/playTrackUntilEndThenPause(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/toggleMute(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setMute(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/loopPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/reorderTracks(newOrder:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/clearAds(completion:)"],"generated":true}],"sections":[],"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQ(im)addTrackWithIdentifier:metadata:contextType:contextId:index:completion:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"AutomixIQ"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addTrackWithIdentifier:metadata:contextType:contextId:index:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","kind":"typeIdentifier","text":"TunedTrackModel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"title":"addTrack(identifier:metadata:contextType:contextId:index:completion:)"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/loopPlayingTrack(completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/loopPlayingTrack(completion:)","title":"loopPlayingTrack(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopPlayingTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"abstract":[{"text":"Makes AutomixIQ repeat the currently playing track.","type":"text"}],"url":"\/documentation\/automixiq\/automixiq\/loopplayingtrack(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loopPlayingTrackWithCompletion:"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/reorderTracks(newOrder:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reorderTracks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"newOrder","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reorderTracksWithNewOrder:completion:"}],"kind":"symbol","abstract":[{"type":"text","text":"Sets a new order to the playlist while continuing to play the current track"}],"type":"topic","url":"\/documentation\/automixiq\/automixiq\/reordertracks(neworder:completion:)","title":"reorderTracks(newOrder:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/reorderTracks(newOrder:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/removeTrack(at:completion:)":{"abstract":[{"type":"text","text":"Removes a track at a given index in the AutomixIQ playlist."},{"type":"text","text":" "},{"type":"text","text":"Returns an erorr if the index is out of bounds."}],"title":"removeTrack(at:completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/removeTrack(at:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"removeTrackAt:completion:"}],"url":"\/documentation\/automixiq\/automixiq\/removetrack(at:completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/play(completion:)":{"abstract":[{"text":"Starts playback if paused.","type":"text"},{"text":" ","type":"text"},{"text":"Returns an error if the player is already playing.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"role":"symbol","title":"play(completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/play(completion:)","url":"\/documentation\/automixiq\/automixiq\/play(completion:)","navigatorTitle":[{"kind":"identifier","text":"playWithCompletion:"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/addTracks(identifiers:metadata:contextType:contextId:index:completion:)":{"url":"\/documentation\/automixiq\/automixiq\/addtracks(identifiers:metadata:contexttype:contextid:index:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTracks(identifiers:metadata:contextType:contextId:index:completion:)","navigatorTitle":[{"text":"addTracksWithIdentifiers:metadata:contextType:contextId:index:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTracks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TunedTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"abstract":[{"text":"Adds additional tracks to the playlist in AutomixIQ at a given index.","type":"text"},{"text":" ","type":"text"},{"text":"Returns an erorr if the index is out of bounds.","type":"text"}],"title":"addTracks(identifiers:metadata:contextType:contextId:index:completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/toggleMute(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toggleMute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixiq\/togglemute(completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/toggleMute(completion:)","deprecated":true,"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Toggles the AutomixIQ SDK mute"}],"title":"toggleMute(completion:)","navigatorTitle":[{"text":"toggleMuteWithCompletion:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ":{"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/automixiq\/automixiq","navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}],"abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TunedTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"playTrackIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contextType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixiq\/loadtracks(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","title":"loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","abstract":[{"type":"text","text":"Loads a new playlist into AutomixIQ"},{"type":"text","text":" "},{"type":"text","text":"Returns an error if the playlist is empty this opperation will fail and AutomixIQ will be turned off."},{"type":"text","text":" "},{"type":"text","text":"This will stop playback of the currently playing playlist and start the newly loaded one."}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/previous(completion:)":{"type":"topic","kind":"symbol","url":"\/documentation\/automixiq\/automixiq\/previous(completion:)","abstract":[{"text":"Moves the player to the beginning of the previous track","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/previous(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previous"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"previousWithCompletion:"}],"title":"previous(completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/clearAds(completion:)":{"abstract":[{"text":"Removes existing Ad(s) if not currently playing one.","type":"text"}],"title":"clearAds(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearAdsWithCompletion:"}],"url":"\/documentation\/automixiq\/automixiq\/clearads(completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/clearAds(completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearAds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/skipToTrackAtIndex(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/skipToTrackAtIndex(_:completion:)","url":"\/documentation\/automixiq\/automixiq\/skiptotrackatindex(_:completion:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Jumps playback to the beginning of the track at the desired index as soon as possible."}],"title":"skipToTrackAtIndex(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipToTrackAtIndex"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"kind":"symbol","navigatorTitle":[{"text":"skipToTrackAtIndex:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/playTrackUntilEndThenPause(_:completion:)":{"type":"topic","kind":"symbol","title":"playTrackUntilEndThenPause(_:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/playTrackUntilEndThenPause(_:completion:)","url":"\/documentation\/automixiq\/automixiq\/playtrackuntilendthenpause(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playTrackUntilEndThenPause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"playTrackUntilEndThenPause:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Makes AutomixIQ play a given track until the end and then pause."},{"type":"text","text":" "},{"type":"text","text":"This is useful if you need to play any other content between tracks such as advertisements."},{"type":"text","text":" "},{"type":"text","text":"Returns an error if you call this on the last track’"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setAutomixPlaySpeed(_:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAutomixPlaySpeed","kind":"identifier"},{"text":"(Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAutomixPlaySpeed:completion:"}],"kind":"symbol","abstract":[{"type":"text","text":"Sets AutomixIQ’s play speed to a given value between 0.5 and 2, where 0.5 is half speed and 2 is double speed."}],"type":"topic","url":"\/documentation\/automixiq\/automixiq\/setautomixplayspeed(_:completion:)","title":"setAutomixPlaySpeed(_:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setAutomixPlaySpeed(_:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/toggleReplay(completion:)":{"abstract":[{"type":"text","text":"If on, after a playlist is done it restarts. Otherwise, it pauses."},{"type":"text","text":" "},{"type":"text","text":"This defaults to false on initialisation and should be set to match the state of the consumer’s UI"}],"title":"toggleReplay(completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/toggleReplay(completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggleReplay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"deprecated":true,"navigatorTitle":[{"text":"toggleReplayWithCompletion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq\/togglereplay(completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setAutomixVolumeNormalised(_:completion:)":{"abstract":[{"type":"text","text":"Sets AutomixIQ’s volume to a given value between 0 and 1. If muted, calling this will cause AutomixIQ to unmute."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAutomixVolumeNormalised"},{"kind":"text","text":"(Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"setAutomixVolumeNormalised:completion:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setAutomixVolumeNormalised(_:completion:)","url":"\/documentation\/automixiq\/automixiq\/setautomixvolumenormalised(_:completion:)","title":"setAutomixVolumeNormalised(_:completion:)","kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/next(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"next"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nextWithCompletion:"}],"kind":"symbol","type":"topic","title":"next(completion:)","url":"\/documentation\/automixiq\/automixiq\/next(completion:)","abstract":[{"text":"Moves the player to the beginning of the next track","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/next(completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/back(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"backWithCompletion:","kind":"identifier"}],"title":"back(completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/back(completion:)","abstract":[{"text":"Moves the player to the beginning of the current track","type":"text"}],"url":"\/documentation\/automixiq\/automixiq\/back(completion:)","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedTrackModel":{"type":"topic","url":"\/documentation\/automixiq\/tunedtrackmodel","kind":"symbol","role":"symbol","abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"title":"TunedTrackModel","navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/stopLoopingPlayingTrack(completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/stopLoopingPlayingTrack(completion:)","title":"stopLoopingPlayingTrack(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLoopingPlayingTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"abstract":[{"text":"Makes AutomixIQ stop repeating the currently playing track.","type":"text"}],"url":"\/documentation\/automixiq\/automixiq\/stoploopingplayingtrack(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopLoopingPlayingTrackWithCompletion:"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/seekTo(seconds:completion:)":{"type":"topic","abstract":[{"text":"Jumps playback on the current track to the desired timestamp as soon as possible.","type":"text"},{"text":" ","type":"text"},{"text":"This will mix the track with itself so the seek is beat-matched and as seamless as possible, which means the landing position will be close but not exactly the fed timestamp.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekTo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"seekToSeconds:completion:"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/seekTo(seconds:completion:)","url":"\/documentation\/automixiq\/automixiq\/seekto(seconds:completion:)","kind":"symbol","title":"seekTo(seconds:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/pause(completion:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pauseWithCompletion:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/pause(completion:)","url":"\/documentation\/automixiq\/automixiq\/pause(completion:)","abstract":[{"type":"text","text":"Pauses playback if playing."},{"type":"text","text":" "},{"type":"text","text":"Returns an error if the player is already paused."}],"title":"pause(completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/addTrack(identifier:metadata:contextType:contextId:index:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTrack(identifier:metadata:contextType:contextId:index:completion:)","abstract":[{"text":"Adds a single track to the AutomixIQ playlist at a given index.","type":"text"},{"text":" ","type":"text"},{"text":"Returns an erorr if the index is out of bounds.","type":"text"}],"navigatorTitle":[{"text":"addTrackWithIdentifier:metadata:contextType:contextId:index:completion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq\/addtrack(identifier:metadata:contexttype:contextid:index:completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","title":"addTrack(identifier:metadata:contextType:contextId:index:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setReplay(on:completion:)":{"url":"\/documentation\/automixiq\/automixiq\/setreplay(on:completion:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setReplay(on:completion:)","abstract":[{"type":"text","text":"Tells AutomixIQ whether or not it should restart the playlist when reaching the end."},{"type":"text","text":" "},{"type":"text","text":"If on then playback will restart at the beginning otherwise it pauses at the end."}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setReplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"setReplay(on:completion:)","navigatorTitle":[{"text":"setReplayOn:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setMute(on:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setMuteOn:completion:"}],"kind":"symbol","type":"topic","title":"setMute(on:completion:)","url":"\/documentation\/automixiq\/automixiq\/setmute(on:completion:)","abstract":[{"text":"Mutes AutomixIQ","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setMute(on:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/moveTrack(at:toIndex:completion:)":{"type":"topic","navigatorTitle":[{"text":"moveTrackAt:toIndex:completion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq\/movetrack(at:toindex:completion:)","abstract":[{"text":"Moves the track from one index to a different index.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"toIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","title":"moveTrack(at:toIndex:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/moveTrack(at:toIndex:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"addTrackWithIdentifier:metadata:contextType:contextId:index:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addTrackWithIdentifier:metadata:contextType:contextId:index:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/addTracks(identifiers:metadata:contextType:contextId:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/pause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/playTrackUntilEndThenPause(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/toggleMute(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setMute(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/loopPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/reorderTracks(newOrder:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/clearAds(completion:)"],"generated":true,"anchor":"Playback-Control","title":"Playback Control"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addTrackWithIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"TunedTrackModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contextType"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int32_t","preciseIdentifier":"c:@T@int32_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"contextId"},{"kind":"text","text":" "},{"kind":"identifier","text":"index:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int32_t","text":"int32_t"},{"kind":"text","text":") "},{"kind":"internalParam","text":"index"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track identifier to be added."}]}]},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"TunedTrackModel object you can pass to the engine so it doesn’t make additional API requests for the corresponding track identifier metadata. Can be nil."}]}]},{"name":"contextType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string representing the source of these tracks, for logging purposes (‘playlist’, ‘album’, etc)."}]}]},{"name":"contextId","content":[{"inlineContent":[{"text":"The id of the source of these tracks, for logging purposes.","type":"text"}],"type":"paragraph"}]},{"name":"index","content":[{"inlineContent":[{"type":"text","text":"The index at which this track will be added. If index == 0, it will be the first track of the playlist. If index == playlist.size() the track will be added last. If inbetween, it’ll push tracks from the index onwards back in the playlist to make room."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1loopPlayingTrack(completion:)\/title","op":"replace","value":"loopPlayingTrackWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1loopPlayingTrack(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loopPlayingTrackWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1reorderTracks(newOrder:completion:)\/title","op":"replace","value":"reorderTracksWithNewOrder:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1reorderTracks(newOrder:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"reorderTracksWithNewOrder:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1removeTrack(at:completion:)\/title","op":"replace","value":"removeTrackAt:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1removeTrack(at:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeTrackAt:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1play(completion:)\/title","op":"replace","value":"playWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1play(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1addTracks(identifiers:metadata:contextType:contextId:index:completion:)\/title","op":"replace","value":"addTracksWithIdentifiers:metadata:contextType:contextId:index:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1addTracks(identifiers:metadata:contextType:contextId:index:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addTracksWithIdentifiers:metadata:contextType:contextId:index:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1toggleMute(completion:)\/title","op":"replace","value":"toggleMuteWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1toggleMute(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toggleMuteWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/title","op":"replace","value":"AutomixIQ"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQ"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title","op":"replace","value":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1previous(completion:)\/title","op":"replace","value":"previousWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1previous(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"previousWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1clearAds(completion:)\/title","op":"replace","value":"clearAdsWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1clearAds(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"clearAdsWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1skipToTrackAtIndex(_:completion:)\/title","op":"replace","value":"skipToTrackAtIndex:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1skipToTrackAtIndex(_:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"skipToTrackAtIndex:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1playTrackUntilEndThenPause(_:completion:)\/title","op":"replace","value":"playTrackUntilEndThenPause:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1playTrackUntilEndThenPause(_:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playTrackUntilEndThenPause:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setAutomixPlaySpeed(_:completion:)\/title","op":"replace","value":"setAutomixPlaySpeed:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setAutomixPlaySpeed(_:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setAutomixPlaySpeed:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1toggleReplay(completion:)\/title","op":"replace","value":"toggleReplayWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1toggleReplay(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toggleReplayWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setAutomixVolumeNormalised(_:completion:)\/title","op":"replace","value":"setAutomixVolumeNormalised:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setAutomixVolumeNormalised(_:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setAutomixVolumeNormalised:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1next(completion:)\/title","op":"replace","value":"nextWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1next(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nextWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1back(completion:)\/title","op":"replace","value":"backWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1back(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/title","op":"replace","value":"TunedTrackModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1stopLoopingPlayingTrack(completion:)\/title","op":"replace","value":"stopLoopingPlayingTrackWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1stopLoopingPlayingTrack(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopLoopingPlayingTrackWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1seekTo(seconds:completion:)\/title","op":"replace","value":"seekToSeconds:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1seekTo(seconds:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"seekToSeconds:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1pause(completion:)\/title","op":"replace","value":"pauseWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1pause(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pauseWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1addTrack(identifier:metadata:contextType:contextId:index:completion:)\/title","op":"replace","value":"addTrackWithIdentifier:metadata:contextType:contextId:index:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1addTrack(identifier:metadata:contextType:contextId:index:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTrackWithIdentifier:metadata:contextType:contextId:index:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setReplay(on:completion:)\/title","op":"replace","value":"setReplayOn:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setReplay(on:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setReplayOn:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setMute(on:completion:)\/title","op":"replace","value":"setMuteOn:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setMute(on:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setMuteOn:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1moveTrack(at:toIndex:completion:)\/title","op":"replace","value":"moveTrackAt:toIndex:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1moveTrack(at:toIndex:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveTrackAt:toIndex:completion:","kind":"identifier"}]}]}]}