{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqstatus\/playingtrackoriginalsessionid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqstatus\/playingtrackoriginalsessionid"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackOriginalSessionId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"metadata":{"modules":[{"name":"SocialRadio"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackOriginalSessionId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQStatus(py)playingTrackOriginalSessionId","navigatorTitle":[{"text":"playingTrackOriginalSessionId","kind":"identifier"}],"title":"playingTrackOriginalSessionId","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackOriginalSessionId","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/playingTrackOriginalSessionId":{"kind":"symbol","role":"symbol","title":"playingTrackOriginalSessionId","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/playingTrackOriginalSessionId","navigatorTitle":[{"kind":"identifier","text":"playingTrackOriginalSessionId"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqstatus\/playingtrackoriginalsessionid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackOriginalSessionId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"url":"\/documentation\/socialradio\/automixiqstatus","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatus"}],"type":"topic","title":"AutomixIQStatus","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatus"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"playingTrackOriginalSessionId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"playingTrackOriginalSessionId","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"playingTrackOriginalSessionId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackOriginalSessionId\/title","value":"playingTrackOriginalSessionId"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1playingTrackOriginalSessionId\/fragments","value":[{"text":"playingTrackOriginalSessionId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title","value":"AutomixIQStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments","value":[{"text":"AutomixIQStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle","value":[{"text":"AutomixIQStatus","kind":"identifier"}]}]}]}