{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"title":"ErrorCode.addTrackPlaylistDoesNotExist","externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeAddTrackPlaylistDoesNotExist","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackPlaylistDoesNotExist"}],"modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"roleHeading":"Case"},"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/errorcode\/addtrackplaylistdoesnotexist"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/errorcode\/addtrackplaylistdoesnotexist"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackPlaylistDoesNotExist","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/addTrackPlaylistDoesNotExist":{"title":"ErrorCode.addTrackPlaylistDoesNotExist","type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackPlaylistDoesNotExist"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeAddTrackPlaylistDoesNotExist"}],"url":"\/documentation\/socialradio\/errorcode\/addtrackplaylistdoesnotexist","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackPlaylistDoesNotExist"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"type":"topic","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","title":"ErrorCode","role":"symbol","url":"\/documentation\/socialradio\/errorcode"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ErrorCodeAddTrackPlaylistDoesNotExist","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackPlaylistDoesNotExist\/title","op":"replace","value":"ErrorCodeAddTrackPlaylistDoesNotExist"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackPlaylistDoesNotExist\/fragments","op":"replace","value":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]}]}]}