{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playingTrackIdentifier","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/playingtrackidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiostatusvariable\/playingtrackidentifier"]}],"sections":[],"metadata":{"roleHeading":"Case","role":"symbol","title":"SocialRadioStatusVariable.playingTrackIdentifier","navigatorTitle":[{"text":"SocialRadioStatusVariablePlayingTrackIdentifier","kind":"identifier"}],"modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@E@SocialRadioStatusVariable@SocialRadioStatusVariablePlayingTrackIdentifier","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackIdentifier","kind":"identifier"}],"symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/playingTrackIdentifier"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"title":"SocialRadioStatusVariable","url":"\/documentation\/socialradio\/socialradiostatusvariable","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusVariable"}],"abstract":[{"type":"text","text":"SocialRadio status variable type"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable/playingTrackIdentifier":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariablePlayingTrackIdentifier"}],"abstract":[],"url":"\/documentation\/socialradio\/socialradiostatusvariable\/playingtrackidentifier","title":"SocialRadioStatusVariable.playingTrackIdentifier","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playingTrackIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable\/playingTrackIdentifier","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"SocialRadioStatusVariablePlayingTrackIdentifier","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusVariablePlayingTrackIdentifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"SocialRadioStatusVariablePlayingTrackIdentifier","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title","op":"replace","value":"SocialRadioStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle"},{"value":"SocialRadioStatusVariablePlayingTrackIdentifier","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1playingTrackIdentifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable~1playingTrackIdentifier\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusVariablePlayingTrackIdentifier"}]}]}]}