{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"artistName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isExplicit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"releaseName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"tempo"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"trackId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the track"}]}]},{"name":"artistName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the main artist of the track"}]}]},{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The title of the track"}]}]},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track duration in seconds"}]}]},{"name":"isExplicit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if the track contains explicit lyrics, false otherwise"}]}]},{"name":"isAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if the track is an Ad, false otherwise"}]}]},{"name":"trackNumber","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index of the track in the album it was released in"}]}]},{"name":"releaseName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The nemae of the release this track’s in"}]}]},{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key of this track as a String in Camelot format, i.e. 8m, nil if unavailable"}]}]},{"name":"tempo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The bpm of this track as a float"}]}]},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url of the artwork image for this track as a String"}]}]}]}],"variants":[{"paths":["\/documentation\/automixiq\/tunedtrackmodel\/init(trackid:artistname:name:duration:isexplicit:isad:tracknumber:releasename:key:tempo:image:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/tunedtrackmodel\/init(trackid:artistname:name:duration:isexplicit:isad:tracknumber:releasename:key:tempo:image:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel\/init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel"]]},"abstract":[{"type":"text","text":"Initialises a Track Model"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"init","externalID":"c:@M@AutomixIQ@objc(cs)TunedTrackModel(im)initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"artistName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isExplicit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"trackNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"releaseName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tempo","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"AutomixIQ"}],"title":"init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)","navigatorTitle":[{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:"}],"roleHeading":"Initializer"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedTrackModel":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedTrackModel"}],"abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"type":"topic","url":"\/documentation\/automixiq\/tunedtrackmodel","title":"TunedTrackModel","navigatorTitle":[{"kind":"identifier","text":"TunedTrackModel"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedTrackModel/init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)":{"url":"\/documentation\/automixiq\/tunedtrackmodel\/init(trackid:artistname:name:duration:isexplicit:isad:tracknumber:releasename:key:tempo:image:)","abstract":[{"text":"Initialises a Track Model","type":"text"}],"role":"symbol","type":"topic","title":"init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)","kind":"symbol","navigatorTitle":[{"text":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"artistName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isExplicit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isAd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"trackNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"releaseName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tempo","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel\/init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithTrackId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"trackId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"artistName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"artistName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"duration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"duration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isExplicit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isExplicit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isAd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isAd","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"trackNumber:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"trackNumber","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"releaseName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"releaseName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"key:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tempo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"tempo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"image:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"trackId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the track"}]}]},{"name":"artistName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the main artist of the track"}]}]},{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The title of the track"}]}]},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track duration in seconds"}]}]},{"name":"isExplicit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if the track contains explicit lyrics, false otherwise"}]}]},{"name":"isAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if the track is an Ad, false otherwise"}]}]},{"name":"trackNumber","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index of the track in the album it was released in"}]}]},{"name":"releaseName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The nemae of the release this track’s in"}]}]},{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key of this track as a String in Camelot format, i.e. 8m, nil if unavailable"}]}]},{"name":"tempo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The bpm of this track as a float"}]}]},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url of the artwork image for this track as a String"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"TunedTrackModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/navigatorTitle","op":"replace"},{"value":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel~1init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel~1init(trackId:artistName:name:duration:isExplicit:isAd:trackNumber:releaseName:key:tempo:image:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}