{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/tunedtrackmodel\/fromtunedad(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/tunedtrackmodel\/fromtunedad(_:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel\/fromTunedAd(_:)","interfaceLanguage":"swift"},"metadata":{"title":"fromTunedAd(_:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromTunedAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TunedTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"method","externalID":"c:@M@SocialRadio@objc(cs)TunedTrackModel(cm)fromTunedAd:","navigatorTitle":[{"text":"fromTunedAd:","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromTunedAd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tunedAd","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","text":"TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","text":"TunedTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","role":"collection","url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAdModel":{"role":"symbol","abstract":[{"text":"TunedAdModel models a Ad.","type":"text"}],"url":"\/documentation\/socialradio\/tunedadmodel","navigatorTitle":[{"text":"TunedAdModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","kind":"symbol","title":"TunedAdModel","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAdModel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedTrackModel"}],"url":"\/documentation\/socialradio\/tunedtrackmodel","abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"title":"TunedTrackModel","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedTrackModel"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel/fromTunedAd(_:)":{"abstract":[],"type":"topic","title":"fromTunedAd(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromTunedAd:"}],"url":"\/documentation\/socialradio\/tunedtrackmodel\/fromtunedad(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromTunedAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","text":"TunedAdModel"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","text":"TunedTrackModel"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel\/fromTunedAd(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"fromTunedAd:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromTunedAd:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","text":"TunedTrackModel"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromTunedAd:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","text":"TunedAdModel"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tunedAd"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/title","op":"replace","value":"TunedAdModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/fragments","op":"replace","value":[{"text":"TunedAdModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedAdModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title","op":"replace","value":"TunedTrackModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle","op":"replace","value":[{"text":"TunedTrackModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel~1fromTunedAd(_:)\/title","op":"replace","value":"fromTunedAd:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel~1fromTunedAd(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromTunedAd:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}