{"metadata":{"navigatorTitle":[{"text":"token_type","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioTunedAuthenticationResponse(py)token_type","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"token_type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","title":"token_type","modules":[{"name":"SocialRadioLite"}]},"abstract":[{"type":"text","text":"The token type"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse\/token_type","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/socialradiolite\/socialradiotunedauthenticationresponse\/token_type"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiotunedauthenticationresponse\/token_type"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"token_type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse"]]},"sections":[],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedAuthenticationResponse":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"abstract":[{"text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"title":"SocialRadioTunedAuthenticationResponse","url":"\/documentation\/socialradiolite\/socialradiotunedauthenticationresponse","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedAuthenticationResponse/token_type":{"kind":"symbol","abstract":[{"text":"The token type","type":"text"}],"title":"token_type","url":"\/documentation\/socialradiolite\/socialradiotunedauthenticationresponse\/token_type","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse\/token_type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"token_type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"token_type","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"token_type","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"token_type","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"token_type","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"SocialRadioTunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/navigatorTitle","value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}]},{"op":"replace","value":"token_type","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse~1token_type\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse~1token_type\/fragments","value":[{"kind":"identifier","text":"token_type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}