{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqstreamingdelegate\/syncgetcachedtrack(trackid:)"]},{"paths":["\/documentation\/automixiq\/automixiqstreamingdelegate\/syncgetcachedtrack(trackid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","interfaceLanguage":"swift"},"metadata":{"required":true,"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate(im)syncGetCachedTrackWithTrackId:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"title":"syncGetCachedTrack(trackId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetCachedTrack"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetCachedTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The id of the track that AutomixIQ is streaming.","type":"text"}],"type":"paragraph"}],"name":"trackId"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The entire unencrypted track data, nil if not available."}]}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate":{"url":"\/documentation\/automixiq\/automixiqstreamingdelegate","abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"navigatorTitle":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"title":"AutomixIQStreamingDelegate","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/syncGetCachedTrack(trackId:)":{"required":true,"role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/syncgetcachedtrack(trackid:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"title":"syncGetCachedTrack(trackId:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetCachedTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"type":"topic","kind":"symbol","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"syncGetCachedTrackWithTrackId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"trackId","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"trackId","content":[{"inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ is streaming."}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The entire unencrypted track data, nil if not available."}]}]}},{"value":"AutomixIQStreamingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/title","value":"syncGetCachedTrackWithTrackId:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}]}]}]}