{"abstract":[{"type":"text","text":"The time in the track the right transition ends at, in seconds"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel\/rightTransitionEndTime","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightTransitionEndTime"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/automixiq\/automixsdkwaveformmodel\/righttransitionendtime"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkwaveformmodel\/righttransitionendtime"]}],"metadata":{"title":"rightTransitionEndTime","symbolKind":"property","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKWaveformModel(py)rightTransitionEndTime","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightTransitionEndTime"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"kind":"identifier","text":"rightTransitionEndTime"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKWaveformModel":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel","role":"symbol","abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"url":"\/documentation\/automixiq\/automixsdkwaveformmodel","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"title":"AutomixSDKWaveformModel"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKWaveformModel/rightTransitionEndTime":{"title":"rightTransitionEndTime","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightTransitionEndTime","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"type":"text","text":"The time in the track the right transition ends at, in seconds"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel\/rightTransitionEndTime","navigatorTitle":[{"kind":"identifier","text":"rightTransitionEndTime"}],"url":"\/documentation\/automixiq\/automixsdkwaveformmodel\/righttransitionendtime"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"rightTransitionEndTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rightTransitionEndTime"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"rightTransitionEndTime","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/title","op":"replace","value":"AutomixSDKWaveformModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/fragments","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/navigatorTitle","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},{"value":"rightTransitionEndTime","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel~1rightTransitionEndTime\/title","op":"replace"},{"value":[{"text":"rightTransitionEndTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel~1rightTransitionEndTime\/fragments"}]}]}