{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/failedTrackLoadIdentifiers"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqstatus\/failedtrackloadidentifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqstatus\/failedtrackloadidentifiers"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"failedTrackLoadIdentifiers","navigatorTitle":[{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQStatus(py)failedTrackLoadIdentifiers","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Property"},"abstract":[{"text":"Represents the tracks that failed loading for any reason","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/failedTrackLoadIdentifiers":{"role":"symbol","title":"failedTrackLoadIdentifiers","type":"topic","navigatorTitle":[{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/failedTrackLoadIdentifiers","abstract":[{"type":"text","text":"Represents the tracks that failed loading for any reason"}],"url":"\/documentation\/socialradio\/automixiqstatus\/failedtrackloadidentifiers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","url":"\/documentation\/socialradio\/automixiqstatus","abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"type":"topic","navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"title":"AutomixIQStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"failedTrackLoadIdentifiers","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"failedTrackLoadIdentifiers","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1failedTrackLoadIdentifiers\/title"},{"op":"replace","value":[{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1failedTrackLoadIdentifiers\/fragments"},{"op":"replace","value":"AutomixIQStatus","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}