{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}],"symbolKind":"case","modules":[{"name":"SocialRadio"}],"role":"symbol","title":"AutomixIQPlaybackEventType.mixPlaybackEnded","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"externalID":"c:@M@SocialRadio@E@AutomixIQPlaybackEventType@AutomixIQPlaybackEventTypeMixPlaybackEnded"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/mixPlaybackEnded"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/socialradio\/automixiqplaybackeventtype\/mixplaybackended"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqplaybackeventtype\/mixplaybackended"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType/mixPlaybackEnded":{"navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqplaybackeventtype\/mixplaybackended","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType\/mixPlaybackEnded","abstract":[],"title":"AutomixIQPlaybackEventType.mixPlaybackEnded"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQPlaybackEventType":{"role":"symbol","abstract":[{"text":"AutomixIQPlaybackEventType is an enum of all the available playback events","type":"text"}],"navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQPlaybackEventType","url":"\/documentation\/socialradio\/automixiqplaybackeventtype","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"title":"AutomixIQPlaybackEventType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AutomixIQPlaybackEventTypeMixPlaybackEnded","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AutomixIQPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/title","value":"AutomixIQPlaybackEventTypeMixPlaybackEnded"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/title","value":"AutomixIQPlaybackEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/fragments","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQPlaybackEventType\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}]}]}]}