{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQEqualiserConfig\/init"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQEqualiserConfig"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqequaliserconfig\/init"]}],"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQEqualiserConfig(im)init","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"AutomixIQ"}],"title":"init","symbolKind":"method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQEqualiserConfig/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQEqualiserConfig\/init","kind":"symbol","title":"init","abstract":[],"url":"\/documentation\/automixiq\/automixiqequaliserconfig\/init","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQEqualiserConfig":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQEqualiserConfig","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQEqualiserConfig","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}],"role":"symbol","type":"topic","title":"AutomixIQEqualiserConfig","url":"\/documentation\/automixiq\/automixiqequaliserconfig"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQEqualiserConfig\/title","value":"AutomixIQEqualiserConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQEqualiserConfig\/fragments","value":[{"kind":"identifier","text":"AutomixIQEqualiserConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQEqualiserConfig\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQEqualiserConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}