{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(cm)initialiseWithConfig:streamingDelegate:statusDelegate:completion:","symbolKind":"method","title":"initialise(config:streamingDelegate:statusDelegate:completion:)","navigatorTitle":[{"text":"initialiseWithConfig:streamingDelegate:statusDelegate:completion:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"streamingDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","roleHeading":"Type Method","modules":[{"name":"AutomixIQ"}]},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)"],"generated":true,"anchor":"Initialization","title":"Initialization"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"abstract":[{"text":"Initialiser for AutomixIQ to work against any custom set of APIs.","type":"text"},{"text":" ","type":"text"},{"text":"This method takes in delegates to update the UI and feeds all data and metadata the AutomixIQ needs.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamingDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","text":"AutomixSDKStreamingDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AutomixIQ Configuration"}]}]},{"name":"streamingDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of feeding all data and metadata the AutomixIQ needs. See AutomixSDKStreamingDelegate.","type":"text"}]}]},{"name":"statusDelegate","content":[{"inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixSDKStatusObserverDelegate.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:streamingDelegate:statusDelegate:completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdk\/initialise(config:streamingdelegate:statusdelegate:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdk\/initialise(config:streamingdelegate:statusdelegate:completion:)"]}],"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"title":"AutomixSDKStatusObserverDelegate","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","type":"topic","abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDK"}],"url":"\/documentation\/automixiq\/automixsdk","type":"topic","role":"symbol","title":"AutomixSDK","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKConfig":{"role":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixsdkconfig","abstract":[],"navigatorTitle":[{"text":"AutomixSDKConfig","kind":"identifier"}],"title":"AutomixSDKConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKConfig"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:"}],"abstract":[{"type":"text","text":"Initialiser for AutomixIQ to work against a Tuned Global backend"},{"type":"text","text":" "},{"text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/initialise(config:tuneddelegate:statusdelegate:musiccachedelegate:completion:)","kind":"symbol","type":"topic","title":"initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"title":"AutomixSDKStreamingDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","role":"collection","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/initialise(config:streamingDelegate:statusDelegate:completion:)":{"navigatorTitle":[{"text":"initialiseWithConfig:streamingDelegate:statusDelegate:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialiser for AutomixIQ to work against any custom set of APIs."},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feeds all data and metadata the AutomixIQ needs."}],"url":"\/documentation\/automixiq\/automixsdk\/initialise(config:streamingdelegate:statusdelegate:completion:)","kind":"symbol","title":"initialise(config:streamingDelegate:statusDelegate:completion:)","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig","text":"AutomixSDKConfig"},{"text":", ","kind":"text"},{"text":"streamingDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:streamingDelegate:statusDelegate:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"initialiseWithConfig:streamingDelegate:statusDelegate:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"initialiseWithConfig:streamingDelegate:statusDelegate:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)"],"generated":true,"anchor":"Initialization","title":"Initialization"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"streamingDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","text":"id<AutomixSDKStreamingDelegate>"},{"kind":"text","text":") "},{"text":"streamingDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"statusDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<AutomixSDKStatusObserverDelegate>","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"statusDelegate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AutomixIQ Configuration"}]}]},{"name":"streamingDelegate","content":[{"inlineContent":[{"text":"The delegate in charge of feeding all data and metadata the AutomixIQ needs. See AutomixSDKStreamingDelegate.","type":"text"}],"type":"paragraph"}]},{"name":"statusDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixSDKStatusObserverDelegate.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]}],"name":"completion"}],"kind":"parameters"}},{"value":"AutomixSDKStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"op":"replace","value":"AutomixSDK","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments","op":"replace","value":[{"text":"AutomixSDK","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDK"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/title","value":"AutomixSDKConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/fragments","value":[{"text":"AutomixSDKConfig","kind":"identifier"}]},{"value":[{"text":"AutomixSDKConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/navigatorTitle"},{"value":"initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(config:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:","kind":"identifier"}]},{"value":"AutomixSDKStreamingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments","op":"replace","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(config:streamingDelegate:statusDelegate:completion:)\/title","value":"initialiseWithConfig:streamingDelegate:statusDelegate:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(config:streamingDelegate:statusDelegate:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"initialiseWithConfig:streamingDelegate:statusDelegate:completion:","kind":"identifier"}]}]}]}