{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/minEngineVersion","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"minEngineVersion","role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtape(py)minEngineVersion","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"minEngineVersion","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"minEngineVersion","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"SocialRadio"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkmixtape\/minengineversion"]},{"paths":["\/documentation\/socialradio\/automixsdkmixtape\/minengineversion"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The minimum version of the Pacemaker Engine that can play this mixtape"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minEngineVersion","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtape","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkmixtape","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape","abstract":[{"text":"AutomixSDKMixtape models a mixtape","type":"text"}],"role":"symbol","title":"AutomixSDKMixtape"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/minEngineVersion":{"role":"symbol","abstract":[{"type":"text","text":"The minimum version of the Pacemaker Engine that can play this mixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/minEngineVersion","kind":"symbol","title":"minEngineVersion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"minEngineVersion","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"minEngineVersion","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/automixsdkmixtape\/minengineversion"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"minEngineVersion"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"minEngineVersion","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"minEngineVersion","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/title","value":"AutomixSDKMixtape","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtape"}]},{"value":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1minEngineVersion\/title","value":"minEngineVersion","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1minEngineVersion\/fragments","op":"replace","value":[{"kind":"identifier","text":"minEngineVersion"}]}]}]}