{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig\/featureSetConfig","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"featureSetConfig","kind":"identifier"},{"kind":"text","text":": "},{"text":"RadioSDKFeatureSetConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKFeatureSetConfig"}],"navigatorTitle":[{"text":"featureSetConfig","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)RadioSDKConfig(py)featureSetConfig","symbolKind":"property","modules":[{"name":"SocialRadio"}],"title":"featureSetConfig"},"variants":[{"paths":["\/documentation\/socialradio\/radiosdkconfig\/featuresetconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/radiosdkconfig\/featuresetconfig"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"featureSetConfig"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKFeatureSetConfig","text":"RadioSDKFeatureSetConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKConfig/featureSetConfig":{"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"featureSetConfig"},{"kind":"text","text":": "},{"text":"RadioSDKFeatureSetConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKFeatureSetConfig"}],"title":"featureSetConfig","navigatorTitle":[{"kind":"identifier","text":"featureSetConfig"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig\/featureSetConfig","kind":"symbol","url":"\/documentation\/socialradio\/radiosdkconfig\/featuresetconfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKConfig":{"navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"title":"RadioSDKConfig","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKConfig"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKConfig","role":"symbol","url":"\/documentation\/socialradio\/radiosdkconfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKFeatureSetConfig":{"url":"\/documentation\/socialradio\/radiosdkfeaturesetconfig","navigatorTitle":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"kind":"symbol","type":"topic","title":"RadioSDKFeatureSetConfig","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"featureSetConfig","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"featureSetConfig","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)RadioSDKFeatureSetConfig","text":"RadioSDKFeatureSetConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"featureSetConfig","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"featureSetConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig~1featureSetConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig~1featureSetConfig\/fragments","value":[{"text":"featureSetConfig","kind":"identifier"}]},{"value":"RadioSDKConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKConfig\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDKConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/title","op":"replace","value":"RadioSDKFeatureSetConfig"},{"value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}]}]}]}