{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixRemixes","interfaceLanguage":"swift"},"abstract":[{"text":"The number of times this mixtape has been remixed","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixRemixes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixremixes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixremixes"]}],"metadata":{"externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioMixtapeCounters(py)mixRemixes","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"mixRemixes"}],"modules":[{"name":"SocialRadioLite"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixRemixes"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"mixRemixes","symbolKind":"property"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters/mixRemixes":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixRemixes","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"mixRemixes","abstract":[{"type":"text","text":"The number of times this mixtape has been remixed"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters\/mixRemixes","url":"\/documentation\/socialradiolite\/socialradiomixtapecounters\/mixremixes","navigatorTitle":[{"kind":"identifier","text":"mixRemixes"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters","abstract":[{"text":"SocialRadioMixtapeCounters models the set of counters for information about a mixtape","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","title":"SocialRadioMixtapeCounters","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"mixRemixes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"mixRemixes"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"mixRemixes","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixRemixes\/title","value":"mixRemixes","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters~1mixRemixes\/fragments","value":[{"kind":"identifier","text":"mixRemixes"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/title","value":"SocialRadioMixtapeCounters"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}