{"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStart","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplaystart"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplaystart"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType"]]},"metadata":{"externalID":"c:@M@AutomixIQ@E@AutomixIQPlaybackEventType@AutomixIQPlaybackEventTypeTrackPlayStart","modules":[{"name":"AutomixIQ"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayStart","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","title":"AutomixIQPlaybackEventType.trackPlayStart","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayStart","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlayStart":{"url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplaystart","abstract":[],"kind":"symbol","title":"AutomixIQPlaybackEventType.trackPlayStart","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayStart","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayStart","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType":{"navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqplaybackeventtype","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"title":"AutomixIQPlaybackEventType","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayStart","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStart"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayStart","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayStart\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayStart"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayStart\/fragments"},{"op":"replace","value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/fragments"},{"op":"replace","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/navigatorTitle"}]}]}