{"abstract":[{"type":"text","text":"Called by the AutomixIQ SDK when it needs tracks recommendations based on a set of identifiers"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkstreamingdelegate\/asyncgettrackrecommendations(identifiers:contextids:limit:completion:)"]},{"paths":["\/documentation\/socialradio\/automixsdkstreamingdelegate\/asyncgettrackrecommendations(identifiers:contextids:limit:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asyncGetTrackRecommendations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"contextIds","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"tracks","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKTrackModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel"},{"text":"]?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"identifiers","content":[{"type":"paragraph","inlineContent":[{"text":"Set of track identifiers to base the recommendations on","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Number of recommendations to get","type":"text"}],"type":"paragraph"}],"name":"limit"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}],"type":"paragraph"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate\/asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(pl)AutomixSDKStreamingDelegate(im)asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"asyncGetTrackRecommendations","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"contextIds","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tracks"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"required":true,"title":"asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)","modules":[{"name":"SocialRadio"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate":{"role":"symbol","type":"topic","title":"AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate","url":"\/documentation\/socialradio\/automixsdkstreamingdelegate","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKStreamingDelegate/asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKStreamingDelegate\/asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"asyncGetTrackRecommendations","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"contextIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"limit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tracks"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel","kind":"typeIdentifier"},{"kind":"text","text":"]?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"title":"asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)","url":"\/documentation\/socialradio\/automixsdkstreamingdelegate\/asyncgettrackrecommendations(identifiers:contextids:limit:completion:)","abstract":[{"type":"text","text":"Called by the AutomixIQ SDK when it needs tracks recommendations based on a set of identifiers"}],"navigatorTitle":[{"text":"asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTrackModel":{"abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTrackModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdktrackmodel","title":"AutomixSDKTrackModel","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"asyncGetTrackRecommendationsWithIdentifiers:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"identifiers","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"contextIds:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"contextIds","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"limit:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"limit"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<AutomixSDKTrackModel *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set of track identifiers to base the recommendations on"}]}],"name":"identifiers"},{"name":"limit","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Number of recommendations to get"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}],"type":"paragraph"}],"name":"completion"}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate"},{"value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}]},{"op":"replace","value":"asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate~1asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKStreamingDelegate~1asyncGetTrackRecommendations(identifiers:contextIds:limit:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asyncGetTrackRecommendationsWithIdentifiers:contextIds:limit:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/fragments","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKTrackModel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}