{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogDescriptionTextColor","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogDescriptionTextColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/dialogdescriptiontextcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/dialogdescriptiontextcolor"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogDescriptionTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"modules":[{"name":"SocialRadio"}],"symbolKind":"property","navigatorTitle":[{"text":"dialogDescriptionTextColor","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig(py)dialogDescriptionTextColor","role":"symbol","title":"dialogDescriptionTextColor"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogDescriptionTextColor":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dialogDescriptionTextColor"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogDescriptionTextColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogDescriptionTextColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogdescriptiontextcolor","role":"symbol","type":"topic","title":"dialogDescriptionTextColor"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKUIConfig"}],"abstract":[],"title":"RadioSDKUIConfig","role":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"dialogDescriptionTextColor","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"dialogDescriptionTextColor"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"text":"dialogDescriptionTextColor","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogDescriptionTextColor\/title","value":"dialogDescriptionTextColor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogDescriptionTextColor\/fragments","value":[{"text":"dialogDescriptionTextColor","kind":"identifier"}]},{"op":"replace","value":"RadioSDKUIConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle","op":"replace","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]}]}]}