{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig(py)dialogSecondaryButtonBorderColor","title":"dialogSecondaryButtonBorderColor","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonBorderColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"dialogSecondaryButtonBorderColor","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonBorderColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]}]}],"variants":[{"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonbordercolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonbordercolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorderColor"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"]]},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKUIConfig"}],"abstract":[],"title":"RadioSDKUIConfig","role":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogSecondaryButtonBorderColor":{"abstract":[],"title":"dialogSecondaryButtonBorderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonBorderColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"text":"dialogSecondaryButtonBorderColor","kind":"identifier"}],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonbordercolor","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonBorderColor","role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"dialogSecondaryButtonBorderColor"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"dialogSecondaryButtonBorderColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"text":"dialogSecondaryButtonBorderColor","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"RadioSDKUIConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title"},{"value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle","op":"replace","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBorderColor\/title","value":"dialogSecondaryButtonBorderColor"},{"value":[{"kind":"identifier","text":"dialogSecondaryButtonBorderColor"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonBorderColor\/fragments","op":"replace"}]}]}