{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonfontbold"]},{"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonfontbold"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonFontBold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig(py)dialogSecondaryButtonFontBold","title":"dialogSecondaryButtonFontBold","navigatorTitle":[{"text":"dialogSecondaryButtonFontBold","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonFontBold"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogSecondaryButtonFontBold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/dialogSecondaryButtonFontBold":{"abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonFontBold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/dialogSecondaryButtonFontBold","title":"dialogSecondaryButtonFontBold","url":"\/documentation\/socialradio\/radiosdkuiconfig\/dialogsecondarybuttonfontbold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dialogSecondaryButtonFontBold"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKUIConfig"}],"abstract":[],"title":"RadioSDKUIConfig","role":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dialogSecondaryButtonFontBold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"dialogSecondaryButtonFontBold","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonFontBold","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonFontBold\/title","op":"replace","value":"dialogSecondaryButtonFontBold"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1dialogSecondaryButtonFontBold\/fragments","op":"replace","value":[{"text":"dialogSecondaryButtonFontBold","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title","op":"replace","value":"RadioSDKUIConfig"},{"op":"replace","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}