{"metadata":{"title":"init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","navigatorTitle":[{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"fontFamily","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"titleFontSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeHuge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"radioUIFontSizeLarge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeRegular","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeSmall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeTiny"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeMatchMachine","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textFieldFontBold"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"textFieldBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"textFieldBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"textFieldTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldPlaceholderTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogTitleFontBold"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"dialogTitleTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"text":"dialogDescriptionFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogDescriptionTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorderRadius"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBorder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogPrimaryButtonBorderColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonFontBold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorderColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig(im)initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","modules":[{"name":"SocialRadio"}],"roleHeading":"Initializer","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"fontFamily","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" = \"HelveticaNeue\", ","kind":"text"},{"kind":"externalParam","text":"titleFontSize"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = 14, ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeHuge"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 40, ","kind":"text"},{"text":"radioUIFontSizeLarge","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 16, ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeRegular"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":" = 14, "},{"text":"radioUIFontSizeSmall","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 12, ","kind":"text"},{"text":"radioUIFontSizeTiny","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" = 10, "},{"text":"radioUIFontSizeMatchMachine","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" = 20, "},{"text":"textFieldFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"textFieldBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = UIColor.init(white: 0.2, alpha: 1), "},{"kind":"externalParam","text":"textFieldBorderRadius"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":" = 5, ","kind":"text"},{"text":"textFieldTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = UIColor.white, "},{"text":"textFieldPlaceholderTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" = UIColor.black, ","kind":"text"},{"text":"dialogTitleFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"dialogTitleTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" = UIColor.white, ","kind":"text"},{"text":"dialogDescriptionFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"dialogDescriptionTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = UIColor.white, "},{"kind":"externalParam","text":"dialogPrimaryButtonFontBold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"dialogPrimaryButtonBackgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" = UIColor.clear, ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorderRadius"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":" = -1, "},{"kind":"externalParam","text":"dialogPrimaryButtonTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = UIColor.white, "},{"kind":"externalParam","text":"dialogPrimaryButtonBorder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true, "},{"text":"dialogPrimaryButtonBorderColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" = UIColor.white, ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonFontBold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"dialogSecondaryButtonBackgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" = UIColor.clear, "},{"text":"dialogSecondaryButtonBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":" = -1, ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = UIColor.white, "},{"text":"dialogSecondaryButtonBorder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"dialogSecondaryButtonBorderColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = UIColor.clear)","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)"},"variants":[{"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/init(fontfamily:titlefontsize:radiouifontsizehuge:radiouifontsizelarge:radiouifontsizeregular:radiouifontsizesmall:radiouifontsizetiny:radiouifontsizematchmachine:textfieldfontbold:textfieldbackgroundcolor:textfieldborderradius:textfieldtex-7khup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/init(fontfamily:titlefontsize:radiouifontsizehuge:radiouifontsizelarge:radiouifontsizeregular:radiouifontsizesmall:radiouifontsizetiny:radiouifontsizematchmachine:textfieldfontbold:textfieldbackgroundcolor:textfieldborderradius:textfieldtex-7khup"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)":{"kind":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig\/init(fontfamily:titlefontsize:radiouifontsizehuge:radiouifontsizelarge:radiouifontsizeregular:radiouifontsizesmall:radiouifontsizetiny:radiouifontsizematchmachine:textfieldfontbold:textfieldbackgroundcolor:textfieldborderradius:textfieldtex-7khup","navigatorTitle":[{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","title":"init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fontFamily"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"titleFontSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeHuge","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeLarge","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeRegular"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"radioUIFontSizeSmall","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeTiny"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeMatchMachine"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"textFieldFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"textFieldBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldBorderRadius"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"textFieldTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldPlaceholderTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogTitleFontBold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogTitleTextColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogDescriptionFontBold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogDescriptionTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonFontBold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBackgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogPrimaryButtonTextColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBorder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogPrimaryButtonBorderColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKUIConfig"}],"abstract":[],"title":"RadioSDKUIConfig","role":"symbol","url":"\/documentation\/socialradio\/radiosdkuiconfig","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithFontFamily:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fontFamily"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleFontSize:"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"titleFontSize","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeHuge:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"text":"radioUIFontSizeHuge","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeLarge:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"radioUIFontSizeLarge"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeRegular:"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"radioUIFontSizeRegular","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeSmall:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"radioUIFontSizeSmall","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeTiny:"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"radioUIFontSizeTiny"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeMatchMachine:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"radioUIFontSizeMatchMachine","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textFieldFontBold:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"textFieldFontBold","kind":"internalParam"},{"kind":"text","text":" "},{"text":"textFieldBackgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textFieldBackgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldBorderRadius:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"textFieldBorderRadius"},{"text":" ","kind":"text"},{"text":"textFieldTextColor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"textFieldTextColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"textFieldPlaceholderTextColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textFieldPlaceholderTextColor"},{"kind":"text","text":" "},{"text":"dialogTitleFontBold:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"dialogTitleFontBold","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogTitleTextColor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" *) ","kind":"text"},{"text":"dialogTitleTextColor","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dialogDescriptionFontBold:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dialogDescriptionFontBold"},{"text":" ","kind":"text"},{"text":"dialogDescriptionTextColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" *) ","kind":"text"},{"text":"dialogDescriptionTextColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogPrimaryButtonFontBold:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"dialogPrimaryButtonFontBold"},{"kind":"text","text":" "},{"text":"dialogPrimaryButtonBackgroundColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dialogPrimaryButtonBackgroundColor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBorderRadius:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dialogPrimaryButtonBorderRadius"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonTextColor:"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"text":"dialogPrimaryButtonTextColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogPrimaryButtonBorder:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dialogPrimaryButtonBorder"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonBorderColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dialogPrimaryButtonBorderColor"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonFontBold:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"dialogSecondaryButtonFontBold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBackgroundColor:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dialogSecondaryButtonBackgroundColor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogSecondaryButtonBorderRadius:"},{"text":"(","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"dialogSecondaryButtonBorderRadius"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonTextColor:"},{"kind":"text","text":"("},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"dialogSecondaryButtonTextColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonBorder:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dialogSecondaryButtonBorder"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonBorderColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"dialogSecondaryButtonBorderColor","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/title","op":"replace","value":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1init(fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title","op":"replace","value":"RadioSDKUIConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}