{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ is streaming."}],"type":"paragraph"}],"name":"trackId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track download progress, between 0 (none) and 1 (complete)."}]}],"name":"progress"}],"kind":"parameters"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"modules":[{"name":"SocialRadio"}],"required":true,"role":"symbol","externalID":"c:@M@SocialRadio@objc(pl)AutomixIQMusicCacheDelegate(im)trackDownloadProgressChangedWithTrackId:progress:","symbolKind":"method","title":"trackDownloadProgressChanged(trackId:progress:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadProgressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":")"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate"]]},"variants":[{"paths":["\/documentation\/socialradio\/automixiqmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate/trackDownloadProgressChanged(trackId:progress:)":{"title":"trackDownloadProgressChanged(trackId:progress:)","kind":"symbol","navigatorTitle":[{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}],"required":true,"abstract":[{"text":"Called by AutomixIQ when a track download progress has changed.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/automixiqmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQMusicCacheDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQMusicCacheDelegate","role":"symbol","title":"AutomixIQMusicCacheDelegate","abstract":[{"text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqmusiccachedelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"trackDownloadProgressChangedWithTrackId:progress:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackId"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"progress"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The id of the track that AutomixIQ is streaming.","type":"text"}]}],"name":"trackId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track download progress, between 0 (none) and 1 (complete)."}]}],"name":"progress"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title","value":"trackDownloadProgressChangedWithTrackId:progress:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/title","value":"AutomixIQMusicCacheDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/fragments","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQMusicCacheDelegate\/navigatorTitle","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}