{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig\/allowVoiceOver","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/radiosdkfeaturesetconfig\/allowvoiceover"]},{"paths":["\/documentation\/socialradio\/radiosdkfeaturesetconfig\/allowvoiceover"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"allowVoiceOver","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"allowVoiceOver","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowVoiceOver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:@M@SocialRadio@objc(cs)RadioSDKFeatureSetConfig(py)allowVoiceOver","modules":[{"name":"SocialRadio"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowVoiceOver"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKFeatureSetConfig":{"url":"\/documentation\/socialradio\/radiosdkfeaturesetconfig","navigatorTitle":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"kind":"symbol","type":"topic","title":"RadioSDKFeatureSetConfig","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKFeatureSetConfig/allowVoiceOver":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig\/allowVoiceOver","role":"symbol","title":"allowVoiceOver","type":"topic","url":"\/documentation\/socialradio\/radiosdkfeaturesetconfig\/allowvoiceover","navigatorTitle":[{"text":"allowVoiceOver","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowVoiceOver","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"allowVoiceOver","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"allowVoiceOver","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"allowVoiceOver","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/title","op":"replace","value":"RadioSDKFeatureSetConfig"},{"op":"replace","value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/fragments"},{"value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig~1allowVoiceOver\/title","op":"replace","value":"allowVoiceOver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig~1allowVoiceOver\/fragments","value":[{"kind":"identifier","text":"allowVoiceOver"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}