{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ"]]},"abstract":[{"type":"text","text":"Initialiser for AutomixIQ to work against any custom set of APIs."},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feeds all data and metadata the AutomixIQ needs."}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","text":"AutomixIQConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"automixIQStreamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate","text":"AutomixIQStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","symbolKind":"method","title":"initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQ(cm)initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:","roleHeading":"Type Method","navigatorTitle":[{"text":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","kind":"typeIdentifier","text":"AutomixIQConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStreamingDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate","kind":"typeIdentifier","text":"AutomixIQStreamingDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStatusDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixIQStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The AutomixIQ Configuration"}]}]},{"name":"automixIQStreamingDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of feeding all data and metadata the AutomixIQ needs. See AutomixIQStreamingDelegate."}]}]},{"name":"automixIQStatusDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixIQStatusObserverDelegate."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}]}]}],"type":"unorderedList"}]}]}],"kind":"symbol","sections":[],"seeAlsoSections":[{"anchor":"Initialization","title":"Initialization","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiq\/initialise(config:automixiqstreamingdelegate:automixiqstatusdelegate:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiq\/initialise(config:automixiqstreamingdelegate:automixiqstatusdelegate:completion:)"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQConfig","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AutomixIQConfig","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqconfig","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","title":"AutomixIQConfig"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"title":"AutomixIQStatusObserverDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"type":"topic","navigatorTitle":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate","role":"symbol","abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig"},{"text":", ","kind":"text"},{"text":"tunedRestDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq\/initialise(config:tunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)","role":"symbol","abstract":[{"type":"text","text":"Initialiser for AutomixIQ to work against a Tuned Global backend"},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","title":"initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"text":"AutomixIQConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig"},{"text":", ","kind":"text"},{"text":"automixIQStreamingDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate","text":"AutomixIQStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStatusDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[{"text":"Initialiser for AutomixIQ to work against any custom set of APIs.","type":"text"},{"text":" ","type":"text"},{"text":"This method takes in delegates to update the UI and feeds all data and metadata the AutomixIQ needs.","type":"text"}],"role":"symbol","type":"topic","title":"initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)","kind":"symbol","url":"\/documentation\/automixiq\/automixiq\/initialise(config:automixiqstreamingdelegate:automixiqstatusdelegate:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)","navigatorTitle":[{"text":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQ","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiq","role":"symbol","abstract":[{"type":"text","text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"kind":"symbol","title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate","url":"\/documentation\/automixiq\/automixiqstreamingdelegate","kind":"symbol","navigatorTitle":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"type":"topic","title":"AutomixIQStreamingDelegate","abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"title":"Initialization","anchor":"Initialization","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"initialiseWithConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","text":"AutomixIQConfig"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixIQStreamingDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate","text":"id<AutomixIQStreamingDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"automixIQStreamingDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixIQStatusDelegate:"},{"kind":"text","text":"("},{"text":"id<AutomixIQStatusObserverDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"automixIQStatusDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"config","content":[{"inlineContent":[{"text":"The AutomixIQ Configuration","type":"text"}],"type":"paragraph"}]},{"name":"automixIQStreamingDelegate","content":[{"inlineContent":[{"text":"The delegate in charge of feeding all data and metadata the AutomixIQ needs. See AutomixIQStreamingDelegate.","type":"text"}],"type":"paragraph"}]},{"name":"automixIQStatusDelegate","content":[{"inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixIQStatusObserverDelegate.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}]}]}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title","value":"AutomixIQConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments","value":[{"text":"AutomixIQConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle","value":[{"text":"AutomixIQConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title","op":"replace","value":"AutomixIQStatusObserverDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments","op":"replace","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)\/title","op":"replace","value":"initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"initialiseWithConfig:tunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)\/title","op":"replace","value":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1initialise(config:automixIQStreamingDelegate:automixIQStatusDelegate:completion:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"initialiseWithConfig:automixIQStreamingDelegate:automixIQStatusDelegate:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/title","op":"replace","value":"AutomixIQ"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/fragments","op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/title","op":"replace","value":"AutomixIQStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/fragments","op":"replace","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}