{"abstract":[{"type":"text","text":"The index the right transition starts"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightTransitionStartIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","title":"rightTransitionStartIndex","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTransitionStartIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"rightTransitionStartIndex"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel(py)rightTransitionStartIndex","symbolKind":"property","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/rightTransitionStartIndex","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/socialradio\/automixiqwaveformmodel\/righttransitionstartindex"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqwaveformmodel\/righttransitionstartindex"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel/rightTransitionStartIndex":{"abstract":[{"type":"text","text":"The index the right transition starts"}],"navigatorTitle":[{"text":"rightTransitionStartIndex","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/rightTransitionStartIndex","title":"rightTransitionStartIndex","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightTransitionStartIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/socialradio\/automixiqwaveformmodel\/righttransitionstartindex","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"url":"\/documentation\/socialradio\/automixiqwaveformmodel","title":"AutomixIQWaveformModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQWaveformModel models the waveform of a track."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rightTransitionStartIndex"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rightTransitionStartIndex"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTransitionStartIndex"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel~1rightTransitionStartIndex\/title","value":"rightTransitionStartIndex"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel~1rightTransitionStartIndex\/fragments","value":[{"text":"rightTransitionStartIndex","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","op":"replace","value":"AutomixIQWaveformModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","op":"replace","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQWaveformModel"}]}]}]}