{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"statusObserverDelegate","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradioobjc\/add(_:)"]}],"metadata":{"modules":[{"name":"SocialRadio"}],"title":"add(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"add","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SocialRadioObjC(im)addStatusObserverDelegate:","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/add(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC":{"title":"SocialRadioObjC","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioObjC"}],"url":"\/documentation\/socialradio\/socialradioobjc","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioObjC"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"kind":"symbol","title":"SocialRadioStatusObserverDelegate","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC/add(_:)":{"abstract":[],"type":"topic","url":"\/documentation\/socialradio\/socialradioobjc\/add(_:)","title":"add(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/add(_:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","value":"SocialRadioStatusObserverDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}