{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMusicCacheDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"musicCacheDelegate"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate","kind":"typeIdentifier","text":"AutomixIQMusicCacheDelegate"},{"kind":"text","text":")?)"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMusicCacheDelegate","kind":"identifier"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","text":"AutomixIQMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate"},{"kind":"text","text":")?)"}],"modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Method","title":"setMusicCacheDelegate(_:)","externalID":"c:objc(cs)AutomixIQObjC(im)setMusicCacheDelegate:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/automixiq\/automixiqobjc\/setmusiccachedelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/setMusicCacheDelegate(_:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC":{"role":"symbol","url":"\/documentation\/automixiq\/automixiqobjc","title":"AutomixIQObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQObjC"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC","abstract":[],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate":{"role":"symbol","url":"\/documentation\/automixiq\/automixiqmusiccachedelegate","title":"AutomixIQMusicCacheDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","abstract":[{"type":"text","text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","kind":"symbol","title":"AutomixIQ","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC/setMusicCacheDelegate(_:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMusicCacheDelegate"},{"kind":"text","text":"((any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQMusicCacheDelegate","text":"AutomixIQMusicCacheDelegate"},{"kind":"text","text":")?)"}],"title":"setMusicCacheDelegate(_:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/setMusicCacheDelegate(_:)","url":"\/documentation\/automixiq\/automixiqobjc\/setmusiccachedelegate(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AutomixIQMusicCacheDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/fragments","op":"replace"},{"value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/navigatorTitle","op":"replace"}]}]}