{"sections":[],"variants":[{"paths":["\/documentation\/automixiq\/automixsdkplaylistoperationtype\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperationType\/init(rawValue:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperationType"]]},"kind":"symbol","metadata":{"roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"role":"symbol","title":"init(rawValue:)","externalID":"s:9AutomixIQ0A24SDKPlaylistOperationTypeO8rawValueACSgSi_tcfc"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperationType":{"abstract":[],"title":"AutomixSDKPlaylistOperationType","url":"\/documentation\/automixiq\/automixsdkplaylistoperationtype","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperationType","role":"symbol","navigatorTitle":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperationType/init(rawValue:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperationType\/init(rawValue:)","type":"topic","url":"\/documentation\/automixiq\/automixsdkplaylistoperationtype\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","abstract":[],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"AutomixSDKPlaylistOperationType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperationType\/title"},{"value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperationType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperationType\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}