{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment"]]},"metadata":{"title":"commentTrackIndexX10","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioComment(py)commentTrackIndexX10","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commentTrackIndexX10"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"commentTrackIndexX10"}],"roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiocomment\/commenttrackindexx10"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiocomment\/commenttrackindexx10"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commentTrackIndexX10"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment\/commentTrackIndexX10"},"abstract":[{"text":"The track index that was playing when the comment was made, x10 for some reason","type":"text"}],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment/commentTrackIndexX10":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"commentTrackIndexX10"}],"title":"commentTrackIndexX10","abstract":[{"type":"text","text":"The track index that was playing when the comment was made, x10 for some reason"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiocomment\/commenttrackindexx10","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment\/commentTrackIndexX10","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commentTrackIndexX10"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment":{"abstract":[{"type":"text","text":"SocialRadioComment models a comment"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioComment"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","title":"SocialRadioComment","role":"symbol","url":"\/documentation\/socialradio\/socialradiocomment","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioComment"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"commentTrackIndexX10","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"commentTrackIndexX10","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"commentTrackIndexX10","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"commentTrackIndexX10","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment~1commentTrackIndexX10\/title","op":"replace"},{"value":[{"text":"commentTrackIndexX10","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment~1commentTrackIndexX10\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/title","value":"SocialRadioComment"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/fragments","value":[{"kind":"identifier","text":"SocialRadioComment"}]},{"value":[{"text":"SocialRadioComment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/navigatorTitle"}]}]}