{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/socialradiocomment\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioComment(im)init","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment\/init","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment/init":{"url":"\/documentation\/socialradio\/socialradiocomment\/init","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment\/init","abstract":[],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment":{"abstract":[{"type":"text","text":"SocialRadioComment models a comment"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioComment"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","title":"SocialRadioComment","role":"symbol","url":"\/documentation\/socialradio\/socialradiocomment","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioComment"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"patch":[{"op":"replace","value":"SocialRadioComment","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/title"},{"op":"replace","value":[{"text":"SocialRadioComment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/fragments"},{"op":"replace","value":[{"text":"SocialRadioComment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}