{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/dialogSecondaryButtonBorderRadius","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/socialradio\/socialradiouiconfig\/dialogsecondarybuttonborderradius"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiouiconfig\/dialogsecondarybuttonborderradius"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"symbol","title":"dialogSecondaryButtonBorderRadius","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioUIConfig(py)dialogSecondaryButtonBorderRadius","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonBorderRadius"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig/dialogSecondaryButtonBorderRadius":{"abstract":[],"url":"\/documentation\/socialradio\/socialradiouiconfig\/dialogsecondarybuttonborderradius","title":"dialogSecondaryButtonBorderRadius","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/dialogSecondaryButtonBorderRadius","navigatorTitle":[{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig":{"title":"SocialRadioUIConfig","url":"\/documentation\/socialradio\/socialradiouiconfig","abstract":[{"text":"Social Radio UI options","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig","navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","url":"\/documentation\/socialradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"dialogSecondaryButtonBorderRadius","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"dialogSecondaryButtonBorderRadius","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1dialogSecondaryButtonBorderRadius\/title","op":"replace"},{"value":[{"text":"dialogSecondaryButtonBorderRadius","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1dialogSecondaryButtonBorderRadius\/fragments","op":"replace"},{"value":"SocialRadioUIConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/navigatorTitle","op":"replace"}]}]}