{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/errorcode"]}],"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"externalID":"c:@M@SocialRadio@E@ErrorCode","symbolKind":"enum","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"role":"symbol","title":"ErrorCode"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to use the SDK from any thread not main"}],"type":"paragraph"}],"name":"notMainThread"},{"name":"sdkNotInitialised","content":[{"inlineContent":[{"text":"Thrown when you attempt to use the SDK prior to initialising it","type":"text"}],"type":"paragraph"}]},{"name":"sdkNotOn","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to use playback controls when AutomixIQ is not on"}]}]},{"name":"sdkAlreadyOn","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to turn on AutomixIQ but it is already on"}]}]},{"name":"loadTracksEmptyPlaylist","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to load an empty playlist"}]}]},{"name":"loadTracksOutOfBounds","content":[{"inlineContent":[{"type":"text","text":""}],"type":"paragraph"}]},{"name":"addTrackPlaylistDoesNotExist","content":[{"inlineContent":[{"text":"","type":"text"}],"type":"paragraph"}]},{"name":"addTrackOutOfBounds","content":[{"inlineContent":[{"text":"Thrown when you attempt to insert a track at a position outside the bounds of the loaded playlist","type":"text"}],"type":"paragraph"}]},{"name":"addTrackNoMetadata","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when the metadata for a track you are trying to load is not available and could not be downloaded","type":"text"}]}]},{"name":"addTrackInternalError","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when AutomixIQ fails internally (not user error)","type":"text"}]}]},{"name":"removeTrackOutOfBounds","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to remove a track at a position outside the bounds of the loaded playlist"}],"type":"paragraph"}]},{"name":"playAlreadyPlaying","content":[{"inlineContent":[{"text":"Thrown when you attempt to play but AutomixIQ is already playing","type":"text"}],"type":"paragraph"}]},{"name":"pauseAlreadyPaused","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to pause but AutomixIQ is already paused"}],"type":"paragraph"}]},{"name":"previousNoTrackAvailable","content":[{"inlineContent":[{"text":"Thrown when you attempt to go to the previous track but AutomixIQ is already on the first in the playlist and “Repeat” is off","type":"text"}],"type":"paragraph"}]},{"name":"nextNoTrackAvailable","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to go to the next track but AutomixIQ is already on the last in the playlist and “Repeat” is off","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Thrown when you attempt to go to the start of a track but the playlist is empty","type":"text"}],"type":"paragraph"}],"name":"backNoTrackAvailable"},{"name":"seekNoTrackAvailable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to seek to a track but the playlist is empty or the index is out of bounds of the playlist"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to seek within a track but the playlist is empty or the track is not yet loaded","type":"text"}]}],"name":"seekNoCurrentTrack"},{"name":"reorderMissingTrack","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to move a track that is not on the loaded playlist","type":"text"}]}]},{"name":"playToEndMissingTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to select a track to be played until the end but that track is not on the loaded playlist"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to move a track at a position outside the bounds of the loaded playlist","type":"text"}]}],"name":"moveTrackOutOfBounds"},{"name":"startLoopingNoLoopingTrack","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to stop looping a track but that track is not on the loaded playlist"}]}]},{"name":"stopLoopingNoLoopingTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to loop a track but that track is not on the loaded playlist"}],"type":"paragraph"}]},{"name":"unimplemented","content":[{"inlineContent":[{"text":"Thrown when you attempt to use an unimplemented method of the SDK","type":"text"}],"type":"paragraph"}]},{"name":"cancelled","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when an action you previously issued to AutomixIQ is cancelled due to another user initialed action that overrides it","type":"text"}]}]},{"name":"onAlreadyTurningOn","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ on while it is already turning on"}]}]},{"name":"onWhileTurningOff","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ on while it is already turning off"}],"type":"paragraph"}]},{"name":"offAlreadyTurningOff","content":[{"inlineContent":[{"text":"Thrown when you attempt to turn AutomixIQ off while it is already turning off","type":"text"}],"type":"paragraph"}]},{"name":"offWhileTurningOn","content":[{"inlineContent":[{"text":"Thrown when you attempt to turn AutomixIQ off while it is already turning on","type":"text"}],"type":"paragraph"}]},{"name":"cannotCreateChannelLayout","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when AutomixIQ fails to set up the channel layout","type":"text"}]}]},{"name":"cannotCreateInputBuffer","content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the input buffer"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when AutomixIQ fails to set up the AVAudioSession","type":"text"}]}],"name":"cannotSetupAVAudioSession"},{"name":"cannotStartAudioEngine","content":[{"inlineContent":[{"text":"Thrown when AutomixIQ fails to start the audio engine","type":"text"}],"type":"paragraph"}]},{"name":"cannotRestoreAudioSession","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to restore the audio session to the state it found it when you turned it on"}]}]},{"name":"failedToStop","content":[{"inlineContent":[{"text":"Thrown when AutomixIQ is unable to be stopped","type":"text"}],"type":"paragraph"}]},{"name":"cannotLoadExplicitLyricsTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to load an explicit track but the setting to filter out explicit tracks is on"}],"type":"paragraph"}]},{"name":"cannotDownloadAd","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you fail to download the ad from the url provided"}]}]},{"content":[{"inlineContent":[{"text":"Thrown when you attempt to do something you cannot do while playing an ad","type":"text"}],"type":"paragraph"}],"name":"cannotInterruptAd"}]},{"mentions":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Errors-article"],"kind":"mentions"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cancelled","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotDownloadAd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotInterruptAd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/didNotAddAdIndexPassedAlready","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/failedToStop","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/notMainThread","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/unable_to_load_mix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/unimplemented"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH","doc:\/\/org.cocoapods.SocialRadio\/SY"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"seeAlsoSections":[{"title":"Errors","anchor":"Errors","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Errors-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/sdkError(code:)"],"generated":true}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/addTrackOutOfBounds":{"url":"\/documentation\/socialradio\/errorcode\/addtrackoutofbounds","kind":"symbol","type":"topic","abstract":[],"title":"ErrorCode.addTrackOutOfBounds","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackOutOfBounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackOutOfBounds","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ErrorCodeAddTrackOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/sdkAlreadyInitialised":{"url":"\/documentation\/socialradio\/errorcode\/sdkalreadyinitialised","kind":"symbol","type":"topic","abstract":[],"title":"ErrorCode.sdkAlreadyInitialised","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkAlreadyInitialised","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkAlreadyInitialised","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ErrorCodeSdkAlreadyInitialised","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/unimplemented":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unimplemented"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[],"title":"ErrorCode.unimplemented","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/unimplemented","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeUnimplemented"}],"url":"\/documentation\/socialradio\/errorcode\/unimplemented"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/playToEndMissingTrack":{"url":"\/documentation\/socialradio\/errorcode\/playtoendmissingtrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playToEndMissingTrack"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePlayToEndMissingTrack"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/playToEndMissingTrack","title":"ErrorCode.playToEndMissingTrack","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/unable_to_load_mix":{"title":"ErrorCode.unable_to_load_mix","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unable_to_load_mix","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/errorcode\/unable_to_load_mix","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/unable_to_load_mix","navigatorTitle":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/stopLoopingNoLoopingTrack":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLoopingNoLoopingTrack"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[],"title":"ErrorCode.stopLoopingNoLoopingTrack","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/stopLoopingNoLoopingTrack","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeStopLoopingNoLoopingTrack"}],"url":"\/documentation\/socialradio\/errorcode\/stoploopingnoloopingtrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/seekNoCurrentTrack":{"title":"ErrorCode.seekNoCurrentTrack","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekNoCurrentTrack","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/errorcode\/seeknocurrenttrack","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/seekNoCurrentTrack","navigatorTitle":[{"text":"ErrorCodeSeekNoCurrentTrack","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/didNotAddAdIndexPassedAlready":{"type":"topic","title":"ErrorCode.didNotAddAdIndexPassedAlready","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeDidNotAddAdIndexPassedAlready"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/didNotAddAdIndexPassedAlready","url":"\/documentation\/socialradio\/errorcode\/didnotaddadindexpassedalready","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didNotAddAdIndexPassedAlready","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotStartAudioEngine":{"url":"\/documentation\/socialradio\/errorcode\/cannotstartaudioengine","kind":"symbol","type":"topic","abstract":[],"title":"ErrorCode.cannotStartAudioEngine","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotStartAudioEngine","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotStartAudioEngine"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotStartAudioEngine"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/moveTrackOutOfBounds":{"title":"ErrorCode.moveTrackOutOfBounds","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveTrackOutOfBounds","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/errorcode\/movetrackoutofbounds","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/moveTrackOutOfBounds","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeMoveTrackOutOfBounds"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/noInternetAvailableTooLongOffline":{"url":"\/documentation\/socialradio\/errorcode\/nointernetavailabletoolongoffline","kind":"symbol","type":"topic","abstract":[],"title":"ErrorCode.noInternetAvailableTooLongOffline","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailableTooLongOffline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noInternetAvailableTooLongOffline"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailableTooLongOffline"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotLoadExplicitLyricsTrack":{"title":"ErrorCode.cannotLoadExplicitLyricsTrack","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/errorcode\/cannotloadexplicitlyricstrack","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotLoadExplicitLyricsTrack","type":"topic","navigatorTitle":[{"text":"ErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/sdkError(code:)":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/socialradio\/sdkerror(code:)","role":"symbol","title":"sdkError(code:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@E@ErrorCode","kind":"typeIdentifier","text":"ErrorCode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/sdkError(code:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/init(rawValue:)","url":"\/documentation\/socialradio\/errorcode\/init(rawvalue:)","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/addTrackInternalError":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackInternalError"}],"role":"symbol","type":"topic","title":"ErrorCode.addTrackInternalError","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackInternalError","navigatorTitle":[{"text":"ErrorCodeAddTrackInternalError","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode\/addtrackinternalerror"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/Equatable-Implementations":{"url":"\/documentation\/socialradio\/errorcode\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","abstract":[],"kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"title":"ErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","kind":"symbol","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/socialradio\/errorcode"},"doc://org.cocoapods.SocialRadio/SY":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/sdkNotOn":{"title":"ErrorCode.sdkNotOn","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotOn","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotOn","type":"topic","url":"\/documentation\/socialradio\/errorcode\/sdknoton","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkNotOn"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/addTrackPlaylistDoesNotExist":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/socialradio\/errorcode\/addtrackplaylistdoesnotexist","role":"symbol","title":"ErrorCode.addTrackPlaylistDoesNotExist","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackPlaylistDoesNotExist"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/sdkAlreadyOn":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkAlreadyOn","kind":"identifier"}],"role":"symbol","type":"topic","title":"ErrorCode.sdkAlreadyOn","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkAlreadyOn","navigatorTitle":[{"text":"ErrorCodeSdkAlreadyOn","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode\/sdkalreadyon"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cancelled":{"url":"\/documentation\/socialradio\/errorcode\/cancelled","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeCancelled","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cancelled","type":"topic","title":"ErrorCode.cancelled","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/onWhileTurningOff":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeOnWhileTurningOff"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/onWhileTurningOff","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onWhileTurningOff"}],"type":"topic","url":"\/documentation\/socialradio\/errorcode\/onwhileturningoff","title":"ErrorCode.onWhileTurningOff"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/backNoTrackAvailable":{"url":"\/documentation\/socialradio\/errorcode\/backnotrackavailable","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/backNoTrackAvailable","title":"ErrorCode.backNoTrackAvailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backNoTrackAvailable","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/startLoopingNoLoopingTrack":{"url":"\/documentation\/socialradio\/errorcode\/startloopingnoloopingtrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"startLoopingNoLoopingTrack","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/startLoopingNoLoopingTrack","title":"ErrorCode.startLoopingNoLoopingTrack","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/noInternetAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailable","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","title":"ErrorCode.noInternetAvailable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailable","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailable"}],"url":"\/documentation\/socialradio\/errorcode\/nointernetavailable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/playToEndMixEnd":{"title":"ErrorCode.playToEndMixEnd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playToEndMixEnd"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePlayToEndMixEnd"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/playToEndMixEnd","kind":"symbol","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/socialradio\/errorcode\/playtoendmixend"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/sdkNotInitialisedVersionNoLongerSupported":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","url":"\/documentation\/socialradio\/errorcode\/sdknotinitialisedversionnolongersupported","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"title":"ErrorCode.sdkNotInitialisedVersionNoLongerSupported"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotCreateChannelLayout":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotCreateChannelLayout"}],"role":"symbol","type":"topic","title":"ErrorCode.cannotCreateChannelLayout","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotCreateChannelLayout","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotCreateChannelLayout"}],"url":"\/documentation\/socialradio\/errorcode\/cannotcreatechannellayout"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/removeTrackOutOfBounds":{"url":"\/documentation\/socialradio\/errorcode\/removetrackoutofbounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeTrackOutOfBounds","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/removeTrackOutOfBounds","type":"topic","title":"ErrorCode.removeTrackOutOfBounds","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/addTrackNoMetadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackNoMetadata"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","title":"ErrorCode.addTrackNoMetadata","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackNoMetadata","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeAddTrackNoMetadata"}],"url":"\/documentation\/socialradio\/errorcode\/addtracknometadata"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/nextNoTrackAvailable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/nextNoTrackAvailable","url":"\/documentation\/socialradio\/errorcode\/nextnotrackavailable","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextNoTrackAvailable"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNextNoTrackAvailable"}],"title":"ErrorCode.nextNoTrackAvailable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/onAlreadyTurningOn":{"url":"\/documentation\/socialradio\/errorcode\/onalreadyturningon","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAlreadyTurningOn"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeOnAlreadyTurningOn"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/onAlreadyTurningOn","type":"topic","title":"ErrorCode.onAlreadyTurningOn","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/RawRepresentable-Implementations","url":"\/documentation\/socialradio\/errorcode\/rawrepresentable-implementations"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/offAlreadyTurningOff":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/offAlreadyTurningOff","url":"\/documentation\/socialradio\/errorcode\/offalreadyturningoff","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"offAlreadyTurningOff","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeOffAlreadyTurningOff"}],"title":"ErrorCode.offAlreadyTurningOff"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/notMainThread":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notMainThread"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","title":"ErrorCode.notMainThread","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/notMainThread","navigatorTitle":[{"text":"ErrorCodeNotMainThread","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode\/notmainthread"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotCreateInputBuffer":{"type":"topic","title":"ErrorCode.cannotCreateInputBuffer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotCreateInputBuffer"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotCreateInputBuffer","url":"\/documentation\/socialradio\/errorcode\/cannotcreateinputbuffer","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotCreateInputBuffer","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/offWhileTurningOn":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/offWhileTurningOn","url":"\/documentation\/socialradio\/errorcode\/offwhileturningon","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offWhileTurningOn","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"ErrorCodeOffWhileTurningOn","kind":"identifier"}],"title":"ErrorCode.offWhileTurningOn"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/seekNoTrackAvailable":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"seekNoTrackAvailable","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","title":"ErrorCode.seekNoTrackAvailable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/seekNoTrackAvailable","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSeekNoTrackAvailable"}],"url":"\/documentation\/socialradio\/errorcode\/seeknotrackavailable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotDownloadAd":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotDownloadAd","url":"\/documentation\/socialradio\/errorcode\/cannotdownloadad","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotDownloadAd","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"ErrorCodeCannotDownloadAd","kind":"identifier"}],"title":"ErrorCode.cannotDownloadAd"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/sdkNotInitialised":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotInitialised","url":"\/documentation\/socialradio\/errorcode\/sdknotinitialised","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkNotInitialised"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"ErrorCodeSdkNotInitialised","kind":"identifier"}],"title":"ErrorCode.sdkNotInitialised"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotRestoreAudioSession":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotRestoreAudioSession","kind":"identifier"}],"role":"symbol","type":"topic","title":"ErrorCode.cannotRestoreAudioSession","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotRestoreAudioSession","navigatorTitle":[{"text":"ErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode\/cannotrestoreaudiosession"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/pauseAlreadyPaused":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/pauseAlreadyPaused","url":"\/documentation\/socialradio\/errorcode\/pausealreadypaused","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseAlreadyPaused"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}],"title":"ErrorCode.pauseAlreadyPaused"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/reorderMissingTrack":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderMissingTrack"}],"role":"symbol","type":"topic","kind":"symbol","title":"ErrorCode.reorderMissingTrack","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/reorderMissingTrack","navigatorTitle":[{"text":"ErrorCodeReorderMissingTrack","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode\/reordermissingtrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Errors-article":{"url":"\/documentation\/socialradio\/errors-article","kind":"article","type":"topic","abstract":[{"type":"text","text":"What errors the SocialRadio player can issue to help with player integration"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Errors-article","title":"Errors","role":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/previousNoTrackAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousNoTrackAvailable","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","title":"ErrorCode.previousNoTrackAvailable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/previousNoTrackAvailable","navigatorTitle":[{"text":"ErrorCodePreviousNoTrackAvailable","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode\/previousnotrackavailable"},"doc://org.cocoapods.SocialRadio/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotInterruptAd":{"url":"\/documentation\/socialradio\/errorcode\/cannotinterruptad","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotInterruptAd","title":"ErrorCode.cannotInterruptAd","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotInterruptAd"}],"role":"symbol","navigatorTitle":[{"text":"ErrorCodeCannotInterruptAd","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/SH":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","type":"topic","title":"SocialRadio","role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/playAlreadyPlaying":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playAlreadyPlaying"}],"url":"\/documentation\/socialradio\/errorcode\/playalreadyplaying","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/playAlreadyPlaying","title":"ErrorCode.playAlreadyPlaying","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePlayAlreadyPlaying"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/sdkInitialisationUnauthorised":{"url":"\/documentation\/socialradio\/errorcode\/sdkinitialisationunauthorised","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInitialisationUnauthorised"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSdkInitialisationUnauthorised"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkInitialisationUnauthorised","title":"ErrorCode.sdkInitialisationUnauthorised","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/failedToStop":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/failedToStop","url":"\/documentation\/socialradio\/errorcode\/failedtostop","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToStop","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"ErrorCodeFailedToStop","kind":"identifier"}],"title":"ErrorCode.failedToStop"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/loadTracksEmptyPlaylist":{"url":"\/documentation\/socialradio\/errorcode\/loadtracksemptyplaylist","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTracksEmptyPlaylist"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeLoadTracksEmptyPlaylist"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/loadTracksEmptyPlaylist","title":"ErrorCode.loadTracksEmptyPlaylist","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotSetupAVAudioSession":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotSetupAVAudioSession","url":"\/documentation\/socialradio\/errorcode\/cannotsetupavaudiosession","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cannotSetupAVAudioSession","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotSetupAVAudioSession"}],"title":"ErrorCode.cannotSetupAVAudioSession"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/loadTracksOutOfBounds":{"url":"\/documentation\/socialradio\/errorcode\/loadtracksoutofbounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracksOutOfBounds","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeLoadTracksOutOfBounds","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/loadTracksOutOfBounds","title":"ErrorCode.loadTracksOutOfBounds","type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/offlineNoTunedUserIdAvailable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/offlineNoTunedUserIdAvailable","url":"\/documentation\/socialradio\/errorcode\/offlinenotuneduseridavailable","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"title":"ErrorCode.offlineNoTunedUserIdAvailable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ErrorCode","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cancelled","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotDownloadAd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotInterruptAd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/didNotAddAdIndexPassedAlready","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/failedToStop","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/notMainThread","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/unable_to_load_mix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/unimplemented"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Errors-article"],"generated":true,"anchor":"Errors","title":"Errors"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeAddTrackOutOfBounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackOutOfBounds\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeAddTrackOutOfBounds"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackOutOfBounds\/fragments"},{"value":"ErrorCodeSdkAlreadyInitialised","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkAlreadyInitialised\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyInitialised"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkAlreadyInitialised\/fragments"},{"value":"ErrorCodeUnimplemented","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1unimplemented\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeUnimplemented"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1unimplemented\/fragments"},{"value":"ErrorCodePlayToEndMissingTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1playToEndMissingTrack\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1playToEndMissingTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodePlayToEndMissingTrack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1unable_to_load_mix\/title","op":"replace","value":"ErrorCodeUnable_to_load_mix"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1unable_to_load_mix\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeUnable_to_load_mix"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1stopLoopingNoLoopingTrack\/title","op":"replace","value":"ErrorCodeStopLoopingNoLoopingTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1stopLoopingNoLoopingTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeStopLoopingNoLoopingTrack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1seekNoCurrentTrack\/title","op":"replace","value":"ErrorCodeSeekNoCurrentTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1seekNoCurrentTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeSeekNoCurrentTrack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1didNotAddAdIndexPassedAlready\/title","op":"replace","value":"ErrorCodeDidNotAddAdIndexPassedAlready"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1didNotAddAdIndexPassedAlready\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeDidNotAddAdIndexPassedAlready"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotStartAudioEngine\/title","op":"replace","value":"ErrorCodeCannotStartAudioEngine"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotStartAudioEngine\/fragments","op":"replace","value":[{"text":"ErrorCodeCannotStartAudioEngine","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1moveTrackOutOfBounds\/title","op":"replace","value":"ErrorCodeMoveTrackOutOfBounds"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1moveTrackOutOfBounds\/fragments","op":"replace","value":[{"text":"ErrorCodeMoveTrackOutOfBounds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1noInternetAvailableTooLongOffline\/title","op":"replace","value":"ErrorCodeNoInternetAvailableTooLongOffline"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1noInternetAvailableTooLongOffline\/fragments","op":"replace","value":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotLoadExplicitLyricsTrack\/title","op":"replace","value":"ErrorCodeCannotLoadExplicitLyricsTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotLoadExplicitLyricsTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeCannotLoadExplicitLyricsTrack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackInternalError\/title","op":"replace","value":"ErrorCodeAddTrackInternalError"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackInternalError\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeAddTrackInternalError"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkNotOn\/title","op":"replace","value":"ErrorCodeSdkNotOn"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkNotOn\/fragments","value":[{"text":"ErrorCodeSdkNotOn","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackPlaylistDoesNotExist\/title","value":"ErrorCodeAddTrackPlaylistDoesNotExist","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackPlaylistDoesNotExist\/fragments","value":[{"kind":"identifier","text":"ErrorCodeAddTrackPlaylistDoesNotExist"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkAlreadyOn\/title","value":"ErrorCodeSdkAlreadyOn","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkAlreadyOn\/fragments","value":[{"kind":"identifier","text":"ErrorCodeSdkAlreadyOn"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cancelled\/title","value":"ErrorCodeCancelled","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cancelled\/fragments","value":[{"text":"ErrorCodeCancelled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1onWhileTurningOff\/title","value":"ErrorCodeOnWhileTurningOff","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1onWhileTurningOff\/fragments","value":[{"text":"ErrorCodeOnWhileTurningOff","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1backNoTrackAvailable\/title","value":"ErrorCodeBackNoTrackAvailable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1backNoTrackAvailable\/fragments","value":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1startLoopingNoLoopingTrack\/title","value":"ErrorCodeStartLoopingNoLoopingTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1startLoopingNoLoopingTrack\/fragments","value":[{"text":"ErrorCodeStartLoopingNoLoopingTrack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1noInternetAvailable\/title","value":"ErrorCodeNoInternetAvailable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1noInternetAvailable\/fragments","value":[{"kind":"identifier","text":"ErrorCodeNoInternetAvailable"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1playToEndMixEnd\/title","value":"ErrorCodePlayToEndMixEnd","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1playToEndMixEnd\/fragments","value":[{"text":"ErrorCodePlayToEndMixEnd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/title","value":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/fragments","value":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotCreateChannelLayout\/title","value":"ErrorCodeCannotCreateChannelLayout","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotCreateChannelLayout\/fragments","value":[{"kind":"identifier","text":"ErrorCodeCannotCreateChannelLayout"}],"op":"replace"},{"value":"ErrorCodeRemoveTrackOutOfBounds","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1removeTrackOutOfBounds\/title","op":"replace"},{"value":[{"text":"ErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1removeTrackOutOfBounds\/fragments","op":"replace"},{"value":"ErrorCodeAddTrackNoMetadata","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackNoMetadata\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeAddTrackNoMetadata"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1addTrackNoMetadata\/fragments","op":"replace"},{"value":"ErrorCodeNextNoTrackAvailable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1nextNoTrackAvailable\/title","op":"replace"},{"value":[{"text":"ErrorCodeNextNoTrackAvailable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1nextNoTrackAvailable\/fragments","op":"replace"},{"value":"ErrorCodeOnAlreadyTurningOn","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1onAlreadyTurningOn\/title","op":"replace"},{"value":[{"text":"ErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1onAlreadyTurningOn\/fragments","op":"replace"},{"value":"ErrorCodeOffAlreadyTurningOff","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1offAlreadyTurningOff\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeOffAlreadyTurningOff"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1offAlreadyTurningOff\/fragments","op":"replace"},{"value":"ErrorCodeNotMainThread","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1notMainThread\/title","op":"replace"},{"value":[{"text":"ErrorCodeNotMainThread","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1notMainThread\/fragments","op":"replace"},{"value":"ErrorCodeCannotCreateInputBuffer","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotCreateInputBuffer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeCannotCreateInputBuffer"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotCreateInputBuffer\/fragments","op":"replace"},{"value":"ErrorCodeOffWhileTurningOn","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1offWhileTurningOn\/title","op":"replace"},{"value":[{"text":"ErrorCodeOffWhileTurningOn","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1offWhileTurningOn\/fragments","op":"replace"},{"value":"ErrorCodeSeekNoTrackAvailable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1seekNoTrackAvailable\/title","op":"replace"},{"value":[{"text":"ErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1seekNoTrackAvailable\/fragments","op":"replace"},{"value":"ErrorCodeCannotDownloadAd","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotDownloadAd\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeCannotDownloadAd"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotDownloadAd\/fragments","op":"replace"},{"value":"ErrorCodeSdkNotInitialised","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkNotInitialised\/title","op":"replace"},{"value":[{"text":"ErrorCodeSdkNotInitialised","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkNotInitialised\/fragments","op":"replace"},{"value":"ErrorCodeCannotRestoreAudioSession","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotRestoreAudioSession\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeCannotRestoreAudioSession"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotRestoreAudioSession\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1pauseAlreadyPaused\/title","value":"ErrorCodePauseAlreadyPaused","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1pauseAlreadyPaused\/fragments","value":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1reorderMissingTrack\/title","value":"ErrorCodeReorderMissingTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1reorderMissingTrack\/fragments","value":[{"text":"ErrorCodeReorderMissingTrack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1previousNoTrackAvailable\/title","value":"ErrorCodePreviousNoTrackAvailable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1previousNoTrackAvailable\/fragments","value":[{"text":"ErrorCodePreviousNoTrackAvailable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotInterruptAd\/title","value":"ErrorCodeCannotInterruptAd","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotInterruptAd\/fragments","value":[{"kind":"identifier","text":"ErrorCodeCannotInterruptAd"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1playAlreadyPlaying\/title","value":"ErrorCodePlayAlreadyPlaying","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1playAlreadyPlaying\/fragments","value":[{"text":"ErrorCodePlayAlreadyPlaying","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkInitialisationUnauthorised\/title","value":"ErrorCodeSdkInitialisationUnauthorised","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1sdkInitialisationUnauthorised\/fragments","value":[{"text":"ErrorCodeSdkInitialisationUnauthorised","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1failedToStop\/title","value":"ErrorCodeFailedToStop","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1failedToStop\/fragments","value":[{"kind":"identifier","text":"ErrorCodeFailedToStop"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1loadTracksEmptyPlaylist\/title","value":"ErrorCodeLoadTracksEmptyPlaylist","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1loadTracksEmptyPlaylist\/fragments","value":[{"text":"ErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotSetupAVAudioSession\/title","value":"ErrorCodeCannotSetupAVAudioSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotSetupAVAudioSession\/fragments","value":[{"kind":"identifier","text":"ErrorCodeCannotSetupAVAudioSession"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1loadTracksOutOfBounds\/title","value":"ErrorCodeLoadTracksOutOfBounds","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1loadTracksOutOfBounds\/fragments","value":[{"text":"ErrorCodeLoadTracksOutOfBounds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1offlineNoTunedUserIdAvailable\/title","value":"ErrorCodeOfflineNoTunedUserIdAvailable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1offlineNoTunedUserIdAvailable\/fragments","value":[{"kind":"identifier","text":"ErrorCodeOfflineNoTunedUserIdAvailable"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}