{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiotunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiotunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)"]}],"abstract":[{"type":"text","text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required."},{"text":" ","type":"text"},{"type":"text","text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}],"externalID":"c:@M@SocialRadio@objc(pl)SocialRadioTunedRestDelegate(im)asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetAuthenticatedDevice"},{"kind":"text","text":"("},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tunedDeviceId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"required":true,"title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncGetAuthenticatedDevice","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tunedDeviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The unique identifier of the device"}],"type":"paragraph"}],"name":"deviceIdentifierForVendor"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request","type":"text"}]}],"name":"completion"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedRestDelegate/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)":{"kind":"symbol","title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","required":true,"url":"\/documentation\/socialradio\/socialradiotunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncGetAuthenticatedDevice","kind":"identifier"},{"kind":"text","text":"("},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tunedDeviceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}],"abstract":[{"type":"text","text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required."},{"type":"text","text":" "},{"type":"text","text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”."}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTunedRestDelegate":{"title":"SocialRadioTunedRestDelegate","kind":"symbol","url":"\/documentation\/socialradio\/socialradiotunedrestdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTunedRestDelegate","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"deviceIdentifierForVendor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The unique identifier of the device"}],"type":"paragraph"}],"name":"deviceIdentifierForVendor"},{"content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}],"type":"paragraph"}],"name":"completion"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate\/title","value":"SocialRadioTunedRestDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate\/fragments","op":"replace","value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTunedRestDelegate\/navigatorTitle","value":[{"text":"SocialRadioTunedRestDelegate","kind":"identifier"}],"op":"replace"}]}]}