{"metadata":{"title":"allowVoiceOver","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowVoiceOver","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","modules":[{"name":"SocialRadioLite"}],"navigatorTitle":[{"text":"allowVoiceOver","kind":"identifier"}],"externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioFeatureSetConfig(py)allowVoiceOver"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiofeaturesetconfig\/allowvoiceover"]},{"paths":["\/documentation\/socialradiolite\/socialradiofeaturesetconfig\/allowvoiceover"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig\/allowVoiceOver"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowVoiceOver","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioFeatureSetConfig/allowVoiceOver":{"navigatorTitle":[{"text":"allowVoiceOver","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig\/allowVoiceOver","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowVoiceOver"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradiofeaturesetconfig\/allowvoiceover","abstract":[],"title":"allowVoiceOver","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioFeatureSetConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","url":"\/documentation\/socialradiolite\/socialradiofeaturesetconfig","title":"SocialRadioFeatureSetConfig"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"allowVoiceOver","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"allowVoiceOver","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"allowVoiceOver","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig~1allowVoiceOver\/title","op":"replace","value":"allowVoiceOver"},{"op":"replace","value":[{"kind":"identifier","text":"allowVoiceOver"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig~1allowVoiceOver\/fragments"},{"value":"SocialRadioFeatureSetConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/fragments","op":"replace","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}]},{"op":"replace","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/navigatorTitle"}]}]}