{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlayLogID"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLogID","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"kind":"symbol","seeAlsoSections":[{"title":"Persistency","anchor":"Persistency","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Persistency-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLog","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLogAttributes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLog","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLogAttributes","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLogID","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType"],"generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSManagedObjectID"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSFetchRequestResult","doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSCopying","doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH","doc:\/\/org.cocoapods.SocialRadio\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkplaylogid"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"class","title":"AutomixSDKPlayLogID","roleHeading":"Class","externalID":"c:objc(cs)AutomixSDKPlayLogID","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlayLogID"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLogID"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTransitionLogID":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLogID","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLogID","role":"symbol","type":"topic","title":"AutomixSDKTransitionLogID","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLogID"}],"url":"\/documentation\/socialradio\/automixsdktransitionlogid"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlaybackEventType":{"abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkplaybackeventtype","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"title":"AutomixSDKPlaybackEventType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlaybackEventType","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTransitionLog":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLog"}],"role":"symbol","title":"AutomixSDKTransitionLog","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdktransitionlog","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLog","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTransitionLog"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlayLogID":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLogID"}],"role":"symbol","title":"AutomixSDKPlayLogID","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkplaylogid","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLogID","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlayLogID","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlayLog":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLog"}],"url":"\/documentation\/socialradio\/automixsdkplaylog","kind":"symbol","abstract":[],"role":"symbol","title":"AutomixSDKPlayLog","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLog","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlayLog","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadio/objc(cs)NSManagedObjectID":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSManagedObjectID","title":"CoreData.NSManagedObjectID"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.SocialRadio/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSCopying","title":"Foundation.NSCopying"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKPlayLogAttributes":{"role":"symbol","abstract":[],"title":"AutomixSDKPlayLogAttributes","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlayLogAttributes"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLogAttributes"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKPlayLogAttributes","url":"\/documentation\/socialradio\/automixsdkplaylogattributes","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.SocialRadio/objc(pl)NSFetchRequestResult":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSFetchRequestResult","title":"CoreData.NSFetchRequestResult"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Persistency-article":{"abstract":[{"text":"What AutomixIQ stores locally","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Persistency-article","role":"article","type":"topic","title":"Persistency","kind":"article","url":"\/documentation\/socialradio\/persistency-article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKTransitionLogAttributes":{"navigatorTitle":[{"text":"AutomixSDKTransitionLogAttributes","kind":"identifier"}],"role":"symbol","title":"AutomixSDKTransitionLogAttributes","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKTransitionLogAttributes","url":"\/documentation\/socialradio\/automixsdktransitionlogattributes","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLogAttributes","kind":"identifier"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKPlaybackEventType\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"op":"replace"}]}]}