{"sections":[],"kind":"symbol","metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotStartAudioEngine","kind":"identifier"}],"role":"symbol","externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeCannotStartAudioEngine","navigatorTitle":[{"text":"ErrorCodeCannotStartAudioEngine","kind":"identifier"}],"title":"ErrorCode.cannotStartAudioEngine","symbolKind":"case","modules":[{"name":"SocialRadio"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotStartAudioEngine"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotStartAudioEngine","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errorcode\/cannotstartaudioengine"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/errorcode\/cannotstartaudioengine"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cannotStartAudioEngine":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cannotStartAudioEngine","navigatorTitle":[{"text":"ErrorCodeCannotStartAudioEngine","kind":"identifier"}],"title":"ErrorCode.cannotStartAudioEngine","url":"\/documentation\/socialradio\/errorcode\/cannotstartaudioengine","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotStartAudioEngine","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"title":"ErrorCode","type":"topic","url":"\/documentation\/socialradio\/errorcode","kind":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ErrorCodeCannotStartAudioEngine","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ErrorCodeCannotStartAudioEngine","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodeCannotStartAudioEngine"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeCannotStartAudioEngine","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotStartAudioEngine\/title"},{"value":[{"text":"ErrorCodeCannotStartAudioEngine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cannotStartAudioEngine\/fragments"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle"}]}]}