{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixPlaybackEnded"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/automixiqplaybackeventtype\/mixplaybackended"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/automixiqplaybackeventtype\/mixplaybackended"]}],"metadata":{"externalID":"c:@M@SocialRadioLite@E@AutomixIQPlaybackEventType@AutomixIQPlaybackEventTypeMixPlaybackEnded","roleHeading":"Case","symbolKind":"case","title":"AutomixIQPlaybackEventType.mixPlaybackEnded","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"modules":[{"name":"SocialRadioLite"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/mixPlaybackEnded"},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype","navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"title":"AutomixIQPlaybackEventType","type":"topic","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType/mixPlaybackEnded":{"abstract":[],"role":"symbol","type":"topic","title":"AutomixIQPlaybackEventType.mixPlaybackEnded","url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype\/mixplaybackended","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType\/mixPlaybackEnded","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"AutomixIQPlaybackEventTypeMixPlaybackEnded"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixIQPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeMixPlaybackEnded"}]}]},"path":"\/primaryContentSections\/0"},{"value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"op":"replace"},{"value":"AutomixIQPlaybackEventTypeMixPlaybackEnded","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/title"},{"value":[{"text":"AutomixIQPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType~1mixPlaybackEnded\/fragments","op":"replace"}]}]}