{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel\/isAd-a0z","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Objective-C accessible member for IsAd"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"title":"isAd","roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)TunedTrackModel(py)isAd","navigatorTitle":[{"text":"isAd","kind":"identifier"}],"role":"symbol","symbolKind":"property","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/socialradio\/tunedtrackmodel\/isad-a0z"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/tunedtrackmodel\/isad-a0z"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"url":"\/documentation\/socialradio\/tunedtrackmodel","abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"type":"topic","role":"symbol","title":"TunedTrackModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","role":"collection","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel/isAd-a0z":{"navigatorTitle":[{"kind":"identifier","text":"isAd"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel\/isAd-a0z","kind":"symbol","abstract":[{"type":"text","text":"Objective-C accessible member for IsAd"}],"title":"isAd","url":"\/documentation\/socialradio\/tunedtrackmodel\/isad-a0z","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isAd","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"isAd"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAd"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TunedTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title"},{"value":[{"kind":"identifier","text":"TunedTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments"},{"value":[{"kind":"identifier","text":"TunedTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle"},{"value":"isAd","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel~1isAd-a0z\/title"},{"value":[{"kind":"identifier","text":"isAd"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel~1isAd-a0z\/fragments"}]}]}