{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus"]]},"metadata":{"symbolKind":"property","externalID":"c:@M@SocialRadio@objc(cs)AutomixIQStatus(py)explicitLyricsFiltering","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"SocialRadio"}],"title":"explicitLyricsFiltering","navigatorTitle":[{"text":"explicitLyricsFiltering","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"explicitLyricsFiltering"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"explicitLyricsFiltering"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/explicitLyricsFiltering","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqstatus\/explicitlyricsfiltering"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqstatus\/explicitlyricsfiltering"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus/explicitLyricsFiltering":{"url":"\/documentation\/socialradio\/automixiqstatus\/explicitlyricsfiltering","navigatorTitle":[{"kind":"identifier","text":"explicitLyricsFiltering"}],"title":"explicitLyricsFiltering","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus\/explicitLyricsFiltering","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"explicitLyricsFiltering"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"role":"collection","kind":"symbol","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatus":{"type":"topic","title":"AutomixIQStatus","url":"\/documentation\/socialradio\/automixiqstatus","abstract":[{"text":"AutomixIQStatus models the State of the AutomixIQ during playback.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatus","kind":"symbol","navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"explicitLyricsFiltering","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"explicitLyricsFiltering","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"explicitLyricsFiltering","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"explicitLyricsFiltering","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1explicitLyricsFiltering\/title","op":"replace"},{"value":[{"text":"explicitLyricsFiltering","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus~1explicitLyricsFiltering\/fragments","op":"replace"},{"value":"AutomixIQStatus","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/title","op":"replace"},{"value":[{"text":"AutomixIQStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/fragments","op":"replace"},{"value":[{"text":"AutomixIQStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}