{"seeAlsoSections":[{"generated":true,"anchor":"Waveform-Data-access","title":"Waveform Data access","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/waveformDataForTrack(identifier:applyTransitions:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setWaveformPointsPerTrack(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiq\/setwaveformpointspertrack(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiq\/setwaveformpointspertrack(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setWaveformPointsPerTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"waveformPointsPerTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The number of points representing a waveform for a track, maximum of 1024, defaults to 256","type":"text"}],"type":"paragraph"}],"name":"waveformPointsPerTrack"}]},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Accessing-waveform-data-article"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setWaveformPointsPerTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQ(im)setWaveformPointsPerTrack:","title":"setWaveformPointsPerTrack(_:)","modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"kind":"identifier","text":"setWaveformPointsPerTrack:"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ"]]},"abstract":[{"text":"Sets the resolution of the waveform data for a track","type":"text"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Accessing-waveform-data-article":{"abstract":[],"role":"article","title":"Accessing waveform data","kind":"article","url":"\/documentation\/automixiq\/accessing-waveform-data-article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Accessing-waveform-data-article","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/waveformDataForTrack(identifier:applyTransitions:)":{"title":"waveformDataForTrack(identifier:applyTransitions:)","type":"topic","url":"\/documentation\/automixiq\/automixiq\/waveformdatafortrack(identifier:applytransitions:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/waveformDataForTrack(identifier:applyTransitions:)","kind":"symbol","abstract":[{"type":"text","text":"Gets the waveform data for a track."}],"role":"symbol","navigatorTitle":[{"text":"waveformDataForTrackWithIdentifier:applyTransitions:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waveformDataForTrack"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applyTransitions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"AutomixIQWaveformModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQWaveformModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ":{"type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq\/automixiq","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ","abstract":[{"text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"type":"topic","role":"collection","title":"AutomixIQ","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQ/setWaveformPointsPerTrack(_:)":{"type":"topic","title":"setWaveformPointsPerTrack(_:)","url":"\/documentation\/automixiq\/automixiq\/setwaveformpointspertrack(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/setWaveformPointsPerTrack(_:)","abstract":[{"type":"text","text":"Sets the resolution of the waveform data for a track"}],"role":"symbol","navigatorTitle":[{"text":"setWaveformPointsPerTrack:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setWaveformPointsPerTrack"},{"kind":"text","text":"("},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"setWaveformPointsPerTrack:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setWaveformPointsPerTrack:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Waveform Data access","anchor":"Waveform-Data-access","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQ\/waveformDataForTrack(identifier:applyTransitions:)"]}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setWaveformPointsPerTrack:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"int32_t","preciseIdentifier":"c:@T@int32_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"waveformPointsPerTrack","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"waveformPointsPerTrack","content":[{"inlineContent":[{"text":"The number of points representing a waveform for a track, maximum of 1024, defaults to 256","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1waveformDataForTrack(identifier:applyTransitions:)\/title","op":"replace","value":"waveformDataForTrackWithIdentifier:applyTransitions:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1waveformDataForTrack(identifier:applyTransitions:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"waveformDataForTrackWithIdentifier:applyTransitions:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/title","op":"replace","value":"AutomixIQ"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/fragments","op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQ","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setWaveformPointsPerTrack(_:)\/title","op":"replace","value":"setWaveformPointsPerTrack:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQ~1setWaveformPointsPerTrack(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setWaveformPointsPerTrack:","kind":"identifier"}]}]}]}