{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postUnfollowUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"loggedInUserIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the user to unfollow."}]}],"name":"identifier"},{"content":[{"inlineContent":[{"text":"The ID of the logged-in user initiating the unfollow.","type":"text"}],"type":"paragraph"}],"name":"loggedInUserIdentifier"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}],"name":"completion"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate\/postUnfollowUser(identifier:loggedInUserIdentifier:completion:)"},"kind":"symbol","metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postUnfollowUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"loggedInUserIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@SocialRadio@objc(pl)SocialLayerUserDelegate(im)postUnfollowUserWithIdentifier:loggedInUserIdentifier:completion:","roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"method","title":"postUnfollowUser(identifier:loggedInUserIdentifier:completion:)","navigatorTitle":[{"text":"postUnfollowUserWithIdentifier:loggedInUserIdentifier:completion:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/socialradio\/sociallayeruserdelegate\/postunfollowuser(identifier:loggedinuseridentifier:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayeruserdelegate\/postunfollowuser(identifier:loggedinuseridentifier:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Unfollows a user on behalf of the logged-in user.","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerUserDelegate":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialLayerUserDelegate"}],"type":"topic","title":"SocialLayerUserDelegate","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding  users."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerUserDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","url":"\/documentation\/socialradio\/sociallayeruserdelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","role":"collection","url":"\/documentation\/socialradio","title":"SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerUserDelegate/postUnfollowUser(identifier:loggedInUserIdentifier:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postUnfollowUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"loggedInUserIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"postUnfollowUserWithIdentifier:loggedInUserIdentifier:completion:","kind":"identifier"}],"title":"postUnfollowUser(identifier:loggedInUserIdentifier:completion:)","required":true,"type":"topic","url":"\/documentation\/socialradio\/sociallayeruserdelegate\/postunfollowuser(identifier:loggedinuseridentifier:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate\/postUnfollowUser(identifier:loggedInUserIdentifier:completion:)","role":"symbol","abstract":[{"type":"text","text":"Unfollows a user on behalf of the logged-in user."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"postUnfollowUserWithIdentifier:loggedInUserIdentifier:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"postUnfollowUserWithIdentifier:loggedInUserIdentifier:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"postUnfollowUserWithIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"loggedInUserIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"loggedInUserIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the user to unfollow.","type":"text"}]}]},{"name":"loggedInUserIdentifier","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the logged-in user initiating the unfollow.","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/title","value":"SocialLayerUserDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"SocialLayerUserDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialLayerUserDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/navigatorTitle"},{"op":"replace","value":"postUnfollowUserWithIdentifier:loggedInUserIdentifier:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate~1postUnfollowUser(identifier:loggedInUserIdentifier:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"postUnfollowUserWithIdentifier:loggedInUserIdentifier:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate~1postUnfollowUser(identifier:loggedInUserIdentifier:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}