{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTracksEmptyPlaylist"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksEmptyPlaylist","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTracksEmptyPlaylist"}],"title":"ErrorCode.loadTracksEmptyPlaylist","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeLoadTracksEmptyPlaylist"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeLoadTracksEmptyPlaylist","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/errorcode\/loadtracksemptyplaylist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/errorcode\/loadtracksemptyplaylist"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"role":"symbol","title":"ErrorCode","url":"\/documentation\/automixiq\/errorcode","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/loadTracksEmptyPlaylist":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksEmptyPlaylist","url":"\/documentation\/automixiq\/errorcode\/loadtracksemptyplaylist","abstract":[],"type":"topic","kind":"symbol","title":"ErrorCode.loadTracksEmptyPlaylist","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracksEmptyPlaylist","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ErrorCodeLoadTracksEmptyPlaylist","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1loadTracksEmptyPlaylist\/title","value":"ErrorCodeLoadTracksEmptyPlaylist","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1loadTracksEmptyPlaylist\/fragments","value":[{"text":"ErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}],"op":"replace"}]}]}