{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekNoCurrentTrack","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekNoCurrentTrack"}],"externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeSeekNoCurrentTrack","role":"symbol","roleHeading":"Case","title":"ErrorCode.seekNoCurrentTrack","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeSeekNoCurrentTrack"}],"modules":[{"name":"AutomixIQ"}]},"sections":[],"variants":[{"paths":["\/documentation\/automixiq\/errorcode\/seeknocurrenttrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/errorcode\/seeknocurrenttrack"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/seekNoCurrentTrack","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/seekNoCurrentTrack":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekNoCurrentTrack","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeSeekNoCurrentTrack","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/seekNoCurrentTrack","kind":"symbol","title":"ErrorCode.seekNoCurrentTrack","url":"\/documentation\/automixiq\/errorcode\/seeknocurrenttrack"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"role":"symbol","title":"ErrorCode","url":"\/documentation\/automixiq\/errorcode","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ErrorCodeSeekNoCurrentTrack","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeSeekNoCurrentTrack"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"ErrorCodeSeekNoCurrentTrack","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ErrorCodeSeekNoCurrentTrack","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1seekNoCurrentTrack\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1seekNoCurrentTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeSeekNoCurrentTrack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]}]}]}