{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/errors-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/errors-article"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"abstract":[{"type":"text","text":"What errors the SocialRadio player can issue to help with player integration"}],"metadata":{"modules":[{"name":"SocialRadio"}],"role":"article","roleHeading":"Article","title":"Errors"},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/sdkError(code:)"],"anchor":"Errors","title":"Errors","generated":true}],"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"Essentials","anchor":"Essentials"},{"type":"paragraph","inlineContent":[{"text":"SocialRadio can issue errors listed in the enumeration ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"},{"text":":","type":"text"}]},{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Errors-article"},"kind":"article","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"title":"ErrorCode","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/sdkError(code:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ErrorCode","preciseIdentifier":"c:@M@SocialRadio@E@ErrorCode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"url":"\/documentation\/socialradio\/sdkerror(code:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/sdkError(code:)","title":"sdkError(code:)","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"anchor":"Errors","title":"Errors","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]}],"path":"\/seeAlsoSections","op":"replace"},{"value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","op":"replace"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","op":"replace"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","op":"replace"}]}]}