{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseAlreadyPaused"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/pauseAlreadyPaused","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/errorcode\/pausealreadypaused"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode\/pausealreadypaused"]}],"metadata":{"roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodePauseAlreadyPaused","navigatorTitle":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}],"modules":[{"name":"AutomixIQ"}],"title":"ErrorCode.pauseAlreadyPaused","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseAlreadyPaused"}]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/pauseAlreadyPaused":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseAlreadyPaused"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}],"url":"\/documentation\/automixiq\/errorcode\/pausealreadypaused","title":"ErrorCode.pauseAlreadyPaused","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/pauseAlreadyPaused","kind":"symbol","role":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ","type":"topic","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","role":"symbol","url":"\/documentation\/automixiq\/errorcode","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ErrorCodePauseAlreadyPaused","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ErrorCodePauseAlreadyPaused","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1pauseAlreadyPaused\/title","op":"replace","value":"ErrorCodePauseAlreadyPaused"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1pauseAlreadyPaused\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}