{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel"]]},"variants":[{"paths":["\/documentation\/socialradio\/tunedloglevel\/loglevelinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/tunedloglevel\/loglevelinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"symbolKind":"case","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelInfo","kind":"identifier"}],"externalID":"c:@M@SocialRadio@E@TunedLogLevel@TunedLogLevelLogLevelInfo","roleHeading":"Case","title":"TunedLogLevel.logLevelInfo","navigatorTitle":[{"text":"TunedLogLevelLogLevelInfo","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel\/logLevelInfo"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelInfo"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","url":"\/documentation\/socialradio\/tunedloglevel","title":"TunedLogLevel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedLogLevel"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedLogLevel"}],"abstract":[{"type":"text","text":"TunedLogLevel is an enum of all the AutomixIQ available log levels"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel/logLevelInfo":{"abstract":[],"navigatorTitle":[{"text":"TunedLogLevelLogLevelInfo","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelInfo","kind":"identifier"}],"title":"TunedLogLevel.logLevelInfo","type":"topic","url":"\/documentation\/socialradio\/tunedloglevel\/loglevelinfo","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel\/logLevelInfo","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"TunedLogLevelLogLevelInfo","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TunedLogLevelLogLevelInfo"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"TunedLogLevelLogLevelInfo"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/title","value":"TunedLogLevel","op":"replace"},{"value":[{"kind":"identifier","text":"TunedLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TunedLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/navigatorTitle","op":"replace"},{"value":"TunedLogLevelLogLevelInfo","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel~1logLevelInfo\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TunedLogLevelLogLevelInfo"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel~1logLevelInfo\/fragments","op":"replace"}]}]}