{"metadata":{"title":"playlist","externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQStatus(py)playlist","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"playlist"}],"role":"symbol","modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlist"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixiqstatus\/playlist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqstatus\/playlist"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus\/playlist","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents the list of track identifiers in the order they will be played"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playlist","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus/playlist":{"title":"playlist","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus\/playlist","url":"\/documentation\/automixiq\/automixiqstatus\/playlist","abstract":[{"text":"Represents the list of track identifiers in the order they will be played","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlist"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playlist"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatus":{"navigatorTitle":[{"text":"AutomixIQStatus","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatus","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqstatus","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"AutomixIQStatus models the State of the AutomixIQ during playback."}],"type":"topic","title":"AutomixIQStatus","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatus"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"playlist","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"playlist","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"playlist"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"playlist","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus~1playlist\/title"},{"value":[{"kind":"identifier","text":"playlist"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus~1playlist\/fragments"},{"value":"AutomixIQStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/title"},{"value":[{"kind":"identifier","text":"AutomixIQStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}