{"metadata":{"modules":[{"name":"SocialRadio"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncPreloadLoggedInUserBackgrounds","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeBackgroundsDelegate(im)syncPreloadLoggedInUserBackgroundsWithUserIdentifier:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"syncPreloadLoggedInUserBackgroundsWithUserIdentifier:"}],"required":true,"roleHeading":"Instance Method","title":"syncPreloadLoggedInUserBackgrounds(userIdentifier:)"},"variants":[{"paths":["\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate\/syncpreloadloggedinuserbackgrounds(useridentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate\/syncpreloadloggedinuserbackgrounds(useridentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate\/syncPreloadLoggedInUserBackgrounds(userIdentifier:)"},"abstract":[{"type":"text","text":"Preloads all backgrounds associated with the logged-in user."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncPreloadLoggedInUserBackgrounds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"userIdentifier","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the user.","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate":{"type":"topic","abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds."}],"title":"SocialLayerMixtapeBackgroundsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerMixtapeBackgroundsDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SocialLayerMixtapeBackgroundsDelegate"}],"role":"symbol","url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate/syncPreloadLoggedInUserBackgrounds(userIdentifier:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate\/syncPreloadLoggedInUserBackgrounds(userIdentifier:)","url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate\/syncpreloadloggedinuserbackgrounds(useridentifier:)","navigatorTitle":[{"kind":"identifier","text":"syncPreloadLoggedInUserBackgroundsWithUserIdentifier:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncPreloadLoggedInUserBackgrounds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"title":"syncPreloadLoggedInUserBackgrounds(userIdentifier:)","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Preloads all backgrounds associated with the logged-in user."}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"syncPreloadLoggedInUserBackgroundsWithUserIdentifier:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"syncPreloadLoggedInUserBackgroundsWithUserIdentifier:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"syncPreloadLoggedInUserBackgroundsWithUserIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"userIdentifier","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ID of the user.","type":"text"}],"type":"paragraph"}],"name":"userIdentifier"}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/title","value":"SocialLayerMixtapeBackgroundsDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/fragments","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/navigatorTitle","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate~1syncPreloadLoggedInUserBackgrounds(userIdentifier:)\/title","value":"syncPreloadLoggedInUserBackgroundsWithUserIdentifier:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate~1syncPreloadLoggedInUserBackgrounds(userIdentifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"syncPreloadLoggedInUserBackgroundsWithUserIdentifier:","kind":"identifier"}],"op":"replace"}]}]}