{"abstract":[{"text":"true if this waveform is placeholder data, false otherwise","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placeholder"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"placeholder","kind":"identifier"}],"title":"placeholder","role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformModel(py)placeholder","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"variants":[{"paths":["\/documentation\/socialradio\/automixsdkwaveformmodel\/placeholder"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkwaveformmodel\/placeholder"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel\/placeholder","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel"]]},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel/placeholder":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","title":"placeholder","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel\/placeholder","type":"topic","url":"\/documentation\/socialradio\/automixsdkwaveformmodel\/placeholder","navigatorTitle":[{"kind":"identifier","text":"placeholder"}],"abstract":[{"text":"true if this waveform is placeholder data, false otherwise","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformModel":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformModel","abstract":[{"text":"AutomixSDKWaveformModel models the waveform of a track.","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkwaveformmodel","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"title":"AutomixSDKWaveformModel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"placeholder"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"placeholder","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"placeholder","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel~1placeholder\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel~1placeholder\/fragments","value":[{"text":"placeholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/title","value":"AutomixSDKWaveformModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformModel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}