{"variants":[{"paths":["\/documentation\/automixiq\/automixiqobjc\/addtrack(withidentifier:metadata:index:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"title":"addTrack(withIdentifier:metadata:index:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": ","kind":"text"},{"text":"AutomixIQTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQTrackModel"},{"text":"?, ","kind":"text"},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixIQ.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"role":"symbol","modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(cs)AutomixIQObjC(im)addTrackWithIdentifier:metadata:index:completion:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addTrack","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifier","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQTrackModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQTrackModel","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","text":"CompletionWithError","preciseIdentifier":"c:AutomixIQ.h@T@CompletionWithError"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]},{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixIQTrackModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQTrackModel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/addTrack(withIdentifier:metadata:index:completion:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC/addTrack(withIdentifier:metadata:index:completion:)":{"abstract":[],"role":"symbol","url":"\/documentation\/automixiq\/automixiqobjc\/addtrack(withidentifier:metadata:index:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/addTrack(withIdentifier:metadata:index:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQTrackModel","text":"AutomixIQTrackModel","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"index","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:AutomixIQ.h@T@CompletionWithError","text":"CompletionWithError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"addTrack(withIdentifier:metadata:index:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTrackModel":{"title":"AutomixIQTrackModel","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTrackModel"}],"url":"\/documentation\/automixiq\/automixiqtrackmodel","abstract":[{"type":"text","text":"AutomixIQTrackModel models a track. This metadata is required."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTrackModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQTrackModel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC":{"kind":"symbol","title":"AutomixIQObjC","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC","url":"\/documentation\/automixiq\/automixiqobjc","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQObjC"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/CompletionWithError":{"url":"\/documentation\/automixiq\/completionwitherror","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","title":"CompletionWithError","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CompletionWithError"}],"navigatorTitle":[{"kind":"identifier","text":"CompletionWithError"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AutomixIQTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTrackModel\/title"},{"value":[{"text":"AutomixIQTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTrackModel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixIQTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTrackModel\/navigatorTitle"}]}]}