{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/initialise(with:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixIQConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig"},{"kind":"text","text":", "},{"text":"automixIQTunedRestDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"AutomixIQTunedRestDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStatusDelegate"},{"text":": (any ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate","kind":"typeIdentifier","text":"AutomixIQTunedMusicCacheDelegate"},{"kind":"text","text":")?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionWithError","preciseIdentifier":"c:AutomixIQ.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"modules":[{"name":"AutomixIQ"}],"externalID":"c:objc(cs)AutomixIQObjC(cm)initialiseWithConfig:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:","roleHeading":"Type Method","title":"initialise(with:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","text":"AutomixIQConfig"},{"text":", ","kind":"text"},{"text":"automixIQTunedRestDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate","text":"AutomixIQTunedRestDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automixIQStatusDelegate"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate","text":"AutomixIQTunedMusicCacheDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","preciseIdentifier":"c:AutomixIQ.h@T@CompletionWithError","text":"CompletionWithError"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]},{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","kind":"typeIdentifier","text":"AutomixIQConfig"},{"text":", ","kind":"text"},{"text":"automixIQTunedRestDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate","text":"AutomixIQTunedRestDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automixIQStatusDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate"},{"kind":"text","text":")?, "},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","text":"AutomixIQTunedMusicCacheDelegate"},{"text":")?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqobjc\/initialise(with:automixiqtunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"role":"symbol","title":"AutomixIQConfig","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"abstract":[],"url":"\/documentation\/automixiq\/automixiqconfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQConfig","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"title":"AutomixIQStatusObserverDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate":{"type":"topic","title":"AutomixIQTunedRestDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqtunedrestdelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedMusicCacheDelegate":{"role":"symbol","title":"AutomixIQTunedMusicCacheDelegate","navigatorTitle":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQTunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"url":"\/documentation\/automixiq\/automixiqtunedmusiccachedelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedMusicCacheDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/CompletionWithError":{"url":"\/documentation\/automixiq\/completionwitherror","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","title":"CompletionWithError","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CompletionWithError"}],"navigatorTitle":[{"kind":"identifier","text":"CompletionWithError"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC":{"kind":"symbol","title":"AutomixIQObjC","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC","url":"\/documentation\/automixiq\/automixiqobjc","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQObjC"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC/initialise(with:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)":{"role":"symbol","title":"initialise(with:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","abstract":[],"url":"\/documentation\/automixiq\/automixiqobjc\/initialise(with:automixiqtunedrestdelegate:automixiqstatusdelegate:musiccachedelegate:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/initialise(with:automixIQTunedRestDelegate:automixIQStatusDelegate:musicCacheDelegate:completion:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixIQConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"automixIQTunedRestDelegate"},{"kind":"text","text":": any "},{"text":"AutomixIQTunedRestDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"automixIQStatusDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedMusicCacheDelegate","kind":"typeIdentifier","text":"AutomixIQTunedMusicCacheDelegate"},{"kind":"text","text":")?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixIQ.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AutomixIQConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title","value":"AutomixIQStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]},{"value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/title","value":"AutomixIQTunedRestDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/fragments","value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/title","value":"AutomixIQTunedMusicCacheDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/fragments","value":[{"text":"AutomixIQTunedMusicCacheDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedMusicCacheDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQTunedMusicCacheDelegate"}],"op":"replace"}]}]}