{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel\/logLevelDebug"},"metadata":{"modules":[{"name":"SocialRadio"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@SocialRadio@E@AutomixIQLogLevel@AutomixIQLogLevelLogLevelDebug","symbolKind":"case","title":"AutomixIQLogLevel.logLevelDebug","navigatorTitle":[{"text":"AutomixIQLogLevelLogLevelDebug","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"logLevelDebug","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"logLevelDebug","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel"]]},"variants":[{"paths":["\/documentation\/socialradio\/automixiqloglevel\/logleveldebug"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqloglevel\/logleveldebug"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQLogLevel/logLevelDebug":{"type":"topic","abstract":[],"title":"AutomixIQLogLevel.logLevelDebug","role":"symbol","url":"\/documentation\/socialradio\/automixiqloglevel\/logleveldebug","navigatorTitle":[{"kind":"identifier","text":"AutomixIQLogLevelLogLevelDebug"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel\/logLevelDebug","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"logLevelDebug","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQLogLevel":{"type":"topic","title":"AutomixIQLogLevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixIQLogLevel","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"abstract":[{"type":"text","text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels"}],"url":"\/documentation\/socialradio\/automixiqloglevel"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"AutomixIQLogLevelLogLevelDebug","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AutomixIQLogLevelLogLevelDebug"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixIQLogLevelLogLevelDebug","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel~1logLevelDebug\/title","value":"AutomixIQLogLevelLogLevelDebug"},{"value":[{"text":"AutomixIQLogLevelLogLevelDebug","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel~1logLevelDebug\/fragments"},{"value":"AutomixIQLogLevel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/title"},{"value":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/fragments"},{"value":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}