{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelWarning"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixiqloglevel\/loglevelwarning"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixiqloglevel\/loglevelwarning"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel\/logLevelWarning","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@E@AutomixIQLogLevel@AutomixIQLogLevelLogLevelWarning","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"logLevelWarning","kind":"identifier"}],"role":"symbol","title":"AutomixIQLogLevel.logLevelWarning","navigatorTitle":[{"kind":"identifier","text":"AutomixIQLogLevelLogLevelWarning"}],"roleHeading":"Case"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQLogLevel/logLevelWarning":{"abstract":[],"type":"topic","url":"\/documentation\/socialradio\/automixiqloglevel\/loglevelwarning","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelWarning"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel\/logLevelWarning","title":"AutomixIQLogLevel.logLevelWarning","role":"symbol","navigatorTitle":[{"text":"AutomixIQLogLevelLogLevelWarning","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQLogLevel":{"type":"topic","title":"AutomixIQLogLevel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixIQLogLevel","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"abstract":[{"type":"text","text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels"}],"url":"\/documentation\/socialradio\/automixiqloglevel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"AutomixIQLogLevelLogLevelWarning","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"AutomixIQLogLevelLogLevelWarning","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixIQLogLevelLogLevelWarning"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel~1logLevelWarning\/title","value":"AutomixIQLogLevelLogLevelWarning","op":"replace"},{"value":[{"text":"AutomixIQLogLevelLogLevelWarning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel~1logLevelWarning\/fragments"},{"value":"AutomixIQLogLevel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/title"},{"value":[{"kind":"identifier","text":"AutomixIQLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQLogLevel\/navigatorTitle","value":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}