{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiomixtapetrack\/artist"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiomixtapetrack\/artist"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/artist","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"artist"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"SocialRadioLite"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"artist"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioMixtapeTrack(py)artist","navigatorTitle":[{"kind":"identifier","text":"artist"}],"symbolKind":"property","title":"artist"},"abstract":[{"type":"text","text":"The artist name"}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack":{"type":"topic","title":"SocialRadioMixtapeTrack","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/artist":{"role":"symbol","navigatorTitle":[{"text":"artist","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/artist","abstract":[{"text":"The artist name","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"artist","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/artist","title":"artist","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"artist","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"artist"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"artist","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"SocialRadioMixtapeTrack","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/fragments","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/navigatorTitle","op":"replace"},{"value":"artist","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1artist\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1artist\/fragments","value":[{"text":"artist","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}