{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"service"}],"role":"symbol","modules":[{"name":"SocialRadioLite"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"service","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"service","externalID":"c:@M@SocialRadioLite@objc(cs)SocialRadioMixtapeTrack(py)service","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/service"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"service","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}]}],"abstract":[{"type":"text","text":"The identifier for the type of track"}],"variants":[{"paths":["\/documentation\/socialradiolite\/socialradiomixtapetrack\/service"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiomixtapetrack\/service"]}],"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack/service":{"navigatorTitle":[{"text":"service","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack\/service","title":"service","kind":"symbol","abstract":[{"text":"The identifier for the type of track","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"service","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapetrack\/service"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack":{"type":"topic","title":"SocialRadioMixtapeTrack","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"service","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"service","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"service"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"service","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1service\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack~1service\/fragments","value":[{"kind":"identifier","text":"service"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/title","value":"SocialRadioMixtapeTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/fragments","op":"replace","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/navigatorTitle"}]}]}