{"sections":[],"metadata":{"roleHeading":"Case","modules":[{"name":"SocialRadio"}],"symbolKind":"case","navigatorTitle":[{"text":"SocialRadioLogLevelLogLevelWarning","kind":"identifier"}],"role":"symbol","title":"SocialRadioLogLevel.logLevelWarning","externalID":"c:@M@SocialRadio@E@SocialRadioLogLevel@SocialRadioLogLevelLogLevelWarning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelWarning"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel\/logLevelWarning","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiologlevel\/loglevelwarning"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiologlevel\/loglevelwarning"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelWarning","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioLogLevel":{"abstract":[{"text":"SocialRadio’s available log levels","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel","role":"symbol","kind":"symbol","title":"SocialRadioLogLevel","type":"topic","navigatorTitle":[{"text":"SocialRadioLogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioLogLevel","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiologlevel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioLogLevel/logLevelWarning":{"title":"SocialRadioLogLevel.logLevelWarning","url":"\/documentation\/socialradio\/socialradiologlevel\/loglevelwarning","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioLogLevel\/logLevelWarning","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelWarning","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SocialRadioLogLevelLogLevelWarning","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","title":"SocialRadio"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SocialRadioLogLevelLogLevelWarning","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SocialRadioLogLevelLogLevelWarning","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelWarning"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SocialRadioLogLevel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel\/navigatorTitle"},{"op":"replace","value":"SocialRadioLogLevelLogLevelWarning","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel~1logLevelWarning\/title"},{"op":"replace","value":[{"text":"SocialRadioLogLevelLogLevelWarning","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioLogLevel~1logLevelWarning\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}