{"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"asyncGetThumborLocationWithCompletion:"}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"asyncGetThumborLocation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"asyncGetThumborLocation(completion:)","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Method","externalID":"c:@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate(im)asyncGetThumborLocationWithCompletion:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate"]]},"kind":"symbol","abstract":[{"type":"text","text":"Called by the AutomixIQ SDK when it needs the URL for thumbor. Return nil on completion if there is none"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate\/asyncGetThumborLocation(completion:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"asyncGetThumborLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"url","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request","type":"text"}],"type":"paragraph"}],"name":"completion"}]}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiostreamingdelegate\/asyncgetthumborlocation(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiostreamingdelegate\/asyncgetthumborlocation(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStreamingDelegate/asyncGetThumborLocation(completion:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate\/asyncGetThumborLocation(completion:)","abstract":[{"type":"text","text":"Called by the AutomixIQ SDK when it needs the URL for thumbor. Return nil on completion if there is none"}],"title":"asyncGetThumborLocation(completion:)","required":true,"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/socialradiostreamingdelegate\/asyncgetthumborlocation(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetThumborLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"asyncGetThumborLocationWithCompletion:"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStreamingDelegate":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiostreamingdelegate","title":"SocialRadioStreamingDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"abstract":[{"type":"text","text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"asyncGetThumborLocationWithCompletion:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetThumborLocationWithCompletion:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"asyncGetThumborLocationWithCompletion:"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}]}],"name":"completion"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate~1asyncGetThumborLocation(completion:)\/title","value":"asyncGetThumborLocationWithCompletion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"asyncGetThumborLocationWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate~1asyncGetThumborLocation(completion:)\/fragments"},{"value":"SocialRadioStreamingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}]},{"op":"replace","value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}