{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/errorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/errorcode"]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH","doc:\/\/org.cocoapods.AutomixIQ\/SY"]}],"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cancelled","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotDownloadAd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotInterruptAd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/didNotAddAdIndexPassedAlready","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/failedToStop","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/notMainThread","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/unable_to_load_mix","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/unimplemented"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/Equatable-Implementations","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"sections":[],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"symbolKind":"enum","role":"symbol","externalID":"c:@M@AutomixIQ@E@ErrorCode","roleHeading":"Enumeration","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"title":"ErrorCode"},"kind":"symbol","seeAlsoSections":[{"title":"Errors","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article"],"anchor":"Errors"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"notMainThread","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to use the SDK from any thread not main"}],"type":"paragraph"}]},{"name":"sdkNotInitialised","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to use the SDK prior to initialising it"}],"type":"paragraph"}]},{"name":"sdkNotOn","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to use playback controls when AutomixIQ is not on"}],"type":"paragraph"}]},{"name":"sdkAlreadyOn","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn on AutomixIQ but it is already on"}],"type":"paragraph"}]},{"name":"loadTracksEmptyPlaylist","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to load an empty playlist"}],"type":"paragraph"}]},{"name":"loadTracksOutOfBounds","content":[{"inlineContent":[{"type":"text","text":""}],"type":"paragraph"}]},{"name":"addTrackPlaylistDoesNotExist","content":[{"inlineContent":[{"type":"text","text":""}],"type":"paragraph"}]},{"name":"addTrackOutOfBounds","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to insert a track at a position outside the bounds of the loaded playlist"}],"type":"paragraph"}]},{"name":"addTrackNoMetadata","content":[{"inlineContent":[{"type":"text","text":"Thrown when the metadata for a track you are trying to load is not available and could not be downloaded"}],"type":"paragraph"}]},{"name":"addTrackInternalError","content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails internally (not user error)"}],"type":"paragraph"}]},{"name":"removeTrackOutOfBounds","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to remove a track at a position outside the bounds of the loaded playlist"}],"type":"paragraph"}]},{"name":"playAlreadyPlaying","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to play but AutomixIQ is already playing"}],"type":"paragraph"}]},{"name":"pauseAlreadyPaused","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to pause but AutomixIQ is already paused"}],"type":"paragraph"}]},{"name":"previousNoTrackAvailable","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to go to the previous track but AutomixIQ is already on the first in the playlist and “Repeat” is off"}],"type":"paragraph"}]},{"name":"nextNoTrackAvailable","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to go to the next track but AutomixIQ is already on the last in the playlist and “Repeat” is off"}],"type":"paragraph"}]},{"name":"backNoTrackAvailable","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to go to the start of a track but the playlist is empty"}],"type":"paragraph"}]},{"name":"seekNoTrackAvailable","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to seek to a track but the playlist is empty or the index is out of bounds of the playlist"}],"type":"paragraph"}]},{"name":"seekNoCurrentTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to seek within a track but the playlist is empty or the track is not yet loaded"}],"type":"paragraph"}]},{"name":"reorderMissingTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to move a track that is not on the loaded playlist"}],"type":"paragraph"}]},{"name":"playToEndMissingTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to select a track to be played until the end but that track is not on the loaded playlist"}],"type":"paragraph"}]},{"name":"moveTrackOutOfBounds","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to move a track at a position outside the bounds of the loaded playlist"}],"type":"paragraph"}]},{"name":"startLoopingNoLoopingTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to stop looping a track but that track is not on the loaded playlist"}],"type":"paragraph"}]},{"name":"stopLoopingNoLoopingTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to loop a track but that track is not on the loaded playlist"}],"type":"paragraph"}]},{"name":"unimplemented","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to use an unimplemented method of the SDK"}],"type":"paragraph"}]},{"name":"cancelled","content":[{"inlineContent":[{"type":"text","text":"Thrown when an action you previously issued to AutomixIQ is cancelled due to another user initialed action that overrides it"}],"type":"paragraph"}]},{"name":"onAlreadyTurningOn","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ on while it is already turning on"}],"type":"paragraph"}]},{"name":"onWhileTurningOff","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ on while it is already turning off"}],"type":"paragraph"}]},{"name":"offAlreadyTurningOff","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ off while it is already turning off"}],"type":"paragraph"}]},{"name":"offWhileTurningOn","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ off while it is already turning on"}],"type":"paragraph"}]},{"name":"cannotCreateChannelLayout","content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the channel layout"}],"type":"paragraph"}]},{"name":"cannotCreateInputBuffer","content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the input buffer"}],"type":"paragraph"}]},{"name":"cannotSetupAVAudioSession","content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the AVAudioSession"}],"type":"paragraph"}]},{"name":"cannotStartAudioEngine","content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to start the audio engine"}],"type":"paragraph"}]},{"name":"cannotRestoreAudioSession","content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to restore the audio session to the state it found it when you turned it on"}],"type":"paragraph"}]},{"name":"failedToStop","content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ is unable to be stopped"}],"type":"paragraph"}]},{"name":"cannotLoadExplicitLyricsTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to load an explicit track but the setting to filter out explicit tracks is on"}],"type":"paragraph"}]},{"name":"cannotDownloadAd","content":[{"inlineContent":[{"type":"text","text":"Thrown when you fail to download the ad from the url provided"}],"type":"paragraph"}]},{"name":"cannotInterruptAd","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to do something you cannot do while playing an ad"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/addTrackPlaylistDoesNotExist":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"title":"ErrorCode.addTrackPlaylistDoesNotExist","url":"\/documentation\/automixiq\/errorcode\/addtrackplaylistdoesnotexist","navigatorTitle":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackPlaylistDoesNotExist","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotRestoreAudioSession":{"url":"\/documentation\/automixiq\/errorcode\/cannotrestoreaudiosession","navigatorTitle":[{"text":"ErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"type":"topic","title":"ErrorCode.cannotRestoreAudioSession","role":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotRestoreAudioSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotRestoreAudioSession","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/seekNoCurrentTrack":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekNoCurrentTrack","kind":"identifier"}],"title":"ErrorCode.seekNoCurrentTrack","url":"\/documentation\/automixiq\/errorcode\/seeknocurrenttrack","navigatorTitle":[{"text":"ErrorCodeSeekNoCurrentTrack","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/seekNoCurrentTrack","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/moveTrackOutOfBounds":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveTrackOutOfBounds","kind":"identifier"}],"title":"ErrorCode.moveTrackOutOfBounds","url":"\/documentation\/automixiq\/errorcode\/movetrackoutofbounds","navigatorTitle":[{"text":"ErrorCodeMoveTrackOutOfBounds","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/moveTrackOutOfBounds","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/Equatable-Implementations":{"abstract":[],"kind":"article","title":"Equatable Implementations","url":"\/documentation\/automixiq\/errorcode\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/Equatable-Implementations","role":"collectionGroup","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/didNotAddAdIndexPassedAlready":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didNotAddAdIndexPassedAlready","kind":"identifier"}],"title":"ErrorCode.didNotAddAdIndexPassedAlready","url":"\/documentation\/automixiq\/errorcode\/didnotaddadindexpassedalready","navigatorTitle":[{"text":"ErrorCodeDidNotAddAdIndexPassedAlready","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/didNotAddAdIndexPassedAlready","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/onAlreadyTurningOn":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onAlreadyTurningOn","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/onAlreadyTurningOn","url":"\/documentation\/automixiq\/errorcode\/onalreadyturningon","title":"ErrorCode.onAlreadyTurningOn","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"title":"ErrorCode","url":"\/documentation\/automixiq\/errorcode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/RawRepresentable-Implementations":{"abstract":[],"kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/automixiq\/errorcode\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/failedToStop":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToStop","kind":"identifier"}],"title":"ErrorCode.failedToStop","url":"\/documentation\/automixiq\/errorcode\/failedtostop","navigatorTitle":[{"text":"ErrorCodeFailedToStop","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/failedToStop","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/sdkAlreadyOn":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkAlreadyOn","kind":"identifier"}],"title":"ErrorCode.sdkAlreadyOn","url":"\/documentation\/automixiq\/errorcode\/sdkalreadyon","navigatorTitle":[{"text":"ErrorCodeSdkAlreadyOn","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyOn","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/onWhileTurningOff":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onWhileTurningOff","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeOnWhileTurningOff","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/onWhileTurningOff","url":"\/documentation\/automixiq\/errorcode\/onwhileturningoff","title":"ErrorCode.onWhileTurningOff","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/sdkNotInitialisedVersionNoLongerSupported":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"title":"ErrorCode.sdkNotInitialisedVersionNoLongerSupported","url":"\/documentation\/automixiq\/errorcode\/sdknotinitialisedversionnolongersupported","navigatorTitle":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/sdkInitialisationUnauthorised":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkInitialisationUnauthorised","kind":"identifier"}],"title":"ErrorCode.sdkInitialisationUnauthorised","url":"\/documentation\/automixiq\/errorcode\/sdkinitialisationunauthorised","navigatorTitle":[{"text":"ErrorCodeSdkInitialisationUnauthorised","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkInitialisationUnauthorised","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotStartAudioEngine":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotStartAudioEngine","kind":"identifier"}],"title":"ErrorCode.cannotStartAudioEngine","url":"\/documentation\/automixiq\/errorcode\/cannotstartaudioengine","navigatorTitle":[{"text":"ErrorCodeCannotStartAudioEngine","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotStartAudioEngine","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/addTrackNoMetadata":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackNoMetadata","kind":"identifier"}],"title":"ErrorCode.addTrackNoMetadata","url":"\/documentation\/automixiq\/errorcode\/addtracknometadata","navigatorTitle":[{"text":"ErrorCodeAddTrackNoMetadata","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackNoMetadata","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/noInternetAvailableTooLongOffline":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}],"title":"ErrorCode.noInternetAvailableTooLongOffline","url":"\/documentation\/automixiq\/errorcode\/nointernetavailabletoolongoffline","navigatorTitle":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/noInternetAvailableTooLongOffline","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/sdkNotInitialised":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialised","kind":"identifier"}],"title":"ErrorCode.sdkNotInitialised","url":"\/documentation\/automixiq\/errorcode\/sdknotinitialised","navigatorTitle":[{"text":"ErrorCodeSdkNotInitialised","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotInitialised","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/unimplemented":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unimplemented","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeUnimplemented","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/unimplemented","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/unimplemented","title":"ErrorCode.unimplemented"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/playToEndMixEnd":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playToEndMixEnd","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodePlayToEndMixEnd","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/playtoendmixend","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/playToEndMixEnd","title":"ErrorCode.playToEndMixEnd"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/noInternetAvailable":{"kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailable","kind":"identifier"}],"title":"ErrorCode.noInternetAvailable","url":"\/documentation\/automixiq\/errorcode\/nointernetavailable","navigatorTitle":[{"text":"ErrorCodeNoInternetAvailable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/noInternetAvailable","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotDownloadAd":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotDownloadAd","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeCannotDownloadAd","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/cannotdownloadad","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotDownloadAd","title":"ErrorCode.cannotDownloadAd"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotCreateInputBuffer":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotCreateInputBuffer"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCannotCreateInputBuffer"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotCreateInputBuffer","url":"\/documentation\/automixiq\/errorcode\/cannotcreateinputbuffer","title":"ErrorCode.cannotCreateInputBuffer","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/previousNoTrackAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousNoTrackAvailable","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePreviousNoTrackAvailable"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/previousnotrackavailable","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/previousNoTrackAvailable","title":"ErrorCode.previousNoTrackAvailable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/init(rawValue:)":{"url":"\/documentation\/automixiq\/errorcode\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/init(rawValue:)","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/sdkAlreadyInitialised":{"url":"\/documentation\/automixiq\/errorcode\/sdkalreadyinitialised","navigatorTitle":[{"text":"ErrorCodeSdkAlreadyInitialised","kind":"identifier"}],"type":"topic","title":"ErrorCode.sdkAlreadyInitialised","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sdkAlreadyInitialised","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyInitialised","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/addTrackInternalError":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackInternalError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackInternalError","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode\/addtrackinternalerror","role":"symbol","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"ErrorCodeAddTrackInternalError","kind":"identifier"}],"title":"ErrorCode.addTrackInternalError"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/removeTrackOutOfBounds":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeTrackOutOfBounds","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/removetrackoutofbounds","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/removeTrackOutOfBounds","title":"ErrorCode.removeTrackOutOfBounds"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cancelled":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCancelled"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/cancelled","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cancelled","title":"ErrorCode.cancelled"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/playToEndMissingTrack":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/playToEndMissingTrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playToEndMissingTrack"}],"url":"\/documentation\/automixiq\/errorcode\/playtoendmissingtrack","role":"symbol","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePlayToEndMissingTrack"}],"title":"ErrorCode.playToEndMissingTrack"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/seekNoTrackAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekNoTrackAvailable","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/seeknotrackavailable","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/seekNoTrackAvailable","title":"ErrorCode.seekNoTrackAvailable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/loadTracksOutOfBounds":{"title":"ErrorCode.loadTracksOutOfBounds","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/loadtracksoutofbounds","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksOutOfBounds","role":"symbol","type":"topic","navigatorTitle":[{"text":"ErrorCodeLoadTracksOutOfBounds","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracksOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/offWhileTurningOn":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offWhileTurningOn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offWhileTurningOn","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode\/offwhileturningon","role":"symbol","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ErrorCodeOffWhileTurningOn","kind":"identifier"}],"title":"ErrorCode.offWhileTurningOn"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/playAlreadyPlaying":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playAlreadyPlaying"}],"url":"\/documentation\/automixiq\/errorcode\/playalreadyplaying","title":"ErrorCode.playAlreadyPlaying","navigatorTitle":[{"kind":"identifier","text":"ErrorCodePlayAlreadyPlaying"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/playAlreadyPlaying","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotSetupAVAudioSession":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotSetupAVAudioSession","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeCannotSetupAVAudioSession","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/cannotsetupavaudiosession","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotSetupAVAudioSession","title":"ErrorCode.cannotSetupAVAudioSession"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/startLoopingNoLoopingTrack":{"url":"\/documentation\/automixiq\/errorcode\/startloopingnoloopingtrack","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"type":"topic","title":"ErrorCode.startLoopingNoLoopingTrack","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startLoopingNoLoopingTrack"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/startLoopingNoLoopingTrack","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Errors-article":{"abstract":[{"type":"text","text":"What errors the AutomixIQ player can issue to help with player integration"}],"kind":"article","title":"Errors","url":"\/documentation\/automixiq\/errors-article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article","role":"article","type":"topic"},"doc://org.cocoapods.AutomixIQ/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SY"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotLoadExplicitLyricsTrack":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotLoadExplicitLyricsTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode\/cannotloadexplicitlyricstrack","role":"symbol","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"title":"ErrorCode.cannotLoadExplicitLyricsTrack"},"doc://org.cocoapods.AutomixIQ/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/pauseAlreadyPaused":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseAlreadyPaused","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodePauseAlreadyPaused","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/pausealreadypaused","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/pauseAlreadyPaused","title":"ErrorCode.pauseAlreadyPaused"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/backNoTrackAvailable":{"navigatorTitle":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/backNoTrackAvailable","url":"\/documentation\/automixiq\/errorcode\/backnotrackavailable","title":"ErrorCode.backNoTrackAvailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backNoTrackAvailable","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/stopLoopingNoLoopingTrack":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLoopingNoLoopingTrack","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/stoploopingnoloopingtrack","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/stopLoopingNoLoopingTrack","title":"ErrorCode.stopLoopingNoLoopingTrack"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/loadTracksEmptyPlaylist":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracksEmptyPlaylist","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/loadtracksemptyplaylist","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksEmptyPlaylist","title":"ErrorCode.loadTracksEmptyPlaylist"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/sdkNotOn":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotOn","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeSdkNotOn","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/sdknoton","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotOn","title":"ErrorCode.sdkNotOn"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/offAlreadyTurningOff":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offAlreadyTurningOff","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/offalreadyturningoff","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offAlreadyTurningOff","title":"ErrorCode.offAlreadyTurningOff"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/nextNoTrackAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextNoTrackAvailable","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeNextNoTrackAvailable","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/nextnotrackavailable","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/nextNoTrackAvailable","title":"ErrorCode.nextNoTrackAvailable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotInterruptAd":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotInterruptAd","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeCannotInterruptAd","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/cannotinterruptad","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotInterruptAd","title":"ErrorCode.cannotInterruptAd"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/cannotCreateChannelLayout":{"url":"\/documentation\/automixiq\/errorcode\/cannotcreatechannellayout","navigatorTitle":[{"text":"ErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"type":"topic","title":"ErrorCode.cannotCreateChannelLayout","role":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotCreateChannelLayout","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotCreateChannelLayout","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/addTrackOutOfBounds":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackOutOfBounds","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeAddTrackOutOfBounds","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/addtrackoutofbounds","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackOutOfBounds","title":"ErrorCode.addTrackOutOfBounds"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/offlineNoTunedUserIdAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/offlinenotuneduseridavailable","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offlineNoTunedUserIdAvailable","title":"ErrorCode.offlineNoTunedUserIdAvailable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/reorderMissingTrack":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reorderMissingTrack","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeReorderMissingTrack","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/reordermissingtrack","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/reorderMissingTrack","title":"ErrorCode.reorderMissingTrack"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/unable_to_load_mix":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unable_to_load_mix"}],"navigatorTitle":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/unable_to_load_mix","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/unable_to_load_mix","title":"ErrorCode.unable_to_load_mix"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/notMainThread":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notMainThread","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeNotMainThread"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/errorcode\/notmainthread","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/notMainThread","title":"ErrorCode.notMainThread"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"ErrorCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cancelled","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotDownloadAd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotInterruptAd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/didNotAddAdIndexPassedAlready","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/failedToStop","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/notMainThread","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/unable_to_load_mix","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/unimplemented"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":[{"generated":true,"title":"Errors","anchor":"Errors","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeAddTrackPlaylistDoesNotExist","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackPlaylistDoesNotExist\/title"},{"value":[{"text":"ErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackPlaylistDoesNotExist\/fragments"},{"value":"ErrorCodeCannotRestoreAudioSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotRestoreAudioSession\/title"},{"value":[{"text":"ErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotRestoreAudioSession\/fragments"},{"value":"ErrorCodeSeekNoCurrentTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1seekNoCurrentTrack\/title"},{"value":[{"text":"ErrorCodeSeekNoCurrentTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1seekNoCurrentTrack\/fragments"},{"value":"ErrorCodeMoveTrackOutOfBounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1moveTrackOutOfBounds\/title"},{"value":[{"text":"ErrorCodeMoveTrackOutOfBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1moveTrackOutOfBounds\/fragments"},{"value":"ErrorCodeDidNotAddAdIndexPassedAlready","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1didNotAddAdIndexPassedAlready\/title"},{"value":[{"text":"ErrorCodeDidNotAddAdIndexPassedAlready","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1didNotAddAdIndexPassedAlready\/fragments"},{"value":"ErrorCodeOnAlreadyTurningOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1onAlreadyTurningOn\/title"},{"value":[{"text":"ErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1onAlreadyTurningOn\/fragments"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle"},{"value":"ErrorCodeFailedToStop","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1failedToStop\/title"},{"value":[{"text":"ErrorCodeFailedToStop","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1failedToStop\/fragments"},{"value":"ErrorCodeSdkAlreadyOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkAlreadyOn\/title"},{"value":[{"text":"ErrorCodeSdkAlreadyOn","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkAlreadyOn\/fragments"},{"value":"ErrorCodeOnWhileTurningOff","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1onWhileTurningOff\/title"},{"value":[{"text":"ErrorCodeOnWhileTurningOff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1onWhileTurningOff\/fragments"},{"value":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/title"},{"value":[{"text":"ErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/fragments"},{"value":"ErrorCodeSdkInitialisationUnauthorised","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkInitialisationUnauthorised\/title"},{"value":[{"text":"ErrorCodeSdkInitialisationUnauthorised","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkInitialisationUnauthorised\/fragments"},{"value":"ErrorCodeCannotStartAudioEngine","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotStartAudioEngine\/title"},{"value":[{"text":"ErrorCodeCannotStartAudioEngine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotStartAudioEngine\/fragments"},{"value":"ErrorCodeAddTrackNoMetadata","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackNoMetadata\/title"},{"value":[{"text":"ErrorCodeAddTrackNoMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackNoMetadata\/fragments"},{"value":"ErrorCodeNoInternetAvailableTooLongOffline","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1noInternetAvailableTooLongOffline\/title"},{"value":[{"text":"ErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1noInternetAvailableTooLongOffline\/fragments"},{"value":"ErrorCodeSdkNotInitialised","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkNotInitialised\/title"},{"value":[{"text":"ErrorCodeSdkNotInitialised","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkNotInitialised\/fragments"},{"value":"ErrorCodeUnimplemented","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1unimplemented\/title"},{"value":[{"text":"ErrorCodeUnimplemented","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1unimplemented\/fragments"},{"value":"ErrorCodePlayToEndMixEnd","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1playToEndMixEnd\/title"},{"value":[{"text":"ErrorCodePlayToEndMixEnd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1playToEndMixEnd\/fragments"},{"value":"ErrorCodeNoInternetAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1noInternetAvailable\/title"},{"value":[{"text":"ErrorCodeNoInternetAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1noInternetAvailable\/fragments"},{"value":"ErrorCodeCannotDownloadAd","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotDownloadAd\/title"},{"value":[{"text":"ErrorCodeCannotDownloadAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotDownloadAd\/fragments"},{"value":"ErrorCodeCannotCreateInputBuffer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotCreateInputBuffer\/title"},{"value":[{"text":"ErrorCodeCannotCreateInputBuffer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotCreateInputBuffer\/fragments"},{"value":"ErrorCodePreviousNoTrackAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1previousNoTrackAvailable\/title"},{"value":[{"text":"ErrorCodePreviousNoTrackAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1previousNoTrackAvailable\/fragments"},{"value":"ErrorCodeSdkAlreadyInitialised","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkAlreadyInitialised\/title"},{"value":[{"text":"ErrorCodeSdkAlreadyInitialised","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkAlreadyInitialised\/fragments"},{"value":"ErrorCodeAddTrackInternalError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackInternalError\/title"},{"value":[{"text":"ErrorCodeAddTrackInternalError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackInternalError\/fragments"},{"value":"ErrorCodeRemoveTrackOutOfBounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1removeTrackOutOfBounds\/title"},{"value":[{"text":"ErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1removeTrackOutOfBounds\/fragments"},{"value":"ErrorCodeCancelled","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cancelled\/title"},{"value":[{"text":"ErrorCodeCancelled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cancelled\/fragments"},{"value":"ErrorCodePlayToEndMissingTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1playToEndMissingTrack\/title"},{"value":[{"text":"ErrorCodePlayToEndMissingTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1playToEndMissingTrack\/fragments"},{"value":"ErrorCodeSeekNoTrackAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1seekNoTrackAvailable\/title"},{"value":[{"text":"ErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1seekNoTrackAvailable\/fragments"},{"value":"ErrorCodeLoadTracksOutOfBounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1loadTracksOutOfBounds\/title"},{"value":[{"text":"ErrorCodeLoadTracksOutOfBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1loadTracksOutOfBounds\/fragments"},{"value":"ErrorCodeOffWhileTurningOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offWhileTurningOn\/title"},{"value":[{"text":"ErrorCodeOffWhileTurningOn","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offWhileTurningOn\/fragments"},{"value":"ErrorCodePlayAlreadyPlaying","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1playAlreadyPlaying\/title"},{"value":[{"text":"ErrorCodePlayAlreadyPlaying","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1playAlreadyPlaying\/fragments"},{"value":"ErrorCodeCannotSetupAVAudioSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotSetupAVAudioSession\/title"},{"value":[{"text":"ErrorCodeCannotSetupAVAudioSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotSetupAVAudioSession\/fragments"},{"value":"ErrorCodeStartLoopingNoLoopingTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1startLoopingNoLoopingTrack\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1startLoopingNoLoopingTrack\/fragments","value":[{"kind":"identifier","text":"ErrorCodeStartLoopingNoLoopingTrack"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotLoadExplicitLyricsTrack\/title","value":"ErrorCodeCannotLoadExplicitLyricsTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotLoadExplicitLyricsTrack\/fragments","value":[{"text":"ErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1pauseAlreadyPaused\/title","value":"ErrorCodePauseAlreadyPaused","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1pauseAlreadyPaused\/fragments","value":[{"kind":"identifier","text":"ErrorCodePauseAlreadyPaused"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1backNoTrackAvailable\/title","value":"ErrorCodeBackNoTrackAvailable","op":"replace"},{"value":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1backNoTrackAvailable\/fragments","op":"replace"},{"value":"ErrorCodeStopLoopingNoLoopingTrack","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1stopLoopingNoLoopingTrack\/title","op":"replace"},{"value":[{"text":"ErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1stopLoopingNoLoopingTrack\/fragments","op":"replace"},{"value":"ErrorCodeLoadTracksEmptyPlaylist","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1loadTracksEmptyPlaylist\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ErrorCodeLoadTracksEmptyPlaylist"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1loadTracksEmptyPlaylist\/fragments","op":"replace"},{"value":"ErrorCodeSdkNotOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkNotOn\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeSdkNotOn"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1sdkNotOn\/fragments","op":"replace"},{"value":"ErrorCodeOffAlreadyTurningOff","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offAlreadyTurningOff\/title","op":"replace"},{"value":[{"text":"ErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offAlreadyTurningOff\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1nextNoTrackAvailable\/title","value":"ErrorCodeNextNoTrackAvailable","op":"replace"},{"value":[{"text":"ErrorCodeNextNoTrackAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1nextNoTrackAvailable\/fragments"},{"value":"ErrorCodeCannotInterruptAd","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotInterruptAd\/title"},{"value":[{"text":"ErrorCodeCannotInterruptAd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotInterruptAd\/fragments"},{"value":"ErrorCodeCannotCreateChannelLayout","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotCreateChannelLayout\/title"},{"value":[{"text":"ErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1cannotCreateChannelLayout\/fragments"},{"value":"ErrorCodeAddTrackOutOfBounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackOutOfBounds\/title"},{"value":[{"text":"ErrorCodeAddTrackOutOfBounds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1addTrackOutOfBounds\/fragments"},{"value":"ErrorCodeOfflineNoTunedUserIdAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offlineNoTunedUserIdAvailable\/title"},{"value":[{"text":"ErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1offlineNoTunedUserIdAvailable\/fragments"},{"value":"ErrorCodeReorderMissingTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1reorderMissingTrack\/title"},{"value":[{"text":"ErrorCodeReorderMissingTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1reorderMissingTrack\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1unable_to_load_mix\/title","op":"replace","value":"ErrorCodeUnable_to_load_mix"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1unable_to_load_mix\/fragments","value":[{"kind":"identifier","text":"ErrorCodeUnable_to_load_mix"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1notMainThread\/title","op":"replace","value":"ErrorCodeNotMainThread"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1notMainThread\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCodeNotMainThread"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}