{"abstract":[{"type":"text","text":"Attempts to commit a co-creation mixtape."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/postUpdateMixtapeMetadata(identifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postUpdateMixtapeMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"newTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"recipe","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mixDictionary","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"oldMixHash","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"newMixHash","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"recipeJSONString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"tracksJSONString","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mixtape ID."}]}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional new title for the mix.","type":"text"}]}],"name":"newTitle"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Base64 Encoded recipe string.","type":"text"}]}],"name":"recipe"},{"content":[{"inlineContent":[{"text":"Updated mix metadata.","type":"text"}],"type":"paragraph"}],"name":"mixDictionary"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Previous hash of the mix.","type":"text"}]}],"name":"oldMixHash"},{"content":[{"type":"paragraph","inlineContent":[{"text":"New hash after changes.","type":"text"}]}],"name":"newMixHash"},{"content":[{"inlineContent":[{"text":"The JSON string representing the recipe’s metadata.","type":"text"}],"type":"paragraph"}],"name":"recipeJSONString"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JSON string representing the tracks in the recipe’s metadata.."}]}],"name":"tracksJSONString"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]}],"name":"completion"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/postupdatemixtapemetadata(identifier:newtitle:recipe:mixdictionary:oldmixhash:newmixhash:recipejsonstring:tracksjsonstring:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/postupdatemixtapemetadata(identifier:newtitle:recipe:mixdictionary:oldmixhash:newmixhash:recipejsonstring:tracksjsonstring:completion:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"postUpdateMixtapeMetadataWithIdentifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postUpdateMixtapeMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mixDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"oldMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tracksJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"modules":[{"name":"SocialRadio"}],"title":"postUpdateMixtapeMetadata(identifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerLiveMixtapeDelegate(im)postUpdateMixtapeMetadataWithIdentifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:","symbolKind":"method"},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate":{"role":"symbol","navigatorTitle":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"title":"SocialLayerLiveMixtapeDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding live mixtapes."}],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate/postUpdateMixtapeMetadata(identifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/postUpdateMixtapeMetadata(identifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postUpdateMixtapeMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"recipe"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mixDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"oldMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newMixHash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recipeJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tracksJSONString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/postupdatemixtapemetadata(identifier:newtitle:recipe:mixdictionary:oldmixhash:newmixhash:recipejsonstring:tracksjsonstring:completion:)","navigatorTitle":[{"kind":"identifier","text":"postUpdateMixtapeMetadataWithIdentifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:"}],"required":true,"kind":"symbol","title":"postUpdateMixtapeMetadata(identifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)","abstract":[{"type":"text","text":"Attempts to commit a co-creation mixtape."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"postUpdateMixtapeMetadataWithIdentifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"postUpdateMixtapeMetadataWithIdentifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"postUpdateMixtapeMetadataWithIdentifier:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"newTitle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"newTitle"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipe:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"recipe"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixDictionary:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,id>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mixDictionary"},{"kind":"text","text":" "},{"kind":"identifier","text":"oldMixHash:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"oldMixHash"},{"kind":"text","text":" "},{"kind":"identifier","text":"newMixHash:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"newMixHash"},{"kind":"text","text":" "},{"kind":"identifier","text":"recipeJSONString:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"recipeJSONString"},{"kind":"text","text":" "},{"kind":"identifier","text":"tracksJSONString:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tracksJSONString"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"identifier","content":[{"inlineContent":[{"type":"text","text":"The mixtape ID."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional new title for the mix."}]}],"name":"newTitle"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Base64 Encoded recipe string."}]}],"name":"recipe"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Updated mix metadata."}]}],"name":"mixDictionary"},{"content":[{"inlineContent":[{"text":"Previous hash of the mix.","type":"text"}],"type":"paragraph"}],"name":"oldMixHash"},{"content":[{"type":"paragraph","inlineContent":[{"text":"New hash after changes.","type":"text"}]}],"name":"newMixHash"},{"content":[{"inlineContent":[{"type":"text","text":"The JSON string representing the recipe’s metadata."}],"type":"paragraph"}],"name":"recipeJSONString"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JSON string representing the tracks in the recipe’s metadata.."}]}],"name":"tracksJSONString"},{"content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/title","value":"SocialLayerLiveMixtapeDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/navigatorTitle"},{"op":"replace","value":"postUpdateMixtapeMetadataWithIdentifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1postUpdateMixtapeMetadata(identifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"postUpdateMixtapeMetadataWithIdentifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1postUpdateMixtapeMetadata(identifier:newTitle:recipe:mixDictionary:oldMixHash:newMixHash:recipeJSONString:tracksJSONString:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}