{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayfinished"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayfinished"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayFinished"},"metadata":{"externalID":"c:@M@AutomixIQ@E@AutomixIQPlaybackEventType@AutomixIQPlaybackEventTypeTrackPlayFinished","title":"AutomixIQPlaybackEventType.trackPlayFinished","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayFinished"}],"role":"symbol","modules":[{"name":"AutomixIQ"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayFinished","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlayFinished","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType/trackPlayFinished":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/automixiq\/automixiqplaybackeventtype\/trackplayfinished","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayFinished","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType\/trackPlayFinished","navigatorTitle":[{"text":"AutomixIQPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"title":"AutomixIQPlaybackEventType.trackPlayFinished"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQPlaybackEventType":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQPlaybackEventType","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"url":"\/documentation\/automixiq\/automixiqplaybackeventtype","title":"AutomixIQPlaybackEventType","navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayFinished","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixIQPlaybackEventTypeTrackPlayFinished"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixIQPlaybackEventTypeTrackPlayFinished","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayFinished\/title"},{"op":"replace","value":[{"text":"AutomixIQPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType~1trackPlayFinished\/fragments"},{"op":"replace","value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/title"},{"op":"replace","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/fragments"},{"op":"replace","value":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQPlaybackEventType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}