{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/unable_to_load_mix"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"variants":[{"paths":["\/documentation\/automixiq\/errorcode\/unable_to_load_mix"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/errorcode\/unable_to_load_mix"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"ErrorCode.unable_to_load_mix","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unable_to_load_mix"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeUnable_to_load_mix"}],"modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeUnable_to_load_mix","roleHeading":"Case","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unable_to_load_mix","kind":"identifier"}]}]}],"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/unable_to_load_mix":{"title":"ErrorCode.unable_to_load_mix","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unable_to_load_mix","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode\/unable_to_load_mix","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/unable_to_load_mix"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"title":"ErrorCode","url":"\/documentation\/automixiq\/errorcode","role":"symbol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ErrorCodeUnable_to_load_mix","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeUnable_to_load_mix"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ErrorCodeUnable_to_load_mix","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ErrorCodeUnable_to_load_mix","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1unable_to_load_mix\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCodeUnable_to_load_mix"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1unable_to_load_mix\/fragments"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle"}]}]}