{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradio\/setsociallayerdelegates(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradio\/setsociallayerdelegates(_:)"]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)SocialRadio(im)setSocialLayerDelegates:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSocialLayerDelegates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SocialLayerDelegates","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates"},{"text":"?)","kind":"text"}],"title":"setSocialLayerDelegates(_:)","roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setSocialLayerDelegates:"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/setSocialLayerDelegates(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setSocialLayerDelegates","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"delegates","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SocialLayerDelegates","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates"},{"text":"?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"delegates","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The social layer delegates"}]}]}]},{"mentions":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article"],"kind":"mentions"}],"abstract":[{"type":"text","text":"Sets the Social Layer delegates"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerDelegates","kind":"identifier"}],"title":"SocialLayerDelegates","navigatorTitle":[{"text":"SocialLayerDelegates","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/sociallayerdelegates","abstract":[{"type":"text","text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions."},{"type":"text","text":" "},{"type":"text","text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc."},{"type":"text","text":" "},{"type":"text","text":"See each delegate’s documentation for details."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio":{"title":"SocialRadio","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadio","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio","navigatorTitle":[{"text":"SocialRadio","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"url":"\/documentation\/socialradio\/socialradio","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/setSocialLayerDelegates(_:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/setSocialLayerDelegates(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSocialLayerDelegates"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates","text":"SocialLayerDelegates"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"setSocialLayerDelegates:"}],"url":"\/documentation\/socialradio\/socialradio\/setsociallayerdelegates(_:)","kind":"symbol","title":"setSocialLayerDelegates(_:)","abstract":[{"type":"text","text":"Sets the Social Layer delegates"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-with-custom-audio-and-social-layer-article":{"title":"Initializing SocialRadio with custom audio and social layer","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","type":"topic","url":"\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-and-social-layer-article","abstract":[{"type":"text","text":"How to validate your client and start using the SocialRadio SDK with custom audio track data and custom social layer."}],"kind":"article","role":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setSocialLayerDelegates:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setSocialLayerDelegates:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setSocialLayerDelegates:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","text":"SocialLayerDelegates","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"delegates"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"delegates","content":[{"inlineContent":[{"text":"The social layer delegates","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","value":"SocialLayerDelegates"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"kind":"identifier","text":"SocialLayerDelegates"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerDelegates"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/title","value":"SocialRadio"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/fragments","value":[{"kind":"identifier","text":"SocialRadio"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadio"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1setSocialLayerDelegates(_:)\/title","value":"setSocialLayerDelegates:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1setSocialLayerDelegates(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSocialLayerDelegates:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}