{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/tunedGlobalSocialLayerDelegates()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","text":"SocialLayerDelegates","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Tuned Global’s backend implementation of the Social Layer delegates"}]}],"kind":"content"},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"SocialLayerDelegates","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadio(im)tunedGlobalSocialLayerDelegates","title":"tunedGlobalSocialLayerDelegates()","modules":[{"name":"SocialRadio"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio"]]},"abstract":[{"type":"text","text":"Gets the Tuned Global’s backend implementation of the Social Layer delegates"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradio\/tunedglobalsociallayerdelegates()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradio\/tunedglobalsociallayerdelegates()"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerDelegates","kind":"identifier"}],"title":"SocialLayerDelegates","navigatorTitle":[{"text":"SocialLayerDelegates","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/sociallayerdelegates","abstract":[{"type":"text","text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions."},{"type":"text","text":" "},{"type":"text","text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc."},{"type":"text","text":" "},{"type":"text","text":"See each delegate’s documentation for details."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/tunedGlobalSocialLayerDelegates()":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/tunedGlobalSocialLayerDelegates()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates","text":"SocialLayerDelegates","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradio\/tunedglobalsociallayerdelegates()","title":"tunedGlobalSocialLayerDelegates()","kind":"symbol","abstract":[{"type":"text","text":"Gets the Tuned Global’s backend implementation of the Social Layer delegates"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-with-custom-audio-and-social-layer-article":{"title":"Initializing SocialRadio with custom audio and social layer","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","type":"topic","url":"\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-and-social-layer-article","abstract":[{"type":"text","text":"How to validate your client and start using the SocialRadio SDK with custom audio track data and custom social layer."}],"kind":"article","role":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio":{"title":"SocialRadio","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadio","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio","navigatorTitle":[{"text":"SocialRadio","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"url":"\/documentation\/socialradio\/socialradio","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"tunedGlobalSocialLayerDelegates","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","kind":"typeIdentifier","text":"SocialLayerDelegates","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"tunedGlobalSocialLayerDelegates"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The Tuned Global’s backend implementation of the Social Layer delegates","type":"text"}],"type":"paragraph"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"SocialLayerDelegates","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","op":"replace"},{"value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","op":"replace"},{"value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","op":"replace"},{"value":"tunedGlobalSocialLayerDelegates","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1tunedGlobalSocialLayerDelegates()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"tunedGlobalSocialLayerDelegates","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1tunedGlobalSocialLayerDelegates()\/fragments","op":"replace"},{"value":"SocialRadio","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/title","op":"replace"},{"value":[{"text":"SocialRadio","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/fragments","op":"replace"},{"value":[{"text":"SocialRadio","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio\/navigatorTitle","op":"replace"}]}]}