{"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"trackDurationSeconds"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDurationSeconds","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)AutomixIQWaveformModel(py)trackDurationSeconds","title":"trackDurationSeconds","symbolKind":"property","modules":[{"name":"SocialRadio"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDurationSeconds"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}]}]}],"abstract":[{"type":"text","text":"The duration of the track, in seconds"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel"]]},"variants":[{"paths":["\/documentation\/socialradio\/automixiqwaveformmodel\/trackdurationseconds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqwaveformmodel\/trackdurationseconds"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/trackDurationSeconds","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","type":"topic","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel":{"url":"\/documentation\/socialradio\/automixiqwaveformmodel","abstract":[{"type":"text","text":"AutomixIQWaveformModel models the waveform of a track."}],"navigatorTitle":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"role":"symbol","type":"topic","title":"AutomixIQWaveformModel","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQWaveformModel/trackDurationSeconds":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDurationSeconds","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"abstract":[{"text":"The duration of the track, in seconds","type":"text"}],"url":"\/documentation\/socialradio\/automixiqwaveformmodel\/trackdurationseconds","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQWaveformModel\/trackDurationSeconds","kind":"symbol","navigatorTitle":[{"text":"trackDurationSeconds","kind":"identifier"}],"title":"trackDurationSeconds","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"trackDurationSeconds"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"trackDurationSeconds","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"text":"trackDurationSeconds","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/title","op":"replace","value":"AutomixIQWaveformModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/fragments","op":"replace","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel~1trackDurationSeconds\/title","op":"replace","value":"trackDurationSeconds"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQWaveformModel~1trackDurationSeconds\/fragments","op":"replace","value":[{"text":"trackDurationSeconds","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}