{"variants":[{"paths":["\/documentation\/automixiq\/automixiqwaveformmodel\/lefttransitionendtime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqwaveformmodel\/lefttransitionendtime"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"AutomixIQ"}],"symbolKind":"property","title":"leftTransitionEndTime","externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQWaveformModel(py)leftTransitionEndTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftTransitionEndTime"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"role":"symbol","navigatorTitle":[{"text":"leftTransitionEndTime","kind":"identifier"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel\/leftTransitionEndTime"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftTransitionEndTime","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":"The time in the track the left transition ends at, in seconds","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel"]]},"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/automixiq","title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQWaveformModel/leftTransitionEndTime":{"url":"\/documentation\/automixiq\/automixiqwaveformmodel\/lefttransitionendtime","role":"symbol","title":"leftTransitionEndTime","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftTransitionEndTime"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel\/leftTransitionEndTime","navigatorTitle":[{"kind":"identifier","text":"leftTransitionEndTime"}],"abstract":[{"type":"text","text":"The time in the track the left transition ends at, in seconds"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQWaveformModel":{"abstract":[{"type":"text","text":"AutomixIQWaveformModel models the waveform of a track."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQWaveformModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQWaveformModel","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQWaveformModel","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqwaveformmodel","type":"topic","role":"symbol","kind":"symbol","title":"AutomixIQWaveformModel"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"leftTransitionEndTime"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"leftTransitionEndTime","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"leftTransitionEndTime","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel~1leftTransitionEndTime\/title","op":"replace","value":"leftTransitionEndTime"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel~1leftTransitionEndTime\/fragments","op":"replace","value":[{"text":"leftTransitionEndTime","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/title","op":"replace","value":"AutomixIQWaveformModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/fragments","op":"replace","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQWaveformModel\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQWaveformModel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}