{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/backNoTrackAvailable","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/automixiq\/errorcode\/backnotrackavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/errorcode\/backnotrackavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@ErrorCode@ErrorCodeBackNoTrackAvailable","role":"symbol","title":"ErrorCode.backNoTrackAvailable","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeBackNoTrackAvailable"}],"symbolKind":"case","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backNoTrackAvailable","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backNoTrackAvailable","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode":{"abstract":[],"navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"url":"\/documentation\/automixiq\/errorcode","title":"ErrorCode","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/ErrorCode/backNoTrackAvailable":{"abstract":[],"url":"\/documentation\/automixiq\/errorcode\/backnotrackavailable","type":"topic","title":"ErrorCode.backNoTrackAvailable","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/ErrorCode\/backNoTrackAvailable","role":"symbol","navigatorTitle":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backNoTrackAvailable","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ErrorCodeBackNoTrackAvailable","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/title"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/fragments"},{"op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode\/navigatorTitle"},{"op":"replace","value":"ErrorCodeBackNoTrackAvailable","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1backNoTrackAvailable\/title"},{"op":"replace","value":[{"text":"ErrorCodeBackNoTrackAvailable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1ErrorCode~1backNoTrackAvailable\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}