{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"on","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","title":"on()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"on"}],"roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQ(im)on"},"abstract":[{"text":"Returns the on\/off status of AutomixIQ.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/on()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/socialradio\/automixiq\/on()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiq\/on()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"on","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"returns true if on, false otherwise.","type":"text"}]}]}],"type":"unorderedList"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","role":"symbol","type":"topic","abstract":[{"type":"text","text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"title":"AutomixIQ","kind":"symbol","url":"\/documentation\/socialradio\/automixiq","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQ","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ/on()":{"abstract":[{"type":"text","text":"Returns the on\/off status of AutomixIQ."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"on"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/on()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"on"}],"kind":"symbol","role":"symbol","title":"on()","url":"\/documentation\/socialradio\/automixiq\/on()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"url":"\/documentation\/socialradio","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"on","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"on"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"on","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixIQ","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title"},{"value":[{"text":"AutomixIQ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments"},{"value":[{"text":"AutomixIQ","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle"},{"value":"on","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1on()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"on","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1on()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}