{"sections":[],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Essentials","type":"heading","text":"Essentials","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This document explains how to integrate SocialRadio with your application using a custom backend to retrieve audio and metadata."}]},{"anchor":"Initialization-with-custom-audio","type":"heading","text":"Initialization with custom audio","level":3},{"type":"paragraph","inlineContent":[{"text":"In order to initialise SocialRadio with custom audio you need the following:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Tuned Global Store ID"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tuned Global Application ID"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Device Country Code","type":"text"}]}]}]},{"code":["func application(_ application: UIApplication, ","                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","    \/\/ ...","","    let automixIQStreamingDelegate: AutomixIQStreamingDelegate = myAutomixIQStreamingDelegate","    let socialRadioTrackMetadataDelegate: SocialRadioTrackMetadataDelegate = mySocialRadioTrackMetadataDelegate","    let socialRadioUIDelegate: SocialRadioUIDelegate = mySocialRadioUIDelegate","    let socialRadioStatusObserverDelegate: SocialRadioStatusObserverDelegate = mySocialRadioStatusObserverDelegate","    let authenticationDelegate: AuthenticationDelegate = myTrackDataBackendAuthenticationDelegate","    let countryCode: String = myCountryCode \/\/ \"US\" ? \"AU\"?","    let storeId: String = myTunedStoreId","    let applicationId: String = myApplicationId","    let myAPIKey: String = myApplicationKey","","    let config = SocialRadioConfig(apiKey: myAPIKey, country: countryCode, storeId: storeId, applicationId: applicationId)","    SocialRadio.initialise(config: config","                           automixIQStreamingDelegate: automixIQStreamingDelegate,","                           socialRadioTrackMetadataDelegate: socialRadioTrackMetadataDelegate","                           socialRadioStatusDelegate: socialRadioStatusObserverDelegate,","                           socialRadioUIDelegate: socialRadioUIDelegate,","                           authenticationDelegate: authenticationDelegate)","    { error in","        if error != nil {","            \/\/ This means you are forbidden to use the Automix SDK or you have no internet connection.","            return","        }","        \/\/ The Automix SDK public functions can be used from this point onwards :)","    }","","    \/\/ ...","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"You can tweak the SocialRadio UI and available feature set by changing flags on the config object. See ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","isActive":true,"type":"reference"},{"text":".","type":"text"}]},{"level":4,"text":"AutomixIQStreamingDelegate","anchor":"AutomixIQStreamingDelegate","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If your custom backend puts fetching metadata and track data behind a login, SocialRadio needs to know if the user in your application is logged in or not via"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/isLoggedIn()"}]}]}],"type":"unorderedList"},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func isLoggedIn() {","        return self.loggedIn","    }","    \/\/ ...","}"],"type":"codeListing"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If your custom backend only allows playback on a device under certain conditions (for instance it only allows one device to play at any given time), SocialRadio needs to know if a device is allowed to play via"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncCheckDeviceStatus(completion:)"}]}]}],"type":"unorderedList"},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func asyncCheckDeviceStatus(completion: @escaping (_ error: Error?, _ canContinuePlaying: Bool) -> Void) {","        self.canDeviceContinuePlaying() { allowedToPlay in","            return allowedToPlay","        }","    }","    \/\/ ...","}"],"type":"codeListing"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SocialRadio requires devices to have a unique identifier, provided via"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/getDeviceIdentifier()"}]}]}],"type":"unorderedList"},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func getDeviceIdentifier() -> String {","        return self.deviceIdentifier","    }","    \/\/ ...","}"],"type":"codeListing"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This provides hooks to inject cached track audio data and metadata, preventing SocialRadio from having to request this data from your custom backend if they are already available. This also enables offline playback when all required data is available on the device"}]}]}],"type":"unorderedList"},{"type":"paragraph","inlineContent":[{"text":"This is done via ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","type":"reference"}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func syncGetTrackMetadata(trackId: String?) -> TunedTrackModel? {","        \/\/ If I have this track cached, I should be able to tell its metadata","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.metadataForTrack(trackId)","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","type":"reference"}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func syncGetCachedTrack(trackId: String) -> Data? {","        \/\/ If I have this track cached, I should be able to decrypt it and send the data","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.unencryptedDataForTrack(trackId)","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"SocialRadio will pass every track metadata model it may have downloaded to the client to provide an opportunity to cache it. If you do not need this, you may leave this function empty.","type":"text"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/cacheMetadata(_:)","type":"reference"}]},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func cacheMetadata(_ metadata: [TunedTrackModel]) -> Data? {","        self.metadataForTrack[metadata.trackId] = metadata","    }","    \/\/ ...","}"],"type":"codeListing"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SocialRadio will download track metadata as it needs it. When required, it will do so via"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)"}]}]}],"type":"unorderedList"},{"syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func asyncGetTrackMetadata(trackId: String, completion: @escaping (_ error: Error?, _ track: TunedTrackModel?) -> Void) {","        self.getTrackMetadata(trackId: trackId) { error, trackMetadata in","            let automixIQTrackModel = translateMetadata(trackMetadata)","            return completion(error, automixIQTrackModel)","        }","    }","    \/\/ ...","}"],"type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"When SocialRadio needs to download a track, it will ask for the url for it. It supports session IDs if you want urls to expire and return 403s. It will do so via"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","isActive":true}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func asyncGetStream(streamingDeviceId: String, sessionId: String, trackId: String, completion: @escaping (_ error: Error?, _ url: String?, _ newSessionId: String?, _ reportingURLS: Beacons?) -> Void) {","        self.getTrackURL(deviceId: streamingDeviceId, sessionId: sessionId, trackId: trackId) { error, url in ","            return completion(error, url)","        }","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"When a track finishes downloading, SocialRadio will pass the audio data for you to cache if required. This is done via"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadCompleted(trackId:data:)","isActive":true}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func trackDownloadCompleted(trackId: String, data: NSData) {","        self.cacheTrack(trackId: trackId, data: data)","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"As a track is being downloaded, SocialRadio will report download progress via"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)","isActive":true}]}]}]},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixIQStreamingDelegate: NSObject, AutomixIQStreamingDelegate {","    \/\/ ...","    public func trackDownloadProgressChanged(trackId: String, progress: Swift.Float) {","        self.updateTrackDownloadProgress(trackId: trackId, progress: progress)","    }","    \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Do keep in mind this download is done lazily, as SocialRadio requires data for analysis \/ playback. There is no guarantee a track will download in its entirety if the track is not played in its entirety."}]},{"level":4,"type":"heading","text":"SocialRadioTrackMetadataDelegate","anchor":"SocialRadioTrackMetadataDelegate"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","isActive":true},{"type":"text","text":" is responsible for getting artwork for tracks, and track recommendations:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"SocialRadio will ask you for the URL to a provider of artwork given track Ids:","type":"text"}]}]}]},{"syntax":"swift","type":"codeListing","code":["public class MySocialRadioTrackMetadataDelegate: NSObject, SocialRadioTrackMetadataDelegate {","    \/\/ ...","    func asyncGetThumborLocation(completion: @escaping(_ url: String?) -> Void) -> Void {","        return self.imageGenerationURL","    }","    \/\/ ...","}"]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"SocialRadio will ask for track recommendations for a given track:","type":"text"}]}]}],"type":"unorderedList"},{"syntax":"swift","type":"codeListing","code":["public class MySocialRadioTrackMetadataDelegate: NSObject, SocialRadioTrackMetadataDelegate {","    \/\/ ...","    func asyncGetTrackRecommendations(identifiers: [String],","                                      contextIds: [String]?,","                                      limit: Int, completion: @escaping(_ tracks: [TunedTrackModel]?) -> Void) -> Void {","        return completion(self.trackRecommendations(identifiers)","    }","    \/\/ ...","}"]},{"type":"heading","text":"SocialRadioUIDelegate","anchor":"SocialRadioUIDelegate","level":4},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"reference","isActive":true},{"text":" is responsible for providing data required for the Radio UI to function, as well as presenting UI SocialRadio is not able to do on its own.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"SocialRadio allows the user to add one or multiple tracks to a radio show. When that action is triggered, SocialRadio asks this delegate to provide the UI for selecting them. This is done via "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentTracklist(filterOutExplicitContent:completion:)","type":"reference","isActive":true}],"type":"paragraph"}]}]},{"code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func presentTracklist(filterOutExplicitContent: Bool,","                          completion: @escaping (_ tracks: [TunedTrackModel]?,","                                                 _ contextType: String?, _ contextId: Int,","                                                 _ playlistName: String?) -> Void) {","        \/\/ Your implementation for presenting UI that allows to select one or more tracks:","        let tracklist = MyTracklist() { tracks, playlistName in","            \/\/ - Feed the track\/tracks selected as the second paramenter of the completion block,","            \/\/ - If the tracks selected are part of a playlist, feed the name opf that playlist as the thirsd parameter of the completion block.","            completion(tracks, playlistName)","        }","        self.present(filterOutExplicitContent, tracklist, animated: true)","    }","    \/\/ ...","}"],"type":"codeListing","syntax":"swift"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"At a time where SocialRadio requires a User Id, if it does not have one it will require the user to authenticate via "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentAuthentication(completion:)"}]}]}]},{"code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func presentAuthentication(completion: @escaping (_ success: Bool) -> Void) {","        \/\/ Present your login here","        let authenticationDialog = MyAuthenticationDialog() { success in","            completion(success)","        }","        self.present(authenticationDialog, animated: true)","    }","    \/\/ ...","}"],"type":"codeListing","syntax":"swift"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"At times, SocialRadio will need to present a users’ profile. It will do so via ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentProfile(identifier:completion:)","isActive":true,"type":"reference"}]}]}]},{"type":"codeListing","syntax":"swift","code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func presentProfile(identifier: String?, completion: @escaping () -> Void) {","        \/\/ Present the user profile here","        let profileDialog = MyProfileDialog(identifier: identifier) {","            completion()","        }","        self.present(profileDialog, animated: true)","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"SocialRadio also notifies this delegate when it will and has minimised the Radio UI, and when it will and has closed the Radio UI. It does so via ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willDismissRadioUI(userInitiated:)","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didDismissRadioUI(userInitiated:)","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willCloseRadioUI(userInitiated:)","isActive":true,"type":"reference"},{"text":", ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didCloseRadioUI(userInitiated:)","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}]},{"code":["public class MySocialRadioUIDelegate: NSObject, SocialRadioUIDelegate {","    \/\/ ...","    func willDismissRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    ","    func didDismissRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    ","    func willCloseRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    ","    func didCloseRadioUI(userInitiated: Boolean) -> Void {","        return","    }","    \/\/ ...","}"],"type":"codeListing","syntax":"swift"},{"type":"heading","text":"SocialRadioStatusObserverDelegate","level":4,"anchor":"SocialRadioStatusObserverDelegate"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"reference","isActive":true},{"type":"text","text":" is responsible for updating your player’s UI."}]},{"type":"heading","text":"AuthenticationDelegate","level":4,"anchor":"AuthenticationDelegate"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","type":"reference","isActive":true},{"type":"text","text":" is responsible for fetching and refreshing your custom audio backend’s credentials:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"SocialRadio will ask you to refresh your custom audio backend’s credentials should they have expired:","type":"text"}]}]}]},{"code":["public class MyAuthenticationDelegate: NSObject, AuthenticationDelegate {","    func refreshCredentials(oldAccessToken: String?, refreshToken: String?, tokenType: String?,","                                completion: @escaping (_ error: Error?,","                                                       _ credentials: SocialRadioCredentials?) -> Void) {","        self.refreshCredentials(completion)","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"heading","text":"Checking if SocialRadio is initialised","level":3,"anchor":"Checking-if-SocialRadio-is-initialised"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To check wether AutomixIQ is currently initialised, use"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialised()","isActive":true,"type":"reference"}]}]}]}]}],"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-article"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with custom audio track data.","type":"text"}],"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"SocialRadio"}],"title":"Initializing SocialRadio with custom audio"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"],"anchor":"Initialising-SocialRadio-for-use-with-custom-audio","title":"Initialising SocialRadio for use with custom audio"}],"variants":[{"paths":["\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-article"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/syncGetTrackMetadata(trackId:)":{"title":"syncGetTrackMetadata(trackId:)","required":true,"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"TunedTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/syncgettrackmetadata(trackid:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/willDismissRadioUI(userInitiated:)":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate\/willdismissradioui(userinitiated:)","abstract":[{"text":"Called by SocialRadio when the Radio UI about to be dismissed","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willDismissRadioUI(userInitiated:)","type":"topic","title":"willDismissRadioUI(userInitiated:)","role":"symbol","navigatorTitle":[{"text":"willDismissRadioUIWithUserInitiated:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willDismissRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/asyncCheckDeviceStatus(completion:)":{"abstract":[{"type":"text","text":"Called by AutomixIQ regularly while something is being played, this can be used if you have restrictions on the number of devices that can play simultaneously"}],"role":"symbol","type":"topic","title":"asyncCheckDeviceStatus(completion:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/asynccheckdevicestatus(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncCheckDeviceStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"canContinuePlaying"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"asyncCheckDeviceStatusWithCompletion:"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncCheckDeviceStatus(completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackMetadataDelegate":{"title":"SocialRadioTrackMetadataDelegate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Handles track recommendations and artwork"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiotrackmetadatadelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/presentAuthentication(completion:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentAuthentication(completion:)","url":"\/documentation\/socialradio\/socialradiouidelegate\/presentauthentication(completion:)","abstract":[{"type":"text","text":"Called by SocialRadio when it wishes to present UI to authenticate a user"}],"kind":"symbol","type":"topic","title":"presentAuthentication(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"presentAuthenticationWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"presentAuthentication","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/syncGetCachedTrack(trackId:)":{"abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"role":"symbol","type":"topic","title":"syncGetCachedTrack(trackId:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/syncgetcachedtrack(trackid:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetCachedTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/didDismissRadioUI(userInitiated:)":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate\/diddismissradioui(userinitiated:)","abstract":[{"text":"Called by SocialRadio when the Radio UI is dismissed","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didDismissRadioUI(userInitiated:)","type":"topic","title":"didDismissRadioUI(userInitiated:)","role":"symbol","navigatorTitle":[{"text":"didDismissRadioUIWithUserInitiated:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didDismissRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","url":"\/documentation\/socialradio\/socialradioconfig","kind":"symbol","abstract":[{"text":"SocialRadioConfig holds the variables to initialise SocialRadio and describe the desired feature set and UI","type":"text"}],"type":"topic","title":"SocialRadioConfig","role":"symbol","navigatorTitle":[{"text":"SocialRadioConfig","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/presentProfile(identifier:completion:)":{"required":true,"abstract":[{"text":"Called by SocialRadio when it wishes to present UI with a user’s information","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentProfile","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentProfile(identifier:completion:)","kind":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate\/presentprofile(identifier:completion:)","title":"presentProfile(identifier:completion:)","navigatorTitle":[{"kind":"identifier","text":"presentProfileWithIdentifier:completion:"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/willCloseRadioUI(userInitiated:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/willCloseRadioUI(userInitiated:)","url":"\/documentation\/socialradio\/socialradiouidelegate\/willcloseradioui(userinitiated:)","kind":"symbol","abstract":[{"text":"Called by SocialRadio when the Radio UI is closed","type":"text"}],"type":"topic","title":"willCloseRadioUI(userInitiated:)","role":"symbol","navigatorTitle":[{"text":"willCloseRadioUIWithUserInitiated:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/isLoggedIn()":{"abstract":[{"text":"Called by AutomixIQ to learn if it is allowed to stream content that is protected by some form of authentication.","type":"text"},{"text":" ","type":"text"},{"text":"An example is, an implementation via an API behind OAuth would return true if access and refresh tokens are available, false otherwise","type":"text"}],"role":"symbol","type":"topic","title":"isLoggedIn()","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/isloggedin()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoggedIn"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isLoggedIn"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/isLoggedIn()"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)":{"abstract":[{"type":"text","text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required."}],"role":"symbol","type":"topic","title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asyncGetStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"streamingDeviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"sessionId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newSessionId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","url":"\/documentation\/socialradio\/socialradiouidelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUIDelegate"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"title":"SocialRadioUIDelegate","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/asyncGetTrackMetadata(trackId:completion:)":{"abstract":[{"text":"Called by AutomixIQ when it requires the metadata of a track in order to load it.","type":"text"}],"role":"symbol","type":"topic","title":"asyncGetTrackMetadata(trackId:completion:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/asyncgettrackmetadata(trackid:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetTrackMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"track"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","kind":"typeIdentifier","text":"TunedTrackModel"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetTrackMetadataWithTrackId:completion:"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/trackDownloadCompleted(trackId:data:)":{"abstract":[{"type":"text","text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device."}],"role":"symbol","type":"topic","title":"trackDownloadCompleted(trackId:data:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/trackdownloadcompleted(trackid:data:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDownloadCompleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadCompleted(trackId:data:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/initialised()":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/initialised()","url":"\/documentation\/socialradio\/socialradio\/initialised()","kind":"symbol","abstract":[{"text":"Returns the initialised status of the Automix SDK.","type":"text"}],"type":"topic","title":"initialised()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initialised"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialised"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/trackDownloadProgressChanged(trackId:progress:)":{"title":"trackDownloadProgressChanged(trackId:progress:)","required":true,"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadProgressChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/trackdownloadprogresschanged(trackid:progress:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"title":"SocialRadioStatusObserverDelegate","type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/presentTracklist(filterOutExplicitContent:completion:)":{"required":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/presentTracklist(filterOutExplicitContent:completion:)","url":"\/documentation\/socialradio\/socialradiouidelegate\/presenttracklist(filteroutexplicitcontent:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Called by SocialRadio when it wishes to present UI to select one or many tracks"}],"type":"topic","title":"presentTracklist(filterOutExplicitContent:completion:)","role":"symbol","navigatorTitle":[{"text":"presentTracklistWithFilterOutExplicitContent:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentTracklist"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"filterOutExplicitContent"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tracks","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"TunedTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel"},{"text":"]?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"contextType","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"contextId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"playlistName","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/cacheMetadata(_:)":{"abstract":[{"type":"text","text":"AutomixIQ calls this function to provide a chance to cache metadata to shortcut future requests."}],"role":"symbol","type":"topic","title":"cacheMetadata(_:)","kind":"symbol","required":true,"url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/cachemetadata(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cacheMetadata","kind":"identifier"},{"text":"([","kind":"text"},{"text":"TunedTrackModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedTrackModel","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"cacheMetadata:"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/cacheMetadata(_:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"title":"AutomixIQStreamingDelegate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AuthenticationDelegate":{"title":"AuthenticationDelegate","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Handles handoff of authentication tokens"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/authenticationdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate/getDeviceIdentifier()":{"required":true,"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate\/getDeviceIdentifier()","url":"\/documentation\/socialradio\/automixiqstreamingdelegate\/getdeviceidentifier()","kind":"symbol","abstract":[{"text":"Called by Automix to learn the identity of the device requesting to stream audio, for those services that require it.","type":"text"},{"text":" ","type":"text"},{"text":"An example would be, a service that only allows one device to stream at any one time, would need to know the identity of the device to provide the stream.","type":"text"}],"type":"topic","title":"getDeviceIdentifier()","role":"symbol","navigatorTitle":[{"text":"getDeviceIdentifier","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getDeviceIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/didCloseRadioUI(userInitiated:)":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate\/didcloseradioui(userinitiated:)","abstract":[{"text":"Called by SocialRadio when the Radio UI is closed","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/didCloseRadioUI(userInitiated:)","type":"topic","title":"didCloseRadioUI(userInitiated:)","role":"symbol","navigatorTitle":[{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Initialising-SocialRadio-for-use-with-custom-audio","title":"Initialising SocialRadio for use with custom audio","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"]}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/title","value":"syncGetTrackMetadataWithTrackId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willDismissRadioUI(userInitiated:)\/title","value":"willDismissRadioUIWithUserInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willDismissRadioUI(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willDismissRadioUIWithUserInitiated:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/title","value":"asyncCheckDeviceStatusWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncCheckDeviceStatusWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/title","value":"SocialRadioTrackMetadataDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioTrackMetadataDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioTrackMetadataDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentAuthentication(completion:)\/title","value":"presentAuthenticationWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentAuthentication(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentAuthenticationWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/title","value":"syncGetCachedTrackWithTrackId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didDismissRadioUI(userInitiated:)\/title","value":"didDismissRadioUIWithUserInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didDismissRadioUI(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDismissRadioUIWithUserInitiated:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","value":"SocialRadioConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","value":[{"kind":"identifier","text":"SocialRadioConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentProfile(identifier:completion:)\/title","value":"presentProfileWithIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentProfile(identifier:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentProfileWithIdentifier:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willCloseRadioUI(userInitiated:)\/title","value":"willCloseRadioUIWithUserInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1willCloseRadioUI(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willCloseRadioUIWithUserInitiated:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1isLoggedIn()\/title","value":"isLoggedIn"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1isLoggedIn()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLoggedIn"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/title","value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","value":"SocialRadioUIDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/title","value":"asyncGetTrackMetadataWithTrackId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetTrackMetadataWithTrackId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/title","value":"trackDownloadCompletedWithTrackId:data:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialised()\/title","value":"initialised"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1initialised()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initialised"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title","value":"trackDownloadProgressChangedWithTrackId:progress:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","value":"SocialRadioStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentTracklist(filterOutExplicitContent:completion:)\/title","value":"presentTracklistWithFilterOutExplicitContent:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1presentTracklist(filterOutExplicitContent:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentTracklistWithFilterOutExplicitContent:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1cacheMetadata(_:)\/title","value":"cacheMetadata:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1cacheMetadata(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cacheMetadata:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title","value":"AutomixIQStreamingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/title","value":"AuthenticationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/fragments","value":[{"kind":"identifier","text":"AuthenticationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AuthenticationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/title","value":"getDeviceIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDeviceIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didCloseRadioUI(userInitiated:)\/title","value":"didCloseRadioUIWithUserInitiated:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1didCloseRadioUI(userInitiated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCloseRadioUIWithUserInitiated:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}