{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/dialogPrimaryButtonBackgroundColor"},"kind":"symbol","metadata":{"symbolKind":"property","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioUIConfig(py)dialogPrimaryButtonBackgroundColor","roleHeading":"Instance Property","modules":[{"name":"SocialRadio"}],"title":"dialogPrimaryButtonBackgroundColor","role":"symbol","navigatorTitle":[{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiouiconfig\/dialogprimarybuttonbackgroundcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiouiconfig\/dialogprimarybuttonbackgroundcolor"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig":{"title":"SocialRadioUIConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUIConfig"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Social Radio UI options"}],"url":"\/documentation\/socialradio\/socialradiouiconfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIConfig/dialogPrimaryButtonBackgroundColor":{"url":"\/documentation\/socialradio\/socialradiouiconfig\/dialogprimarybuttonbackgroundcolor","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"title":"dialogPrimaryButtonBackgroundColor","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIConfig\/dialogPrimaryButtonBackgroundColor","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"url":"\/documentation\/socialradio","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"dialogPrimaryButtonBackgroundColor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"dialogPrimaryButtonBackgroundColor","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/title","op":"replace","value":"SocialRadioUIConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1dialogPrimaryButtonBackgroundColor\/title","op":"replace","value":"dialogPrimaryButtonBackgroundColor"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIConfig~1dialogPrimaryButtonBackgroundColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"dialogPrimaryButtonBackgroundColor"}]}]}]}