{"kind":"article","primaryContentSections":[{"content":[{"anchor":"Essentials","text":"Essentials","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"SocialRadio offers moderation of content by allowing the user to report inapropriate users. To do so, you use ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/reportUser(identifier:completion:)","type":"reference","isActive":true},{"text":".","type":"text"}]},{"syntax":"swift","code":["public class MyApplication {","    \/\/ ...","    func didPressReportUserButton(identifier: String) {","        SocialRadio.getInstance()?.reportUser(identifier) { error in ","        }","    }","    \/\/ ...","}"],"type":"codeListing"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/moderation-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/moderation-article"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Moderation-article"},"metadata":{"title":"Moderation","modules":[{"name":"SocialRadio"}],"roleHeading":"Article","role":"article"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Tools to interact with the social layer.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadio/reportUser(identifier:completion:)":{"abstract":[{"type":"text","text":"Submits a report for inappropriate content for a user."}],"title":"reportUser(identifier:completion:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadio\/reportUser(identifier:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reportUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/socialradio\/socialradio\/reportuser(identifier:completion:)","navigatorTitle":[{"text":"reportUserWithIdentifier:completion:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"url":"\/documentation\/socialradio","title":"SocialRadio"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"reportUserWithIdentifier:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1reportUser(identifier:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"reportUserWithIdentifier:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadio~1reportUser(identifier:completion:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}