{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/getUserLiveMixtape(identifier:completion:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserLiveMixtape"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mixtape"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioMixtape","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The user’s unique identifier.","type":"text"}],"type":"paragraph"}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter mixtape: The live mixtape, if found.","type":"text"}]}]}]}],"name":"completion"}],"kind":"parameters"}],"abstract":[{"text":"Retrieves the live mixtape of a specific user.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/getuserlivemixtape(identifier:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/getuserlivemixtape(identifier:completion:)"]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getUserLiveMixtapeWithIdentifier:completion:"}],"role":"symbol","required":true,"roleHeading":"Instance Method","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerLiveMixtapeDelegate(im)getUserLiveMixtapeWithIdentifier:completion:","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserLiveMixtape"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mixtape"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioMixtape","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"getUserLiveMixtape(identifier:completion:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate":{"title":"SocialLayerLiveMixtapeDelegate","navigatorTitle":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding live mixtapes."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate/getUserLiveMixtape(identifier:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getUserLiveMixtape","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"mixtape"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape","text":"SocialRadioMixtape","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"getUserLiveMixtape(identifier:completion:)","navigatorTitle":[{"kind":"identifier","text":"getUserLiveMixtapeWithIdentifier:completion:"}],"url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate\/getuserlivemixtape(identifier:completion:)","abstract":[{"text":"Retrieves the live mixtape of a specific user.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate\/getUserLiveMixtape(identifier:completion:)","type":"topic","required":true,"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape":{"title":"SocialRadioMixtape","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"url":"\/documentation\/socialradio\/socialradiomixtape","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtape"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getUserLiveMixtapeWithIdentifier:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"getUserLiveMixtapeWithIdentifier:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getUserLiveMixtapeWithIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioMixtape","text":"SocialRadioMixtape"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"identifier","content":[{"inlineContent":[{"text":"The user’s unique identifier.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Parameter error: An error describing a problem that occurred, nil otherwise."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter mixtape: The live mixtape, if found."}]}]}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/title","value":"SocialLayerLiveMixtapeDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/fragments","value":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/navigatorTitle","value":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1getUserLiveMixtape(identifier:completion:)\/title","value":"getUserLiveMixtapeWithIdentifier:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"getUserLiveMixtapeWithIdentifier:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate~1getUserLiveMixtape(identifier:completion:)\/fragments","op":"replace"},{"value":"SocialRadioMixtape","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/title"},{"value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtape"}]}]}]}