{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioCommentTag(im)init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiocommenttag\/init"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag\/init","interfaceLanguage":"occ"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCommentTag":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioCommentTag"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"title":"SocialRadioCommentTag","kind":"symbol","abstract":[{"text":"SocialRadioCommentTag models a user tag in a comment","type":"text"}],"url":"\/documentation\/socialradio\/socialradiocommenttag"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCommentTag/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","type":"topic","title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/socialradio\/socialradiocommenttag\/init","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag\/init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/title","op":"replace","value":"SocialRadioCommentTag"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioCommentTag"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioCommentTag"}]}]}]}