{"variants":[{"paths":["\/documentation\/socialradio\/automixsdkmixtape\/author"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkmixtape\/author"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"author","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKUser","text":"AutomixSDKUser","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"SocialRadio"}],"title":"author","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtape(py)author","navigatorTitle":[{"kind":"identifier","text":"author"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/author"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"author"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKUser","kind":"typeIdentifier","text":"AutomixSDKUser","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser"},{"kind":"text","text":"?"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape"]]},"abstract":[{"type":"text","text":"The author of this mixtape"}],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKUser":{"abstract":[{"text":"AutomixSDKUser models a user","type":"text"}],"role":"symbol","url":"\/documentation\/socialradio\/automixsdkuser","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKUser","kind":"identifier"}],"title":"AutomixSDKUser","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser","type":"topic","navigatorTitle":[{"text":"AutomixSDKUser","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/author":{"navigatorTitle":[{"kind":"identifier","text":"author"}],"role":"symbol","title":"author","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkmixtape\/author","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/author","abstract":[{"type":"text","text":"The author of this mixtape"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"author","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKUser","text":"AutomixSDKUser"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtape"}],"title":"AutomixSDKMixtape","url":"\/documentation\/socialradio\/automixsdkmixtape","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKMixtape models a mixtape"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"author"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"author"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKUser","kind":"typeIdentifier","text":"AutomixSDKUser","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKUser"},{"kind":"text","text":" * "},{"kind":"identifier","text":"author"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/title","value":"AutomixSDKUser","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/fragments","value":[{"text":"AutomixSDKUser","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKUser"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKUser\/navigatorTitle"},{"value":"author","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1author\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1author\/fragments","value":[{"kind":"identifier","text":"author"}]},{"value":"AutomixSDKMixtape","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/navigatorTitle"}]}]}