{"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtape(py)waveform","navigatorTitle":[{"kind":"identifier","text":"waveform"}],"modules":[{"name":"SocialRadio"}],"title":"waveform","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"waveform","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformBlob","text":"AutomixSDKWaveformBlob","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","role":"symbol"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waveform"},{"kind":"text","text":": "},{"text":"AutomixSDKWaveformBlob","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformBlob","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/waveform"},"abstract":[{"type":"text","text":"The waveform representation for this mixtape"}],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkmixtape\/waveform"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixsdkmixtape\/waveform"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape/waveform":{"url":"\/documentation\/socialradio\/automixsdkmixtape\/waveform","role":"symbol","kind":"symbol","abstract":[{"text":"The waveform representation for this mixtape","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape\/waveform","title":"waveform","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveform","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutomixSDKWaveformBlob","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformBlob","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"waveform"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformBlob":{"abstract":[{"type":"text","text":"AutomixSDKWaveformBlob models the data to create a waveform shape representing a track"}],"role":"symbol","url":"\/documentation\/socialradio\/automixsdkwaveformblob","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob","title":"AutomixSDKWaveformBlob","type":"topic","navigatorTitle":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtape":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtape"}],"title":"AutomixSDKMixtape","url":"\/documentation\/socialradio\/automixsdkmixtape","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtape","kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKMixtape models a mixtape"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"waveform","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"waveform","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"AutomixSDKWaveformBlob","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob","preciseIdentifier":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformBlob","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"waveform","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"waveform","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1waveform\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape~1waveform\/fragments","value":[{"text":"waveform","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/title","value":"AutomixSDKWaveformBlob","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/navigatorTitle","value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/title","op":"replace","value":"AutomixSDKMixtape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/fragments","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}]},{"op":"replace","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtape\/navigatorTitle"}]}]}