{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeStatusObserverDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)AutomixIQ(im)removeStatusObserverDelegate:","title":"removeStatusObserverDelegate(_:)","symbolKind":"method","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"removeStatusObserverDelegate:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/removeStatusObserverDelegate(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Removes a status observer delegate","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeStatusObserverDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"statusObserverDelegate","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate to remove.","type":"text"}]}],"name":"statusObserverDelegate"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/socialradio\/automixiq\/removestatusobserverdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiq\/removestatusobserverdelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ/removeStatusObserverDelegate(_:)":{"kind":"symbol","url":"\/documentation\/socialradio\/automixiq\/removestatusobserverdelegate(_:)","title":"removeStatusObserverDelegate(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeStatusObserverDelegate:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeStatusObserverDelegate"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixIQStatusObserverDelegate"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/removeStatusObserverDelegate(_:)","abstract":[{"type":"text","text":"Removes a status observer delegate"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"navigatorTitle":[{"text":"AutomixIQ","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiq","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","title":"AutomixIQ","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQ","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusObserverDelegate":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusObserverDelegate","url":"\/documentation\/socialradio\/automixiqstatusobserverdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}],"abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"title":"AutomixIQStatusObserverDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"role":"collection","kind":"symbol","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","title":"SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"removeStatusObserverDelegate:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeStatusObserverDelegate:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeStatusObserverDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)AutomixIQStatusObserverDelegate","text":"id<AutomixIQStatusObserverDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"statusObserverDelegate"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"statusObserverDelegate","content":[{"inlineContent":[{"type":"text","text":"The delegate to remove."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"removeStatusObserverDelegate:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1removeStatusObserverDelegate(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeStatusObserverDelegate:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1removeStatusObserverDelegate(_:)\/fragments","op":"replace"},{"value":"AutomixIQ","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQ"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments","op":"replace"},{"value":[{"text":"AutomixIQ","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle","op":"replace"},{"value":"AutomixIQStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/title","op":"replace"},{"value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/fragments","op":"replace"},{"value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusObserverDelegate\/navigatorTitle","op":"replace"}]}]}