{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob\/init(from:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob\/blob"],"anchor":"Instance-Properties","title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/Se","doc:\/\/org.cocoapods.SocialRadio\/SE","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/socialradio\/socialradiowaveformblob"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradiowaveformblob"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track"}],"sections":[],"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioWaveformBlob","symbolKind":"class","title":"SocialRadioWaveformBlob","role":"symbol","modules":[{"name":"SocialRadio"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}]},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"],"anchor":"Data-models","title":"Data models"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCredentials":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","url":"\/documentation\/socialradio\/socialradiocredentials","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SocialRadioCredentials","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioCredentials","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioCredentials models credentials to access social REST APIs."}],"title":"SocialRadioCredentials"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","url":"\/documentation\/socialradio\/socialradiomixtapetrackimage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"abstract":[{"type":"text","text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape"}],"title":"SocialRadioMixtapeTrackImage"},"doc://org.cocoapods.SocialRadio/SE":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SE","title":"Swift.Encodable"},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeLite":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","url":"\/documentation\/socialradio\/socialradiomixtapelite","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeLite"}],"abstract":[{"text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields","type":"text"}],"title":"SocialRadioMixtapeLite"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedArtistModel":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedArtistModel"}],"role":"symbol","url":"\/documentation\/socialradio\/tunedartistmodel","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","type":"topic","abstract":[{"text":"TunedArtistModel models an artist.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TunedArtistModel"}],"title":"TunedArtistModel"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusVariable"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiostatusvariable","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","type":"topic","abstract":[{"type":"text","text":"SocialRadio status variable type"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"title":"SocialRadioStatusVariable"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioWaveformBlob/init":{"kind":"symbol","title":"init","type":"topic","url":"\/documentation\/socialradio\/socialradiowaveformblob\/init","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioList":{"url":"\/documentation\/socialradio\/socialradiolist","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioList"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioList"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","kind":"symbol","abstract":[],"role":"symbol","title":"SocialRadioList","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode":{"url":"\/documentation\/socialradio\/socialradioplaybackmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"kind":"symbol","abstract":[{"text":"SocialRadio playback mode","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","role":"symbol","title":"SocialRadioPlaybackMode","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioGenericList":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioGenericList","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiogenericlist","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","type":"topic","abstract":[{"text":"SocialRadioGenericList models a list of things","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioGenericList"}],"title":"SocialRadioGenericList"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","url":"\/documentation\/socialradio\/socialradiomixtapetrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"title":"SocialRadioMixtapeTrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","title":"SocialRadio","role":"collection","url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioWaveformBlob/blob":{"kind":"symbol","title":"blob","type":"topic","url":"\/documentation\/socialradio\/socialradiowaveformblob\/blob","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob\/blob","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blob"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"blob"}],"abstract":[{"text":"That data","type":"text"}]},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatus":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatus","kind":"identifier"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiostatus","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","type":"topic","abstract":[{"type":"text","text":"SocialRadioStatus models the State of the AutomixIQ during playback."}],"navigatorTitle":[{"text":"SocialRadioStatus","kind":"identifier"}],"title":"SocialRadioStatus"},"doc://org.cocoapods.SocialRadio/Se":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/Se","title":"Swift.Decodable"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioWaveformBlob":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiowaveformblob","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","type":"topic","abstract":[{"type":"text","text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"title":"SocialRadioWaveformBlob"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCommentTag":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","url":"\/documentation\/socialradio\/socialradiocommenttag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioCommentTag"}],"abstract":[{"type":"text","text":"SocialRadioCommentTag models a user tag in a comment"}],"title":"SocialRadioCommentTag"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Data-models-article":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","url":"\/documentation\/socialradio\/data-models-article","kind":"article","type":"topic","role":"article","abstract":[{"type":"text","text":"How data is passed to and from SocialRadio"}],"title":"Data models"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","url":"\/documentation\/socialradio\/socialradiomixtape","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SocialRadioMixtape","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtape","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"title":"SocialRadioMixtape"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","url":"\/documentation\/socialradio\/socialradiouser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUser"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUser"}],"abstract":[{"type":"text","text":"SocialRadioUser models a user"}],"title":"SocialRadioUser"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioWaveformBlob/init(from:)":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob\/init(from:)","url":"\/documentation\/socialradio\/socialradiowaveformblob\/init(from:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"title":"init(from:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","url":"\/documentation\/socialradio\/socialradiocomment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioComment"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioComment"}],"abstract":[{"text":"SocialRadioComment models a comment","type":"text"}],"title":"SocialRadioComment"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"type":"topic","navigatorTitle":[{"text":"TunedTrackModel","kind":"identifier"}],"title":"TunedTrackModel","role":"symbol","url":"\/documentation\/socialradio\/tunedtrackmodel","abstract":[{"type":"text","text":"TunedTrackModel models a track. This metadata is required."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TunedTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SocialRadioWaveformBlob","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob\/blob"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob\/init"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel"],"anchor":"Data-models","title":"Data models"}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioWaveformBlob"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/title","value":"SocialRadioCredentials","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/fragments","value":[{"text":"SocialRadioCredentials","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioCredentials"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/title","value":"SocialRadioMixtapeTrackImage","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/fragments","value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/title","value":"SocialRadioMixtapeLite","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/fragments","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/title","value":"TunedArtistModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/fragments","value":[{"text":"TunedArtistModel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TunedArtistModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title","value":"SocialRadioStatusVariable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/title","value":"SocialRadioList","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/fragments","value":[{"text":"SocialRadioList","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioList"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/title","value":"SocialRadioPlaybackMode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/fragments","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/title","value":"SocialRadioMixtapeTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/fragments","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob~1blob\/title","value":"blob","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob~1blob\/fragments","value":[{"text":"blob","kind":"identifier"}],"op":"replace"},{"value":"SocialRadioStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/fragments","value":[{"text":"SocialRadioStatus","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/navigatorTitle","op":"replace"},{"value":"SocialRadioWaveformBlob","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/navigatorTitle","op":"replace"},{"value":"SocialRadioCommentTag","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/title","value":"SocialRadioMixtape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/fragments","value":[{"kind":"identifier","text":"SocialRadioMixtape"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/navigatorTitle","value":[{"text":"SocialRadioMixtape","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/title","value":"SocialRadioUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/fragments","value":[{"text":"SocialRadioUser","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioUser"}]},{"value":"SocialRadioComment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/title"},{"value":[{"text":"SocialRadioComment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/navigatorTitle","value":[{"text":"SocialRadioComment","kind":"identifier"}],"op":"replace"},{"value":"TunedTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments","value":[{"text":"TunedTrackModel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TunedTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}