{"abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding users.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialLayerUserDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerUserDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate"}]}]}],"metadata":{"modules":[{"name":"SocialRadio"}],"title":"userDelegate","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialLayerUserDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerUserDelegate"}],"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)SocialLayerDelegates(py)userDelegate","navigatorTitle":[{"text":"userDelegate","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/userDelegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayerdelegates\/userdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayerdelegates\/userdelegate"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","role":"collection","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerDelegates","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SocialLayerDelegates","kind":"identifier"}],"url":"\/documentation\/socialradio\/sociallayerdelegates","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","type":"topic","abstract":[{"text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions.","type":"text"},{"text":" ","type":"text"},{"text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc.","type":"text"},{"text":" ","type":"text"},{"text":"See each delegate’s documentation for details.","type":"text"}],"title":"SocialLayerDelegates","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerUserDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","role":"symbol","url":"\/documentation\/socialradio\/sociallayeruserdelegate","navigatorTitle":[{"text":"SocialLayerUserDelegate","kind":"identifier"}],"title":"SocialLayerUserDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerUserDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding  users."}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates/userDelegate":{"type":"topic","navigatorTitle":[{"text":"userDelegate","kind":"identifier"}],"title":"userDelegate","kind":"symbol","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding users.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates\/userDelegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SocialLayerUserDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialLayerUserDelegate"}],"url":"\/documentation\/socialradio\/sociallayerdelegates\/userdelegate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"userDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"userDelegate"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SocialRadio@objc(pl)SocialLayerUserDelegate","text":"id<SocialLayerUserDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDelegate"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","value":"SocialLayerDelegates","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"text":"SocialLayerDelegates","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerDelegates"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/title","value":"SocialLayerUserDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerUserDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/navigatorTitle","value":[{"text":"SocialLayerUserDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1userDelegate\/title","value":"userDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates~1userDelegate\/fragments","value":[{"kind":"identifier","text":"userDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}