{"sections":[],"metadata":{"modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offlineNoTunedUserIdAvailable"}],"externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","title":"AutomixSDKErrorCode.offlineNoTunedUserIdAvailable"},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/offlinenotuneduseridavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode\/offlinenotuneduseridavailable"]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode","title":"AutomixSDKErrorCode","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/offlineNoTunedUserIdAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offlineNoTunedUserIdAvailable"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/offlinenotuneduseridavailable","role":"symbol","title":"AutomixSDKErrorCode.offlineNoTunedUserIdAvailable","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","type":"topic","kind":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace"},{"value":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/fragments","value":[{"text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}]}]}]}