{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTrackLiked"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"liked","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"success","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"text":"The identifier of the track.","type":"text"}]}]},{"name":"liked","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if we want the track liked, false otherwise."}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"Code to be run when the operation completes.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiouidelegate\/settrackliked(identifier:liked:completion:)"]},{"paths":["\/documentation\/socialradio\/socialradiouidelegate\/settrackliked(identifier:liked:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate(im)setTrackLikedWithIdentifier:liked:completion:","roleHeading":"Instance Method","symbolKind":"method","required":true,"title":"setTrackLiked(identifier:liked:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTrackLiked"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"liked","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"success","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setTrackLikedWithIdentifier:liked:completion:","kind":"identifier"}],"modules":[{"name":"SocialRadio"}]},"abstract":[{"type":"text","text":"Called by SocialRadio when it needs add or remove a track with a given identifier from liked"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/setTrackLiked(identifier:liked:completion:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","url":"\/documentation\/socialradio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate/setTrackLiked(identifier:liked:completion:)":{"required":true,"kind":"symbol","url":"\/documentation\/socialradio\/socialradiouidelegate\/settrackliked(identifier:liked:completion:)","title":"setTrackLiked(identifier:liked:completion:)","role":"symbol","navigatorTitle":[{"text":"setTrackLikedWithIdentifier:liked:completion:","kind":"identifier"}],"abstract":[{"text":"Called by SocialRadio when it needs add or remove a track with a given identifier from liked","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate\/setTrackLiked(identifier:liked:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTrackLiked","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"liked"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","url":"\/documentation\/socialradio\/socialradiouidelegate","role":"symbol","abstract":[{"type":"text","text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"type":"topic","title":"SocialRadioUIDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"setTrackLikedWithIdentifier:liked:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTrackLikedWithIdentifier:liked:completion:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setTrackLikedWithIdentifier:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"identifier"},{"text":" ","kind":"text"},{"text":"liked:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"liked","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The identifier of the track."}],"type":"paragraph"}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"True if we want the track liked, false otherwise."}]}],"name":"liked"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be run when the operation completes."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"setTrackLikedWithIdentifier:liked:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1setTrackLiked(identifier:liked:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate~1setTrackLiked(identifier:liked:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setTrackLikedWithIdentifier:liked:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SocialRadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title"},{"value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","op":"replace"},{"value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}