{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters\/init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters"]]},"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKMixtapeCounters(im)init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","modules":[{"name":"SocialRadio"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/automixsdkmixtapecounters\/init"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeCounters/init":{"abstract":[],"url":"\/documentation\/socialradio\/automixsdkmixtapecounters\/init","title":"init","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters\/init","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKMixtapeCounters":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKMixtapeCounters","navigatorTitle":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkmixtapecounters","title":"AutomixSDKMixtapeCounters","abstract":[{"type":"text","text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeCounters\/title","value":"AutomixSDKMixtapeCounters"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeCounters\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKMixtapeCounters\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}