{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@E@AutomixIQStatusVariable@AutomixIQStatusVariableFailedTrackLoadIdentifiers","navigatorTitle":[{"text":"AutomixIQStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}],"roleHeading":"Case","role":"symbol","title":"AutomixIQStatusVariable.failedTrackLoadIdentifiers","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/failedTrackLoadIdentifiers","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/failedtrackloadidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiqstatusvariable\/failedtrackloadidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"kind":"symbol","url":"\/documentation\/socialradio","role":"collection","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable/failedTrackLoadIdentifiers":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable\/failedTrackLoadIdentifiers","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"title":"AutomixIQStatusVariable.failedTrackLoadIdentifiers","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"AutomixIQStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixiqstatusvariable\/failedtrackloadidentifiers","role":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStatusVariable":{"abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"type":"topic","url":"\/documentation\/socialradio\/automixiqstatusvariable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStatusVariable","title":"AutomixIQStatusVariable","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStatusVariable"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQStatusVariable"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AutomixIQStatusVariableFailedTrackLoadIdentifiers","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixIQStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixIQStatusVariableFailedTrackLoadIdentifiers"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1failedTrackLoadIdentifiers\/title","value":"AutomixIQStatusVariableFailedTrackLoadIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable~1failedTrackLoadIdentifiers\/fragments","value":[{"kind":"identifier","text":"AutomixIQStatusVariableFailedTrackLoadIdentifiers"}]},{"op":"replace","value":"AutomixIQStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/fragments","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStatusVariable\/navigatorTitle","value":[{"text":"AutomixIQStatusVariable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}