{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelDebug"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelDebug"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite\/socialradiologlevel\/logleveldebug"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite\/socialradiologlevel\/logleveldebug"]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelDebug"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelDebug"}],"externalID":"c:@M@SocialRadioLite@E@SocialRadioLogLevel@SocialRadioLogLevelLogLevelDebug","modules":[{"name":"SocialRadioLite"}],"roleHeading":"Case","title":"SocialRadioLogLevel.logLevelDebug","symbolKind":"case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel"]]},"references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel/logLevelDebug":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"logLevelDebug","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelDebug"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel\/logLevelDebug","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiologlevel\/logleveldebug","title":"SocialRadioLogLevel.logLevelDebug","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel","role":"symbol","abstract":[{"type":"text","text":"SocialRadioLogLevel is an enum of all the AutomixIQ available log levels"}],"title":"SocialRadioLogLevel","type":"topic","url":"\/documentation\/socialradiolite\/socialradiologlevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioLogLevel"}],"navigatorTitle":[{"text":"SocialRadioLogLevel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SocialRadioLogLevelLogLevelDebug"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SocialRadioLogLevelLogLevelDebug","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelDebug"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SocialRadioLogLevelLogLevelDebug","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelDebug\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioLogLevelLogLevelDebug"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel~1logLevelDebug\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/title","value":"SocialRadioLogLevel","op":"replace"},{"value":[{"text":"SocialRadioLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/fragments"},{"value":[{"text":"SocialRadioLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}