{"sections":[],"variants":[{"paths":["\/documentation\/automixiq\/automixiqconfig\/automaticallylogplayback"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqconfig\/automaticallylogplayback"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticallyLogPlayback"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"]]},"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixIQConfig(py)automaticallyLogPlayback","role":"symbol","modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"kind":"identifier","text":"automaticallyLogPlayback"}],"roleHeading":"Instance Property","title":"automaticallyLogPlayback","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automaticallyLogPlayback"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig\/automaticallyLogPlayback","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig/automaticallyLogPlayback":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig\/automaticallyLogPlayback","url":"\/documentation\/automixiq\/automixiqconfig\/automaticallylogplayback","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automaticallyLogPlayback","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"text":"automaticallyLogPlayback","kind":"identifier"}],"abstract":[],"title":"automaticallyLogPlayback"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"role":"symbol","title":"AutomixIQConfig","navigatorTitle":[{"kind":"identifier","text":"AutomixIQConfig"}],"abstract":[],"url":"\/documentation\/automixiq\/automixiqconfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQConfig","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"automaticallyLogPlayback","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"automaticallyLogPlayback","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticallyLogPlayback"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"automaticallyLogPlayback","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig~1automaticallyLogPlayback\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig~1automaticallyLogPlayback\/fragments","value":[{"kind":"identifier","text":"automaticallyLogPlayback"}],"op":"replace"},{"value":"AutomixIQConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments","op":"replace","value":[{"text":"AutomixIQConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle","value":[{"text":"AutomixIQConfig","kind":"identifier"}],"op":"replace"}]}]}