{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","role":"symbol","title":"remove(_:)","symbolKind":"method","externalID":"c:objc(cs)AutomixIQObjC(im)removeStatusObserverDelegate:","modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate"},{"kind":"text","text":")"}]},"variants":[{"paths":["\/documentation\/automixiq\/automixiqobjc\/remove(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"statusObserverDelegate","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","text":"AutomixIQStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/remove(_:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC/remove(_:)":{"title":"remove(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/remove(_:)","url":"\/documentation\/automixiq\/automixiqobjc\/remove(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixIQStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixIQStatusObserverDelegate"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC","title":"AutomixIQObjC","navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"abstract":[],"kind":"symbol","url":"\/documentation\/automixiq\/automixiqobjc","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQObjC"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","type":"topic","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStatusObserverDelegate":{"title":"AutomixIQStatusObserverDelegate","abstract":[{"type":"text","text":"AutomixIQStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStatusObserverDelegate","url":"\/documentation\/automixiq\/automixiqstatusobserverdelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/title","value":"AutomixIQStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/fragments","value":[{"text":"AutomixIQStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStatusObserverDelegate"}]}]}]}