{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding commenting a mixtape."}],"metadata":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}],"title":"SocialLayerMixtapeCommentsDelegate","modules":[{"name":"SocialRadio"}],"symbolKind":"protocol","externalID":"c:@M@SocialRadio@objc(pl)SocialLayerMixtapeCommentsDelegate","roleHeading":"Protocol","navigatorTitle":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/deleteComment(mixIdentifier:commentIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/getComment(mixIdentifier:commentIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/getComments(identifier:timelineComments:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate"],"anchor":"Initialising-SocialRadio-for-use-with-custom-audio-and-custom-social-layer","title":"Initialising SocialRadio for use with custom audio and custom social layer"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/sociallayermixtapecommentsdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/sociallayermixtapecommentsdelegate"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate/deleteComment(mixIdentifier:commentIdentifier:completion:)":{"navigatorTitle":[{"text":"deleteCommentWithMixIdentifier:commentIdentifier:completion:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteComment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"mixIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"commentIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"deleteComment(mixIdentifier:commentIdentifier:completion:)","abstract":[{"type":"text","text":"Deletes a specific comment from a mixtape."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/deleteComment(mixIdentifier:commentIdentifier:completion:)","url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate\/deletecomment(mixidentifier:commentidentifier:completion:)","kind":"symbol","required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate/getComments(identifier:timelineComments:completion:)":{"navigatorTitle":[{"text":"getCommentsWithIdentifier:timelineComments:completion:","kind":"identifier"}],"title":"getComments(identifier:timelineComments:completion:)","abstract":[{"type":"text","text":"Fetches general or timeline-specific comments on a mixtape."}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate\/getcomments(identifier:timelinecomments:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getComments","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timelineComments","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"comments","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"SocialRadioComment","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioComment","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/getComments(identifier:timelineComments:completion:)","type":"topic","required":true},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate":{"title":"SocialLayerMixtapeCommentsDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate","type":"topic","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding commenting a mixtape.","type":"text"}],"navigatorTitle":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioTrackMetadataDelegate":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Handles track recommendations and artwork"}],"title":"SocialRadioTrackMetadataDelegate","kind":"symbol","url":"\/documentation\/socialradio\/socialradiotrackmetadatadelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerTrackLikesDelegate":{"url":"\/documentation\/socialradio\/sociallayertracklikesdelegate","role":"symbol","abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a track."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate","navigatorTitle":[{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}],"title":"SocialLayerTrackLikesDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerModerationDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","type":"topic","url":"\/documentation\/socialradio\/sociallayermoderationdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding content moderation."}],"title":"SocialLayerModerationDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiouidelegate","title":"SocialRadioUIDelegate","abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","role":"symbol","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"title":"AutomixIQStreamingDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"url":"\/documentation\/socialradio\/automixiqstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","kind":"symbol","navigatorTitle":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerDelegates":{"navigatorTitle":[{"text":"SocialLayerDelegates","kind":"identifier"}],"title":"SocialLayerDelegates","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerDelegates","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialLayerDelegates is an object that holds all delegates used to communicate between the SocialRadio SDK and a backend that handles storage of social interactions."},{"type":"text","text":" "},{"type":"text","text":"‘authenticationDelegate’, ‘userDelegate’ and ‘liveMixtapeDelegate’ are required always. Every other delegate can be nil and is only required if your backend and SocialRadio implementation supports the attached features, like commenting, moderation, backgrounds, etc."},{"type":"text","text":" "},{"type":"text","text":"See each delegate’s documentation for details."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","type":"topic","url":"\/documentation\/socialradio\/sociallayerdelegates"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"kind":"symbol","url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","title":"SocialRadioStatusObserverDelegate","abstract":[],"navigatorTitle":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate/getComment(mixIdentifier:commentIdentifier:completion:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/getComment(mixIdentifier:commentIdentifier:completion:)","required":true,"navigatorTitle":[{"text":"getCommentWithMixIdentifier:commentIdentifier:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getComment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mixIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"commentIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"comment","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioComment","text":"SocialRadioComment","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate\/getcomment(mixidentifier:commentidentifier:completion:)","title":"getComment(mixIdentifier:commentIdentifier:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Retrieves a specific comment from a mixtape."}],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerUserDelegate":{"role":"symbol","title":"SocialLayerUserDelegate","type":"topic","url":"\/documentation\/socialradio\/sociallayeruserdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerUserDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SocialLayerUserDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding  users."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerNotificationsDelegate":{"title":"SocialLayerNotificationsDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialLayerNotificationsDelegate"}],"abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding notifications."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerNotificationsDelegate"}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayernotificationsdelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AuthenticationDelegate":{"kind":"symbol","url":"\/documentation\/socialradio\/authenticationdelegate","navigatorTitle":[{"text":"AuthenticationDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Handles handoff of authentication tokens"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationDelegate","kind":"identifier"}],"title":"AuthenticationDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeLikesDelegate":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","abstract":[{"text":"Handles communication between SocialRadio SDK and a backend regarding liking and unliking a mixtape.","type":"text"}],"role":"symbol","title":"SocialLayerMixtapeLikesDelegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialLayerMixtapeLikesDelegate"}],"type":"topic","url":"\/documentation\/socialradio\/sociallayermixtapelikesdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerMixtapeLikesDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeCommentsDelegate/postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)":{"title":"postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)","url":"\/documentation\/socialradio\/sociallayermixtapecommentsdelegate\/postcomment(useridentifier:mixidentifier:text:tags:trackindex10:mixtimestamp:completion:)","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Posts a comment to a mixtape."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"postComment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mixIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tags"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioCommentTag","text":"SocialRadioCommentTag"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"trackIndex10"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mixTimestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioComment","text":"SocialRadioComment"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerMixtapeBackgroundsDelegate":{"role":"symbol","title":"SocialLayerMixtapeBackgroundsDelegate","navigatorTitle":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/socialradio\/sociallayermixtapebackgroundsdelegate","abstract":[{"type":"text","text":"Handles communication between SocialRadio SDK and a backend regarding mixtape backgrounds."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerAuthenticationDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding authentication"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","title":"SocialLayerAuthenticationDelegate","url":"\/documentation\/socialradio\/sociallayerauthenticationdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Initialising-SocialRadio-with-custom-audio-and-social-layer-article":{"role":"article","title":"Initializing SocialRadio with custom audio and social layer","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with custom audio track data and custom social layer.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","url":"\/documentation\/socialradio\/initialising-socialradio-with-custom-audio-and-social-layer-article","kind":"article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialLayerLiveMixtapeDelegate":{"title":"SocialLayerLiveMixtapeDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"(Required) Handles communication between SocialRadio SDK and a backend regarding live mixtapes."}],"type":"topic","url":"\/documentation\/socialradio\/sociallayerlivemixtapedelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","navigatorTitle":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"SocialLayerMixtapeCommentsDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SocialLayerMixtapeCommentsDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/deleteComment(mixIdentifier:commentIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/getComment(mixIdentifier:commentIdentifier:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/getComments(identifier:timelineComments:completion:)","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeCommentsDelegate\/postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Initialising-SocialRadio-with-custom-audio-and-social-layer-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioTrackMetadataDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerDelegates","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerAuthenticationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerLiveMixtapeDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerUserDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeBackgroundsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerMixtapeLikesDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerModerationDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerNotificationsDelegate","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialLayerTrackLikesDelegate"],"generated":true,"title":"Initialising SocialRadio for use with custom audio and custom social layer","anchor":"Initialising-SocialRadio-for-use-with-custom-audio-and-custom-social-layer"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1deleteComment(mixIdentifier:commentIdentifier:completion:)\/title","op":"replace","value":"deleteCommentWithMixIdentifier:commentIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1deleteComment(mixIdentifier:commentIdentifier:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deleteCommentWithMixIdentifier:commentIdentifier:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1getComments(identifier:timelineComments:completion:)\/title","value":"getCommentsWithIdentifier:timelineComments:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1getComments(identifier:timelineComments:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getCommentsWithIdentifier:timelineComments:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/title","value":"SocialLayerMixtapeCommentsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerMixtapeCommentsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/title","value":"SocialRadioTrackMetadataDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/fragments","value":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioTrackMetadataDelegate\/navigatorTitle","value":[{"text":"SocialRadioTrackMetadataDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/title","value":"SocialLayerTrackLikesDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerTrackLikesDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerTrackLikesDelegate\/navigatorTitle","value":[{"text":"SocialLayerTrackLikesDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/title","value":"SocialLayerModerationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/fragments","value":[{"text":"SocialLayerModerationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerModerationDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerModerationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","value":"SocialRadioUIDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title","value":"AutomixIQStreamingDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/title","value":"SocialLayerDelegates"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/fragments","value":[{"text":"SocialLayerDelegates","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerDelegates\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerDelegates"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","value":"SocialRadioStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1getComment(mixIdentifier:commentIdentifier:completion:)\/title","value":"getCommentWithMixIdentifier:commentIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1getComment(mixIdentifier:commentIdentifier:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getCommentWithMixIdentifier:commentIdentifier:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/title","value":"SocialLayerUserDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerUserDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerUserDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerUserDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/title","value":"SocialLayerNotificationsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerNotificationsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerNotificationsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerNotificationsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/title","value":"AuthenticationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/fragments","value":[{"kind":"identifier","text":"AuthenticationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AuthenticationDelegate\/navigatorTitle","value":[{"text":"AuthenticationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/title","value":"SocialLayerMixtapeLikesDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerMixtapeLikesDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeLikesDelegate\/navigatorTitle","value":[{"text":"SocialLayerMixtapeLikesDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)\/title","value":"postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeCommentsDelegate~1postComment(userIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"postCommentWithUserIdentifier:mixIdentifier:text:tags:trackIndex10:mixTimestamp:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/title","value":"SocialLayerMixtapeBackgroundsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/fragments","value":[{"text":"SocialLayerMixtapeBackgroundsDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerMixtapeBackgroundsDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerMixtapeBackgroundsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/title","value":"SocialLayerAuthenticationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/fragments","value":[{"kind":"identifier","text":"SocialLayerAuthenticationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerAuthenticationDelegate\/navigatorTitle","value":[{"text":"SocialLayerAuthenticationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/title","value":"SocialLayerLiveMixtapeDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/fragments","value":[{"text":"SocialLayerLiveMixtapeDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialLayerLiveMixtapeDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialLayerLiveMixtapeDelegate"}]}]}]}