{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP","doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SocialRadio\/Se","doc:\/\/org.cocoapods.SocialRadio\/SE","doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiomixtapetrackimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiomixtapetrackimage"]}],"seeAlsoSections":[{"title":"Data models","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse"],"anchor":"Data-models","generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"sections":[],"abstract":[{"text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/init(from:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/imageHeight","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/imageWidth","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/url"],"anchor":"Instance-Properties","generated":true}],"metadata":{"title":"SocialRadioMixtapeTrackImage","modules":[{"name":"SocialRadio"}],"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioMixtapeTrackImage","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"roleHeading":"Class"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioWaveformBlob":{"navigatorTitle":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/socialradiowaveformblob","title":"SocialRadioWaveformBlob","abstract":[{"type":"text","text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SE"},"doc://org.cocoapods.SocialRadio/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(pl)NSObject"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusVariable":{"type":"topic","abstract":[{"type":"text","text":"SocialRadio status variable type"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatusVariable"}],"url":"\/documentation\/socialradio\/socialradiostatusvariable","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"kind":"symbol","title":"SocialRadioStatusVariable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAuthenticationResponse":{"title":"TunedAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse","type":"topic","url":"\/documentation\/socialradio\/tunedauthenticationresponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAuthenticationResponse"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrack":{"abstract":[{"text":"SocialRadioMixtapeTrack models a track in a mixtape","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"title":"SocialRadioMixtapeTrack","url":"\/documentation\/socialradio\/socialradiomixtapetrack","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedPluginMetadataModel":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedPluginMetadataModel","kind":"identifier"}],"url":"\/documentation\/socialradio\/tunedpluginmetadatamodel","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","navigatorTitle":[{"text":"TunedPluginMetadataModel","kind":"identifier"}],"abstract":[{"type":"text","text":"TunedPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"type":"text","text":" "},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"title":"TunedPluginMetadataModel","type":"topic"},"doc://org.cocoapods.SocialRadio/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUser":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","kind":"symbol","abstract":[{"text":"SocialRadioUser models a user","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUser","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/socialradiouser","title":"SocialRadioUser","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SocialRadio/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH"},"doc://org.cocoapods.SocialRadio/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SocialRadio\/s7CVarArgP"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCredentials":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","url":"\/documentation\/socialradio\/socialradiocredentials","title":"SocialRadioCredentials","abstract":[{"text":"SocialRadioCredentials models credentials to access social REST APIs.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioCredentials","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioCredentials","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioComment":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioComment","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"SocialRadioComment models a comment","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SocialRadioComment","kind":"identifier"}],"title":"SocialRadioComment","url":"\/documentation\/socialradio\/socialradiocomment","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage/url":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"url","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiomixtapetrackimage\/url","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/url","kind":"symbol","abstract":[{"text":"The url for the image","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"url"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioList":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioList","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","navigatorTitle":[{"text":"SocialRadioList","kind":"identifier"}],"title":"SocialRadioList","url":"\/documentation\/socialradio\/socialradiolist","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage/imageHeight":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/imageHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradiomixtapetrackimage\/imageheight","abstract":[{"type":"text","text":"The height of the image"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageHeight"}],"title":"imageHeight"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage/init(from:)":{"kind":"symbol","title":"init(from:)","role":"symbol","url":"\/documentation\/socialradio\/socialradiomixtapetrackimage\/init(from:)","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/init(from:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage","navigatorTitle":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"role":"symbol","type":"topic","title":"SocialRadioMixtapeTrackImage","abstract":[{"type":"text","text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape"}],"kind":"symbol","url":"\/documentation\/socialradio\/socialradiomixtapetrackimage"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtape":{"title":"SocialRadioMixtape","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","url":"\/documentation\/socialradio\/socialradiomixtape","role":"symbol","abstract":[{"text":"SocialRadioMixtape models a mixtape","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtape","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioMixtape","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedArtistModel":{"type":"topic","title":"TunedArtistModel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedArtistModel"}],"navigatorTitle":[{"kind":"identifier","text":"TunedArtistModel"}],"url":"\/documentation\/socialradio\/tunedartistmodel","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"TunedArtistModel models an artist."}]},"doc://org.cocoapods.SocialRadio/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatus":{"title":"SocialRadioStatus","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStatus"}],"url":"\/documentation\/socialradio\/socialradiostatus","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatus"}],"kind":"symbol","abstract":[{"text":"SocialRadioStatus models the State of the AutomixIQ during playback.","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage/imageWidth":{"title":"imageWidth","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageWidth","kind":"identifier"}],"url":"\/documentation\/socialradio\/socialradiomixtapetrackimage\/imagewidth","type":"topic","kind":"symbol","abstract":[{"text":"The width of the image","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/imageWidth"},"doc://org.cocoapods.SocialRadio/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/Se"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioCommentTag":{"title":"SocialRadioCommentTag","navigatorTitle":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"abstract":[{"type":"text","text":"SocialRadioCommentTag models a user tag in a comment"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","type":"topic","url":"\/documentation\/socialradio\/socialradiocommenttag","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioCommentTag"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeTrackImage/init":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/init","url":"\/documentation\/socialradio\/socialradiomixtapetrackimage\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeLite":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"title":"SocialRadioMixtapeLite","abstract":[{"text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields","type":"text"}],"url":"\/documentation\/socialradio\/socialradiomixtapelite","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Data-models-article":{"type":"topic","kind":"article","abstract":[{"text":"How data is passed to and from SocialRadio","type":"text"}],"role":"article","title":"Data models","url":"\/documentation\/socialradio\/data-models-article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedTrackModel":{"abstract":[{"type":"text","text":"TunedTrackModel models a track. This metadata is required."}],"url":"\/documentation\/socialradio\/tunedtrackmodel","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedTrackModel"}],"role":"symbol","kind":"symbol","type":"topic","title":"TunedTrackModel","navigatorTitle":[{"kind":"identifier","text":"TunedTrackModel"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPlaybackMode":{"title":"SocialRadioPlaybackMode","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","url":"\/documentation\/socialradio\/socialradioplaybackmode","navigatorTitle":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"SocialRadio playback mode","type":"text"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioGenericList":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioGenericList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioGenericList","navigatorTitle":[{"text":"SocialRadioGenericList","kind":"identifier"}],"role":"symbol","type":"topic","title":"SocialRadioGenericList","abstract":[{"type":"text","text":"SocialRadioGenericList models a list of things"}],"kind":"symbol","url":"\/documentation\/socialradio\/socialradiogenericlist"},"doc://org.cocoapods.SocialRadio/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SocialRadioMixtapeTrackImage","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/imageHeight","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/imageWidth","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/url"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrackImage\/init"]}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Data models","anchor":"Data-models","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Data-models-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioWaveformBlob","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCredentials","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioComment","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioCommentTag","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedTrackModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedArtistModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAuthenticationResponse"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SocialRadioWaveformBlob","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/fragments"},{"op":"replace","value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioWaveformBlob\/navigatorTitle"},{"op":"replace","value":"SocialRadioStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/title"},{"op":"replace","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusVariable\/navigatorTitle"},{"op":"replace","value":"TunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAuthenticationResponse\/navigatorTitle"},{"op":"replace","value":"SocialRadioMixtapeTrack","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/title"},{"op":"replace","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/fragments"},{"op":"replace","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrack\/navigatorTitle"},{"op":"replace","value":"TunedPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedPluginMetadataModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedPluginMetadataModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedPluginMetadataModel\/navigatorTitle"},{"op":"replace","value":"SocialRadioUser","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUser"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/fragments"},{"op":"replace","value":[{"text":"SocialRadioUser","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUser\/navigatorTitle"},{"op":"replace","value":"SocialRadioCredentials","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioCredentials"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/fragments"},{"op":"replace","value":[{"text":"SocialRadioCredentials","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCredentials\/navigatorTitle"},{"op":"replace","value":"SocialRadioComment","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/title"},{"op":"replace","value":[{"text":"SocialRadioComment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/fragments"},{"op":"replace","value":[{"text":"SocialRadioComment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioComment\/navigatorTitle"},{"op":"replace","value":"url","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage~1url\/title"},{"op":"replace","value":[{"text":"url","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage~1url\/fragments"},{"op":"replace","value":"SocialRadioList","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioList"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioList"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioList\/navigatorTitle"},{"op":"replace","value":"imageHeight","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage~1imageHeight\/title"},{"op":"replace","value":[{"kind":"identifier","text":"imageHeight"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage~1imageHeight\/fragments"},{"op":"replace","value":"SocialRadioMixtapeTrackImage","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage\/navigatorTitle"},{"op":"replace","value":"SocialRadioMixtape","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtape"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/fragments"},{"op":"replace","value":[{"text":"SocialRadioMixtape","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtape\/navigatorTitle"},{"op":"replace","value":"TunedArtistModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"TunedArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedArtistModel\/navigatorTitle"},{"op":"replace","value":"SocialRadioStatus","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/title"},{"op":"replace","value":[{"text":"SocialRadioStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/fragments"},{"op":"replace","value":[{"text":"SocialRadioStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatus\/navigatorTitle"},{"op":"replace","value":"imageWidth","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage~1imageWidth\/title"},{"op":"replace","value":[{"text":"imageWidth","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeTrackImage~1imageWidth\/fragments"},{"op":"replace","value":"SocialRadioCommentTag","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioCommentTag"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioCommentTag\/navigatorTitle"},{"op":"replace","value":"SocialRadioMixtapeLite","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeLite"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/fragments"},{"op":"replace","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeLite\/navigatorTitle"},{"op":"replace","value":"TunedTrackModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/title"},{"op":"replace","value":[{"text":"TunedTrackModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedTrackModel\/navigatorTitle"},{"op":"replace","value":"SocialRadioPlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/title"},{"op":"replace","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/fragments"},{"op":"replace","value":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPlaybackMode\/navigatorTitle"}]}]}