{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"text":"AutomixSDKConfig","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedDelegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","text":"TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CompletionWithError","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]},{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig"},{"kind":"text","text":", "},{"text":"tunedDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": (any "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"method","title":"initialise(with:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","modules":[{"name":"AutomixIQ"}],"externalID":"c:objc(cs)AutomixSDKObjC(cm)initialiseWithConfig:tunedDelegate:statusDelegate:musicCacheDelegate:completion:","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"AutomixSDKConfig","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"tunedDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkobjc\/initialise(with:tuneddelegate:statusdelegate:musiccachedelegate:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC\/initialise(with:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKConfig":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKConfig"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKConfig"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKConfig","role":"symbol","url":"\/documentation\/automixiq\/automixsdkconfig","title":"AutomixSDKConfig","kind":"symbol","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKObjC/initialise(with:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC\/initialise(with:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkobjc\/initialise(with:tuneddelegate:statusdelegate:musiccachedelegate:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedDelegate"},{"text":": any ","kind":"text"},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusDelegate"},{"text":": (any ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"text":"?)","kind":"text"}],"title":"initialise(with:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedMusicCacheDelegate":{"navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/tunedmusiccachedelegate","type":"topic","role":"symbol","title":"TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","kind":"symbol","abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKObjC":{"title":"AutomixSDKObjC","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkobjc","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKObjC","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKObjC"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","title":"AutomixSDKStatusObserverDelegate","abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/tunedrestdelegate","type":"topic","role":"symbol","title":"TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","kind":"symbol","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TunedRestDelegate","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/CompletionWithError":{"role":"symbol","url":"\/documentation\/automixiq\/completionwitherror","abstract":[],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionWithError"}],"navigatorTitle":[{"text":"CompletionWithError","kind":"identifier"}],"title":"CompletionWithError","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError"}},"variantOverrides":[{"patch":[{"value":"AutomixSDKConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/title"},{"value":[{"text":"AutomixSDKConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKConfig\/navigatorTitle","value":[{"text":"AutomixSDKConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate"},{"value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title","op":"replace","value":"TunedRestDelegate"},{"value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments","op":"replace"},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}