{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixiqobjc\/addads(withmetadata:aftertrackidentifier:completion:)"]}],"kind":"symbol","metadata":{"title":"addAds(withMetadata:afterTrackIdentifier:completion:)","externalID":"c:objc(cs)AutomixIQObjC(im)addAdsWithMetadata:afterTrackIdentifier:completion:","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMetadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TunedAdModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedAdModel"},{"text":"], ","kind":"text"},{"text":"afterTrackIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/addAds(withMetadata:afterTrackIdentifier:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMetadata","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"TunedAdModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedAdModel"},{"text":"], ","kind":"text"},{"text":"afterTrackIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"languages":["swift"]},{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMetadata"},{"kind":"text","text":" "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TunedAdModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedAdModel"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"afterTrackIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","title":"AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC/addAds(withMetadata:afterTrackIdentifier:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC\/addAds(withMetadata:afterTrackIdentifier:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withMetadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TunedAdModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedAdModel"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"afterTrackIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"type":"topic","role":"symbol","url":"\/documentation\/automixiq\/automixiqobjc\/addads(withmetadata:aftertrackidentifier:completion:)","abstract":[],"title":"addAds(withMetadata:afterTrackIdentifier:completion:)","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQObjC":{"url":"\/documentation\/automixiq\/automixiqobjc","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQObjC","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQObjC"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQObjC"}],"title":"AutomixIQObjC"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAdModel":{"abstract":[{"type":"text","text":"TunedAdModel models a Ad."}],"kind":"symbol","role":"symbol","title":"TunedAdModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedAdModel"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAdModel","url":"\/documentation\/automixiq\/tunedadmodel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TunedAdModel"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel\/title","op":"replace","value":"TunedAdModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel\/fragments","op":"replace","value":[{"text":"TunedAdModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAdModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedAdModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}