{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeTiny"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/radiouifontsizetiny"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/radiosdkuiconfig\/radiouifontsizetiny"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeTiny","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"]]},"metadata":{"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)RadioSDKUIConfig(py)radioUIFontSizeTiny","title":"radioUIFontSizeTiny","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"radioUIFontSizeTiny","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeTiny"}],"modules":[{"name":"SocialRadio"}]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig/radioUIFontSizeTiny":{"abstract":[],"url":"\/documentation\/socialradio\/radiosdkuiconfig\/radiouifontsizetiny","title":"radioUIFontSizeTiny","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig\/radioUIFontSizeTiny","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeTiny"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeTiny"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/socialradio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKUIConfig":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKUIConfig"}],"url":"\/documentation\/socialradio\/radiosdkuiconfig","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"title":"RadioSDKUIConfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKUIConfig"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"radioUIFontSizeTiny"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"radioUIFontSizeTiny","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"radioUIFontSizeTiny","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeTiny\/title","value":"radioUIFontSizeTiny"},{"value":[{"text":"radioUIFontSizeTiny","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig~1radioUIFontSizeTiny\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/title","value":"RadioSDKUIConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"op":"replace"},{"value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKUIConfig\/navigatorTitle"}]}]}