{"metadata":{"title":"SocialRadioLite","symbolKind":"module","role":"collection","modules":[{"name":"SocialRadioLite"}],"roleHeading":"Framework","externalID":"SocialRadioLite"},"sections":[],"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions.","type":"text"}],"primaryContentSections":[{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"Overview"},{"type":"paragraph","inlineContent":[{"text":"SocialRadio is a framework that exposes an interactive UI to AutomixIQ as well as the capability to leverage Pacemaker Technology to start a broadcast with music from your catalog, your voice and other content, as well as joining available broadcasts, interact with other members of a community or the broacaster, and more.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This documentation provides a step-by-step guide on how to get started with using the SocialRadio in your application."}]},{"inlineContent":[{"type":"image","identifier":"overview-tuned-demo-radio"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradiolite"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradiolite"]}],"topicSections":[{"title":"Importing SocialRadio","anchor":"Importing-SocialRadio","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Importing-SocialRadio-article"]},{"title":"SocialRadio singleton","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC"],"anchor":"SocialRadio-singleton"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStreamingDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel"],"title":"Initializing SocialRadio for use with Tuned Global’s APIs","anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs"},{"title":"Starting a broadcast","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Starting-a-broadcast-article"],"anchor":"Starting-a-broadcast"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Joining-a-broadcast-article"],"title":"Joining a broadcast","anchor":"Joining-a-broadcast"},{"title":"Getting available broadcasts","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Getting-available-broadcasts-article"],"anchor":"Getting-available-broadcasts"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Moderation-article"],"title":"Moderation","anchor":"Moderation"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Errors-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/sdkError(code:)"],"anchor":"Errors","title":"Errors"},{"anchor":"Data-models","title":"Data models","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioGenericList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"]},{"anchor":"AutomixIQ","title":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQ-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQObjC"]},{"anchor":"Persistency","title":"Persistency","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLog","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogAttributes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogID","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLog","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogID","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType"]},{"title":"Type Aliases","generated":true,"anchor":"Type-Aliases","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/CompletionWithError","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/CompletionWithErrorAndPlaybackState"]},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Swift"],"title":"Extended Modules","generated":true,"anchor":"Extended-Modules"}],"hierarchy":{"paths":[[]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite"},"kind":"symbol","references":{"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlaybackEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQPlaybackEventType"}],"url":"\/documentation\/socialradiolite\/automixiqplaybackeventtype","navigatorTitle":[{"text":"AutomixIQPlaybackEventType","kind":"identifier"}],"title":"AutomixIQPlaybackEventType","type":"topic","abstract":[{"type":"text","text":"AutomixIQPlaybackEventType is an enum of all the available playback events"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrack":{"type":"topic","title":"SocialRadioMixtapeTrack","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtapeTrack","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtapeTrack models a track in a mixtape"}],"role":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrack","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioList":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","role":"symbol","abstract":[],"title":"SocialRadioList","url":"\/documentation\/socialradiolite\/socialradiolist","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioList"}],"navigatorTitle":[{"text":"SocialRadioList","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStreamingDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"abstract":[{"text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations.","type":"text"}],"navigatorTitle":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStreamingDelegate","url":"\/documentation\/socialradiolite\/socialradiostreamingdelegate","title":"SocialRadioStreamingDelegate"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Moderation-article":{"kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Moderation-article","abstract":[{"type":"text","text":"Tools to interact with the social layer."}],"role":"article","type":"topic","title":"Moderation","url":"\/documentation\/socialradiolite\/moderation-article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTrackModel":{"abstract":[{"type":"text","text":"SocialRadioTrackModel models a track. This metadata is required."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTrackModel"}],"navigatorTitle":[{"text":"SocialRadioTrackModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiotrackmodel","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","title":"SocialRadioTrackModel","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIConfig":{"url":"\/documentation\/socialradiolite\/socialradiouiconfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","abstract":[],"role":"symbol","title":"SocialRadioUIConfig","navigatorTitle":[{"text":"SocialRadioUIConfig","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIConfig","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeCounters":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}],"url":"\/documentation\/socialradiolite\/socialradiomixtapecounters","abstract":[{"text":"SocialRadioMixtapeCounters models the set of counters for information about a mixtape","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","title":"SocialRadioMixtapeCounters","kind":"symbol"},"overview-tuned-demo-radio":{"type":"image","alt":"A player interface that uses SocialRadio to broadcast a show.","identifier":"overview-tuned-demo-radio","variants":[{"url":"\/images\/org.cocoapods.SocialRadioLite\/overview-tuned-demo-radio.png","traits":["1x","light"]}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioWaveformBlob":{"navigatorTitle":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"type":"topic","title":"SocialRadioWaveformBlob","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiowaveformblob","abstract":[{"text":"SocialRadioWaveformBlob models the data to create a waveform shape representing a track","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/CompletionWithErrorAndPlaybackState":{"abstract":[],"title":"CompletionWithErrorAndPlaybackState","url":"\/documentation\/socialradiolite\/completionwitherrorandplaybackstate","navigatorTitle":[{"text":"CompletionWithErrorAndPlaybackState","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/CompletionWithErrorAndPlaybackState","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"CompletionWithErrorAndPlaybackState","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedAuthenticationResponse":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}],"abstract":[{"text":"AutomixIQTunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"title":"SocialRadioTunedAuthenticationResponse","url":"\/documentation\/socialradiolite\/socialradiotunedauthenticationresponse","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio","kind":"symbol","title":"SocialRadio","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadio"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadio"}],"type":"topic","url":"\/documentation\/socialradiolite\/socialradio","abstract":[{"type":"text","text":"SocialRadio represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioPlaybackMode":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioPlaybackMode","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioplaybackmode","title":"SocialRadioPlaybackMode","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode","type":"topic","abstract":[{"text":"SocialRadio playback mode","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioPlaybackMode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioArtistModel":{"role":"symbol","navigatorTitle":[{"text":"SocialRadioArtistModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioartistmodel","abstract":[{"type":"text","text":"SocialRadioArtistModel models an artist."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioArtistModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","title":"SocialRadioArtistModel","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusObserverDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusObserverDelegate","url":"\/documentation\/socialradiolite\/socialradiostatusobserverdelegate","title":"SocialRadioStatusObserverDelegate"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioLogLevel":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel","role":"symbol","abstract":[{"type":"text","text":"SocialRadioLogLevel is an enum of all the AutomixIQ available log levels"}],"title":"SocialRadioLogLevel","type":"topic","url":"\/documentation\/socialradiolite\/socialradiologlevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioLogLevel"}],"navigatorTitle":[{"text":"SocialRadioLogLevel","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/CompletionWithError":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/CompletionWithError","abstract":[],"role":"symbol","type":"topic","title":"CompletionWithError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CompletionWithError"}],"url":"\/documentation\/socialradiolite\/completionwitherror","navigatorTitle":[{"text":"CompletionWithError","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioFeatureSetConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","url":"\/documentation\/socialradiolite\/socialradiofeaturesetconfig","title":"SocialRadioFeatureSetConfig"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioGenericList":{"navigatorTitle":[{"text":"SocialRadioGenericList","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioGenericList","title":"SocialRadioGenericList","kind":"symbol","abstract":[{"text":"SocialRadioGenericList models a list of things","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioGenericList","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiogenericlist"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatus":{"navigatorTitle":[{"text":"SocialRadioStatus","kind":"identifier"}],"type":"topic","title":"SocialRadioStatus","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiostatus","abstract":[{"text":"SocialRadioStatus models the State of the AutomixIQ during playback.","type":"text"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogID":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogid","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogID"}],"title":"AutomixIQTransitionLogID","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogID","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioPluginMetadataModel":{"role":"symbol","navigatorTitle":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiopluginmetadatamodel","abstract":[{"type":"text","text":"SocialRadioPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"text":" ","type":"text"},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioPluginMetadataModel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","title":"SocialRadioPluginMetadataModel","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLogAttributes":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLogAttributes","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"url":"\/documentation\/socialradiolite\/automixiqtransitionlogattributes","title":"AutomixIQTransitionLogAttributes","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLogAttributes"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeTrackImage":{"navigatorTitle":[{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"type":"topic","title":"SocialRadioMixtapeTrackImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeTrackImage","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapetrackimage","abstract":[{"type":"text","text":"SocialRadioMixtapeTrackImage models the image for a track in a mixtape"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtape":{"type":"topic","kind":"symbol","title":"SocialRadioMixtape","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioMixtape","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioMixtape"}],"role":"symbol","abstract":[{"type":"text","text":"SocialRadioMixtape models a mixtape"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","url":"\/documentation\/socialradiolite\/socialradiomixtape"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite":{"role":"collection","type":"topic","title":"SocialRadioLite","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions."}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite","kind":"symbol","url":"\/documentation\/socialradiolite"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioObjC":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioObjC","url":"\/documentation\/socialradiolite\/socialradioobjc","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioObjC","kind":"identifier"}],"kind":"symbol","title":"SocialRadioObjC","navigatorTitle":[{"kind":"identifier","text":"SocialRadioObjC"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLogID":{"title":"AutomixIQPlayLogID","kind":"symbol","type":"topic","url":"\/documentation\/socialradiolite\/automixiqplaylogid","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQPlayLogID","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogID"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogID","role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Getting-available-broadcasts-article":{"type":"topic","abstract":[{"text":"How to learn which broadcasts are currently live.","type":"text"}],"title":"Getting available broadcasts","role":"article","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Getting-available-broadcasts-article","url":"\/documentation\/socialradiolite\/getting-available-broadcasts-article","kind":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Data-models-article":{"role":"article","url":"\/documentation\/socialradiolite\/data-models-article","abstract":[{"type":"text","text":"How data is passed to and from SocialRadio"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","title":"Data models","kind":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Starting-a-broadcast-article":{"kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Starting-a-broadcast-article","abstract":[{"text":"Creating a draft for a radio show and presenting the UI to curate it, then going live.","type":"text"}],"role":"article","type":"topic","title":"Starting a broadcast","url":"\/documentation\/socialradiolite\/starting-a-broadcast-article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQObjC":{"title":"AutomixIQObjC","navigatorTitle":[{"text":"AutomixIQObjC","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQObjC","kind":"symbol","url":"\/documentation\/socialradiolite\/automixiqobjc","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQObjC","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/sdkError(code:)":{"title":"sdkError(code:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/sdkError(code:)","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/socialradiolite\/sdkerror(code:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkError"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadioLite@E@ErrorCode","kind":"typeIdentifier","text":"ErrorCode"},{"kind":"text","text":") -> "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLog":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlayLog"}],"url":"\/documentation\/socialradiolite\/automixiqplaylog","navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLog"}],"title":"AutomixIQPlayLog","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLog","role":"symbol","kind":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Importing-SocialRadio-article":{"type":"topic","abstract":[{"text":"Accessing the SocialRadio framework","type":"text"}],"title":"Importing SocialRadio","role":"article","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Importing-SocialRadio-article","url":"\/documentation\/socialradiolite\/importing-socialradio-article","kind":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQPlayLogAttributes":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlayLogAttributes","role":"symbol","abstract":[],"title":"AutomixIQPlayLogAttributes","type":"topic","url":"\/documentation\/socialradiolite\/automixiqplaylogattributes","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQPlayLogAttributes"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQ-article":{"kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQ-article","abstract":[{"text":"Availablity of underlying technologies and APIs.","type":"text"}],"role":"article","type":"topic","title":"AutomixIQ","url":"\/documentation\/socialradiolite\/automixiq-article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Joining-a-broadcast-article":{"type":"topic","abstract":[{"text":"How to start playing a broadcast by a user that is currently live","type":"text"}],"title":"Joining a broadcast","role":"article","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Joining-a-broadcast-article","url":"\/documentation\/socialradiolite\/joining-a-broadcast-article","kind":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/ErrorCode":{"url":"\/documentation\/socialradiolite\/errorcode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode","abstract":[],"role":"symbol","title":"ErrorCode","navigatorTitle":[{"text":"ErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCode","kind":"identifier"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioMixtapeLite":{"navigatorTitle":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"type":"topic","title":"SocialRadioMixtapeLite","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiomixtapelite","abstract":[{"type":"text","text":"SocialRadioMixtapeLite models a mixtape with the minimum required fields"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUser":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","abstract":[{"type":"text","text":"SocialRadioUser models a user"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SocialRadioUser","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiouser","title":"SocialRadioUser","navigatorTitle":[{"text":"SocialRadioUser","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Errors-article":{"title":"Errors","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Errors-article","kind":"article","abstract":[{"text":"What errors the SocialRadio player can issue to help with player integration","type":"text"}],"type":"topic","role":"article","url":"\/documentation\/socialradiolite\/errors-article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioStatusVariable":{"abstract":[{"text":"SocialRadio status variable type","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusVariable","kind":"identifier"}],"title":"SocialRadioStatusVariable","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioStatusVariable","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradiostatusvariable"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioTunedRestDelegate":{"title":"SocialRadioTunedRestDelegate","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiotunedrestdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/AutomixIQTransitionLog":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQTransitionLog","role":"symbol","abstract":[],"title":"AutomixIQTransitionLog","type":"topic","url":"\/documentation\/socialradiolite\/automixiqtransitionlog","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixIQTransitionLog","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQTransitionLog"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioUIDelegate":{"title":"SocialRadioUIDelegate","kind":"symbol","url":"\/documentation\/socialradiolite\/socialradiouidelegate","abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIDelegate","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Persistency-article":{"title":"Persistency","kind":"article","type":"topic","url":"\/documentation\/socialradiolite\/persistency-article","abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article","role":"article"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Swift":{"identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Swift","title":"Swift","abstract":[],"kind":"symbol","url":"\/documentation\/socialradiolite\/swift","role":"collection","type":"topic"},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/SocialRadioConfig":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SocialRadioConfig","kind":"identifier"}],"url":"\/documentation\/socialradiolite\/socialradioconfig","title":"SocialRadioConfig","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SocialRadioConfig"}]},"doc://org.cocoapods.SocialRadioLite/documentation/SocialRadioLite/Initialising-SocialRadio-article":{"role":"article","kind":"article","url":"\/documentation\/socialradiolite\/initialising-socialradio-article","title":"Initializing SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Initialising-SocialRadio-article","type":"topic","abstract":[{"text":"How to validate your client and start using the SocialRadio SDK with Tuned Global APIs","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"anchor":"Importing-SocialRadio","title":"Importing SocialRadio","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Importing-SocialRadio-article"]},{"anchor":"SocialRadio-singleton","title":"SocialRadio singleton","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadio"]},{"title":"Initializing SocialRadio for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Initialising-SocialRadio-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedRestDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioFeatureSetConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUIConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioConfig","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusObserverDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStreamingDelegate","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatusVariable","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPlaybackMode","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioLogLevel"],"anchor":"Initializing-SocialRadio-for-use-with-Tuned-Globals-APIs"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Starting-a-broadcast-article"],"title":"Starting a broadcast","anchor":"Starting-a-broadcast"},{"title":"Joining a broadcast","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Joining-a-broadcast-article"],"anchor":"Joining-a-broadcast"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Getting-available-broadcasts-article"],"title":"Getting available broadcasts","anchor":"Getting-available-broadcasts"},{"anchor":"Moderation","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Moderation-article"],"title":"Moderation"},{"anchor":"Errors","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Errors-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/ErrorCode"],"title":"Errors"},{"identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Data-models-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTrackModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioArtistModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioPluginMetadataModel","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioStatus","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioTunedAuthenticationResponse","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioList","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioUser","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtape","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeCounters","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeLite","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrack","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioMixtapeTrackImage","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/SocialRadioWaveformBlob"],"anchor":"Data-models","title":"Data models"},{"title":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQ-article"],"anchor":"AutomixIQ"},{"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/Persistency-article","doc:\/\/org.cocoapods.SocialRadioLite\/documentation\/SocialRadioLite\/AutomixIQPlaybackEventType"],"anchor":"Persistency"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"AutomixIQPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/fragments","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1AutomixIQPlaybackEventType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixIQPlaybackEventType"}]},{"value":"SocialRadioMixtapeTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrack\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioMixtapeTrack","kind":"identifier"}]},{"value":"SocialRadioList","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/fragments","value":[{"text":"SocialRadioList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioList\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioList"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStreamingDelegate\/title","value":"SocialRadioStreamingDelegate"},{"value":[{"text":"SocialRadioStreamingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStreamingDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStreamingDelegate\/navigatorTitle"},{"value":"SocialRadioTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/fragments","value":[{"text":"SocialRadioTrackModel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTrackModel\/navigatorTitle"},{"op":"replace","value":"SocialRadioUIConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/title"},{"value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIConfig\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/title","value":"SocialRadioMixtapeCounters"},{"value":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeCounters\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}]},{"value":"SocialRadioWaveformBlob","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/title","op":"replace"},{"value":[{"text":"SocialRadioWaveformBlob","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/fragments"},{"value":[{"kind":"identifier","text":"SocialRadioWaveformBlob"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioWaveformBlob\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/title","value":"SocialRadioTunedAuthenticationResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/fragments","value":[{"kind":"identifier","text":"SocialRadioTunedAuthenticationResponse"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedAuthenticationResponse\/navigatorTitle","value":[{"text":"SocialRadioTunedAuthenticationResponse","kind":"identifier"}],"op":"replace"},{"value":"SocialRadio","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio\/title"},{"value":[{"text":"SocialRadio","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio\/fragments","op":"replace"},{"value":[{"text":"SocialRadio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadio\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/title","op":"replace","value":"SocialRadioPlaybackMode"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/fragments","value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioPlaybackMode"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPlaybackMode\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/title","value":"SocialRadioArtistModel"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioArtistModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SocialRadioArtistModel"}]},{"value":"SocialRadioStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusObserverDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusObserverDelegate\/fragments","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/title","value":"SocialRadioLogLevel","op":"replace"},{"op":"replace","value":[{"text":"SocialRadioLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/fragments"},{"value":[{"text":"SocialRadioLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioLogLevel\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/title","value":"SocialRadioFeatureSetConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/fragments","value":[{"kind":"identifier","text":"SocialRadioFeatureSetConfig"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioFeatureSetConfig\/navigatorTitle","value":[{"text":"SocialRadioFeatureSetConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/title","op":"replace","value":"SocialRadioStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatus"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatus\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/title","value":"SocialRadioPluginMetadataModel"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/fragments","value":[{"kind":"identifier","text":"SocialRadioPluginMetadataModel"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioPluginMetadataModel\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioPluginMetadataModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/title","value":"SocialRadioMixtapeTrackImage"},{"value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeTrackImage\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeTrackImage"}]},{"value":"SocialRadioMixtape","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/title","op":"replace"},{"op":"replace","value":[{"text":"SocialRadioMixtape","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtape\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtape"}]},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/title"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/fragments","op":"replace"},{"value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1ErrorCode\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/title","value":"SocialRadioMixtapeLite"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/fragments","value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}]},{"value":[{"text":"SocialRadioMixtapeLite","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioMixtapeLite\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/title","value":"SocialRadioUser"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/fragments","op":"replace","value":[{"text":"SocialRadioUser","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUser\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUser"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/title","op":"replace","value":"SocialRadioStatusVariable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/fragments","value":[{"kind":"identifier","text":"SocialRadioStatusVariable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioStatusVariable\/navigatorTitle","op":"replace","value":[{"text":"SocialRadioStatusVariable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/title","op":"replace","value":"SocialRadioTunedRestDelegate"},{"value":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioTunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioTunedRestDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIDelegate\/title","value":"SocialRadioUIDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioUIDelegate\/navigatorTitle","value":[{"text":"SocialRadioUIDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/title","value":"SocialRadioConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/fragments","value":[{"text":"SocialRadioConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadioLite~1documentation~1SocialRadioLite~1SocialRadioConfig\/navigatorTitle","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}