{"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loopPlayingTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"loopPlayingTrackWithCompletion:"}],"role":"symbol","modules":[{"name":"AutomixIQ"}],"title":"loopPlayingTrack(completion:)","externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(im)loopPlayingTrackWithCompletion:","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopPlayingTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"abstract":[{"text":"Makes AutomixIQ repeat the currently playing track.","type":"text"}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdk\/loopplayingtrack(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdk\/loopplayingtrack(completion:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"seeAlsoSections":[{"anchor":"Playback-Control","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/pause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleMute(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setMute(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/reorderTracks(newOrder:completion:)"],"generated":true,"title":"Playback Control"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loopPlayingTrack(completion:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/play(completion:)":{"url":"\/documentation\/automixiq\/automixsdk\/play(completion:)","kind":"symbol","title":"play(completion:)","abstract":[{"type":"text","text":"Starts playback if paused."},{"text":" ","type":"text"},{"type":"text","text":"Returns an error if the player is already playing."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playWithCompletion:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/play(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"play","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/toggleReplay(completion:)":{"type":"topic","abstract":[{"text":"If on, after a playlist is done it restarts. Otherwise, it pauses.","type":"text"},{"text":" ","type":"text"},{"text":"This defaults to false on initialisation and should be set to match the state of the consumer’s UI","type":"text"}],"title":"toggleReplay(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toggleReplay"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"deprecated":true,"kind":"symbol","url":"\/documentation\/automixiq\/automixsdk\/togglereplay(completion:)","navigatorTitle":[{"kind":"identifier","text":"toggleReplayWithCompletion:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleReplay(completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/skipToTrackAtIndex(_:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skipToTrackAtIndex"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"skipToTrackAtIndex:completion:"}],"abstract":[{"text":"Jumps playback to the beginning of the track at the desired index as soon as possible.","type":"text"}],"title":"skipToTrackAtIndex(_:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","type":"topic","url":"\/documentation\/automixiq\/automixsdk\/skiptotrackatindex(_:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/back(completion:)":{"title":"back(completion:)","url":"\/documentation\/automixiq\/automixsdk\/back(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"backWithCompletion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/back(completion:)","abstract":[{"text":"Moves the player to the beginning of the current track","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setAutomixPlaySpeed(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","abstract":[{"type":"text","text":"Sets AutomixIQ’s play speed to a given value between 0.5 and 2, where 0.5 is half speed and 2 is double speed."}],"url":"\/documentation\/automixiq\/automixsdk\/setautomixplayspeed(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAutomixPlaySpeed"},{"kind":"text","text":"(Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","type":"topic","title":"setAutomixPlaySpeed(_:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAutomixPlaySpeed:completion:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/previous(completion:)":{"title":"previous(completion:)","url":"\/documentation\/automixiq\/automixsdk\/previous(completion:)","role":"symbol","navigatorTitle":[{"text":"previousWithCompletion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"previous","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/previous(completion:)","abstract":[{"type":"text","text":"Moves the player to the beginning of the previous track"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/loopPlayingTrack(completion:)":{"type":"topic","abstract":[{"type":"text","text":"Makes AutomixIQ repeat the currently playing track."}],"title":"loopPlayingTrack(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loopPlayingTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdk\/loopplayingtrack(completion:)","navigatorTitle":[{"text":"loopPlayingTrackWithCompletion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loopPlayingTrack(completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/playTrackUntilEndThenPause(completion:)":{"title":"playTrackUntilEndThenPause(completion:)","url":"\/documentation\/automixiq\/automixsdk\/playtrackuntilendthenpause(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playTrackUntilEndThenPauseWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playTrackUntilEndThenPause"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","kind":"symbol","abstract":[{"text":"Makes AutomixIQ play a given track until the end and then pause.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is useful if you need to play any other content between tracks such as advertisements."},{"text":" ","type":"text"},{"type":"text","text":"Returns an error if you call this on the last track"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/addTracks(identifiers:metadata:index:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTracks","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"index"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"addTracksWithIdentifiers:metadata:index:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Adds additional tracks to the playlist in AutomixIQ at a given index."},{"type":"text","text":" "},{"type":"text","text":"Returns an erorr if the index is out of bounds."}],"title":"addTracks(identifiers:metadata:index:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","type":"topic","url":"\/documentation\/automixiq\/automixsdk\/addtracks(identifiers:metadata:index:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"kind":"symbol","type":"topic","title":"AutomixSDK","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDK","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdk","navigatorTitle":[{"kind":"identifier","text":"AutomixSDK"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/moveTrack(at:toIndex:completion:)":{"url":"\/documentation\/automixiq\/automixsdk\/movetrack(at:toindex:completion:)","navigatorTitle":[{"text":"moveTrackAt:toIndex:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Moves the track from one index to a different index."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/moveTrack(at:toIndex:completion:)","title":"moveTrack(at:toIndex:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveTrack"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"toIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/pause(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pauseWithCompletion:"}],"abstract":[{"type":"text","text":"Pauses playback if playing."},{"type":"text","text":" "},{"type":"text","text":"Returns an error if the player is already paused."}],"title":"pause(completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/pause(completion:)","type":"topic","url":"\/documentation\/automixiq\/automixsdk\/pause(completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadTracks","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifiers"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"playTrackIndex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"text":"seconds","kind":"externalParam"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"contextId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","navigatorTitle":[{"text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Loads a new playlist into AutomixIQ"},{"text":" ","type":"text"},{"type":"text","text":"Returns an error if the playlist is empty this opperation will fail and AutomixIQ will be turned off."},{"text":" ","type":"text"},{"type":"text","text":"This will stop playback of the currently playing playlist and start the newly loaded one."}],"title":"loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","type":"topic","url":"\/documentation\/automixiq\/automixsdk\/loadtracks(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","title":"AutomixIQ","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setMute(on:completion:)":{"type":"topic","abstract":[{"text":"Mutes AutomixIQ","type":"text"}],"title":"setMute(on:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMute"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdk\/setmute(on:completion:)","navigatorTitle":[{"kind":"identifier","text":"setMuteOn:completion:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setMute(on:completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setReplay(on:completion:)":{"type":"topic","abstract":[{"type":"text","text":"Tells AutomixIQ whether or not it should restart the playlist when reaching the end."},{"text":" ","type":"text"},{"type":"text","text":"If on then playback will restart at the beginning otherwise it pauses at the end."}],"title":"setReplay(on:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setReplay","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdk\/setreplay(on:completion:)","navigatorTitle":[{"kind":"identifier","text":"setReplayOn:completion:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setReplay(on:completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/next(completion:)":{"title":"next(completion:)","url":"\/documentation\/automixiq\/automixsdk\/next(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nextWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"next","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/next(completion:)","kind":"symbol","abstract":[{"type":"text","text":"Moves the player to the beginning of the next track"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/seekTo(seconds:completion:)":{"type":"topic","abstract":[{"text":"Jumps playback on the current track to the desired timestamp as soon as possible.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This will mix the track with itself so the seek is beat-matched and as seamless as possible, which means the landing position will be close but not exactly the fed timestamp."}],"title":"seekTo(seconds:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekTo"},{"text":"(","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdk\/seekto(seconds:completion:)","navigatorTitle":[{"kind":"identifier","text":"seekToSeconds:completion:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/seekTo(seconds:completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/addTrack(identifier:metadata:index:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","abstract":[{"type":"text","text":"Adds a single track to the AutomixIQ playlist at a given index."},{"text":" ","type":"text"},{"type":"text","text":"Returns an erorr if the index is out of bounds."}],"kind":"symbol","type":"topic","title":"addTrack(identifier:metadata:index:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/addtrack(identifier:metadata:index:completion:)","navigatorTitle":[{"kind":"identifier","text":"addTrackWithIdentifier:metadata:index:completion:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/removeTrack(at:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/removeTrack(at:completion:)","abstract":[{"text":"Removes a track at a given index in the AutomixIQ playlist.","type":"text"},{"type":"text","text":" "},{"text":"Returns an erorr if the index is out of bounds.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/removetrack(at:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"kind":"symbol","type":"topic","title":"removeTrack(at:completion:)","role":"symbol","navigatorTitle":[{"text":"removeTrackAt:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/stopLoopingPlayingTrack(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","abstract":[{"type":"text","text":"Makes AutomixIQ stop repeating the currently playing track."}],"url":"\/documentation\/automixiq\/automixsdk\/stoploopingplayingtrack(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLoopingPlayingTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"kind":"symbol","type":"topic","title":"stopLoopingPlayingTrack(completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopLoopingPlayingTrackWithCompletion:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setAutomixVolumeNormalised(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","abstract":[{"type":"text","text":"Sets AutomixIQ’s volume to a given value between 0 and 1. If muted, calling this will cause AutomixIQ to unmute."}],"url":"\/documentation\/automixiq\/automixsdk\/setautomixvolumenormalised(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setAutomixVolumeNormalised","kind":"identifier"},{"text":"(Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","type":"topic","title":"setAutomixVolumeNormalised(_:completion:)","role":"symbol","navigatorTitle":[{"text":"setAutomixVolumeNormalised:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/reorderTracks(newOrder:completion:)":{"title":"reorderTracks(newOrder:completion:)","url":"\/documentation\/automixiq\/automixsdk\/reordertracks(neworder:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reorderTracksWithNewOrder:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reorderTracks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"newOrder","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/reorderTracks(newOrder:completion:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Sets a new order to the playlist while continuing to play the current track"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/toggleMute(completion:)":{"url":"\/documentation\/automixiq\/automixsdk\/togglemute(completion:)","kind":"symbol","title":"toggleMute(completion:)","abstract":[{"type":"text","text":"Toggles the AutomixIQ SDK mute"}],"role":"symbol","type":"topic","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"toggleMuteWithCompletion:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleMute(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toggleMute","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"loopPlayingTrackWithCompletion:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loopPlayingTrackWithCompletion:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Playback Control","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/pause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleMute(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setMute(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/reorderTracks(newOrder:completion:)"],"anchor":"Playback-Control"}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"loopPlayingTrackWithCompletion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1play(completion:)\/title","value":"playWithCompletion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1play(completion:)\/fragments","op":"replace"},{"value":"toggleReplayWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleReplay(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleReplay(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toggleReplayWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1skipToTrackAtIndex(_:completion:)\/title","op":"replace","value":"skipToTrackAtIndex:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1skipToTrackAtIndex(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"skipToTrackAtIndex:completion:","kind":"identifier"}]},{"op":"replace","value":"backWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1back(completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"backWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1back(completion:)\/fragments"},{"op":"replace","value":"setAutomixPlaySpeed:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixPlaySpeed(_:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setAutomixPlaySpeed:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixPlaySpeed(_:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1previous(completion:)\/title","value":"previousWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1previous(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"previousWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loopPlayingTrack(completion:)\/title","value":"loopPlayingTrackWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loopPlayingTrack(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loopPlayingTrackWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1playTrackUntilEndThenPause(completion:)\/title","value":"playTrackUntilEndThenPauseWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1playTrackUntilEndThenPause(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playTrackUntilEndThenPauseWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTracks(identifiers:metadata:index:completion:)\/title","op":"replace","value":"addTracksWithIdentifiers:metadata:index:completion:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTracksWithIdentifiers:metadata:index:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTracks(identifiers:metadata:index:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title","value":"AutomixSDK","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments","value":[{"kind":"identifier","text":"AutomixSDK"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/navigatorTitle","value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace"},{"value":"moveTrackAt:toIndex:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1moveTrack(at:toIndex:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1moveTrack(at:toIndex:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"moveTrackAt:toIndex:completion:"}],"op":"replace"},{"value":"pauseWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1pause(completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1pause(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pauseWithCompletion:","kind":"identifier"}]},{"op":"replace","value":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setMute(on:completion:)\/title","value":"setMuteOn:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setMute(on:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setMuteOn:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setReplay(on:completion:)\/title","op":"replace","value":"setReplayOn:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"setReplayOn:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setReplay(on:completion:)\/fragments"},{"value":"nextWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1next(completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nextWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1next(completion:)\/fragments"},{"value":"seekToSeconds:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1seekTo(seconds:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"seekToSeconds:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1seekTo(seconds:completion:)\/fragments"},{"value":"addTrackWithIdentifier:metadata:index:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTrack(identifier:metadata:index:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTrack(identifier:metadata:index:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addTrackWithIdentifier:metadata:index:completion:"}]},{"value":"removeTrackAt:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1removeTrack(at:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeTrackAt:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1removeTrack(at:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1stopLoopingPlayingTrack(completion:)\/title","value":"stopLoopingPlayingTrackWithCompletion:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopLoopingPlayingTrackWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1stopLoopingPlayingTrack(completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixVolumeNormalised(_:completion:)\/title","op":"replace","value":"setAutomixVolumeNormalised:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixVolumeNormalised(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setAutomixVolumeNormalised:completion:","kind":"identifier"}],"op":"replace"},{"value":"reorderTracksWithNewOrder:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1reorderTracks(newOrder:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1reorderTracks(newOrder:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"reorderTracksWithNewOrder:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleMute(completion:)\/title","value":"toggleMuteWithCompletion:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"toggleMuteWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleMute(completion:)\/fragments","op":"replace"}]}]}