{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cancelled","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCancelled"}],"externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeCancelled","title":"ErrorCode.cancelled","modules":[{"name":"SocialRadio"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"variants":[{"paths":["\/documentation\/socialradio\/errorcode\/cancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/errorcode\/cancelled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/cancelled":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/cancelled","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeCancelled","kind":"identifier"}],"url":"\/documentation\/socialradio\/errorcode\/cancelled","title":"ErrorCode.cancelled","kind":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"title":"SocialRadio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","type":"topic","url":"\/documentation\/socialradio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"kind":"symbol","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"title":"ErrorCode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/errorcode"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ErrorCodeCancelled","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ErrorCodeCancelled"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ErrorCodeCancelled"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ErrorCodeCancelled","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cancelled\/title"},{"value":[{"kind":"identifier","text":"ErrorCodeCancelled"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1cancelled\/fragments"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}