{"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncCheckDeviceStatus(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncLogPlayEvent(trackId:seconds:guid:logPlayType:source:sourceId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/cacheMetadata(_:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/canPlayAds(metadata:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/getDeviceIdentifier()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/isLoggedIn()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)"],"title":"Instance Methods","generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"variants":[{"paths":["\/documentation\/automixiq\/automixiqstreamingdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqstreamingdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"AutomixIQ"}],"roleHeading":"Protocol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"title":"AutomixIQStreamingDelegate","symbolKind":"protocol","externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQStreamingDelegate","navigatorTitle":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate"},"seeAlsoSections":[{"anchor":"Initializing-AutomixIQ-for-use-with-a-custom-backend","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedLogLevel"],"title":"Initializing AutomixIQ for use with a custom backend","generated":true}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQStreamingDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-with-custom-backend-article":{"title":"Initializing AutomixIQ with a custom backend","url":"\/documentation\/automixiq\/initialising-automixiq-with-custom-backend-article","role":"article","type":"topic","abstract":[{"type":"text","text":"How to validate your client and start using the AutomixIQ SDK with a custom backend"}],"kind":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/getDeviceIdentifier()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getDeviceIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","required":true,"url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/getdeviceidentifier()","title":"getDeviceIdentifier()","role":"symbol","navigatorTitle":[{"text":"getDeviceIdentifier","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/getDeviceIdentifier()","abstract":[{"text":"Called by Automix to learn the identity of the device requesting to stream audio, for those services that require it.","type":"text"},{"text":" ","type":"text"},{"text":"An example would be, a service that only allows one device to stream at any one time, would need to know the identity of the device to provide the stream.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/syncGetTrackMetadata(trackId:)":{"abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}],"type":"topic","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetTrackMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","kind":"typeIdentifier","text":"TunedTrackModel"},{"kind":"text","text":"?"}],"url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/syncgettrackmetadata(trackid:)","title":"syncGetTrackMetadata(trackId:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","navigatorTitle":[{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/trackDownloadCompleted(trackId:data:)":{"kind":"symbol","title":"trackDownloadCompleted(trackId:data:)","url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/trackdownloadcompleted(trackid:data:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadCompleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/trackDownloadCompleted(trackId:data:)","navigatorTitle":[{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)":{"title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetStream"},{"kind":"text","text":"("},{"kind":"externalParam","text":"streamingDeviceId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newSessionId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}],"required":true,"url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)","abstract":[{"type":"text","text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedLogLevel":{"title":"TunedLogLevel","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedLogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"TunedLogLevel"}],"url":"\/documentation\/automixiq\/tunedloglevel","abstract":[{"type":"text","text":"TunedLogLevel is an enum of all the AutomixIQ available log levels"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedLogLevel"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/isLoggedIn()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoggedIn"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/isLoggedIn()","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isLoggedIn"}],"url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/isloggedin()","kind":"symbol","title":"isLoggedIn()","abstract":[{"type":"text","text":"Called by AutomixIQ to learn if it is allowed to stream content that is protected by some form of authentication."},{"type":"text","text":" "},{"type":"text","text":"An example is, an implementation via an API behind OAuth would return true if access and refresh tokens are available, false otherwise"}],"required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/asyncCheckDeviceStatus(completion:)":{"title":"asyncCheckDeviceStatus(completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncCheckDeviceStatus(completion:)","type":"topic","abstract":[{"type":"text","text":"Called by AutomixIQ regularly while something is being played, this can be used if you have restrictions on the number of devices that can play simultaneously"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncCheckDeviceStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"canContinuePlaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"asyncCheckDeviceStatusWithCompletion:"}],"kind":"symbol","required":true,"url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/asynccheckdevicestatus(completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/asyncGetTrackMetadata(trackId:completion:)":{"title":"asyncGetTrackMetadata(trackId:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","type":"topic","abstract":[{"type":"text","text":"Called by AutomixIQ when it requires the metadata of a track in order to load it."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncGetTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"track","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TunedTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetTrackMetadataWithTrackId:completion:"}],"kind":"symbol","required":true,"url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/asyncgettrackmetadata(trackid:completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/trackDownloadProgressChanged(trackId:progress:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"title":"trackDownloadProgressChanged(trackId:progress:)","url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/trackdownloadprogresschanged(trackid:progress:)","required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/canPlayAds(metadata:completion:)":{"kind":"symbol","title":"canPlayAds(metadata:completion:)","url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/canplayads(metadata:completion:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlayAds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedAdModel","text":"TunedAdModel","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"canPlay","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"AutomixIQ calls this function to provide a chance to cache Ads and inform it if it can actually play them."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/canPlayAds(metadata:completion:)","navigatorTitle":[{"text":"canPlayAdsWithMetadata:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/logAutomixIQMessage(logLevel:message:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/logAutomixIQMessage(logLevel:message:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/logautomixiqmessage(loglevel:message:)","kind":"symbol","title":"logAutomixIQMessage(logLevel:message:)","abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logAutomixIQMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@E@TunedLogLevel","kind":"typeIdentifier","text":"TunedLogLevel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/syncGetCachedTrack(trackId:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","kind":"symbol","type":"topic","role":"symbol","title":"syncGetCachedTrack(trackId:)","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/syncgetcachedtrack(trackid:)","navigatorTitle":[{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetCachedTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/asyncLogPlayEvent(trackId:seconds:guid:logPlayType:source:sourceId:completion:)":{"navigatorTitle":[{"text":"asyncLogPlayEventWithTrackId:seconds:guid:logPlayType:source:sourceId:completion:","kind":"identifier"}],"title":"asyncLogPlayEvent(trackId:seconds:guid:logPlayType:source:sourceId:completion:)","url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/asynclogplayevent(trackid:seconds:guid:logplaytype:source:sourceid:completion:)","role":"symbol","type":"topic","abstract":[{"text":"Called by AutomixIQ when playback of a track has fulfilled the requirements to report a playback event.","type":"text"}],"kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncLogPlayEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"guid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"logPlayType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"sourceId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"success","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncLogPlayEvent(trackId:seconds:guid:logPlayType:source:sourceId:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate/cacheMetadata(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheMetadata"},{"kind":"text","text":"(["},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedTrackModel","kind":"typeIdentifier","text":"TunedTrackModel"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/cacheMetadata(_:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cacheMetadata:"}],"url":"\/documentation\/automixiq\/automixiqstreamingdelegate\/cachemetadata(_:)","kind":"symbol","title":"cacheMetadata(_:)","abstract":[{"type":"text","text":"AutomixIQ calls this function to provide a chance to cache metadata to shortcut future requests."}],"required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQStreamingDelegate":{"title":"AutomixIQStreamingDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate","type":"topic","abstract":[{"text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"kind":"symbol","role":"symbol","url":"\/documentation\/automixiq\/automixiqstreamingdelegate"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AutomixIQStreamingDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncCheckDeviceStatus(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/asyncLogPlayEvent(trackId:seconds:guid:logPlayType:source:sourceId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/cacheMetadata(_:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/canPlayAds(metadata:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/getDeviceIdentifier()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/isLoggedIn()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/syncGetCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/syncGetTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"generated":true,"anchor":"Initializing-AutomixIQ-for-use-with-a-custom-backend","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedLogLevel"],"title":"Initializing AutomixIQ for use with a custom backend"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"getDeviceIdentifier","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getDeviceIdentifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1getDeviceIdentifier()\/fragments","op":"replace"},{"value":"syncGetTrackMetadataWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1syncGetTrackMetadata(trackId:)\/fragments","op":"replace"},{"value":"trackDownloadCompletedWithTrackId:data:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/fragments","op":"replace"},{"value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/fragments","op":"replace"},{"value":"TunedLogLevel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedLogLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TunedLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedLogLevel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TunedLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedLogLevel\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1isLoggedIn()\/title","value":"isLoggedIn"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1isLoggedIn()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isLoggedIn","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/title","value":"asyncCheckDeviceStatusWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asyncCheckDeviceStatusWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/title","value":"asyncGetTrackMetadataWithTrackId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asyncGetTrackMetadataWithTrackId:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title","value":"trackDownloadProgressChangedWithTrackId:progress:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1canPlayAds(metadata:completion:)\/title","value":"canPlayAdsWithMetadata:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1canPlayAds(metadata:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPlayAdsWithMetadata:completion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1logAutomixIQMessage(logLevel:message:)\/title","value":"logAutomixIQMessageWithLogLevel:message:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}]},{"value":"syncGetCachedTrackWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1syncGetCachedTrack(trackId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncLogPlayEvent(trackId:seconds:guid:logPlayType:source:sourceId:completion:)\/title","value":"asyncLogPlayEventWithTrackId:seconds:guid:logPlayType:source:sourceId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1asyncLogPlayEvent(trackId:seconds:guid:logPlayType:source:sourceId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asyncLogPlayEventWithTrackId:seconds:guid:logPlayType:source:sourceId:completion:","kind":"identifier"}]},{"value":"cacheMetadata:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1cacheMetadata(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"cacheMetadata:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate~1cacheMetadata(_:)\/fragments","op":"replace"},{"value":"AutomixIQStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQStreamingDelegate\/navigatorTitle","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}