{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelDebug"}],"externalID":"c:@M@SocialRadio@E@TunedLogLevel@TunedLogLevelLogLevelDebug","symbolKind":"case","roleHeading":"Case","modules":[{"name":"SocialRadio"}],"navigatorTitle":[{"text":"TunedLogLevelLogLevelDebug","kind":"identifier"}],"title":"TunedLogLevel.logLevelDebug","role":"symbol"},"variants":[{"paths":["\/documentation\/socialradio\/tunedloglevel\/logleveldebug"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/tunedloglevel\/logleveldebug"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel\/logLevelDebug"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelDebug","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel/logLevelDebug":{"title":"TunedLogLevel.logLevelDebug","role":"symbol","url":"\/documentation\/socialradio\/tunedloglevel\/logleveldebug","navigatorTitle":[{"text":"TunedLogLevelLogLevelDebug","kind":"identifier"}],"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelDebug","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel\/logLevelDebug","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","title":"SocialRadio","type":"topic","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedLogLevel":{"kind":"symbol","url":"\/documentation\/socialradio\/tunedloglevel","navigatorTitle":[{"kind":"identifier","text":"TunedLogLevel"}],"role":"symbol","title":"TunedLogLevel","abstract":[{"type":"text","text":"TunedLogLevel is an enum of all the AutomixIQ available log levels"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedLogLevel"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedLogLevel","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"TunedLogLevelLogLevelDebug","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"TunedLogLevelLogLevelDebug"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"TunedLogLevelLogLevelDebug"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TunedLogLevelLogLevelDebug","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel~1logLevelDebug\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel~1logLevelDebug\/fragments","value":[{"text":"TunedLogLevelLogLevelDebug","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/title","value":"TunedLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/fragments","value":[{"text":"TunedLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedLogLevel\/navigatorTitle","value":[{"text":"TunedLogLevel","kind":"identifier"}]}]}]}