{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate\/getTrackMetadata(trackId:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"text":"?","kind":"text"}],"role":"symbol","required":true,"symbolKind":"method","externalID":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate(im)getTrackMetadataWithTrackId:","title":"getTrackMetadata(trackId:)","modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"getTrackMetadataWithTrackId:","kind":"identifier"}]},"abstract":[{"text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/automixiq\/tunedmusiccachedelegate\/gettrackmetadata(trackid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/tunedmusiccachedelegate\/gettrackmetadata(trackid:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"AutomixSDKTrackModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ  is streaming."}],"type":"paragraph"}],"name":"trackId"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The metadata of the track, nil if not available.","type":"text"}]}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedMusicCacheDelegate":{"type":"topic","role":"symbol","url":"\/documentation\/automixiq\/tunedmusiccachedelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"kind":"symbol","title":"TunedMusicCacheDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel":{"url":"\/documentation\/automixiq\/automixsdktrackmodel","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"title":"AutomixSDKTrackModel","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","title":"AutomixIQ","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedMusicCacheDelegate/getTrackMetadata(trackId:)":{"type":"topic","abstract":[{"text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available.","type":"text"}],"url":"\/documentation\/automixiq\/tunedmusiccachedelegate\/gettrackmetadata(trackid:)","required":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate\/getTrackMetadata(trackId:)","kind":"symbol","title":"getTrackMetadata(trackId:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTrackMetadata","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"getTrackMetadataWithTrackId:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getTrackMetadataWithTrackId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getTrackMetadataWithTrackId:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"AutomixSDKTrackModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"getTrackMetadataWithTrackId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"trackId"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ  is streaming."}],"type":"paragraph"}],"name":"trackId"}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The metadata of the track, nil if not available.","type":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate"},{"value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/fragments"},{"value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/navigatorTitle"},{"value":"AutomixSDKTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/fragments","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate~1getTrackMetadata(trackId:)\/title","value":"getTrackMetadataWithTrackId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate~1getTrackMetadata(trackId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getTrackMetadataWithTrackId:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}