{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/canOnOff"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canOnOff"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatus\/canonoff"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkstatus\/canonoff"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus"]]},"abstract":[{"text":"Represents if the SDK can be turned On or off. It is true if not other On \/ Off action is ongoing, flase otherwise. When this switch is true, On \/Off actions return an error.","type":"text"}],"metadata":{"role":"symbol","externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus(py)canOnOff","symbolKind":"property","title":"canOnOff","navigatorTitle":[{"text":"canOnOff","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"canOnOff","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus/canOnOff":{"title":"canOnOff","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/canOnOff","type":"topic","role":"symbol","abstract":[{"text":"Represents if the SDK can be turned On or off. It is true if not other On \/ Off action is ongoing, flase otherwise. When this switch is true, On \/Off actions return an error.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdkstatus\/canonoff","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"canOnOff"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canOnOff"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","title":"AutomixIQ","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"title":"AutomixSDKStatus","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"canOnOff","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"canOnOff","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"canOnOff"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"canOnOff","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1canOnOff\/title","op":"replace"},{"value":[{"text":"canOnOff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1canOnOff\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title","op":"replace","value":"AutomixSDKStatus"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatus"}]}]}]}