{"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatus\/playlistdiff"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkstatus\/playlistdiff"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : [","kind":"text"},{"text":"AutomixSDKPlaylistOperation","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKPlaylistOperation"},{"text":"]]?","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/playlistDiff"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus(py)playlistDiff","navigatorTitle":[{"text":"playlistDiff","kind":"identifier"}],"symbolKind":"property","title":"playlistDiff","role":"symbol","modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : [","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKPlaylistOperation","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKPlaylistOperation"},{"text":"]]?","kind":"text"}]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"title":"AutomixSDKStatus","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus/playlistDiff":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/playlistDiff","title":"playlistDiff","kind":"symbol","navigatorTitle":[{"text":"playlistDiff","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playlistDiff","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : [","kind":"text"},{"text":"AutomixSDKPlaylistOperation","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKPlaylistOperation","kind":"typeIdentifier"},{"kind":"text","text":"]]?"}],"type":"topic","abstract":[],"url":"\/documentation\/automixiq\/automixsdkstatus\/playlistdiff","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperation":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"abstract":[{"text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdkplaylistoperation","title":"AutomixSDKPlaylistOperation","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","title":"AutomixIQ","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"playlistDiff","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"playlistDiff","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSArray<AutomixSDKPlaylistOperation *> *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"playlistDiff","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"AutomixSDKStatus","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"op":"replace"},{"value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/navigatorTitle"},{"op":"replace","value":"playlistDiff","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1playlistDiff\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1playlistDiff\/fragments","value":[{"kind":"identifier","text":"playlistDiff"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}]}]}]}