{"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logAutomixIQMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"logLevel"},{"text":": ","kind":"text"},{"text":"AutomixIQLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQLogLevel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"logLevel","content":[{"type":"paragraph","inlineContent":[{"text":"The log level.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message it wishes to log."}]}],"name":"message"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate(im)logAutomixIQMessageWithLogLevel:message:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"logAutomixIQMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"logLevel","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixIQLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQLogLevel"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"logAutomixIQMessage(logLevel:message:)","roleHeading":"Instance Method"},"sections":[],"variants":[{"paths":["\/documentation\/automixiq\/automixiqtunedrestdelegate\/logautomixiqmessage(loglevel:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixiqtunedrestdelegate\/logautomixiqmessage(loglevel:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)"},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQLogLevel":{"url":"\/documentation\/automixiq\/automixiqloglevel","navigatorTitle":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel","title":"AutomixIQLogLevel","abstract":[{"text":"AutomixIQLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixIQLogLevel"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate/logAutomixIQMessage(logLevel:message:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","abstract":[{"text":"Called by AutomixIQ when it wishes to output a log message","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutomixIQLogLevel","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQLogLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/automixiq\/automixiqtunedrestdelegate\/logautomixiqmessage(loglevel:message:)","title":"logAutomixIQMessage(logLevel:message:)","navigatorTitle":[{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate":{"type":"topic","title":"AutomixIQTunedRestDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqtunedrestdelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"logAutomixIQMessageWithLogLevel:message:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixIQLogLevel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQLogLevel"},{"text":") ","kind":"text"},{"text":"logLevel","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The log level."}],"type":"paragraph"}],"name":"logLevel"},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"text":"The message it wishes to log.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/title","value":"AutomixIQLogLevel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/fragments","value":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"AutomixIQLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQLogLevel\/navigatorTitle"},{"value":"logAutomixIQMessageWithLogLevel:message:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments"},{"value":"AutomixIQTunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}]},{"value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}