{"metadata":{"modules":[{"name":"AutomixIQ"}],"role":"symbol","title":"uniqueDeviceIdentifier()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueDeviceIdentifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"uniqueDeviceIdentifier","kind":"identifier"}],"symbolKind":"method","required":true,"externalID":"c:@M@AutomixIQ@objc(pl)AutomixIQTunedRestDelegate(im)uniqueDeviceIdentifier"},"variants":[{"paths":["\/documentation\/automixiq\/automixiqtunedrestdelegate\/uniquedeviceidentifier()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixiqtunedrestdelegate\/uniquedeviceidentifier()"]}],"abstract":[{"type":"text","text":"Called by AutomixIQ to request the unique identifier for the users device as a string."},{"type":"text","text":" "},{"text":"On iOS this is generally the Identifier for Vendor.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It can be any string as long as it is unique"},{"type":"text","text":" "},{"text":"AutomixIQ will use this string as the UniqueId if it needs to register the device for playback","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"uniqueDeviceIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"The unique device identifier as string","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/uniqueDeviceIdentifier()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"role":"collection","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate":{"type":"topic","title":"AutomixIQTunedRestDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixiqtunedrestdelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"abstract":[{"type":"text","text":"AutomixIQTunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQTunedRestDelegate/uniqueDeviceIdentifier()":{"url":"\/documentation\/automixiq\/automixiqtunedrestdelegate\/uniquedeviceidentifier()","title":"uniqueDeviceIdentifier()","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQTunedRestDelegate\/uniqueDeviceIdentifier()","required":true,"abstract":[{"type":"text","text":"Called by AutomixIQ to request the unique identifier for the users device as a string."},{"text":" ","type":"text"},{"type":"text","text":"On iOS this is generally the Identifier for Vendor."},{"text":" ","type":"text"},{"text":"It can be any string as long as it is unique","type":"text"},{"type":"text","text":" "},{"type":"text","text":"AutomixIQ will use this string as the UniqueId if it needs to register the device for playback"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uniqueDeviceIdentifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","navigatorTitle":[{"text":"uniqueDeviceIdentifier","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"uniqueDeviceIdentifier","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"uniqueDeviceIdentifier","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"uniqueDeviceIdentifier","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The unique device identifier as string","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/1"},{"value":"AutomixIQTunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixIQTunedRestDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixIQTunedRestDelegate","kind":"identifier"}]},{"op":"replace","value":"uniqueDeviceIdentifier","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1uniqueDeviceIdentifier()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"uniqueDeviceIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQTunedRestDelegate~1uniqueDeviceIdentifier()\/fragments"}]}]}