{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialize(with:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","kind":"typeIdentifier","text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStreamingDelegate"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","kind":"typeIdentifier","text":"AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStreamingDelegate"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","kind":"typeIdentifier","text":"SocialRadioStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate"},{"kind":"text","text":", "},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"socialBackendDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialBackendDelegate","text":"SocialBackendDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"languages":["swift"]},{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","text":"SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStreamingDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate","text":"AutomixIQStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStreamingDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate","text":"SocialRadioStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialBackendDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialBackendDelegate","text":"SocialBackendDelegate"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradioobjc\/initialize(with:automixiqstreamingdelegate:socialradiostreamingdelegate:socialradiostatusdelegate:socialradiouidelegate:socialbackenddelegate:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC"]]},"sections":[],"metadata":{"roleHeading":"Type Method","externalID":"c:objc(cs)SocialRadioObjC(cm)initializeWithConfig:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:","modules":[{"name":"SocialRadio"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStreamingDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"AutomixIQStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStreamingDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"SocialRadioStreamingDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialBackendDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"SocialBackendDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialBackendDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"initialize(with:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)","symbolKind":"method"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC/initialize(with:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)":{"abstract":[],"url":"\/documentation\/socialradio\/socialradioobjc\/initialize(with:automixiqstreamingdelegate:socialradiostreamingdelegate:socialradiostatusdelegate:socialradiouidelegate:socialbackenddelegate:completion:)","role":"symbol","title":"initialize(with:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","text":"SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"automixIQStreamingDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)AutomixIQStreamingDelegate","text":"AutomixIQStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStreamingDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStreamingDelegate","text":"SocialRadioStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialBackendDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialBackendDelegate","text":"SocialBackendDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialize(with:automixIQStreamingDelegate:socialRadioStreamingDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:socialBackendDelegate:completion:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStreamingDelegate":{"title":"SocialRadioStreamingDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"SocialRadioStreamingDelegate protocol defines the methods to be implemented with providing SocialRadio the information it requires to display content and get recommendations."}],"url":"\/documentation\/socialradio\/socialradiostreamingdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStreamingDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC":{"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioObjC"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioObjC"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradioobjc","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC","title":"SocialRadioObjC","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQStreamingDelegate":{"kind":"symbol","type":"topic","title":"AutomixIQStreamingDelegate","url":"\/documentation\/socialradio\/automixiqstreamingdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQStreamingDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"navigatorTitle":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"title":"SocialRadioStatusObserverDelegate","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"kind":"symbol","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"url":"\/documentation\/socialradio\/socialradiouidelegate","title":"SocialRadioUIDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioConfig"}],"url":"\/documentation\/socialradio\/socialradioconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioConfig"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","abstract":[],"title":"SocialRadioConfig","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialBackendDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialBackendDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialBackendDelegate","role":"symbol","title":"SocialBackendDelegate","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/socialbackenddelegate","navigatorTitle":[{"kind":"identifier","text":"SocialBackendDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/title","value":"SocialRadioStreamingDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStreamingDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioStreamingDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/title","value":"AutomixIQStreamingDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixIQStreamingDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQStreamingDelegate\/navigatorTitle","value":[{"text":"AutomixIQStreamingDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","value":"SocialRadioStatusObserverDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","value":"SocialRadioUIDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","value":"SocialRadioConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","value":[{"text":"SocialRadioConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/title","value":"SocialBackendDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/fragments","value":[{"text":"SocialBackendDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialBackendDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialBackendDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}