{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","text":"SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","text":"TunedRestDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","text":"SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"platforms":["iOS"],"languages":["swift"]},{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","kind":"typeIdentifier","text":"SocialRadioConfig","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier","text":"TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","kind":"typeIdentifier","text":"SocialRadioStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","kind":"typeIdentifier","text":"SocialRadioUIDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradioobjc\/initialize(with:tunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"title":"initialize(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"SocialRadio"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","text":"SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"externalID":"c:objc(cs)SocialRadioObjC(cm)initializeWithConfig:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialize(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC/initialize(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)":{"type":"topic","title":"initialize(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","role":"symbol","abstract":[],"url":"\/documentation\/socialradio\/socialradioobjc\/initialize(with:tunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SocialRadioConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig"},{"text":", ","kind":"text"},{"text":"tunedRestDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"socialRadioStatusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialize(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioConfig"}],"url":"\/documentation\/socialradio\/socialradioconfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioConfig"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","abstract":[],"title":"SocialRadioConfig","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"title":"SocialRadioStatusObserverDelegate","role":"symbol","navigatorTitle":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","role":"symbol","title":"TunedRestDelegate","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/tunedrestdelegate","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"kind":"symbol","navigatorTitle":[{"text":"SocialRadioUIDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioUIDelegate","kind":"identifier"}],"abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"url":"\/documentation\/socialradio\/socialradiouidelegate","title":"SocialRadioUIDelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC":{"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioObjC"}],"navigatorTitle":[{"kind":"identifier","text":"SocialRadioObjC"}],"role":"symbol","url":"\/documentation\/socialradio\/socialradioobjc","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC","title":"SocialRadioObjC","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","kind":"symbol","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"url":"\/documentation\/socialradio","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"}},"variantOverrides":[{"patch":[{"value":"SocialRadioConfig","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments"},{"op":"replace","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle"},{"op":"replace","value":"SocialRadioStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title"},{"op":"replace","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments"},{"op":"replace","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle"},{"op":"replace","value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title"},{"op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments"},{"op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle"},{"op":"replace","value":"SocialRadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}