{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLoopingNoLoopingTrack","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/stopLoopingNoLoopingTrack","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"ErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}],"externalID":"c:@M@SocialRadio@E@ErrorCode@ErrorCodeStopLoopingNoLoopingTrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLoopingNoLoopingTrack"}],"roleHeading":"Case","modules":[{"name":"SocialRadio"}],"title":"ErrorCode.stopLoopingNoLoopingTrack","symbolKind":"case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/errorcode\/stoploopingnoloopingtrack"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/errorcode\/stoploopingnoloopingtrack"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode":{"title":"ErrorCode","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/socialradio\/errorcode"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"role":"collection","title":"SocialRadio","url":"\/documentation\/socialradio","type":"topic","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/ErrorCode/stopLoopingNoLoopingTrack":{"navigatorTitle":[{"text":"ErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"stopLoopingNoLoopingTrack","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/ErrorCode\/stopLoopingNoLoopingTrack","type":"topic","title":"ErrorCode.stopLoopingNoLoopingTrack","kind":"symbol","url":"\/documentation\/socialradio\/errorcode\/stoploopingnoloopingtrack","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodeStopLoopingNoLoopingTrack"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodeStopLoopingNoLoopingTrack"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/title","value":"ErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode\/navigatorTitle","value":[{"text":"ErrorCode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1stopLoopingNoLoopingTrack\/title","value":"ErrorCodeStopLoopingNoLoopingTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1ErrorCode~1stopLoopingNoLoopingTrack\/fragments","value":[{"text":"ErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}