{"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/addAds(metadata:afterTrackIdentifier:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","text":"TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"afterTrackIdentifier","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?), ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The metadata of the Ads."}]}],"name":"metadata"},{"name":"afterTrackIdentifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the track thatshould have an ad after, nil if it should be added after the currently playing track"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}],"type":"paragraph"}]}]}]}],"kind":"parameters"}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"SocialRadio"}],"externalID":"c:@M@SocialRadio@objc(cs)AutomixIQ(im)addAdsWithMetadata:afterTrackIdentifier:completion:","title":"addAds(metadata:afterTrackIdentifier:completion:)","symbolKind":"method","navigatorTitle":[{"text":"addAdsWithMetadata:afterTrackIdentifier:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addAds"},{"kind":"text","text":"("},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"afterTrackIdentifier"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?), "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/socialradio\/automixiq\/addads(metadata:aftertrackidentifier:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/automixiq\/addads(metadata:aftertrackidentifier:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Ads Ad(s) right after the currently playing index.","type":"text"}],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ/addAds(metadata:afterTrackIdentifier:completion:)":{"type":"topic","title":"addAds(metadata:afterTrackIdentifier:completion:)","navigatorTitle":[{"text":"addAdsWithMetadata:afterTrackIdentifier:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ\/addAds(metadata:afterTrackIdentifier:completion:)","abstract":[{"type":"text","text":"Ads Ad(s) right after the currently playing index."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addAds","kind":"identifier"},{"text":"(","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"TunedAdModel","preciseIdentifier":"c:@M@SocialRadio@objc(cs)TunedAdModel","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"afterTrackIdentifier"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?), "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","url":"\/documentation\/socialradio\/automixiq\/addads(metadata:aftertrackidentifier:completion:)"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","title":"SocialRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or voice to the world."}],"type":"topic","role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedAdModel":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedAdModel","url":"\/documentation\/socialradio\/tunedadmodel","title":"TunedAdModel","kind":"symbol","abstract":[{"text":"TunedAdModel models a Ad.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TunedAdModel"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAdModel","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixIQ":{"type":"topic","title":"AutomixIQ","navigatorTitle":[{"kind":"identifier","text":"AutomixIQ"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixIQ","abstract":[{"type":"text","text":"AutomixIQ represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQ"}],"role":"symbol","url":"\/documentation\/socialradio\/automixiq"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"addAdsWithMetadata:afterTrackIdentifier:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addAdsWithMetadata:afterTrackIdentifier:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addAdsWithMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<TunedAdModel *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"afterTrackIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"afterTrackIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The metadata of the Ads.","type":"text"}],"type":"paragraph"}],"name":"metadata"},{"name":"afterTrackIdentifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the track thatshould have an ad after, nil if it should be added after the currently playing track"}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameter error: An error describing a problem that occurred, nil otherwise.","type":"text"}]}]}]}]}]},"op":"replace"},{"value":"addAdsWithMetadata:afterTrackIdentifier:completion:","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1addAds(metadata:afterTrackIdentifier:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addAdsWithMetadata:afterTrackIdentifier:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ~1addAds(metadata:afterTrackIdentifier:completion:)\/fragments","op":"replace"},{"value":"TunedAdModel","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/title","op":"replace"},{"value":[{"text":"TunedAdModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/fragments","op":"replace"},{"value":[{"text":"TunedAdModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedAdModel\/navigatorTitle","op":"replace"},{"value":"AutomixIQ","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/title","op":"replace"},{"value":[{"text":"AutomixIQ","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/fragments","op":"replace"},{"value":[{"text":"AutomixIQ","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixIQ\/navigatorTitle","op":"replace"}]}]}