{"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/SQ","doc:\/\/org.cocoapods.SocialRadio\/SH","doc:\/\/org.cocoapods.SocialRadio\/SY"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"seeAlsoSections":[{"generated":true,"title":"Errors","anchor":"Errors","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Errors-article","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/sdkError(code:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"identifier"}]}]},{"kind":"parameters","parameters":[{"name":"notMainThread","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to use the SDK from any thread not main","type":"text"}]}]},{"name":"sdkNotInitialised","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to use the SDK prior to initialising it"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to use playback controls when AutomixIQ is not on"}],"type":"paragraph"}],"name":"sdkNotOn"},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn on AutomixIQ but it is already on"}],"type":"paragraph"}],"name":"sdkAlreadyOn"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to load an empty playlist","type":"text"}]}],"name":"loadTracksEmptyPlaylist"},{"content":[{"inlineContent":[{"type":"text","text":""}],"type":"paragraph"}],"name":"loadTracksOutOfBounds"},{"name":"addTrackPlaylistDoesNotExist","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Thrown when you attempt to insert a track at a position outside the bounds of the loaded playlist","type":"text"}],"type":"paragraph"}],"name":"addTrackOutOfBounds"},{"name":"addTrackNoMetadata","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when the metadata for a track you are trying to load is not available and could not be downloaded","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails internally (not user error)"}]}],"name":"addTrackInternalError"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to remove a track at a position outside the bounds of the loaded playlist"}]}],"name":"removeTrackOutOfBounds"},{"name":"playAlreadyPlaying","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to play but AutomixIQ is already playing"}]}]},{"name":"pauseAlreadyPaused","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to pause but AutomixIQ is already paused","type":"text"}]}]},{"name":"previousNoTrackAvailable","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to go to the previous track but AutomixIQ is already on the first in the playlist and “Repeat” is off"}],"type":"paragraph"}]},{"name":"nextNoTrackAvailable","content":[{"inlineContent":[{"text":"Thrown when you attempt to go to the next track but AutomixIQ is already on the last in the playlist and “Repeat” is off","type":"text"}],"type":"paragraph"}]},{"name":"backNoTrackAvailable","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to go to the start of a track but the playlist is empty"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to seek to a track but the playlist is empty or the index is out of bounds of the playlist"}]}],"name":"seekNoTrackAvailable"},{"name":"seekNoCurrentTrack","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to seek within a track but the playlist is empty or the track is not yet loaded"}]}]},{"name":"reorderMissingTrack","content":[{"inlineContent":[{"text":"Thrown when you attempt to move a track that is not on the loaded playlist","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to select a track to be played until the end but that track is not on the loaded playlist","type":"text"}]}],"name":"playToEndMissingTrack"},{"name":"moveTrackOutOfBounds","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to move a track at a position outside the bounds of the loaded playlist","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to stop looping a track but that track is not on the loaded playlist"}],"type":"paragraph"}],"name":"startLoopingNoLoopingTrack"},{"name":"stopLoopingNoLoopingTrack","content":[{"inlineContent":[{"text":"Thrown when you attempt to loop a track but that track is not on the loaded playlist","type":"text"}],"type":"paragraph"}]},{"name":"unimplemented","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to use an unimplemented method of the SDK"}]}]},{"name":"cancelled","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when an action you previously issued to AutomixIQ is cancelled due to another user initialed action that overrides it","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Thrown when you attempt to turn AutomixIQ on while it is already turning on","type":"text"}],"type":"paragraph"}],"name":"onAlreadyTurningOn"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ on while it is already turning off"}]}],"name":"onWhileTurningOff"},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ off while it is already turning off"}],"type":"paragraph"}],"name":"offAlreadyTurningOff"},{"name":"offWhileTurningOn","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to turn AutomixIQ off while it is already turning on","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the channel layout"}],"type":"paragraph"}],"name":"cannotCreateChannelLayout"},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the input buffer"}],"type":"paragraph"}],"name":"cannotCreateInputBuffer"},{"name":"cannotSetupAVAudioSession","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the AVAudioSession"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to start the audio engine"}],"type":"paragraph"}],"name":"cannotStartAudioEngine"},{"name":"cannotRestoreAudioSession","content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to restore the audio session to the state it found it when you turned it on"}],"type":"paragraph"}]},{"name":"failedToStop","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when AutomixIQ is unable to be stopped"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to load an explicit track but the setting to filter out explicit tracks is on"}]}],"name":"cannotLoadExplicitLyricsTrack"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/automixsdkerrorcode"]},{"paths":["\/documentation\/socialradio\/automixsdkerrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio"]]},"metadata":{"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"title":"AutomixSDKErrorCode","role":"symbol","externalID":"c:@M@SocialRadio@E@AutomixSDKErrorCode","modules":[{"name":"SocialRadio"}]},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cancelled","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/failedToStop","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/notMainThread","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/unable_to_load_mix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/unimplemented"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/Equatable-Implementations","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/seekNoCurrentTrack":{"url":"\/documentation\/socialradio\/automixsdkerrorcode\/seeknocurrenttrack","role":"symbol","type":"topic","kind":"symbol","abstract":[],"title":"AutomixSDKErrorCode.seekNoCurrentTrack","navigatorTitle":[{"text":"AutomixSDKErrorCodeSeekNoCurrentTrack","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/seekNoCurrentTrack","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"seekNoCurrentTrack","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/sdkNotInitialisedVersionNoLongerSupported":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkNotInitialisedVersionNoLongerSupported"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/sdknotinitialisedversionnolongersupported","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported"}],"title":"AutomixSDKErrorCode.sdkNotInitialisedVersionNoLongerSupported","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotInitialisedVersionNoLongerSupported","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/Errors-article":{"abstract":[{"text":"What errors the SocialRadio player can issue to help with player integration","type":"text"}],"url":"\/documentation\/socialradio\/errors-article","title":"Errors","role":"article","kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Errors-article","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"role":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/init(rawValue:)","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/init(rawvalue:)","abstract":[],"type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/onWhileTurningOff":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"onWhileTurningOff","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/onwhileturningoff","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOnWhileTurningOff"}],"title":"AutomixSDKErrorCode.onWhileTurningOff","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/onWhileTurningOff","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/backNoTrackAvailable":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"backNoTrackAvailable","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeBackNoTrackAvailable"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/backNoTrackAvailable","type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/backnotrackavailable","abstract":[],"title":"AutomixSDKErrorCode.backNoTrackAvailable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/addTrackOutOfBounds":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackOutOfBounds"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/addtrackoutofbounds","title":"AutomixSDKErrorCode.addTrackOutOfBounds","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackOutOfBounds","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackOutOfBounds"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/noInternetAvailableTooLongOffline":{"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/nointernetavailabletoolongoffline","title":"AutomixSDKErrorCode.noInternetAvailableTooLongOffline","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noInternetAvailableTooLongOffline"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","navigatorTitle":[{"text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/startLoopingNoLoopingTrack":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/startLoopingNoLoopingTrack","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/startloopingnoloopingtrack","type":"topic","title":"AutomixSDKErrorCode.startLoopingNoLoopingTrack","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeStartLoopingNoLoopingTrack"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startLoopingNoLoopingTrack"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/cannotCreateInputBuffer":{"navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotCreateInputBuffer","kind":"identifier"}],"type":"topic","title":"AutomixSDKErrorCode.cannotCreateInputBuffer","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotCreateInputBuffer","url":"\/documentation\/socialradio\/automixsdkerrorcode\/cannotcreateinputbuffer","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotCreateInputBuffer"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/unable_to_load_mix":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unable_to_load_mix"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/unable_to_load_mix","navigatorTitle":[{"text":"AutomixSDKErrorCodeUnable_to_load_mix","kind":"identifier"}],"title":"AutomixSDKErrorCode.unable_to_load_mix","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/unable_to_load_mix","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/cannotSetupAVAudioSession":{"kind":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotSetupAVAudioSession","kind":"identifier"}],"title":"AutomixSDKErrorCode.cannotSetupAVAudioSession","role":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode\/cannotsetupavaudiosession","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotSetupAVAudioSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotSetupAVAudioSession"},"doc://org.cocoapods.SocialRadio/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.SocialRadio\/SY","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/cancelled":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelled","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/cancelled","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCancelled"}],"title":"AutomixSDKErrorCode.cancelled","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cancelled","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/removeTrackOutOfBounds":{"title":"AutomixSDKErrorCode.removeTrackOutOfBounds","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeTrackOutOfBounds","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode\/removetrackoutofbounds","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/removeTrackOutOfBounds","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/failedToStop":{"navigatorTitle":[{"text":"AutomixSDKErrorCodeFailedToStop","kind":"identifier"}],"type":"topic","title":"AutomixSDKErrorCode.failedToStop","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/failedToStop","url":"\/documentation\/socialradio\/automixsdkerrorcode\/failedtostop","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failedToStop"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/addTrackNoMetadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackNoMetadata"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/addtracknometadata","navigatorTitle":[{"text":"AutomixSDKErrorCodeAddTrackNoMetadata","kind":"identifier"}],"title":"AutomixSDKErrorCode.addTrackNoMetadata","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackNoMetadata","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode":{"title":"AutomixSDKErrorCode","kind":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/offlineNoTunedUserIdAvailable":{"abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/offlinenotuneduseridavailable","title":"AutomixSDKErrorCode.offlineNoTunedUserIdAvailable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"offlineNoTunedUserIdAvailable"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/sdkAlreadyInitialised":{"title":"AutomixSDKErrorCode.sdkAlreadyInitialised","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/sdkalreadyinitialised","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkAlreadyInitialised","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sdkAlreadyInitialised","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkAlreadyInitialised","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/sdkAlreadyOn":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkAlreadyOn"}],"type":"topic","title":"AutomixSDKErrorCode.sdkAlreadyOn","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkAlreadyOn","url":"\/documentation\/socialradio\/automixsdkerrorcode\/sdkalreadyon","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sdkAlreadyOn","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/cannotCreateChannelLayout":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cannotCreateChannelLayout","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/cannotcreatechannellayout","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateChannelLayout"}],"title":"AutomixSDKErrorCode.cannotCreateChannelLayout","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotCreateChannelLayout","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"role":"collection","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/addTrackInternalError":{"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeAddTrackInternalError","kind":"identifier"}],"abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/addtrackinternalerror","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackInternalError"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackInternalError","title":"AutomixSDKErrorCode.addTrackInternalError","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/seekNoTrackAvailable":{"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSeekNoTrackAvailable"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/seekNoTrackAvailable","title":"AutomixSDKErrorCode.seekNoTrackAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekNoTrackAvailable"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/seeknotrackavailable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/reorderMissingTrack":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeReorderMissingTrack"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reorderMissingTrack","kind":"identifier"}],"title":"AutomixSDKErrorCode.reorderMissingTrack","url":"\/documentation\/socialradio\/automixsdkerrorcode\/reordermissingtrack","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/reorderMissingTrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/playToEndMixEnd":{"navigatorTitle":[{"text":"AutomixSDKErrorCodePlayToEndMixEnd","kind":"identifier"}],"type":"topic","title":"AutomixSDKErrorCode.playToEndMixEnd","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMixEnd","url":"\/documentation\/socialradio\/automixsdkerrorcode\/playtoendmixend","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playToEndMixEnd"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/sdkInitialisationUnauthorised":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkInitialisationUnauthorised","role":"symbol","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/sdkinitialisationunauthorised","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInitialisationUnauthorised"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkInitialisationUnauthorised"}],"abstract":[],"title":"AutomixSDKErrorCode.sdkInitialisationUnauthorised","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/onAlreadyTurningOn":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAlreadyTurningOn"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/onalreadyturningon","kind":"symbol","title":"AutomixSDKErrorCode.onAlreadyTurningOn","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOnAlreadyTurningOn"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/onAlreadyTurningOn","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/playAlreadyPlaying":{"title":"AutomixSDKErrorCode.playAlreadyPlaying","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/playalreadyplaying","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playAlreadyPlaying"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodePlayAlreadyPlaying","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playAlreadyPlaying","abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/playToEndMissingTrack":{"title":"AutomixSDKErrorCode.playToEndMissingTrack","url":"\/documentation\/socialradio\/automixsdkerrorcode\/playtoendmissingtrack","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playToEndMissingTrack","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMissingTrack","navigatorTitle":[{"text":"AutomixSDKErrorCodePlayToEndMissingTrack","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/stopLoopingNoLoopingTrack":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/stoploopingnoloopingtrack","navigatorTitle":[{"text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLoopingNoLoopingTrack"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","type":"topic","title":"AutomixSDKErrorCode.stopLoopingNoLoopingTrack"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/offAlreadyTurningOff":{"url":"\/documentation\/socialradio\/automixsdkerrorcode\/offalreadyturningoff","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offAlreadyTurningOff","kind":"identifier"}],"title":"AutomixSDKErrorCode.offAlreadyTurningOff","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offAlreadyTurningOff","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"AutomixSDKErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/loadTracksEmptyPlaylist":{"abstract":[],"navigatorTitle":[{"text":"AutomixSDKErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}],"title":"AutomixSDKErrorCode.loadTracksEmptyPlaylist","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/loadTracksEmptyPlaylist","role":"symbol","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode\/loadtracksemptyplaylist","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadTracksEmptyPlaylist"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/sdkError(code:)":{"url":"\/documentation\/socialradio\/sdkerror(code:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/sdkError(code:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkError"},{"kind":"text","text":"("},{"text":"code","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@E@AutomixSDKErrorCode","text":"AutomixSDKErrorCode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"}],"kind":"symbol","type":"topic","title":"sdkError(code:)","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/pauseAlreadyPaused":{"navigatorTitle":[{"text":"AutomixSDKErrorCodePauseAlreadyPaused","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/pauseAlreadyPaused","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pauseAlreadyPaused"}],"abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/pausealreadypaused","kind":"symbol","title":"AutomixSDKErrorCode.pauseAlreadyPaused"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/noInternetAvailable":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/noInternetAvailable","abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/nointernetavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"noInternetAvailable","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeNoInternetAvailable","kind":"identifier"}],"kind":"symbol","title":"AutomixSDKErrorCode.noInternetAvailable"},"doc://org.cocoapods.SocialRadio/SH":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/notMainThread":{"type":"topic","title":"AutomixSDKErrorCode.notMainThread","kind":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/notmainthread","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/notMainThread","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeNotMainThread"}],"abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notMainThread"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/addTrackPlaylistDoesNotExist":{"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackPlaylistDoesNotExist"}],"title":"AutomixSDKErrorCode.addTrackPlaylistDoesNotExist","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/addtrackplaylistdoesnotexist"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/moveTrackOutOfBounds":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/moveTrackOutOfBounds","kind":"symbol","role":"symbol","type":"topic","title":"AutomixSDKErrorCode.moveTrackOutOfBounds","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeMoveTrackOutOfBounds"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/movetrackoutofbounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveTrackOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/loadTracksOutOfBounds":{"url":"\/documentation\/socialradio\/automixsdkerrorcode\/loadtracksoutofbounds","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/loadTracksOutOfBounds","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadTracksOutOfBounds","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeLoadTracksOutOfBounds","kind":"identifier"}],"role":"symbol","title":"AutomixSDKErrorCode.loadTracksOutOfBounds","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/cannotStartAudioEngine":{"abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/cannotstartaudioengine","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotStartAudioEngine","type":"topic","navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotStartAudioEngine","kind":"identifier"}],"title":"AutomixSDKErrorCode.cannotStartAudioEngine","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cannotStartAudioEngine","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/sdkNotInitialised":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/sdknotinitialised","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkNotInitialised","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkNotInitialised"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotInitialised","title":"AutomixSDKErrorCode.sdkNotInitialised","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/previousNoTrackAvailable":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousNoTrackAvailable","kind":"identifier"}],"type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode\/previousnotrackavailable","role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/previousNoTrackAvailable","navigatorTitle":[{"text":"AutomixSDKErrorCodePreviousNoTrackAvailable","kind":"identifier"}],"title":"AutomixSDKErrorCode.previousNoTrackAvailable","kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/offWhileTurningOn":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offWhileTurningOn"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/offwhileturningon","navigatorTitle":[{"text":"AutomixSDKErrorCodeOffWhileTurningOn","kind":"identifier"}],"title":"AutomixSDKErrorCode.offWhileTurningOn","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offWhileTurningOn","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/cannotLoadExplicitLyricsTrack":{"kind":"symbol","type":"topic","title":"AutomixSDKErrorCode.cannotLoadExplicitLyricsTrack","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","url":"\/documentation\/socialradio\/automixsdkerrorcode\/cannotloadexplicitlyricstrack","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotLoadExplicitLyricsTrack"}],"abstract":[],"navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/Equatable-Implementations":{"url":"\/documentation\/socialradio\/automixsdkerrorcode\/equatable-implementations","title":"Equatable Implementations","abstract":[],"kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/Equatable-Implementations"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/sdkNotOn":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotOn","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/socialradio\/automixsdkerrorcode\/sdknoton","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sdkNotOn","kind":"identifier"}],"title":"AutomixSDKErrorCode.sdkNotOn","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkNotOn","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/unimplemented":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unimplemented","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeUnimplemented","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/unimplemented","title":"AutomixSDKErrorCode.unimplemented","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/unimplemented","abstract":[],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/nextNoTrackAvailable":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/nextNoTrackAvailable","url":"\/documentation\/socialradio\/automixsdkerrorcode\/nextnotrackavailable","title":"AutomixSDKErrorCode.nextNoTrackAvailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextNoTrackAvailable","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeNextNoTrackAvailable"}],"abstract":[],"role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/cannotRestoreAudioSession":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotRestoreAudioSession","kind":"identifier"}],"url":"\/documentation\/socialradio\/automixsdkerrorcode\/cannotrestoreaudiosession","kind":"symbol","title":"AutomixSDKErrorCode.cannotRestoreAudioSession","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotRestoreAudioSession"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotRestoreAudioSession","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKErrorCode/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/socialradio\/automixsdkerrorcode\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKErrorCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cancelled","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/failedToStop","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/notMainThread","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/unable_to_load_mix","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKErrorCode\/unimplemented"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Errors","identifiers":["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/Errors-article"],"title":"Errors"}],"op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AutomixSDKErrorCodeSeekNoCurrentTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1seekNoCurrentTrack\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1seekNoCurrentTrack\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeSeekNoCurrentTrack"}],"op":"replace"},{"value":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1onWhileTurningOff\/title","value":"AutomixSDKErrorCodeOnWhileTurningOff","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeOnWhileTurningOff","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1onWhileTurningOff\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1backNoTrackAvailable\/title","value":"AutomixSDKErrorCodeBackNoTrackAvailable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1backNoTrackAvailable\/fragments","value":[{"text":"AutomixSDKErrorCodeBackNoTrackAvailable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackOutOfBounds\/title","value":"AutomixSDKErrorCodeAddTrackOutOfBounds"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackOutOfBounds"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackOutOfBounds\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1noInternetAvailableTooLongOffline\/title","value":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1noInternetAvailableTooLongOffline\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline"}]},{"value":"AutomixSDKErrorCodeStartLoopingNoLoopingTrack","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1startLoopingNoLoopingTrack\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1startLoopingNoLoopingTrack\/fragments","value":[{"text":"AutomixSDKErrorCodeStartLoopingNoLoopingTrack","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeCannotCreateInputBuffer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotCreateInputBuffer\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateInputBuffer"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotCreateInputBuffer\/fragments","op":"replace"},{"value":"AutomixSDKErrorCodeUnable_to_load_mix","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1unable_to_load_mix\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeUnable_to_load_mix"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1unable_to_load_mix\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotSetupAVAudioSession\/title","value":"AutomixSDKErrorCodeCannotSetupAVAudioSession","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotSetupAVAudioSession\/fragments","value":[{"text":"AutomixSDKErrorCodeCannotSetupAVAudioSession","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cancelled\/title","value":"AutomixSDKErrorCodeCancelled"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cancelled\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeCancelled","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKErrorCodeRemoveTrackOutOfBounds","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1removeTrackOutOfBounds\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1removeTrackOutOfBounds\/fragments"},{"op":"replace","value":"AutomixSDKErrorCodeFailedToStop","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1failedToStop\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1failedToStop\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeFailedToStop"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackNoMetadata\/title","value":"AutomixSDKErrorCodeAddTrackNoMetadata"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackNoMetadata"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackNoMetadata\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/title","op":"replace","value":"AutomixSDKErrorCode"},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/title","value":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkAlreadyInitialised\/title","op":"replace","value":"AutomixSDKErrorCodeSdkAlreadyInitialised"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkAlreadyInitialised\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkAlreadyInitialised","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeSdkAlreadyOn","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkAlreadyOn\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkAlreadyOn\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkAlreadyOn","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotCreateChannelLayout\/title","op":"replace","value":"AutomixSDKErrorCodeCannotCreateChannelLayout"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateChannelLayout"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotCreateChannelLayout\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackInternalError\/title","value":"AutomixSDKErrorCodeAddTrackInternalError"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeAddTrackInternalError","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackInternalError\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1seekNoTrackAvailable\/title","op":"replace","value":"AutomixSDKErrorCodeSeekNoTrackAvailable"},{"value":[{"text":"AutomixSDKErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1seekNoTrackAvailable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1reorderMissingTrack\/title","value":"AutomixSDKErrorCodeReorderMissingTrack"},{"value":[{"text":"AutomixSDKErrorCodeReorderMissingTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1reorderMissingTrack\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playToEndMixEnd\/title","value":"AutomixSDKErrorCodePlayToEndMixEnd","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playToEndMixEnd\/fragments","value":[{"text":"AutomixSDKErrorCodePlayToEndMixEnd","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkInitialisationUnauthorised\/title","op":"replace","value":"AutomixSDKErrorCodeSdkInitialisationUnauthorised"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkInitialisationUnauthorised\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkInitialisationUnauthorised","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1onAlreadyTurningOn\/title","value":"AutomixSDKErrorCodeOnAlreadyTurningOn"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1onAlreadyTurningOn\/fragments","value":[{"text":"AutomixSDKErrorCodeOnAlreadyTurningOn","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKErrorCodePlayAlreadyPlaying","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playAlreadyPlaying\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playAlreadyPlaying\/fragments","value":[{"text":"AutomixSDKErrorCodePlayAlreadyPlaying","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playToEndMissingTrack\/title","op":"replace","value":"AutomixSDKErrorCodePlayToEndMissingTrack"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayToEndMissingTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1playToEndMissingTrack\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1stopLoopingNoLoopingTrack\/title","op":"replace","value":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1stopLoopingNoLoopingTrack\/fragments","value":[{"text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1offAlreadyTurningOff\/title","value":"AutomixSDKErrorCodeOffAlreadyTurningOff","op":"replace"},{"value":[{"text":"AutomixSDKErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1offAlreadyTurningOff\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1loadTracksEmptyPlaylist\/title","value":"AutomixSDKErrorCodeLoadTracksEmptyPlaylist","op":"replace"},{"value":[{"text":"AutomixSDKErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1loadTracksEmptyPlaylist\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1pauseAlreadyPaused\/title","value":"AutomixSDKErrorCodePauseAlreadyPaused","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1pauseAlreadyPaused\/fragments","value":[{"text":"AutomixSDKErrorCodePauseAlreadyPaused","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKErrorCodeNoInternetAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1noInternetAvailable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeNoInternetAvailable"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1noInternetAvailable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1notMainThread\/title","value":"AutomixSDKErrorCodeNotMainThread"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1notMainThread\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeNotMainThread"}],"op":"replace"},{"value":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackPlaylistDoesNotExist\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1addTrackPlaylistDoesNotExist\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeMoveTrackOutOfBounds","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1moveTrackOutOfBounds\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1moveTrackOutOfBounds\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeMoveTrackOutOfBounds"}]},{"value":"AutomixSDKErrorCodeLoadTracksOutOfBounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1loadTracksOutOfBounds\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeLoadTracksOutOfBounds"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1loadTracksOutOfBounds\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotStartAudioEngine\/title","value":"AutomixSDKErrorCodeCannotStartAudioEngine"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotStartAudioEngine"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotStartAudioEngine\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkNotInitialised\/title","value":"AutomixSDKErrorCodeSdkNotInitialised"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeSdkNotInitialised","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkNotInitialised\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1previousNoTrackAvailable\/title","value":"AutomixSDKErrorCodePreviousNoTrackAvailable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1previousNoTrackAvailable\/fragments","value":[{"text":"AutomixSDKErrorCodePreviousNoTrackAvailable","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKErrorCodeOffWhileTurningOn","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1offWhileTurningOn\/title","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeOffWhileTurningOn","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1offWhileTurningOn\/fragments"},{"value":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/fragments","value":[{"text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeSdkNotOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkNotOn\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1sdkNotOn\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeSdkNotOn","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1unimplemented\/title","op":"replace","value":"AutomixSDKErrorCodeUnimplemented"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1unimplemented\/fragments","value":[{"text":"AutomixSDKErrorCodeUnimplemented","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1nextNoTrackAvailable\/title","value":"AutomixSDKErrorCodeNextNoTrackAvailable"},{"value":[{"text":"AutomixSDKErrorCodeNextNoTrackAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1nextNoTrackAvailable\/fragments"},{"value":"AutomixSDKErrorCodeCannotRestoreAudioSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotRestoreAudioSession\/title"},{"value":[{"text":"AutomixSDKErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKErrorCode~1cannotRestoreAudioSession\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}