{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Objective-C accessible member for the track number"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel\/trackNumber-3vb21","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@AutomixIQ@objc(cs)TunedTrackModel(py)trackNumber","navigatorTitle":[{"kind":"identifier","text":"trackNumber"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"trackNumber","role":"symbol","modules":[{"name":"AutomixIQ"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/tunedtrackmodel\/tracknumber-3vb21"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/tunedtrackmodel\/tracknumber-3vb21"]}],"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedTrackModel/trackNumber-3vb21":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"text":"Objective-C accessible member for the track number","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel\/trackNumber-3vb21","title":"trackNumber","type":"topic","navigatorTitle":[{"text":"trackNumber","kind":"identifier"}],"url":"\/documentation\/automixiq\/tunedtrackmodel\/tracknumber-3vb21","kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedTrackModel":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedTrackModel"}],"abstract":[{"text":"TunedTrackModel models a track. This metadata is required.","type":"text"}],"url":"\/documentation\/automixiq\/tunedtrackmodel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedTrackModel"}],"title":"TunedTrackModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedTrackModel"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"type":"topic","role":"collection","title":"AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"trackNumber","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"trackNumber"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackNumber"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"trackNumber","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel~1trackNumber-3vb21\/title","op":"replace"},{"value":[{"kind":"identifier","text":"trackNumber"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel~1trackNumber-3vb21\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/title","op":"replace","value":"TunedTrackModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/fragments","op":"replace","value":[{"text":"TunedTrackModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedTrackModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedTrackModel"}]}]}]}