{"metadata":{"title":"init","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@SocialRadio@objc(cs)AutomixSDKWaveformBlob(im)init","modules":[{"name":"SocialRadio"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/socialradio\/automixsdkwaveformblob\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob\/init","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformBlob":{"abstract":[{"type":"text","text":"AutomixSDKWaveformBlob models the data to create a waveform shape representing a track"}],"role":"symbol","url":"\/documentation\/socialradio\/automixsdkwaveformblob","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob","title":"AutomixSDKWaveformBlob","type":"topic","navigatorTitle":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/AutomixSDKWaveformBlob/init":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/AutomixSDKWaveformBlob\/init","url":"\/documentation\/socialradio\/automixsdkwaveformblob\/init","navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"AutomixSDKWaveformBlob","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/title"},{"op":"replace","value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1AutomixSDKWaveformBlob\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}