{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH"],"title":"Conforms To","kind":"relationships"}],"metadata":{"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDK","symbolKind":"class","modules":[{"name":"PacemakerRadio"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDK"}],"roleHeading":"Class","title":"AutomixSDK"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/addStatusObserverDelegate(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOff(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOn(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixStatus()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/back(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/clearCache(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/loopPlayingTrack(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/next(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/on()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/pause(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/placeholderWaveformDataForTrack(identifier:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/play(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/previous(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/removeStatusObserverDelegate(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/reorderTracks(newOrder:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/resetPlaylistToEmpty(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setFilterExplicit(filterExplicit:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setMusicCacheDelegate(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setMute(on:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setPreferredTransitionDurationSeconds(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setReplay(on:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setVinylStartStopEnabled(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setWaveformPointsPerTrack(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/terminate()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/toggleMute(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/toggleReplay(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/waveformDataForTrack(identifier:applyTransitions:)"],"generated":true},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/instance"],"anchor":"Type-Properties"},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixSDKError(code:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/errorDescription(code:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/initialised()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/internetAvailable()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC"],"title":"AutomixIQ","anchor":"AutomixIQ"}],"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/loopPlayingTrack(completion:)":{"navigatorTitle":[{"text":"loopPlayingTrackWithCompletion:","kind":"identifier"}],"title":"loopPlayingTrack(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loopPlayingTrack"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/loopPlayingTrack(completion:)","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdk\/loopplayingtrack(completion:)","abstract":[{"type":"text","text":"Makes AutomixIQ repeat the currently playing track."}],"type":"topic","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setWaveformPointsPerTrack(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setWaveformPointsPerTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the resolution of the waveform data for a track"}],"navigatorTitle":[{"kind":"identifier","text":"setWaveformPointsPerTrack:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setWaveformPointsPerTrack(_:)","title":"setWaveformPointsPerTrack(_:)","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk\/setwaveformpointspertrack(_:)"},"doc://org.cocoapods.PacemakerRadio/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/automixOn(completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOn(completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/automixon(completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automixOn"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"title":"automixOn(completion:)","navigatorTitle":[{"kind":"identifier","text":"automixOnCompletion:"}],"abstract":[{"text":"Turns AutomixIQ on.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Returns an error if the engine has not been initialised or has already been turned on."}]},"doc://org.cocoapods.PacemakerRadio/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/loadtracks(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadTracks","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel"},{"kind":"text","text":"]?, "},{"text":"playTrackIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"autoplay"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","navigatorTitle":[{"text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","kind":"identifier"}],"abstract":[{"text":"Loads a new playlist into AutomixIQ","type":"text"},{"text":" ","type":"text"},{"text":"Returns an error if the playlist is empty this opperation will fail and AutomixIQ will be turned off.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This will stop playback of the currently playing playlist and start the newly loaded one."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/pause(completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/pause(completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/pause(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"title":"pause(completion:)","navigatorTitle":[{"text":"pauseWithCompletion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Pauses playback if playing."},{"text":" ","type":"text"},{"text":"Returns an error if the player is already paused.","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/removeStatusObserverDelegate(_:)":{"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk\/removestatusobserverdelegate(_:)","kind":"symbol","abstract":[{"text":"Removes a status observer delegate","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeStatusObserverDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"title":"removeStatusObserverDelegate(_:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/removeStatusObserverDelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"removeStatusObserverDelegate:"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/toggleMute(completion:)":{"kind":"symbol","title":"toggleMute(completion:)","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/toggleMute(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toggleMute","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"toggleMuteWithCompletion:"}],"abstract":[{"text":"Toggles the AutomixIQ SDK mute","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdk\/togglemute(completion:)"},"doc://org.cocoapods.PacemakerRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/errorDescription(code:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/errorDescription(code:)","url":"\/documentation\/pacemakerradio\/automixsdk\/errordescription(code:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"errorDescription(code:)","navigatorTitle":[{"kind":"identifier","text":"errorDescriptionWithCode:"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/toggleReplay(completion:)":{"kind":"symbol","role":"symbol","title":"toggleReplay(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toggleReplay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"toggleReplayWithCompletion:"}],"deprecated":true,"url":"\/documentation\/pacemakerradio\/automixsdk\/togglereplay(completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/toggleReplay(completion:)","abstract":[{"type":"text","text":"If on, after a playlist is done it restarts. Otherwise, it pauses."},{"type":"text","text":" "},{"text":"This defaults to false on initialisation and should be set to match the state of the consumer’s UI","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixIQ-article":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixIQ-article","type":"topic","url":"\/documentation\/pacemakerradio\/automixiq-article","abstract":[{"type":"text","text":"Availablity of underlying technologies and APIs."}],"kind":"article","role":"article","title":"AutomixIQ"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/automixOff(completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOff(completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/automixoff(completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixOff"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"kind":"text","text":": "},{"text":"AutomixSDKStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"automixOff(completion:)","navigatorTitle":[{"text":"automixOffWithCompletion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Turns the AutomixIQ player off."},{"type":"text","text":" "},{"text":"In order to turn it back on you will have to call -(void)automixOnWithIdentifiers:playTrackIndex:seconds:autoplay:","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/previous(completion:)":{"abstract":[{"type":"text","text":"Moves the player to the beginning of the previous track"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"previousWithCompletion:"}],"title":"previous(completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/previous(completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/previous(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"previous"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setReplay(on:completion:)":{"url":"\/documentation\/pacemakerradio\/automixsdk\/setreplay(on:completion:)","role":"symbol","title":"setReplay(on:completion:)","abstract":[{"text":"Tells AutomixIQ whether or not it should restart the playlist when reaching the end.","type":"text"},{"type":"text","text":" "},{"text":"If on then playback will restart at the beginning otherwise it pauses at the end.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setReplay(on:completion:)","navigatorTitle":[{"text":"setReplayOn:completion:","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setReplay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/internetAvailable()":{"abstract":[{"type":"text","text":"Returns whether AutomixIQ can see the internet"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"internetAvailable"}],"title":"internetAvailable()","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/internetAvailable()","url":"\/documentation\/pacemakerradio\/automixsdk\/internetavailable()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internetAvailable","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/moveTrack(at:toIndex:completion:)":{"url":"\/documentation\/pacemakerradio\/automixsdk\/movetrack(at:toindex:completion:)","role":"symbol","title":"moveTrack(at:toIndex:completion:)","abstract":[{"type":"text","text":"Moves the track from one index to a different index."}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/moveTrack(at:toIndex:completion:)","navigatorTitle":[{"text":"moveTrackAt:toIndex:completion:","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toIndex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setVinylStartStopEnabled(_:completion:)":{"kind":"symbol","role":"symbol","title":"setVinylStartStopEnabled(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setVinylStartStopEnabled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"setVinylStartStopEnabled:completion:","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdk\/setvinylstartstopenabled(_:completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setVinylStartStopEnabled(_:completion:)","abstract":[{"type":"text","text":"Enables \/ Disables vinyl pause sound effect."}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setAutomixVolumeNormalised(_:completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/setautomixvolumenormalised(_:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAutomixVolumeNormalised","kind":"identifier"},{"kind":"text","text":"(Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"setAutomixVolumeNormalised(_:completion:)","navigatorTitle":[{"text":"setAutomixVolumeNormalised:completion:","kind":"identifier"}],"abstract":[{"text":"Sets AutomixIQ’s volume to a given value between 0 and 1. If muted, calling this will cause AutomixIQ to unmute.","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/resetPlaylistToEmpty(completion:)":{"kind":"symbol","role":"symbol","title":"resetPlaylistToEmpty(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetPlaylistToEmpty","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"resetPlaylistToEmptyWithCompletion:"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/resetPlaylistToEmpty(completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/resetplaylisttoempty(completion:)","abstract":[{"type":"text","text":"Clears all the tracks in the AutomixIQ playlist"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setMusicCacheDelegate(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setMusicCacheDelegate(_:)","url":"\/documentation\/pacemakerradio\/automixsdk\/setmusiccachedelegate(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMusicCacheDelegate"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":")"}],"title":"setMusicCacheDelegate(_:)","navigatorTitle":[{"kind":"identifier","text":"setMusicCacheDelegate:"}],"abstract":[{"type":"text","text":"Adds a new music cache delegate"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/terminate()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"terminate"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Terminates \/ deinitialises AutomixIQ. Call this on applicationWillTerminate, or whenever you no longer need it."}],"navigatorTitle":[{"kind":"identifier","text":"terminate"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/terminate()","title":"terminate()","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk\/terminate()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/instance":{"abstract":[{"type":"text","text":"Returns the singleton instance."}],"kind":"symbol","title":"instance","url":"\/documentation\/pacemakerradio\/automixsdk\/instance","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/instance","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDK","text":"AutomixSDK","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"instance","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setAutomixPlaySpeed(_:completion:)":{"type":"topic","abstract":[{"type":"text","text":"Sets AutomixIQ’s play speed to a given value between 0.5 and 2, where 0.5 is half speed and 2 is double speed."}],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdk\/setautomixplayspeed(_:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAutomixPlaySpeed","kind":"identifier"},{"text":"(Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"title":"setAutomixPlaySpeed(_:completion:)","navigatorTitle":[{"text":"setAutomixPlaySpeed:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/reorderTracks(newOrder:completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/reorderTracks(newOrder:completion:)","title":"reorderTracks(newOrder:completion:)","abstract":[{"type":"text","text":"Sets a new order to the playlist while continuing to play the current track"}],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdk\/reordertracks(neworder:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reorderTracks","kind":"identifier"},{"kind":"text","text":"("},{"text":"newOrder","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"reorderTracksWithNewOrder:completion:","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","title":"PacemakerRadio","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setMute(on:completion:)":{"kind":"symbol","role":"symbol","title":"setMute(on:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMute"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"setMuteOn:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setMute(on:completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/setmute(on:completion:)","abstract":[{"text":"Mutes AutomixIQ","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/SH":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKObjC","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC","title":"AutomixSDKObjC","kind":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setPreferredTransitionDurationSeconds(_:completion:)":{"navigatorTitle":[{"text":"setPreferredTransitionDurationSeconds:completion:","kind":"identifier"}],"abstract":[{"text":"Sets AutomixIQ’s preferred transition duration - transitions will not be exactly this duration but AutomixIQ will favour transitions with duration close to this one.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Setting it to 0 disables this hint and allows the engine to select the transition duration based on trained genre-based transition data."}],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdk\/setpreferredtransitiondurationseconds(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPreferredTransitionDurationSeconds"},{"kind":"text","text":"(Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"type":"topic","title":"setPreferredTransitionDurationSeconds(_:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setPreferredTransitionDurationSeconds(_:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/stopLoopingPlayingTrack(completion:)":{"kind":"symbol","role":"symbol","title":"stopLoopingPlayingTrack(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLoopingPlayingTrack"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"stopLoopingPlayingTrackWithCompletion:"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/stoploopingplayingtrack(completion:)","abstract":[{"text":"Makes AutomixIQ stop repeating the currently playing track.","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/play(completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/play(completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/play(completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"play"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"title":"play(completion:)","navigatorTitle":[{"text":"playWithCompletion:","kind":"identifier"}],"abstract":[{"text":"Starts playback if paused.","type":"text"},{"text":" ","type":"text"},{"text":"Returns an error if the player is already playing.","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/waveformDataForTrack(identifier:applyTransitions:)":{"role":"symbol","kind":"symbol","title":"waveformDataForTrack(identifier:applyTransitions:)","abstract":[{"type":"text","text":"Gets the waveform data for a track."}],"url":"\/documentation\/pacemakerradio\/automixsdk\/waveformdatafortrack(identifier:applytransitions:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/waveformDataForTrack(identifier:applyTransitions:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyTransitions"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel","text":"AutomixSDKWaveformModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"waveformDataForTrackWithIdentifier:applyTransitions:","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/init":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/init","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk\/init"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/placeholderWaveformDataForTrack(identifier:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placeholderWaveformDataForTrack"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"placeholderWaveformDataForTrackWithIdentifier:","kind":"identifier"}],"kind":"symbol","title":"placeholderWaveformDataForTrack(identifier:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/placeholderWaveformDataForTrack(identifier:)","url":"\/documentation\/pacemakerradio\/automixsdk\/placeholderwaveformdatafortrack(identifier:)","abstract":[{"type":"text","text":"Gets the placeholder waveform data for a track."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/addTrack(identifier:metadata:index:completion:)":{"kind":"symbol","role":"symbol","title":"addTrack(identifier:metadata:index:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"index"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"addTrackWithIdentifier:metadata:index:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/addtrack(identifier:metadata:index:completion:)","abstract":[{"text":"Adds a single track to the AutomixIQ playlist at a given index.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Returns an erorr if the index is out of bounds."}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/initialised()":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/initialised()","url":"\/documentation\/pacemakerradio\/automixsdk\/initialised()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialised","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"initialised()","navigatorTitle":[{"kind":"identifier","text":"initialised"}],"abstract":[{"text":"Returns whether or not AutomixIQ is initialised.","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/back(completion:)":{"kind":"symbol","role":"symbol","title":"back(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"backWithCompletion:"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/back(completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/back(completion:)","abstract":[{"text":"Moves the player to the beginning of the current track","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/addStatusObserverDelegate(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/addStatusObserverDelegate(_:)","url":"\/documentation\/pacemakerradio\/automixsdk\/addstatusobserverdelegate(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addStatusObserverDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"title":"addStatusObserverDelegate(_:)","navigatorTitle":[{"text":"addStatusObserverDelegate:","kind":"identifier"}],"abstract":[{"type":"text","text":"Adds a new status observer delegate"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)":{"abstract":[{"text":"Gets the waveform data for a track.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applyEnterTransition"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyExitTransition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)","role":"symbol","kind":"symbol","title":"waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)","url":"\/documentation\/pacemakerradio\/automixsdk\/waveformdatafortrack(identifier:applyentertransition:applyexittransition:)"},"doc://org.cocoapods.PacemakerRadio/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/addTracks(identifiers:metadata:index:completion:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addTracks","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","abstract":[{"text":"Adds additional tracks to the playlist in AutomixIQ at a given index.","type":"text"},{"type":"text","text":" "},{"text":"Returns an erorr if the index is out of bounds.","type":"text"}],"title":"addTracks(identifiers:metadata:index:completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/addtracks(identifiers:metadata:index:completion:)","role":"symbol","navigatorTitle":[{"text":"addTracksWithIdentifiers:metadata:index:completion:","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/automixSDKError(code:)":{"navigatorTitle":[{"text":"automixSDKErrorWithCode:","kind":"identifier"}],"title":"automixSDKError(code:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"automixSDKError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode","text":"AutomixSDKErrorCode","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixSDKError(code:)","url":"\/documentation\/pacemakerradio\/automixsdk\/automixsdkerror(code:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/seekTo(seconds:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/seekTo(seconds:completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/seekto(seconds:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekTo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"seconds"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"type":"topic","title":"seekTo(seconds:completion:)","abstract":[{"text":"Jumps playback on the current track to the desired timestamp as soon as possible.","type":"text"},{"text":" ","type":"text"},{"text":"This will mix the track with itself so the seek is beat-matched and as seamless as possible, which means the landing position will be close but not exactly the fed timestamp.","type":"text"}],"navigatorTitle":[{"text":"seekToSeconds:completion:","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/next(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"next"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/next(completion:)","title":"next(completion:)","abstract":[{"text":"Moves the player to the beginning of the next track","type":"text"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk\/next(completion:)","navigatorTitle":[{"kind":"identifier","text":"nextWithCompletion:"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automixOn","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"playTrackIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Turns the AutomixIQ player on and starts playback if required as soon as possible at a given track and playback time within the provided playlist."},{"text":" ","type":"text"},{"text":"If the playlist is empty this operation will fail and AutomixIQ will be turned off.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Returns an error if the engine has not been initialised or has already been turned on."}],"title":"automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/automixon(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/removeTrack(at:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeTrack","kind":"identifier"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/removeTrack(at:completion:)","title":"removeTrack(at:completion:)","abstract":[{"type":"text","text":"Removes a track at a given index in the AutomixIQ playlist."},{"type":"text","text":" "},{"text":"Returns an erorr if the index is out of bounds.","type":"text"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk\/removetrack(at:completion:)","navigatorTitle":[{"kind":"identifier","text":"removeTrackAt:completion:"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setFilterExplicit(filterExplicit:completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setFilterExplicit","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"filterExplicit"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"setFilterExplicitWithFilterExplicit:completion:"}],"abstract":[{"type":"text","text":"Sets the filter explicit lyrics flag."},{"text":" ","type":"text"},{"type":"text","text":"When set to on, AutomixIQ will skip over the tracks that have the explicit content flag set in their metadata by mixing the currently playing track with the first available non-explicit track in the queue."}],"title":"setFilterExplicit(filterExplicit:completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/setfilterexplicit(filterexplicit:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setFilterExplicit(filterExplicit:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/automixStatus()":{"type":"topic","role":"symbol","abstract":[{"text":"Gets the current automix status","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixStatus"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKStatus","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"automixStatus"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixStatus()","url":"\/documentation\/pacemakerradio\/automixsdk\/automixstatus()","kind":"symbol","title":"automixStatus()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/playTrackUntilEndThenPause(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"playTrackUntilEndThenPause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","title":"playTrackUntilEndThenPause(completion:)","abstract":[{"type":"text","text":"Makes AutomixIQ play a given track until the end and then pause."},{"text":" ","type":"text"},{"type":"text","text":"This is useful if you need to play any other content between tracks such as advertisements."},{"text":" ","type":"text"},{"type":"text","text":"Returns an error if you call this on the last track"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk\/playtrackuntilendthenpause(completion:)","navigatorTitle":[{"text":"playTrackUntilEndThenPauseWithCompletion:","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDK"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK","navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"kind":"symbol","role":"symbol","title":"AutomixSDK"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/skipToTrackAtIndex(_:completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipToTrackAtIndex"},{"kind":"text","text":"("},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"skipToTrackAtIndex:completion:","kind":"identifier"}],"abstract":[{"text":"Jumps playback to the beginning of the track at the desired index as soon as possible.","type":"text"}],"title":"skipToTrackAtIndex(_:completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/skiptotrackatindex(_:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/skipToTrackAtIndex(_:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/clearCache(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearCache","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/clearCache(completion:)","title":"clearCache(completion:)","abstract":[{"text":"Clears AutomixIQ backing files and recreates them empty","type":"text"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk\/clearcache(completion:)","navigatorTitle":[{"kind":"identifier","text":"clearCacheWithCompletion:"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/on()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"on","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"on"}],"abstract":[{"type":"text","text":"Returns the on\/off status of AutomixIQ."}],"title":"on()","url":"\/documentation\/pacemakerradio\/automixsdk\/on()","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/on()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDK"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AutomixSDK"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/addStatusObserverDelegate(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOff(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOn(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixStatus()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/back(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/clearCache(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/init","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/loopPlayingTrack(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/next(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/on()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/pause(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/placeholderWaveformDataForTrack(identifier:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/play(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/previous(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/removeStatusObserverDelegate(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/reorderTracks(newOrder:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/resetPlaylistToEmpty(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setFilterExplicit(filterExplicit:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setMusicCacheDelegate(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setMute(on:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setPreferredTransitionDurationSeconds(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setReplay(on:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setVinylStartStopEnabled(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setWaveformPointsPerTrack(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/terminate()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/toggleMute(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/toggleReplay(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/waveformDataForTrack(identifier:applyTransitions:)"]},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/instance"],"title":"Type Properties","anchor":"Type-Properties"},{"anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixSDKError(code:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/errorDescription(code:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/initialised()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/internetAvailable()"],"title":"Type Methods","generated":true}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixIQ-article"],"anchor":"AutomixIQ","title":"AutomixIQ"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1loopPlayingTrack(completion:)\/title","value":"loopPlayingTrackWithCompletion:"},{"value":[{"text":"- ","kind":"text"},{"text":"loopPlayingTrackWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1loopPlayingTrack(completion:)\/fragments"},{"value":"setWaveformPointsPerTrack:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setWaveformPointsPerTrack(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setWaveformPointsPerTrack(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setWaveformPointsPerTrack:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixOn(completion:)\/title","value":"automixOnCompletion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"automixOnCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixOn(completion:)\/fragments"},{"value":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}]},{"value":"pauseWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1pause(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1pause(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pauseWithCompletion:"}]},{"value":"removeStatusObserverDelegate:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1removeStatusObserverDelegate(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1removeStatusObserverDelegate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeStatusObserverDelegate:","kind":"identifier"}]},{"op":"replace","value":"toggleMuteWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1toggleMute(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1toggleMute(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toggleMuteWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1errorDescription(code:)\/title","value":"errorDescriptionWithCode:"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1errorDescription(code:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"errorDescriptionWithCode:","kind":"identifier"}],"op":"replace"},{"value":"toggleReplayWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1toggleReplay(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1toggleReplay(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"toggleReplayWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixOff(completion:)\/title","op":"replace","value":"automixOffWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixOff(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"automixOffWithCompletion:"}],"op":"replace"},{"op":"replace","value":"previousWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1previous(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"previousWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1previous(completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setReplay(on:completion:)\/title","value":"setReplayOn:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setReplayOn:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setReplay(on:completion:)\/fragments"},{"value":"internetAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1internetAvailable()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1internetAvailable()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"internetAvailable"}]},{"value":"moveTrackAt:toIndex:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1moveTrack(at:toIndex:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"moveTrackAt:toIndex:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1moveTrack(at:toIndex:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setVinylStartStopEnabled(_:completion:)\/title","value":"setVinylStartStopEnabled:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setVinylStartStopEnabled:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setVinylStartStopEnabled(_:completion:)\/fragments","op":"replace"},{"value":"setAutomixVolumeNormalised:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setAutomixVolumeNormalised(_:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setAutomixVolumeNormalised:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setAutomixVolumeNormalised(_:completion:)\/fragments"},{"value":"resetPlaylistToEmptyWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1resetPlaylistToEmpty(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1resetPlaylistToEmpty(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"resetPlaylistToEmptyWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setMusicCacheDelegate(_:)\/title","value":"setMusicCacheDelegate:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setMusicCacheDelegate(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMusicCacheDelegate:"}]},{"value":"terminate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1terminate()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1terminate()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"terminate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1instance\/title","value":"instance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1instance\/fragments","value":[{"text":"instance","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setAutomixPlaySpeed(_:completion:)\/title","value":"setAutomixPlaySpeed:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"setAutomixPlaySpeed:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setAutomixPlaySpeed(_:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1reorderTracks(newOrder:completion:)\/title","op":"replace","value":"reorderTracksWithNewOrder:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reorderTracksWithNewOrder:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1reorderTracks(newOrder:completion:)\/fragments"},{"value":"setMuteOn:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setMute(on:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setMute(on:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setMuteOn:completion:"}],"op":"replace"},{"value":"setPreferredTransitionDurationSeconds:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setPreferredTransitionDurationSeconds(_:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setPreferredTransitionDurationSeconds(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPreferredTransitionDurationSeconds:completion:"}]},{"value":"stopLoopingPlayingTrackWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1stopLoopingPlayingTrack(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1stopLoopingPlayingTrack(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"stopLoopingPlayingTrackWithCompletion:","kind":"identifier"}]},{"value":"playWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1play(completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1play(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"playWithCompletion:","kind":"identifier"}]},{"value":"waveformDataForTrackWithIdentifier:applyTransitions:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1waveformDataForTrack(identifier:applyTransitions:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1waveformDataForTrack(identifier:applyTransitions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"waveformDataForTrackWithIdentifier:applyTransitions:"}]},{"op":"replace","value":"placeholderWaveformDataForTrackWithIdentifier:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1placeholderWaveformDataForTrack(identifier:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1placeholderWaveformDataForTrack(identifier:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"placeholderWaveformDataForTrackWithIdentifier:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1addTrack(identifier:metadata:index:completion:)\/title","value":"addTrackWithIdentifier:metadata:index:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1addTrack(identifier:metadata:index:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTrackWithIdentifier:metadata:index:completion:"}]},{"value":"initialised","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1initialised()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1initialised()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"initialised","kind":"identifier"}]},{"op":"replace","value":"backWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1back(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1back(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backWithCompletion:"}]},{"value":"addStatusObserverDelegate:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1addStatusObserverDelegate(_:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addStatusObserverDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1addStatusObserverDelegate(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)\/title","value":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:"}],"op":"replace"},{"value":"addTracksWithIdentifiers:metadata:index:completion:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1addTracks(identifiers:metadata:index:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1addTracks(identifiers:metadata:index:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addTracksWithIdentifiers:metadata:index:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"automixSDKErrorWithCode:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixSDKError(code:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"automixSDKErrorWithCode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixSDKError(code:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1seekTo(seconds:completion:)\/title","op":"replace","value":"seekToSeconds:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1seekTo(seconds:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"seekToSeconds:completion:"}]},{"op":"replace","value":"nextWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1next(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1next(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"nextWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title","op":"replace","value":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixOn(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"automixOnIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1removeTrack(at:completion:)\/title","op":"replace","value":"removeTrackAt:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1removeTrack(at:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeTrackAt:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setFilterExplicit(filterExplicit:completion:)\/title","value":"setFilterExplicitWithFilterExplicit:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setFilterExplicitWithFilterExplicit:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setFilterExplicit(filterExplicit:completion:)\/fragments"},{"value":"automixStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixStatus()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixStatus()\/fragments","value":[{"kind":"text","text":"- "},{"text":"automixStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"playTrackUntilEndThenPauseWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1playTrackUntilEndThenPause(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1playTrackUntilEndThenPause(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"playTrackUntilEndThenPauseWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/title","value":"AutomixSDK"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/fragments","value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"AutomixSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1skipToTrackAtIndex(_:completion:)\/title","value":"skipToTrackAtIndex:completion:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"skipToTrackAtIndex:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1skipToTrackAtIndex(_:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1clearCache(completion:)\/title","value":"clearCacheWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1clearCache(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearCacheWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1on()\/title","value":"on","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"on"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1on()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}