{"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Moderation-article","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"Moderation","roleHeading":"Article","role":"article","modules":[{"name":"PacemakerRadio"}]},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Essentials","level":2,"anchor":"Essentials"},{"type":"paragraph","inlineContent":[{"text":"PacemakerRadio offers moderation of content by allowing the user to report inapropriate mixtapes or users. To do so, you use ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/reportUser(identifier:completion:)"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/reportMixtape(identifier:completion:)","type":"reference"},{"text":".","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["public class MyApplication {","    \/\/ ...","    func didPressReportUserButton(identifier: String) {","        RadioSDK.getInstance()?.reportUser(identifier) { error in ","        }","    }","    ","    fun didPressReportMixtapeButton(identifier: String) {","        RadioSDK.getInstance()?.reportMixtape(identifier) { error in ","        }","    }","    \/\/ ...","}"]},{"inlineContent":[{"type":"text","text":"PacemakerRadio also offers the possibility of sending users a notification. To do so, you use "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"},{"code":["public class MyApplication {","    \/\/ ...","    func notifyFollowers(identifier: String, title: String, body: String, objectType: String?, objectId: String?) {","        RadioSDK.getInstance()?.notifyFollowers(userIdentifier: identifier, ","                                                title: title, ","                                                body: body, ","                                                objectType: objectType, ","                                                objectId: objectId) {","        }","    }","    \/\/ ...","}"],"type":"codeListing","syntax":"swift"}]}],"variants":[{"paths":["\/documentation\/pacemakerradio\/moderation-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/moderation-article"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"abstract":[{"type":"text","text":"Tools to interact with the social layer."}],"sections":[],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK/reportMixtape(identifier:completion:)":{"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdk\/reportmixtape(identifier:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reportMixtape","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"reportMixtape(identifier:completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/reportMixtape(identifier:completion:)","navigatorTitle":[{"text":"reportMixtapeWithIdentifier:completion:","kind":"identifier"}],"abstract":[{"text":"Submits a report for inappropriate content for a mixtape.","type":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK/reportUser(identifier:completion:)":{"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdk\/reportuser(identifier:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reportUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"reportUser(identifier:completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/reportUser(identifier:completion:)","navigatorTitle":[{"text":"reportUserWithIdentifier:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Submits a report for inappropriate content for a user."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)":{"url":"\/documentation\/pacemakerradio\/radiosdk\/notifyfollowers(useridentifier:title:body:objecttype:objectid:completion:)","title":"notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"notifyFollowers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"objectType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"objectId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"notifyFollowersWithUserIdentifier:title:body:objectType:objectId:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Submits a request to notify all followers of a user of something."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol","title":"PacemakerRadio","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"reportMixtapeWithIdentifier:completion:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1reportMixtape(identifier:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"reportMixtapeWithIdentifier:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1reportMixtape(identifier:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1reportUser(identifier:completion:)\/title","value":"reportUserWithIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1reportUser(identifier:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reportUserWithIdentifier:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)\/title","value":"notifyFollowersWithUserIdentifier:title:body:objectType:objectId:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"notifyFollowersWithUserIdentifier:title:body:objectType:objectId:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1notifyFollowers(userIdentifier:title:body:objectType:objectId:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}