{"variants":[{"paths":["\/documentation\/socialradio\/radiosdkfeaturesetconfig\/deeplinktouser"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/radiosdkfeaturesetconfig\/deeplinktouser"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)RadioSDKFeatureSetConfig(py)deeplinkToUser","modules":[{"name":"SocialRadio"}],"title":"deeplinkToUser","navigatorTitle":[{"text":"deeplinkToUser","kind":"identifier"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deeplinkToUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig\/deeplinkToUser","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deeplinkToUser"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig"]]},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKFeatureSetConfig/deeplinkToUser":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deeplinkToUser"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"deeplinkToUser","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig\/deeplinkToUser","url":"\/documentation\/socialradio\/radiosdkfeaturesetconfig\/deeplinktouser","navigatorTitle":[{"kind":"identifier","text":"deeplinkToUser"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"url":"\/documentation\/socialradio","title":"SocialRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","kind":"symbol","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/RadioSDKFeatureSetConfig":{"abstract":[],"kind":"symbol","type":"topic","title":"RadioSDKFeatureSetConfig","role":"symbol","url":"\/documentation\/socialradio\/radiosdkfeaturesetconfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/RadioSDKFeatureSetConfig","navigatorTitle":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"deeplinkToUser","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"deeplinkToUser"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"deeplinkToUser","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig~1deeplinkToUser\/title","value":"deeplinkToUser","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig~1deeplinkToUser\/fragments","value":[{"text":"deeplinkToUser","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/title","value":"RadioSDKFeatureSetConfig","op":"replace"},{"value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/fragments","op":"replace"},{"op":"replace","value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1RadioSDKFeatureSetConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}