{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig"]]},"variants":[{"paths":["\/documentation\/socialradio\/socialradioconfig\/applicationid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/socialradio\/socialradioconfig\/applicationid"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioConfig(py)applicationId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"modules":[{"name":"SocialRadio"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"applicationId"}],"symbolKind":"property","roleHeading":"Instance Property","title":"applicationId"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig\/applicationId"},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig/applicationId":{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig\/applicationId","url":"\/documentation\/socialradio\/socialradioconfig\/applicationid","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"applicationId","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"applicationId"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"kind":"symbol","title":"SocialRadioConfig","role":"symbol","abstract":[{"type":"text","text":"SocialRadioConfig holds the variables to initialise SocialRadio and describe the desired feature set and UI"}],"url":"\/documentation\/socialradio\/socialradioconfig","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioConfig","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioConfig","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"applicationId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"applicationId","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"applicationId","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig~1applicationId\/title","op":"replace","value":"applicationId"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig~1applicationId\/fragments","op":"replace","value":[{"kind":"identifier","text":"applicationId"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","value":"SocialRadioConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","value":[{"kind":"identifier","text":"SocialRadioConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"op":"replace"}]}]}