{"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"],"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs","generated":true,"title":"Initializing AutomixIQ for use with Tuned Global’s APIs"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/automixiq\/tunedrestdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/tunedrestdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"role":"symbol","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"title":"TunedRestDelegate","externalID":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","roleHeading":"Protocol","modules":[{"name":"AutomixIQ"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/automaticallyLogPlayback()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/uniqueDeviceIdentifier()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate"},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-article":{"url":"\/documentation\/automixiq\/initialising-automixiq-article","title":"Initializing AutomixIQ","role":"article","type":"topic","abstract":[{"type":"text","text":"How to validate your client and start using the AutomixIQ SDK with Tuned Global APIs"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","kind":"article"},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/logAutomixIQMessage(logLevel:message:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logAutomixIQMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"logLevel","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@E@TunedLogLevel","kind":"typeIdentifier","text":"TunedLogLevel"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","abstract":[{"text":"Called by AutomixIQ when it wishes to output a log message","type":"text"}],"kind":"symbol","title":"logAutomixIQMessage(logLevel:message:)","navigatorTitle":[{"text":"logAutomixIQMessageWithLogLevel:message:","kind":"identifier"}],"url":"\/documentation\/automixiq\/tunedrestdelegate\/logautomixiqmessage(loglevel:message:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetAuthenticatedDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedDeviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","abstract":[{"type":"text","text":"Called by AutomixIQ while initialising to give you an opportunity to provide the authenticated device ID or perform device authentication as required."},{"type":"text","text":" "},{"type":"text","text":"If not implemented, AutomixIQ will proceed to register a device for the logged in user with deviceType: “iPhone”, displayName: “AutomixIQ” and deviceOS: “iOS”."}],"kind":"symbol","title":"asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","navigatorTitle":[{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}],"url":"\/documentation\/automixiq\/tunedrestdelegate\/asyncgetauthenticateddevice(deviceidentifierforvendor:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"kind":"symbol","title":"TunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"url":"\/documentation\/automixiq\/tunedrestdelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQMusicCacheDelegate":{"url":"\/documentation\/automixiq\/automixiqmusiccachedelegate","title":"AutomixIQMusicCacheDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"type":"topic","abstract":[{"type":"text","text":"AutomixIQMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixIQConfig":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixIQConfig"}],"role":"symbol","abstract":[],"type":"topic","title":"AutomixIQConfig","url":"\/documentation\/automixiq\/automixiqconfig","navigatorTitle":[{"text":"AutomixIQConfig","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","title":"AutomixIQ","url":"\/documentation\/automixiq","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/automaticallyLogPlayback()":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticallyLogPlayback"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/automaticallyLogPlayback()","abstract":[{"text":"Called by AutomixIQ to learn if it should log playback events to Tuned’s backend on your behalf or if you will implement logging yourself.","type":"text"}],"kind":"symbol","title":"automaticallyLogPlayback()","navigatorTitle":[{"kind":"identifier","text":"automaticallyLogPlayback"}],"required":true,"url":"\/documentation\/automixiq\/tunedrestdelegate\/automaticallylogplayback()"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/uniqueDeviceIdentifier()":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uniqueDeviceIdentifier","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ to request the unique identifier for the users device as a string."},{"type":"text","text":" "},{"type":"text","text":"On iOS this is generally the Identifier for Vendor."},{"type":"text","text":" "},{"type":"text","text":"It can be any string as long as it is unique"},{"type":"text","text":" "},{"type":"text","text":"AutomixIQ will use this string as the UniqueId if it needs to register the device for playback"}],"title":"uniqueDeviceIdentifier()","type":"topic","url":"\/documentation\/automixiq\/tunedrestdelegate\/uniquedeviceidentifier()","navigatorTitle":[{"text":"uniqueDeviceIdentifier","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/uniqueDeviceIdentifier()","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tunedRestTokenExpired"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"oldAccessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tokenType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"credentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)TunedAuthenticationResponse","text":"TunedAuthenticationResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedUserId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:)","abstract":[{"type":"text","text":"Called by AutomixIQ when initialised against a Tuned Global backend or when its access token has expired."}],"kind":"symbol","title":"tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:)","navigatorTitle":[{"kind":"identifier","text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:"}],"required":true,"url":"\/documentation\/automixiq\/tunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:tokentype:completion:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"TunedRestDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/automaticallyLogPlayback()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/logAutomixIQMessage(logLevel:message:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/uniqueDeviceIdentifier()"],"anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Initializing AutomixIQ for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQMusicCacheDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixIQConfig"],"anchor":"Initializing-AutomixIQ-for-use-with-Tuned-Globals-APIs","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"logAutomixIQMessageWithLogLevel:message:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logAutomixIQMessageWithLogLevel:message:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1logAutomixIQMessage(logLevel:message:)\/fragments"},{"value":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetAuthenticatedDeviceWithDeviceIdentifierForVendor:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1asyncGetAuthenticatedDevice(deviceIdentifierForVendor:completion:)\/fragments"},{"value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments"},{"op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQMusicCacheDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/title"},{"op":"replace","value":[{"text":"AutomixIQMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQMusicCacheDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQMusicCacheDelegate\/navigatorTitle"},{"op":"replace","value":"AutomixIQConfig","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixIQConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixIQConfig\/navigatorTitle"},{"value":"automaticallyLogPlayback","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1automaticallyLogPlayback()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"automaticallyLogPlayback"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1automaticallyLogPlayback()\/fragments","op":"replace"},{"value":"uniqueDeviceIdentifier","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1uniqueDeviceIdentifier()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"uniqueDeviceIdentifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1uniqueDeviceIdentifier()\/fragments","op":"replace"},{"value":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:tokenType:completion:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}