{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradioobjc\/initialise(with:tunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialise(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","text":"SocialRadioConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedRestDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","text":"SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil)"}],"languages":["swift"]},{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","text":"SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"text":"SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC"]]},"metadata":{"title":"initialise(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","modules":[{"name":"SocialRadio"}],"symbolKind":"method","externalID":"c:objc(cs)SocialRadioObjC(cm)initialiseWithConfig:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:","role":"symbol","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","kind":"typeIdentifier","text":"SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"SocialRadioStatusObserverDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"text":"socialRadioUIDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"SocialRadioUIDelegate","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"sections":[],"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioObjC"}],"url":"\/documentation\/socialradio\/socialradioobjc","title":"SocialRadioObjC","kind":"symbol","navigatorTitle":[{"text":"SocialRadioObjC","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC","type":"topic","abstract":[]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioUIDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocialRadioUIDelegate"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"abstract":[{"text":"SocialRadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features.","type":"text"}],"title":"SocialRadioUIDelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioUIDelegate","url":"\/documentation\/socialradio\/socialradiouidelegate","role":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"type":"topic","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"url":"\/documentation\/socialradio","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","title":"SocialRadio"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioObjC/initialise(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)":{"url":"\/documentation\/socialradio\/socialradioobjc\/initialise(with:tunedrestdelegate:socialradiostatusdelegate:socialradiouidelegate:completion:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioObjC\/initialise(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","title":"initialise(with:tunedRestDelegate:socialRadioStatusDelegate:socialRadioUIDelegate:completion:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@SocialRadio@objc(cs)SocialRadioConfig","kind":"typeIdentifier","text":"SocialRadioConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedRestDelegate"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@SocialRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"socialRadioStatusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioStatusObserverDelegate","text":"SocialRadioStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialRadioUIDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SocialRadio@objc(pl)SocialRadioUIDelegate","text":"SocialRadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"kind":"symbol"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioConfig":{"kind":"symbol","role":"symbol","title":"SocialRadioConfig","type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioConfig","kind":"identifier"}],"navigatorTitle":[{"text":"SocialRadioConfig","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioConfig holds the variables to initialise SocialRadio and describe the desired feature set and UI"}],"url":"\/documentation\/socialradio\/socialradioconfig"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioStatusObserverDelegate":{"url":"\/documentation\/socialradio\/socialradiostatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioStatusObserverDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SocialRadioStatusObserverDelegate"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/TunedRestDelegate":{"abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/TunedRestDelegate","role":"symbol","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"type":"topic","kind":"symbol","url":"\/documentation\/socialradio\/tunedrestdelegate","title":"TunedRestDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/title","value":"SocialRadioUIDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/fragments","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioUIDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioUIDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/title","value":"SocialRadioConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/fragments","value":[{"text":"SocialRadioConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/title","value":"SocialRadioStatusObserverDelegate","op":"replace"},{"op":"replace","value":[{"text":"SocialRadioStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SocialRadioStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioStatusObserverDelegate\/navigatorTitle"},{"op":"replace","value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/title"},{"op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/fragments"},{"op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1TunedRestDelegate\/navigatorTitle"}]}]}