{"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"SocialRadio"}],"title":"mixPlays","navigatorTitle":[{"kind":"identifier","text":"mixPlays"}],"role":"symbol","externalID":"c:@M@SocialRadio@objc(cs)SocialRadioMixtapeCounters(py)mixPlays","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlays","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeCounters"]]},"identifier":{"url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeCounters\/mixPlays","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlays"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The number of times this mixtape has been played","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiomixtapecounters\/mixplays"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiomixtapecounters\/mixplays"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeCounters/mixPlays":{"url":"\/documentation\/socialradio\/socialradiomixtapecounters\/mixplays","abstract":[{"type":"text","text":"The number of times this mixtape has been played"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeCounters\/mixPlays","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlays","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","title":"mixPlays","type":"topic","navigatorTitle":[{"text":"mixPlays","kind":"identifier"}]},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioMixtapeCounters":{"kind":"symbol","title":"SocialRadioMixtapeCounters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioMixtapeCounters","navigatorTitle":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}],"abstract":[{"type":"text","text":"SocialRadioMixtapeCounters models the set of counters for information about a mixtape"}],"url":"\/documentation\/socialradio\/socialradiomixtapecounters","type":"topic"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio","abstract":[{"text":"Broadcast your playlist, mix, or voice to the world.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mixPlays"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mixPlays"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlays"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeCounters~1mixPlays\/title","value":"mixPlays"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeCounters~1mixPlays\/fragments","value":[{"text":"mixPlays","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeCounters\/title","value":"SocialRadioMixtapeCounters"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeCounters\/fragments","value":[{"text":"SocialRadioMixtapeCounters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioMixtapeCounters\/navigatorTitle","value":[{"kind":"identifier","text":"SocialRadioMixtapeCounters"}]}]}]}