{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel\/init","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixsdkwaveformmodel\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKWaveformModel(im)init","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKWaveformModel":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel","url":"\/documentation\/automixiq\/automixsdkwaveformmodel","kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"title":"AutomixSDKWaveformModel","navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKWaveformModel/init":{"url":"\/documentation\/automixiq\/automixsdkwaveformmodel\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic","kind":"symbol","title":"init","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","title":"AutomixIQ","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/title","value":"AutomixSDKWaveformModel"},{"value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}