{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/socialradio\/socialradiopluginmetadatamodel\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/socialradio\/socialradiopluginmetadatamodel\/type"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"`Type`","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPluginMetadataModel"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The Type of metadata described by this object, examples: “key”, “bpm”","type":"text"}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"SocialRadio"}],"role":"symbol","symbolKind":"property","title":"Type","roleHeading":"Instance Property","navigatorTitle":[{"text":"Type","kind":"identifier"}],"externalID":"c:@M@SocialRadio@objc(cs)SocialRadioPluginMetadataModel(py)Type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`Type`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPluginMetadataModel\/Type"},"references":{"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPluginMetadataModel/Type":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"`Type`"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/socialradio\/socialradiopluginmetadatamodel\/type","role":"symbol","navigatorTitle":[{"text":"Type","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPluginMetadataModel\/Type","kind":"symbol","abstract":[{"text":"The Type of metadata described by this object, examples: “key”, “bpm”","type":"text"}],"title":"Type"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio/SocialRadioPluginMetadataModel":{"type":"topic","url":"\/documentation\/socialradio\/socialradiopluginmetadatamodel","abstract":[{"text":"SocialRadioPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio\/SocialRadioPluginMetadataModel","navigatorTitle":[{"kind":"identifier","text":"SocialRadioPluginMetadataModel"}],"role":"symbol","kind":"symbol","title":"SocialRadioPluginMetadataModel"},"doc://org.cocoapods.SocialRadio/documentation/SocialRadio":{"kind":"symbol","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.SocialRadio\/documentation\/SocialRadio","url":"\/documentation\/socialradio","type":"topic","title":"SocialRadio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"Type"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Type"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"Type"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPluginMetadataModel~1Type\/title","op":"replace","value":"Type"},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPluginMetadataModel~1Type\/fragments","op":"replace","value":[{"text":"Type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPluginMetadataModel\/title","value":"SocialRadioPluginMetadataModel","op":"replace"},{"value":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPluginMetadataModel\/fragments","op":"replace"},{"value":[{"text":"SocialRadioPluginMetadataModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SocialRadio~1documentation~1SocialRadio~1SocialRadioPluginMetadataModel\/navigatorTitle"}]}]}